<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="sysIFManagerService">

    <select id="getIFManagerHeaderList" resultType="SysIFManagerResDto">
      SELECT /* [SysIFManagerService.sqlx][getIFManagerHeaderList][인터페이스 상태관리 조회][JiSooKim][2025.07.17] */
      		  '' AS CHECKYN
		       , T.TARGETSYSTEM 
		       , T.IF_ID
		       , T.IF_NAME
		       , T.DEL_YN
		       , T.DEL_YN 		AS ORG_DEL_YN
		       , T.STATUS
		       , T.STATUS 		AS ORG_STATUS
		       , T.STARTDATE
		       , T.ENDDATE
		       , T.LASTRUN
		       , T.REALTYPE
		       , T.SYNCTYPE
		       , T.METHOD
		       , T.EAI_MNG_YN
		    FROM  (
		            SELECT TARGETSYSTEM 
		                 , IF_ID
		                 , IF_NAME
		                 , DEL_YN
		                 , STATUS
		                 , to_char(STARTDATE, 'yyyy-mm-dd hh24:mi:ss') 		AS STARTDATE
		                 , to_char(ENDDATE, 'yyyy-mm-dd hh24:mi:ss') 		AS ENDDATE
		                 , to_char(LASTRUN, 'yyyy-mm-dd hh24:mi:ss') 		AS LASTRUN
		                 , REALTYPE
		                 , SYNCTYPE
		                 , METHOD
		                 , CASE WHEN SOURCESYSTEM = 'LOGISONE'
		                            AND TARGETSYSTEM not in ('LOGISONE', 'SAP(AS-IS)') THEN 'Y'
		                        ELSE 'N'
		                   END 												AS EAI_MNG_YN
		              FROM   IF_MASTER
		              WHERE  1=1
		                <if test="ifId != null and ifId != ''">
		                  AND if_id = #{ifId}
		                </if>
		          ) T
		    WHERE 1=1
		      <if test="eaiMngChYn == 1">
		        AND T.EAI_MNG_YN = 'Y'
		      </if>
		    ORDER BY TARGETSYSTEM, IF_ID
    </select>
    
    <update id="updateIFManager">
    	UPDATE /* [SysIFManagerService.sqlx][updateIFManager][인터페이스 상태관리 저장][JiSooKim][2025.08.01] */
    		   IF_MASTER
        SET    DEL_YN = CASE WHEN DEL_YN = #{orgDelYn} THEN #{delYn}
                             ELSE DEL_YN
                        END /*조회이후 상태가 변경된 경우에는 사용자 요청을 무시하도록 처리*/
              ,STATUS = CASE WHEN STATUS = #{orgStatus} THEN #{status}
                             ELSE STATUS
                        END /*조회이후 상태가 변경된 경우에는 사용자 요청을 무시하도록 처리*/
              ,EDITDATE = sysdate
              ,EDITWHO  = #{gUserId}
		WHERE  IF_ID = #{ifId}
    
    </update>
    
    
</mapper>