<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="sysProgramService">

	<select id="getProgramList" resultType="SysProgramResDto">
        SELECT /* [SysProgramService.sqlx][getProgramList][프로그램 목록 검색 조회][JGS][2025.04.29] */
		     PROG_CD 						/* 프로그램코드 */      
		    ,PROG_NM 						/* 프로그램명 */      
		    ,SYSTEM_CL 						/* 시스템구분 */   
		    ,PROG_LVL 						/* 프로그램레벨 */     
		    ,PROG_NO 						/* 프로그램내부순번 */      
		    ,PROG_URL 						/* 프로그램URL */     
		    ,PROG_ARGS 						/* 프로그램 파라미터 */     
		    ,PROG_OPTS 						/* 프로그램 옵션 */     
		    ,AUTHORITY 						/* 권한코드 */     
		    ,AUTHORITY AS AUTHORITY_OLD 	/* 권한코드 */
		    ,PROGHELP_URL 					/* 프로그램 도움말 URL */ 
		    ,MENU_YN 						/* 메뉴여부 */   
		    ,TOPMENU_YN 					/* 상위메뉴여부 */
		    ,BTN1_NM 						/* 사용자버튼1 */      
		    ,BTN2_NM 						/* 사용자버튼2 */      
		    ,BTN3_NM 						/* 사용자버튼3 */      
		    ,BTN4_NM 						/* 사용자버튼4 */      
		    ,BTN5_NM 						/* 사용자버튼5 */      
		    ,BTN6_NM 						/* 사용자버튼6 */      
		    ,BTN7_NM 						/* 사용자버튼7 */       
		    ,BTN8_NM 						/* 사용자버튼8 */      
		    ,BTN9_NM 						/* 사용자버튼9 */      
		    ,BTN10_NM 						/* 사용자버튼10 */       
		    ,USE_YN 						/* 사용여부 */ 
		    ,PROG_CD AS ROW_ID 				/* 프로그램코드 rowid */
		    ,REG_ID 						/* 등록자ID */
		    ,UPD_ID 						/* 수정자ID */
		FROM FRAMEONE_PROGRAM
		WHERE 1 = 1
			<if test='systemCl != null and systemCl != ""'>
				AND SYSTEM_CL = #{systemCl}
			</if>
		ORDER BY PROG_NO
    </select>
    
	<select id="insertProgram" statementType="CALLABLE">
		<![CDATA[ 
	    {
	    	CALL /* [SysProgramService.sqlx][insertProgram][프로그램정보 등록][JGS][2025.04.29] */
	    	DECLARE 
	        	V_AFTER		FRAMEONE_PROGRAM%rowtype; 
	            O_SUCCESS   NUMBER  					:=  1;		/* 성공여부(사용하지 않음) */ 
	            O_ERRCODE   NUMBER  					:=  0;		/* 오류 코드(0이면 성공) */ 
	            O_ERRMSG    VARCHAR2(4000) 				:= '';		/* 오류 메세지 */ 
	            SQL_ERROR 	EXCEPTION;
	        BEGIN 		
	        	BEGIN			 
	                V_AFTER.PROG_CD 		:= #{progCd};
	                V_AFTER.PROG_NM 		:= #{progNm};
	                V_AFTER.SYSTEM_CL 		:= #{systemCl};
	                V_AFTER.PROG_LVL 		:= #{progLvl};
	                V_AFTER.PROG_NO 		:= #{progNo};
	                V_AFTER.PROG_URL 		:= #{progUrl};
	                V_AFTER.PROG_ARGS 		:= #{progArgs};
	                V_AFTER.PROG_OPTS 		:= #{progOpts};
	                V_AFTER.AUTHORITY 		:= #{authority};
	                V_AFTER.PROGHELP_URL 	:= #{proghelpUrl};
	                V_AFTER.MENU_YN 		:= #{menuYn};
	                V_AFTER.TOPMENU_YN 		:= #{topmenuYn};
	                V_AFTER.BTN1_NM 		:= #{btn1Nm};
	                V_AFTER.BTN2_NM 		:= #{btn2Nm};
	                V_AFTER.BTN3_NM 		:= #{btn3Nm};
	                V_AFTER.BTN4_NM 		:= #{btn4Nm};
	                V_AFTER.BTN5_NM 		:= #{btn5Nm};
	                V_AFTER.BTN6_NM 		:= #{btn6Nm};
	                V_AFTER.BTN7_NM 		:= #{btn7Nm};
	                V_AFTER.BTN8_NM 		:= #{btn8Nm};
	                V_AFTER.BTN9_NM 		:= #{btn9Nm};
	                V_AFTER.BTN10_NM 		:= #{btn10Nm};
	                V_AFTER.USE_YN 			:= #{useYn};
	                V_AFTER.REG_ID 			:= #{regId};
	                V_AFTER.REG_DTM 		:= SYSDATE;
	                V_AFTER.UPD_ID 			:= #{updId};
	                V_AFTER.UPD_DTM 		:= SYSDATE;
	 
	                TRFRAMEONE_PROGRAM.TR_INSERT (
	                   	 V_AFTER 
	                    ,O_SUCCESS 
	                    ,O_ERRCODE 
	                    ,O_ERRMSG 
	                );
	                
	                IF O_ERRCODE = -20001 THEN
	                	RAISE_APPLICATION_ERROR (-20001, NVL(O_ERRMSG, SQLERRM));
	                ELSIF O_ERRCODE != 0 THEN
					    RAISE SQL_ERROR;
		            END IF;
			        
			        EXCEPTION WHEN OTHERS THEN
			        	O_ERRCODE := SQLCODE;
						O_ERRMSG := NVL(O_ERRMSG, SQLERRM);
			    END;
			    
			    #{success, 	mode=OUT, jdbcType=INTEGER, javaType=int}		:=  O_SUCCESS;
				#{errCode, 	mode=OUT, jdbcType=INTEGER, javaType=int}		:=  O_ERRCODE;
				#{errMsg, 	mode=OUT, jdbcType=VARCHAR, javaType=String}  	:=  O_ERRMSG;
		    END
	    } 
	    ]]>
    </select>
    
	<select id="updateProgram" statementType="CALLABLE">
		<![CDATA[
	    {
	    	CALL /*[SysProgramService.sqlx][updateProgram][프로그램정보 등록][JGS][2025.04.29]*/
	    	DECLARE
	        	V_AFTER		FRAMEONE_PROGRAM%rowtype;
	            O_SUCCESS   NUMBER  					:=  1;		/* 성공여부(사용하지 않음) */
	            O_ERRCODE   NUMBER  					:=  0;		/* 오류 코드(0이면 성공) */
	            O_ERRMSG    VARCHAR2(4000) 				:= '';		/* 오류 메세지 */
	            SQL_ERROR 	EXCEPTION;
	        BEGIN
	        	BEGIN
		        	SELECT  *
	                INTO    V_AFTER
	                FROM    FRAMEONE_PROGRAM
	                WHERE   PROG_CD = #{progCd};
	                    				 
	                V_AFTER.PROG_NM 		:= #{progNm};
	                V_AFTER.PROG_LVL 		:= #{progLvl};
	                V_AFTER.PROG_NO 		:= #{progNo};
	                V_AFTER.PROG_URL 		:= #{progUrl};
	                V_AFTER.PROG_ARGS 		:= #{progArgs};
	                V_AFTER.PROG_OPTS 		:= #{progOpts};
	                V_AFTER.AUTHORITY 		:= #{authority};
	                V_AFTER.PROGHELP_URL 	:= #{proghelpUrl};
	                V_AFTER.MENU_YN 		:= #{menuYn};
	                V_AFTER.TOPMENU_YN 		:= #{topmenuYn};
	                V_AFTER.BTN1_NM 		:= #{btn1Nm};
	                V_AFTER.BTN2_NM 		:= #{btn2Nm};
	                V_AFTER.BTN3_NM 		:= #{btn3Nm};
	                V_AFTER.BTN4_NM 		:= #{btn4Nm};
	                V_AFTER.BTN5_NM 		:= #{btn5Nm};
	                V_AFTER.BTN6_NM 		:= #{btn6Nm};
	                V_AFTER.BTN7_NM 		:= #{btn7Nm};
	                V_AFTER.BTN8_NM 		:= #{btn8Nm};
	                V_AFTER.BTN9_NM 		:= #{btn9Nm};
	                V_AFTER.BTN10_NM 		:= #{btn10Nm};
	                V_AFTER.USE_YN 			:= #{useYn};
	                V_AFTER.UPD_ID 			:= #{updId};
	                V_AFTER.UPD_DTM 		:= SYSDATE;
	 
	                TRFRAMEONE_PROGRAM.TR_UPDATE (
	                   	 V_AFTER
	                    ,O_SUCCESS
	                    ,O_ERRCODE
	                    ,O_ERRMSG
	                );
	                
	                IF O_ERRCODE = -20001 THEN
	                	RAISE_APPLICATION_ERROR (-20001, NVL(O_ERRMSG, SQLERRM));
	                ELSIF O_ERRCODE != 0 THEN
					    RAISE SQL_ERROR;
		            END IF;
			        
			        EXCEPTION WHEN OTHERS THEN
			        	O_ERRCODE := SQLCODE;
						O_ERRMSG := NVL(O_ERRMSG, SQLERRM);
		        END;
                
                #{success, 	mode=OUT, jdbcType=INTEGER, javaType=int}		:=  O_SUCCESS;
				#{errCode, 	mode=OUT, jdbcType=INTEGER, javaType=int}		:=  O_ERRCODE;
				#{errMsg, 	mode=OUT, jdbcType=VARCHAR, javaType=String}  	:=  O_ERRMSG;
	        END
	    }
	    ]]>
    </select>
    
	<delete id="deleteProgram">
        DELETE /* [SysProgramService.sqlx][deleteProgram][프로그램정보 삭제][JGS][2025.04.29] */ FRAMEONE_PROGRAM
        WHERE PROG_CD = #{progCd}
    </delete>
    
</mapper>