package cjfw.batch.shr0130.soap;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebServiceClient(name = "SI_SHR0130_EAI_SOService",
                  wsdlLocation = "wsdl/SI_SHR0130_EAI_SOService.wsdl",
                  targetNamespace = "urn://shr.cjfreshway.co.kr/COMM")
public class SISHR0130EAISOService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn://shr.cjfreshway.co.kr/COMM", "SI_SHR0130_EAI_SOService");
    public final static QName HTTPSPort = new QName("urn://shr.cjfreshway.co.kr/COMM", "HTTPS_Port");
    public final static QName HTTPPort = new QName("urn://shr.cjfreshway.co.kr/COMM", "HTTP_Port");
    static {
        URL url = SISHR0130EAISOService.class.getResource("wsdl/SI_SHR0130_EAI_SOService.wsdl");
        if (url == null) {
            url = SISHR0130EAISOService.class.getClassLoader().getResource("wsdl/SI_SHR0130_EAI_SOService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(SISHR0130EAISOService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "wsdl/SI_SHR0130_EAI_SOService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SISHR0130EAISOService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SISHR0130EAISOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SISHR0130EAISOService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SISHR0130EAISOService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SISHR0130EAISOService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SISHR0130EAISOService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SISHR0130EAISO
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISHR0130EAISO getHTTPSPort() {
        return super.getPort(HTTPSPort, SISHR0130EAISO.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISHR0130EAISO
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISHR0130EAISO getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SISHR0130EAISO.class, features);
    }


    /**
     *
     * @return
     *     returns SISHR0130EAISO
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISHR0130EAISO getHTTPPort() {
        return super.getPort(HTTPPort, SISHR0130EAISO.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISHR0130EAISO
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISHR0130EAISO getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SISHR0130EAISO.class, features);
    }

}
