package cjfw.batch.shr0130.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "urn://shr.cjfreshway.co.kr/COMM", name = "SI_SHR0130_EAI_SO")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SISHR0130EAISO {

    @WebMethod(operationName = "SI_SHR0130_EAI_SO", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_SHR0130_EAI_response", targetNamespace = "urn://shr.cjfreshway.co.kr/COMM", partName = "MT_SHR0130_EAI_response")
    public DTSHR0130EAIResponse siSHR0130EAISO(

        @WebParam(partName = "MT_SHR0130_EAI", name = "MT_SHR0130_EAI", targetNamespace = "urn://shr.cjfreshway.co.kr/COMM")
        DTSHR0130EAI mtSHR0130EAI
    );
}
