<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" 
"http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="commonPaging">
	<sql id="header">
        SELECT PAGE_T2.* 
          FROM( 
               SELECT ROWNUM AS RNUM
                    , PAGE_T1.* 
                FROM( 
	</sql>
	
	<sql id="footer">
                    )PAGE_T1
               WHERE ROWNUM <![CDATA[<=]]> #{END_ROW} 
              )PAGE_T2
         WHERE RNUM >= #{START_ROW}
	</sql>
</mapper>