<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="stAdjustmentRequestService">

    <select id="getZoneList" resultType="StAdjustmentCommCdResDto">
        SELECT /* [StAdjustmentRequestService.sqlx][stAdjustmentRequestService.getZoneList][일괄재고 zone 목록 조회][JiHoPark][2025.09.25] */
               DCCODE AS DCCODE
             , ZONE   AS COM_CD
             , ZONE   AS CD_NM
		  FROM MS_ZONE
         WHERE 1=1
           AND DEL_YN = 'N'
         ORDER BY ZONE ASC
    </select>

    <select id="getMasterList" resultType="StAdjustmentRequestResDto">
        SELECT /* [StAdjustmentRequestService.sqlx][stAdjustmentRequestService.getMasterList][재고조정 요청 목록 조회][JiHoPark][2025.10.10] */
               ST_STOCK.DCCODE                                                                                                        AS DCCODE
             , ST_STOCK.STORERKEY                                                                                                     AS STORERKEY
             , ST_STOCK.ORGANIZE                                                                                                      AS ORGANIZE
             , ST_STOCK.AREA                                                                                                          AS AREA
             , FN_CODEDESCR(ST_STOCK.STORERKEY, 'STOCKTYPE', ST_STOCK.STOCKTYPE)                                                      AS STOCKTYPENM
             , ST_STOCK.STOCKTYPE                                                                                                     AS STOCKTYPE
             , ST_STOCK.STOCKGRADE                                                                                                    AS STOCKGRADE
             , FN_CODEDESCR(ST_STOCK.STORERKEY, 'STOCKGRADE', ST_STOCK.STOCKGRADE)                                                    AS STOCKGRADENAME
             , MS_LOCATION.ZONE                                                                                                       AS ZONE
             , ST_STOCK.LOC                                                                                                           AS LOC
             , ST_STOCK.SKU                                                                                                           AS SKU
             , MS_SKU.DESCRIPTION                                                                                                     AS SKUNAME
             , ST_STOCK.LOT                                                                                                           AS LOT
             , ST_STOCK.UOM                                                                                                           AS UOM
             , ST_STOCK.QTY                                                                                                           AS QTY
             , ST_STOCK.OPENQTY                                                                                                       AS OPENQTY
             , ST_STOCK.QTYALLOCATED                                                                                                  AS QTYALLOCATED
             , ST_STOCK.QTYPICKED                                                                                                     AS QTYPICKED
             , ''                                                                                                                     AS TRANQTY
             , ''                                                                                                                     AS REASONCODE
             , ''                                                                                                                     AS REASONMSG
             , ''                                                                                                                     AS DECREASETYPE
             , ''                                                                                                                     AS IMPUTETYPE
             , ''                                                                                                                     AS PROCESSMAIN
             , ''                                                                                                                     AS COSTCD
             , ''                                                                                                                     AS COSTCDNAME
             , ''                                                                                                                     AS CUSTKEY
             , ''                                                                                                                     AS CUSTNAME
             , NVL(TRIM(FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'Y')),'N') AS NEARDURATIONYN /** 유통기한임박여부 */
             , CM_LOT.LOTTABLE01                                                                                                      AS LOTTABLE01
             /*
              * 기준일(제조) ~까지 : DURATIONTYPE = 1 일때 LOTTABLE01 - DURATION
              *                  DURATIONTYPE = 2 일때 LOTTABLE01
              * 기준일(소비) ~부터 : DURATIONTYPE = 1 일때 LOTTABLE01
              *                  DURATIONTYPE = 2 일때 LOTTABLE01 + DURATION  -1
              */
              --
              ,LOGISONESVC.FN_LOTTABLE_INFO('1',ST_STOCK.STORERKEY,CM_LOT.LOTTABLE01,MS_SKU.DURATIONTYPE,MS_SKU.DURATION,'')             AS MANUFACTUREDT   /*제조일자*/
              ,LOGISONESVC.FN_LOTTABLE_INFO('2',ST_STOCK.STORERKEY,CM_LOT.LOTTABLE01,MS_SKU.DURATIONTYPE,MS_SKU.DURATION,'')             AS EXPIREDT        /*소비일자*/
              --              
             , FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'N0') ||'/'|| MS_SKU.DURATION AS DURATION_TERM
             , ST_STOCK.STOCKID                                                                                                       AS STOCKID
             , ST_SNINFO.SERIALNO                                                                                                     AS SERIALNO
             , ST_SNINFO.CONVSERIALNO                                                                                                 AS CONVSERIALNO
             , ST_SNINFO.SERIALLEVEL                                                                                                  AS SERIALLEVEL
             , ST_SNINFO.SERIALTYPE                                                                                                   AS SERIALTYPE
             , ST_SNINFO.FACTORYNAME                                                                                                  AS FACTORYNAME
             , MS_SKU.COLORDESCR                                                                                                      AS COLORDESCR
             , ST_SNINFO.PLACEOFORIGIN                                                                                                AS PLACEOFORIGIN
             , DECODE(ST_STOCK.STOCKTYPE,'GOOD','DDGA','BAD','DDBA',ST_STOCK.STOCKTYPE)                                               AS ORDERTYPE
             , MS_SKU.DURATION                                                                                                        AS DURATION
             , MS_SKU.DURATIONTYPE                                                                                                    AS DURATIONTYPE
             , ST_SNINFO.BUTCHERYDT                                                                                                   AS BUTCHERYDT
             , ST_SNINFO.CONTRACTCUSTKEY                                                                                              AS CONTRACTCOMPANY
             , (SELECT DESCRIPTION
                  FROM MS_CUST
                 WHERE MS_CUST.STORERKEY = ST_SNINFO.STORERKEY
                   AND MS_CUST.CUSTKEY   = ST_SNINFO.CONTRACTCUSTKEY
                   AND ROWNUM            = 1 )                                                                                        AS CONTRACTCOMPANYNAME
             , ST_SNINFO.FROMVALIDDT                                                                                                  AS FROMVALIDDT
             , ST_SNINFO.TOVALIDDT                                                                                                    AS TOVALIDDT
             , FN_CODEDESCR(ST_STOCK.STORERKEY,'CONTRACTTYPE_SN', ST_SNINFO.CONTRACTTYPE)                                             AS CONTRACTTYPE
             , ST_SNINFO.STOCKID                                                                                                      AS BARCODE
             , (SELECT ST_STOCK_SERIALINFODETAIL.POLINE
                  FROM ST_STOCK_SERIALINFODETAIL
                 WHERE ST_STOCK_SERIALINFODETAIL.STOCKID = ST_STOCK.STOCKID
                   AND ROWNUM                            = 1)                                                                         AS POLINE
             , '<![CDATA[<]]>SERIALNO<![CDATA[>]]>'||ST_SNINFO.SERIALNO||'<![CDATA[<]]>/SERIALNO<![CDATA[>]]>'
               ||'<![CDATA[<]]>CONVSERIALNO<![CDATA[>]]>'||ST_SNINFO.CONVSERIALNO||'<![CDATA[<]]>/CONVSERIALNO<![CDATA[>]]>'
               ||'<![CDATA[<]]>POLINE<![CDATA[>]]>'||(SELECT ST_STOCK_SERIALINFODETAIL.POLINE
                                FROM ST_STOCK_SERIALINFODETAIL
                               WHERE ST_STOCK_SERIALINFODETAIL.STOCKID = ST_STOCK.STOCKID
                                 AND ROWNUM                            = 1)||'<![CDATA[<]]>/POLINE<![CDATA[>]]>'
               ||'<![CDATA[<]]>CUTKEY<![CDATA[>]]>'||ST_SNINFO.CONTRACTCUSTKEY||'<![CDATA[<]]>/CUTKEY<![CDATA[>]]>'                   AS OTHER03
             , CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 AND ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN TO_NUMBER(NVL(MS_SKU.LINE02,0))
                    ELSE 0
                END                                                                                                                   AS AVGWEIGHT       /* 평균중량    */
             , ROUND(CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 AND ST_STOCK.DCCODE = '2170'AND NVL(MS_SKU.LINE01,'N') = 'Y'
                          THEN (ST_STOCK.OPENQTY) / TO_NUMBER(NVL(MS_SKU.LINE02,0))
                          ELSE 0
                      END, 2)                                                                                                         AS CALBOX          /* 환산박스    */
             , CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN NVL(ST_STOCK.BOXQTY,0)
                    ELSE 0
                END                                                                                                                   AS REALORDERBOX    /* 실박스예정 */
             , CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN NVL(ST_STOCK.BOXQTY,0)
                    ELSE 0
                END                                                                                                                   AS REALCFMBOX      /* 실박스확정 */
             , '0'                                                                                                                    AS TRANBOX         /* 작업박스    */
             , CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN 'Y'
                    ELSE 'N'
                END                                                                                                                   AS BOXFLAG         /* 박스처리유무    */
             , MS_SKU.QTYPERBOX                                                                                                       AS QTYPERBOX
             , ''                                                                                                                     AS OTHER05
          FROM ST_STOCK
      <if test="fixdccode == null or fixdccode == ''">
          JOIN CM_USER_AUTHORITY ON CM_USER_AUTHORITY.USERID    = #{gUserId}
                            <if test="gDccode != null and gDccode != ''">
                                AND CM_USER_AUTHORITY.DCCODE    = #{gDccode}
                            </if>
                            <if test="gStorerkey != null and gStorerkey != ''">
                                AND CM_USER_AUTHORITY.STORERKEY = #{gStorerkey}
                            </if>
                            <if test="gOrganize != null and gOrganize != ''">
                                AND CM_USER_AUTHORITY.ORGANIZE  = #{gOrganize}
                            </if>
                            <if test="gArea != null and gArea != ''">
                                AND CM_USER_AUTHORITY.AREA      = #{gArea}
                            </if>
                            <!-- 창고 다중선택 -->
                            <if test="gMultiOrganize != null and gMultiOrganize != ''">
                                AND CM_USER_AUTHORITY.ORGANIZE IN (SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
                                                                     FROM (SELECT #{gMultiOrganize} AS VAL FROM DUAL) A
                                                                  CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
                            </if>
                                AND CM_USER_AUTHORITY.DCCODE    = ST_STOCK.DCCODE
                                AND CM_USER_AUTHORITY.STORERKEY = ST_STOCK.STORERKEY
                                AND CM_USER_AUTHORITY.ORGANIZE  = ST_STOCK.ORGANIZE
                                AND CM_USER_AUTHORITY.AREA      = ST_STOCK.AREA
                            </if>
          JOIN MS_SKU ON MS_SKU.STORERKEY = ST_STOCK.STORERKEY
                     AND MS_SKU.SKU       = ST_STOCK.SKU
                     AND MS_SKU.DEL_YN    = 'N'
                 <if test="storagetype != null and storagetype != ''">
                     AND MS_SKU.STORAGETYPE = #{storagetype}
                 </if>
                 <!-- 상품 다중선택 -->
                 <if test="sku != null and sku != ''">
                     AND MS_SKU.SKU IN (SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
                                          FROM (SELECT #{sku} AS VAL FROM DUAL) A
                                       CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
                 </if>
          JOIN CM_LOT ON CM_LOT.STORERKEY = ST_STOCK.STORERKEY
                     AND CM_LOT.LOT       = ST_STOCK.LOT
                     AND CM_LOT.DEL_YN    = 'N'
                 <if test="lottable01yn == 'Y'.toString()">
                     AND CM_LOT.LOTTABLE01 <![CDATA[<>]]>'STD'
                 </if>
                 <if test="lottable01yn == 'N'.toString()">
                     AND CM_LOT.LOTTABLE01 = 'STD'
                 </if>
          JOIN MS_LOCATION ON MS_LOCATION.DCCODE = ST_STOCK.DCCODE
                          AND MS_LOCATION.LOC    = ST_STOCK.LOC
                      <if test="fromloc != null and fromloc != ''">
                          AND MS_LOCATION.LOC <![CDATA[>=]]> #{fromloc}
                      </if>
                      <if test="toloc != null and toloc != ''">
                          AND MS_LOCATION.LOC <![CDATA[<=]]> #{toloc}
                      </if>
                      <if test="zone != null and zone != ''">
                          AND MS_LOCATION.ZONE = #{zone}
                      </if>
      <if test="serialnoyn != null and serialnoyn != ''">
          JOIN ST_SNINFO ON ST_STOCK.STORERKEY = ST_SNINFO.STORERKEY
                        AND ST_STOCK.SKU       = ST_SNINFO.SKU
                        AND ST_STOCK.STOCKID   = ST_SNINFO.STOCKID
                    <if test="serialno != null and serialno != ''">
                        AND ST_SNINFO.SERIALNO = #{serialno}
                    </if>
                    <if test="convserialno != null and convserialno != ''">
                        AND ST_SNINFO.CONVSERIALNO IN ( SELECT * FROM TABLE(FN_SPLIT_ARRAY(#{convserialno}) ))
                    </if>
                    <if test="contractcompany != null and contractcompany != ''">
                        AND ST_SNINFO.CONTRACTCUSTKEY = #{contractcompany}
                    </if>
      </if>
      <if test="serialnoyn == null or serialnoyn == ''">
          LEFT OUTER JOIN ST_SNINFO ON ST_STOCK.STORERKEY = ST_SNINFO.STORERKEY
                                   AND ST_STOCK.SKU       = ST_SNINFO.SKU
                                   AND ST_STOCK.STOCKID   = ST_SNINFO.STOCKID
                               <if test="serialno != null and serialno != ''">
                                   AND ST_SNINFO.SERIALNO = #{serialno}
                               </if>
                               <if test="convserialno != null and convserialno != ''">
                                   AND ST_SNINFO.CONVSERIALNO IN ( SELECT * FROM TABLE(FN_SPLIT_ARRAY(#{convserialno}) ))
                               </if>
                               <if test="contractcompany != null and contractcompany != ''">
                                   AND ST_SNINFO.CONTRACTCUSTKEY = #{contractcompany}
                               </if>
      </if>
         WHERE 1=1
           AND ST_STOCK.STOCKGRADE <![CDATA[<>]]> 'S3'
       <if test="gStorerkey != null and gStorerkey != ''">
           AND ST_STOCK.STORERKEY = #{gStorerkey}
       </if>
       <if test="fixdccode != null and fixdccode != ''">
           AND ST_STOCK.DCCODE    = #{fixdccode}
       </if>
       <!-- 창고 다중선택 -->
       <if test="organize != null and organize != ''">
           AND ST_STOCK.ORGANIZE IN (SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
                                            FROM (SELECT #{organize} AS VAL FROM DUAL) A
                                         CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
       </if>
       <if test="stocktype != null and stocktype != ''">
           AND ST_STOCK.STOCKTYPE  = #{stocktype}
       </if>
       <if test="stockgrade != null and stockgrade != ''">
           AND ST_STOCK.STOCKGRADE = #{stockgrade}
       </if>
       ORDER BY ST_STOCK.DCCODE
              , ST_STOCK.ORGANIZE
              , ST_STOCK.LOC
              , ST_STOCK.SKU
    </select>

    <select id="getMasterList2" resultType="StAdjustmentRequestResDto">
        SELECT /* [StAdjustmentRequestService.sqlx][stAdjustmentRequestService.getMasterList2][재고조정 결과 조회][JiHoPark][2025.10.10] */
               SY_PROCESSTEMP_AJ.DCCODE                                                                                     AS DCCODE
             , SY_PROCESSTEMP_AJ.STORERKEY                                                                                  AS STORERKEY
             , SY_PROCESSTEMP_AJ.ORGANIZE                                                                                   AS ORGANIZE
             , NVL(SY_PROCESSTEMP_AJ.STOCKTYPE, ST_STOCK.STOCKTYPE)                                                         AS STOCKTYPE
             , FN_CODEDESCR(SY_PROCESSTEMP_AJ.STORERKEY, 'STOCKTYPE', NVL(SY_PROCESSTEMP_AJ.STOCKTYPE, ST_STOCK.STOCKTYPE)) AS STOCKTYPENM
             , SY_PROCESSTEMP_AJ.STOCKGRADE                                                                                 AS STOCKGRADE
             , FN_CODEDESCR(SY_PROCESSTEMP_AJ.STORERKEY, 'STOCKGRADE', SY_PROCESSTEMP_AJ.STOCKGRADE)                        AS STOCKGRADENAME
             , SY_PROCESSTEMP_AJ.ZONE                                                                                       AS ZONE
             , SY_PROCESSTEMP_AJ.LOC                                                                                        AS LOC
             , SY_PROCESSTEMP_AJ.SKU                                                                                        AS SKU
             , MS_SKU.DESCRIPTION                                                                                           AS SKUNAME
             , NVL(SY_PROCESSTEMP_AJ.UOM, ST_STOCK.UOM)                                                                     AS UOM
             , SY_PROCESSTEMP_AJ.ORDERQTY                                                                                   AS QTY
             , SY_PROCESSTEMP_AJ.OPENQTY                                                                                    AS OPENQTY
             , SY_PROCESSTEMP_AJ.PROCESSQTY                                                                                 AS QTYALLOCATED
             , SY_PROCESSTEMP_AJ.WORKQTY                                                                                    AS QTYPICKED
             , SY_PROCESSTEMP_AJ.CONFIRMQTY                                                                                 AS TRANQTY
             , SY_PROCESSTEMP_AJ.TASKKEY                                                                                    AS REASONCODE
             , SY_PROCESSTEMP_AJ.WAVEKEY                                                                                    AS IMPUTETYPE
             , SY_PROCESSTEMP_AJ.INVOICENO                                                                                  AS PROCESSMAIN
             , SY_PROCESSTEMP_AJ.OTHER01                                                                                    AS COSTCD
             , SY_PROCESSTEMP_AJ.CUSTKEY                                                                                    AS CUSTKEY
             , SY_PROCESSTEMP_AJ.MIXBOXKEY                                                                                  AS LOTTABLE01
             , SY_PROCESSTEMP_AJ.LOT                                                                                        AS LOT
             , SY_PROCESSTEMP_AJ.STOCKID	                                                                                AS STOCKID
             , SY_PROCESSTEMP_AJ.AREA                                                                                       AS AREA
             , SY_PROCESSTEMP_AJ.PROCESSFLAG                                                                                AS PROCESSFLAG
             , SY_PROCESSTEMP_AJ.PROCESSMSG                                                                                 AS PROCESSMSG
             , ST_SNINFO.FACTORYNAME                                                                                        AS FACTORYNAME
             , ST_SNINFO.CONVSERIALNO                                                                                       AS CONVSERIALNO
             , ST_SNINFO.BUTCHERYDT                                                                                         AS BUTCHERYDT
             , ST_SNINFO.CONTRACTCUSTKEY                                                                                    AS CONTRACTCOMPANY
             , (SELECT DESCRIPTION
                  FROM MS_CUST
                 WHERE MS_CUST.STORERKEY = ST_SNINFO.STORERKEY
                   AND MS_CUST.CUSTKEY   = ST_SNINFO.CONTRACTCUSTKEY
                   AND ROWNUM            = 1)                                                                               AS CONTRACTCOMPANYNAME
             , ST_SNINFO.FROMVALIDDT                                                                                        AS FROMVALIDDT
             , ST_SNINFO.TOVALIDDT                                                                                          AS TOVALIDDT
             , FN_CODEDESCR(SY_PROCESSTEMP_AJ.STORERKEY,'CONTRACTTYPE_SN', ST_SNINFO.CONTRACTTYPE)                          AS CONTRACTTYPE
             , ST_SNINFO.STOCKID                                                                                            AS BARCODE
             , CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 AND ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN TO_NUMBER(NVL(MS_SKU.LINE02,0))
                    ELSE 0
                END                                                                                                         AS AVGWEIGHT       /* 평균중량    */
             , ROUND(CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 AND ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                          THEN (ST_STOCK.QTY - ST_STOCK.QTYALLOCATED - ST_STOCK.QTYPICKED) / TO_NUMBER(NVL(MS_SKU.LINE02,0))
                          ELSE 0
                      END, 2)                                                                                               AS CALBOX          /* 환산박스    */
             , CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN NVL(ST_STOCK.BOXQTY,0)
                    ELSE 0
                END                                                                                                         AS REALORDERBOX    /* 실박스예정 */
             , CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN NVL(ST_STOCK.BOXQTY,0)
                    ELSE 0
                END                                                                                                         AS REALCFMBOX      /* 실박스확정 */
             , SY_PROCESSTEMP_AJ.ETCQTY1                                                                                    AS TRANBOX         /* 작업박스    */
             , SY_PROCESSTEMP_AJ.OTHER05                                                                                    AS OTHER05         /* 비고    */
          FROM SY_PROCESSTEMP_AJ
          JOIN MS_SKU ON MS_SKU.STORERKEY = SY_PROCESSTEMP_AJ.STORERKEY
                     AND MS_SKU.SKU       = SY_PROCESSTEMP_AJ.SKU
                     AND MS_SKU.DEL_YN    = 'N'
          JOIN MS_LOCATION ON MS_LOCATION.DCCODE = SY_PROCESSTEMP_AJ.DCCODE
                          AND MS_LOCATION.LOC    = SY_PROCESSTEMP_AJ.LOC
          LEFT OUTER JOIN ST_STOCK ON ST_STOCK.STORERKEY  = SY_PROCESSTEMP_AJ.STORERKEY
                                  AND ST_STOCK.DCCODE     = SY_PROCESSTEMP_AJ.DCCODE
                                  AND ST_STOCK.ORGANIZE   = SY_PROCESSTEMP_AJ.ORGANIZE
                                  AND ST_STOCK.AREA       = SY_PROCESSTEMP_AJ.AREA
                                  AND ST_STOCK.SKU        = SY_PROCESSTEMP_AJ.SKU
                                  AND ST_STOCK.LOC        = SY_PROCESSTEMP_AJ.LOC
                                  AND ST_STOCK.LOT        = SY_PROCESSTEMP_AJ.LOT
                                  AND ST_STOCK.STOCKID    = SY_PROCESSTEMP_AJ.STOCKID
                                  AND ST_STOCK.STOCKGRADE = SY_PROCESSTEMP_AJ.STOCKGRADE
          LEFT OUTER JOIN CM_LOT ON CM_LOT.STORERKEY = ST_STOCK.STORERKEY
                                AND CM_LOT.LOT       = ST_STOCK.LOT
                                AND CM_LOT.DEL_YN    = 'N'
          LEFT OUTER JOIN ST_SNINFO ON SY_PROCESSTEMP_AJ.STORERKEY = ST_SNINFO.STORERKEY
                                   AND SY_PROCESSTEMP_AJ.SKU       = ST_SNINFO.SKU
                                   AND SY_PROCESSTEMP_AJ.STOCKID   = ST_SNINFO.STOCKID
        WHERE SY_PROCESSTEMP_AJ.PROCESSTYPE    = 'AJ_ADJUSTMENTREQ_DC'
          AND SY_PROCESSTEMP_AJ.PROCESSCREATOR = #{gUserId}
          AND SY_PROCESSTEMP_AJ.SPID           = #{gSpid}
        ORDER BY SY_PROCESSTEMP_AJ.DCCODE
               , SY_PROCESSTEMP_AJ.LOC
               , SY_PROCESSTEMP_AJ.STORERKEY
               , SY_PROCESSTEMP_AJ.SKU
    </select>

    <select id="getMasterList3" resultType="StAdjustmentRequestElectApprovalDto">
        SELECT /* [StAdjustmentRequestService.sqlx][stAdjustmentRequestService.getMasterList3][재고조정 결재 조회][JiHoPark][2025.10.16] */
               T1.*
          FROM ( SELECT AJ_INPLAN.DCCODE                                                                                                       AS DCCODE
                      , AJ_INPLAN.STORERKEY                                                                                                    AS STORERKEY
                      , AJ_INPLAN.ORGANIZE                                                                                                     AS ORGANIZE
                      , AJ_INPLAN.AREA                                                                                                         AS AREA
                      , AJ_INPLAN.DOCDT                                                                                                        AS DOCDT
                      , AJ_INPLAN.DOCNO                                                                                                        AS DOCNO
                      , AJ_INPLAN.DOCLINE                                                                                                      AS DOCLINE
                      , AJ_INPLAN.SLIPDT                                                                                                       AS SLIPDT
                      , AJ_INPLAN.SLIPNO                                                                                                       AS SLIPNO
                      , AJ_INPLAN.SLIPLINE                                                                                                     AS SLIPLINE
                      , AJ_INPLAN.SLIPTYPE                                                                                                     AS SLIPTYPE
                      , AJ_INPLAN.SKU                                                                                                          AS SKU
                      , MS_SKU.DESCRIPTION                                                                                                     AS SKUNAME
                      , AJ_INPLAN.UOM                                                                                                          AS UOM
                      , AJ_INPLAN.ORDERQTY                                                                                                     AS ORDERQTY
                      , AJ_INPLAN.OPENQTY                                                                                                      AS OPENQTY
                      , AJ_INPLAN.ORDERQTY                                                                                                     AS TRANQTY
                      , AJ_INPLAN.ORDERTYPE                                                                                                    AS ORDERTYPE
                      , DECODE(AJ_INPLAN.ORDERTYPE, 'KITAJ', AJ_INPLAN.OTHER03, NULL)                                                          AS PLANORDER
                      , AJ_INPLAN.IOTYPE                                                                                                       AS IOTYPE
                      , CASE WHEN AJ_INPLAN.ORDERTYPE = 'DDRAJ' OR AJ_INPLAN.ORDERTYPE = 'KITAJ'
                             THEN CASE WHEN AJ_INPLAN.IOTYPE = 'WD'
                                       THEN '감모'
                                       ELSE '역감모'
                                   END
                             ELSE '폐기'
                         END                                                                                                                   AS INQUIRYTYPENAME
                      , NVL(TRIM(FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'Y')),'N') AS NEARDURATIONYN /** 유통기한임박여부 */
                      , CM_LOT.LOTTABLE01                                                                                                      AS LOTTABLE01
                      /*
                      * 기준일(제조) ~까지 : DURATIONTYPE = 1 일때 LOTTABLE01 - DURATION
                      *                  DURATIONTYPE = 2 일때 LOTTABLE01
                      * 기준일(소비) ~부터 : DURATIONTYPE = 1 일때 LOTTABLE01
                      *                  DURATIONTYPE = 2 일때 LOTTABLE01 + DURATION  -1
                      */
		              --
		              ,LOGISONESVC.FN_LOTTABLE_INFO('1',MS_SKU.STORERKEY,CM_LOT.LOTTABLE01,MS_SKU.DURATIONTYPE,MS_SKU.DURATION,'')             AS MANUFACTUREDT   /*제조일자*/
		              ,LOGISONESVC.FN_LOTTABLE_INFO('2',MS_SKU.STORERKEY,CM_LOT.LOTTABLE01,MS_SKU.DURATIONTYPE,MS_SKU.DURATION,'')             AS EXPIREDT        /*소비일자*/
		              --                         
                      , FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'N0') ||'/'|| MS_SKU.DURATION AS DURATION_TERM
                      , FN_CODEDESCR(MS_SKU.STORERKEY, 'STORAGETYPE', MS_SKU.STORAGETYPE)                                                      AS STORAGETYPE
                      , MS_SKU.DURATION                                                                                                        AS DURATION
                      , MS_SKU.DURATIONTYPE                                                                                                    AS DURATIONTYPE
                      , 0                                                                                                                      AS STOCKAMT
                      , 0                                                                                                                      AS PRICE
                      , FN_CONV_UOM(AJ_INPLAN.STORERKEY, AJ_INPLAN.SKU, AJ_INPLAN.UOM, 'KG', AJ_INPLAN.ORDERQTY )                              AS WEIGHT
                      , AJ_INPLAN.REASONCODE                                                                                                   AS REASONCODE
                      , AJ_INPLAN.OTHER04                                                                                                      AS OTHER04
                      , MS_COST.DESCRIPTION                                                                                                    AS COSTCENTERNAME
                      , AJ_INPLAN.OTHER02	                                                                                                   AS OTHER02
                      , CASE WHEN AJ_INPLAN.ORDERTYPE = 'DDRAJ'
                             THEN FN_CODEDESCR(AJ_INPLAN.STORERKEY, 'DECREASETYPE', AJ_INPLAN.OTHER02)
                             WHEN AJ_INPLAN.ORDERTYPE = 'KITAJ'
                             THEN FN_CODEDESCR(AJ_INPLAN.STORERKEY, 'DECREASETYPE', 'KIT')
                             ELSE FN_CODEDESCR(AJ_INPLAN.STORERKEY, 'DISUSETYPE', AJ_INPLAN.OTHER02)
                         END                                                                                                                   AS APPROVALREASONNAME
                      , DECODE(MS_SKU.SERIALTYPE,'3',NULL,ST_SNINFO.SERIALNO)                                                                  AS SERIALNO
                      , ST_SNINFO.SERIALNO                                                                                                     AS SERIALNO_ORG
                      , ST_SNINFO.CONVSERIALNO                                                                                                 AS CONVSERIALNO
                      , ( SELECT ST_STOCK_SERIALINFODETAIL.POLINE
                            FROM ST_STOCK_SERIALINFODETAIL
                           WHERE ST_STOCK_SERIALINFODETAIL.STOCKID = ST_STOCK.STOCKID
                             AND ROWNUM                            = 1 )                                                                        AS POLINE
                      , ST_SNINFO.BUTCHERYDT                                                                                                   AS BUTCHERYDT
                      , ST_SNINFO.CONTRACTCUSTKEY                                                                                              AS CONTRACTCOMPANY
                      , ( SELECT DESCRIPTION
                            FROM MS_CUST
                           WHERE MS_CUST.STORERKEY = ST_SNINFO.STORERKEY
                             AND MS_CUST.CUSTKEY   = ST_SNINFO.CONTRACTCUSTKEY
                             AND ROWNUM            = 1 )                                                                                       AS CONTRACTCOMPANYNAME
                      , ST_SNINFO.FACTORYNAME                                                                                                  AS FACTORYNAME
                      , ST_SNINFO.FROMVALIDDT                                                                                                  AS FROMVALIDDT
                      , ST_SNINFO.TOVALIDDT                                                                                                    AS TOVALIDDT
                      , FN_CODEDESCR(AJ_INPLAN.STORERKEY,'CONTRACTTYPE_SN', ST_SNINFO.CONTRACTTYPE)                                            AS CONTRACTTYPE
                      , ST_SNINFO.STOCKID                                                                                                      AS BARCODE
                      , CASE WHEN ST_STOCK.DCCODE IN ('1000', '2170')
                             THEN fn_dataparse(ST_STOCK.ORGANIZE,'-',2)
                             ELSE CASE WHEN ST_STOCK.STOCKTYPE = 'GOOD'
                                       THEN '1000'
                                       ELSE '2000'
                                   END
                               END                                                                                                             AS STORAGELOC
                      , CASE WHEN AJ_INPLAN.ORDERTYPE = 'DDRAJ' OR AJ_INPLAN.ORDERTYPE = 'KITAJ'
                             THEN CASE WHEN AJ_INPLAN.IOTYPE = 'WD'
                                       THEN AJ_INPLAN.ORDERQTY * -1
                                       ELSE AJ_INPLAN.ORDERQTY
                                   END
                              ELSE AJ_INPLAN.ORDERQTY
                          END                                                                                                                  AS QTY
                      ,AJ_INPLAN.OTHER03                                                                                                       AS OTHER03
                      ,AJ_INPLAN.LOC                                                                                                           AS LOC
                      ,AJ_INPLAN.LOT                                                                                                           AS LOT
                      ,AJ_INPLAN.STOCKGRADE                                                                                                    AS STOCKGRADE
                      ,AJ_INPLAN.STOCKID                                                                                                       AS STOCKID
                      ,''                                                                                                                      AS STOCKAMTMSG
                      ,NVL(MS_SKU.SERIALTYPE,'3')                                                                                              AS SERIALTYPE
                      ,REGEXP_SUBSTR(AJ_INPLAN.OTHER02, '[^|]+', 1, 2)                                                                         AS KIT_SKU
                      , ( SELECT DM_DOCUMENT_D.MEMO2
                            FROM DM_DOCUMENT_D
                           WHERE DM_DOCUMENT_D.DCCODE  = AJ_INPLAN.DCCODE
                             AND DM_DOCUMENT_D.DOCTYPE = AJ_INPLAN.DOCTYPE
                             AND DM_DOCUMENT_D.DOCNO   = AJ_INPLAN.DOCNO
                             AND DM_DOCUMENT_D.DOCLINE = AJ_INPLAN.DOCLINE)                                                                    AS MEMO2
                   FROM AJ_INPLAN
               <if test="fixdccode != null and fixdccode != ''">
                   JOIN CM_USER_AUTHORITY ON 1=1
                                         AND CM_USER_AUTHORITY.USERID    = #{gUserId}
                                         AND CM_USER_AUTHORITY.DCCODE    = AJ_INPLAN.DCCODE
                                         AND CM_USER_AUTHORITY.STORERKEY = AJ_INPLAN.STORERKEY
                                         AND CM_USER_AUTHORITY.ORGANIZE  = AJ_INPLAN.ORGANIZE
                                         AND CM_USER_AUTHORITY.AREA      = AJ_INPLAN.AREA
               </if>
                   JOIN ST_STOCK ON ST_STOCK.DCCODE     = AJ_INPLAN.DCCODE
                                AND ST_STOCK.STORERKEY  = AJ_INPLAN.STORERKEY
                                AND ST_STOCK.ORGANIZE   = AJ_INPLAN.ORGANIZE
                                AND ST_STOCK.AREA       = AJ_INPLAN.AREA
                                AND ST_STOCK.SKU        = AJ_INPLAN.SKU
                                AND ST_STOCK.LOC        = AJ_INPLAN.LOC
                                AND ST_STOCK.LOT        = AJ_INPLAN.LOT
                                AND ST_STOCK.STOCKID    = AJ_INPLAN.STOCKID
                                AND ST_STOCK.STOCKGRADE = AJ_INPLAN.STOCKGRADE
                   JOIN MS_SKU ON MS_SKU.STORERKEY = AJ_INPLAN.STORERKEY
                              AND MS_SKU.SKU       = AJ_INPLAN.SKU
                              AND MS_SKU.DEL_YN    = 'N'
                          <!-- 상품 다중선택 -->
                          <if test="sku != null and sku != ''">
                              AND MS_SKU.SKU IN (SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
                                                   FROM (SELECT #{sku} AS VAL FROM DUAL) A
                                                CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
                          </if>
                   JOIN CM_LOT ON CM_LOT.STORERKEY = AJ_INPLAN.STORERKEY
                              AND CM_LOT.LOT       = AJ_INPLAN.LOT
                              AND CM_LOT.DEL_YN    = 'N'
                   LEFT OUTER JOIN ST_SNINFO ON AJ_INPLAN.STORERKEY = ST_SNINFO.STORERKEY
                                            AND AJ_INPLAN.SKU       = ST_SNINFO.SKU
                                            AND AJ_INPLAN.STOCKID   = ST_SNINFO.STOCKID
                   LEFT OUTER JOIN MS_UOM ON AJ_INPLAN.STORERKEY = MS_UOM.STORERKEY
                                         AND AJ_INPLAN.SKU       = MS_UOM.SKU
                                         AND AJ_INPLAN.UOM       = MS_UOM.BASEUOM
                                         AND MS_UOM.UOM          = 'KG'
                   LEFT OUTER JOIN MS_COST ON AJ_INPLAN.STORERKEY = MS_COST.STORERKEY
                                          AND AJ_INPLAN.OTHER04   = MS_COST.COSTCODE
                                          AND AJ_INPLAN.SLIPDT <![CDATA[>=]]> MS_COST.FROMDATE
                                          AND AJ_INPLAN.SLIPDT <![CDATA[<=]]> MS_COST.TODATE
                                          AND MS_COST.DEL_YN      = 'N'
                  WHERE 1=1
                    AND AJ_INPLAN.STATUS <![CDATA[<]]> '90'
                    AND AJ_INPLAN.ORDERTYPE IN ('DDRAJ', 'DURAJ', 'KITAJ')
                    AND AJ_INPLAN.DCCODE = #{fixdccode}
                <!-- 창고 다중선택 -->
                <if test="organize != null and organize != ''">
                    AND AJ_INPLAN.ORGANIZE IN (SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
                                                 FROM (SELECT #{organize} AS VAL FROM DUAL) A
                                              CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
                </if>
                <if test="basedtFrom != null and basedtFrom != ''">
                    AND AJ_INPLAN.DOCDT <![CDATA[>=]]> #{basedtFrom}
                </if>
                <if test="basedtTo != null and basedtTo != ''">
                    AND AJ_INPLAN.DOCDT <![CDATA[<=]]> #{basedtTo}
                </if>
                <if test="approvaltype != null and approvaltype != ''">
                    AND AJ_INPLAN.ORDERTYPE = #{approvaltype}
                </if>
                    AND NOT EXISTS (SELECT 1
                                      FROM AJ_APPRREQUEST
                                     WHERE AJ_APPRREQUEST.DCCODE    = AJ_INPLAN.DCCODE
                                       AND AJ_APPRREQUEST.STORERKEY = AJ_INPLAN.STORERKEY
                                       AND AJ_APPRREQUEST.ORGANIZE  = AJ_INPLAN.ORGANIZE
                                       AND AJ_APPRREQUEST.DOCDT     = AJ_INPLAN.DOCDT
                                       AND AJ_APPRREQUEST.DOCNO     = AJ_INPLAN.DOCNO
                                       AND AJ_APPRREQUEST.SLIPDT    = AJ_INPLAN.SLIPDT
                                       AND AJ_APPRREQUEST.SLIPNO    = AJ_INPLAN.SLIPNO
                                       AND AJ_APPRREQUEST.APPROVALSTATUS <![CDATA[<>]]> '9')
             ) T1
         ORDER BY T1.DCCODE
                , T1.STORERKEY
            <if test="approvaltype == 'KITAJ'.toString()">
                , T1.KIT_SKU
                , T1.DOCDT DESC
                , T1.DOCNO
            </if>
                , T1.SKU
    </select>

    <select id="getMasterList4" resultType="StAdjustmentRequestResDto">
        SELECT /* [StAdjustmentRequestService.sqlx][stAdjustmentRequestService.getMasterList4][재고조정 처리 조회][JiHoPark][2025.10.10] */
               AJ_APPRREQUEST.DCCODE                                                                                                  AS DCCODE
             , AJ_APPRREQUEST.STORERKEY                                                                                               AS STORERKEY
             , AJ_APPRREQUEST.ORGANIZE                                                                                                AS ORGANIZE
             , AJ_INPLAN.AREA                                                                                                         AS AREA
             , AJ_INPLAN.DOCTYPE                                                                                                      AS DOCTYPE
             , AJ_INPLAN.DOCDT                                                                                                        AS DOCDT
             , AJ_INPLAN.DOCNO                                                                                                        AS DOCNO
             , AJ_INPLAN.DOCLINE                                                                                                      AS DOCLINE
             , AJ_INPLAN.SLIPDT                                                                                                       AS SLIPDT
             , AJ_INPLAN.SLIPNO                                                                                                       AS SLIPNO
             , AJ_INPLAN.SLIPLINE                                                                                                     AS SLIPLINE
             , AJ_INPLAN.ORDERTYPE                                                                                                    AS ORDERTYPE
             , AJ_INPLAN.IOTYPE                                                                                                       AS IOTYPE
             , AJ_INPLAN.SLIPTYPE                                                                                                     AS SLIPTYPE
             , FN_CODEDESCR(AJ_APPRREQUEST.STORERKEY, 'STOCKTYPE', ST_STOCK.STOCKTYPE)                                                AS STOCKTYPENM
             , ST_STOCK.STOCKTYPE                                                                                                     AS STOCKTYPE
             , AJ_INPLAN.STOCKGRADE                                                                                                   AS STOCKGRADE
             , FN_CODEDESCR(AJ_APPRREQUEST.STORERKEY, 'STOCKGRADE', AJ_INPLAN.STOCKGRADE)                                             AS STOCKGRADENAME
             , MS_LOCATION.ZONE                                                                                                       AS ZONE
             , AJ_INPLAN.LOC                                                                                                          AS LOC
             , AJ_INPLAN.SKU                                                                                                          AS SKU
             , MS_SKU.DESCRIPTION                                                                                                     AS SKUNAME
             , AJ_INPLAN.LOT                                                                                                          AS LOT
             , AJ_INPLAN.UOM                                                                                                          AS UOM
             , AJ_INPLAN.ORDERQTY                                                                                                     AS TRANQTY
             , AJ_APPRREQUEST.DEL_YN                                                                                                  AS DEL_YN
             , AJ_INPLAN.OTHER02                                                                                                      AS DECREASETYPE
             , FN_CODEDESCR(AJ_INPLAN.STORERKEY, 'DECREASETYPE', AJ_INPLAN.OTHER02)                                                   AS DECREASETYPENAME
             , AJ_INPLAN.REASONCODE                                                                                                   AS REASONCODE
             , FN_CODEDESCR(AJ_INPLAN.STORERKEY, 'REASONCODE_AJ', AJ_INPLAN.REASONCODE)                                               AS REASONCODENAME
             , FN_CODEDESCR(AJ_INPLAN.STORERKEY, 'OTHER01_DMD', AJ_INPLAN.OTHER01)                                                    AS IMPUTETYPE
             , FN_CODEDESCR(AJ_INPLAN.STORERKEY, 'OTHER01_DMD', AJ_INPLAN.OTHER01)                                                    AS IMPUTETYPENAME
             , FN_CODEDESCR(AJ_INPLAN.STORERKEY, 'OTHER05_DMD', AJ_INPLAN.OTHER05)                                                    AS PROCESSMAIN
             , AJ_INPLAN.OTHER04                                                                                                      AS COSTCD
             , MS_COST.DESCRIPTION                                                                                                    AS COSTCDNAME
             , NVL(TRIM(FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'Y')),'N') AS NEARDURATIONYN /** 유통기한임박여부 */
             , CM_LOT.LOTTABLE01                                                                                                      AS LOTTABLE01
             /*
              * 기준일(제조) ~까지 : DURATIONTYPE = 1 일때 LOTTABLE01 - DURATION
              *                  DURATIONTYPE = 2 일때 LOTTABLE01
              * 기준일(소비) ~부터 : DURATIONTYPE = 1 일때 LOTTABLE01
              *                  DURATIONTYPE = 2 일때 LOTTABLE01 + DURATION  -1
              */
              --
              ,LOGISONESVC.FN_LOTTABLE_INFO('1',MS_SKU.STORERKEY,CM_LOT.LOTTABLE01,MS_SKU.DURATIONTYPE,MS_SKU.DURATION,'')             AS MANUFACTUREDT   /*제조일자*/
              ,LOGISONESVC.FN_LOTTABLE_INFO('2',MS_SKU.STORERKEY,CM_LOT.LOTTABLE01,MS_SKU.DURATIONTYPE,MS_SKU.DURATION,'')             AS EXPIREDT        /*소비일자*/
              --                 
             , FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'N0') ||'/'|| MS_SKU.DURATION AS DURATION_TERM
             , AJ_INPLAN.STOCKID                                                                                                      AS STOCKID
             , ST_SNINFO.SERIALNO                                                                                                     AS SERIALNO
             , ST_SNINFO.CONVSERIALNO                                                                                                 AS CONVSERIALNO
             , ST_SNINFO.SERIALLEVEL                                                                                                  AS SERIALLEVEL
             , ST_SNINFO.SERIALTYPE                                                                                                   AS SERIALTYPE
             , ST_SNINFO.FACTORYNAME                                                                                                  AS FACTORYNAME
             , MS_SKU.COLORDESCR                                                                                                      AS COLORDESCR
             , ST_SNINFO.PLACEOFORIGIN                                                                                                AS PLACEOFORIGIN
             , MS_SKU.DURATION                                                                                                        AS DURATION
             , MS_SKU.DURATIONTYPE                                                                                                    AS DURATIONTYPE
             , ST_SNINFO.BUTCHERYDT                                                                                                   AS BUTCHERYDT
             , ST_SNINFO.CONTRACTCUSTKEY                                                                                              AS CONTRACTCOMPANY
             , (SELECT DESCRIPTION
                  FROM MS_CUST
                 WHERE MS_CUST.STORERKEY = ST_SNINFO.STORERKEY
                   AND MS_CUST.CUSTKEY   = ST_SNINFO.CONTRACTCUSTKEY
                   AND ROWNUM            = 1 )                                                                                        AS CONTRACTCOMPANYNAME
             , ST_SNINFO.FROMVALIDDT                                                                                                  AS FROMVALIDDT
             , ST_SNINFO.TOVALIDDT                                                                                                    AS TOVALIDDT
             , FN_CODEDESCR(AJ_APPRREQUEST.STORERKEY,'CONTRACTTYPE_SN', ST_SNINFO.CONTRACTTYPE)                                       AS CONTRACTTYPE
             , ST_SNINFO.STOCKID                                                                                                      AS BARCODE
             , AJ_APPRREQUEST.APPROVALSTATUS                                                                                          AS APPROVALSTATUS
             , FN_CODEDESCR(AJ_APPRREQUEST.STORERKEY,'APPROVALSTATUS', AJ_APPRREQUEST.APPROVALSTATUS)                                 AS APPROVALSTATUSNAME
             , AJ_APPRREQUEST.EDITDATE                                                                                                AS APPROVALDATE
             , AJ_APPRREQUEST.APPROVALREQNO                                                                                           AS APPROVALREQNO
             , AJ_APPRREQUEST.APPROVALNO                                                                                              AS APPROVALNO
             , AJ_APPRREQUEST.APPROVALDT                                                                                              AS APPROVALDT
             , CASE WHEN AJ_APPRREQUEST.APPROVALSTATUS = '3' AND AJ_INPLAN.STATUS <![CDATA[<]]> '90' THEN UNISTR('S')
                    WHEN AJ_APPRREQUEST.APPROVALSTATUS = '0' AND AJ_INPLAN.STATUS <![CDATA[<]]> '90' THEN UNISTR('S')
                    ELSE UNISTR('E')
                END                                                                                                                   AS CHKFLAG
             , FN_CODEDESCR(AJ_INPLAN.STORERKEY, 'STATUS_AJ', AJ_INPLAN.STATUS )                                                      AS STATUS_AJ
             , CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 AND AJ_INPLAN.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN TO_NUMBER(NVL(MS_SKU.LINE02,0))
                    ELSE 0
                END                                                                                                                   AS AVGWEIGHT       /* 평균중량    */
             , ROUND(CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 AND AJ_INPLAN.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                          THEN (AJ_INPLAN.ORDERQTY) / TO_NUMBER(NVL(MS_SKU.LINE02,0))
                          ELSE 0
                      END, 2)                                                                                                         AS CALBOX          /* 환산박스    */
             , CASE WHEN AJ_INPLAN.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN NVL(AJ_INPLAN.ETCQTY1,0)
                    ELSE 0
                END                                                                                                                   AS REALORDERBOX    /* 실박스예정 */
             , CASE WHEN AJ_INPLAN.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN NVL(AJ_INPLAN.ETCQTY2,0)
                    ELSE 0
                END                                                                                                                   AS REALCFMBOX      /* 실박스확정 */
             , CASE WHEN NVL(AJ_INPLAN.ETCQTY2,0) = 0
                    THEN NVL(AJ_INPLAN.ETCQTY1,0)
                    ELSE 0
                END                                                                                                                   AS TRANBOX         /* 작업박스    */
             , CASE WHEN AJ_INPLAN.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN 'Y'
                    ELSE 'N'
                END                                                                                                                   AS BOXFLAG         /* 박스처리유무    */
             , AJ_INPLAN.ADDDATE                                                                                                      AS ADDDATE         /* 감모/역감모 생성일자 */
             , AJ_INPLAN.ADDWHO || CASE WHEN FN_GETUSERNAME(AJ_INPLAN.ADDWHO) NOT IN ('NOT FOUND','UNKNOWN')
                                        THEN '(' || FN_GETUSERNAME(AJ_INPLAN.ADDWHO) || ')'
                                    END                                                                                               AS ADDWHO          /* 감모/역감모 생성자 */
         <if test="gDccode == '2170'.toString()">
             , CASE WHEN AJ_INPLAN.DCCODE = '2170'
                    THEN DM_DOCUMENT_D.VENDOR
                END                                                                                                                   AS CUSTKEY         /* 외부창고 거래처코드 * /
             , CASE WHEN AJ_INPLAN.DCCODE = '2170'
                    THEN MS_CUST.DESCRIPTION
                END                                                                                                                   AS CUSTNAME        /* 외부창고 거래처명 */
             , CASE WHEN AJ_INPLAN.DCCODE = '2170'
                    THEN WD_EXDCINSTRUCT.REFERENCE01
                END                                                                                                                   AS REFERENCE01     /* 외부창고 비고 */
         </if>
         <if test="gDccode != '2170'.toString()">
             , ''                                                                                                                     AS CUSTKEY         /* 외부창고 거래처코드 * /
             , ''                                                                                                                     AS CUSTNAME        /* 외부창고 거래처명 */
             , ''                                                                                                                     AS REFERENCE01     /* 외부창고 비고 */
         </if>
          FROM AJ_APPRREQUEST
      <if test="fixdccode == null or fixdccode == ''">
          JOIN CM_USER_AUTHORITY ON CM_USER_AUTHORITY.USERID = #{gUserId}
                            <if test="gDccode != null and gDccode != ''">
                                AND CM_USER_AUTHORITY.DCCODE = #{gDccode}
                            </if>
                            <if test="gStorerkey != null and gStorerkey != ''">
                                AND CM_USER_AUTHORITY.STORERKEY = #{gStorerkey}
                            </if>
                            <if test="gOrganize != null and gOrganize != ''">
                                AND CM_USER_AUTHORITY.ORGANIZE = #{gOrganize}
                            </if>
                            <if test="gArea != null and gArea != ''">
                                AND CM_USER_AUTHORITY.AREA = #{gArea}
                            </if>
                            <!-- 창고 다중선택 -->
                            <if test="gMultiOrganize != null and gMultiOrganize != ''">
                                AND CM_USER_AUTHORITY.ORGANIZE IN (SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
                                                                     FROM (SELECT #{gMultiOrganize} AS VAL FROM DUAL) A
                                                                  CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
                            </if>
                            <if test="gMultiArea != null and gMultiArea != ''">
                                AND CM_USER_AUTHORITY.AREA      = #{gMultiArea}
                            </if>
                                AND CM_USER_AUTHORITY.DCCODE    = AJ_APPRREQUEST.DCCODE
                                AND CM_USER_AUTHORITY.STORERKEY = AJ_APPRREQUEST.STORERKEY
                                AND CM_USER_AUTHORITY.ORGANIZE  = AJ_APPRREQUEST.ORGANIZE
      </if>
          JOIN AJ_INPLAN ON AJ_APPRREQUEST.DCCODE    = AJ_INPLAN.DCCODE
                        AND AJ_APPRREQUEST.STORERKEY = AJ_INPLAN.STORERKEY
                        AND AJ_APPRREQUEST.ORGANIZE  = AJ_INPLAN.ORGANIZE
                        AND AJ_APPRREQUEST.DOCTYPE   = AJ_INPLAN.DOCTYPE
                        AND AJ_APPRREQUEST.DOCDT     = AJ_INPLAN.DOCDT
                        AND AJ_APPRREQUEST.DOCNO     = AJ_INPLAN.DOCNO
                        AND AJ_APPRREQUEST.SLIPDT    = AJ_INPLAN.SLIPDT
                        AND AJ_APPRREQUEST.SLIPNO    = AJ_INPLAN.SLIPNO
                        AND AJ_INPLAN.STOCKGRADE <![CDATA[<>]]> 'S3'   /* 폐기가 아닌것 */
                        AND AJ_INPLAN.ORDERTYPE != 'KITAJ'            /* 밀키트제외*/
          JOIN DM_DOCUMENT_D ON AJ_INPLAN.DCCODE = DM_DOCUMENT_D.DCCODE
                        AND AJ_INPLAN.STORERKEY  = DM_DOCUMENT_D.STORERKEY
                        AND AJ_INPLAN.ORGANIZE   = DM_DOCUMENT_D.ORGANIZE
                        AND AJ_INPLAN.AREA       = DM_DOCUMENT_D.AREA
                        AND AJ_INPLAN.DOCTYPE    = DM_DOCUMENT_D.DOCTYPE
                        AND AJ_INPLAN.DOCDT      = DM_DOCUMENT_D.DOCDT
                        AND AJ_INPLAN.DOCNO      = DM_DOCUMENT_D.DOCNO
                        AND AJ_INPLAN.DOCLINE    = DM_DOCUMENT_D.DOCLINE
          JOIN DM_DOCUMENT_H ON DM_DOCUMENT_D.DCCODE = DM_DOCUMENT_H.DCCODE
                        AND DM_DOCUMENT_D.STORERKEY  = DM_DOCUMENT_H.STORERKEY
                        AND DM_DOCUMENT_D.ORGANIZE   = DM_DOCUMENT_H.ORGANIZE
                        AND DM_DOCUMENT_D.DOCTYPE    = DM_DOCUMENT_H.DOCTYPE
                        AND DM_DOCUMENT_D.DOCDT      = DM_DOCUMENT_H.DOCDT
                        AND DM_DOCUMENT_D.DOCNO      = DM_DOCUMENT_H.DOCNO
          JOIN MS_SKU ON MS_SKU.STORERKEY = AJ_INPLAN.STORERKEY
                     AND MS_SKU.SKU       = AJ_INPLAN.SKU
                     AND MS_SKU.DEL_YN    = 'N'
                 <if test="storagetype != null and storagetype != ''">
                     AND MS_SKU.STORAGETYPE = #{storagetype}
                 </if>
                 <!-- 상품 다중선택 -->
                 <if test="sku != null and sku != ''">
                     AND MS_SKU.SKU IN (SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
                                          FROM (SELECT #{sku} AS VAL FROM DUAL) A
                                       CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
                 </if>
          JOIN CM_LOT ON CM_LOT.STORERKEY = AJ_INPLAN.STORERKEY
                     AND CM_LOT.LOT = AJ_INPLAN.LOT
                     AND CM_LOT.DEL_YN = 'N'
                 <if test="lottable01yn == 'Y'.toString()">
                     AND CM_LOT.LOTTABLE01 <![CDATA[<>]]> 'STD'
                 </if>
                 <if test="lottable01yn == 'N'.toString()">
                     AND CM_LOT.LOTTABLE01 = 'STD'
                 </if>
          JOIN MS_LOCATION ON MS_LOCATION.DCCODE = AJ_INPLAN.DCCODE
                          AND MS_LOCATION.LOC = AJ_INPLAN.LOC
                 <if test="zone != null and zone != ''">
                          AND MS_LOCATION.ZONE = #{zone}
                 </if>
          LEFT OUTER JOIN ST_STOCK ON AJ_INPLAN.DCCODE     = ST_STOCK.DCCODE
                                  AND AJ_INPLAN.STORERKEY  = ST_STOCK.STORERKEY
                                  AND AJ_INPLAN.ORGANIZE   = ST_STOCK.ORGANIZE
                                  AND AJ_INPLAN.AREA       = ST_STOCK.AREA
                                  AND AJ_INPLAN.SKU        = ST_STOCK.SKU
                                  AND AJ_INPLAN.LOC        = ST_STOCK.LOC
                                  AND AJ_INPLAN.LOT        = ST_STOCK.LOT
                                  AND AJ_INPLAN.STOCKID    = ST_STOCK.STOCKID
                                  AND AJ_INPLAN.STOCKGRADE = ST_STOCK.STOCKGRADE
      <if test="serialno != null and serialno != ''">
          JOIN ST_SNINFO ON ST_STOCK.STORERKEY = ST_SNINFO.STORERKEY
                        AND ST_STOCK.SKU       = ST_SNINFO.SKU
                        AND ST_STOCK.STOCKID   = ST_SNINFO.STOCKID
                    <if test="serialno != null and serialno != ''">
                        AND ST_SNINFO.SERIALNO = #{serialno}
                    </if>
                    <if test="convserialno != null and convserialno != ''">
                        AND ST_SNINFO.CONVSERIALNO = #{convserialno}
                    </if>
                    <if test="contractcompany != null and contractcompany != ''">
                        AND ST_SNINFO.CONTRACTCUSTKEY = #{contractcompany}
                    </if>
      </if>
      <if test="serialno == null or serialno == ''">
          LEFT OUTER JOIN ST_SNINFO ON ST_STOCK.STORERKEY = ST_SNINFO.STORERKEY
                                   AND ST_STOCK.SKU       = ST_SNINFO.SKU
                                   AND ST_STOCK.STOCKID   = ST_SNINFO.STOCKID
                               <if test="serialno != null and serialno != ''">
                                   AND ST_SNINFO.SERIALNO = #{serialno}
                               </if>
                               <if test="convserialno != null and convserialno != ''">
                                   AND ST_SNINFO.CONVSERIALNO = #{convserialno}
                               </if>
                               <if test="contractcompany != null and contractcompany != ''">
                                   AND ST_SNINFO.CONTRACTCUSTKEY = #{contractcompany}
                               </if>
      </if>
      <if test="gDccode == '2170'.toString()">
          LEFT OUTER JOIN MS_CUST ON DM_DOCUMENT_D.STORERKEY = MS_CUST.STORERKEY
                                 AND DM_DOCUMENT_D.VENDOR    = MS_CUST.CUSTKEY
                                 AND MS_CUST.CUSTTYPE        = 'C'
                                 AND MS_CUST.DEL_YN          = 'N'
          LEFT OUTER JOIN WD_EXDCINSTRUCT ON AJ_INPLAN.DCCODE       = WD_EXDCINSTRUCT.DCCODE
                                         AND AJ_INPLAN.STORERKEY    = WD_EXDCINSTRUCT.STORERKEY
                                         AND AJ_INPLAN.ORGANIZE     = WD_EXDCINSTRUCT.ORGANIZE
                                         AND AJ_INPLAN.DOCNO        = WD_EXDCINSTRUCT.DOCNO
                                         AND AJ_INPLAN.DOCLINE      = WD_EXDCINSTRUCT.DOCLINE
                                         AND AJ_INPLAN.SKU          = WD_EXDCINSTRUCT.SKU
                                         AND AJ_INPLAN.SLIPDT       = WD_EXDCINSTRUCT.SLIPDT
                                         AND WD_EXDCINSTRUCT.DEL_YN = 'N'
      </if>
          LEFT OUTER JOIN MS_COST ON AJ_INPLAN.STORERKEY = MS_COST.STORERKEY
                                 AND AJ_INPLAN.OTHER04   = MS_COST.COSTCODE
                                 AND AJ_INPLAN.SLIPDT <![CDATA[>=]]> MS_COST.FROMDATE
                                 AND AJ_INPLAN.SLIPDT <![CDATA[<=]]> MS_COST.TODATE
                                 AND MS_COST.DEL_YN      = 'N'
         WHERE 1=1
       <if test="gStorerkey != null and gStorerkey != ''">
           AND AJ_APPRREQUEST.STORERKEY = #{gStorerkey}
       </if>
       <if test="fixdccode != null and fixdccode != ''">
           AND AJ_APPRREQUEST.DCCODE = #{fixdccode}
       </if>
       <!-- 창고 다중선택 -->
       <if test="organize != null and organize != ''">
           AND ST_STOCK.ORGANIZE IN (SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
                                       FROM (SELECT #{organize} AS VAL FROM DUAL) A
                                    CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
       </if>
       <if test="stocktype != null and stocktype != ''">
           AND ST_STOCK.STOCKTYPE = #{stocktype}
       </if>
       <if test="stockgrade != null and stockgrade != ''">
           AND AJ_INPLAN.STOCKGRADE = #{stockgrade}
       </if>
       <if test="apprstatus != null and apprstatus != ''">
           AND AJ_APPRREQUEST.APPROVALSTATUS = #{apprstatus}
       </if>
       <if test="fromApprreqdt != null and fromApprreqdt != ''">
           AND AJ_APPRREQUEST.APPROVALREQDT <![CDATA[>=]]> #{fromApprreqdt}
       </if>
       <if test="toApprreqdt != null and toApprreqdt != ''">
           AND AJ_APPRREQUEST.APPROVALREQDT <![CDATA[<=]]> #{toApprreqdt}
       </if>
       <if test="fromSlipdt != null and fromSlipdt != ''">
           AND AJ_INPLAN.SLIPDT <![CDATA[>=]]> #{fromSlipdt}
       </if>
       <if test="toSlipdt != null and toSlipdt != ''">
           AND AJ_INPLAN.SLIPDT <![CDATA[<=]]> #{toSlipdt}
       </if>
           AND AJ_APPRREQUEST.APPROVALSTATUS <![CDATA[<>]]> '9'
         ORDER BY AJ_APPRREQUEST.DCCODE
                , AJ_APPRREQUEST.ORGANIZE
                , AJ_INPLAN.LOC
                , AJ_INPLAN.SKU
    </select>
</mapper>