<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="stAdjustmentBatchService">

    <select id="getZoneList" resultType="StAdjustmentCommCdResDto">
        SELECT /* [StAdjustmentBatchService.sqlx][stAdjustmentBatchService.getZoneList][일괄재고 zone 목록 조회][JiHoPark][2025.09.25] */
               DCCODE AS DCCODE
             , ZONE AS COM_CD
             , ZONE AS CD_NM
		  FROM MS_ZONE
         WHERE 1=1
           AND DEL_YN = 'N'
         ORDER BY ZONE ASC
    </select>

    <select id="getMasterList" resultType="StAdjustmentBatchResDto">
        SELECT /* [StAdjustmentBatchService.sqlx][stAdjustmentBatchService.getMasterList][일괄재고 재고조정 목록 조회][JiHoPark][2025.09.24] */
               ST_STOCK.DCCODE                                                                                                        AS DCCODE
             , ST_STOCK.STORERKEY                                                                                                     AS STORERKEY
             , ST_STOCK.ORGANIZE                                                                                                      AS ORGANIZE
             , ST_STOCK.STOCKTYPE                                                                                                     AS STOCKTYPE
             , FN_CODEDESCR(ST_STOCK.STORERKEY, 'STOCKTYPE', ST_STOCK.STOCKTYPE)                                                      AS STOCKTYPEDESC
             , ST_STOCK.STOCKGRADE                                                                                                    AS STOCKGRADE
             , FN_CODEDESCR(ST_STOCK.STORERKEY, 'STOCKGRADE', ST_STOCK.STOCKGRADE)                                                    AS STOCKGRADEDESC
             , ST_STOCK.LOC                                                                                                           AS LOC
             , ST_STOCK.SKU                                                                                                           AS SKU
             , MS_SKU.DESCRIPTION                                                                                                     AS SKUNAME
             , ST_STOCK.UOM                                                                                                           AS UOM
             , ST_STOCK.QTY                                                                                                           AS QTY
             , ST_STOCK.QTYALLOCATED                                                                                                  AS QTYALLOCATED
             , ST_STOCK.QTYPICKED                                                                                                     AS QTYPICKED
             , ST_STOCK.OPENQTY                                                                                                       AS SHOTAGE_QTY
             , 0                                                                                                                      AS TRANQTY
             , ''	                                                                                                                  AS REASONCODE
             , NVL(TRIM(FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'Y')),'N0') AS NEARDURATIONYN /** 유통기한임박여부 */
             , CM_LOT.LOTTABLE01                                                                                                      AS LOTTABLE01
             /*
              * 기준일(제조) ~까지 : DURATIONTYPE = 1 일때 LOTTABLE01 - DURATION
              *                  DURATIONTYPE = 2 일때 LOTTABLE01
              * 기준일(소비) ~부터 : DURATIONTYPE = 1 일때 LOTTABLE01
              *                  DURATIONTYPE = 2 일때 LOTTABLE01 + DURATION  -1
              */
              , CASE WHEN VALIDATE_CONVERSION(CM_LOT.LOTTABLE01 AS DATE, 'YYYYMMDD') = 1
                     THEN (CASE WHEN MS_SKU.DURATIONTYPE = '1'
                                THEN TO_CHAR(TO_DATE(REPLACE(CM_LOT.LOTTABLE01,'-',''),'YYYYMMDD') - MS_SKU.DURATION,'YYYY-MM-DD')
                                WHEN MS_SKU.DURATIONTYPE = '2'
                                THEN TO_CHAR(TO_DATE(REPLACE(CM_LOT.LOTTABLE01,'-',''),'YYYYMMDD'),'YYYY-MM-DD')
                                ELSE ''
                            END)
                     ELSE CM_LOT.LOTTABLE01
                 END                                                                                                                  AS MANUFACTUREDT   /*제조일자*/
              , CASE WHEN VALIDATE_CONVERSION(CM_LOT.LOTTABLE01 AS DATE, 'YYYYMMDD') = 1
                     THEN (CASE WHEN MS_SKU.DURATIONTYPE = '1'
                                THEN TO_CHAR(TO_DATE(REPLACE(CM_LOT.LOTTABLE01,'-',''),'YYYYMMDD'),'YYYY-MM-DD')
                                WHEN MS_SKU.DURATIONTYPE = '2'
                                THEN TO_CHAR(TO_DATE(REPLACE(CM_LOT.LOTTABLE01,'-',''),'YYYYMMDD') + MS_SKU.DURATION -1,'YYYY-MM-DD')
                                ELSE ''
                            END)
                     ELSE CM_LOT.LOTTABLE01
                 END                                                                                                                  AS EXPIREDT          /*소비일자*/
             , FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'N0') ||'/'|| MS_SKU.DURATION AS DURATION_TERM
             , ST_SNINFO.SERIALNO                                                                                                     AS SERIALNO
             , FN_CODEDESCR(MS_SKU.STORERKEY, 'STORAGETYPE', MS_SKU.STORAGETYPE)	                                                  AS STORAGETYPE
             , ST_STOCK.LOT                                                                                                           AS LOT
             , ST_STOCK.STOCKID                                                                                                       AS STOCKID
             , MS_SKU.DURATION                                                                                                        AS DURATION
             , MS_SKU.DURATIONTYPE                                                                                                    AS DURATIONTYPE
             , ST_STOCK.QTYALLOCATED                                                                                                  AS ETCQTY1
             , ST_STOCK.QTYPICKED                                                                                                     AS ETCQTY2
             , ST_STOCK.AREA                                                                                                          AS AREA
             , ST_SNINFO.FACTORYNAME                                                                                                  AS FACTORYNAME
             , ST_SNINFO.CONVSERIALNO                                                                                                 AS CONVSERIALNO
             , ST_SNINFO.BUTCHERYDT                                                                                                   AS BUTCHERYDT
             , ST_SNINFO.CONTRACTCUSTKEY                                                                                              AS CONTRACTCOMPANY
             , (SELECT DESCRIPTION
                  FROM MS_CUST
                 WHERE MS_CUST.STORERKEY = ST_SNINFO.STORERKEY
                   AND MS_CUST.CUSTKEY   = ST_SNINFO.CONTRACTCUSTKEY
                   AND ROWNUM = 1)                                                                                                    AS CONTRACTCOMPANYNAME
             , ST_SNINFO.FROMVALIDDT                                                                                                  AS FROMVALIDDT
             , ST_SNINFO.TOVALIDDT                                                                                                    AS TOVALIDDT
             , ST_SNINFO.POKEY                                                                                                        AS POKEY
             , ST_SNINFO.POLINE                                                                                                       AS POLINE
             , FN_CODEDESCR(ST_STOCK.STORERKEY,'CONTRACTTYPE_SN', ST_SNINFO.CONTRACTTYPE)                                             AS CONTRACTTYPE
             , ST_SNINFO.STOCKID                                                                                                      AS BARCODE
             , CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 AND ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN TO_NUMBER(NVL(MS_SKU.LINE02,0))
                    ELSE 0
                END                                                                                                                   AS AVGWEIGHT    /*평균중량*/
             , ROUND(CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 AND ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                          THEN ST_STOCK.OPENQTY / TO_NUMBER(NVL(MS_SKU.LINE02,0))
                          ELSE 0
                      END, 2)                                                                                                         AS CALBOX       /*환산박스*/
             , CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN NVL(ST_STOCK.BOXQTY,0)
                    ELSE 0
                END                                                                                                                   AS REALORDERBOX /*실박스예정*/
             , CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN NVL(ST_STOCK.BOXQTY,0)
                    ELSE 0
                END                                                                                                                   AS REALCFMBOX   /*실박스확정*/
             , '0'                                                                                                                    AS TRANBOX      /*작업박스*/
             , CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN 'Y'
                    ELSE 'N'
                END                                                                                                                   AS BOXFLAG      /*박스처리유무*/
             , ST_SNINFO.REAL_YN                                                                                                      AS REAL_YN
          FROM ST_STOCK
          JOIN CM_USER_AUTHORITY ON 1=1
                                AND CM_USER_AUTHORITY.DCCODE    = #{fixdccode}
                            <if test="gStorerkey != null and gStorerkey != ''">
                                AND CM_USER_AUTHORITY.STORERKEY = #{gStorerkey}
                            </if>
                            <!-- 창고 다중선택 -->
              				<if test="organize != null and organize != ''">
                                AND CM_USER_AUTHORITY.ORGANIZE IN (SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
                                                                     FROM (SELECT #{organize} AS VAL FROM DUAL) A
                                                                  CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
                            </if>
                                AND CM_USER_AUTHORITY.USERID    = #{gUserId}
                                AND CM_USER_AUTHORITY.DCCODE    = ST_STOCK.DCCODE
                                AND CM_USER_AUTHORITY.STORERKEY = ST_STOCK.STORERKEY
                                AND CM_USER_AUTHORITY.ORGANIZE  = ST_STOCK.ORGANIZE
                                AND CM_USER_AUTHORITY.AREA      = ST_STOCK.AREA
          JOIN MS_SKU ON MS_SKU.STORERKEY = ST_STOCK.STORERKEY
                     AND MS_SKU.SKU       = ST_STOCK.SKU
                     AND MS_SKU.DEL_YN    = 'N'
                 <if test="storagetype != null and storagetype != ''">
                     AND MS_SKU.STORAGETYPE = #{storagetype}
                 </if>
                 <!-- 상품 다중선택 -->
                 <if test="sku != null and sku != ''">
                     AND MS_SKU.SKU IN (SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
                                          FROM (SELECT #{sku} AS VAL FROM DUAL) A
                                       CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
                 </if>
          JOIN CM_LOT ON CM_LOT.STORERKEY = ST_STOCK.STORERKEY
                     AND CM_LOT.LOT       = ST_STOCK.LOT
                     AND CM_LOT.DEL_YN    = 'N'
                 <if test="lottable01yn == 'Y'.toString()">
                     AND CM_LOT.LOTTABLE01 <![CDATA[<>]]> 'STD'
                 </if>
                 <if test="lottable01yn == 'N'.toString()">
                     AND CM_LOT.LOTTABLE01 = 'STD'
                 </if>
          JOIN MS_LOCATION ON MS_LOCATION.DCCODE = ST_STOCK.DCCODE
                          AND MS_LOCATION.LOC    = ST_STOCK.LOC
          LEFT OUTER JOIN ST_SNINFO ON ST_STOCK.STORERKEY = ST_SNINFO.STORERKEY
                                   AND ST_STOCK.SKU       = ST_SNINFO.SKU
                                   AND ST_STOCK.STOCKID   = ST_SNINFO.STOCKID
         WHERE 1=1
       <if test="gStorerkey != null and gStorerkey != ''">
           AND ST_STOCK.STORERKEY = #{gStorerkey}
       </if>
       <if test="fixdccode != null and fixdccode != ''">
           AND ST_STOCK.DCCODE = #{fixdccode}
       </if>
       <!-- 창고 다중선택 -->
       <if test="organize != null and organize != ''">
           AND ST_STOCK.ORGANIZE IN (SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
                                       FROM (SELECT #{organize} AS VAL FROM DUAL) A
                                    CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
       </if>
       <if test="stocktype != null and stocktype != ''">
           AND ST_STOCK.STOCKTYPE = #{stocktype}
       </if>
       <if test="stockgrade != null and stockgrade != ''">
           AND ST_STOCK.STOCKGRADE = #{stockgrade}
       </if>
       <if test="fromloc != null and fromloc != ''">
           AND ST_STOCK.LOC <![CDATA[>=]]> #{fromloc}
       </if>
       <if test="toloc != null and toloc != ''">
           AND ST_STOCK.LOC <![CDATA[<=]]> #{toloc}
       </if>
       <if test="zone != null and zone != ''">
           AND MS_LOCATION.ZONE = #{zone}
       </if>
       <if test="serialno != null and serialno != ''">
           AND ST_SNINFO.SERIALNO = #{serialno}
       </if>
       <if test="convserialno != null and convserialno != ''">
           AND ST_SNINFO.CONVSERIALNO = #{convserialno}
       </if>
       ORDER BY ST_STOCK.DCCODE
              , ST_STOCK.LOC
              , ST_STOCK.STORERKEY
              , ST_STOCK.SKU
    </select>

    <select id="getMasterList2" resultType="StAdjustmentBatchResDto">
        SELECT /* [StAdjustmentBatchService.sqlx][stAdjustmentBatchService.getMasterList2][일괄재고 조정 처리결과 조회][JiHoPark][2025.09.24] */
               SY_PROCESSTEMP_ST.FROM_DCCODE                                                                                          AS DCCODE
             , SY_PROCESSTEMP_ST.FROM_STORERKEY                                                                                       AS STORERKEY
             , SY_PROCESSTEMP_ST.FROM_ORGANIZE                                                                                        AS ORGANIZE
             , NVL(SY_PROCESSTEMP_ST.FROM_STOCKTYPE, ST_STOCK.STOCKTYPE)                                                              AS STOCKTYPE
             , FN_CODEDESCR(SY_PROCESSTEMP_ST.FROM_STORERKEY, 'STOCKTYPE', NVL(SY_PROCESSTEMP_ST.FROM_STOCKTYPE, ST_STOCK.STOCKTYPE)) AS STOCKTYPEDESC
             , SY_PROCESSTEMP_ST.FROM_STOCKGRADE                                                                                      AS STOCKGRADE
             , FN_CODEDESCR(SY_PROCESSTEMP_ST.FROM_STORERKEY, 'STOCKGRADE', SY_PROCESSTEMP_ST.FROM_STOCKGRADE)                        AS STOCKGRADEDESC
             , SY_PROCESSTEMP_ST.FROM_LOC                                                                                             AS LOC
             , SY_PROCESSTEMP_ST.FROM_SKU                                                                                             AS SKU
             , MS_SKU.DESCRIPTION                                                                                                     AS SKUNAME
             , NVL(SY_PROCESSTEMP_ST.FROM_UOM, ST_STOCK.UOM)                                                                          AS UOM
             , SY_PROCESSTEMP_ST.FROM_ORDERQTY                                                                                        AS QTY
             , SY_PROCESSTEMP_ST.ETCQTY1                                                                                              AS QTYALLOCATED
             , SY_PROCESSTEMP_ST.ETCQTY2                                                                                              AS QTYPICKED
             , SY_PROCESSTEMP_ST.FROM_ORDERQTY - SY_PROCESSTEMP_ST.ETCQTY1 - SY_PROCESSTEMP_ST.ETCQTY2                                AS SHOTAGE_QTY
             , SY_PROCESSTEMP_ST.FROM_CONFIRMQTY                                                                                      AS TRANQTY
             , FN_CODEDESCR(SY_PROCESSTEMP_ST.FROM_STORERKEY, 'REASONCODE_AJ', SY_PROCESSTEMP_ST.TO_IOTYPE)                           AS REASONCODE
             , NVL(TRIM(FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'Y')),'N')          AS NEARDURATIONYN /** 유통기한임박여부 */
             , CM_LOT.LOTTABLE01                                                                                                      AS LOTTABLE01
             /*
              * 기준일(제조) ~까지 : DURATIONTYPE = 1 일때 LOTTABLE01 - DURATION
              *                  DURATIONTYPE = 2 일때 LOTTABLE01
              * 기준일(소비) ~부터 : DURATIONTYPE = 1 일때 LOTTABLE01
              *                  DURATIONTYPE = 2 일때 LOTTABLE01 + DURATION  -1
              */
              , CASE WHEN VALIDATE_CONVERSION(CM_LOT.LOTTABLE01 AS DATE, 'YYYYMMDD') = 1
                     THEN (CASE WHEN MS_SKU.DURATIONTYPE = '1'
                                THEN TO_CHAR(TO_DATE(REPLACE(CM_LOT.LOTTABLE01,'-',''),'YYYYMMDD') - MS_SKU.DURATION,'YYYY-MM-DD')
                                WHEN MS_SKU.DURATIONTYPE = '2'
                                THEN TO_CHAR(TO_DATE(REPLACE(CM_LOT.LOTTABLE01,'-',''),'YYYYMMDD'),'YYYY-MM-DD')
                                ELSE ''
                            END)
                     ELSE CM_LOT.LOTTABLE01
                 END                                                                                                                  AS MANUFACTUREDT   /*제조일자*/
              , CASE WHEN VALIDATE_CONVERSION(CM_LOT.LOTTABLE01 AS DATE, 'YYYYMMDD') = 1
                     THEN (CASE WHEN MS_SKU.DURATIONTYPE = '1'
                                THEN TO_CHAR(TO_DATE(REPLACE(CM_LOT.LOTTABLE01,'-',''),'YYYYMMDD'),'YYYY-MM-DD')
                                WHEN MS_SKU.DURATIONTYPE = '2'
                                THEN TO_CHAR(TO_DATE(REPLACE(CM_LOT.LOTTABLE01,'-',''),'YYYYMMDD') + MS_SKU.DURATION -1,'YYYY-MM-DD')
                                ELSE ''
                            END)
                     ELSE CM_LOT.LOTTABLE01
                 END                                                                                                                  AS EXPIREDT          /*소비일자*/
             , FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'N0') ||'/'|| MS_SKU.DURATION AS DURATION_TERM
             , ST_SNINFO.SERIALNO                                                                                                     AS SERIALNO
             , FN_CODEDESCR(MS_SKU.STORERKEY, 'STORAGETYPE', MS_SKU.STORAGETYPE)                                                      AS STORAGETYPE
             , MS_SKU.DURATION                                                                                                        AS DURATION
             , MS_SKU.DURATIONTYPE                                                                                                    AS DURATIONTYPE
             , CM_LOT.LOT                                                                                                             AS LOT
             , SY_PROCESSTEMP_ST.PROCESSFLAG                                                                                          AS PROCESSFLAG
             , SY_PROCESSTEMP_ST.PROCESSMSG                                                                                           AS PROCESSMSG
             , ST_SNINFO.FACTORYNAME                                                                                                  AS FACTORYNAME
             , ST_SNINFO.CONVSERIALNO                                                                                                 AS CONVSERIALNO
             , ST_SNINFO.BUTCHERYDT                                                                                                   AS BUTCHERYDT
             , ST_SNINFO.CONTRACTCUSTKEY                                                                                              AS CONTRACTCOMPANY
             , (SELECT DESCRIPTION
                  FROM MS_CUST
                 WHERE MS_CUST.STORERKEY = ST_SNINFO.STORERKEY
                   AND MS_CUST.CUSTKEY   = ST_SNINFO.CONTRACTCUSTKEY
                   AND ROWNUM = 1)                                                                                                    AS CONTRACTCOMPANYNAME
             , ST_SNINFO.FROMVALIDDT                                                                                                  AS FROMVALIDDT
             , ST_SNINFO.TOVALIDDT                                                                                                    AS TOVALIDDT
             , ST_SNINFO.POKEY                                                                                                        AS POKEY
             , ST_SNINFO.POLINE                                                                                                       AS POLINE
             , FN_CODEDESCR(SY_PROCESSTEMP_ST.FROM_STORERKEY,'CONTRACTTYPE_SN', ST_SNINFO.CONTRACTTYPE)                               AS CONTRACTTYPE
             , ST_SNINFO.STOCKID                                                                                                      AS BARCODE
             , CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 AND ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN TO_NUMBER(NVL(MS_SKU.LINE02,0))
                    ELSE 0
                END                                                                                                                   AS AVGWEIGHT  /* 평균중량*/
             , ROUND(CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 AND ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                          THEN (ST_STOCK.QTY - ST_STOCK.QTYALLOCATED - ST_STOCK.QTYPICKED) / TO_NUMBER(NVL(MS_SKU.LINE02,0))
                          ELSE 0
                      END, 2)                                                                                                         AS CALBOX     /* 환산박스*/
             , CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN NVL(ST_STOCK.BOXQTY,0)
                    ELSE 0
                END AS REALORDERBOX /*실박스예정*/
             , CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'
                    THEN NVL(ST_STOCK.BOXQTY,0)
                    ELSE 0
                END                                                                                                                   AS REALCFMBOX /*실박스확정*/
             , '0'                                                                                                                    AS TRANBOX    /*작업박스*/
          FROM SY_PROCESSTEMP_ST
          JOIN MS_SKU ON MS_SKU.STORERKEY = SY_PROCESSTEMP_ST.FROM_STORERKEY
                     AND MS_SKU.SKU       = SY_PROCESSTEMP_ST.FROM_SKU
                     AND MS_SKU.DEL_YN    = 'N'
          JOIN MS_LOCATION ON MS_LOCATION.DCCODE = SY_PROCESSTEMP_ST.FROM_DCCODE
                          AND MS_LOCATION.LOC    = SY_PROCESSTEMP_ST.FROM_LOC
          LEFT OUTER JOIN ST_STOCK ON ST_STOCK.STORERKEY  = SY_PROCESSTEMP_ST.FROM_STORERKEY
                                  AND ST_STOCK.DCCODE     = SY_PROCESSTEMP_ST.FROM_DCCODE
                                  AND ST_STOCK.ORGANIZE   = SY_PROCESSTEMP_ST.FROM_ORGANIZE
                                  AND ST_STOCK.AREA       = SY_PROCESSTEMP_ST.FROM_AREA
                                  AND ST_STOCK.SKU        = SY_PROCESSTEMP_ST.FROM_SKU
                                  AND ST_STOCK.LOC        = SY_PROCESSTEMP_ST.FROM_LOC
                                  AND ST_STOCK.LOT        = SY_PROCESSTEMP_ST.FROM_LOT
                                  AND ST_STOCK.STOCKID    = SY_PROCESSTEMP_ST.FROM_STOCKID
                                  AND ST_STOCK.STOCKGRADE = SY_PROCESSTEMP_ST.FROM_STOCKGRADE
          LEFT OUTER JOIN CM_LOT ON CM_LOT.STORERKEY = ST_STOCK.STORERKEY
                                AND CM_LOT.LOT       = ST_STOCK.LOT
                                AND CM_LOT.DEL_YN    = 'N'
          LEFT OUTER JOIN ST_SNINFO ON SY_PROCESSTEMP_ST.FROM_STORERKEY = ST_SNINFO.STORERKEY
                                   AND SY_PROCESSTEMP_ST.FROM_SKU       = ST_SNINFO.SKU
                                   AND SY_PROCESSTEMP_ST.FROM_STOCKID   = ST_SNINFO.STOCKID
         WHERE SY_PROCESSTEMP_ST.PROCESSTYPE    = 'ST_ADJUSTMENTBATCH'
           AND SY_PROCESSTEMP_ST.PROCESSCREATOR = #{gUserId}
           AND SY_PROCESSTEMP_ST.SPID	        = #{gSpid}
         ORDER BY SY_PROCESSTEMP_ST.FROM_DCCODE
                , SY_PROCESSTEMP_ST.FROM_LOC
                , SY_PROCESSTEMP_ST.FROM_STORERKEY
                , SY_PROCESSTEMP_ST.FROM_SKU
    </select>

</mapper>