<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="stConvertLotExDCService">

    <select id="getDataHeaderList" resultType="StConvertLotExDCResDto">    	
        SELECT  /* [stConvertLotExDCService.sqlx][getDataHeaderList][소비기한변경 목록 조회][sunho.kim][2025.06.16] */
               '0'                                                                                                                      AS CHECKYN               /* 체크유무 */ 
              ,ST_STOCK.SERIALKEY                                                                                                       AS SERIALKEY             /* 데이터번호 */
              ,ST_STOCK.DCCODE                                                                                                          AS DCCODE                /* 물류센터 */ 
              ,ST_STOCK.STORERKEY                                                                                                       AS STORERKEY             /* 고객사코드 */     
              ,ST_STOCK.ORGANIZE                                                                                                        AS ORGANIZE              /* 창고 */     
              ,ST_STOCK.AREA                                                                                                            AS AREA                  /* 작업구역 */          
              ,fn_DESCR_AREA( ST_STOCK.STORERKEY,ST_STOCK.AREA  )                                                                       AS AREANAME              /* 작업구역명 */               
              ,ST_STOCK.STOCKGRADE                                                                                                      AS FROM_STOCKGRADE       /* 재고등급(재고속성) */ 
              ,CD1.BASEDESCR                                                                                                            AS STOCKGRADENAME        /* 재고등급명(재고속성명) */                                                         
              ,ST_STOCK.SKU                                                                                                             AS SKU                   /* 상품코드 */ 
              ,MS_SKU.DESCRIPTION                                                                                                       AS SKUNAME               /* 상품영 */ 
              ,MS_SKUSPEC.SPECDESCR                                                                                                     AS SKUGROUP              /* 상품분류명 */ 
              ,ST_STOCK.LOC                                                                                                             AS FROM_LOC              /* 로케이션 */                    
              ,ST_STOCK.LOT                                                                                                             AS FROM_LOT              /* LOT */                
              ,ST_STOCK.STOCKID                                                                                                         AS FROM_STOCKID          /* 재고ID */        
              ,ST_STOCK.STOCKTYPE                                                                                                       AS FROM_STOCKTYPE        /* 재고유형 */        
              ,CD2.BASEDESCR                                                                                                            AS FROM_STOCKTYPEDESCR   /* 재고위치 */        
              ,ST_STOCK.UOM                                                                                                             AS UOM                   /* 단위 */
              ,ST_STOCK.QTY                                                                                                             AS QTY                   /* 현재고수량 */
              ,ST_STOCK.OPENQTY                                                                                                         AS OPENQTY               /* 가용재고수량 */         
              ,ST_STOCK.QTYALLOCATED                                                                                                    AS QTYALLOCATED          /* 재고할당수량 */   
              ,ST_STOCK.QTYPICKED                                                                                                       AS QTYPICKED             /* 피킹재고수량 */   
              ,ST_STOCK.OPENQTY                                                                                                         AS TRANQTY               /* 작업수량(가용재고) */   
              ,CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y' AND TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 THEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) ELSE 0 END AS AVGWEIGHT   /* 평균중량 */   
              ,ROUND(CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y' AND TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 AND ST_STOCK.UOM = 'KG' 
                    THEN ST_STOCK.QTY / TO_NUMBER(NVL(MS_SKU.LINE02,0)) 
                    ELSE 0 
               END  ,2)                                                                                                                 AS CALBOX                /* 환산박스 */   
              ,CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y' THEN ROUND(ST_STOCK.BOXQTY,2) ELSE 0 END             AS REALOPENBOX           /* REALOPENBOX */   
              ,CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y' THEN ROUND(ST_STOCK.BOXQTY,2) ELSE 0 END             AS REALCFMBOX            /* 실박스 */   
              ,0                                                                                                                        AS TRANBOX               /* 작업박스수량 */   
              ,CASE WHEN ST_STOCK.DCCODE = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'  THEN 'Y' ELSE 'N' END                               AS BOXFLAG               /* 박스처리유무 */ 
              ,CM_LOT.LOTTABLE01                                                                                                        AS FROM_LOTTABLE01       /* 라벨1(기준일(유통제조)) */   
              ,CM_LOT.LOTTABLE02                                                                                                        AS FROM_LOTTABLE02       /* 라벨2 */   
              ,CM_LOT.LOTTABLE03                                                                                                        AS FROM_LOTTABLE03       /* 라벨3 */   
              ,CM_LOT.LOTTABLE04                                                                                                        AS FROM_LOTTABLE04       /* 라벨4 */   
              ,CM_LOT.LOTTABLE05                                                                                                        AS FROM_LOTTABLE05       /* 라벨5 */   
              ,CASE WHEN FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'N') > 0 
                    THEN ROUND(FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'N') / MS_SKU.DURATION * 100) 
                    ELSE 0 
                END                                                                                                                     AS USEBYDATE_FREE_RT     /* 소비기한잔여율 */ 
              ,FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'N0') ||'/'|| MS_SKU.DURATION   AS DURATION_TERM         /* 유통기간잔여 */   
              ,MS_SKU.DURATIONTYPE                                                                                                      AS DURATIONTYPE          /* 유통기한관리방법 */   
              ,MS_SKU.DURATION                                                                                                          AS DURATION              /* 유통기간 */   
              ,ST_SERIALINFO.SERIALNO                                                                                                   AS SERIALNO              /* 이력번호 */   
              ,ST_SERIALINFO.CONVSERIALNO                                                                                               AS CONVSERIALNO          /* B/L번호  */   
              ,ST_SERIALINFO.BUTCHERYDT                                                                                                 AS BUTCHERYDT            /* 도축일자 */   
              ,ST_SERIALINFO.CONTRACTCUSTKEY                                                                                            AS CONTRACTCOMPANY       /* 계약업체 */   
              ,(SELECT DESCRIPTION FROM MS_CUST 
                WHERE  MS_CUST.STORERKEY = ST_SERIALINFO.STORERKEY
                AND    MS_CUST.CUSTKEY   = ST_SERIALINFO.CONTRACTCUSTKEY
                AND    ROWNUM = 1 )                                                                                                     AS CONTRACTCOMPANYNAME   /* 계약업체명 */   
              ,ST_SERIALINFO.FROMVALIDDT                                                                                                AS FROMVALIDDT           /* 유효일자(from) */   
              ,ST_SERIALINFO.TOVALIDDT                                                                                                  AS TOVALIDDT             /* 유효일자(to) */   
              ,CD3.BASEDESCR                                                                                                            AS CONTRACTTYPE          /* 계약유형 */   
              ,ST_SERIALINFO.STOCKID                                                                                                    AS BARCODE               /* 바코드 */   
              ,ST_SERIALINFO.FACTORYNAME                                                                                                AS FACTORYNAME           /* 도축장 */     
              ,TO_CHAR(ST_STOCK.ADDDATE, 'yyyy-mm-dd hh24:mi:ss')                                                                       AS ADDDATE               /* 최초등록시간 */
              ,TO_CHAR(ST_STOCK.EDITDATE, 'yyyy-mm-dd hh24:mi:ss')                                                                      AS EDITDATE              /* 최종변경시간 */
              ,ST_STOCK.ADDWHO                                                                                                          AS ADDWHO                /* 최초등록자 */
              ,USER1.USER_NM                                                                                                            AS ADDWHO_NM             /* 최초등록자명 */
              ,ST_STOCK.EDITWHO                                                                                                         AS EDITWHO               /* 최종변경자 */
              ,USER2.USER_NM                                                                                                            AS EDITWHO_NM            /* 최종변경자명 */
        FROM   ST_STOCK      
        
        
        LEFT OUTER JOIN FRAMEONE_USER USER1
                ON   USER1.USER_ID        = ST_STOCK.ADDWHO 
                
            LEFT OUTER JOIN FRAMEONE_USER USER2
                ON   USER2.USER_ID        = ST_STOCK.EDITWHO
        
        JOIN   CM_USER_AUTHORITY 
        ON  CM_USER_AUTHORITY.USERID            = #{gUserId}  
        <if test="fixdccode != null and fixdccode != ''">    
            AND    CM_USER_AUTHORITY.DCCODE    = #{fixdccode}       
        </if>
        <if test="gStorerkey != null and gStorerkey != ''"> 
            AND    CM_USER_AUTHORITY.STORERKEY = #{gStorerkey}    
        </if>
        <if test="area != null and area != ''">      
            AND    CM_USER_AUTHORITY.AREA      = #{area}         
        </if>
        <if test="organize != null and organize != ''">
            AND    CM_USER_AUTHORITY.ORGANIZE IN (SELECT TRIM(REGEXP_SUBSTR(VAL,'[^,]+',1,LEVEL)) AS VAL
                                               FROM (SELECT #{organize} AS VAL FROM DUAL) A
                                               CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0) 
        </if>
            AND    CM_USER_AUTHORITY.DCCODE        = ST_STOCK.DCCODE    
            AND    CM_USER_AUTHORITY.STORERKEY     = ST_STOCK.STORERKEY 
            AND    CM_USER_AUTHORITY.ORGANIZE      = ST_STOCK.ORGANIZE  
            AND    CM_USER_AUTHORITY.AREA          = ST_STOCK.AREA  
        JOIN   MS_SKU
            ON     MS_SKU.STORERKEY         = ST_STOCK.STORERKEY
            AND    MS_SKU.SKU               = ST_STOCK.SKU
            AND    MS_SKU.DEL_YN            = 'N'
        <if test="skuMulti != null and skuMulti != '' ">
            <trim prefix="AND (" suffix=")" prefixOverrides="OR">
                <foreach collection="skuMulti" item="item">
                    OR MS_SKU.SKU IN
                    <foreach collection="item" item="code" open="(" close=")" separator=",">
                        #{code}      
                    </foreach>
                </foreach>
            </trim>                                             
        </if>
        <if test="skugroup != null and skugroup != ''">   
            AND    MS_SKU.SKUGROUP           = #{skugroup} 
        </if>
        LEFT OUTER JOIN MS_SKUSPEC
            ON     MS_SKU.STORERKEY         = MS_SKUSPEC.STORERKEY
            AND    MS_SKU.SKUGROUP          = MS_SKUSPEC.SPECCODE
            AND    MS_SKUSPEC.SPECCATEGORY  = 'SKUGROUP'
            AND    MS_SKUSPEC.SPECCLASS     = 'MC'
            AND    MS_SKUSPEC.DEL_YN        = 'N'               
        JOIN   CM_LOT
            ON     CM_LOT.STORERKEY         = ST_STOCK.STORERKEY  
            AND    CM_LOT.LOT               = ST_STOCK.LOT       
            AND    CM_LOT.DEL_YN            = 'N'
        <if test="lottable01 != null and lottable01 != ''">    
            AND    CM_LOT.LOTTABLE01        LIKE #{lottable01} || '%'   
        </if>        
        JOIN   MS_LOCATION
            ON     MS_LOCATION.DCCODE       = ST_STOCK.DCCODE
            AND    MS_LOCATION.LOC          = ST_STOCK.LOC
        <if test="searchserial != null and searchserial != ''">
        JOIN   ST_SNINFO ST_SERIALINFO   
            ON     ST_STOCK.STORERKEY       = ST_SERIALINFO.STORERKEY
            AND    ST_STOCK.SKU             = ST_SERIALINFO.SKU     
            AND    ST_STOCK.STOCKID         = ST_SERIALINFO.STOCKID
        </if>        
        <if test="searchserial == null or searchserial == ''">
        LEFT OUTER JOIN   ST_SNINFO ST_SERIALINFO   
            ON     ST_STOCK.STORERKEY       = ST_SERIALINFO.STORERKEY 
            AND    ST_STOCK.SKU             = ST_SERIALINFO.SKU     
            AND    ST_STOCK.STOCKID         = ST_SERIALINFO.STOCKID
        </if>
        
        LEFT OUTER JOIN CM_CODE_STORER CD1
                    ON CD1.STORERKEY = ST_STOCK.STORERKEY
                   AND CD1.CODELIST  = 'STOCKGRADE'   
                   AND CD1.BASECODE  = ST_STOCK.STOCKGRADE
                   
        LEFT OUTER JOIN CM_CODE_STORER CD2
                    ON CD2.STORERKEY = ST_STOCK.STORERKEY
                   AND CD2.CODELIST  = 'STOCKTYPE'   
                   AND CD2.BASECODE  = ST_STOCK.STOCKTYPE
                   
        LEFT OUTER JOIN CM_CODE_STORER CD3
                    ON CD3.STORERKEY = ST_STOCK.STORERKEY
                   AND CD3.CODELIST  = 'CONTRACTTYPE_SN'   
                   AND CD3.BASECODE  = ST_SERIALINFO.CONTRACTTYPE                           
        
        WHERE  1=1
        <if test="organize != null and organize != ''">
            AND    ST_STOCK.ORGANIZE IN (SELECT TRIM(REGEXP_SUBSTR(VAL,'[^,]+',1,LEVEL)) AS VAL
                                               FROM (SELECT #{organize} AS VAL FROM DUAL) A
                                               CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0) 
        </if>
        <if test="stockgrade != null and stockgrade != ''">  
            AND    ST_STOCK.STOCKGRADE           = #{stockgrade}              
        </if>
        <if test="serialno != null and serialno != ''">    
            AND    ST_SERIALINFO.SERIALNO LIKE   #{serialno} || '%'   
        </if>   
        <if test="blnoMulti != null and blnoMulti != ''">
            AND    ST_SERIALINFO.CONVSERIALNO      IN
            <foreach collection="blnoMulti" item="item" open="(" separator="," close=")">
              #{item}
            </foreach> 
        </if>
        <if test="contractcompanyMulti != null and contractcompanyMulti != ''">
            AND    ST_SERIALINFO.CONTRACTCUSTKEY      IN
            <foreach collection="contractcompanyMulti" item="item" open="(" separator="," close=")">
                 #{item}
            </foreach> 
          </if> 
        <if test="sortkey == 'LOC'"> 
        ORDER BY ST_STOCK.DCCODE
                ,ST_STOCK.ORGANIZE    
                ,ST_STOCK.LOC
                ,ST_STOCK.SKU
                ,CM_LOT.LOTTABLE01
        </if>
        <if test="sortkey == 'DATE'">
        ORDER BY ST_STOCK.DCCODE
              ,ST_STOCK.STORERKEY 
              ,ST_STOCK.ORGANIZE  
              ,ST_STOCK.SKU
              ,CM_LOT.LOTTABLE01
        </if>
    </select>    
    
</mapper>