<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="stDailyInoutExDcService">
 	<select id="getStDailyInoutExDcMasterList" resultType="StDailyInoutExDcMasterResDto">
	   SELECT /* [stDailyInoutExDcService.sqlx][getStDailyInoutExDcMasterList][외부비축상품별수불현황 헤더 조회][parkJinWoo][20250710] */
                                                K_OUT.SKU                                     AS SKU                 /* 상품코드 */
                                                , K_OUT.ORGANIZE                                AS ORGANIZE            /* 창고 */
                                                , FN_DESCR_ORGANIZE('2170', K_OUT.ORGANIZE) AS ORGANIZENM          /* 창고명 */
                                                , MAX(K_OUT.DESCRIPTION)                        AS SKUNM               /* 상품명(원문) */
                                                , MAX(K_OUT.BASEUOM)                            AS UOM                 /* 기본단위 */
                                                , MAX(K_OUT.QTYPERBOX)                          AS QTYPERBOX           /* 박스입수 */
                                                , MAX(FN_DESCR_SKU('FW00', K_OUT.SKU))          AS SKUNAME             /* 상품명 */
                                                , MAX(K_OUT.BASEQTY)                            AS BASEQTY             /* 기초수량 */
                                                , MAX(K_OUT.STOCKQTY)                           AS STOCKQTY            /* 현재재고수량 */
                                                /* ── ■ 기말재고(수량) = 기초 + 입고 – 출고 ───────────────────────────── */
--                                                , ( MAX(K_OUT.BASEQTY) + ( NVL(SUM(K_OUT.DP_STO_QTY), 0) + NVL(SUM(K_OUT.DP_PO_QTY), 0) + NVL(SUM(K_OUT.RT_QTY), 0) + NVL(SUM(K_OUT.DP_AJ_DC_QTY), 0) ) + ( NVL(SUM(K_OUT.WD_STO_QTY), 0) + NVL(SUM(K_OUT.WD_SO_QTY), 0) + NVL(SUM(K_OUT.WD_PO_QTY), 0) + NVL(SUM(K_OUT.WD_AJ_DC_QTY), 0) + NVL(SUM(K_OUT.WD_AJ_DU_QTY), 0)+ NVL(SUM(K_OUT.WD_AJ_DU_QTY), 0) ) ) AS ENDQTY /* 기말재고수량 */
                                              , ( MAX(K_OUT.BASEQTY)
                                                + ( NVL(SUM(K_OUT.DP_STO_QTY), 0) + NVL(SUM(K_OUT.DP_PO_QTY), 0) + NVL(SUM(K_OUT.RT_QTY), 0) + NVL(SUM(K_OUT.DP_AJ_DC_QTY), 0) )
                                                + ( NVL(SUM(K_OUT.WD_STO_QTY), 0) + NVL(SUM(K_OUT.WD_SO_QTY), 0) + NVL(SUM(K_OUT.WD_PO_QTY), 0) + NVL(SUM(K_OUT.WD_AJ_DC_QTY), 0) + NVL(SUM(K_OUT.WD_AJ_DU_QTY), 0)
                                                  + NVL(SUM(K_OUT.WD_AJ_SA_QTY), 0)
                                                  )
                                                ) AS ENDQTY /* 기말재고수량 */
                                                /* 기말재고수량 */
                                                /* ── ■ 입고(STO) ───────────────────────────────────────────────────── */
                                                , SUM(K_OUT.DP_STO_QTY)                        AS DP_STO_QTY          /* 입고_STO_수량 */
                                                , CASE
                                                WHEN MAX(K_OUT.BASEUOM) IN ('EA', 'PACK') THEN
                                                TO_CHAR(TRUNC(SUM(K_OUT.DP_STO_QTY) / MAX(K_OUT.QTYPERBOX)))
                                                || '/' ||
                                                TO_CHAR(MOD(SUM(K_OUT.DP_STO_QTY), MAX(K_OUT.QTYPERBOX)))
                                                WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                TO_CHAR(SUM(K_OUT.DP_STO_BOX))
                                                ELSE TO_CHAR(SUM(K_OUT.DP_STO_QTY))
                                                END                                        AS DP_STO_BOX_DISP      /* 입고_STO_박스표기 */
                                                , SUM(K_OUT.DP_STO_BOX)                       AS DP_STO_BOX          /* 입고_STO_박스 */
                                                /* ── ■ 입고(PO) ────────────────────────────────────────────────────── */
                                                , SUM(K_OUT.DP_PO_QTY)                        AS DP_PO_QTY           /* 입고_PO_수량 */
                                                , CASE
                                                WHEN MAX(K_OUT.BASEUOM) IN ('EA', 'PACK') THEN
                                                TO_CHAR(TRUNC(SUM(K_OUT.DP_PO_QTY) / MAX(K_OUT.QTYPERBOX)))
                                                || '/' ||
                                                TO_CHAR(MOD(SUM(K_OUT.DP_PO_QTY), MAX(K_OUT.QTYPERBOX)))
                                                WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                TO_CHAR(SUM(K_OUT.DP_PO_BOX))
                                                ELSE TO_CHAR(SUM(K_OUT.DP_PO_QTY))
                                                END                                        AS DP_PO_BOX_DISP       /* 입고_PO_박스표기 */
                                                , SUM(K_OUT.DP_PO_BOX)                       AS DP_PO_BOX           /* 입고_PO_박스 */
                                                /* ── ■ 역감모 ──────────────────────────────────────────────────────── */
                                                , SUM(K_OUT.DP_AJ_DC_QTY)                    AS DP_AJ_DC_QTY        /* 역감모_수량 */
                                                , CASE
                                                WHEN MAX(K_OUT.BASEUOM) IN ('EA', 'PACK') THEN
                                                TO_CHAR(TRUNC(SUM(K_OUT.DP_AJ_DC_QTY) / MAX(K_OUT.QTYPERBOX)))
                                                || '/' ||
                                                TO_CHAR(MOD(SUM(K_OUT.DP_AJ_DC_QTY), MAX(K_OUT.QTYPERBOX)))
                                                WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                TO_CHAR(SUM(K_OUT.DP_AJ_DC_BOX))
                                                ELSE TO_CHAR(SUM(K_OUT.DP_AJ_DC_QTY))
                                                END                                        AS DP_AJ_DC_BOX_DISP    /* 역감모_박스표기 */
                                                , SUM(K_OUT.DP_AJ_DC_BOX)                    AS DP_AJ_DC_BOX        /* 역감모_박스 */
                                                /* ── ■ 반품(RT) ───────────────────────────────────────────────────── */
                                                , SUM(K_OUT.RT_QTY)                          AS RT_QTY              /* 반품_수량 */
                                                , CASE
                                                WHEN MAX(K_OUT.BASEUOM) IN ('EA', 'PACK') THEN
                                                TO_CHAR(TRUNC(SUM(K_OUT.RT_QTY) / MAX(K_OUT.QTYPERBOX)))
                                                || '/' ||
                                                TO_CHAR(MOD(SUM(K_OUT.RT_QTY), MAX(K_OUT.QTYPERBOX)))
                                                WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                TO_CHAR(SUM(K_OUT.RT_BOX))
                                                ELSE TO_CHAR(SUM(K_OUT.RT_QTY))
                                                END                                        AS RT_BOX_DISP          /* 반품_박스표기 */
                                                , SUM(K_OUT.RT_BOX)                          AS RT_BOX              /* 반품_박스 */
                                                /* ── ■ 출고(STO) ──────────────────────────────────────────────────── */
                                                , SUM(K_OUT.WD_STO_QTY)                      AS WD_STO_QTY          /* 출고_STO_수량 */
                                                , CASE
                                                WHEN MAX(K_OUT.BASEUOM) IN ('EA', 'PACK') THEN
                                                TO_CHAR(TRUNC(SUM(K_OUT.WD_STO_QTY) / MAX(K_OUT.QTYPERBOX)))
                                                || '/' ||
                                                TO_CHAR(MOD(SUM(K_OUT.WD_STO_QTY), MAX(K_OUT.QTYPERBOX)))
                                                WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                TO_CHAR(SUM(K_OUT.WD_STO_BOX))
                                                ELSE TO_CHAR(SUM(K_OUT.WD_STO_QTY))
                                                END                                        AS WD_STO_BOX_DISP      /* 출고_STO_박스표기 */
                                                , SUM(K_OUT.WD_STO_BOX)                      AS WD_STO_BOX          /* 출고_STO_박스 */
                                                /* ── ■ 출고(SO) ───────────────────────────────────────────────────── */
                                                , SUM(K_OUT.WD_SO_QTY)                       AS WD_SO_QTY           /* 출고_SO_수량 */
                                                , CASE
                                                WHEN MAX(K_OUT.BASEUOM) IN ('EA', 'PACK') THEN
                                                TO_CHAR(TRUNC(SUM(K_OUT.WD_SO_QTY) / MAX(K_OUT.QTYPERBOX)))
                                                || '/' ||
                                                TO_CHAR(MOD(SUM(K_OUT.WD_SO_QTY), MAX(K_OUT.QTYPERBOX)))
                                                WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                TO_CHAR(SUM(K_OUT.WD_SO_BOX))
                                                ELSE TO_CHAR(SUM(K_OUT.WD_SO_QTY))
                                                END                                        AS WD_SO_BOX_DISP       /* 출고_SO_박스표기 */
                                                , SUM(K_OUT.WD_SO_BOX)                       AS WD_SO_BOX           /* 출고_SO_박스 */
                                                /* ── ■ 출고(PO)협력사 반품 ────────────────────────────────────────── */
                                                , SUM(K_OUT.WD_PO_QTY)                       AS WD_PO_QTY           /* 출고_PO_수량 */
                                                , CASE
                                                WHEN MAX(K_OUT.BASEUOM) IN ('EA', 'PACK') THEN
                                                TO_CHAR(TRUNC(SUM(K_OUT.WD_PO_QTY) / MAX(K_OUT.QTYPERBOX)))
                                                || '/' ||
                                                TO_CHAR(MOD(SUM(K_OUT.WD_PO_QTY), MAX(K_OUT.QTYPERBOX)))
                                                WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                TO_CHAR(SUM(K_OUT.WD_PO_BOX))
                                                ELSE TO_CHAR(SUM(K_OUT.WD_PO_QTY))
                                                END                                        AS WD_PO_BOX_DISP       /* 출고_PO_박스표기 */
                                                , SUM(K_OUT.WD_PO_BOX)                       AS WD_PO_BOX           /* 출고_PO_박스 */
                                                /* ── ■ 감모 ──────────────────────────────────────────────────────── */
                                                , SUM(K_OUT.WD_AJ_DC_QTY)                    AS WD_AJ_DC_QTY        /* 감모_수량 */
                                                , CASE
                                                WHEN MAX(K_OUT.BASEUOM) IN ('EA', 'PACK') THEN
                                                TO_CHAR(TRUNC(SUM(K_OUT.WD_AJ_DC_QTY) / MAX(K_OUT.QTYPERBOX)))
                                                || '/' ||
                                                TO_CHAR(MOD(SUM(K_OUT.WD_AJ_DC_QTY), MAX(K_OUT.QTYPERBOX)))
                                                WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                TO_CHAR(SUM(K_OUT.WD_AJ_DC_BOX))
                                                ELSE TO_CHAR(SUM(K_OUT.WD_AJ_DC_QTY))
                                                END                                        AS WD_AJ_DC_BOX_DISP    /* 감모_박스표기 */
                                                , SUM(K_OUT.WD_AJ_DC_BOX)                    AS WD_AJ_DC_BOX        /* 감모_박스 */
                                                /* ── ■ 폐기 ──────────────────────────────────────────────────────── */
                                                , SUM(K_OUT.WD_AJ_DU_QTY)                    AS WD_AJ_DU_QTY        /* 폐기_수량 */
                                                , CASE
                                                WHEN MAX(K_OUT.BASEUOM) IN ('EA', 'PACK') THEN
                                                TO_CHAR(TRUNC(SUM(K_OUT.WD_AJ_DU_QTY) / MAX(K_OUT.QTYPERBOX)))
                                                || '/' ||
                                                TO_CHAR(MOD(SUM(K_OUT.WD_AJ_DU_QTY), MAX(K_OUT.QTYPERBOX)))
                                                WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                TO_CHAR(SUM(K_OUT.WD_AJ_DU_BOX))
                                                ELSE TO_CHAR(SUM(K_OUT.WD_AJ_DU_QTY))
                                                END                                        AS WD_AJ_DU_DISP        /* 폐기_박스표기 */
                                                , SUM(K_OUT.WD_AJ_DU_BOX)                    AS WD_AJ_DU_BOX        /* 폐기_박스 */
                                                /* ── ■ 총계 ─────────────────────────────────────────────────────── */
                                                , SUM(K_OUT.DAY_TOTAL_QTY)                   AS TOTAL_QTY           /* 일계_수량합계 */
                                                , SUM(K_OUT.DAY_TOTAL_BOX)                   AS TOTAL_BOX           /* 일계_박스합계 */
                                                /* ── ■ 입고계 / 출고계 ───────────────────────────────────────────── */
                                                , (  NVL(SUM(K_OUT.DP_STO_QTY), 0)
                                                + NVL(SUM(K_OUT.DP_PO_QTY), 0)
                                                + NVL(SUM(K_OUT.RT_QTY), 0)
                                                + NVL(SUM(K_OUT.DP_AJ_DC_QTY), 0)
                                                )                                          AS IN_TOTAL_QTY        /* 입고총계_수량 */
                                                , (  NVL(SUM(K_OUT.DP_STO_BOX), 0)
                                                + NVL(SUM(K_OUT.DP_PO_BOX), 0)
                                                + NVL(SUM(K_OUT.RT_BOX), 0)
                                                + NVL(SUM(K_OUT.DP_AJ_DC_BOX), 0)
                                                )                                          AS IN_TOTAL_BOX        /* 입고총계_박스 */
                                                , (  NVL(SUM(K_OUT.WD_STO_QTY), 0)
                                                + NVL(SUM(K_OUT.WD_SO_QTY), 0)
                                                + NVL(SUM(K_OUT.WD_PO_QTY), 0)
                                                + NVL(SUM(K_OUT.WD_AJ_DC_QTY), 0)
                                                + NVL(SUM(K_OUT.WD_AJ_DU_QTY), 0)
                                                + NVL(SUM(K_OUT.WD_AJ_SA_QTY), 0)
                                                )                                          AS OUT_TOTAL_QTY       /* 출고총계_수량 */
                                                , (  NVL(SUM(K_OUT.WD_STO_BOX), 0)
                                                + NVL(SUM(K_OUT.WD_SO_BOX), 0)
                                                + NVL(SUM(K_OUT.WD_PO_BOX), 0)
                                                + NVL(SUM(K_OUT.WD_AJ_DC_BOX), 0)
                                                + NVL(SUM(K_OUT.WD_AJ_DU_BOX), 0)
                                                  + NVL(SUM(K_OUT.WD_AJ_SA_BOX), 0)
                                                )                                          AS OUT_TOTAL_BOX       /* 출고총계_박스 */
                                                , CASE
                                                WHEN MAX(K_OUT.BASEUOM) IN ('EA', 'PACK') THEN
                                                TO_CHAR(TRUNC(
                                                ( SUM(K_OUT.DP_STO_QTY) + SUM(K_OUT.DP_PO_QTY)
                                                + SUM(K_OUT.RT_QTY)     + SUM(K_OUT.DP_AJ_DC_QTY) )
                                                / MAX(K_OUT.QTYPERBOX)
                                                ))
                                                || '/' ||
                                                TO_CHAR(MOD(
                                                ( SUM(K_OUT.DP_STO_QTY) + SUM(K_OUT.DP_PO_QTY)
                                                + SUM(K_OUT.RT_QTY)     + SUM(K_OUT.DP_AJ_DC_QTY) ),
                                                MAX(K_OUT.QTYPERBOX)
                                                ))
                                                WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                TO_CHAR(SUM(K_OUT.DP_STO_BOX) + SUM(K_OUT.DP_PO_BOX)
                                                + SUM(K_OUT.RT_BOX)    + SUM(K_OUT.DP_AJ_DC_BOX))
                                                ELSE TO_CHAR(SUM(K_OUT.DP_STO_QTY) + SUM(K_OUT.DP_PO_QTY)
                                                + SUM(K_OUT.RT_QTY)    + SUM(K_OUT.DP_AJ_DC_QTY))
                                                END                                        AS IN_TOTAL_BOX_DISP   /* 입고총계_박스표기 */
                                                , CASE
                                                WHEN MAX(K_OUT.BASEUOM) IN ('EA', 'PACK') THEN
                                                TO_CHAR(TRUNC(
                                                ( SUM(K_OUT.WD_STO_QTY) + SUM(K_OUT.WD_SO_QTY)
                                                + SUM(K_OUT.WD_PO_QTY)  + SUM(K_OUT.WD_AJ_DC_QTY)
                                                + SUM(K_OUT.WD_AJ_DU_QTY)
                                                + SUM(K_OUT.WD_AJ_SA_QTY) )
                                                / MAX(K_OUT.QTYPERBOX)
                                                ))
                                                || '/' ||
                                                TO_CHAR(MOD(
                                                ( SUM(K_OUT.WD_STO_QTY) + SUM(K_OUT.WD_SO_QTY)
                                                + SUM(K_OUT.WD_PO_QTY)  + SUM(K_OUT.WD_AJ_DC_QTY)
                                                + SUM(K_OUT.WD_AJ_DU_QTY)
                                                + SUM(K_OUT.WD_AJ_SA_QTY) ),
                                                MAX(K_OUT.QTYPERBOX)
                                                ))
                                                WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                TO_CHAR(SUM(K_OUT.WD_STO_BOX) + SUM(K_OUT.WD_SO_BOX)
                                                + SUM(K_OUT.WD_PO_BOX) + SUM(K_OUT.WD_AJ_DC_BOX)
                                                + SUM(K_OUT.WD_AJ_DU_BOX)
                                                + SUM(K_OUT.WD_AJ_SA_BOX))
                                                ELSE TO_CHAR(SUM(K_OUT.WD_STO_QTY) + SUM(K_OUT.WD_SO_QTY)
                                                + SUM(K_OUT.WD_PO_QTY) + SUM(K_OUT.WD_AJ_DC_QTY)
                                                + SUM(K_OUT.WD_AJ_DU_QTY)
                                                + SUM(K_OUT.WD_AJ_SA_QTY))
                                                END                                        AS OUT_TOTAL_BOX_DISP  /* 출고총계_박스표기 */
                                                /* ── ■ 기말재고(박스표기) ─────────────────────────────────────────── */
                                                , CASE
                                                WHEN MAX(K_OUT.BASEUOM) IN ('EA','PACK') THEN
                                                TO_CHAR(TRUNC( ( MAX(K_OUT.BASEQTY)
                                                + ( NVL(SUM(K_OUT.DP_STO_QTY),0) + NVL(SUM(K_OUT.DP_PO_QTY),0)
                                                + NVL(SUM(K_OUT.RT_QTY),0)    + NVL(SUM(K_OUT.DP_AJ_DC_QTY),0) )
                                                + ( NVL(SUM(K_OUT.WD_STO_QTY),0) + NVL(SUM(K_OUT.WD_SO_QTY),0)
                                                + NVL(SUM(K_OUT.WD_PO_QTY),0)  + NVL(SUM(K_OUT.WD_AJ_DC_QTY),0)
                                                + NVL(SUM(K_OUT.WD_AJ_DU_QTY),0) + NVL(SUM(K_OUT.WD_AJ_SA_QTY),0))
                                                ) / MAX(K_OUT.QTYPERBOX) ))
                                                || '/' ||
                                                TO_CHAR(MOD( ( MAX(K_OUT.BASEQTY)
                                                + ( NVL(SUM(K_OUT.DP_STO_QTY),0) + NVL(SUM(K_OUT.DP_PO_QTY),0)
                                                + NVL(SUM(K_OUT.RT_QTY),0)    + NVL(SUM(K_OUT.DP_AJ_DC_QTY),0) )
                                                + ( NVL(SUM(K_OUT.WD_STO_QTY),0) + NVL(SUM(K_OUT.WD_SO_QTY),0)
                                                + NVL(SUM(K_OUT.WD_PO_QTY),0)  + NVL(SUM(K_OUT.WD_AJ_DC_QTY),0)
                                                + NVL(SUM(K_OUT.WD_AJ_DU_QTY),0) + NVL(SUM(K_OUT.WD_AJ_SA_QTY),0))
                                                ), MAX(K_OUT.QTYPERBOX) ))
                                                WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                TO_CHAR( NVL(SUM(K_OUT.DP_STO_BOX),0) + NVL(SUM(K_OUT.DP_PO_BOX),0)
                                                + NVL(SUM(K_OUT.RT_BOX),0)     + NVL(SUM(K_OUT.DP_AJ_DC_BOX),0)
                                                + NVL(SUM(K_OUT.WD_STO_BOX),0) + NVL(SUM(K_OUT.WD_SO_BOX),0)
                                                + NVL(SUM(K_OUT.WD_PO_BOX),0)  + NVL(SUM(K_OUT.WD_AJ_DC_BOX),0)
                                                + NVL(SUM(K_OUT.WD_AJ_DU_BOX),0) + NVL(SUM(K_OUT.WD_AJ_SA_BOX),0))
                                                ELSE
                                                TO_CHAR( MAX(K_OUT.BASEQTY)
                                                + NVL(SUM(K_OUT.DP_STO_QTY),0) + NVL(SUM(K_OUT.DP_PO_QTY),0)
                                                + NVL(SUM(K_OUT.RT_QTY),0)     + NVL(SUM(K_OUT.DP_AJ_DC_QTY),0)
                                                + NVL(SUM(K_OUT.WD_STO_QTY),0) + NVL(SUM(K_OUT.WD_SO_QTY),0)
                                                + NVL(SUM(K_OUT.WD_PO_QTY),0)  + NVL(SUM(K_OUT.WD_AJ_DC_QTY),0)
                                                + NVL(SUM(K_OUT.WD_AJ_DU_QTY),0)+ NVL(SUM(K_OUT.WD_AJ_SA_QTY),0) )
                                                END AS END_BOX_DISP /* 기말재고_박스표기 */
                                                /* ── ■ 매각 ──────────────────────────────────────────────────────── */
                                                  	, SUM(K_OUT.WD_AJ_SA_QTY)                    AS WD_AJ_SA_QTY        /* 매각_수량 */
                                                  , CASE
                                                    WHEN MAX(K_OUT.BASEUOM) IN ('EA', 'PACK') THEN
                                                         TO_CHAR(TRUNC(SUM(K_OUT.WD_AJ_SA_QTY) / MAX(K_OUT.QTYPERBOX)))
                                                         || '/' ||
                                                         TO_CHAR(MOD(SUM(K_OUT.WD_AJ_SA_QTY), MAX(K_OUT.QTYPERBOX)))
                                                    WHEN MAX(K_OUT.BASEUOM) = 'KG' THEN
                                                         TO_CHAR(SUM(K_OUT.WD_AJ_SA_BOX))
                                                    ELSE TO_CHAR(SUM(K_OUT.WD_AJ_SA_QTY))
                                                    END                                        AS WD_AJ_SA_BOX_DISP   /* 매각_박스표기 */
                                                  , SUM(K_OUT.WD_AJ_SA_BOX)                    AS WD_AJ_SA_BOX        /* 매각_박스 */
		FROM
		    (
		        SELECT
		              K.SKU                  AS SKU
		            , K.ORGANIZE			 AS ORGANIZE
					, MS_SKU.DESCRIPTION	 AS DESCRIPTION
		            , MS_SKU.BASEUOM         AS BASEUOM
		            , MS_SKU.QTYPERBOX       AS QTYPERBOX
		            , K.DELIVERYDATE         AS DELIVERYDATE
		            , ST_SNINFO.CONVSERIALNO AS CONVSERIALNO
		            , K.DP_STO_QTY           AS DP_STO_QTY
		            , K.DP_STO_BOX           AS DP_STO_BOX
		            , K.DP_PO_QTY            AS DP_PO_QTY
		            , K.DP_PO_BOX            AS DP_PO_BOX
		            , K.RT_QTY               AS RT_QTY
		            , K.RT_BOX               AS RT_BOX
		            , K.WD_STO_QTY           AS WD_STO_QTY
		            , K.WD_STO_BOX           AS WD_STO_BOX
		            , K.WD_SO_QTY            AS WD_SO_QTY
		            , K.WD_SO_BOX            AS WD_SO_BOX
		            , K.WD_PO_QTY            AS WD_PO_QTY
		            , K.WD_PO_BOX            AS WD_PO_BOX
		            , K.WD_AJ_DC_QTY         AS WD_AJ_DC_QTY
		            , K.WD_AJ_DC_BOX         AS WD_AJ_DC_BOX
		            , K.DP_AJ_DC_QTY         AS DP_AJ_DC_QTY
		            , K.DP_AJ_DC_BOX         AS DP_AJ_DC_BOX
		            , K.WD_AJ_DU_QTY         AS WD_AJ_DU_QTY
		            , K.WD_AJ_DU_BOX         AS WD_AJ_DU_BOX
		            , K.DAY_TOTAL_QTY        AS DAY_TOTAL_QTY
		            , K.DAY_TOTAL_BOX        AS DAY_TOTAL_BOX
                    , K.WD_AJ_SA_QTY          AS WD_AJ_SA_QTY /*매각*/
                    , K.WD_AJ_SA_BOX          AS WD_AJ_SA_BOX /*매각*/ 
		           , NVL((
					    SELECT SUM(A.QTY)
					      FROM ST_STOCK A
					      JOIN CM_LOT
					        ON CM_LOT.STORERKEY = A.STORERKEY
					       AND CM_LOT.LOT       = A.LOT
					       AND CM_LOT.DEL_YN    = 'N'
					     WHERE A.STORERKEY = K.STORERKEY
					       AND A.DCCODE    = K.DCCODE
					       AND A.ORGANIZE  = K.ORGANIZE
					       AND A.SKU       = K.SKU
					       AND A.UOM       = MS_SKU.BASEUOM
					), 0) AS STOCKQTY  
		            , NVL((
		                SELECT SUM(BASEQTY)
		                     + SUM(RECEIPT_PO + RETURNQTY + RECEIPT_STO + ADJUSTQTY_DP)
		                     - SUM(ORDERQTY_SO + ORDERQTY_PO + ORDERQTY_STO + ADJUSTQTY_WD + ADJUSTQTY_DISUSE)
		                FROM ST_DAILYINOUT A
		                WHERE A.STORERKEY =#{gStorerkey}
		                  AND A.DCCODE = #{fixDcCode}
		                  AND A.ORGANIZE = K.ORGANIZE
		                  AND A.SKU = K.SKU
		                  AND A.UOM = MS_SKU.BASEUOM
		                  AND A.INOUTDT = #{fromDeliveryDate}
		                GROUP BY A.STORERKEY, A.DCCODE, A.ORGANIZE, A.SKU, A.UOM
		            ), 0)                  AS BASEQTY
		        FROM
		            (
		                SELECT
		                      SKU                AS SKU
		                    , DOCNO              AS DOCNO
		                    , REF_DOCID          AS REF_DOCID
		                    , REF_CUST_DOCID     AS REF_CUST_DOCID
		                    , DOCLINE            AS DOCLINE
		                    , ORGANIZE           AS ORGANIZE
		                    , DELIVERYDATE       AS DELIVERYDATE
		                    , STOCKID            AS STOCKID
		                    , STORERKEY			 AS STORERKEY
		                    , DCCODE			 AS DCCODE
		                    , NVL(DP_STO_QTY, 0)     AS DP_STO_QTY
		                    , NVL(DP_PO_QTY, 0)      AS DP_PO_QTY
		                    , NVL(RT_QTY, 0)         AS RT_QTY
		                    , NVL(WD_STO_QTY, 0)     AS WD_STO_QTY
		                    , NVL(WD_SO_QTY, 0)      AS WD_SO_QTY
		                    , NVL(WD_PO_QTY, 0)      AS WD_PO_QTY
		                    , NVL(WD_AJ_DC_QTY, 0)   AS WD_AJ_DC_QTY
		                    , NVL(DP_AJ_DC_QTY, 0)   AS DP_AJ_DC_QTY
		                    , NVL(WD_AJ_DU_QTY, 0)   AS WD_AJ_DU_QTY
		                    , NVL(WD_AJ_SA_QTY,0)        AS WD_AJ_SA_QTY
<!-- 		                    , NVL(DP_STO_QTY, 0) + NVL(DP_PO_QTY, 0) + NVL(RT_QTY, 0)
		                      + NVL(WD_STO_QTY, 0) + NVL(WD_SO_QTY, 0) + NVL(WD_PO_QTY, 0)
		                      + NVL(WD_AJ_DC_QTY, 0) + NVL(DP_AJ_DC_QTY, 0) + NVL(WD_AJ_DU_QTY, 0)
		                      AS DAY_TOTAL_QTY -->
                            , NVL(DP_STO_QTY, 0) + NVL(DP_PO_QTY, 0) + NVL(RT_QTY, 0)
								+ NVL(WD_STO_QTY, 0) + NVL(WD_SO_QTY, 0) + NVL(WD_PO_QTY, 0)
								+ NVL(WD_AJ_DC_QTY, 0) + NVL(DP_AJ_DC_QTY, 0) + NVL(WD_AJ_DU_QTY, 0)
								+ NVL(WD_AJ_SA_QTY, 0)
								AS DAY_TOTAL_QTY		                      
		                    , NVL(DP_STO_BOX, 0)     AS DP_STO_BOX
		                    , NVL(DP_PO_BOX, 0)      AS DP_PO_BOX
		                    , NVL(RT_BOX, 0)         AS RT_BOX
		                    , NVL(WD_STO_BOX, 0)     AS WD_STO_BOX
		                    , NVL(WD_SO_BOX, 0)      AS WD_SO_BOX
		                    , NVL(WD_PO_BOX, 0)      AS WD_PO_BOX
		                    , NVL(WD_AJ_DC_BOX, 0)   AS WD_AJ_DC_BOX
		                    , NVL(DP_AJ_DC_BOX, 0)   AS DP_AJ_DC_BOX
		                    , NVL(WD_AJ_DU_BOX, 0)   AS WD_AJ_DU_BOX
		                    , NVL(WD_AJ_SA_BOX,0)        AS WD_AJ_SA_BOX      
<!-- 		                    , NVL(DP_STO_BOX, 0) + NVL(DP_PO_BOX, 0) + NVL(RT_BOX, 0)
		                      + NVL(WD_STO_BOX, 0) + NVL(WD_SO_BOX, 0) + NVL(WD_PO_BOX, 0)
		                      + NVL(WD_AJ_DC_BOX, 0) + NVL(DP_AJ_DC_BOX, 0) + NVL(WD_AJ_DU_BOX, 0)
		                      AS DAY_TOTAL_BOX -->
		                    ,  NVL(DP_STO_BOX, 0) + NVL(DP_PO_BOX, 0) + NVL(RT_BOX, 0)
							 + NVL(WD_STO_BOX, 0) + NVL(WD_SO_BOX, 0) + NVL(WD_PO_BOX, 0)
							 + NVL(WD_AJ_DC_BOX, 0) + NVL(DP_AJ_DC_BOX, 0) + NVL(WD_AJ_DU_BOX, 0)
							 + NVL(WD_AJ_SA_BOX, 0)
								AS DAY_TOTAL_BOX
		                    , ADDDATE             AS ADDDATE
		                    , ADDWHO              AS ADDWHO
		                    , EDITWHO             AS EDITWHO
		                    , CUSTKEY             AS CUSTKEY
		                    , CUSTNAME            AS CUSTNAME
		                    , DOCDT               AS DOCDT
		                FROM
		                    (
		                        SELECT
		                              TB.DELIVERYDATE      AS DELIVERYDATE
		                            , MAX(TB.DOCDT)        AS DOCDT
		                            , TB.DOCNO             AS DOCNO
		                            , TB.REF_DOCID         AS REF_DOCID
		                            , TB.REF_CUST_DOCID    AS REF_CUST_DOCID
		                            , TB.DOCLINE           AS DOCLINE
		                            , TB.SKU               AS SKU
		                            , TB.ORGANIZE          AS ORGANIZE
		                            , TB.STOCKID           AS STOCKID
		                            , TB.STORERKEY		   AS STORERKEY
		                            
		                            ,TB.DCCODE
		                            , CASE
		                                  WHEN TB.DOCTYPE = 'DP' AND TB.WORKPROCESSCODE <![CDATA[=]]>   'STO' THEN 'DP_STO'
		                                  WHEN TB.DOCTYPE = 'DP' AND TB.WORKPROCESSCODE <![CDATA[<>]]> 'STO' THEN 'DP_PO'
		                                  WHEN TB.DOCTYPE = 'RT' THEN 'RT'
		                                  WHEN TB.DOCTYPE = 'WD' AND TB.WORKPROCESSCODE = 'STO' THEN 'WD_STO'
		                                  WHEN TB.DOCTYPE = 'WD' AND TB.WORKPROCESSCODE IN ('SO', 'JASO') THEN 'WD_SO'
		                                  WHEN TB.DOCTYPE = 'WD' AND TB.WORKPROCESSCODE = 'PO' THEN 'WD_PO'
		                                  WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE  <![CDATA[<>]]> 'DP' AND TB.ORDERTYPE LIKE 'DD%' THEN 'WD_AJ_DC'
		                                  WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE <![CDATA[=]]> 'DP' AND TB.ORDERTYPE LIKE 'DD%' THEN 'DP_AJ_DC'
		                                  WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE  <![CDATA[<>]]>'DP' AND TB.ORDERTYPE LIKE 'DU%' THEN 'WD_AJ_DU'
		                                  WHEN TB.DOCTYPE = 'AJ' AND TB.ORDERTYPE = 'SARAJ' THEN 'WD_AJ_SA'
		                                  ELSE TB.DOCTYPE
		                              END                  AS DOCTYPE
		                            , SUM(TB.CONFIRMQTY * (
		                                  CASE
		                                      WHEN TB.DOCTYPE IN ('RT', 'DP') THEN 1
		                                      ELSE CASE
		                                          WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE = 'DP' THEN 1
		                                          ELSE -1
		                                      END
		                                  END
		                              ))                   AS CONFIRMQTY
		                            , SUM(TB.CONFIRMBOX * (
		                                  CASE
		                                      WHEN TB.DOCTYPE IN ('RT', 'DP') THEN 1
		                                      ELSE CASE
		                                          WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE = 'DP' THEN 1
		                                          ELSE -1
		                                      END
		                                  END
		                              ))                   AS CONFIRMBOX
		                            , TO_CHAR(MIN(TB.ADDDATE), 'yyyy-mm-dd hh24:mi:ss') AS ADDDATE
		                            , MIN(TB.ADDWHO)      AS ADDWHO
		                            , MIN(TB.EDITWHO)     AS EDITWHO
		                            , MIN(
		                                  CASE
		                                      WHEN TB.DOCTYPE IN ('DP', 'RT') THEN TB.FROM_CUSTKEY
		                                      ELSE TB.TO_CUSTKEY
		                                  END
		                              )                   AS CUSTKEY
		                            , MIN(
		                                  CASE
		                                      WHEN TB.DOCTYPE IN ('DP', 'RT') THEN TB.FROM_CUSTNAME
		                                      ELSE TB.TO_CUSTNAME
		                                  END
		                              )                   AS CUSTNAME
		                        FROM
		                            (
		                                SELECT
		                                      
		                                      A.DELIVERYDATE         AS DELIVERYDATE
		                                    , A.DOCDT                AS DOCDT
		                                    , A.DOCNO                AS DOCNO
		                                    , A.DCCODE
		                                    , A.STORERKEY
		                                    , A.REF_DOCID            AS REF_DOCID
		                                    , A.REF_CUST_DOCID       AS REF_CUST_DOCID
		                                    , A.DOCLINE              AS DOCLINE
		                                    , A.SKU                  AS SKU
		                                    , A.ORGANIZE             AS ORGANIZE
		                                    , A.DOCTYPE              AS DOCTYPE
		                                    , A.IOTYPE               AS IOTYPE
		                                    , A.ORDERTYPE            AS ORDERTYPE
		                                    , A.WORKPROCESSCODE      AS WORKPROCESSCODE
		                                    
		                                    , CASE
		                                          WHEN A.DOCTYPE = 'WD' THEN WD_TB.CONFIRMQTY
		                                          WHEN A.DOCTYPE = 'DP' THEN DP_TB.CONFIRMQTY
		                                          WHEN A.DOCTYPE = 'AJ' THEN AJ_TB.CONFIRMQTY
		                                          WHEN A.DOCTYPE = 'RT' THEN RT_TB.CONFIRMQTY
		                                      END                    AS CONFIRMQTY
		                                    , CASE
		                                          WHEN A.DOCTYPE = 'WD' THEN WD_TB.ETCQTY2
		                                          WHEN A.DOCTYPE = 'DP' THEN DP_TB.ETCQTY2
		                                          WHEN A.DOCTYPE = 'AJ' THEN AJ_TB.ETCQTY2
		                                          WHEN A.DOCTYPE = 'RT' THEN RT_TB.ETCQTY2
		                                      END                    AS CONFIRMBOX
		                                    , CASE
		                                          WHEN A.DOCTYPE = 'WD' THEN WD_TB.STOCKID
		                                          WHEN A.DOCTYPE = 'DP' THEN DP_TB.STOCKID
		                                          WHEN A.DOCTYPE = 'AJ' THEN AJ_TB.STOCKID
		                                          WHEN A.DOCTYPE = 'RT' THEN RT_TB.STOCKID
		                                      END                    AS STOCKID
		                                    , A.ADDDATE              AS ADDDATE
		                                    , A.ADDWHO               AS ADDWHO
		                                    , CASE
		                                          WHEN A.DOCTYPE = 'WD' THEN WD_TB.EDITWHO
		                                          WHEN A.DOCTYPE = 'DP' THEN DP_TB.EDITWHO
		                                          WHEN A.DOCTYPE = 'AJ' THEN AJ_TB.EDITWHO
		                                          WHEN A.DOCTYPE = 'RT' THEN RT_TB.EDITWHO
		                                      END                    AS EDITWHO
		                                    , B.TO_CUSTKEY           AS TO_CUSTKEY
		                                    , B.TO_CUSTNAME          AS TO_CUSTNAME
		                                    , B.FROM_CUSTKEY         AS FROM_CUSTKEY
		                                    , B.FROM_CUSTNAME        AS FROM_CUSTNAME
		                                FROM
		                                    DM_DOCUMENT_D A
		                                JOIN
		                                    DM_DOCUMENT_H B
		                                    ON  A.DCCODE       = B.DCCODE
		                                    AND A.DOCTYPE      = B.DOCTYPE
		                                    AND A.DELIVERYDATE = B.DELIVERYDATE
		                                    AND A.DOCNO        = B.DOCNO
								            AND A.STATUS       = '90' /*상태(90:확정완료)*/
								      		AND A.DEL_YN       = 'N' 	                                    
		                                LEFT OUTER JOIN
		                                    AJ_INPLAN AJ_TB
		                                    ON  A.DCCODE   = AJ_TB.DCCODE
		                                    AND A.DOCNO    = AJ_TB.SLIPNO
		                                    AND A.DOCLINE  = AJ_TB.SLIPLINE
		                                    AND A.DOCTYPE  = 'AJ'
		                                LEFT OUTER JOIN
		                                    WD_INVOICE_SN WD_TB
		                                    ON  A.DCCODE       = WD_TB.DCCODE
		                                    AND A.ORGANIZE     = WD_TB.ORGANIZE
		                                    AND A.STORERKEY    = WD_TB.STORERKEY
		                                    AND A.DELIVERYDATE = WD_TB.WD_SLIPDT
		                                    AND A.DOCNO        = WD_TB.WD_SLIPNO
		                                    AND A.DOCLINE      = WD_TB.WD_SLIPLINE
		                                    AND A.DOCTYPE      = 'WD'
		                                LEFT OUTER JOIN
		                                    DP_INVOICE_SN DP_TB
		                                    ON  A.DCCODE       = DP_TB.DCCODE
		                                    AND A.ORGANIZE     = DP_TB.ORGANIZE
		                                    AND A.STORERKEY    = DP_TB.STORERKEY
		                                    AND A.DELIVERYDATE = DP_TB.SLIPDT
		                                    AND A.DOCNO        = DP_TB.SLIPNO
		                                    AND A.DOCLINE      = DP_TB.SLIPLINE
		                                    AND A.DOCTYPE      = 'DP'
		                                LEFT OUTER JOIN
		                                    RT_INSPECT RT_TB
		                                    ON  A.DCCODE    = RT_TB.DCCODE
		                                    AND A.ORGANIZE  = RT_TB.ORGANIZE
		                                    AND A.STORERKEY = RT_TB.STORERKEY
		                                    AND A.DOCNO     = RT_TB.DOCNO
		                                    AND A.DOCLINE   = RT_TB.DOCLINE
		                                    AND A.DOCTYPE   = 'RT'
		                                WHERE
		                                    A.DCCODE        = #{fixDcCode}
		                                <if test="organize != null and organize != ''">
											AND A.ORGANIZE = #{organize}
										 </if> 
		                                    AND A.DELIVERYDATE <![CDATA[>=]]> #{fromDeliveryDate}
		                                    AND A.DELIVERYDATE <![CDATA[<=]]> #{toDeliveryDate}
		                                    AND A.SKU         = #{sku}
		                                    
		                            ) TB
		                        GROUP BY
		                              TB.DELIVERYDATE
		                            , TB.DOCNO
		                            , TB.REF_DOCID
		                            , TB.REF_CUST_DOCID
		                            , TB.STORERKEY        
      								, TB.DCCODE           
		                            , TB.DOCLINE
		                            , TB.SKU
		                            , TB.ORGANIZE
		                            , TB.STOCKID
							        , TB.STORERKEY         
							        , TB.DCCODE
							        , TB.STORERKEY                		                            
		                            , CASE
		                                  WHEN TB.DOCTYPE = 'DP' AND TB.WORKPROCESSCODE <![CDATA[=]]> 'STO' THEN 'DP_STO'
		                                  WHEN TB.DOCTYPE = 'DP' AND TB.WORKPROCESSCODE <![CDATA[<>]]> 'STO' THEN 'DP_PO'
		                                  WHEN TB.DOCTYPE = 'RT' THEN 'RT'
		                                  WHEN TB.DOCTYPE = 'WD' AND TB.WORKPROCESSCODE <![CDATA[=]]> 'STO' THEN 'WD_STO'
		                                  WHEN TB.DOCTYPE = 'WD' AND TB.WORKPROCESSCODE IN ('SO', 'JASO') THEN 'WD_SO'
		                                  WHEN TB.DOCTYPE = 'WD' AND TB.WORKPROCESSCODE = 'PO' THEN 'WD_PO'
		                                  WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE  <![CDATA[<>]]> 'DP' AND TB.ORDERTYPE LIKE 'DD%' THEN 'WD_AJ_DC'
		                                  WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE <![CDATA[=]]> 'DP' AND TB.ORDERTYPE LIKE 'DD%' THEN 'DP_AJ_DC'
		                                  WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE  <![CDATA[<>]]> 'DP' AND TB.ORDERTYPE LIKE 'DU%' THEN 'WD_AJ_DU'
		                                  WHEN TB.DOCTYPE = 'AJ' AND TB.ORDERTYPE = 'SARAJ' THEN 'WD_AJ_SA'
		                                  ELSE TB.DOCTYPE
		                              END
		                     ) T
		                PIVOT (
		                    SUM(CONFIRMQTY) AS QTY,
		                    SUM(CONFIRMBOX) AS BOX
		                    FOR DOCTYPE IN (
		                          'DP_STO'    AS DP_STO
		                        , 'DP_PO'     AS DP_PO
		                        , 'RT'        AS RT
		                        , 'WD_STO'    AS WD_STO
		                        , 'WD_SO'     AS WD_SO
		                        , 'WD_PO'     AS WD_PO
		                        , 'DP_AJ_DC'  AS DP_AJ_DC
		                        , 'WD_AJ_DC'  AS WD_AJ_DC
		                        , 'WD_AJ_DU'  AS WD_AJ_DU
		                        , 'WD_AJ_SA'  AS WD_AJ_SA
		                    )
		                )
		            ) K
	         JOIN
	            ST_SNINFO
	            ON K.STOCKID = ST_SNINFO.STOCKID
	            AND K.STORERKEY = ST_SNINFO.STORERKEY
	              <if test="blNo != null and blNo != ''">
	            
	            AND  (K.DOCNO='기초재고' OR ST_SNINFO.CONVSERIALNO LIKE '%'|| #{blNo} || '%' ) 
	            </if>
	        LEFT OUTER JOIN
	            MS_SKU
	            ON K.SKU = MS_SKU.SKU
	            AND MS_SKU.STORERKEY = K.STORERKEY
		    ) K_OUT
		WHERE
		    1 = 1
		GROUP BY
		    K_OUT.SKU
		   , K_OUT.ORGANIZE
		ORDER BY
		    K_OUT.SKU
		   ,  K_OUT.ORGANIZE
	</select>  
	
	<select id="getStDailyInoutExDcDetailList" resultType="StDailyInoutExDcDetailResDto">
		SELECT /* [stDailyInoutExDcService.sqlx][getStDailyInoutExDcDetailList][외부비축상품별수불현황 상세 조회][parkJinWoo][20250710] */
		         K.SKU                       AS SKU                 /* 상품코드 */
		       , K.DOCTYPE                   AS DOCTYPE             /* 문서유형 */
		       , K.DELIVERYTYPE              AS DELIVERYTYPE        /* 출 / 입고구분 */
		       , K.DELIVERYDATE              AS DELIVERYDATE        /* 처리일자 */
		       , K.CONFIRMQTY                AS CONFIRMQTY          /* 확정수량 */
		       <!-- ,  CASE
				    WHEN NVL(K.CONFIRMQTY, 0) = 0 THEN 0
				    WHEN ABS(NVL(K.CONFIRMBOX, 0)) > 0 THEN K.CONFIRMBOX
				    ELSE
				      CASE
				        WHEN K.CONFIRMQTY >= 0 THEN
				             CEIL( K.CONFIRMQTY / NULLIF( NVL(MS_SKU.QTYPERBOX, NVL(MS_SKU.QTYPERBOX, 0)), 0 ) )
				        ELSE
				            -CEIL( ABS(K.CONFIRMQTY) / NULLIF( NVL(MS_SKU.QTYPERBOX, NVL(MS_SKU.QTYPERBOX, 0)), 0 ) )
				      END
				  END AS CONFIRMBOX	 /* 박스 확정 */ -->
				  ,K.CONFIRMBOX	 AS CONFIRMBOX	 /* 박스 확정 */
		       , K.CUSTKEY                   AS CUSTKEY             /* 거래처코드 */
		       , NVL(K.CUSTNAME,FN_DESCR_CUST(K.STORERKEY,  K.CUSTKEY)) AS CUSTNAME
		       , ST_SNINFO.CONVSERIALNO      AS CONVSERIALNO        /* 변환시리얼 */
		       , ST_SNINFO.SERIALNO          AS SERIALNO            /* 시리얼번호 */
		       , ( SELECT FN_CODEDESCR(#{gStorerkey}, 'CONTRACTTYPE_SN', ST_SNINFO.CONTRACTTYPE)
		             FROM DUAL )               AS CONTRACTTYPE       /* 계약구분 */
		       , ST_SNINFO.CONTRACTCUSTKEY    AS CONTRACTCUSTKEY     /* 계약사코드 */
		       , ( SELECT DESCRIPTION
		             FROM MS_CUST
		            WHERE MS_CUST.STORERKEY = #{gStorerkey}
		              AND MS_CUST.CUSTKEY   = ST_SNINFO.CONTRACTCUSTKEY
		              AND ROWNUM = 1 )        AS CONTRACTCUSTNAME    /* 계약사명 */
		       , ST_SNINFO.POKEY              AS POKEY              /* 발주KEY */
		       , ST_SNINFO.POLINE             AS POLINE             /* 발주LINE */
		       , NVL( ( SELECT NVL(TRIM(USER_NM), K.ADDWHO)
		                  FROM FRAMEONE_USER
		                 WHERE (FRAMEONE_USER.USER_NO = K.ADDWHO
		                        OR FRAMEONE_USER.USER_ID = K.ADDWHO)
		                   AND ROWNUM = 1 ), K.ADDWHO ) AS ADDWHO    /* 등록자 */
		       , NVL( ( SELECT NVL(TRIM(USER_NM), K.EDITWHO)
		                  FROM FRAMEONE_USER
		                 WHERE (FRAMEONE_USER.USER_NO = K.EDITWHO
		                        OR FRAMEONE_USER.USER_ID = K.EDITWHO)
		                   AND ROWNUM = 1 ), K.EDITWHO ) AS EDITWHO  /* 수정자 */
		       , K.ADDDATE                  AS ADDDATE              /* 등록일시 */
		       , K.EDITDATE					AS EDITDATE				/*수정일시*/
		       , K.ADDWHO					AS ADDWHOID
		       , K.EDITWHO					AS EDITWHOID
		    FROM 
				(SELECT
	                   TB.DELIVERYDATE      AS DELIVERYDATE
						, TB.DELIVERYTYPE	   AS DELIVERYTYPE  
						, MAX(TB.DOCDT)        AS DOCDT
						, TB.DOCNO             AS DOCNO
						, TB.REF_DOCID         AS REF_DOCID
						, TB.REF_CUST_DOCID    AS REF_CUST_DOCID
						, TB.DOCLINE           AS DOCLINE
						, TB.SKU               AS SKU
						, TB.ORGANIZE          AS ORGANIZE
						, TB.STOCKID           AS STOCKID
						, TB.STORERKEY		
						, CASE
						WHEN TB.DOCTYPE = 'DP' AND TB.WORKPROCESSCODE  =    'STO' THEN 'DP_STO'
						WHEN TB.DOCTYPE = 'DP' AND TB.WORKPROCESSCODE <![CDATA[<>]]> 'STO' THEN 'DP_PO'
						WHEN TB.DOCTYPE = 'RT' THEN 'RT'
						WHEN TB.DOCTYPE = 'WD' AND TB.WORKPROCESSCODE = 'STO' THEN 'WD_STO'
						WHEN TB.DOCTYPE = 'WD' AND TB.WORKPROCESSCODE IN ('SO', 'JASO') THEN 'WD_SO'
						WHEN TB.DOCTYPE = 'WD' AND TB.WORKPROCESSCODE = 'PO' THEN 'WD_PO'
						WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE  <![CDATA[<>]]>  'DP' AND TB.ORDERTYPE LIKE 'DD%' THEN 'WD_AJ_DC'
						WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE  =  'DP' AND TB.ORDERTYPE LIKE 'DD%' THEN 'DP_AJ_DC'
						WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE  <![CDATA[<>]]> 'DP' AND TB.ORDERTYPE LIKE 'DU%' THEN 'WD_AJ_DU'
						WHEN TB.DOCTYPE = 'AJ' AND TB.ORDERTYPE = 'SARAJ' THEN 'WD_AJ_SA'
						ELSE TB.DOCTYPE
						END                  AS DOCTYPE
						, SUM(TB.CONFIRMQTY * (
						CASE
						WHEN TB.DOCTYPE IN ('RT', 'DP') THEN 1
						ELSE CASE
						WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE = 'DP' THEN 1
						ELSE -1
						END
						END
						))                   AS CONFIRMQTY
						, SUM(TB.CONFIRMBOX * (
						CASE
						WHEN TB.DOCTYPE IN ('RT', 'DP') THEN 1
						ELSE CASE
						WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE = 'DP' THEN 1
						ELSE -1
						END
						END
						))                   AS CONFIRMBOX
						, TO_CHAR(MIN(TB.ADDDATE), 'yyyy-mm-dd hh24:mi:ss') AS ADDDATE
						, MIN(TB.ADDWHO)      AS ADDWHO
						, MIN(TB.EDITWHO)     AS EDITWHO
						, MIN(TB.EDITDATE)     AS EDITDATE
						, MIN(
						CASE
						WHEN TB.DOCTYPE IN ('DP', 'RT') THEN TB.FROM_CUSTKEY
						ELSE TB.TO_CUSTKEY
						END
						)                   AS CUSTKEY
						, MIN(
						CASE
						WHEN TB.DOCTYPE IN ('DP', 'RT') THEN TB.FROM_CUSTNAME
						ELSE TB.TO_CUSTNAME
						END
						)                   AS CUSTNAME
						FROM
						(
						SELECT
							
							A.DELIVERYDATE         AS DELIVERYDATE
							, A.DOCDT                AS DOCDT
							, A.DOCNO                AS DOCNO
							, A.REF_DOCID            AS REF_DOCID
							, A.REF_CUST_DOCID       AS REF_CUST_DOCID
							, A.DOCLINE              AS DOCLINE
							, A.SKU                  AS SKU
							, A.ORGANIZE             AS ORGANIZE
							, A.DOCTYPE              AS DOCTYPE
							, A.IOTYPE               AS IOTYPE
							, A.ORDERTYPE            AS ORDERTYPE
							, A.WORKPROCESSCODE      AS WORKPROCESSCODE
							, A.STORERKEY
							, B.DELIVERYTYPE         AS DELIVERYTYPE
							, CASE
							WHEN A.DOCTYPE = 'WD' THEN WD_TB.CONFIRMQTY
							WHEN A.DOCTYPE = 'DP' THEN DP_TB.CONFIRMQTY
							WHEN A.DOCTYPE = 'AJ' THEN AJ_TB.CONFIRMQTY
							WHEN A.DOCTYPE = 'RT' THEN RT_TB.CONFIRMQTY
							END                    AS CONFIRMQTY
							, CASE
							WHEN A.DOCTYPE = 'WD' THEN WD_TB.ETCQTY2
							WHEN A.DOCTYPE = 'DP' THEN DP_TB.ETCQTY2
							WHEN A.DOCTYPE = 'AJ' THEN AJ_TB.ETCQTY2
							WHEN A.DOCTYPE = 'RT' THEN RT_TB.ETCQTY2
							END                    AS CONFIRMBOX
							, CASE
							WHEN A.DOCTYPE = 'WD' THEN WD_TB.STOCKID
							WHEN A.DOCTYPE = 'DP' THEN DP_TB.STOCKID
							WHEN A.DOCTYPE = 'AJ' THEN AJ_TB.STOCKID
							WHEN A.DOCTYPE = 'RT' THEN RT_TB.STOCKID
							END                    AS STOCKID
							, A.ADDDATE              AS ADDDATE
							, A.ADDWHO               AS ADDWHO
							, CASE
							WHEN A.DOCTYPE = 'WD' THEN WD_TB.EDITWHO
							WHEN A.DOCTYPE = 'DP' THEN DP_TB.EDITWHO
							WHEN A.DOCTYPE = 'AJ' THEN AJ_TB.EDITWHO
							WHEN A.DOCTYPE = 'RT' THEN RT_TB.EDITWHO
							END                    AS EDITWHO
							, CASE
							WHEN A.DOCTYPE = 'WD' THEN WD_TB.EDITDATE
							WHEN A.DOCTYPE = 'DP' THEN DP_TB.EDITDATE
							WHEN A.DOCTYPE = 'AJ' THEN AJ_TB.EDITDATE
							WHEN A.DOCTYPE = 'RT' THEN RT_TB.EDITDATE
							END                    AS EDITDATE
							, B.TO_CUSTKEY           AS TO_CUSTKEY
							, B.TO_CUSTNAME          AS TO_CUSTNAME
							, B.FROM_CUSTKEY         AS FROM_CUSTKEY
							, B.FROM_CUSTNAME        AS FROM_CUSTNAME
							FROM
							DM_DOCUMENT_D A
							JOIN
							DM_DOCUMENT_H B
							ON  A.DCCODE       = B.DCCODE
							AND A.DOCTYPE      = B.DOCTYPE
							AND A.DELIVERYDATE = B.DELIVERYDATE
							AND A.DOCNO        = B.DOCNO
							AND A.STATUS       = '90' /*상태(90:확정완료)*/
							AND A.DEL_YN       = 'N' 	                                    
							LEFT OUTER JOIN
							AJ_INPLAN AJ_TB
							ON  A.DCCODE   = AJ_TB.DCCODE
							AND A.DOCNO    = AJ_TB.SLIPNO
							AND A.DOCLINE  = AJ_TB.SLIPLINE
							AND A.DOCTYPE  = 'AJ'
							LEFT OUTER JOIN
							WD_INVOICE_SN WD_TB
							ON  A.DCCODE       = WD_TB.DCCODE
							AND A.ORGANIZE     = WD_TB.ORGANIZE
							AND A.STORERKEY    = WD_TB.STORERKEY
							AND A.DELIVERYDATE = WD_TB.WD_SLIPDT
							AND A.DOCNO        = WD_TB.WD_SLIPNO
							AND A.DOCLINE      = WD_TB.WD_SLIPLINE
							AND A.DOCTYPE      = 'WD'
							LEFT OUTER JOIN
							DP_INVOICE_SN DP_TB
							ON  A.DCCODE       = DP_TB.DCCODE
							AND A.ORGANIZE     = DP_TB.ORGANIZE
							AND A.STORERKEY    = DP_TB.STORERKEY
							AND A.DELIVERYDATE = DP_TB.SLIPDT
							AND A.DOCNO        = DP_TB.SLIPNO
							AND A.DOCLINE      = DP_TB.SLIPLINE
							AND A.DOCTYPE      = 'DP'
							LEFT OUTER JOIN
							RT_INSPECT RT_TB
							ON  A.DCCODE    = RT_TB.DCCODE
							AND A.ORGANIZE  = RT_TB.ORGANIZE
							AND A.STORERKEY = RT_TB.STORERKEY
							AND A.DOCNO     = RT_TB.DOCNO
							AND A.DOCLINE   = RT_TB.DOCLINE
							AND A.DOCTYPE   = 'RT'
							WHERE 1=1
							AND	  A.DCCODE      = #{fixDcCode}
							AND A.DELIVERYDATE <![CDATA[>=]]>#{fromDeliveryDate}
							AND A.DELIVERYDATE <![CDATA[<=]]> #{toDeliveryDate}
							AND A.SKU         = #{sku}
							<if test="organize != null and organize != ''">
								AND A.ORGANIZE = #{organize}
							</if>
						
						) TB
						GROUP BY
							TB.DELIVERYDATE
							, TB.DELIVERYTYPE
							, TB.DOCNO
							, TB.REF_DOCID
							, TB.REF_CUST_DOCID
							, TB.DOCLINE
							, TB.SKU
							, TB.ORGANIZE
							, TB.STOCKID
							, TB.STORERKEY
							, CASE
							WHEN TB.DOCTYPE = 'DP' AND TB.WORKPROCESSCODE  =  'STO' THEN 'DP_STO'
							WHEN TB.DOCTYPE = 'DP' AND TB.WORKPROCESSCODE <![CDATA[<>]]> 'STO' THEN 'DP_PO'
							WHEN TB.DOCTYPE = 'RT' THEN 'RT'
							WHEN TB.DOCTYPE = 'WD' AND TB.WORKPROCESSCODE  =  'STO' THEN 'WD_STO'
							WHEN TB.DOCTYPE = 'WD' AND TB.WORKPROCESSCODE IN ('SO', 'JASO') THEN 'WD_SO'
							WHEN TB.DOCTYPE = 'WD' AND TB.WORKPROCESSCODE = 'PO' THEN 'WD_PO'
							WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE   <![CDATA[<>]]>  'DP' AND TB.ORDERTYPE LIKE 'DD%' THEN 'WD_AJ_DC'
							WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE  =  'DP' AND TB.ORDERTYPE LIKE 'DD%' THEN 'DP_AJ_DC'
							WHEN TB.DOCTYPE = 'AJ' AND TB.IOTYPE   <![CDATA[<>]]>  'DP' AND TB.ORDERTYPE LIKE 'DU%' THEN 'WD_AJ_DU'
							WHEN TB.DOCTYPE = 'AJ' AND TB.ORDERTYPE = 'SARAJ' THEN 'WD_AJ_SA'
							ELSE TB.DOCTYPE
							END
						)K
					 JOIN ST_SNINFO
					ON K.STOCKID = ST_SNINFO.STOCKID
					AND K.STORERKEY = ST_SNINFO.STORERKEY
					JOIN MS_SKU
					ON K.SKU = MS_SKU.SKU
					AND MS_SKU.STORERKEY = K.STORERKEY
						
					<if test="blNo != null and blNo != ''">
						AND (K.DOCNO='기초재고' OR ST_SNINFO.CONVSERIALNO LIKE '%'|| #{blNo} || '%' ) 
					</if>
				ORDER BY DELIVERYDATE	 	  	        						                             
		</select>  
</mapper>