<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper
  PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
  "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="stInquiryResultService">

    <select id="getTab1MasterList" resultType="cjfw.wms.st.dto.StInquiryResultResDto">
		SELECT  /* [stInquiryResultService.sqlx][stInquiryResultService.getTab1MasterList][조사지시현황(로케이션별/상품별)][sss][20250925] */
		          A.INQUIRY_NAME      /*별칭*/         
                <!--, A.INQUIRYNO         /*조사번호*/       
                , (SELECT MAX(INQUIRYNO)
                     FROM ST_INQUIRY AA
                    WHERE 1=1
                      AND AA.INQUIRY_NAME = A.INQUIRY_NAME
                      AND AA.PRIORITY=1
                     GROUP BY AA.INQUIRY_NAME)    AS INQUIRYNO     
                     -->
                     <!-- 1회차의 INQUIRYNO 가져오기. MIN 을 MAX 로 바꾸면 마지막 회차의 INQUIRYNO 가져옴 -->
                , (SELECT MIN(INQUIRYNO)
                     FROM ST_INQUIRY AA
                    WHERE 1=1
                      AND AA.INQUIRY_NAME = A.INQUIRY_NAME
                      AND AA.DCCODE = A.DCCODE
                      AND AA.PRIORITY= (SELECT MIN(TO_NUMBER(AAA.PRIORITY)) PRIORITY
                                          FROM ST_INQUIRY AAA
                                         WHERE 1=1
                                           AND AAA.INQUIRY_NAME = A.INQUIRY_NAME
                                           AND AAA.DCCODE = A.DCCODE
                                           AND AAA.INQUIRYDT=A.INQUIRYDT
                                         GROUP BY AAA.INQUIRY_NAME)
                   GROUP BY AA.INQUIRY_NAME) AS   INQUIRYNO                                
                , A.DCCODE            /*센터코드*/       
                , A.ORGANIZE          /*조직코드*/       
                , A.AREA              /*지역코드*/       
                , A.INQUIRYDT         /*조사일자*/       
                , A.STATUS            /*상태*/         
                , A.STATUSNM          /*상태명*/        
                , A.WHAREA            /*창고구역*/       
                , A.WHAREAFLOOR       /*창고층*/        
                , A.SKU               /*상품코드*/       
                , A.SKUNAME           /*상품명*/        
                , A.STOCKID           /*재고ID*/   
                , A.MOBILE_ADD_YN     /*모바일추가여부*/    
                , DECODE(A.MOBILE_ADD_YN,'N','Y','Y','N')   AS INSTRUCTION_YN   /* 지시여부 */
                , A.UOM               /*단위*/         
                , CASE WHEN A.DIFFQTY10 != 0 THEN A.DIFFQTY10
                       WHEN A.DIFFQTY09 != 0 THEN A.DIFFQTY09
                       WHEN A.DIFFQTY08 != 0 THEN A.DIFFQTY08
                       WHEN A.DIFFQTY07 != 0 THEN A.DIFFQTY07
                       WHEN A.DIFFQTY06 != 0 THEN A.DIFFQTY06
                       WHEN A.DIFFQTY05 != 0 THEN A.DIFFQTY05
                       WHEN A.DIFFQTY04 != 0 THEN A.DIFFQTY04
                       WHEN A.DIFFQTY03 != 0 THEN A.DIFFQTY03
                       WHEN A.DIFFQTY02 != 0 THEN A.DIFFQTY02
                       WHEN A.DIFFQTY01 != 0 THEN A.DIFFQTY01
                       ELSE 0 END   AS TOTALDIFFQTY      /*총차이수량*/    
--                 , 0 AS  TOTALDIFFAMT      /*총차이금액*/
                , A.ORDERQTY          /*지시수량*/       
                , A.LASTPRIORITY      /*최종차수*/       
                , A.PRIORITY01        /*1차수량*/       
                , A.DIFFQTY01         /*1차차이*/       
                , A.PRIORITY02        /*2차수량*/       
                , A.DIFFQTY02         /*2차차이*/       
                , A.PRIORITY03        /*3차수량*/       
                , A.DIFFQTY03         /*3차차이*/       
                , A.PRIORITY04        /*4차수량*/       
                , A.DIFFQTY04         /*4차차이*/       
                , A.PRIORITY05        /*5차수량*/       
                , A.DIFFQTY05         /*5차차이*/       
                , A.PRIORITY06        /*6차수량*/       
                , A.DIFFQTY06         /*6차차이*/       
                , A.PRIORITY07        /*7차수량*/       
                , A.DIFFQTY07         /*7차차이*/       
                , A.PRIORITY08        /*8차수량*/       
                , A.DIFFQTY08         /*8차차이*/       
                , A.PRIORITY09        /*9차수량*/       
                , A.DIFFQTY09         /*9차차이*/       
                , A.PRIORITY10        /*10차수량*/      
                , A.DIFFQTY10         /*10차차이*/      
                , A.STOCKGRADE        /*재고등급*/       
                , A.STOCKGRADENM      /*재고등급명*/      
                , A.LOTTABLE01        /*유통기한*/
                , A.DURATION_TERM     /*유통기한정보*/
                , A.SERIALNO          /*시리얼번호*/
                , A.COMMITYN          /*처리여부*/                            
                , A.LOTTYPE           /*실사구분(0:소비기한,1:재고조사)*/          
                , A.INQUIRYQTY        /*조사수량*/                         
                , A.DIFFQTY           /*차이수량*/                         
                , A.REASONCODE        /*사유코드*/                         
                , A.REASONMSG         /*사유메시지*/                        
                , A.DURATION          /*유통기간*/                         
                , A.DURATIONTYPE      /*유통기간타입*/                       
                , A.STORERKEY         /*화주코드*/                         
                , A.ZONE              /*존*/                            
                , A.ZONENAME          /*존명*/                           
                , A.LOC               /*로케이션-상품별tab일 경우 미사용*/          
                , A.LOT               /*LOT*/                          
                , A.STOCKQTY          /*재고수량*/  
                , #{reqFlag}  AS REQ_FLAG /*요청구분(1:로케이션별,2:상품별)*/                      
          FROM (                
		      SELECT
                     ST_INQUIRY.INQUIRY_NAME                                                                            AS INQUIRY_NAME  /*별칭*/
                    <!--,MAX(ST_INQUIRY.INQUIRYNO)                                                                          AS INQUIRYNO     /*조사번호*/--> 
                    ,MAX(ST_INQUIRY.DCCODE)                                                                             AS DCCODE        /*센터코드*/
                    ,ST_INQUIRY.ORGANIZE                                                                                AS ORGANIZE      /*조직코드*/
                    ,ST_INQUIRY.AREA                                                                                    AS AREA          /*지역코드*/
                    ,ST_INQUIRY.INQUIRYDT                                                                               AS INQUIRYDT     /*조사일자*/
                    ,MAX(ST_INQUIRY_LAST.STATUS)                                                                        AS STATUS        /*상태*/
                    ,MAX(FN_CODEDESCR(ST_INQUIRY.STORERKEY, 'STATUS_INQUIRY', ST_INQUIRY_LAST.STATUS))                  AS STATUSNM      /*상태명*/
                    ,MAX(FN_CODEDESCR(ST_INQUIRY.STORERKEY, 'WHAREA'        , MS_LOCATION.WHAREA))                      AS WHAREA        /*창고구역*/
                    ,MAX(FN_CODEDESCR(ST_INQUIRY.STORERKEY, 'WHAREAFLOOR'   , MS_LOCATION.WHAREAFLOOR))                 AS WHAREAFLOOR   /*창고층*/
                    ,ST_INQUIRY.SKU                                                                                     AS SKU           /*상품코드*/
                    ,MAX(MS_SKU.DESCRIPTION)                                                                            AS SKUNAME       /*상품명*/
                    ,MAX(ST_INQUIRY.STOCKID)                                                                            AS STOCKID       /*재고ID*/
                    ,NVL(ST_INQUIRY.MOBILE_ADD_YN,'N')                                                                  AS MOBILE_ADD_YN /*모바일추가여부*/
                    ,MAX(MS_SKU.BASEUOM)                                                                                AS UOM           /*단위*/
                    --,SUM(ST_INQUIRY.SCANQTY_A) - SUM(ST_INQUIRY.ORDERQTY)                                             AS TOTALDIFFQTY  /*총차이수량*/
                    --,(SUM(ST_INQUIRY.SCANQTY_A) - SUM(ST_INQUIRY.ORDERQTY)) * MAX(PRICE.PRICE)                        AS TOTALDIFFAMT  /*총차이금액*/
--                     ,MAX(PRICE.PRICE)                          AS PRICE  /*금액*/
                    ,MAX(ST_INQUIRY.ORDERQTY) KEEP (DENSE_RANK LAST ORDER BY ST_INQUIRY.PRIORITY)                       AS ORDERQTY      /*지시수량 20260123 공두경 변경*/
                    ,MAX(ST_INQUIRY.PRIORITY)                                                                           AS LASTPRIORITY  /*최종차수*/
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 1 THEN ST_INQUIRY.SCANQTY_A ELSE 0 END)                        AS PRIORITY01    /*1차수량*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 1 THEN (ST_INQUIRY.SCANQTY_A-ST_INQUIRY.ORDERQTY) ELSE 0 END)  AS DIFFQTY01     /*1차차이*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 2 THEN ST_INQUIRY.SCANQTY_A ELSE 0 END)                        AS PRIORITY02    /*2차수량*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 2 THEN (ST_INQUIRY.SCANQTY_A-ST_INQUIRY.ORDERQTY) ELSE 0 END)  AS DIFFQTY02     /*2차차이*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 3 THEN ST_INQUIRY.SCANQTY_A ELSE 0 END)                        AS PRIORITY03    /*3차수량*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 3 THEN (ST_INQUIRY.SCANQTY_A-ST_INQUIRY.ORDERQTY) ELSE 0 END)  AS DIFFQTY03     /*3차차이*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 4 THEN ST_INQUIRY.SCANQTY_A ELSE 0 END)                        AS PRIORITY04    /*4차수량*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 4 THEN (ST_INQUIRY.SCANQTY_A-ST_INQUIRY.ORDERQTY) ELSE 0 END)  AS DIFFQTY04     /*4차차이*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 5 THEN ST_INQUIRY.SCANQTY_A ELSE 0 END)                        AS PRIORITY05    /*5차수량*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 5 THEN (ST_INQUIRY.SCANQTY_A-ST_INQUIRY.ORDERQTY) ELSE 0 END)  AS DIFFQTY05     /*5차차이*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 6 THEN ST_INQUIRY.SCANQTY_A ELSE 0 END)                        AS PRIORITY06    /*6차수량*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 6 THEN (ST_INQUIRY.SCANQTY_A-ST_INQUIRY.ORDERQTY) ELSE 0 END)  AS DIFFQTY06     /*6차차이*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 7 THEN ST_INQUIRY.SCANQTY_A ELSE 0 END)                        AS PRIORITY07    /*7차수량*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 7 THEN (ST_INQUIRY.SCANQTY_A-ST_INQUIRY.ORDERQTY) ELSE 0 END)  AS DIFFQTY07     /*7차차이*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 8 THEN ST_INQUIRY.SCANQTY_A ELSE 0 END)                        AS PRIORITY08    /*8차수량*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 8 THEN (ST_INQUIRY.SCANQTY_A-ST_INQUIRY.ORDERQTY) ELSE 0 END)  AS DIFFQTY08     /*8차차이*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 9 THEN ST_INQUIRY.SCANQTY_A ELSE 0 END)                        AS PRIORITY09    /*9차수량*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 9 THEN (ST_INQUIRY.SCANQTY_A-ST_INQUIRY.ORDERQTY) ELSE 0 END)  AS DIFFQTY09     /*9차차이*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 10 THEN ST_INQUIRY.SCANQTY_A ELSE 0 END)                       AS PRIORITY10    /*10차수량*/ 
                    ,SUM(CASE WHEN ST_INQUIRY.PRIORITY = 10 THEN (ST_INQUIRY.SCANQTY_A-ST_INQUIRY.ORDERQTY) ELSE 0 END) AS DIFFQTY10     /*10차차이*/ 
                    ,MAX(ST_INQUIRY.STOCKGRADE)                                                                         AS STOCKGRADE    /*재고등급*/
                    ,MAX(FN_CODEDESCR(ST_INQUIRY.STORERKEY, 'STOCKGRADE', ST_INQUIRY.STOCKGRADE))                       AS STOCKGRADENM  /*재고등급명*/
                    --
                    --
                    ,MAX(CM_LOT.LOTTABLE01)                                     AS LOTTABLE01        /*유통기한*/
                    ,MAX(FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'N') || '/' || MS_SKU.DURATION) AS DURATION_TERM /*유통기한정보*/
                    ,MAX(ST_SNINFO.SERIALNO)                                    AS SERIALNO          /*시리얼번호*/
                    ,MAX(DECODE(ST_INQUIRY.COMMIT_YN, 'Y', '처리완료', '미처리'))   AS COMMITYN          /*처리여부*/
                    ,#{lottype}                                                 AS LOTTYPE           /*실사구분(0:소비기한,1:재고조사)*/
                    ,MAX(ST_INQUIRY.SCANQTY_A)                                  AS INQUIRYQTY        /*조사수량*/
                    ,MAX(ST_INQUIRY.SCANQTY_A) - MAX(ST_INQUIRY.ORDERQTY)       AS DIFFQTY           /*차이수량*/
                    ,MAX(ST_INQUIRY.REASONCODE)                                 AS REASONCODE        /*사유코드*/
                    ,MAX(ST_INQUIRY.REASONMSG)                                  AS REASONMSG         /*사유메시지*/
                    ,MAX(MS_SKU.DURATION)                                       AS DURATION          /*유통기간*/
                    ,MAX(MS_SKU.DURATIONTYPE)                                   AS DURATIONTYPE      /*유통기간타입*/
                    ,MAX(ST_INQUIRY.STORERKEY)                                  AS STORERKEY         /*화주코드*/
                    ,MS_LOCATION.ZONE                                           AS ZONE              /*존*/
                    ,MAX(MS_ZONE.DESCRIPTION)                                   AS ZONENAME          /*존명*/
    			     <choose>
    			       <when test="reqFlag == '1'.toString()"><!-- 로케이션별 -->
    	                  ,MAX(ST_INQUIRY.LOC)                                        AS LOC               /*로케이션-상품별tab일 경우 미사용*/ 
    			       </when>
    			       <otherwise><!-- 상품별 -->
    	                 ,''                                                          AS LOC               /*로케이션-상품별tab일 경우 미사용*/
    			       </otherwise>            
    			     </choose>
                    ,MAX(ST_INQUIRY.LOT)                                        AS LOT               /*LOT*/
                    ,MAX(ST_INQUIRY.STOCKQTY)                                   AS STOCKQTY          /*재고수량*/
    		    FROM ST_INQUIRY
		        JOIN (
			            SELECT A.INQUIRY_NAME ,A.PRIORITY ,A.ORGANIZE ,A.AREA       ,A.INQUIRYDT 
			                  ,A.LOC          ,A.SKU      ,A.STOCKID  ,A.STOCKGRADE ,A.LOT       
			                  ,A.MOBILE_ADD_YN
			                  -- 
			                  ,A.STATUS
			             FROM ST_INQUIRY A
			            WHERE (
			                       A.INQUIRY_NAME ,A.PRIORITY ,A.ORGANIZE ,A.AREA       ,A.INQUIRYDT 
			                      ,A.LOC          ,A.SKU      ,A.STOCKID  ,A.STOCKGRADE ,A.LOT                    
			                      ,A.MOBILE_ADD_YN      
			                  )  IN (
			                         SELECT T1.INQUIRY_NAME ,MAX(T1.PRIORITY) AS PRIORITY ,T1.ORGANIZE ,T1.AREA       ,T1.INQUIRYDT              
			                               ,T1.LOC          ,T1.SKU                       ,T1.STOCKID  ,T1.STOCKGRADE ,T1.LOT                    
			                               ,T1.MOBILE_ADD_YN      
			                           FROM ST_INQUIRY T1    
			                          WHERE T1.STORERKEY = #{gStorerkey}
			                            AND T1.DCCODE    = #{fixdccode}
    		                            AND T1.INQUIRYDT <![CDATA[>=]]> #{dt1} 
    			                        AND T1.INQUIRYDT <![CDATA[<=]]> #{dt2}	  
			                          GROUP BY T1.INQUIRY_NAME             
			                                  ,T1.ORGANIZE                 
			                                  ,T1.AREA                     
			                                  ,T1.INQUIRYDT                
			                                  ,T1.LOC                      
			                                  ,T1.SKU                      
			                                  ,T1.STOCKID                  
			                                  ,T1.STOCKGRADE               
			                                  ,T1.LOT                      
			                                  ,T1.MOBILE_ADD_YN 
			                        )    
		             )  ST_INQUIRY_LAST /*마지막 차수 ROW정보*/      
                  ON ST_INQUIRY.INQUIRY_NAME  = ST_INQUIRY_LAST.INQUIRY_NAME            
                 AND ST_INQUIRY.ORGANIZE      = ST_INQUIRY_LAST.ORGANIZE                
                 AND ST_INQUIRY.AREA          = ST_INQUIRY_LAST.AREA                    
                 AND ST_INQUIRY.INQUIRYDT     = ST_INQUIRY_LAST.INQUIRYDT               
                 AND ST_INQUIRY.LOC           = ST_INQUIRY_LAST.LOC                     
                 AND ST_INQUIRY.SKU           = ST_INQUIRY_LAST.SKU                     
                 AND ST_INQUIRY.STOCKID       = ST_INQUIRY_LAST.STOCKID                 
                 AND ST_INQUIRY.STOCKGRADE    = ST_INQUIRY_LAST.STOCKGRADE              
                 AND ST_INQUIRY.LOT           = ST_INQUIRY_LAST.LOT                     
                 AND ST_INQUIRY.MOBILE_ADD_YN = ST_INQUIRY_LAST.MOBILE_ADD_YN  		               		    
    		    JOIN MS_SKU
    		      ON MS_SKU.STORERKEY = ST_INQUIRY.STORERKEY
    		     AND MS_SKU.SKU       = ST_INQUIRY.SKU
    		    JOIN MS_LOCATION
    		      ON MS_LOCATION.DCCODE = ST_INQUIRY.DCCODE
    		     AND MS_LOCATION.LOC    = ST_INQUIRY.LOC
    		     <if test="wharea != null and wharea != ''">             AND MS_LOCATION.WHAREA      = #{wharea}      </if>
    		     <if test="fromZone != null and fromZone != ''">         AND MS_LOCATION.ZONE <![CDATA[>=]]> #{fromZone} </if>
    		     <if test="toZone != null and toZone != ''">             AND MS_LOCATION.ZONE <![CDATA[<=]]> #{toZone}   </if>
			LEFT JOIN MS_ZONE              
				   ON MS_ZONE.DCCODE           = MS_LOCATION.DCCODE
				  AND MS_ZONE.ZONE             = MS_LOCATION.ZONE		
    		    JOIN CM_LOT
    		      ON CM_LOT.STORERKEY = ST_INQUIRY.STORERKEY
    		     AND CM_LOT.LOT       = ST_INQUIRY.LOT
    		    LEFT OUTER JOIN ST_SNINFO
    		      ON ST_INQUIRY.STORERKEY = ST_SNINFO.STORERKEY
    		     AND ST_INQUIRY.SKU       = ST_SNINFO.SKU
    		     AND ST_INQUIRY.STOCKID   = ST_SNINFO.STOCKID
--     		     LEFT JOIN (SELECT 1000 AS PRICE FROM DUAL) PRICE ON  (1=1) /*TODO: 비용코드명 추후 처리 필요*/
    		    WHERE ST_INQUIRY.STORERKEY = #{gStorerkey}
    		      AND ST_INQUIRY.DCCODE    = #{fixdccode}
    		      AND ST_INQUIRY.DEL_YN = 'N'
    		      <!-- START.권한센터 -->
    		      AND EXISTS (SELECT 1
    	                        FROM CM_USER_AUTHORITY 
    	                       WHERE CM_USER_AUTHORITY.DCCODE    = ST_INQUIRY.DCCODE    
    	                         AND CM_USER_AUTHORITY.STORERKEY = ST_INQUIRY.STORERKEY 
    	                         AND CM_USER_AUTHORITY.ORGANIZE  = ST_INQUIRY.ORGANIZE  
    	                         AND CM_USER_AUTHORITY.AREA      = ST_INQUIRY.AREA  
    	                         AND CM_USER_AUTHORITY.STORERKEY = #{gStorerkey}
    	                         AND CM_USER_AUTHORITY.USERID    = #{gUserId}
    	                         AND CM_USER_AUTHORITY.DCCODE    = #{fixdccode}
    	                         AND CM_USER_AUTHORITY.AREA      = #{gArea}   
    			  	             <!-- 창고.다중검색 -->
			                     <if test="organizeMulti != null and organizeMulti != ''">    
				                     AND CM_USER_AUTHORITY.ORGANIZE IN
				                     <foreach collection="organizeMulti" item="code" open="(" close=")" separator=",">
				                       #{code}
				                     </foreach>
			                     </if>                   
    	                     )
    		      <!-- END.권한센터	--> 
    		      
			      <!-- 창고.다중검색 -->
			      <if test="organizeMulti != null and organizeMulti != ''">    
				     AND ST_INQUIRY.ORGANIZE IN
				     <foreach collection="organizeMulti" item="code" open="(" close=")" separator=",">
				       #{code}
				     </foreach>
			      </if>       		      
    		      
    		      <!-- 실사구분(0:소비기한,1:재고조사) -->
    		      AND ST_INQUIRY.LOTTYPE = #{lottype}    
    			  AND ST_INQUIRY.INQUIRYDT <![CDATA[>=]]> #{dt1} 
    			  AND ST_INQUIRY.INQUIRYDT <![CDATA[<=]]> #{dt2}		
    		      <if test="inquiryno != null and inquiryno != ''">         AND ST_INQUIRY.INQUIRYNO = #{inquiryno}                  </if>
    		      <if test="status != null and status != ''">               AND ST_INQUIRY.STATUS    = #{status}                     </if>
    			  <!-- 조사별칭 -->
    			  <if test="inquiryAlias != null and inquiryAlias != ''">
    			     AND ST_INQUIRY.INQUIRY_NAME LIKE '%'||#{inquiryAlias}|| '%'
    			  </if>		      
    		      <if test="inquirytype != null and inquirytype != ''">     AND ST_INQUIRY.INQUIRYTYPE = #{inquirytype}              </if>
    		      <if test="fromLoc != null and fromLoc != ''">             AND ST_INQUIRY.LOC <![CDATA[>=]]> #{fromLoc}             </if>
    		      <if test="toLoc != null and toLoc != ''">                 AND ST_INQUIRY.LOC <![CDATA[<=]]> #{toLoc}               </if>
    	          
    	          
    	          <!-- START.상품.다중OR검색 -->
    	          <if test="skuMulti != null and skuMulti != '' ">
    			  	<trim prefix="AND (" suffix=")" prefixOverrides="OR">
    			  		<foreach collection="skuMulti" item="item">
    			  			OR ST_INQUIRY.SKU IN
    			  			<foreach collection="item" item="code" open="(" close=")" separator=",">
    			  				#{code} 	 
    			        		</foreach>
    			      	</foreach>
    			    	</trim>			                                    
    	          </if>
    	          <!-- END.상품.다중OR검색 -->		      
    		      
                GROUP BY
                
    			 <choose>
    			   <when test="reqFlag == '1'.toString()"><!-- 로케이션별 -->
    	                 ST_INQUIRY.INQUIRY_NAME
    	               , ST_INQUIRY.ORGANIZE
    	               , ST_INQUIRY.AREA
    	               , ST_INQUIRY.INQUIRYDT
    	               , MS_LOCATION.ZONE
    	               , ST_INQUIRY.LOC
    	               , ST_INQUIRY.SKU
    	               , ST_INQUIRY.STOCKID
    	               , ST_INQUIRY.STOCKGRADE
    	               , ST_INQUIRY.LOT         <!-- 2025.12.10 김동한 추가 테스트 데이터 : 202512090003 이거 총 14개 인데 이 조건 빼면 12개만 나옴 -->
    	               , ST_INQUIRY.MOBILE_ADD_YN 
    			   </when>
    			   <otherwise><!-- 상품별 -->
    	                 ST_INQUIRY.INQUIRY_NAME
    	               , ST_INQUIRY.ORGANIZE
    	               , ST_INQUIRY.AREA
    	               , ST_INQUIRY.INQUIRYDT
    	               , MS_LOCATION.ZONE
    	               --, ST_INQUIRY.LOC
    	               , ST_INQUIRY.SKU
    	               , ST_INQUIRY.STOCKID
    	               , ST_INQUIRY.STOCKGRADE
    	               , ST_INQUIRY.LOT
    	               , ST_INQUIRY.MOBILE_ADD_YN
    			   </otherwise>            
    			</choose>
    		    ORDER BY
    		         ST_INQUIRY.INQUIRY_NAME
                   , ST_INQUIRY.ORGANIZE
                   , ST_INQUIRY.AREA
                   , ST_INQUIRY.INQUIRYDT
                   , MS_LOCATION.ZONE
                   , MAX(ST_INQUIRY.LOC)
                   , ST_INQUIRY.SKU
                   , MAX(ST_INQUIRY.STOCKID)
                   , MAX(ST_INQUIRY.STOCKGRADE)
            ) A
            WHERE 1=1
	</select>

    <select id="getTab2MasterList" resultType="cjfw.wms.st.dto.StInquiryResultResSkuDto">
		SELECT 'dummy' FROM DUAL
    </select>
    
    
    <select id="getSequenceNumber" resultType="cjfw.wms.st.dto.StInquiryResultResDto">
		SELECT /* [stInquiryResultService.sqlx][stInquiryResultService.getSequenceNumber][조사지시현황-순번채번][sss][20250925] */
		       /*
		         재지시는 별칭과 조사번호 변경안되고 SEQ만 증가됨
		           ->20260206@김*원님 요청 by sss
		       */
		       <!--TO_CHAR(SYSDATE,'YYYYMMDD')||#{lottype}||LPAD(A.PRIORITY,3,'0') AS INQUIRYNO-->
		       A.INQUIRYNO    AS INQUIRYNO
		      ,A.INQUIRY_NAME AS INQUIRY_NAME
		      ,A.PRIORITY     AS PRIORITY
		  FROM (
		         SELECT A.INQUIRY_NAME
		               ,B.INQUIRYNO
		               ,(
		                 SELECT NVL(MAX(T1.PRIORITY), 0) + 1
		                   FROM ST_INQUIRY T1
		                  WHERE STORERKEY    = #{gStorerkey}
		                    AND DCCODE       = #{fixdccode}
		                    AND INQUIRY_NAME = A.INQUIRY_NAME
		                ) AS PRIORITY
		          FROM (
		                SELECT TRIM(REGEXP_SUBSTR(VAL,'[^,]+',1,LEVEL)) AS INQUIRY_NAME
		                  FROM (SELECT #{inquiryNameNew} AS VAL FROM DUAL) A
		                  CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0           
		               ) A
		              , (
		                 SELECT TRIM(REGEXP_SUBSTR(VAL,'[^,]+',1,LEVEL)) AS INQUIRYNO
		                   FROM (SELECT #{inquirynoNew} AS VAL FROM DUAL) A
		                   CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0           
		               ) B
		          GROUP BY A.INQUIRY_NAME,B.INQUIRYNO
		     ) A
    </select>    
    
    <!-- 
       종료처리
         ->ST_INQUIRY.UPDATE 트리거 적용 
    -->
    <update id="updateCloseMaster" statementType="CALLABLE">
    <![CDATA[
	    {
	        CALL /* [stInquiryResultService.sqlx][stInquiryResultService.updateCloseMaster][조사지시현황-종료처리][sss][20250925] */
	        DECLARE
	            V_AFTER      ST_INQUIRY%rowtype;
	            O_SUCCESS    NUMBER := 1;
	            O_ERRCODE    NUMBER := 0;
	            O_ERRMSG     VARCHAR2(4000) := '';	
	            SQL_ERROR    EXCEPTION;
	            --
	            V_APPLY_CNT  NUMBER := 0; /*적용건수*/
	        BEGIN
	            BEGIN
	            
                FOR C1 IN (
                    SELECT ST_INQUIRY.DCCODE                 AS DCCODE        --1.센터코드                         
                          ,ST_INQUIRY.INQUIRYDT              AS INQUIRYDT     --2.조사일자                         
                          ,ST_INQUIRY.INQUIRYNO              AS INQUIRYNO     --3.조사번호                         
                          ,ST_INQUIRY.INQUIRY_NAME           AS INQUIRY_NAME  --4.조사명칭                         
                          ,ST_INQUIRY.PRIORITY               AS PRIORITY      --5.회차                           
                          ,ST_INQUIRY.INQUIRYTYPE            AS INQUIRYTYPE   --6.유형                           
                          ,ST_INQUIRY.STORERKEY              AS STORERKEY     --7.고객사코드                        
                          ,ST_INQUIRY.ORGANIZE               AS ORGANIZE      --8.조직코드                         
                          ,ST_INQUIRY.AREA                   AS AREA          --9.창고코드 SAP 창고 혹은 별도의 창고 코드     
                          ,ST_INQUIRY.SKU                    AS SKU           --10.상품코드                        
                          ,ST_INQUIRY.LOC                    AS LOC           --11.로케이션                        
                          ,ST_INQUIRY.LOT                    AS LOT           --12.재고 구분 LOT                   
                          ,ST_INQUIRY.STOCKID                AS STOCKID       --13.재고 구분 ID                    
                          ,ST_INQUIRY.STOCKGRADE             AS STOCKGRADE    --14.재고 등급( ABC )                
                          ,NVL(ST_INQUIRY.MOBILE_ADD_YN,'N') AS MOBILE_ADD_YN --15.모바일추가여부    					
	                  FROM ST_INQUIRY
					 WHERE ST_INQUIRY.DCCODE       = #{dccode}
					   AND ST_INQUIRY.INQUIRYDT    = #{inquirydt}
					   AND ST_INQUIRY.INQUIRYNO    = #{inquiryno}
					   AND ST_INQUIRY.INQUIRY_NAME = #{inquiryName}
					   AND ST_INQUIRY.INQUIRYTYPE  = 'STD'
					   AND ST_INQUIRY.STORERKEY    = #{storerkey}
					   AND ST_INQUIRY.ORGANIZE     = #{organize}
					   AND ST_INQUIRY.AREA         = #{area}
					   AND ST_INQUIRY.SKU          = #{sku}
					   AND (#{loc} IS NULL OR LOC = #{loc}) /*로케이션별 처리*/
					   AND ST_INQUIRY.LOT          = #{lot}
					   AND ST_INQUIRY.STOCKID      = #{stockid}
					   AND ST_INQUIRY.STOCKGRADE   = #{stockgrade}
                ) LOOP   
                
	                /*TRIGGER 대상ROW SELECT(1/3)*/
	                SELECT *
	                  INTO V_AFTER
	                  FROM ST_INQUIRY
                     WHERE ST_INQUIRY.DCCODE        = C1.DCCODE        --1.센터코드                                
                       AND ST_INQUIRY.INQUIRYDT     = C1.INQUIRYDT     --2.조사일자                                
                       AND ST_INQUIRY.INQUIRYNO     = C1.INQUIRYNO     --3.조사번호                                
                       AND ST_INQUIRY.INQUIRY_NAME  = C1.INQUIRY_NAME  --4.조사명칭                                
                       AND ST_INQUIRY.PRIORITY      = C1.PRIORITY      --5.회차                                  
                       AND ST_INQUIRY.INQUIRYTYPE   = C1.INQUIRYTYPE   --6.유형                                  
                       AND ST_INQUIRY.STORERKEY     = C1.STORERKEY     --7.고객사코드                               
                       AND ST_INQUIRY.ORGANIZE      = C1.ORGANIZE      --8.조직코드                                
                       AND ST_INQUIRY.AREA          = C1.AREA          --9.창고코드 SAP 창고 혹은 별도의 창고 코드            
                       AND ST_INQUIRY.SKU           = C1.SKU           --10.상품코드                               
                       AND ST_INQUIRY.LOC           = C1.LOC           --11.로케이션                               
                       AND ST_INQUIRY.LOT           = C1.LOT           --12.재고 구분 LOT                          
                       AND ST_INQUIRY.STOCKID       = C1.STOCKID       --13.재고 구분 ID                           
                       AND ST_INQUIRY.STOCKGRADE    = C1.STOCKGRADE    --14.재고 등급( ABC )                       
                       AND ST_INQUIRY.MOBILE_ADD_YN = C1.MOBILE_ADD_YN --15.모바일추가여부    					   
                       ;
                           
                    /*변경값 할당(2/3)*/ 
                    V_AFTER.STATUS     := '91';	  /*상태(00:조사예정,85:불일치,90:일치,91:종료)*/
                    V_AFTER.EDITDATE   := SYSDATE;
                    V_AFTER.EDITWHO    := #{gUserId};
                        
                    /*CALL THE PROCEDURE(3/3)*/ 
	                TRST_INQUIRY.TR_UPDATE(
	                    V_AFTER,
	                    O_SUCCESS,
	                    O_ERRCODE,
	                    O_ERRMSG
	                );
	
	                IF O_ERRCODE = -20001 THEN
	                    RAISE_APPLICATION_ERROR(-20001, NVL(O_ERRMSG, SQLERRM));
	                ELSIF O_ERRCODE != 0 THEN
	                    RAISE SQL_ERROR;
	                END IF;
	                
	                V_APPLY_CNT := V_APPLY_CNT + 1;
                
                END LOOP ;
	
	            EXCEPTION WHEN OTHERS THEN
	                O_ERRCODE := SQLCODE;
	                O_ERRMSG := NVL(O_ERRMSG, SQLERRM);
	            END;
	            
	            IF V_APPLY_CNT = 0 THEN
                     RAISE_APPLICATION_ERROR(-20001, '처리한 데이터가 없습니다.');
                END IF;
	
	            #{success,  mode=OUT, jdbcType=INTEGER, javaType=int}    := O_SUCCESS;
	            #{errCode,  mode=OUT, jdbcType=INTEGER, javaType=int}    := O_ERRCODE;
	            #{errMsg,   mode=OUT, jdbcType=VARCHAR, javaType=String} := O_ERRMSG;
	        END
	    }
    ]]>
	</update>
    
    <!-- 재지시 --> 	
   <insert id="insertTempExcel2" parameterType="java.util.List" >
		INSERT /* [StInquiryService.sqlx][StInquiryService.insertTempExcel2][재지시 Tabele 등록][sss][2025-11-02] */
		  INTO SY_PROCESSTEMP_ST 
			 ( PROCESSTYPE
			 , PROCESSCREATOR
			 , SPID
			 , ADDWHO
			 , EDITWHO
			 , PROCESSFLAG
			 , FROM_DCCODE              /*01.DCCODE */
			 , FROM_IOTYPE              /*02.INQUIRYDT */
			 , FROM_STOCKID             /*03.INQUIRYNO */			 
			 , BATCH_NO                 /*04.INQUIRY_NAME */
			 , ETCQTY1                  /*05.PRIORITY(복사할 기준차수의 회차-최종차수)*/
			 --                         /*06.INQUIRYTYPE - 미존재*/
			 , FROM_STORERKEY           /*07.STORERKEY */
			 , FROM_ORGANIZE            /*08.ORGANIZE */
			 , TO_AREA                  /*09.AREA */
			 , FROM_SKU                 /*10.SKU */
			 , FROM_LOC                 /*11.LOC */
			 , FROM_LOT                 /*12.LOT */
			 , TO_STOCKID               /*13.STOCKID */
			 , FROM_STOCKGRADE          /*14.STOCKGRADE */
			 --                         /*15.MOBILE_ADD_YN - 미존재*/ 
			 --
			 , FROM_ORDERQTY            /*30.LASTPRIORITY */
			 , LIST_NO                  /*31.INQUIRYNO_NEW */
			 , FROM_CONFIRMQTY          /*32.PRIORITY_NEW */
			 , TO_STOCKTYPE             /*33.REQ_FLAG */
			 , ARCHIVECOP               /*34.ARCHIVECOP */
			 , MEMO1                    /*35.REASONMSG */
		     )
        <foreach collection="list" item="item" separator="UNION ALL">
		SELECT
			   #{item.processtype}                 AS PROCESSTYPE
			 , #{item.gUserId}                     AS PROCESSCREATOR
			 , #{item.gSpid}                       AS SPID
			 , #{item.gUserId}                     AS ADDWHO
			 , #{item.gUserId}                     AS EDITWHO
			 , 'N'                                 AS PROCESSFLAG
			 --
			 , #{item.fromDccode}                  AS FROM_DCCODE        /*01.DCCODE */
			 , REPLACE(#{item.fromIotype},'-','')  AS FROM_IOTYPE        /*02.INQUIRYDT */
			 , #{item.fromStockid}                 AS FROM_STOCKID       /*03.INQUIRYNO */
			 , #{item.batchNo}                     AS BATCH_NO           /*04.INQUIRY_NAME */
			 , #{item.etcqty1}                     AS ETCQTY1            /*05.PRIORITY*/
			 --                                                          /*06.INQUIRYTYPE - 미존재*/			 
			 , #{item.fromStorerkey}               AS FROM_STORERKEY     /*07.STORERKEY */
			 , #{item.fromOrganize}                AS FROM_ORGANIZE      /*08.ORGANIZE */
			 , #{item.toArea}                      AS TO_AREA            /*09.AREA */
			 , #{item.fromSku}                     AS FROM_SKU           /*10.SKU */
			 , #{item.fromLoc}                     AS FROM_LOC           /*11.LOC */
			 , #{item.fromLot}                     AS FROM_LOT           /*12.LOT */
			 , #{item.toStockid}                   AS TO_STOCKID         /*13.STOCKID */
			 , #{item.fromStockgrade}              AS FROM_STOCKGRADE    /*14.STOCKGRADE */
			 --                                                          /*15.MOBILE_ADD_YN - 미존재*/ 
			 --
			 , #{item.fromOrderqty}                AS FROM_ORDERQTY      /*30.LASTPRIORITY */
			 , #{item.listNo}                      AS LIST_NO            /*31.INQUIRYNO_NEW */
			 , #{item.fromConfirmqty}              AS FROM_CONFIRMQTY    /*32.PRIORITY_NEW */
			 , #{item.toStocktype}                 AS TO_STOCKTYPE       /*33.REQ_FLAG */
			 , #{item.archivecop}                  AS ARCHIVECOP         /*34.ARCHIVECOP */
			 , #{item.memo1}                       AS MEMO1              /*35.REASONMSG */
		  FROM DUAL	
        </foreach>
    </insert>        
    
    
    
</mapper>