<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="stLocMoveAsrsService">

	<select id="getMasterList" resultType="StLocMoveAsrsTab1ResDto">				
        SELECT /* [StLocMoveAsrsService.sqlx][getMasterList][자동창고보충 이동대상 조회][공두경][2025.09.16] */
			   ST_STOCK.DCCODE           									AS DCCODE               /*물류센터*/
              ,ST_STOCK.ORGANIZE         									AS ORGANIZE             /*창고*/
              ,ST_STOCK.STOCKTYPE											AS FROM_STOCKTYPE       /*재고위치코드*/
              ,NVL(CD1.BASEDESCR,CD1.BASECODE)								AS STOCKTYPE            /*채고위치명칭*/
              ,ST_STOCK.STOCKGRADE                                          AS FROM_STOCKGRADE      /*재고속성코드*/
              ,NVL(CD2.BASEDESCR,CD2.BASECODE) 								AS STOCKGRADE           /*재고속성명칭*/
              ,ST_STOCK.LOC              									AS LOC                  /*로케이션*/
              ,ST_STOCK.SKU              									AS SKU                  /*상품코드*/
              ,MS_SKU.DESCRIPTION        									AS SKUNAME              /*상품명칭*/
              ,NVL(CD3.BASEDESCR,CD3.BASECODE) 								AS STORAGETYPE          /*저장조건*/
              ,NVL(MS_SKUDCSET.LOC,' ')                                     AS FIXLOC				/*고정로케이션*/
              ,NVL((NVL((1 * UOM12.BUNJA / UOM12.BUNMO),0) * UOM13.BUNMO / UOM13.BUNJA),0)                                             							AS QTYPERBOX        /*박스입수*/
              ,TRUNC(NVL((NVL(((ST_STOCK.QTY - ST_STOCK.QTYALLOCATED - ST_STOCK.QTYPICKED ) * UOM11.BUNJA / UOM11.BUNMO),0) * UOM12.BUNMO / UOM12.BUNJA),0))	AS POSBQTY_BOX		/*BOX*/
              ,MOD(NVL((NVL(((ST_STOCK.QTY - ST_STOCK.QTYALLOCATED - ST_STOCK.QTYPICKED) * UOM11.BUNJA / UOM11.BUNMO),0) * UOM13.BUNMO / UOM13.BUNJA),0)
                  ,NVL((NVL((1 * UOM12.BUNJA / UOM12.BUNMO),0) * UOM13.BUNMO / UOM13.BUNJA),0))																	AS POSBQTY_EA		/*EA*/
      		  ,''                                                           AS TO_LOC               /*이동로케이션*/
      		  ,0                                                            AS TO_ORDERQTY_BOX      /*BOX*/
      		  ,0                                                            AS TO_ORDERQTY_EA		/*EA*/
              , NVL(TRIM(FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'Y')),'N') AS NEARDURATIONYN /** 유통기한임박여부 */
              ,CM_LOT.LOTTABLE01         									AS LOTTABLE01			/*기준일(소비,제조)*/
              ,FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'N0') ||'/'|| MS_SKU.DURATION 							AS DURATION_TERM	/*소비기간(잔여/전체)*/
              ,ST_STOCK.UOM              									AS UOM                  /*단위*/
              ,ST_STOCK.QTY              									AS QTY                  /*현재고수량*/
              ,ST_STOCK.QTYALLOCATED     									AS QTYALLOCATED         /*재고할당수량*/
              ,ST_STOCK.QTYPICKED        									AS QTYPICKED            /*피킹재고*/
			  ,ST_STOCK.QTY - ST_STOCK.QTYALLOCATED - ST_STOCK.QTYPICKED	AS POSBQTY              /*이동가능수량*/
              ,ST_SERIALINFO.SERIALNO 										AS SERIALNO             /*이력번호*/
              ,ST_SERIALINFO.STOCKID										AS BARCODE              /*바코드*/
              ,ST_SERIALINFO.CONVSERIALNO       							AS CONVSERIALNO         /*B/L번호*/
              ,ST_SERIALINFO.BUTCHERYDT										AS BUTCHERYDT           /*도축일자*/
              ,ST_SERIALINFO.FACTORYNAME                                    AS FACTORYNAME          /*도축장*/
              ,NVL(CD4.BASEDESCR,CD4.BASECODE)   							AS CONTRACTTYPE         /*게약유형*/
              ,ST_SERIALINFO.CONTRACTCUSTKEY                                AS CONTRACTCOMPANY		/*계약업체*/
              ,(SELECT DESCRIPTION FROM MS_CUST 
                WHERE  MS_CUST.STORERKEY = ST_SERIALINFO.STORERKEY
                AND    MS_CUST.CUSTKEY   = ST_SERIALINFO.CONTRACTCUSTKEY
                AND    ROWNUM = 1 )                                         AS CONTRACTCOMPANYNAME	/*계약업체명*/
              ,ST_SERIALINFO.FROMVALIDDT									AS FROMVALIDDT			/*유효일자(FROM)*/
              ,ST_SERIALINFO.TOVALIDDT										AS TOVALIDDT            /*유효일자(TO)*/
              ,ST_STOCK.LOT              									AS FROM_LOT             /*로트*/
              ,ST_STOCK.STOCKID                                             AS FROM_STOCKID         /*개체식별/유통이력*/
              ,ST_STOCK.AREA         										AS FROM_AREA            /*작업구역*/
      		  ,0                                                            AS TO_ORDERQTY          /**/
              ,MS_SKU.DURATION												AS DURATION             /**/
              ,MS_SKU.DURATIONTYPE 											AS DURATIONTYPE         /**/
              ,ST_STOCK.DCCODE           									AS FROM_DCCODE          /**/
              ,ST_STOCK.STORERKEY											AS FROM_STORERKEY       /**/
              ,ST_STOCK.ORGANIZE         									AS FROM_ORGANIZE        /**/
              ,ST_STOCK.SKU              									AS FROM_SKU             /**/
              ,ST_STOCK.LOC              									AS FROM_LOC             /**/
              ,ST_STOCK.QTY                                                 AS FROM_ORDERQTY        /**/
              ,ST_STOCK.UOM              									AS FROM_UOM             /**/
              ,ST_STOCK.DCCODE           									AS TO_DCCODE            /**/
              ,ST_STOCK.STORERKEY											AS TO_STORERKEY         /**/
              ,ST_STOCK.ORGANIZE         									AS TO_ORGANIZE          /**/
              ,ST_STOCK.AREA         										AS TO_AREA              /**/
              ,ST_STOCK.SKU              									AS TO_SKU               /**/
              ,ST_STOCK.LOT              									AS TO_LOT               /**/
              ,ST_STOCK.STOCKID                                             AS TO_STOCKID           /**/
              ,ST_STOCK.STOCKGRADE                                          AS TO_STOCKGRADE        /**/
              ,ST_STOCK.STOCKTYPE											AS TO_STOCKTYPE         /**/
              ,ST_STOCK.UOM              									AS TO_UOM               /**/
              ,ST_STOCK.QTYALLOCATED     									AS ETCQTY1              /**/
              ,ST_STOCK.QTYPICKED     										AS ETCQTY2              /**/
        FROM   ST_STOCK 
        JOIN   MS_SKU
        ON     MS_SKU.STORERKEY         = ST_STOCK.STORERKEY
        AND    MS_SKU.SKU               = ST_STOCK.SKU
        AND    MS_SKU.DEL_YN            = 'N'
        <if test="storagetype != null and storagetype != ''">  AND    MS_SKU.STORAGETYPE        LIKE #{storagetype}                     </if>         
        <!-- 상품 다중선택 -->     
		<if test="sku != null and sku != '' ">
			<if test="skuMulti != null and skuMulti.size() > 0">
				<trim prefix="AND (" suffix=")" prefixOverrides="OR">
					<foreach collection="skuMulti" item="item">
						OR MS_SKU.SKU IN
						<foreach collection="item" item="code" open="(" close=")" separator=",">
							#{code} 	 
			      		</foreach>
			    	</foreach>
			  	</trim>			                                    
	    	</if>
        </if>
        JOIN   CM_LOT
        ON     CM_LOT.STORERKEY            = ST_STOCK.STORERKEY
        AND    CM_LOT.LOT                  = ST_STOCK.LOT
        AND    CM_LOT.DEL_YN               = 'N'
        <if test="lottable01yn == 'Y'.toString()"> 	    AND    CM_LOT.LOTTABLE01		<![CDATA[<>]]>  'STD'		</if>                       
        <if test="lottable01yn == 'N'.toString()"> 	    AND    CM_LOT.LOTTABLE01		=  'STD'		</if>
        JOIN   MS_LOCATION
        ON     MS_LOCATION.DCCODE          = ST_STOCK.DCCODE
        AND    MS_LOCATION.LOC             = ST_STOCK.LOC
        <if test="loccategory != null and loccategory != ''">AND    MS_LOCATION.LOCCATEGORY     = 'AUTO'</if>
        <choose>
            <when test="searchserial != null and searchserial != ''">
            	JOIN ST_SNINFO ST_SERIALINFO
		        ON     ST_STOCK.STORERKEY  = ST_SERIALINFO.STORERKEY
		        AND    ST_STOCK.SKU        = ST_SERIALINFO.SKU
		        AND    ST_STOCK.STOCKID    = ST_SERIALINFO.STOCKID     
            </when>
            <otherwise>
            	LEFT OUTER JOIN ST_SNINFO ST_SERIALINFO
		        ON     ST_STOCK.STORERKEY  = ST_SERIALINFO.STORERKEY
		        AND    ST_STOCK.SKU        = ST_SERIALINFO.SKU
		        AND    ST_STOCK.STOCKID    = ST_SERIALINFO.STOCKID     
            </otherwise>
        </choose>
        LEFT OUTER JOIN MS_SKUDCSET
        ON    ST_STOCK.DCCODE          = MS_SKUDCSET.DCCODE
        AND   ST_STOCK.STORERKEY       = MS_SKUDCSET.STORERKEY
        AND   ST_STOCK.SKU             = MS_SKUDCSET.SKU     
        LEFT JOIN CM_CODE_STORER CD1  ON CD1.STORERKEY   = ST_STOCK.STORERKEY 	AND CD1.CODELIST  = 'STOCKTYPE' 		AND CD1.BASECODE   = ST_STOCK.STOCKTYPE
        LEFT JOIN CM_CODE_STORER CD2  ON CD2.STORERKEY   = ST_STOCK.STORERKEY 	AND CD2.CODELIST  = 'STOCKGRADE' 		AND CD2.BASECODE   = ST_STOCK.STOCKGRADE
        LEFT JOIN CM_CODE_STORER CD3  ON CD3.STORERKEY   = MS_SKU.STORERKEY 	AND CD3.CODELIST  = 'STORAGETYPE' 		AND CD3.BASECODE   = MS_SKU.STORAGETYPE
        LEFT JOIN CM_CODE_STORER CD4  ON CD4.STORERKEY   = ST_STOCK.STORERKEY 	AND CD4.CODELIST  = 'CONTRACTTYPE_SN' 	AND CD4.BASECODE   = ST_SERIALINFO.CONTRACTTYPE
        LEFT JOIN MS_UOM UOM11  	  ON UOM11.STORERKEY = ST_STOCK.STORERKEY AND UOM11.SKU  = ST_STOCK.SKU AND UOM11.UOM = ST_STOCK.UOM
	    LEFT JOIN MS_UOM UOM12	  	  ON UOM12.STORERKEY = ST_STOCK.STORERKEY AND UOM12.SKU  = ST_STOCK.SKU AND UOM12.UOM = 'BOX'
	    LEFT JOIN MS_UOM UOM13	  	  ON UOM13.STORERKEY = ST_STOCK.STORERKEY AND UOM13.SKU  = ST_STOCK.SKU AND UOM13.UOM = 'EA'
        WHERE  ST_STOCK.QTY - ST_STOCK.QTYALLOCATED - ST_STOCK.QTYPICKED > 0 /* 이동가능한것만 표출 */
	    <if test="gStorerkey != null and gStorerkey != ''"> AND    ST_STOCK.STORERKEY = #{gStorerkey}    </if>
        <if test="fixdccode != null and fixdccode != ''">   AND ST_STOCK.DCCODE               =  #{fixdccode}   </if>
        <if test="organize != null and organize != ''">    AND ST_STOCK.ORGANIZE             =  #{organize}    </if>
        <if test="stocktype != null and stocktype != ''">   AND ST_STOCK.STOCKTYPE            =  #{stocktype}   </if>
        <if test="stockgrade != null and stockgrade != ''">  AND ST_STOCK.STOCKGRADE           =  #{stockgrade}  </if>
        <if test="fromloc != null and fromloc != ''">     AND ST_STOCK.LOC         <![CDATA[>=]]>  #{fromloc} </if>
        <if test="toloc != null and toloc != ''">       AND ST_STOCK.LOC         <![CDATA[<=]]>  #{toloc}   </if>   
        <if test="zone != null and zone != ''">        AND MS_LOCATION.ZONE              =  #{zone}        </if>                
        <if test="serialno != null and serialno != ''">    AND ST_SERIALINFO.SERIALNO        =  #{serialno}    </if>
        <if test="blno != null and blno != ''">    AND ST_SERIALINFO.CONVSERIALNO        =  #{blno}    </if>
        <if test="contractcompany != null and contractcompany != ''">    AND ST_SERIALINFO.CONTRACTCUSTKEY        =  #{contractcompany}    </if>
    	<!-- START.권한센터 -->
	    AND EXISTS (SELECT 1
                      FROM CM_USER_AUTHORITY 
                     WHERE CM_USER_AUTHORITY.DCCODE    = ST_STOCK.DCCODE       
                       AND CM_USER_AUTHORITY.STORERKEY = ST_STOCK.STORERKEY    
                       AND CM_USER_AUTHORITY.ORGANIZE  = ST_STOCK.ORGANIZE     
                       AND CM_USER_AUTHORITY.AREA      = ST_STOCK.AREA         
                       AND CM_USER_AUTHORITY.STORERKEY = #{gStorerkey}
                       AND CM_USER_AUTHORITY.USERID    = #{gUserId}
                       AND CM_USER_AUTHORITY.DCCODE    = #{fixdccode}
                       AND CM_USER_AUTHORITY.AREA      = #{gArea}   
			           <!-- 창고.다중검색 -->
			           <if test='gOrganizeMulti != null and gOrganizeMulti.length > 0'>
				           AND CM_USER_AUTHORITY.ORGANIZE IN
				           <foreach collection="gOrganizeMulti" item="code" open="(" close=")" separator=",">
				             #{code}
				           </foreach>
			           </if>                       
                   )
	    <!-- END.권한센터	--> 
		ORDER BY ST_STOCK.DCCODE
                ,ST_STOCK.LOC
                ,ST_STOCK.STORERKEY
                ,ST_STOCK.SKU
    </select>
    
    <select id="getResultList" resultType="StLocMoveAsrsTab2ResDto">				
        SELECT /* [StLocMoveAsrsService.sqlx][getResultList][자동창고보충 이동결과 조회][공두경][2025.09.16] */ 
               SY_PROCESSTEMP_ST.FROM_DCCODE           					                                                                AS DCCODE               /*물류센터*/
              ,SY_PROCESSTEMP_ST.FROM_ORGANIZE         					                                                                AS ORGANIZE             /*창고*/
              ,NVL(CD1.BASEDESCR,CD1.BASECODE)							                                                                AS STOCKTYPE            /*재고위치*/
              ,NVL(CD2.BASEDESCR,CD2.BASECODE)							                                                                AS STOCKGRADE           /*재고속성*/
              ,SY_PROCESSTEMP_ST.FROM_LOC              					                                                                AS LOC                  /*로케이션*/
              ,SY_PROCESSTEMP_ST.FROM_SKU              					                                                                AS SKU                  /*상품코드*/
              ,MS_SKU.DESCRIPTION        								                                                                AS SKUNAME              /*상품명칭*/
              ,NVL(CD3.BASEDESCR,CD3.BASECODE)																							AS STORAGETYPE          /*저장조건*/
              ,NVL(MS_SKUDCSET.LOC,' ')                                                 		  	                                    AS FIXLOC               /*고정로케이션*/
              ,TRUNC(NVL((NVL(((SY_PROCESSTEMP_ST.FROM_ORDERQTY - SY_PROCESSTEMP_ST.ETCQTY1 - SY_PROCESSTEMP_ST.ETCQTY2) * UOM11.BUNJA / UOM11.BUNMO),0) * UOM12.BUNMO / UOM12.BUNJA),0)
              		)																													AS POSBQTY_BOX			/*BOX*/
              ,MOD(NVL((NVL(((SY_PROCESSTEMP_ST.FROM_ORDERQTY - SY_PROCESSTEMP_ST.ETCQTY1 - SY_PROCESSTEMP_ST.ETCQTY2) * UOM11.BUNJA / UOM11.BUNMO),0) * UOM13.BUNMO / UOM13.BUNJA),0)      
                  ,NVL((NVL((1 * UOM12.BUNJA / UOM12.BUNMO),0) * UOM13.BUNMO / UOM13.BUNJA),0))    										AS POSBQTY_EA      		/*EA*/  
      		  ,SY_PROCESSTEMP_ST.TO_LOC                                                       											AS TO_LOC               /*이동로케이션*/
      		  ,SY_PROCESSTEMP_ST.TO_ORDERQTY                                                                            				AS TO_ORDERQTY_BOX      /*BOX*/
      		  ,SY_PROCESSTEMP_ST.TO_CONFIRMQTY                                                                            				AS TO_ORDERQTY_EA       /*EA*/
              , NVL(TRIM(FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'Y')),'N') AS NEARDURATIONYN /** 유통기한임박여부 */
              ,CM_LOT.LOTTABLE01         																								AS LOTTABLE01           /*기준일(소비,제조)*/
              ,FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, CM_LOT.LOTTABLE01, 'N0') ||'/'|| MS_SKU.DURATION 	AS DURATION_TERM        /*소비기간(잔여/전체)*/
              ,SY_PROCESSTEMP_ST.FROM_UOM              					                                                                AS UOM                  /*단위*/
              ,SY_PROCESSTEMP_ST.FROM_ORDERQTY              			                                                                AS QTY                  /*현재고수량*/
              ,SY_PROCESSTEMP_ST.ETCQTY1     							                                                                AS QTYALLOCATED         /*재고할당수량*/
              ,SY_PROCESSTEMP_ST.ETCQTY2								                                                                AS QTYPICKED            /*피킹재고*/
      		  ,SY_PROCESSTEMP_ST.FROM_ORDERQTY - SY_PROCESSTEMP_ST.ETCQTY1 - SY_PROCESSTEMP_ST.ETCQTY2                       			AS POSBQTY              /*이동가능수량*/
              ,ST_SERIALINFO.SERIALNO 																				                    AS SERIALNO             /*이력번호*/
              ,ST_SERIALINFO.STOCKID															  	                                    AS BARCODE              /*바코드*/
              ,ST_SERIALINFO.CONVSERIALNO       												  										AS CONVSERIALNO         /*B/L번호*/
              ,ST_SERIALINFO.BUTCHERYDT															  										AS BUTCHERYDT           /*도축일자*/
              ,ST_SERIALINFO.FACTORYNAME                                                         										AS FACTORYNAME          /*도축장*/
              ,NVL(CD4.BASEDESCR,CD4.BASECODE)   													                                    AS CONTRACTTYPE         /*계약유형*/
              ,ST_SERIALINFO.CONTRACTCUSTKEY                                                      										AS CONTRACTCOMPANY		/*계약업체*/
              ,(SELECT DESCRIPTION FROM MS_CUST 
                WHERE  MS_CUST.STORERKEY = ST_SERIALINFO.STORERKEY
                AND    MS_CUST.CUSTKEY   = ST_SERIALINFO.CONTRACTCUSTKEY
                AND    ROWNUM = 1 )                                                               	                                    AS CONTRACTCOMPANYNAME	/*계약업체명*/
              ,ST_SERIALINFO.FROMVALIDDT														  	                                    AS FROMVALIDDT          /*유효일자(FROM)*/
              ,ST_SERIALINFO.TOVALIDDT															  	                                    AS TOVALIDDT            /*유효일자(TO)*/
              ,SY_PROCESSTEMP_ST.PROCESSFLAG																							AS PROCESSFLAG          /*PROCESSFLAG*/
              ,SY_PROCESSTEMP_ST.PROCESSMSG																								AS PROCESSMSG           /*PROCESSMSG*/
              ,NVL((NVL((1 * UOM12.BUNJA / UOM12.BUNMO),0) * UOM13.BUNMO / UOM13.BUNJA),0)                                 				AS QTYPERBOX			/**/
      		  ,SY_PROCESSTEMP_ST.TO_ORDERQTY                                                                            				AS TO_ORDERQTY          /**/
              ,MS_SKU.DURATION																											AS DURATION             /**/
              ,MS_SKU.DURATIONTYPE 																										AS DURATIONTYPE         /**/
        FROM   SY_PROCESSTEMP_ST 
        JOIN   MS_SKU
        ON     MS_SKU.STORERKEY         = SY_PROCESSTEMP_ST.FROM_STORERKEY
        AND    MS_SKU.SKU               = SY_PROCESSTEMP_ST.FROM_SKU
        AND    MS_SKU.DEL_YN            = 'N'
        JOIN   CM_LOT
        ON     CM_LOT.STORERKEY            = SY_PROCESSTEMP_ST.FROM_STORERKEY
        AND    CM_LOT.LOT                  = SY_PROCESSTEMP_ST.FROM_LOT
        AND    CM_LOT.DEL_YN               = 'N'
        JOIN   MS_LOCATION
        ON     MS_LOCATION.DCCODE          = SY_PROCESSTEMP_ST.FROM_DCCODE
        AND    MS_LOCATION.LOC             = SY_PROCESSTEMP_ST.FROM_LOC
        LEFT JOIN ST_SNINFO ST_SERIALINFO
        ON     SY_PROCESSTEMP_ST.FROM_STORERKEY  = ST_SERIALINFO.STORERKEY
        AND    SY_PROCESSTEMP_ST.FROM_SKU        = ST_SERIALINFO.SKU
        AND    SY_PROCESSTEMP_ST.FROM_STOCKID    = ST_SERIALINFO.STOCKID
        LEFT JOIN MS_SKUDCSET
        ON     SY_PROCESSTEMP_ST.FROM_DCCODE          = MS_SKUDCSET.DCCODE
        AND    SY_PROCESSTEMP_ST.FROM_STORERKEY       = MS_SKUDCSET.STORERKEY
        AND    SY_PROCESSTEMP_ST.FROM_SKU             = MS_SKUDCSET.SKU   
        LEFT JOIN CM_CODE_STORER CD1  ON CD1.STORERKEY  = SY_PROCESSTEMP_ST.FROM_STORERKEY 		AND CD1.CODELIST  = 'STOCKTYPE' 		AND CD1.BASECODE   = SY_PROCESSTEMP_ST.FROM_STOCKTYPE
        LEFT JOIN CM_CODE_STORER CD2  ON CD2.STORERKEY  = SY_PROCESSTEMP_ST.FROM_STORERKEY 		AND CD2.CODELIST  = 'STOCKGRADE' 		AND CD2.BASECODE   = SY_PROCESSTEMP_ST.FROM_STOCKGRADE
        LEFT JOIN CM_CODE_STORER CD3  ON CD3.STORERKEY  = MS_SKU.STORERKEY 					AND CD3.CODELIST  = 'STORAGETYPE' 		AND CD3.BASECODE   = MS_SKU.STORAGETYPE
        LEFT JOIN CM_CODE_STORER CD4  ON CD4.STORERKEY  = SY_PROCESSTEMP_ST.FROM_STORERKEY 	AND CD4.CODELIST  = 'CONTRACTTYPE_SN' 	AND CD4.BASECODE   = ST_SERIALINFO.CONTRACTTYPE
        LEFT JOIN MS_UOM UOM11  	  ON UOM11.STORERKEY = SY_PROCESSTEMP_ST.FROM_STORERKEY AND UOM11.SKU  = SY_PROCESSTEMP_ST.FROM_SKU AND UOM11.UOM = SY_PROCESSTEMP_ST.FROM_UOM
	    LEFT JOIN MS_UOM UOM12	  	  ON UOM12.STORERKEY = SY_PROCESSTEMP_ST.FROM_STORERKEY AND UOM12.SKU  = SY_PROCESSTEMP_ST.FROM_SKU AND UOM12.UOM = 'BOX'
	    LEFT JOIN MS_UOM UOM13	  	  ON UOM13.STORERKEY = SY_PROCESSTEMP_ST.FROM_STORERKEY AND UOM13.SKU  = SY_PROCESSTEMP_ST.FROM_SKU AND UOM12.UOM = 'EA'        
        WHERE  SY_PROCESSTEMP_ST.PROCESSTYPE 	= #{processtype}                               
        AND    SY_PROCESSTEMP_ST.PROCESSCREATOR = #{gUserId}
        AND    SY_PROCESSTEMP_ST.SPID	        = #{gSpid}
        ORDER BY SY_PROCESSTEMP_ST.FROM_DCCODE
                ,SY_PROCESSTEMP_ST.FROM_LOC
                ,SY_PROCESSTEMP_ST.FROM_STORERKEY
                ,SY_PROCESSTEMP_ST.FROM_SKU	  
    </select>
     
    
    <!-- 엑셀업로드 정보을(를) 등록 -->
    <insert id="insertTempExcel" parameterType="java.util.List" >
        <foreach collection="list" index="index" item="item" separator=" " open="INSERT ALL" close="SELECT * FROM DUAL">
              /* [StLocMoveAsrsService.sqlx][insertTempExcel][엑셀데이터임시 Tabele 등록][공두경][2025.07.17] */
              INTO SY_PROCESSTEMP_ST (PROCESSTYPE,PROCESSCREATOR,SPID,ADDWHO,EDITWHO
                                      /**/
                                      ,FROM_DCCODE            
				                      ,FROM_STORERKEY         
				                      ,FROM_ORGANIZE          
				                      ,FROM_AREA              
				                      ,FROM_SKU               
				                      ,FROM_LOC               
				                      ,FROM_LOT               
				                      ,FROM_STOCKID           
				                      ,FROM_STOCKGRADE        
				                      ,FROM_STOCKTYPE         
				                      ,FROM_UOM               
				                      ,TO_LOC                 
				                      ,TO_ORDERQTY            
				                      ,TO_CONFIRMQTY      
				                      ,FROM_ORDERQTY
									  ,TO_DCCODE
									  ,TO_STORERKEY
									  ,TO_ORGANIZE
									  ,TO_AREA
									  ,TO_SKU									
									  ,TO_LOT
									  ,TO_STOCKID
									  ,TO_STOCKGRADE
									  ,TO_STOCKTYPE
									  ,TO_UOM
									  ,ETCQTY1
									  ,ETCQTY2
                                    )
            VALUES (
                    #{item.processtype},#{item.gUserId},#{item.gSpid},#{item.gUserId},#{item.gUserId}
                    /**/
                    ,#{item.fromDccode}    
                    ,#{item.fromStorerkey} 
                    ,#{item.fromOrganize} 
                    ,#{item.fromArea}        
                    ,#{item.fromSku}    	
                    ,#{item.fromLoc}    	                    
                    ,#{item.fromLot}    	                    
                    ,#{item.fromStockid}    	                    
                    ,#{item.fromStockgrade}    	                    
                    ,#{item.fromStocktype}    	                    
                    ,#{item.fromUom}    	                    
                    ,#{item.toLoc}    	                    
                    ,#{item.toOrderqty}    	                    
                    ,#{item.toConfirmqty}
                    ,#{item.fromOrderqty}    	
                    ,#{item.toDccode}    
                    ,#{item.toStorerkey} 
                    ,#{item.toOrganize} 
                    ,#{item.toArea}        
                    ,#{item.toSku}    		                    
                    ,#{item.toLot}    	                    
                    ,#{item.toStockid}    	                    
                    ,#{item.toStockgrade}    	                    
                    ,#{item.toStocktype}    	                    
                    ,#{item.toUom}
                    ,#{item.etcqty1}
                    ,#{item.etcqty2}
                   )
        </foreach>
     </insert>   
    
</mapper>