<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper   PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
  "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="stTplUserService">
<select id="getTplUserPopupList"  parameterType="StTplUserReqDto" resultType="StTplUserResDto">
    SELECT 
           MS_CLIENT.USER_ID AS CODE   /*사용자ID*/
         --, USER3.USER_NM AS NAME   /*화주명*/
         , MS_CLIENT.CUSTKEY AS CUSTKEY /* 거래처코드*/
         , CUST.DESCRIPTION     AS CUST_NM     /* 거래처명*/
         , MS_CLIENT.VENDOR AS VENDOR   /*협력사코드*/
         , PARTNER.DESCRIPTION  AS VENDOR_NM  /* 협력사명*/
         ,USER4.DESCRIPTION AS NAME
      FROM MS_CLIENT
      INNER JOIN FRAMEONE_USER USER3
        ON MS_CLIENT.USER_ID = USER3.USER_ID   /*화주명*/
      LEFT JOIN MS_CUST CUST                   
        ON MS_CLIENT.CUSTKEY = CUST.CUSTKEY
       AND CUST.STORERKEY   =  'FW00'
       AND CUST.CUSTTYPE    ='C'              /*협력사명 */
      LEFT JOIN MS_CUST PARTNER
        ON MS_CLIENT.VENDOR = PARTNER.CUSTKEY
       AND PARTNER.STORERKEY   =  'FW00'
       AND PARTNER.CUSTTYPE    ='P'            /*거래처명*/
      JOIN MS_CUST  USER4  
        ON USER4.CUSTKEY =USER3.CUSTKEY
     WHERE 1=1
     <if test='date != null and date != ""'>
        <![CDATA[
       AND #{date} BETWEEN MS_CLIENT.FROMDATE AND MS_CLIENT.TODATE 
         ]]>
     </if>
     <if test='name != null and name != ""'>
         <choose>
         <when test="fixedSearchYn == '' and fixedSearchYn == null"> <!-- FIX검색.%1개일 때(3/4) -->
           AND (MS_CLIENT.USER_ID    LIKE '%'||#{name}||'%' OR USER4.DESCRIPTION LIKE '%'||#{name}||'%')
         </when>
         <when test="fixedSearchYn == 'Y'.toString()"> <!-- FIX검색.%1개일 때(3/4) -->
           AND (MS_CLIENT.USER_ID LIKE #{name} OR USER4.DESCRIPTION LIKE #{name} )
          </when>
         <otherwise><!-- 2.단일검색,5.%다중검색  -->
           AND ( REGEXP_LIKE(MS_CLIENT.USER_ID, #{name}, 'i') OR REGEXP_LIKE(USER4.DESCRIPTION, #{name}, 'i'))
         </otherwise>
         </choose>                     
    </if>
 </select>
 
 <select id="getMasterList"  resultType="StTplUserResDto"  parameterType="StTplUserReqDto" >
    SELECT 
           MS_CLIENT.USER_ID AS CODE   /*사용자ID*/
         , USER1.USER_NM AS NAME   /*화주명*/
         , MS_CLIENT.CUSTKEY AS CUSTKEY /* 거래처코드*/
         , MS_CLIENT.VENDOR AS VENDOR   /*협력사코드*/
      FROM MS_CLIENT
     INNER JOIN FRAMEONE_USER USER1
        ON MS_CLIENT.USER_ID = USER1.USER_ID   /*화주명*/
     WHERE 1=1
        AND MS_CLIENT.USER_ID = #{gUserId}
        <![CDATA[
        AND TO_CHAR(SYSDATE, 'YYYYMMDD') >= MS_CLIENT.FROMDATE
        AND TO_CHAR(SYSDATE, 'YYYYMMDD') <= MS_CLIENT.TODATE
        ]]>
 </select>
</mapper>
