package cjfw.batch.scm0060.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "urn://scm.cjfreshway.co.kr/SD", name = "SI_SCM0060_SCM_SO")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SISCM0060SCMSO {

    @WebMethod(operationName = "SI_SCM0060_SCM_SO", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_SCM0060_SCM_response", targetNamespace = "urn://scm.cjfreshway.co.kr/SD", partName = "MT_SCM0060_SCM_response")
    public DTSCM0060SCMResponse siSCM0060SCMSO(

        @WebParam(partName = "MT_SCM0060_SCM", name = "MT_SCM0060_SCM", targetNamespace = "urn://scm.cjfreshway.co.kr/SD")
        DTSCM0060SCM mtSCM0060SCM
    );
}
