server:
  server-header: cjfw
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
  shutdown: graceful
  tomcat:
    threads:
      max: 100                  # 요청 처리를 위한 최대 스레드 수
      min-spare: 100            # 항상 유지할 최소 여유 스레드 수
    connection-timeout: 10s     # 연결 후 요청이 들어올 때까지 기다리는 시간 (ms)
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 2048

spring:
  profiles:
    default: local
  batch:
    restApi:
      url: http://localhost:8081
      #url: https://waylodev.ifresh.co.kr:9443
  application:
    name: apiserver
    logfilename: cjfw-wms-api
  datasource-oracle:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.73.197.41:1531/FWWMSDBD.cj.net
    username: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
    password: ENC(VfW2zCbD7leUYCVEunPh2nppaLV0+v27)
    hikari:
      pool-name: hikaricp-waylo
      maximum-pool-size: 30
      minimum-idle: 30
      connection-timeout: 10000       # 10초
      validation-timeout: 5000        # 5초
      max-lifetime: 1800000           # 30분
      idle-timeout: 300000            # 5분
      keepalive-time: 120000          # 2분
      leak-detection-threshold: 30000 # 30초
  #  datasource-oracle:
  #     driver-class-name: oracle.jdbc.OracleDriver
  #     url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=ON)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=10.73.151.111)(PORT=1591))(ADDRESS=(PROTOCOL=TCP)(HOST=10.73.151.113)(PORT=1591)))(CONNECT_DATA=(SERVICE_NAME=FWWMSDBP.cj.net)))
  #     username: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
  #     password: ENC(UHyU838T3T/pqEXNLbhcPPGWJZCvZ/3e)
  #data:
  #  redis:
  #    host: 10.74.11.58
  #    port: 18504
  #    password: redis2026!
  #    timeout: 6000
  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: -1
  main:
    allow-bean-definition-overriding: true
  #    allow-circular-references: true
  task:   #async thread pool 생성
    execution:
      pool:
        core-size: 3
        max-size: 3
        queue-capacity: 100
  config:
    import:
      - classpath:/config/cf-config.yml
      - classpath:/config/project-config.yml
      - classpath:/config/auth-config.yml
  # 404응답 커스터마이징
  mvc:
    converters:
      preferred-json-mapper: jackson
  web:
    resources:
      add-mappings: false
  tmap:
    url: https://apis.openapi.sk.com/tmap
    appkey: l7xx78a123696af740b8a2b4c8c8fa8c6e86
  naver:
    api:
      id:  pzz52pipm2
      key: sXxjz7QxVtUBH7GPDXenCpwU5i9WmQDOains5oBM
      urlMapGc:  https://maps.apigw.ntruss.com/map-geocode/v2/geocode   ###위도(Y),경도(X)
      urlMapRGc: https://maps.apigw.ntruss.com/map-reversegeocode/v2/gc ###행정동코드

springdoc:
  use-fqn: true
  show-actuator: false
  model-and-view-allowed: true
  writer-with-order-by-keys: true
  cache:
    disabled: true
  swagger-ui:
    enabled: true
    path: swagger.html #http://localhost:8080/swagger.html 로 호출
    defaultModelsExpandDepth: 10
    defaultModelExpandDepth: 3
    urls-primary-name: wm
    try-it-out-enabled: true
  override-with-generic-response: false # Default 응답 메시지(@ControllerAdvice) 제외
  default-produces-media-type: application/json
  api-docs:
    enabled: true # http://ip:port/context-path/v3/api-docs.yaml 또는 ~/v3/api-docs End-point 활성화 여부
    path: /v3/api-docs
    # 특정 API의 End-point를 노출하면 안되는 경우는 Controller class 또는 Method 상단에 @Hidden 추가

#logback-spring.xml에서 console 설정하도록 변경가능
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  level:
    org:
      springframework: INFO
      apache: ERROR
    com: ERROR
    ${server.server-header}: DEBUG

pagehelper:
  dialect: cjfw.core.dataaccess.interceptor.MybatisPageHelper
  helper-dialect: oracle   # DB지정[oracle, mysql, mariadb, sqlite, hsqldb, postgresql, db2, sqlserver, informix, h2, sqlserver2012, derby]

tm:
  test-mode: true
  engine:
    base-url: "http://49.50.129.218:8000/api/v1/optimize/base"
    connect-timeout: 30000
    read-timeout: 1200000
    retry-count: 3
    retry-delay: 2000

---

spring:
  config:
    activate:
      on-profile: dev
  batch:
    restApi:
      url: https://waylodev.ifresh.co.kr:9443
      #url: http://10.74.11.64:9680
logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: /app/logs/applog/${spring.application.logfilename}.log
  logback:
    rollingpolicy:
      file-name-pattern: "/app/logs/applog/${spring.application.logfilename}.%d{yyyy-MM-dd}.%i"
      max-history: 30
  level:
    org:
      springframework: INFO
      apache: ERROR
    com: ERROR
    ${server.server-header}: DEBUG

tm:
  engine:
    base-url: "http://49.50.129.218:8000/api/v1/optimize/base"

---

spring:
  config:
    activate:
      on-profile: qa
  batch:
    restApi:
      url: https://wayloqa.ifresh.co.kr
  datasource-oracle:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.73.197.41:1541/FWWMSDBQ.cj.net
    username: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
    password: ENC(8z/0HjWxtjhC0fQ3XqYNb664cZ5rfpiI)

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: /app/logs/applog/${spring.application.logfilename}.log
  logback:
    rollingpolicy:
      file-name-pattern: "/app/logs/applog/${spring.application.logfilename}.%d{yyyy-MM-dd}.%i"
      max-history: 30
  level:
    org:
      springframework: INFO
      apache: ERROR
    com: ERROR
    ${server.server-header}: DEBUG

tm:
  test-mode: false
  engine:
    base-url: "http://49.50.129.218:8000/api/v1/optimize/base"
---

spring:
  config:
    activate:
      on-profile: prd
  batch:
    restApi:
      url: https://waylo.ifresh.co.kr
  datasource-oracle:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=ON)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=10.73.151.111)(PORT=1591))(ADDRESS=(PROTOCOL=TCP)(HOST=10.73.151.113)(PORT=1591)))(CONNECT_DATA=(SERVICE_NAME=FWWMSDBP.cj.net)))
    username: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
    password: ENC(iOgNulfg0LPnM/8UXwa+LCYrAoZzY4wp)
  #data:
  #  redis:
  #    host: 10.74.10.193
  #    port: 18504
  #    password: redis2026!
  #    timeout: 6000
  # cj 실오픈여부
  cj:
    realOpen:
      quick: N

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: /app/logs/applog/${spring.application.logfilename}.log
  logback:
    rollingpolicy:
      file-name-pattern: "/app/logs/applog/${spring.application.logfilename}.%d{yyyy-MM-dd}.%i"
      max-history: 30
  level:
    org:
      springframework: ERROR
      apache: ERROR
    com: ERROR
    ${server.server-header}: ERROR

#운영에서는 Swagger 미사용
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

tm:
  test-mode: false
  engine:
    base-url: "https://cj.roouty.io/api/v1/optimize/base"

---

spring:
  config:
    activate:
      on-profile: set
  batch:
    restApi:
      url: https://10.74.11.78
  datasource-oracle:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.73.197.41:1541/FWWMSDBS.cj.net
    username: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
    password: ENC(8z/0HjWxtjhC0fQ3XqYNb664cZ5rfpiI)

logging:
  pattern:
    file: "[%d{HH:mm:ss.SSS}][%-5level][%logger.%method:line%line] - %msg%n"
  file:
    name: /app/logs/applog/${spring.application.logfilename}.log
  logback:
    rollingpolicy:
      file-name-pattern: "/app/logs/applog/${spring.application.logfilename}.%d{yyyy-MM-dd}.%i"
      max-history: 30
  level:
    org:
      springframework: INFO
      apache: ERROR
    com: ERROR
    ${server.server-header}: DEBUG

tm:
  test-mode: false