<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="msBlankLocService">
	<!-- 기둥/빈 공간 정보 조회(목록) -->
    <select id="getMasterList" resultType="MsBlankLocResDto">
    	SELECT	/* [msBlankLocService.sqlx][msBlankLocService.getMasterList][기둥/빈공간정보 조회(목록)][jangjaehyun][20250624]  */
    		   MS_BLANKLOC.SERIALKEY    
    		  ,MS_BLANKLOC.DCCODE        												        AS DCCODE       /* 센터코드 */
              ,MS_BLANKLOC.LOC           												        AS LOC          /* 로케이션 */
              ,MS_BLANKLOC.ZONE         												        AS ZONE         /* 소속존 */
              ,MS_BLANKLOC.DESCRIPTION													        AS DESCRIPTION  /* 로케이션명 */
              ,MS_BLANKLOC.LOCTYPE                                                  		    AS LOCTYPE     	/* 로케이션유형 */
              ,MS_BLANKLOC.RACKLINE                                                             AS RACKLINE
              ,MS_BLANKLOC.RACKCOLUMN                                                           AS RACKCOLUMN
              ,MS_BLANKLOC.DEL_YN                                                               AS DEL_YN
              ,MS_BLANKLOC.ADDWHO                                                               AS ADDWHO
              ,MS_BLANKLOC.ADDDATE                                                              AS ADDDATE
              ,MS_BLANKLOC.EDITWHO                                                              AS EDITWHO
              ,MS_BLANKLOC.EDITDATE                                                             AS EDITDATE
              ,USER1.USER_NM                                                                    AS ADDWHO_NM  /*등록자명*/
			  ,USER2.USER_NM                                                                    AS EDITWHO_NM  /*수정자명*/
        FROM   MS_BLANKLOC
		JOIN   CM_USER_AUTHORITY_DC  
        ON     CM_USER_AUTHORITY_DC.USERID    	= #{gUserId}
        AND    CM_USER_AUTHORITY_DC.DCCODE     	= MS_BLANKLOC.DCCODE
        LEFT JOIN FRAMEONE_USER USER1 ON USER1.USER_ID = MS_BLANKLOC.ADDWHO   /*등록자명*/
        LEFT JOIN FRAMEONE_USER USER2 ON USER2.USER_ID = MS_BLANKLOC.EDITWHO  /*수정자명*/
        WHERE  1=1
        <if test='dcCode != null and dcCode.trim().length() > 0'>
		   AND     MS_BLANKLOC.DCCODE               LIKE #{dcCode}
        </if>
        <if test="zone != null and zone.trim().length() > 0">
        	AND    MS_BLANKLOC.ZONE                 LIKE #{zone}
        </if>
        <if test="locType != null and locType.trim().length() > 0">
        	AND    MS_BLANKLOC.LOCTYPE              LIKE #{locType}
        </if>
        <if test="loc != null and loc.trim().length() > 0">
        	AND    MS_BLANKLOC.LOC                  LIKE #{loc}
        </if>
        ORDER BY LOC
    </select>    
    
    <!-- 기둥/빈 공간 정보 INSERT -->
    <insert id="insertMaster">
		INSERT	/* [msBlankLocService.sqlx][msBlankLocService.insertMaster][기둥/빈공강 정보 INSERT][jangjaehyun][20250624]  */ 
        INTO MS_BLANKLOC
          (SERIALKEY
          ,STORERKEY
          ,DCCODE
          ,LOC
          ,DESCRIPTION
          ,ZONE
          ,RACKLINE
          ,RACKCOLUMN
          ,LOCTYPE
          ,DEL_YN
          ,ADDWHO
          ,ADDDATE
          ,EDITWHO
          ,EDITDATE
          )
        VALUES
          (SEQ_MS_BLANKLOC.NEXTVAL
          ,#{gStorerkey}
          ,#{dcCode}
          ,UPPER(#{loc})
          ,#{description}
          ,NVL(UPPER(#{zone}), 'STD')
          ,NVL(#{rackLine}, 1)
          ,NVL(#{rackColumn}, 1)
          ,#{locType}
          ,NVL(#{delYn}, 'N')
          ,#{gUserId}
          ,SYSDATE
          ,#{gUserId}
          ,SYSDATE
          )
    </insert>
    
    <!-- 기둥/빈 공간 정보 UPDATE -->
    <update id="updateMaster">		
		UPDATE	/* [msBlankLocService.sqlx][msBlankLocService.updateMaster][기둥/빈공강 정보 UPDATE][jangjaehyun][20250624]  */
			MS_BLANKLOC
			SET DESCRIPTION  = #{description},
			ZONE         = UPPER(#{zone}),
			RACKLINE     = #{rackLine},
			RACKCOLUMN   = #{rackColumn},
			LOCTYPE      = #{locType},
			DEL_YN       = #{delYn},
			EDITDATE     = SYSDATE,
			EDITWHO      = #{gUserId}
		WHERE SERIALKEY = #{serialKey}
	</update>
	
	<!-- ZONE 리스트 조회 -->
    <select id="getDataZone" resultType="MsBlankLocZoneResDto">
		SELECT /* [msBlankLocService.sqlx][msBlankLocService.getDataZone][ZONE 리스트 조회][jangjaehyun][20250624] */
			 DCCODE 		AS DCCODE
       		,ZONE 			AS BASECODE
       		,'['||ZONE||']'||DESCRIPTION 	AS BASEDESCR 
		FROM MS_ZONE
		WHERE 1=1
		  AND DEL_YN = 'N'		
		ORDER BY ZONE
    </select>
   
</mapper>