<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="msCarDriverService">
	<!-- 차량정보 정보 조회(목록) -->
    <select id="getMasterList" resultType="MsCarDriverResDto">
    	SELECT /* [msCarDriverService.sqlx][msCarDriverService.getMasterList][차량정보 정보 조회(목록)][jangjaehyun][20250812] */
               DISTINCT
    	       CM_CAR.SERIALKEY,    		   
               MS_CAR_ENTRY_INFO.DCCODE         AS DCCODE,
               (SELECT DCNAME FROM CM_DC WHERE DCCODE = MS_CAR_ENTRY_INFO.DCCODE	) AS DCNAME ,
               MS_CAR_ENTRY_INFO.TC_DCCODE,
               CM_TC.TCNAME,
               CM_CAR.CONTRACTTYPE,
               CM_CAR.CARID,
               CM_CAR.CARNO,
               CM_CAR.CARCAPACITY,
               CM_CAR.OPT_LOAD_WEIGHT,
               CM_CAR.MAXWEIGHT,
               CM_CAR.CARGOSIZE,
               CM_CAR.CARGOTYPE,
               CM_CAR.DTGTYPE,
               CM_CAR.GPSTYPE,
               CM_CAR.VEHICLE_YEAR,
               CM_CAR.OTHER03                   AS CAROTHER03,
               CM_CAR.MAXLANDING,
               CM_CAR.CARGROUP,
               CM_CAR.CHECKCAR,
               CM_CAR.INDT,
               CM_CAR.OUTDT,
               CM_CAR.DOCKNO,
               CM_CAR.LAREA,
               CM_CAR.MAREA,
               CM_CAR.SAREA,
               CM_CAR.LINKCARNO1,
               CM_CAR.LINKCARNO2,
               CM_CAR.LINKCARNO3,
               CM_CAR.SHORTNO,
               CM_CAR.BTSCANNERGIVE,
               CM_CAR.PDAPHONE2,
               CM_CAR.PDAPHONE3,
               CM_CAR.PDAPHONE4,
               CM_CAR.ALLOW_LOGIN_YN,
               CM_CAR.SMPGIVE,
               CM_CAR.PDAPHONE1,
               CM_DRIVER.DRIVERNAME,
               DAMO.DEC(CM_DRIVER.PHONE1)       AS PHONE1,
               DAMO.DEC(CM_DRIVER.PHONE2)       AS PHONE2,
               DAMO.DEC(CM_CAR.PHONE3)          AS PHONE3,
               DAMO.DEC(CM_CAR.PHONE4)          AS PHONE4,
               CM_CAR.DRIVER2,
               CM_CAR.DRIVER3,
               CM_CAR.DRIVER3                   AS DRIVER3D,
               CM_CAR.DRIVER4,
               CM_CAR.DEL_YN,
               CM_CAR.EDITDATE,
               CM_CAR.CARCUBEDESCR,
               CM_DRIVER.DRIVERID               AS DRIVER1,
               CM_CAR.EDITWHO,
               CM_CAR.FROMDATE,
               CM_CAR.TODATE,
               CM_CAR.TODATE2,
               CM_CAR.ADDWHO,
               CM_CAR.ADDDATE,
               CM_CAR.CAR_WIDTH,
               CM_CAR.CAR_LENGTH,
               CM_CAR.VEHICLE_HEIGHT,
               USER1.USER_NM                    AS ADDWHO_NM,  /*등록자명*/
               USER2.USER_NM                    AS EDITWHO_NM  /*수정자명*/
          FROM CM_CAR
     LEFT JOIN CM_DRIVER ON CM_DRIVER.DRIVERID = CM_CAR.DRIVER1
     LEFT JOIN MS_CAR_ENTRY_INFO ON CM_CAR.CARNO = MS_CAR_ENTRY_INFO.CARNO
     LEFT JOIN CM_TC ON MS_CAR_ENTRY_INFO.TC_DCCODE = CM_TC.TCCODE
     LEFT JOIN FRAMEONE_USER USER1 ON USER1.USER_ID = CM_CAR.ADDWHO   /*등록자명*/
     LEFT JOIN FRAMEONE_USER USER2 ON USER2.USER_ID = CM_CAR.EDITWHO  /*수정자명*/
         WHERE 1=1		
        <!-- 차량 다중선택 -->				
        <if test='carNo != null and carNo !=""'>
           AND CM_CAR.CARNO IN
                              ( SELECT TRIM(REGEXP_SUBSTR(VAL,'[^,]+',1,LEVEL)) AS VAL
                                  FROM (SELECT #{carNo} AS VAL FROM DUAL) A
                               CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
        </if>
        <if test='multiDcCode != null and multiDcCode.length > 0'>
           AND (MS_CAR_ENTRY_INFO.DCCODE IN
            <foreach collection="multiDcCode" item="dccodeItem" open="(" separator="," close=")">
                   #{dccodeItem}
            </foreach>
                OR MS_CAR_ENTRY_INFO.DCCODE IS NULL)
        </if>
        <if test="driver1 != null and driver1 != ''">
           AND CM_DRIVER.DRIVERNAME LIKE '%' || #{driver1} || '%'
        </if>
        <if test="delYn != null and delYn != ''">
           AND CM_CAR.DEL_YN LIKE #{delYn}
        </if>
        <if test="contractType != null and contractType != ''">
           AND CM_CAR.CONTRACTTYPE LIKE #{contractType}
        </if>
        <!--TC센터 검색-->
        <if test="tcDcCode != null and tcDcCode != ''">
          AND MS_CAR_ENTRY_INFO.TC_DCCODE = #{tcDcCode}
           </if>
        <!-- 운송사 다중선택 -->				
        <if test='custKey != null and custKey !=""'>
           AND CM_CAR.COURIER IN
                                (SELECT TRIM(REGEXP_SUBSTR(VAL,'[^,]+',1,LEVEL)) AS VAL
                                   FROM (SELECT #{custKey} AS VAL FROM DUAL) A
                                CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
        </if>
        <if test="isExpirationDateExpired != null and isExpirationDateExpired != ''">
            <choose>
                <when test='isExpirationDateExpired == "N"'>
          AND NVL(CM_CAR.FROMDATE, '19000101') <![CDATA[>=]]> TO_CHAR(SYSDATE, 'YYYYMMDD')
          AND NVL(CM_CAR.TODATE2, '19000101') <![CDATA[>=]]> TO_CHAR(SYSDATE, 'YYYYMMDD')
          AND NVL(CM_CAR.TODATE, '19000101') <![CDATA[>=]]> TO_CHAR(SYSDATE, 'YYYYMMDD')
                </when>
                 <when test='isExpirationDateExpired == "I"'>
          AND (     NVL(CM_CAR.FROMDATE, '19000101') <![CDATA[<]]> TO_CHAR(SYSDATE-14, 'YYYYMMDD')
                OR  NVL(CM_CAR.TODATE2, '19000101')  <![CDATA[<]]> TO_CHAR(SYSDATE-14, 'YYYYMMDD')
                OR  NVL(CM_CAR.TODATE, '19000101')   <![CDATA[<]]> TO_CHAR(SYSDATE-14, 'YYYYMMDD')
              )
                 </when>
                <otherwise>
          AND (     NVL(CM_CAR.FROMDATE, '19000101') <![CDATA[<]]> TO_CHAR(SYSDATE, 'YYYYMMDD')
                OR  NVL(CM_CAR.TODATE2, '19000101') <![CDATA[<]]> TO_CHAR(SYSDATE, 'YYYYMMDD')
                OR  NVL(CM_CAR.TODATE, '19000101') <![CDATA[<]]> TO_CHAR(SYSDATE, 'YYYYMMDD')
              )
                </otherwise>
            </choose>
        </if>
        ORDER BY MS_CAR_ENTRY_INFO.DCCODE ASC,  CM_CAR.CARID ASC 
        
    </select>
    
    <!-- 차량 정보 조회(단건) -->
    <select id="getMaster" resultType="MsCarDriverDetailResDto">
         SELECT /* [msCarDriverService.sqlx][msCarService.getMaster][차량 정보 조회(단건)][jangjaehyun][20250812] */
	           CM_CAR.SERIALKEY,
	           CM_CAR.SERIALKEY                               AS DRIVERSERIALKEY,
	           CM_CAR.CARID,
	           CM_CAR.CARNO,
	           CM_CAR.SHORTNO,
	           CM_CAR.CARGROUP,
	           CM_CAR.CARTYPE,
	           CM_CAR.CARCATEGORY,
	           CM_CAR.CARCAPACITY,
	           CM_CAR.CARCUBEDESCR,
	           CM_CAR.BRANDNAME,
	           CM_CAR.DEF_DCCODE                              AS DCCODE,
	           CM_CAR.DEF_DISTRICTCODE,
	           CM_CAR.DRIVER2,
	           CM_CAR.DRIVER3,
	           CM_CAR.DRIVER4,
	           CM_DRIVER2.DRIVERNAME                          AS DRIVERNAME2,
	           CM_CAR.GARAGEADDRESS1,
	           CM_CAR.GARAGEADDRESS2,
	           CM_CAR.GARAGEADDRESS3,
	           CM_CAR.GARAGEADDRESS4,
	           CM_CAR.PDAPHONE1,
	           CM_CAR.PDAPHONE2,
	           CM_CAR.PDAPHONE3,
	           CM_CAR.PDAPHONE4,
	           CM_CAR.ALLOW_LOGIN_YN,
	           CM_CAR.OWNER,
	           CM_CAR.CONTRACTTYPE,
	           CM_CAR.CONTRACTDATE,
	           CM_CAR.EXPIREDATE,
	           CM_CAR.CONTRACTPRICE,
	           CM_CAR.CARAGENTKEY,
	           MS_CARRIER2.DESCRIPTION AS CARAGENTNAME,
	           DAMO.DEC(CM_CAR.CARAGENTPHONE) AS CARAGENTPHONE,
	           CM_CAR.CARAGENTFAX,
	           CM_CAR.INSURANCE,
	           CM_CAR.INSUCONTDATE,
	           CM_CAR.INSUEXPIDATE,
	           CM_CAR.CARGOTYPE,
	           CM_CAR.CARGOSIZE,
	           CM_CAR.CARGOCUBE,
	           CM_CAR.MINCUBE,
	           CM_CAR.MAXCUBE,
	           CM_CAR.MINWEIGHT,
	           CM_CAR.MAXWEIGHT,
	           CM_CAR.DTGTYPE,
	           CM_CAR.DTGNO,
	           CM_CAR.DTGCOMMNO,
	           CM_CAR.GPSTYPE,
	           CM_CAR.GPSNO,
	           CM_CAR.GPSCOMMNO,
	           CM_CAR.THERMOMETERTYPE,
	           CM_CAR.THERMOMETERNO,
	           CM_CAR.THERMOMETERCOMMNO,
	           CM_CAR.REFRIGERATORTYPE,
	           CM_CAR.GASTYPE,
	           CM_CAR.GASCUBE,
	           CM_CAR.FUELEFFICIENCY,
	           CM_CAR.BASEFUELEFFICIENCY,
	           CM_CAR.REGISTRATIONDATE,
	           CM_CAR.OTHER01                                 AS CAROTHER01,
	           CM_CAR.OTHER02                                 AS CAROTHER02,
	           CM_CAR.OTHER03                                 AS CAROTHER03,
	           CM_CAR.STATUS,
	           CM_CAR.DEL_YN,
	           CM_CAR.TRAFFICCOP,
	           CM_CAR.ARCHIVECOP,
	           CM_CAR.ADDDATE,
	           CM_CAR.EDITDATE,	           
	           NVL(USER1.USER_NM, CM_CAR.ADDWHO) AS ADDWHO,
	           NVL(USER2.USER_NM, CM_CAR.EDITWHO) AS EDITWHO,
	           CM_CAR.PDASECURITYKEY,
	           CM_CAR.PDASECEXPIDATE,
	           CM_DRIVER1.DRIVERID,
	           CM_DRIVER1.DRIVERNAME,
	           CM_DRIVER1.DRIVERSEX,
	           CM_DRIVER1.DRIVERBIRTHDAY,
	           CM_DRIVER1.DRIVERGROUP,
	           CM_DRIVER1.DRIVERTYPE,
	           CM_DRIVER1.DRIVERCATEGORY,
	           CM_DRIVER1.ADDRESS1,
	           CM_DRIVER1.ADDRESS2,
	           CM_DRIVER1.ADDRESS3,
	           CM_DRIVER1.ADDRESS4,
	           REGEXP_REPLACE(REPLACE(DAMO.DEC(CM_DRIVER1.PHONE1), '-', ''), '([0-9]{3})([0-9]{3,4})([0-9]{4})', '\1-\2-\3')   AS PHONE1,
	           DAMO.DEC(CM_DRIVER1.PHONE2)                    AS PHONE2,
	           DAMO.DEC(CM_CAR.PHONE3)                        AS PHONE3,
	           DAMO.DEC(CM_CAR.PHONE4)                        AS PHONE4,
	           CM_DRIVER1.PDAPHONE1                           AS PDAPHONE1,
	           CM_DRIVER1.PDAPHONE2                           AS PDAPHONE2,
	           CM_DRIVER1.LICENSENO,
	           CM_DRIVER1.LICENSETYPE,
	           CM_DRIVER1.LICENCONTDATE,
	           CM_DRIVER1.LICENEXPIDATE,
	           CM_DRIVER1.VATNO,
	           CM_DRIVER1.VATNAME,
	           CM_DRIVER1.VATOWNER,
	           CM_DRIVER1.VATTYPE,
	           CM_DRIVER1.VATCATEGORY,
	           CM_DRIVER1.VATADDRESS1,
	           CM_DRIVER1.VATADDRESS2,
	           CM_DRIVER1.VATADDRESS3,
	           CM_DRIVER1.VATADDRESS4,
	           CM_DRIVER1.VATPHONE,
	           CM_DRIVER1.VATFAX,
	           CM_DRIVER1.AGENTKEY,
	           CM_DRIVER1.AGENTNAME,
	           CM_DRIVER1.CONTRACTTYPE                        AS CONTRACTTYPE,
	           CM_DRIVER1.CONTRACTDATE                        AS CONTRACTDATE,
	           CM_DRIVER1.EXPIREDATE                          AS EXPIREDATE,
	           CM_DRIVER1.CONTRACTPRICE                       AS CONTRACTPRICE,
	           CM_DRIVER1.INSUCOMPANY,
	           CM_DRIVER1.INSURANCETYPE,
	           CM_DRIVER1.INSURANCE,
	           CM_DRIVER1.INSUCONTDATE,
	           CM_DRIVER1.INSUEXPIDATE,
	           CM_DRIVER1.OTHER01                             AS DRIVEROTHER01,
	           CM_DRIVER1.OTHER02                             AS DRIVEROTHER02,
	           CM_DRIVER1.OTHER03                             AS DRIVEROTHER03,
	           CM_DRIVER1.OTHER04                             AS DRIVEROTHER04,
	           CM_DRIVER1.OTHER05                             AS DRIVEROTHER05,
	           CM_DRIVER1.OTHER05                             AS DRIVEROTHER05,
	           CM_DRIVER1.OTHER05                             AS DRIVEROTHER05,	           
	           CM_CAR.LAREA,
	           CM_CAR.MAREA,
	           CM_CAR.SAREA,
	           CM_CAR.INDT,
	           CM_CAR.OUTDT,
	           CM_CAR.DOCKNO,
	           CM_CAR.CARMEMO,
	           CM_CAR.NOTE,
	           CM_CAR.CHECKCAR,
	           CM_CAR.LINKCARNO1,
	           CM_CAR.LINKCARNO2,
	           CM_CAR.LINKCARNO3,
	           CM_CAR.BTSCANNERGIVE,
	           CM_CAR.SMPGIVE,
	           CM_CAR.DRIVERMEMO,
	           CM_CAR.DRIVERNOTE,
	           CM_CAR.CARGODIVTYPE,
	           CM_CAR.MAXLANDING,
	           (SELECT MAX(MS_DISTRICT.DISTRICTNAME)
	              FROM MS_DISTRICT
	             WHERE MS_DISTRICT.CARNO = (SELECT MAX(CARID) FROM CM_CAR M WHERE M.CARNO = CM_CAR.LINKCARNO1)
	               AND MS_DISTRICT.DCCODE = #{dcCode}) AS LINKCARNAME1,
	           (SELECT MAX(MS_DISTRICT.DISTRICTNAME)
	              FROM MS_DISTRICT
	             WHERE MS_DISTRICT.CARNO = (SELECT MAX(CARID) FROM CM_CAR M WHERE M.CARNO = CM_CAR.LINKCARNO2)
	               AND MS_DISTRICT.DCCODE = #{dcCode}) AS LINKCARNAME2,
	           (SELECT MAX(MS_DISTRICT.DISTRICTNAME)
	              FROM MS_DISTRICT
	             WHERE MS_DISTRICT.CARNO = (SELECT MAX(CARID) FROM CM_CAR M WHERE M.CARNO = CM_CAR.LINKCARNO3)
	               AND MS_DISTRICT.DCCODE = #{dcCode}) AS LINKCARNAME3,
	           (SELECT MAX(MS_DISTRICT.DISTRICTCODE)
	              FROM MS_DISTRICT
	             WHERE MS_DISTRICT.CARNO = CM_CAR.CARID
	               AND MS_DISTRICT.DCCODE = #{dcCode}) AS POPNO,
	           CM_CAR.HJDONG_CD,
	           CM_CAR.FROM_DCCODE,
	           CM_CAR.LATITUDE,
	           CM_CAR.LONGITUDE,
	           CM_CAR.OPT_LOAD_WEIGHT,
	           CM_CAR.VEHICLE_HEIGHT,
	           CM_CAR.VEHICLE_YEAR,
	           CM_CAR.VEHICLE_TYPE_CD,
	           CM_CAR.PROC_YN,
	           CM_CAR.REUSE_YN,
	           CM_CAR.PROC_TYPE_CD,
	           CM_CAR.PROC_FROMHOUR,
	           CM_CAR.PROC_TOHOUR,
	           CM_CAR.OPT_PLT,
               CM_CAR.CAR_WIDTH,
               CM_CAR.CAR_LENGTH,
               CM_CAR.DELIVERY_YN,
               CM_CAR.CARRY_YN,
               CM_CAR.PROC_SAMEDAY_YN,
               CM_CAR.PROC_STORAGE_YN,
               CM_CAR.OWN_CAR_YN,
               CM_CAR.RETURN_YN,
               CM_CAR.SUBDRIVER_YN,
               <!-- CM_CAR.CUSTKEY, -->
               CM_CAR.COURIER AS CUSTKEY,
               MS_CARRIER1.DESCRIPTION AS CUSTNAME,
               NVL(CM_CAR.STTL_YN, 'Y') AS STTL_YN,
               CM_CAR.FROMDATE,
               CM_CAR.TODATE,
               CM_CAR.TODATE2,
               CM_DRIVER1.WORK_FROMHOUR                       AS WORK_FROMHOUR,
	           CM_DRIVER1.WORK_TOHOUR                         AS WORK_TOHOUR,
	           CM_CAR.CAR_ORDERCLOSE_CD,
	           CM_CAR.RADIUS                        AS RADIUS, /* 반경 */
               CM_CAR.STYTIME                       AS STYTIME,   /* 체류시간 */ 
               CM_CAR.BASEWEIGHT_2ND,             /*2회전기본적재중량*/
               CM_CAR.MAXWEIGHT_2ND, /*2회전최대적재중량*/ 
               CM_CAR.BASELANDING_2ND, /*2회전기본착지수*/
               CM_CAR.MAXLANDING_2ND /*2회전최대착지수*/
	      FROM CM_CAR
	      LEFT OUTER JOIN CM_DRIVER CM_DRIVER1 ON CM_DRIVER1.DRIVERID = CM_CAR.DRIVER1
	      LEFT OUTER JOIN CM_DRIVER CM_DRIVER2 ON CM_DRIVER2.DRIVERID = CM_CAR.DRIVER2
	      LEFT OUTER JOIN MS_CARRIER MS_CARRIER1 ON MS_CARRIER1.CARRIERKEY = CM_CAR.COURIER AND MS_CARRIER1.CARRIERTYPE = 'LOCAL'
	      LEFT OUTER JOIN MS_CARRIER MS_CARRIER2 ON MS_CARRIER2.CARRIERKEY = CM_CAR.CARAGENTKEY AND MS_CARRIER2.CARRIERTYPE = 'SUBC'
	      LEFT JOIN FRAMEONE_USER USER1 ON USER1.USER_ID = CM_CAR.ADDWHO   /*등록자명*/
          LEFT JOIN FRAMEONE_USER USER2 ON USER2.USER_ID = CM_CAR.EDITWHO  /*수정자명*/
	     WHERE 1=1 
	    <if test="serialKey != null and serialKey != ''">
	        AND CM_CAR.SERIALKEY = #{serialKey}
	    </if>
	    <if test="carNo != null and carNo != ''">
	        AND CM_CAR.CARNO = #{carNo}
	    </if>		
	</select>
	
	<!-- 차량정보 입출차정보 조회(목록) -->
    <select id="getEntryInfoList" resultType="MsCarDriverEntryInfoResDto">
    	SELECT /* [msCarDriverService.sqlx][msCarDriverService.getEntryInfoList][차량정보 입출차정보 조회(목록)][jangjaehyun][20250904] */
    	         MS_CAR_ENTRY_INFO.SERIALKEY AS ENTRYSERIALKEY
    	       , MS_CAR_ENTRY_INFO.CARNO
    	       , MS_CAR_ENTRY_INFO.DCCODE
    	       , MS_CAR_ENTRY_INFO.OUT_GROUP_CD
    	       , MS_OUT_GROUP.IN_TIME
    	       , MS_OUT_GROUP.OUT_TIME
    	       , MS_CAR_ENTRY_INFO.POPNO
    	       , MS_CAR_ENTRY_INFO.TC_DCCODE
    	       , CM_TC.TCNAME
    	       , MS_CAR_ENTRY_INFO.DOCKNO
    	       , (SELECT LISTAGG(SUB_GROUP.OUT_GROUP_CD, ',') WITHIN GROUP (ORDER BY SUB_GROUP.OUT_GROUP_CD)
		          FROM MS_OUT_GROUP SUB_GROUP
		          WHERE SUB_GROUP.DCCODE = MS_CAR_ENTRY_INFO.DCCODE) AS OUT_GROUP_CD_LIST
		       , (SELECT LISTAGG(CM_CODE.BASEDESCR, ',') WITHIN GROUP (ORDER BY SUB_GROUP.OUT_GROUP_CD)
		          FROM MS_OUT_GROUP SUB_GROUP
		          JOIN CM_CODE ON CM_CODE.BASECODE = SUB_GROUP.OUT_GROUP_CD
		                    AND CM_CODE.CODELIST = 'CARGROUP'
		                    AND CM_CODE.DEL_YN = 'N'
		                    AND CM_CODE.STORERKEY = #{gStorerkey}
		        WHERE SUB_GROUP.DCCODE = MS_CAR_ENTRY_INFO.DCCODE) AS OUT_GROUP_NM_LIST
    	FROM MS_CAR_ENTRY_INFO
    	LEFT OUTER JOIN MS_OUT_GROUP
    	  ON  MS_CAR_ENTRY_INFO.DCCODE = MS_OUT_GROUP.DCCODE
    	 AND  MS_CAR_ENTRY_INFO.OUT_GROUP_CD = MS_OUT_GROUP.OUT_GROUP_CD
    	LEFT JOIN CM_TC
    	  ON MS_CAR_ENTRY_INFO.TC_DCCODE = CM_TC.TCCODE
        WHERE 1=1
          AND MS_CAR_ENTRY_INFO.CARNO = #{carNo}
    </select>
    
    <!-- 차량정보 정보 INSERT -->
    <insert id="insertMaster">			 
		INSERT /* [msCarDriverService.sqlx][msCarDriverService.insertMaster][차량정보 정보 INSERT][jangjaehyun][20250812] */
			INTO CM_CAR
               ( SERIALKEY, DEF_DCCODE, CARNO, CARID, SHORTNO, CARCAPACITY, CARGODIVTYPE, GARAGEADDRESS1, CARGOSIZE,
                 OTHER03, FUELEFFICIENCY, DTGTYPE, DTGNO, CARAGENTKEY, CARAGENTNAME, CARAGENTPHONE, CONTRACTTYPE,
                 MAXWEIGHT, CARGOTYPE, REGISTRATIONDATE, CARGOCUBE, MAXLANDING, BASEFUELEFFICIENCY, GPSTYPE, GPSNO,
                 CARGROUP, CHECKCAR, LAREA, MAREA, SAREA, INDT, OUTDT, DOCKNO, LINKCARNO1, LINKCARNO2, LINKCARNO3,
                 CARMEMO, NOTE, PHONE1, PHONE2, PHONE3, PHONE4, DRIVER1, DRIVER2, DRIVER3, DRIVER4, BTSCANNERGIVE,
                 PDAPHONE2, PDAPHONE3, PDAPHONE4, ALLOW_LOGIN_YN, SMPGIVE, PDAPHONE1, DRIVERMEMO, DRIVERNOTE,
                 THERMOMETERCOMMNO, CUSTKEY, CAR_LENGTH, CAR_WIDTH, VEHICLE_HEIGHT, COURIER, STTL_YN,
                 DELIVERY_YN, CARRY_YN, PROC_SAMEDAY_YN, PROC_STORAGE_YN, OWN_CAR_YN, RETURN_YN, SUBDRIVER_YN,
                 VEHICLE_YEAR, VEHICLE_TYPE_CD, OPT_LOAD_WEIGHT, LATITUDE, LONGITUDE, OPT_PLT, REUSE_YN,
                 GARAGEADDRESS2, GARAGEADDRESS3, GARAGEADDRESS4, PROC_FROMHOUR, PROC_TOHOUR, FROMDATE, TODATE, TODATE2, THERMOMETERNO, CAR_ORDERCLOSE_CD,
                 ADDDATE, EDITDATE, ADDWHO, EDITWHO, RADIUS, STYTIME ,BASEWEIGHT_2ND, MAXWEIGHT_2ND, BASELANDING_2ND, MAXLANDING_2ND
               )
        SELECT SEQ_CM_CAR.NEXTVAL,
               #{dcCode}, #{carNo}, #{carNo}, #{shortNo}, #{carCapacity}, #{cargoDivType}, #{garageAddress1}, #{cargoSize},
               #{carOther03}, #{fuelEfficiency}, #{dtgType}, #{dtgNo}, #{carAgentKey}, #{carAgentName}, #{carAgentPhone}, #{contractType},
               #{maxWeight}, #{cargoType}, #{registrationDate}, #{cargoCube}, #{maxLanding}, #{baseFuelEfficiency}, #{gpsType}, #{gpsNo},
               #{carGroup}, #{checkCar}, #{lArea}, #{mArea}, #{sArea}, #{inDt}, #{outDt}, #{dockNo}, #{linkCarNo1}, #{linkCarNo2}, #{linkCarNo3},
               #{carMemo}, #{note}, DAMO.ENC(#{phone1}), DAMO.ENC(#{phone2}), DAMO.ENC(#{phone3}), DAMO.ENC(#{phone4}),
               #{driverId}, #{driver2}, #{driver3}, #{driver4}, #{btScannerGive}, #{pdaPhone2}, #{pdaPhone3}, #{pdaPhone4},
               #{allowLoginYn}, #{smpGive}, #{pdaPhone1}, #{driverMemo}, #{driverNote}, #{thermometerCommNo},
               #{custKey}, #{carLength}, #{carWidth}, #{vehicleHeight}, #{custKey}, #{sttlYn},
               #{deliveryYn}, #{carryYn}, #{procSamedayYn}, #{procStorageYn}, #{ownCarYn}, #{returnYn}, #{subDriverYn},
               #{vehicleYear}, #{vehicleTypeCd}, #{optLoadWeight}, #{latitude}, #{longitude}, #{optPlt}, #{reuseYn}, 
               #{garageAddress2}, #{garageAddress3}, #{garageAddress4}, #{procFromHour}, #{procToHour}, #{fromDate}, #{toDate}, #{toDate2}, #{thermometerNo}, #{carOrderCloseCd},             
               SYSDATE, SYSDATE, #{gUserId}, #{gUserId}, #{radius}, #{stytime}, #{baseWeight2nd}, #{maxWeight2nd}, #{baseLanding2nd}, #{maxLanding2nd}
          FROM DUAL
    </insert>    
    
    <!-- 차량정보 정보 UPDATE -->
    <update id="updateMaster">		
		UPDATE /* [msCarDriverService.sqlx][msCarDriverService.updateMaster][차량정보 정보 UPDATE][jangjaehyun][20250812] */
		    CM_CAR
           SET DEF_DCCODE = #{dcCode},
               SHORTNO = #{shortNo},
               CARCAPACITY = #{carCapacity},
               CARGODIVTYPE = #{cargoDivType},
               GARAGEADDRESS1 = #{garageAddress1},
               GARAGEADDRESS2 = #{garageAddress2},
               GARAGEADDRESS3 = #{garageAddress3},
               GARAGEADDRESS4 = #{garageAddress4},
               CARGOSIZE = #{cargoSize},
               OTHER03 = #{carOther03},
               FUELEFFICIENCY = #{fuelEfficiency},
               DTGTYPE = #{dtgType},
               DTGNO = #{dtgNo},
               CARAGENTKEY = #{carAgentKey},
               CARAGENTNAME = #{carAgentName},
               CARAGENTPHONE = #{carAgentPhone},
               CONTRACTTYPE = #{contractType},
               MAXWEIGHT = #{maxWeight},
               CARGOTYPE = #{cargoType},
               REGISTRATIONDATE = #{registrationDate},
               CARGOCUBE = #{cargoCube},
               MAXLANDING = #{maxLanding},
               BASEFUELEFFICIENCY = #{baseFuelEfficiency},
               GPSTYPE = #{gpsType},
               GPSNO = #{gpsNo},
               CARGROUP = #{carGroup},
               CHECKCAR = #{checkCar},
               LAREA = #{lArea},
               MAREA = #{mArea},
               SAREA = #{sArea},
               INDT = #{inDt},
               OUTDT = #{outDt},
               DOCKNO = #{dockNo},
               LINKCARNO1 = #{linkCarNo1},
               LINKCARNO2 = #{linkCarNo2},
               LINKCARNO3 = #{linkCarNo3},
               CARMEMO = #{carMemo},
               NOTE = #{note},
               PHONE1 = DAMO.ENC(#{phone1}),
               PHONE2 = DAMO.ENC(#{phone2}),
               PHONE3 = DAMO.ENC(#{phone3}),
               PHONE4 = DAMO.ENC(#{phone4}),
               DRIVER1 = #{driverId},
               DRIVER2 = #{driver2},
               DRIVER3 = #{driver3},
               DRIVER4 = #{driver4},
               BTSCANNERGIVE = #{btScannerGive},
               PDAPHONE2 = #{pdaPhone2},
               PDAPHONE3 = #{pdaPhone3},
               PDAPHONE4 = #{pdaPhone4},
               ALLOW_LOGIN_YN = #{allowLoginYn},
               SMPGIVE = #{smpGive},
               PDAPHONE1 = #{pdaPhone1},
               DRIVERMEMO = #{driverMemo},
               DRIVERNOTE = #{driverNote},
               THERMOMETERCOMMNO = #{thermometerCommNo},
               EDITDATE = SYSDATE,
               EDITWHO = #{gUserId},
               STTL_YN = #{sttlYn},
               PROC_FROMHOUR = #{procFromHour},
               PROC_TOHOUR = #{procToHour},
               REUSE_YN = #{reuseYn},
               VEHICLE_YEAR = #{vehicleYear},
               VEHICLE_TYPE_CD = #{vehicleTypeCd},
               OPT_LOAD_WEIGHT = #{optLoadWeight},
               LATITUDE = #{latitude},
               LONGITUDE = #{longitude},
               OPT_PLT = #{optPlt},
               DELIVERY_YN = #{deliveryYn},
               CARRY_YN = #{carryYn},
               PROC_SAMEDAY_YN = #{procSamedayYn},
               PROC_STORAGE_YN = #{procStorageYn},
               OWN_CAR_YN = #{ownCarYn},
               RETURN_YN = #{returnYn},
               SUBDRIVER_YN = #{subDriverYn},
               CUSTKEY = #{custKey},
               CAR_LENGTH = #{carLength},
               CAR_WIDTH = #{carWidth},
               VEHICLE_HEIGHT = #{vehicleHeight},
               COURIER = #{custKey},
               FROMDATE = #{fromDate},
               TODATE = #{toDate},
               TODATE2 = #{toDate2},
               THERMOMETERNO = #{thermometerNo},
               CAR_ORDERCLOSE_CD = #{carOrderCloseCd},
               DEL_YN = #{delYn},
               RADIUS = #{radius}, /* 반경 */
               STYTIME = #{stytime},   /* 체류시간 */               
               BASEWEIGHT_2ND = #{baseWeight2nd},
               MAXWEIGHT_2ND = #{maxWeight2nd},
               BASELANDING_2ND = #{baseLanding2nd},
               MAXLANDING_2ND = #{maxLanding2nd}
         WHERE CARNO = #{carNo}
	</update>
	
	<!-- 차량정보 정보 UPDATE -->
    <update id="updateMasterList">		
		UPDATE /* [msCarDriverService.sqlx][msCarDriverService.updateMasterList][차량정보 정보 UPDATE][jangjaehyun][20250812] */
		    CM_CAR
           SET OTHER03 = #{carOther03},
               OPT_LOAD_WEIGHT =#{optLoadWeight},
               MAXWEIGHT = #{maxWeight},
               REGISTRATIONDATE = #{registrationDate},
               CARGOCUBE = #{cargoCube},
               MAXLANDING = #{maxLanding},
               PHONE1 = DAMO.ENC(#{phone1}),
               PHONE2 = DAMO.ENC(#{phone2}),
               DRIVER1 = #{driver1},
               DRIVER2 = #{driver2},
               BTSCANNERGIVE = #{btScannerGive},
               PDAPHONE2 = #{pdaPhone2},
               SMPGIVE = #{smpGive},
               THERMOMETERNO = #{thermometerNo},
               FROMDATE = #{fromDate},               
               TODATE = #{toDate},
               TODATE2 = #{toDate2},
               CARCAPACITY = #{carCapacity},
               CAR_LENGTH = #{carLength},
               CAR_WIDTH = #{carWidth},
               VEHICLE_HEIGHT = #{vehicleHeight},
               VEHICLE_YEAR = #{vehicleYear},
               DEL_YN = #{delYn},               
               EDITDATE = SYSDATE,
               EDITWHO = #{gUserId}
         WHERE CARNO = #{carNo}
	</update>
	
	<!-- 입출차정보 정보 UPDATE -->
    <update id="updateEntryInfoList">		
		MERGE /* [msCarDriverService.sqlx][msCarDriverService.updateEntryInfoList][입출차정보 정보 UPDATE][jangjaehyun][20250904] */ INTO MS_CAR_ENTRY_INFO
             USING DUAL
                ON (SERIALKEY = #{entrySerialKey})
        WHEN MATCHED THEN
             UPDATE SET
				    DCCODE = #{dcCode},
				    OUT_GROUP_CD = #{outGroupCd},
				    POPNO = #{popno},
				    TC_DCCODE = #{tcDcCode},
				    DOCKNO = #{dockno},
				    EDITDATE = SYSDATE,
				    EDITWHO = #{gUserId}
        WHEN NOT MATCHED THEN
             INSERT (CARNO
                    ,DCCODE
                    ,OUT_GROUP_CD
                    ,POPNO
					,TC_DCCODE
                    ,DOCKNO
                    ,ADDDATE
                    ,ADDWHO
                    ,EDITDATE
                    ,EDITWHO)
            VALUES  (#{carNo}
                    ,#{dcCode}
                    ,#{outGroupCd}
                    ,#{popno}
					,#{tcDcCode}
                    ,#{dockno}
                    ,SYSDATE
                    ,#{gUserId}
                    ,SYSDATE
                    ,#{gUserId})
	</update>
	
	<!-- 입출차정보 정보 DELETE -->
    <delete id="deleteEntryInfoList">		
		DELETE /* [msCarDriverService.sqlx][msCarDriverService.updateEntryInfoList][입출차정보 정보 UPDATE][jangjaehyun][20250904] */ FROM MS_CAR_ENTRY_INFO
             WHERE SERIALKEY = #{entrySerialKey}
	</delete>
	
	<select id="update" statementType="CALLABLE" resultType="HMAP">
		<![CDATA[
        {
	        CALL  /* [msCarDriverService.sqlx][update][차량정보 정보 UPDATE][jangjaehyun][20250812] */
	        DECLARE
                V_AFTER     MS_CarDriver%rowtype;
                O_SUCCESS   NUMBER         :=  1;      /* 성공여부(1이면 성공) */
                O_ERRCODE   NUMBER         :=  0;      /* 오류 코드 */
                O_ERRMSG    VARCHAR2(4000) := '';      /* 오류 메세지 */
            BEGIN
                FOR KEY_LIST IN (
                    SELECT
                            DCCODE,	 /* 물류센터 */
                            PLANT,	 /* 플랜트 */
                            STORAGETYPE, /* 저장조건 */
                            DISTANCETYPE /* 원거리유형 */
                    FROM    MS_CarDriver
                    WHERE   DCCODE       = #{dcCode}
                      AND   PLANT        = #{plant}
                      AND   STORAGETYPE  = #{storageType}
                      AND   DISTANCETYPE = #{distanceType}
                )
                LOOP
                    BEGIN
                        SELECT  *
                        INTO    V_AFTER
                        FROM    MS_CarDriver
                        WHERE   DCCODE       = KEY_LIST.DCCODE
                          AND   PLANT        = KEY_LIST.PLANT
                          AND   STORAGETYPE  = KEY_LIST.STORAGETYPE
                          AND   DISTANCETYPE = KEY_LIST.DISTANCETYPE
                        ;
    
                       V_AFTER.DCCODE       := #{dcCode};
                       V_AFTER.PLANT        := #{plant};
                       V_AFTER.STORAGETYPE  := #{storageType};
                       V_AFTER.DISTANCETYPE := #{distanceType};
                       V_AFTER.BATCHGROUP   := #{batchGroup};
                       V_AFTER.DESCRIPTION  := #{description};
                       V_AFTER.STATUS       := #{status};
                       V_AFTER.DEL_YN       := #{delYn};
                       V_AFTER.EDITDATE     := SYSDATE;
                       V_AFTER.EDITWHO      := #{gUserId};
                       V_AFTER.ORGANIZE     := #{organize};
                       V_AFTER.AREA         := #{area};
                       V_AFTER.ORDERTYPE    := #{orderType};
                       V_AFTER.ETCCODE1     := #{etcCode1};
                       V_AFTER.ETCCODE2     := #{etcCode2};
                       V_AFTER.ETCCODE3     := #{etcCode3};
                       V_AFTER.ETCCODE4     := #{etcCode4};
                       V_AFTER.ALLO_UOM     := #{alloUom};
    
                       -- 프로시저 호출
                       TRMS_CARDRIVER.TR_UPDATE(
                                V_AFTER
                            ,   O_SUCCESS
                            ,   O_ERRCODE
                            ,   O_ERRMSG
                        );
    
                        EXIT    WHEN O_SUCCESS < 1;
    
                    END;
                END    LOOP;
    
                #{success, mode=OUT, jdbcType=INTEGER, javaType=int}    :=  O_SUCCESS;
                #{err, mode=OUT, jdbcType=INTEGER, javaType=int}        :=  O_ERRCODE;
                #{errmsg, mode=OUT, jdbcType=VARCHAR, javaType=String}  :=  O_ERRMSG;
    
            END
        }
        ]]>
    </select>
    
    <insert id="insertDriver">
        /* [msDriverService.sqlx][msDriverService.insert][기사 정보 INSERT][jangjaehyun][20250904] */
        INSERT INTO CM_DRIVER
               ( DRIVERID, DRIVERNAME, LICENSETYPE, LICENCONTDATE, OTHER01,
                 OTHER02, OTHER03, LICENSENO, LICENEXPIDATE,
                 WORK_FROMHOUR, WORK_TOHOUR, PHONE1,
                 ADDDATE, EDITDATE, ADDWHO, EDITWHO
               )
        SELECT #{driverId}, #{driverName}, #{licenseType}, #{licenContDate}, #{driverOther01},
               #{driverOther02}, #{driverOther03}, #{licenseNo}, #{licenExpiDate},
               #{workFromHour}, #{workToHour}, DAMO.ENC(#{phone1}),
               SYSDATE, SYSDATE, #{gUserId}, #{gUserId}
          FROM DUAL
    </insert>
    
    <select id="getInsertDriverId" resultType="string">
	    /* [msDriverService.sqlx][msDriverService.getInsertDriverId][기사 정보 INSERT - KEY 조회][jangjaehyun][202501121] */
	    SELECT
			    DECODE(
			        (SELECT MAX(MEMO) 
				    FROM MS_CARRIER 
				    WHERE CARRIERKEY IN (#{carAgentKey})),
				    NULL,
				    'D' || TO_CHAR(SYSDATE, 'RR') || LPAD(SEQ_CM_DRIVER_01.NEXTVAL, 4, '0'),
				    (SELECT MAX(MEMO) 
			        FROM MS_CARRIER 
			        WHERE CARRIERKEY IN (#{custKey}, #{carAgentKey})
			          AND CARRIERTYPE = 'SUBC') || TO_CHAR(SYSDATE, 'RR') || LPAD(SEQ_CM_DRIVER_01.NEXTVAL, 4, '0')
			    ) || '_WAYLO' AS DRIVERID
			FROM DUAL
    </select>

    <update id="updateDriver">
        /* [msDriverService.sqlx][msDriverService.update][기사 정보 UPDATE][jangjaehyun][20250904] */
        UPDATE CM_DRIVER
           SET DRIVERNAME = #{driverName},
               LICENSETYPE = #{licenseType},
               LICENCONTDATE = #{licenContDate},
               OTHER01 = #{driverOther01},
               OTHER02 = #{driverOther02},
               OTHER03 = #{driverOther03},
               LICENSENO = #{licenseNo},
               LICENEXPIDATE = #{licenExpiDate},
               WORK_FROMHOUR = #{workFromHour},
               WORK_TOHOUR = #{workToHour},
               PHONE1 = DAMO.ENC(#{phone1}),
               PHONE2 = DAMO.ENC(#{phone2}),
               EDITDATE = SYSDATE,
               EDITWHO = #{gUserId}
         WHERE DRIVERID = #{driverId}
    </update>

    <select id="getDataCarDriverExcelUploadResult" parameterType="map" resultType="map">
        SELECT /* [msCarDriverService.sqlx][msCarDriverService.getDataCarExcelUploadResult][Car 일괄등록 결과 조회] */
               '0' AS CHECKYN,
               SY_PROCESSTEMP_DM_D.AREA                   AS DEF_DCCODE,
               SY_PROCESSTEMP_DM_D.MALLINVOICE            AS DEF_DCNAME,
               SY_PROCESSTEMP_DM_D.INVOICETYPE            AS CONTRACTTYPE,
               SY_PROCESSTEMP_DM_D.DCCODE                 AS CARID,
               SY_PROCESSTEMP_DM_D.SOKEY                  AS CARNO,
               SY_PROCESSTEMP_DM_D.POTYPE                 AS CARCAPACITY,
               SY_PROCESSTEMP_DM_D.OPENQTY                AS MAXWEIGHT,
               SY_PROCESSTEMP_DM_D.ALTERSKU               AS CARCUBEDESCR,
               SY_PROCESSTEMP_DM_D.MERGEDOCNO             AS CARGOSIZE,
               SY_PROCESSTEMP_DM_D.MERGEDOCTYPE           AS CARGOTYPE,
               SY_PROCESSTEMP_DM_D.ORDERTYPE              AS DTGTYPE,
               SY_PROCESSTEMP_DM_D.SOLINE                 AS GPSTYPE,
               SY_PROCESSTEMP_DM_D.STORERKEY              AS REGISTRATIONDATE,
               SY_PROCESSTEMP_DM_D.DOCLINE                AS OTHER03,
               SY_PROCESSTEMP_DM_D.PLANDOCDT              AS MAXLANDING,
               SY_PROCESSTEMP_DM_D.PLANDOCTYPE            AS CARGROUP,
               SY_PROCESSTEMP_DM_D.ORGANIZE               AS CHECKCAR,
               SY_PROCESSTEMP_DM_D.DOCDT                  AS INDT,
               SY_PROCESSTEMP_DM_D.DOCNO                  AS OUTDT,
               SY_PROCESSTEMP_DM_D.INVOICELINE            AS DOCKNO,
               SY_PROCESSTEMP_DM_D.LOTTABLE01             AS LAREA,
               SY_PROCESSTEMP_DM_D.LOTTABLE02             AS MAREA,
               SY_PROCESSTEMP_DM_D.LOTTABLE03             AS SAREA,
               SY_PROCESSTEMP_DM_D.REFERENCE01            AS LINKCARNO1,
               SY_PROCESSTEMP_DM_D.REFERENCE02            AS LINKCARNAME1,
               SY_PROCESSTEMP_DM_D.REFERENCE03            AS LINKCARNO2,
               SY_PROCESSTEMP_DM_D.REFERENCE04            AS LINKCARNAME2,
               SY_PROCESSTEMP_DM_D.REFERENCE05            AS LINKCARNO3,
               SY_PROCESSTEMP_DM_D.REFERENCE06            AS LINKCARNAME3,
               SY_PROCESSTEMP_DM_D.OTHER01                AS SHORTNO,
               SY_PROCESSTEMP_DM_D.OTHER02                AS BTSCANNERGIVE,
               SY_PROCESSTEMP_DM_D.OTHER03                AS PDAPHONE2,
               SY_PROCESSTEMP_DM_D.OTHER04                AS SMPGIVE,
               SY_PROCESSTEMP_DM_D.OTHER05                AS PDAPHONE1,
               SY_PROCESSTEMP_DM_D.OTHER06                AS PDAPHONE3,
               SY_PROCESSTEMP_DM_D.OTHER07                AS PDAPHONE4,
               SY_PROCESSTEMP_DM_D.OTHER08                AS ALLOW_LOGIN_YN,
               SY_PROCESSTEMP_DM_D.REFERENCE07            AS DRIVERNM,
               DAMO.DEC(SY_PROCESSTEMP_DM_D.REFERENCE08)  AS PHONE1,
               SY_PROCESSTEMP_DM_D.REFERENCE09            AS DRIVER3,
               DAMO.DEC(SY_PROCESSTEMP_DM_D.REFERENCE10)  AS PHONE3,
               SY_PROCESSTEMP_DM_D.PACKINGNO              AS DRIVER4,
               DAMO.DEC(SY_PROCESSTEMP_DM_D.PROCESSCODE)  AS PHONE4,
               SY_PROCESSTEMP_DM_D.STRAGETYCODE           AS DEL_YN,
               SY_PROCESSTEMP_DM_D.WORKPROCESSCODE        AS EDITDATE,
               SY_PROCESSTEMP_DM_D.INTERFACEPROCESSCODE   AS EDITWHO,
               SY_PROCESSTEMP_DM_D.PROCESSFLAG            AS PROCESS_YN,
               SY_PROCESSTEMP_DM_D.PROCPOSS_MSG           AS PROCPOSS_MSG,
               CM_DC.DCNAME                               AS DEF_DCNAME
          FROM SY_PROCESSTEMP_DM_D
          LEFT OUTER JOIN CM_DC ON SY_PROCESSTEMP_DM_D.AREA = CM_DC.DCCODE
         WHERE SY_PROCESSTEMP_DM_D.PROCESSCREATOR = #{gUserId}
           AND SY_PROCESSTEMP_DM_D.PROCESSTYPE = #{processtype}
           AND SY_PROCESSTEMP_DM_D.SPID = #{gSpid}
         ORDER BY SY_PROCESSTEMP_DM_D.SERIALKEY
    </select>

    <insert id="insertDriverIF" parameterType="map">
        /* [msDriverService.sqlx][msDriverService.insertIF][I/F테이블에 기사 정보 INSERT][jangjaehyun][20250904] */
        INSERT INTO IF_CM_DRIVER
               ( STORERKEY, DRIVERID, DRIVERNAME, DRIVERPHONE, STATUS,
                 DEL_YN, IF_DESTINATION, IF_FLAG, IF_DATE, ADDDATE,
                 EDITDATE, ADDWHO, EDITWHO)
        SELECT 'FW00',
               #{driverId},
               #{driverName},
               DAMO.ENC(#{phone1}),
               '00',
               'N',
               'CS',
               'N',
               SYSDATE,
               SYSDATE,
               SYSDATE,
               #{gUserId},
               #{gUserId}
          FROM DUAL
    </insert>

    <update id="update_hd" parameterType="map">
        /* [msNewCarService.sqlx][msNewCarService.update_hd][차량 정보 UPDATE][jangjaehyun][20250904] */
        UPDATE CM_CAR
           SET CARCAPACITY = #{carcapacity},
               MAXWEIGHT = #{maxweight},
               CARCUBEDESCR = #{carcubedescr},
               CARGOSIZE = #{cargosize},
               CARGOTYPE = #{cargotype},
               DTGTYPE = #{dtgtype},
               GPSTYPE = #{gpstype},
               REGISTRATIONDATE = #{registrationdate},
               OTHER03 = #{carother03},
               MAXLANDING = #{maxlanding},
               CARGROUP = #{cargroup},
               CHECKCAR = #{checkcar},
               INDT = #{indt},
               OUTDT = #{outdt},
               DOCKNO = #{dockno},
               LAREA = #{larea},
               MAREA = #{marea},
               SAREA = #{sarea},
               LINKCARNO1 = #{linkcarno1},
               LINKCARNO2 = #{linkcarno2},
               LINKCARNO3 = #{linkcarno3},
               BTSCANNERGIVE = #{btscannergive},
               PDAPHONE2 = #{pdaphone2},
               PDAPHONE3 = #{pdaphone3},
               PDAPHONE4 = #{pdaphone4},
               ALLOW_LOGIN_YN = #{allowLoginYn},
               SMPGIVE = #{smpGive},
               PDAPHONE1 = #{pdaphone1},
               PHONE1 = #{phone1},
               DRIVER3 = #{driver3d},
               PHONE3 = #{phone3},
               DRIVER4 = #{driver4},
               PHONE4 = #{phone4},
               EDITDATE = SYSDATE,
               EDITWHO = #{gUserId},
               FROMDATE = #{fromdate},
               TODATE = #{todate},
               TODATE2 = #{todate2}
         WHERE CARNO = #{carNo}
    </update>

    <update id="updateDriver_hd" parameterType="map">
        /* [msDriverService.sqlx][msDriverService.updateDriver_hd][기사 정보 UPDATE][SLLEE][20141028] */
        UPDATE CM_DRIVER
           SET DRIVERNAME = #{drivername},
               EDITDATE = SYSDATE,
               EDITWHO = #{gUserId}
         WHERE DRIVERID = #{driverid}
    </update>

    <insert id="insertCmCarHttpDocAttach">
        <selectKey resultType="string" keyProperty="carId" order="BEFORE">
            SELECT SEQ_CM_CAR_HTTP_DOC_ATTACH.NEXTVAL AS CARID FROM DUAL
        </selectKey>
        INSERT /* [msCarDriverService.sqlx][msCarDriverService.insertCmCarHttpDocAttach] */
          INTO CM_CAR_HTTP_DOC_ATTACH
               ( SERIALKEY, DOC_ID, DOC_TYPE, DOC_NAME, FILE_NAME,
                 FILE_EXTENSION, FILE_LOCATION, FILE_SIZE_BYTES, TRANS_FILE_NAME, UPLOAD_HASH_ID,
                 UPLOAD_RES_DOC_ID, UPLOAD_FILE_NAME, UPLOAD_WORKPLACE_ID, UPLOAD_LOCATION, DOWNLOAD_COUNT,
                 FILE_CONTENT, FILE_TYPE, STATUS, ADDWHO, ADDDATE,
                 EDITWHO, EDITDATE
               )
        VALUES ( #{carId},
                 #{carId},
                 #{docType},
                 'CM_CAR',
                 #{fileName},
                 #{fileExtension},
                 #{fileLocation},
                 #{fileSizeBytes},
                 #{transFileName},
                 '',
                 #{uploadResDocId},
                 #{uploadFileName},
                 #{uploadWorkplaceId},
                 '',
                 '0',
                 '',
                 'HTTP',
                 'Y',
                 #{gUserId},
                 SYSDATE,
                 #{gUserId},
                 SYSDATE
               )
    </insert>

    <update id="updateCmCarHttpDocAttachDate">
        UPDATE CM_CAR /* [msCarDriverService.sqlx][msCarDriverService.updateCmCarHttpDocAttachDate] */
        <set>
            EDITWHO = #{gUserId},
            EDITDATE = SYSDATE
            <if test='gubun == "1"'>
                ,FROMDATE = #{carDt}
            </if>
            <if test='gubun == "2"'>
                ,TODATE = #{carDt}
            </if>
            <if test='gubun == "3"'>
                ,TODATE2 = #{carDt}
            </if>
        </set>
        WHERE CARNO = #{carNo}
    </update>
    
    <select id="getDriverDupCount" resultType="int">
        SELECT COUNT(*) 
        FROM  CM_CAR 
        WHERE CARNO = #{carNo}     
  	</select> 
  	
    <select id="getDriverList" resultType="MsCarDriverResDto">
        SELECT
             CM_DRIVER.DRIVERID 		AS CODE
            ,CM_DRIVER.DRIVERNAME   	AS NAME
			,DAMO.DEC(CM_DRIVER.PHONE1) AS PHONE1
        FROM CM_DRIVER
        WHERE 1 = 1
        <if test="driverId != null and driverId != ''"> 
           AND CM_DRIVER.DRIVERID = #{driverId} 
        </if>           
    </select>
        <insert id="insertTemp" >
        INSERT /* [msCarDriverService.sqlx][insertTemp][임시 Tabele 등록] */
        INTO SY_PROCESSTEMP_DM_D ( SERIALKEY, PROCESSTYPE,PROCESSCREATOR,SPID,ADDWHO,EDITWHO
        /**/
          ,DCCODE
        , SOKEY
        , INVOICETYPE
        , POKEY
        , LOT
        , LOTTABLE01
        , LOTTABLE02
        , LOTTABLE03
        , LOTTABLE04
        , LOTTABLE05
        , POTYPE
        , SOTYPE
        , PLANDOCTYPE
        , COURIER
        , SITE
        , PLANDOCDT
        , MERGEDOCDT
        , DELIVERYDATE
        , OTHER06
        , OTHER07
        , ORDERQTY
        , OPENQTY
        , PROCESSQTY
        , DOCLINE
        , IOTYPE
        , WORKQTY
        , INSPECTQTY
        , RETURNTYPE
        , RETURNWHO
        , REFERENCE07
        , REFERENCE01
        , REFERENCE02
        , REFERENCE03
        , REFERENCE04
        , REFERENCE05
        , REFERENCE06
        , OTHER01
        , OTHER02
        , OTHER08
        /**/
        )
        SELECT 
          SEQ_SY_PROCESSTEMP_DM_D.NEXTVAL   /* [2] 안전한 바깥쪽 위치에 시퀀스 배치 */
        , A.*
    FROM (
        <foreach collection="list" item="item" index="index" separator="UNION ALL">
            SELECT 
          #{item.processtype}, #{item.gUserId},#{item.gSpid},#{item.gUserId},#{item.gUserId}
         
        , #{item.dccode}
        , #{item.sokey}
        , #{item.invoicetype}
        , #{item.pokey}
        , #{item.lot}
        , #{item.lottable01}
        , #{item.lottable02}
        , #{item.lottable03}
        , #{item.lottable04}
        , #{item.lottable05}
        , #{item.potype}
        , #{item.sotype}
        , #{item.plandoctype}
        , #{item.courier}
        , #{item.site}
        , #{item.plandocdt}
        , #{item.mergedocdt}
        , #{item.deliverydate}
        , #{item.other06}
        , #{item.other07}
        , #{item.orderqty}
        , #{item.openqty}
        , #{item.processqty}
        , #{item.docline}
        , #{item.iotype}
        , #{item.workqty}
        , #{item.inspectqty}
        , #{item.returntype}
        , #{item.returnwho}
        , #{item.reference07}
        , #{item.reference01}
        , #{item.reference02}
        , #{item.reference03}
        , #{item.reference04}
        , #{item.reference05}
        , #{item.reference06}
        , #{item.other01}
        , #{item.other02}
        , #{item.other08}
            FROM DUAL
        </foreach>
        ) A
    </insert>
    <!-- POP 일괄등록 결과 조회(목록) -->
    <select id="getExcelUploadResult" resultType="MsCarDriverExcelResDto">
    	SELECT /* [msPopMngService.sqlx][msCarDriverService.getExcelUploadResult][][][] */
    	       SY_PROCESSTEMP_DM_D.PROCESSFLAG   AS PROCESS_YN
              ,SY_PROCESSTEMP_DM_D.PROCPOSS_MSG        AS PROCESS_MSG
        FROM  SY_PROCESSTEMP_DM_D
        WHERE SY_PROCESSTEMP_DM_D.PROCESSCREATOR = #{gUserId}
        AND   SY_PROCESSTEMP_DM_D.PROCESSTYPE    = #{processtype}
        AND   SY_PROCESSTEMP_DM_D.SPID           = #{gSpid}
        ORDER BY SY_PROCESSTEMP_DM_D.SERIALKEY
    </select>
    
</mapper>