<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="msCustService">

	<!-- 주출고센터 코드리스트 조회 -->
    <select id="getSelectDccodeList" resultType="MsCustHeaderResDto">
	    SELECT	/* [msCustNewService.sqlx][msCustNewService.getSelectDccodeList][주출고센터 코드리스트 조회][JeongHyeongCheol][20250609] */ 
  			   CM_DC.DCCODE BASECODE,	/* 센터코드 */
         	   '['||CM_DC.DCCODE||']'||CM_DC.DCNAME BASEDESCR	/* 센터명 */
        FROM   CM_DC
        WHERE DEL_YN ='N'
    </select>

    <!-- 거래처 기준정보 조회(목록) -->
	<select id="getMasterList" resultType="MsCustResDto">
	    SELECT	/* [msCustService.sqlx][msCustService.getCustList][거래처 기준정보 조회(목록)][JeongHyeongCheol][20250609] */ 
				MS_CUST.CUSTGROUP															AS CUSTGROUP    		 /* 거래처 그룹 */
				,MS_CUST.SERIALKEY    														AS SERIALKEY             /* 데이터번호*/
				,MS_CUST.STORERKEY    														AS STORERKEY             /* 고객사코드*/
				,MS_CUST.CUSTKEY      														AS CUSTKEY               /* 거래처코드*/
				,MS_CUST.CUSTTYPE     														AS CUSTTYPE              /* 거래처 유형*/
				,MS_CUST.CUSTGRADE    														AS CUSTGRADE             /* 거래처등급*/
				,MS_CUST.STORERCUSTKEY														AS STORERCUSTKEY         /* 고객사 거래처 코드(실제 고객사 시스템에 등록된 거래처 코드)*/
				,MS_CUST.PARENTCUSTKEY														AS PARENTCUSTKEY         /* 상위거래처*/
				,MS_CUST.SALEGROUP      													AS SALEGROUP        	 /* 영업그룹*/
				,MS_CUST.SALEDEPARTMENT 													AS SALEDEPARTMENT    	 /* 사업장 */
				,MS_CUST.BILLTOCUSTKEY                    									AS BILLTOCUSTKEY         /* 대금청구거래처 실배송이 아닌 대금 청구 거래처*/
				,MS_CUST.DESCRIPTION                      									AS DESCRIPTION           /* 거래처명*/
				,MS_CUST.PRIORITY                         									AS PRIORITY              /* 우선순위*/
				,MS_CUST.DISTRICTTYPE                     									AS DISTRICTTYPE          /* 권역구분*/
				,MS_CUST.DISTRICTCODE                     									AS DISTRICTCODE          /* 권역코드*/
				,MS_CUST.ROUTE                            									AS ROUTE                 /* 경유지*/
				,MS_CUST.COURIER                          									AS COURIER               /* 기본배송택배사*/
				,MS_CUST.INVOICETYPE                      									AS INVOICETYPE           /* 기본운송장유형*/
				,MS_CUST.DLV_DCCODE                         								AS DLV_DCCODE            /* 주출고처*/
				,CM_DC.DCNAME                             									AS DLV_DCNAME			 /* 주출고처명*/
				,MS_CUST.OWNER                              								AS OWNER                 /* 사업주명*/
				,MS_CUST.TIMEZONE                           								AS TIMEZONE              /* 타임존*/
				,MS_CUST.COUNTRY                            								AS COUNTRY               /* 국가코드*/
				,MS_CUST.STATE                              								AS STATE                 /* 주,도*/
				,MS_CUST.CITY                               								AS CITY                  /* 시,읍,면*/
				,MS_CUST.ZIPCODE                            								AS ZIPCODE               /* 우편번호*/
				,MS_CUST.ADDRESS1                           								AS ADDRESS1              /* 기본주소*/
				,MS_CUST.ADDRESS2                           								AS ADDRESS2              /* 상세주소*/
				,MS_CUST.ADDRESS3                           								AS ADDRESS3              /* 확장주소3*/
				,MS_CUST.ADDRESS4                           								AS ADDRESS4              /* 확장주소4*/
				,DAMO.DEC(MS_CUST.PHONE1)                   								AS PHONE1                /* 전화번호1*/
				,DAMO.DEC(MS_CUST.PHONE2 )                  								AS PHONE2                /* 전화번호2*/
				,MS_CUST.FAX                                								AS FAX                   /* 팩스번호*/
				,MS_CUST.EMAIL                              								AS EMAIL                 /* 일이메*/
				,MS_CUST.VATNO                              								AS VATNO                 /* 사업자 등록 등록번호*/
				,MS_CUST.VATOWNER                           								AS VATOWNER              /* 사업자 등록 사업주명*/
				,MS_CUST.VATTYPE                            								AS VATTYPE               /* 사업자 등록 업태*/
				,MS_CUST.VATNAME                            								AS VATNAME               /* 사업자 등록 명칭*/
				,MS_CUST.VATCATEGORY                        								AS VATCATEGORY           /* 사업자 등록 종목*/
				,MS_CUST.VATADDRESS1                        								AS VATADDRESS1           /* 사업자 등록 기본주소*/
				,MS_CUST.VATADDRESS2                        								AS VATADDRESS2           /* 사업자 등록 상세주소*/
				,MS_CUST.VATADDRESS3                        								AS VATADDRESS3           /* 사업자 등록 확장주소3*/
				,MS_CUST.VATADDRESS4                        								AS VATADDRESS4           /* 사업자 등록 확장주소4*/
				,MS_CUST.VATPHONE                           								AS VATPHONE              /* 사업자 등록 전화번호*/
				,MS_CUST.VATFAX                             								AS VATFAX                /* 사업자 등록 팩스번호*/
				,MS_CUST.EMPNAME1                           								AS EMPNAME1              /* 관리 사원명1*/
				,MS_CUST.EMPNAME2                           								AS EMPNAME2              /* 관리 사원명2*/
				,MS_CUST.EMPNAME3                           								AS EMPNAME3              /* 관리 사원명3*/
				,MS_CUST.EMPNAME4                           								AS EMPNAME4              /* 관리 사원명4*/
				,MS_CUST.EMPNAME5                           								AS EMPNAME5              /* 관리 사원명5*/
				,DAMO.DEC(MS_CUST.EMPPHONE1)                								AS EMPPHONE1             /* 관리 사원 전화번호1*/
				,DAMO.DEC(MS_CUST.EMPPHONE2)                								AS EMPPHONE2             /* 관리 사원 전화번호2*/
				,DAMO.DEC(MS_CUST.EMPPHONE3)                								AS EMPPHONE3             /* 관리 사원 전화번호3*/
				,DAMO.DEC(MS_CUST.EMPPHONE4)                								AS EMPPHONE4             /* 관리 사원 전화번호4*/
				,DAMO.DEC(MS_CUST.EMPPHONE5)                								AS EMPPHONE5             /* 관리 사원 전화번호5*/
				,MS_CUST.MA                                 								AS MA                    /* MA */
				,MS_CUST.MANAME                             								AS MANAME                /* MA명 */
				,MS_CUST.STARTDATE                          								AS STARTDATE             /* 거래 시작 일자*/
				,MS_CUST.ENDDATE                            								AS ENDDATE               /* 거래 종료 일자*/
				,MS_CUST.OPENTIME                           								AS OPENTIME              /* 업무 시작 시간(24hr  2300)*/
				,MS_CUST.CLOSINGTIME                        								AS CLOSINGTIME           /* 업무 종료 시간(24hr  2300)*/
				,MS_CUST.ENTRYCONDITION                     								AS ENTRYCONDITION        /* 진입조건*/
				,MS_CUST.LIMITCAR                           								AS LIMITCAR              /* 진입제한차량*/
				,MS_CUST.LOADBOXPERMIN                      								AS LOADBOXPERMIN         /* 상하역가능한분당박스수*/
				,MS_CUST.LOADTOOLTYPE                       								AS LOADTOOLTYPE          /* 상하역도구코드*/
				,MS_CUST.LATITUDE                           								AS LATITUDE              /* 위도*/
				,MS_CUST.LONGITUDE                          								AS LONGITUDE             /* 경도*/
				,MS_CUST.POTYPE                             								AS POTYPE                /* 구매유형*/
				,MS_CUST.SOTYPE                             								AS SOTYPE                /* 판매유형*/
				,MS_CUST.INSTRATEGY                         								AS INSTRATEGY            /* 입고전략*/
				,MS_CUST.OUTSTRATEGY                        								AS OUTSTRATEGY           /* 출고전략*/
				,MS_CUST.QCTYPE                             								AS QCTYPE                /* 검품유형*/
				,MS_CUST.INSPECTTYPE                 										AS INSPECTTYPE           /* 검수유형*/
				,MS_CUST.CUSTSTRATEGY1                      								AS CUSTSTRATEGY1         /* 거래처전략1*/
				,MS_CUST.CUSTSTRATEGY2                      								AS CUSTSTRATEGY2         /* 거래처전략2*/
				,MS_CUST.CUSTSTRATEGY3                      								AS CUSTSTRATEGY3         /* 거래처전략3*/
				,MS_CUST.CUSTSTRATEGY4                      								AS CUSTSTRATEGY4         /* 거래처전략4 마감유형*/
				,MS_CUST.CUSTSTRATEGY5														AS CUSTSTRATEGY5         /* 거래처전략5(납품서출력옵션)*/
				,MS_CUST.LABELSTRATEGY														AS LABELSTRATEGY    	 /* 2차점 라벨출력 옵션 */
				,MS_CUST.FLOATMASK                          								AS FLOATMASK             /* 기본표시FLOATMASK*/
				,MS_CUST.CURRENCY                           								AS CURRENCY              /* 통화코드*/
				,MS_CUST.OTHER01                            								AS OTHER01               /* 기타정보1*/
				,MS_CUST.OTHER02                            								AS OTHER02               /* 기타정보2*/
				,MS_CUST.OTHER03                            								AS OTHER03               /* 기타정보3*/
				,MS_CUST.OTHER04                            								AS OTHER04               /* 기타정보4 영업조직*/
				,MS_CUST.OTHER05                            								AS OTHER05               /* 기타정보5*/
				,MS_CUST.MEMO                               								AS MEMO                  /* 메모사항*/
				,MS_CUST.IFFILENAME                         								AS IFFILENAME            /* 인터페이스파일명*/
				,MS_CUST.STATUS                             								AS STATUS                /* 상태*/
				,MS_CUST.DEL_YN                             								AS DEL_YN                /* 삭제여부*/
				,MS_CUST.TRAFFICCOP                         								AS TRAFFICCOP            /* 데이터흐름제어*/
				,MS_CUST.ARCHIVECOP                         								AS ARCHIVECOP            /* 아카이브제어*/
				,MS_CUST.ADDDATE 															AS ADDDATE               /* 최초등록시간*/
				,MS_CUST.EDITDATE 															AS EDITDATE              /* 최종변경시간*/
				,MS_CUST.ADDWHO                             								AS ADDWHO                /* 최초등록자*/
				,MS_CUST.EDITWHO                            								AS EDITWHO               /* 최종변경자*/
				,USER1.USER_NM                             									AS REG_NM	             /* 등록자명 */
				,USER2.USER_NM                            									AS UPD_NM	             /* 수정자명 */
				
		FROM   MS_CUST
		JOIN MS_CUSTDLVINFO
			ON 	MS_CUST.STORERKEY 	= MS_CUSTDLVINFO.STORERKEY
			AND MS_CUST.CUSTKEY   	= MS_CUSTDLVINFO.CUSTKEY
			AND MS_CUST.CUSTTYPE   	= MS_CUSTDLVINFO.CUSTTYPE
	 <!-- DLV_DCCODE가 없는 케이스에도 조회 가능하도록 요청 LEFT JOIN으로 수정 -->
	 LEFT JOIN CM_DC 
			ON  CM_DC.DCCODE 	= MS_CUST.DLV_DCCODE
			AND CM_DC.DEL_YN 	= 'N'
		
		JOIN CM_USER_AUTHORITY_DCXSTORER  
			ON CM_USER_AUTHORITY_DCXSTORER.USERID	= #{gUserId}
			AND CM_USER_AUTHORITY_DCXSTORER.DCCODE	= #{gDccode}
			<if test='gStorerkey != null and gStorerkey != "" and gStorerkey != "%"'>
				AND CM_USER_AUTHORITY_DCXSTORER.STORERKEY = #{gStorerkey}
			</if>
			AND CM_USER_AUTHORITY_DCXSTORER.STORERKEY = MS_CUST.STORERKEY
			
	LEFT JOIN FRAMEONE_USER USER1 
			ON USER1.USER_ID = MS_CUST.ADDWHO	  /*등록자명*/
	LEFT JOIN FRAMEONE_USER USER2 
			ON USER2.USER_ID = MS_CUST.EDITWHO  /*수정자명*/
	
		WHERE  1=1
			AND MS_CUST.DEL_YN = 'N'
			AND MS_CUST.STORERKEY                LIKE 'FW00'
			AND MS_CUST.CUSTTYPE  = 'C'
			<!-- 주출고처  -->
			<if test='dlvDccodeMulti != null and dlvDccodeMulti != ""'>
				AND MS_CUST.DLV_DCCODE IN 
				<foreach collection="dlvDccodeMulti" item="code" open="(" close=")" separator="," >
		            #{code}
		        </foreach>
	    	</if>
			<!-- 고객코드  -->
			<if test='custkeyMulti != null and custkeyMulti != ""'>
		        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
	                <foreach collection="custkeyMulti" item="item">
	                    OR MS_CUST.CUSTKEY IN
	                    <foreach collection="item" item="code" open="(" close=")" separator=",">
	                        #{code}
	                    </foreach>
	                </foreach>
	            </trim>	
	    	</if>
    </select>
    
	<!-- 거래처 기준정보 조회(단건) -->
	<select id="getMaster" resultType="MsCustDetailResDto">
	    SELECT	/* [msCustService.sqlx][msCustService.getCustDetail][거래처 기준정보 조회(단건)][JeongHyeongCheol][20250609] */
				 MS_CUST.SERIALKEY               								AS SERIALKEY	    /* 데이터번호 */
				,MS_CUST.STORERKEY                       						AS STORERKEY    	/* 고객사코드 */
				,MS_CUST.CUSTKEY                         						AS CUSTKEY      	/* 거래처코드 */
				,MS_CUST.DESCRIPTION                     						AS DESCRIPTION  	/* 거래처명 */
				,MS_CUST.STORERCUSTKEY											AS STORERCUSTKEY	/* 고객사 시스템에 등록되어 있는 거래처 코드 */              
				,MS_CUST.BILLTOCUSTKEY											AS BILLTOCUSTKEY	/* 대금청구거래처 실배송이 아닌 대금 청구 거래처 */              
				,MS_CUST.CUSTTYPE                         						AS CUSTTYPE     	/* 거래처 유형 */
				,MS_CUST.CUSTGROUP                        						AS CUSTGROUP    	/* 거래처 그룹 */
				,MS_CUST.PRIORITY												AS PRIORITY			/* 우선순위 */
				,MS_CUST.DISTRICTTYPE											AS DISTRICTTYPE		/* 권역구분 */
				,MS_CUST.DISTRICTCODE 											AS DISTRICTCODE 	/* 권역*/
				,MS_CUST.ROUTE													AS ROUTE			/* 경유지 */
				,MS_CUST.COURIER												AS COURIER			/* 기본배송택배사 */  			  
				,MS_CUST.INVOICETYPE											AS INVOICETYPE		/* 기본운송장유형 */  			  
				,MS_CUST.DLV_DCCODE												AS DLV_DCCODE		/* 주출고처 */  			  
				,MS_CUST.OWNER													AS OWNER			/* 사업주명 */
				,DAMO.DEC(MS_CUST.PHONE1)                 						AS PHONE1       	/* 전화번호1 */
				,DAMO.DEC(MS_CUST.PHONE2)                 						AS PHONE2       	/* 전화번호2 */
				,MS_CUST.FAX													AS FAX				/* 팩스번호 */
				,MS_CUST.ZIPCODE												AS ZIPCODE			/* 우편번호 */
				,MS_CUST.COUNTRY												AS COUNTRY			/* 국가코드 */
				,MS_CUST.STATE													AS STATE			/* 주,도 */
				,MS_CUST.CITY													AS CITY				/* 시,읍,면 */
				,MS_CUST.ADDRESS1												AS ADDRESS1			/* 기본주소 */
				,MS_CUST.ADDRESS2												AS ADDRESS2			/* 상세주소 */
				,MS_CUST.VATNO													AS VATNO			/* 사업자 등록 등록번호 */
				,MS_CUST.VATOWNER												AS VATOWNER			/* 사업자 등록 사업주명 */
				,MS_CUST.VATTYPE												AS VATTYPE			/* 사업자 등록 업태 */
				,MS_CUST.VATCATEGORY											AS VATCATEGORY		/* 사업자 등록 종목 */
				,MS_CUST.VATADDRESS1											AS VATADDRESS1		/* 사업자 등록 기본주소 */
				,MS_CUST.VATADDRESS2											AS VATADDRESS2		/* 사업자 등록 상세주소 */
				,MS_CUST.VATPHONE												AS VATPHONE			/* 사업자 등록 전화번호 */
				,MS_CUST.VATFAX													AS VATFAX			/* 사업자 등록 팩스번호 */
				,MS_CUST.EMPNAME1                         						AS EMPNAME1     	/* 관리 사원명1 */
				,DAMO.DEC(MS_CUST.EMPPHONE1)                					AS EMPPHONE1 		/* 관리 사원 전화번호1 */
				,MS_CUST.EMPNAME2                         						AS EMPNAME2     	/* 관리 사원명2 */
				,DAMO.DEC(MS_CUST.EMPPHONE2)                					AS EMPPHONE2 		/* 관리 사원 전화번호2 */
				,MS_CUST.EMPNAME3                         						AS EMPNAME3     	/* 관리 사원명3 */
				,DAMO.DEC(MS_CUST.EMPPHONE3)               						AS EMPPHONE3 		/* 관리 사원 전화번호3 */
				,MS_CUST.MA                               						AS MA           	/* MA */
				,MS_CUST.MANAME                           						AS MANAME    		/* MA명 */
				,MS_CUST.STARTDATE												AS STARTDATE		/* 거래 시작 일자 */
				,MS_CUST.ENDDATE												AS ENDDATE			/* 거래 종료 일자 */
				,MS_CUST.OPENTIME												AS OPENTIME			/* 업무 시작 시간(24hr  2300) */
				,MS_CUST.CLOSINGTIME											AS CLOSINGTIME		/* 업무 종료 시간(24hr  2300) */
				,MS_CUST.LATITUDE												AS LATITUDE			/* 위도 */
				,MS_CUST.LONGITUDE												AS LONGITUDE		/* 경도 */
				,MS_CUST.LIMITCAR												AS LIMITCAR			/* 진입제한차량 */
				,MS_CUST.LOADBOXPERMIN											AS LOADBOXPERMIN	/* 상하역가능한분당박스수 */
				,MS_CUST.LOADTOOLTYPE											AS LOADTOOLTYPE		/* 상하역도구코드 */
				,MS_CUST.ENTRYCONDITION											AS ENTRYCONDITION	/* 진입조건 */
				,MS_CUST.MEMO													AS MEMO				/* 기타사항 */
				,MS_CUST.IFFILENAME												AS IFFILENAME		/* 인터페이스파일명 */
				,MS_CUST.STATUS													AS STATUS			/* 상태 */
				,MS_CUST.DEL_YN													AS DEL_YN			/* 삭제여부 */
				,MS_CUST.FLOATMASK												AS FLOATMASK		/* 기본표시FLOATMASK */
				,TO_CHAR(MS_CUST.ADDDATE, 'YYYY-MM-DD HH:MM:DD')  				AS ADDDATE			/* 최초등록시간 */
				,TO_CHAR(MS_CUST.EDITDATE, 'YYYY-MM-DD HH:MM:DD') 				AS EDITDATE			/* 최종변경시간 */
				,(SELECT REPLACE(USER1.USER_NM,'NOT FOUND',MS_CUST.ADDWHO) from DUAL)		AS ADDWHONAME	/* 최초등록자명 */
				,(SELECT REPLACE(USER2.USER_NM,'NOT FOUND',MS_CUST.EDITWHO) from DUAL)		AS EDITWHONAME	/* 최종등록자명 */
				,MS_CUST.ADDWHO													AS ADDWHO			/* 최초등록자 */
				,MS_CUST.EDITWHO												AS EDITWHO			/* 최종변경자 */
				,MS_CUST.CUSTSTRATEGY4   										AS CUSTSTRATEGY4	/* 마감유형 */
				,MS_CUST.CUSTSTRATEGY1				    	 					AS INEFFICIENT_YN 	/* 배송 비효율 거래처여부*/
				,MS_CUST.CUSTSTRATEGY2						 					AS DISTANT_YN	    /* 격오지여부*/
				,MS_CUST.SALEGROUP                        	 					AS SALEGROUP        /* 영업그룹 */
				,MS_CUST.SALEDEPARTMENT                   	 					AS SALEDEPARTMENT   /* 사업장 */
				,MS_CUST.OTHER04                          	 					AS OTHER04          /* 영업조직  2019-05-17 이름변경*/
				,MS_CUST.CUSTSTRATEGY5                    	 					AS CUSTSTRATEGY5    /* 거래처전략5(납품서출력옵션)*/
				,MS_CUST.LABELSTRATEGY	                	 					AS LABELSTRATEGY    /* 2차점 라벨출력 옵션 */
				,MS_CUST.INVOICETYPE_BT	                	 					AS INVOICETYPE_BT   /* 납품서 하단유형 */
				,MS_CUSTDLVINFO.REQDLVTIME1_FROM 								AS REQDLVTIME1_FROM /* OTD(배송요구시간)1*/
				,MS_CUSTDLVINFO.REQDLVTIME1_TO 			     					AS REQDLVTIME1_TO   /* OTD(배송요구시간)2*/
				,MS_CUST.ADDRESS3              				 					AS ADDRESS3    	 	/* 도로명주소 */
				,MS_CUST.ADDRESS4             				 					AS ADDRESS4         /* 도로명주소2 */
				,MS_CUSTDLVINFO.INSPECTTYPE                 					AS INSPECTTYPE      /* 검수유형*/
        FROM   MS_CUST
	    JOIN MS_CUSTDLVINFO
	      ON MS_CUST.STORERKEY = MS_CUSTDLVINFO.STORERKEY
	     AND MS_CUST.CUSTKEY   = MS_CUSTDLVINFO.CUSTKEY
	     AND MS_CUST.CUSTTYPE   = MS_CUSTDLVINFO.CUSTTYPE
	    LEFT JOIN FRAMEONE_USER USER1  
	    	ON USER1.USER_ID = MS_CUST.ADDWHO         
	    LEFT JOIN FRAMEONE_USER USER2  
	    	ON USER2.USER_ID = MS_CUST.EDITWHO
        WHERE 1=1 <!-- 단건 조회시에는 serialKey가 아닌 PK를 건다 -->

		AND    MS_CUST.STORERKEY    = 'FW00'
		AND    MS_CUST.CUSTKEY      LIKE #{custkey}
		AND    MS_CUST.CUSTTYPE     LIKE #{custtype}
	</select>
    
    <!-- 거래처 기준정보 UPDATE -->
    <select id="updateMaster" statementType="CALLABLE" resultType="MsCustEntity">
        <![CDATA[
        {
        	CALL  /* [msCustService.sqlx][msCustService.update][거래처 기준정보 UPDATE][JeongHyeongCheol][20250609] */
        	DECLARE
                V_AFTER     MS_CUST%rowtype;
                O_SUCCESS   NUMBER         :=  1;      /* 성공여부(1이면 성공) */
                O_ERRCODE   NUMBER         :=  0;      /* 오류 코드 */
                O_ERRMSG    VARCHAR2(4000) := '';      /* 오류 메세지 */
            BEGIN
                SELECT  *
                INTO    V_AFTER
                FROM    MS_CUST
                WHERE   SERIALKEY = #{serialkey};
    
    			V_AFTER.CUSTSTRATEGY5    := #{custstrategy5};   /* 거래처전략5 */      
                V_AFTER.LABELSTRATEGY    := #{labelstrategy};   /* 2차점 라벨출력 옵션 */
                V_AFTER.EDITDATE         := SYSDATE;            /* 최종변경시간 */
                V_AFTER.EDITWHO          := #{gUserId};          /* 최종변경자 */

                TRMS_CUST.TR_UPDATE(
                         V_AFTER
                     ,   O_SUCCESS
                     ,   O_ERRCODE
                     ,   O_ERRMSG
                );
                
				#{success, mode=OUT, jdbcType=INTEGER, javaType=int}    :=  O_SUCCESS;
				#{err, mode=OUT, jdbcType=INTEGER, javaType=int}        :=  O_ERRCODE;
				#{errmsg, mode=OUT, jdbcType=VARCHAR, javaType=String}  :=  O_ERRMSG;
                
        	END
        }
        ]]>        
    </select>
</mapper>