<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="msDirectDlvGroupService">
	<!-- 직송그룹지정 정보 조회(목록) -->
    <select id="getMasterList" resultType="MsDirectDlvGroupResDto">
    	SELECT /* [msDirectDlvGroupService.sqlx][msDirectDlvGroupService.getMasterList][직송그룹지정 조회(목록)] */ 
    	      '0' AS CHECKYN
    	      ,MS_DIRECTDLVGROUP.SERIALKEY                         AS SERIALKEY
		      ,MS_DIRECTDLVGROUP.DIRECTDLVGROUP                    AS DIRECTDLVGROUP
		      ,MS_DIRECTDLVGROUP.DCCODE                            AS DCCODE
		      ,CM_DC.DCNAME                                        AS DCNAME
		      ,MS_DIRECTDLVGROUP.STORERKEY                         AS STORERKEY
		      ,MS_DIRECTDLVGROUP.ORGANIZE                          AS ORGANIZE
		      ,DCXORG.DESCRIPTION                                  AS ORGANIZENAME 
		      ,MS_DIRECTDLVGROUP.CUSTTYPE                          AS CUSTTYPE <!--'D'로 고정되어 들어감 -->
		      ,MS_DIRECTDLVGROUP.CUSTKEY                           AS CUSTKEY
		      ,CM_DCXORGANIZE.DESCRIPTION                          AS CUSTNAME 
		      ,MS_DIRECTDLVGROUP.ORDERQTY                          AS ORDERQTY
		      ,MS_DIRECTDLVGROUP.UOM                               AS UOM
		      ,MS_DIRECTDLVGROUP.MEMO                              AS MEMO
		      ,'1'                                                 AS SAVED
		      ,MS_DIRECTDLVGROUP.ADDDATE                           AS ADDDATE
		      ,MS_DIRECTDLVGROUP.EDITDATE                          AS EDITDATE
		      ,MS_DIRECTDLVGROUP.ADDWHO                            AS ADDWHO
		      ,MS_DIRECTDLVGROUP.EDITWHO                           AS EDITWHO
		      ,USER1.USER_NM                            		   AS REG_NM	/*등록자명*/
		      ,USER2.USER_NM                           			   AS UPD_NM	/*수정자명*/
		  FROM MS_DIRECTDLVGROUP
		  JOIN CM_DC
		    ON MS_DIRECTDLVGROUP.DCCODE       = CM_DC.DCCODE
		  JOIN CM_DCXORGANIZE DCXORG
		    ON MS_DIRECTDLVGROUP.ORGANIZE     = DCXORG.ORGANIZE
		   AND MS_DIRECTDLVGROUP.DCCODE       = DCXORG.DCCODE
		   AND MS_DIRECTDLVGROUP.DEL_YN       = 'N'
		  JOIN CM_DCXORGANIZE
		    ON MS_DIRECTDLVGROUP.CUSTKEY     = CM_DCXORGANIZE.ORGANIZE
		   AND CM_DCXORGANIZE.DCCODE = '1000'
		   AND MS_DIRECTDLVGROUP.DEL_YN       = 'N'
	 LEFT JOIN FRAMEONE_USER USER1 ON USER1.USER_ID = MS_DIRECTDLVGROUP.ADDWHO  
	 LEFT JOIN FRAMEONE_USER USER2 ON USER2.USER_ID = MS_DIRECTDLVGROUP.EDITWHO  
		 WHERE 1=1
		   AND MS_DIRECTDLVGROUP.STORERKEY = #{gStorerkey}
        <if test='directdlvgroup != null and directdlvgroup != ""'>
        	AND    MS_DIRECTDLVGROUP.DIRECTDLVGROUP	IN (SELECT TRIM(REGEXP_SUBSTR(VAL,'[^,]+',1,LEVEL)) AS VAL
						FROM (SELECT #{directdlvgroup} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
        </if>
        <if test='dccode != null and dccode != ""'>
			AND MS_DIRECTDLVGROUP.DCCODE IN (SELECT TRIM(REGEXP_SUBSTR(VAL,'[^,]+',1,LEVEL)) AS VAL
						FROM (SELECT #{dccode} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
		</if>
    </select>
    
    
    <!-- 직송그룹지정 정보 UPDATE   -->
    <select id="updateMasterList" statementType="CALLABLE" resultType="MsDirectDlvGroupEntity">
    	 <![CDATA[
        {
        	CALL  /* [msDirectDlvGroupService.sqlx][msDirectDlvGroupService.updateMasterList][직송그룹지정 정보 UPDATE][JeongHyeongCheol][20250703] */
        	DECLARE
                V_AFTER     MS_DIRECTDLVGROUP%rowtype;
                O_SUCCESS   NUMBER         :=  1;      /* 성공여부(1이면 성공) */
                O_ERRCODE   NUMBER         :=  0;      /* 오류 코드 */
                O_ERRMSG    VARCHAR2(4000) := '';      /* 오류 메세지 */
            BEGIN
                SELECT  *
                INTO    V_AFTER
                FROM    MS_DIRECTDLVGROUP
                WHERE   DIRECTDLVGROUP = #{directdlvgroup}
                AND		DCCODE 		   = #{dccode}
                AND		STORERKEY	   = #{storerkey}
                AND		ORGANIZE	   = #{organize}
                AND		CUSTTYPE	   = #{custtype}
                AND		CUSTKEY		   = #{custkey};
    
    			V_AFTER.ORDERQTY    	 := #{orderqty};   /*  */
    			V_AFTER.UOM    	 		 := #{uom};   /*  */
                V_AFTER.MEMO    		 := #{memo};   /*  */      
                V_AFTER.EDITDATE         := SYSDATE;            /* 최종변경시간 */
                V_AFTER.EDITWHO          := #{gUserId};          /* 최종변경자 */

                TRMS_DIRECTDLVGROUP.TR_UPDATE(
                         V_AFTER
                     ,   O_SUCCESS
                     ,   O_ERRCODE
                     ,   O_ERRMSG
                );
                
                #{success, mode=OUT, jdbcType=INTEGER, javaType=int}    :=  O_SUCCESS;
				#{err, mode=OUT, jdbcType=INTEGER, javaType=int}        :=  O_ERRCODE;
				#{errmsg, mode=OUT, jdbcType=VARCHAR, javaType=String}  :=  O_ERRMSG;
				
        	END
        }
        ]]>          
    </select>
    
    <!-- 직송그룹지정 정보 INSERT -->
    <insert id="insertMasterList">
		INSERT	/* [msDirectDlvGroupService.sqlx][msDirectDlvGroupService.insertMasterList][직송그룹지정 정보 INSERT][JeongHyeongCheol][20250703] */ 
			INTO MS_DIRECTDLVGROUP
	  			(SERIALKEY 
		        ,DIRECTDLVGROUP
			    ,DCCODE
			    ,STORERKEY 
			    ,ORGANIZE
			    ,CUSTTYPE
			    ,CUSTKEY
			    ,ORDERQTY
			    ,UOM	
			    ,MEMO			    																 
				,ADDWHO 
				,EDITWHO)
			VALUES
				(SEQ_MS_DIRECTDLVGROUP.NEXTVAL
				,#{directdlvgroup}
				,#{dccode}
				,#{storerkey}
				,#{organize}
				,#{custtype}
				,#{custkey}
				,#{orderqty}
				,#{uom}
				,#{memo}
				,#{gUserId}
				,#{gUserId})
    </insert>

</mapper>