<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper
  PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
         "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="msOutGroupSettingService">
	<!-- 실비차 배차 조건 설정 목록 조회 -->
	<select id="getMasterList" parameterType="MsOutGroupSettingReqDto" resultType="cjfw.wms.ms.dto.MsOutGroupSettingResDto$OutGroupSetting">
        SELECT /* [msOutGroupSettingService.sqlx][msOutGroupSettingService.getMasterList][실비차 배차 조건 설정 목록조회][20250917] */
             MS_OUT_GROUP.DCCODE         AS DCCODE
            ,MS_OUT_GROUP.OUT_GROUP_CD   AS OUT_GROUP_CD
            ,CM_CODE.BASEDESCR           AS OUT_GROUP_NM
            ,MS_OUT_GROUP.MAX_WEIGHT     AS MAX_WEIGHT
            ,MS_OUT_GROUP.MAX_CBM        AS MAX_CBM
            ,MS_OUT_GROUP.MAX_LOAD_QTY   AS MAX_LOAD_QTY
        FROM MS_OUT_GROUP
        LEFT OUTER JOIN CM_CODE
              ON CM_CODE.CODELIST = 'CARGROUP'
             AND CM_CODE.BASECODE = MS_OUT_GROUP.OUT_GROUP_CD
             AND CM_CODE.STORERKEY = 'FW00'
        WHERE 1 = 1
          AND MS_OUT_GROUP.USE_YN = 'Y'
          AND MS_OUT_GROUP.DCCODE = #{dccode}
        ORDER BY TO_NUMBER(MS_OUT_GROUP.OUT_GROUP_CD) ASC
	</select>
  
	<!-- 실비차 배차 조건 설정 목록 갱신 -->
	<update id="updateMasterList" parameterType="MsOutGroupSettingReqDto">
		UPDATE MS_OUT_GROUP /* [msOutGroupSettingService.sqlx][msOutGroupSettingService.updateMasterList][실비차 배차 조건 설정 목록 갱신][20250917] */
		SET MAX_WEIGHT     = #{maxWeight}
		   ,MAX_CBM        = #{maxCbm}
		   ,MAX_LOAD_QTY   = #{maxLoadQty}
		WHERE DCCODE       = #{dccode}
		AND   OUT_GROUP_CD = #{outGroupCd}
	</update>
</mapper>
