<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<!--
 * Copyright 2025. CJ OliveNetworks Co. all rights reserved.
 *
 * @author      : KimDongHan (liop0123@cj.net)
 * @date        : 2025.09.18
 * @description : 재고 > 공용기 관리 > P-BOX 관리/사용 현황 SQL
 * @issues      :
-->
<mapper namespace="msPboxService">

    <select id="getMasterT1List" resultType="cjfw.wms.ms.dto.MsPboxResT1Dto">
		SELECT /* [MsPboxService.sqlx][MsPboxService.getMasterT1List][재고 > 공용기 관리 > P-BOX 관리/사용 현황 P-BOX등록_탭 조회][KimDongHan][2025-09-18] */ 
		       MS_PBOX.DCCODE                                                 AS DCCODE              /* 01. 물류센터 */
		     , FN_GETDCNAME(MS_PBOX.DCCODE)                                   AS DCNAME              /* 01. 물류센터 */
		     , MS_PBOX.PBOX_NO                                                AS PBOX_NO             /* 02. P_BOX 번호*/
		     , CM_DRIVER.DRIVERNAME                                           AS DRIVERNAME          /* 03. 운전자명 */
		     , MS_PBOX.CARNO                                                  AS CARNO               /* 03. 차량번호 */
		     , MS_PBOX.CAR_ALLOCATE_DT                                        AS CAR_ALLOCATE_DT     /* 04. 차량할당일 */
		     , MS_PBOX.PRINT_CNT                                              AS PRINT_CNT           /* 05. 출력 횟수*/
		     , MS_PBOX.USE_YN                                                 AS USE_YN              /* 06. 사용유무 */
		     , MS_PBOX.RMK                                                    AS RMK                 /* 07. 비고 */
		     , USER1.USER_NM                                                  AS ADDWHO              /* 08. 등록자 */
		     , TO_CHAR(MS_PBOX.ADDDATE,'YYYY-MM-DD HH24:MI:SS')               AS ADDDATE	         /* 09. 등록일시 */
		     , USER2.USER_NM                                                  AS EDITWHO             /* 10. 수정자 */
		     , TO_CHAR(MS_PBOX.EDITDATE,'YYYY-MM-DD HH24:MI:SS')              AS EDITDATE            /* 11. 수정일시 */
		     , USER1.USER_ID                                                  AS ADD_ID              /* 등록자ID */
		     , USER2.USER_ID                                                  AS UPD_ID              /* 수정자ID */		     
		  FROM MS_PBOX
          LEFT OUTER JOIN CM_CAR ON CM_CAR.CARNO               = MS_PBOX.CARNO
          LEFT OUTER JOIN CM_DRIVER ON CM_DRIVER.DRIVERID      = CM_CAR.DRIVER1
          LEFT OUTER JOIN FRAMEONE_USER USER1 ON USER1.USER_ID = MS_PBOX.ADDWHO   /*등록자명*/
          LEFT OUTER JOIN FRAMEONE_USER USER2 ON USER2.USER_ID = MS_PBOX.EDITWHO  /*수정자명*/
		 WHERE 1=1
		<if test="dccode != null and dccode != ''">
		   AND MS_PBOX.DCCODE              = #{dccode} 
		</if>
		<if test="carAllocateDtFrom != null and carAllocateDtFrom != ''">    		
		  AND MS_PBOX.CAR_ALLOCATE_DT <![CDATA[>=]]> #{carAllocateDtFrom}   
		</if>
		<if test="carAllocateDtTo != null and carAllocateDtTo != ''">      		
		  AND MS_PBOX.CAR_ALLOCATE_DT <![CDATA[<=]]> #{carAllocateDtTo}     
		</if>	
		<if test="useYn != null and useYn != ''">
          AND MS_PBOX.USE_YN = #{useYn}
		</if>
		<!-- 
		<if test="carno != null and carno != ''">
		   AND MS_PBOX.CARNO              = #{carno} 
		</if>
		-->
		
	    <!-- START.차량번호 -->
	    <if test="carnoMulti != null and carnoMulti != '' ">
			<trim prefix="AND (" suffix=")" prefixOverrides="OR">
				<foreach collection="carnoMulti" item="item">
					OR MS_PBOX.CARNO IN
					<foreach collection="item" item="code" open="(" close=")" separator=",">
						#{code} 	 
		      		</foreach>
		    	</foreach>
		  	</trim>			                                    
	    </if>
	    <!-- END.차량번호 -->	
	    		
		<if test="reprint == 'Y'.toString()">
		   AND NVL(MS_PBOX.PRINT_CNT,0) <![CDATA[>]]> 0
		</if>
		<if test="reprint == 'N'.toString()">
		   AND NVL(MS_PBOX.PRINT_CNT,0) = 0
		</if>
		<if test="allocatedYn == 'Y'.toString()">
		   AND MS_PBOX.CAR_ALLOCATE_DT IS NOT NULL
		</if>
		<if test="allocatedYn == 'N'.toString()">
		   AND MS_PBOX.CAR_ALLOCATE_DT IS NULL
		</if>
		 ORDER BY MS_PBOX.DCCODE
		        , MS_PBOX.PBOX_NO
    </select>
    
    <select id="getMasterT2List" resultType="cjfw.wms.ms.dto.MsPboxResT2Dto">
		SELECT /* [MsPboxService.sqlx][MsPboxService.getMasterT2List][재고 > 공용기 관리 > P-BOX 관리/사용 현황 사용현황_탭 조회][KimDongHan][2025-09-22] */ 
		       TM_LOADINSPECT_PBOX_MAP.DCCODE                         AS DCCODE              /* 01. 물류센터 */
		     , FN_GETDCNAME(TM_LOADINSPECT_PBOX_MAP.DCCODE)           AS DCNAME              /* 01. 물류센터 */
		     , TM_LOADINSPECT_PBOX_MAP.DELIVERYDT                     AS DELIVERYDT          /* 02. 출고일자 */
		     , TM_LOADINSPECT_PBOX_MAP.PBOX_NO                        AS PBOX_NO             /* 02. P_BOX 번호*/
		     , CM_DRIVER.DRIVERNAME                                   AS DRIVERNAME          /* 03. 기사명 */
			 , TM_LOADINSPECT_PBOX_MAP.CARNO                          AS CARNO               /* 03. 차량번호 */
			 , DM_DOCUMENT_H.TO_CUSTKEY                               AS TO_CUSTKEY          /* 04. 관리처코드 */
			 , DM_DOCUMENT_H.TO_CUSTNAME                              AS TO_CUSTNAME         /* 05. 관리처명 */
			 , DM_DOCUMENT_D.SKU                                      AS SKU                 /* 06. 상품코드 */
			 , MS_SKU.DESCRIPTION                                     AS SKUNAME             /* 07. 상품명칭 */
			 , MS_SKU.BASEUOM                                         AS BASEUOM             /* 08. 판매단위 */
			 , DM_DOCUMENT_D.ORDERQTY                                 AS ORDERQTY            /* 09. 주문수량 */
			 , TM_LOADINSPECT_PBOX_MAP.INSPECTQTY                     AS INSPECTQTY          /* 10. 출고수량 */
		  FROM TM_LOADINSPECT_PBOX_MAP  
          LEFT OUTER JOIN CM_CAR ON CM_CAR.CARNO               = TM_LOADINSPECT_PBOX_MAP.CARNO
          LEFT OUTER JOIN CM_DRIVER ON CM_DRIVER.DRIVERID      = CM_CAR.DRIVER1
		  JOIN DM_DOCUMENT_D 
		    ON DM_DOCUMENT_D.DCCODE       = TM_LOADINSPECT_PBOX_MAP.DCCODE
		   AND DM_DOCUMENT_D.DOCNO        = TM_LOADINSPECT_PBOX_MAP.DOCNO
		   AND DM_DOCUMENT_D.DOCLINE      = TM_LOADINSPECT_PBOX_MAP.DOCLINE 
		   AND DM_DOCUMENT_D.DELIVERYDATE = TM_LOADINSPECT_PBOX_MAP.DELIVERYDT
		  JOIN DM_DOCUMENT_H    
		    ON DM_DOCUMENT_H.DCCODE       = DM_DOCUMENT_D.DCCODE
		   AND DM_DOCUMENT_H.DOCTYPE      = DM_DOCUMENT_D.DOCTYPE
		   AND DM_DOCUMENT_H.DELIVERYDATE = DM_DOCUMENT_D.DELIVERYDATE 
		   AND DM_DOCUMENT_H.DOCNO        = DM_DOCUMENT_D.DOCNO  
		  JOIN MS_SKU
		    ON MS_SKU.SKU                 = DM_DOCUMENT_D.SKU
		   AND MS_SKU.STORERKEY           = #{gStorerkey}
		 WHERE 1=1   
		<if test="dccode != null and dccode != ''">
		   AND TM_LOADINSPECT_PBOX_MAP.DCCODE                 = #{dccode} 
		</if>
		<if test="deliverydtFrom != null and deliverydtFrom != ''">    		
		  AND TM_LOADINSPECT_PBOX_MAP.DELIVERYDT <![CDATA[>=]]> #{deliverydtFrom}   
		</if>
		<if test="deliverydtTo != null and deliverydtTo != ''">      		
		  AND TM_LOADINSPECT_PBOX_MAP.DELIVERYDT <![CDATA[<=]]> #{deliverydtTo}     
		</if>	 
		<if test="carno != null and carno != ''">
		   AND TM_LOADINSPECT_PBOX_MAP.CARNO                  = #{carno} 
		</if>		 
        ORDER BY TM_LOADINSPECT_PBOX_MAP.DCCODE
               , TM_LOADINSPECT_PBOX_MAP.DELIVERYDT
               , TM_LOADINSPECT_PBOX_MAP.PBOX_NO
    </select>    
    
    <select id="getCheckCarNo" resultType="cjfw.wms.ms.dto.MsPboxResT1Dto">
		SELECT /* [MsPboxService.sqlx][MsPboxService.getCheckCarNo][재고 > 공용기 관리 > P-BOX 관리/사용 현황 사용현황_탭 유효한 차량번호 조회][KimDongHan][2025-09-22] */
		       COUNT(*) AS CNT
		  FROM CM_CAR
		 WHERE 1=1
           AND CARNO = #{carno}  

	</select>    
    
    <insert id="insertMaster">
		INSERT /* [MsPboxService.sqlx][MsPboxService.insertMaster][재고 > 공용기 관리 > P-BOX 관리/사용 현황 P-BOX등록_탭 저장(신규)][KimDongHan][2025-09-18] */ 
		  INTO MS_PBOX
		     ( PBOX_NO                                                              /* 01. P_BOX 번호*/
		     , DCCODE                                                               /* 02. 물류센터 */
			<if test="carno != null and carno != ''">	 
			 , CARNO                                                                /* 03. 차량번호 */
			</if>
			<if test="carAllocateDt != null and carAllocateDt != ''">	 
			 , CAR_ALLOCATE_DT                                                      /* 04. 차량할당일 */
			</if>
			<if test="useYn != null and useYn != ''">	 
			 , USE_YN                                                               /* 05. 사용유무 */
			</if>
			<if test="rmk != null and rmk != ''">	 
			 , RMK                                                                  /* 06. 비고 */
			</if>
			 , PRINT_CNT                                                            /* 07. 출력 횟수*/
			 , ADDWHO                                                               /* 08. 등록자 */  
			 , ADDDATE                                                              /* 09. 등록일시 */ 
			 , EDITWHO                                                              /* 10. 수정자 */  
			 , EDITDATE                                                             /* 11. 수정일시 */ 
			 ) VALUES (
		       (SELECT 'PBOX_'||#{dccode}||'_'|| LPAD(NVL(MAX(TO_NUMBER(SUBSTR(PBOX_NO, 11, 11))), 0) + 1, 11, '0')     /* 01. P_BOX 번호 */
		          FROM MS_PBOX                                                                                            
		         WHERE DCCODE=#{dccode})                                                                                /* 02. 물류센터 */                
		     , #{dccode}                                                                                                  
			<if test="carno != null and carno != ''">	 	                                                                            
			 , #{carno}                                                                                                 /* 03. 차량번호 */                
			</if>                                                                                                        
			<if test="carAllocateDt != null and carAllocateDt != ''">	 	 	                                                        
			 , #{carAllocateDt}                                                                                         /* 04. 차량할당일 */                
			</if>	                                                                                                     
			<if test="useYn != null and useYn != ''">	 	 		                                                                    
			 , #{useYn}                                                                                                 /* 05. 사용유무 */                 
			</if>	 	                                                                                                /* 06. 비고 */    
			<if test="rmk != null and rmk != ''">	                                                                                    
			 , #{rmk}                                                                                                   /* 06. 비고 */  
			</if>                                                                                                        
			 , 0                                                                                                        /* 07. 출력 횟수*/   
			 , #{gUserId}                                                                                               /* 08. 등록자 */ 
			 , SYSDATE                                                                                                  /* 09. 등록일시 */   
			 , #{gUserId}                                                                                               /* 10. 수정자 */
			 , SYSDATE                                                                                                  /* 11. 수정일시 */
			 )	 
	</insert>     
    
    <delete id="deleteMaster_backup">
		DELETE /* [MsPboxService.sqlx][MsPboxService.deleteMaster][재고 > 공용기 관리 > P-BOX 관리/사용 현황 저장(삭제)][KimDongHan][2025-09-18] */ 
		  FROM MS_PBOX
		 WHERE 1=1
		   AND PBOX_NO = #{pboxNo}
	</delete>
	
    <delete id="deleteMaster">
		UPDATE /* [MsPboxService.sqlx][MsPboxService.deleteMaster][재고 > 공용기 관리 > P-BOX 관리/사용 현황 P-BOX등록_탭 저장(삭제)][KimDongHan][2025-09-18] */ 
		       MS_PBOX
		   SET EDITWHO         = #{gUserId}
			 , EDITDATE        = SYSDATE
		     , USE_YN          = 'N'
		     , CARNO           = ''
		     , CAR_ALLOCATE_DT = ''
		     , RMK             = ''
	     WHERE 1=1 
		   AND PBOX_NO         = #{pboxNo}
	</delete>
	
    <update id="updateMaster">
		UPDATE /* [MsPboxService.sqlx][MsPboxService.updateMaster][재고 > 공용기 관리 > P-BOX 관리/사용 현황 P-BOX등록_탭 저장(수정)][KimDongHan][2025-09-18] */ 
		       MS_PBOX
		   SET EDITWHO         = #{gUserId}
			 , EDITDATE        = SYSDATE
			 , CARNO           = #{carno}
			 , CAR_ALLOCATE_DT = #{carAllocateDt}
			 , USE_YN          = #{useYn}
			 , RMK             = #{rmk}
		 WHERE 1=1
		   AND PBOX_NO = #{pboxNo}
	</update>
	
    <update id="updateMaster_backup">
		UPDATE /* [MsPboxService.sqlx][MsPboxService.updateMaster][재고 > 공용기 관리 > P-BOX 관리/사용 현황 저장(수정)][KimDongHan][2025-09-18] */ 
		       MS_PBOX
		   SET EDITWHO         = #{gUserId}
			 , EDITDATE        = SYSDATE
			<if test="carno != null and carno != ''">	 
			 , CARNO           = #{carno}
			</if>	 
			<if test="carAllocateDt != null and carAllocateDt != ''">	 
			 , CAR_ALLOCATE_DT = #{carAllocateDt}
			</if>	 
			<if test="useYn != null and useYn != ''">	 
			 , USE_YN          = #{useYn}
			</if>	 	
			<!--
			<if test="rmk != null and rmk != ''">	 
			 , RMK             = #{rmk}
			</if>
			-->	 		
			 , RMK             = #{rmk}
		 WHERE 1=1
		   AND PBOX_NO = #{pboxNo}
	</update>
	     
    <update id="updatePrintMaster">
		UPDATE /* [MsPboxService.sqlx][MsPboxService.updatePrintMaster][재고 > 공용기 관리 > P-BOX 관리/사용 현황 P-BOX등록_탭 인쇄][KimDongHan][2025-09-18] */ 
		       MS_PBOX
		   SET EDITWHO         = #{gUserId}
			 , EDITDATE        = SYSDATE
			 , PRINT_CNT       = NVL(PRINT_CNT,0) + 1
		 WHERE 1=1
		   AND PBOX_NO         = #{pboxNo}
	</update>     
	
	
    
</mapper>