<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="msPurchaseDCNewService">
    
    <!-- 수발주마스터 조회(목록) -->
	<select id="getMasterList" resultType="MsPurchaseDCNewResDto">
		WITH PURCHASE_TB AS(	/* [msPurchaseDCNewService.sqlx][msPurchaseDCNewService.getMasterList][수발주마스터 조회(목록)][JeongHyeongCheol][20251014] */ 
		        SELECT  MS_PURCHASEDC_DAILY.STORERKEY                 
         			   
         			   ,MS_PURCHASEDC_DAILY.YYYYMMDD                  
         			   ,MS_PURCHASEDC_DAILY.DCCODE                  
         			   ,MS_PURCHASEDC_DAILY.SKU                  
         			   ,MS_PURCHASEDC_DAILY.PURCHASETYPE                  
         			   ,MS_PURCHASEDC_DAILY.BUYERKEY                  
         			   ,MS_PURCHASEDC_DAILY.ROUTE                  
         			   ,MS_PURCHASEDC_DAILY.CUSTKEY                  
         			   ,MS_PURCHASEDC_DAILY.CUSTTYPE                  
         			   ,MS_PURCHASEDC_DAILY.MOQ_VENDER                  
         			   ,MS_PURCHASEDC_DAILY.MOQ_SKU                  
         			   ,MS_PURCHASEDC_DAILY.LEADTIME                  
         			   ,MS_PURCHASEDC_DAILY.PURCHASE_IN                  
         			   ,MS_PURCHASEDC_DAILY.PURCHASE_OUT                  
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2600' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2600
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2620' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2620
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2630' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2630
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2650' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2650
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2660' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2660
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2230' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2230
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2250' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2250
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2260' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2260
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2270' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2270
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2041' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2041
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '1000' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_1000
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2900' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2900
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2600' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2600
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2620' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2620
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2630' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2630
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2650' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2650
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2660' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2660
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2230' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2230
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2250' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2250
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2260' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2260
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2270' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2270
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2041' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2041
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '1000' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_1000
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2900' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2900
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2600' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2600 
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2620' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2620
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2630' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2630
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2650' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2650
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2660' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2660
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2230' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2230
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2250' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2250
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2260' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2260
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2270' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2270
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2041' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2041
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '1000' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_1000
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2900' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2900
		        FROM    MS_PURCHASEDC_DAILY
		        WHERE	1=1
		        AND	    MS_PURCHASEDC_DAILY.YYYYMMDD  = #{yyyymmdd}
		        AND 	MS_PURCHASEDC_DAILY.STORERKEY = 'FW00'
		        <!-- 상품 다중선택 -->
				<if test='skuMulti != null and skuMulti != ""'>
			        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
		                <foreach collection="skuMulti" item="item">
		                    OR MS_PURCHASEDC_DAILY.SKU IN
		                    <foreach collection="item" item="code" open="(" close=")" separator=",">
		                        #{code}
		                    </foreach>
		                </foreach>
		            </trim>
				</if>
				<if test='dccodeMulti != null and dccodeMulti != ""'>
					AND MS_PURCHASEDC_DAILY.DCCODE IN
			        <foreach collection="dccodeMulti" item="item" open="(" separator="," close=")">
			            #{item}
			        </foreach>
				</if>
				<if test='buyerkey != null and buyerkey != ""'>
					AND MS_PURCHASEDC_DAILY.BUYERKEY = #{buyerkey}
				</if>
				<if test='fromCustkeyMulti != null and fromCustkeyMulti != ""'>
			        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
		                <foreach collection="fromCustkeyMulti" item="item">
		                    OR MS_PURCHASEDC_DAILY.CUSTKEY IN
		                    <foreach collection="item" item="code" open="(" close=")" separator=",">
		                        #{code}
		                    </foreach>
		                </foreach>
		            </trim>
				</if>
		), PURCHASESTATS_TB AS (
		        SELECT STORERKEY
		               ,SKU
		               ,NVL(SUM(SHIPQTY1W),0)                                    									AS SHIPQTY1W_TOTAL
		               ,NVL(MAX(CASE WHEN DCCODE = '2600' THEN SHIPQTY1W END),0) 									AS SHIPQTY1W_2600
		               ,NVL(MAX(CASE WHEN DCCODE = '2620' THEN SHIPQTY1W END),0) 									AS SHIPQTY1W_2620
		               ,NVL(MAX(CASE WHEN DCCODE = '2630' THEN SHIPQTY1W END),0) 									AS SHIPQTY1W_2630
		               ,NVL(MAX(CASE WHEN DCCODE = '2650' THEN SHIPQTY1W END),0) 									AS SHIPQTY1W_2650
		               ,NVL(MAX(CASE WHEN DCCODE = '2660' THEN SHIPQTY1W END),0) 									AS SHIPQTY1W_2660
		               ,NVL(MAX(CASE WHEN DCCODE = '2230' THEN SHIPQTY1W END),0) 									AS SHIPQTY1W_2230
		               ,NVL(MAX(CASE WHEN DCCODE = '2250' THEN SHIPQTY1W END),0) 									AS SHIPQTY1W_2250
		               ,NVL(MAX(CASE WHEN DCCODE = '2260' THEN SHIPQTY1W END),0) 									AS SHIPQTY1W_2260
		               ,NVL(MAX(CASE WHEN DCCODE = '2270' THEN SHIPQTY1W END),0) 									AS SHIPQTY1W_2270
		               ,NVL(MAX(CASE WHEN DCCODE = '2041' THEN SHIPQTY1W END),0) 									AS SHIPQTY1W_2041
		               ,NVL(MAX(CASE WHEN DCCODE = '1000' THEN SHIPQTY1W END),0) 									AS SHIPQTY1W_1000
		               ,NVL(SUM(SHIPQTY2W),0)                                    									AS SHIPQTY2W_TOTAL
		               ,NVL(MAX(CASE WHEN DCCODE = '2600' THEN SHIPQTY2W END),0) 									AS SHIPQTY2W_2600
		               ,NVL(MAX(CASE WHEN DCCODE = '2620' THEN SHIPQTY2W END),0) 									AS SHIPQTY2W_2620
		               ,NVL(MAX(CASE WHEN DCCODE = '2630' THEN SHIPQTY2W END),0) 									AS SHIPQTY2W_2630
		               ,NVL(MAX(CASE WHEN DCCODE = '2650' THEN SHIPQTY2W END),0) 									AS SHIPQTY2W_2650
		               ,NVL(MAX(CASE WHEN DCCODE = '2660' THEN SHIPQTY2W END),0) 									AS SHIPQTY2W_2660
		               ,NVL(MAX(CASE WHEN DCCODE = '2230' THEN SHIPQTY2W END),0) 									AS SHIPQTY2W_2230
		               ,NVL(MAX(CASE WHEN DCCODE = '2250' THEN SHIPQTY2W END),0) 									AS SHIPQTY2W_2250
		               ,NVL(MAX(CASE WHEN DCCODE = '2260' THEN SHIPQTY2W END),0) 									AS SHIPQTY2W_2260
		               ,NVL(MAX(CASE WHEN DCCODE = '2270' THEN SHIPQTY2W END),0) 									AS SHIPQTY2W_2270
		               ,NVL(MAX(CASE WHEN DCCODE = '2041' THEN SHIPQTY2W END),0) 									AS SHIPQTY2W_2041
		               ,NVL(MAX(CASE WHEN DCCODE = '1000' THEN SHIPQTY2W END),0) 									AS SHIPQTY2W_1000
		               ,NVL(SUM(SHIPQTY3W),0)                                    									AS SHIPQTY3W_TOTAL
		               ,NVL(MAX(CASE WHEN DCCODE = '2600' THEN SHIPQTY3W END),0) 									AS SHIPQTY3W_2600
		               ,NVL(MAX(CASE WHEN DCCODE = '2620' THEN SHIPQTY3W END),0) 									AS SHIPQTY3W_2620
		               ,NVL(MAX(CASE WHEN DCCODE = '2630' THEN SHIPQTY3W END),0) 									AS SHIPQTY3W_2630
		               ,NVL(MAX(CASE WHEN DCCODE = '2650' THEN SHIPQTY3W END),0) 									AS SHIPQTY3W_2650
		               ,NVL(MAX(CASE WHEN DCCODE = '2660' THEN SHIPQTY3W END),0) 									AS SHIPQTY3W_2660
		               ,NVL(MAX(CASE WHEN DCCODE = '2230' THEN SHIPQTY3W END),0) 									AS SHIPQTY3W_2230
		               ,NVL(MAX(CASE WHEN DCCODE = '2250' THEN SHIPQTY3W END),0) 									AS SHIPQTY3W_2250
		               ,NVL(MAX(CASE WHEN DCCODE = '2260' THEN SHIPQTY3W END),0) 									AS SHIPQTY3W_2260
		               ,NVL(MAX(CASE WHEN DCCODE = '2270' THEN SHIPQTY3W END),0) 									AS SHIPQTY3W_2270
		               ,NVL(MAX(CASE WHEN DCCODE = '2041' THEN SHIPQTY3W END),0) 									AS SHIPQTY3W_2041
		               ,NVL(MAX(CASE WHEN DCCODE = '1000' THEN SHIPQTY3W END),0) 									AS SHIPQTY3W_1000
		               ,NVL(MAX(STOCKAVGDAY),0)									 									AS STOCKAVGDAY
		        FROM(
		              SELECT  
		                    MS_PURCHASESTATS.DCCODE
		                    ,MS_PURCHASESTATS.STORERKEY
		                    ,MS_PURCHASESTATS.SKU 
		                    ,MAX(MS_PURCHASESTATS.SHIPQTY1W_SO)   AS SHIPQTY1W
		                    ,MAX(MS_PURCHASESTATS.SHIPQTY2W_SO)   AS SHIPQTY2W
		                    ,MAX(MS_PURCHASESTATS.SHIPQTY3W_SO)   AS SHIPQTY3W
		                    ,MAX(MS_PURCHASESTATS.STOCKAVGDAY) AS STOCKAVGDAY
		                    ,MAX(MS_SKU.SKUTYPE)			   AS SKUTYPE
		              FROM  MS_PURCHASESTATS
		              JOIN	MS_SKU
		                ON  MS_PURCHASESTATS.STORERKEY = MS_SKU.STORERKEY
		               AND  MS_PURCHASESTATS.SKU = MS_SKU.SKU
		              WHERE 1=1
		              AND	MS_PURCHASESTATS.STORERKEY = 'FW00'
		              AND   (MS_PURCHASESTATS.DCCODE IN ('2600', '2620', '2630', '2650', '2660', '2230', '2250', '2260', '2270', '2041')
						     OR
						     (MS_PURCHASESTATS.DCCODE = '1000' AND MS_SKU.SKUTYPE NOT IN('20', '30'))) 
						    
		              AND	1 =  CASE WHEN #{yyyymmdd} = TO_CHAR(SYSDATE, 'YYYYMMDD') THEN 1
		              	              ELSE 2
		              	         END
		             
		              GROUP BY MS_PURCHASESTATS.DCCODE, MS_PURCHASESTATS.STORERKEY, MS_PURCHASESTATS.SKU
		        )
        		GROUP BY STORERKEY, SKU
		),ST_TB AS (
	            SELECT TO_CHAR('FW00')      																						    AS STORERKEY
	                   ,T_STOCKDATE.SKU                                                     										    AS SKU
	                   ,MAX(T_HIS.UOM)                                         										   		 			AS UOM
	                   ,MAX(T_PLT.PLTCNT) 																			    				AS BOXPERPLT
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '1000' AND MS_SKU.SKUTYPE IN ('20', '30') THEN 0 ELSE QTY END),0)                    AS QTY_TOTAL
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE IN ('2600', '2620', '2630', '2650', '2660', '2260') THEN QTY ELSE 0 END),0)            AS QTY_TOTAL_FW
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2600' THEN QTY ELSE 0 END),0)           										    AS QTY_2600
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2620' THEN QTY ELSE 0 END),0)           										    AS QTY_2620
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2630' THEN QTY ELSE 0 END),0)           										    AS QTY_2630
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2650' THEN QTY ELSE 0 END),0)           										    AS QTY_2650
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2660' THEN QTY ELSE 0 END),0)           										    AS QTY_2660
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2230' THEN QTY ELSE 0 END),0)           										    AS QTY_2230
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2250' THEN QTY ELSE 0 END),0)           										    AS QTY_2250
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2260' THEN QTY ELSE 0 END),0)           										    AS QTY_2260
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2270' THEN QTY ELSE 0 END),0)           										    AS QTY_2270
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '1000' AND MS_SKU.SKUTYPE NOT IN('20', '30') THEN QTY ELSE 0 END),0)                 AS QTY_1000
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2900' THEN QTY ELSE 0 END),0)           										    AS QTY_2900
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2041' THEN QTY ELSE 0 END),0)           										    AS QTY_2041
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2930' THEN QTY ELSE 0 END),0)           										    AS QTY_2930
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '1000' AND MS_SKU.SKUTYPE IN ('20', '30') THEN 0 ELSE BOXPERPLT_QTY END),0)          AS BOXPERPLT_QTY_TOTAL
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE IN ('2600', '2620', '2630', '2650', '2660', '2260') THEN BOXPERPLT_QTY ELSE 0 END),0)  AS BOXPERPLT_QTY_TOTAL_FW
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2600' THEN BOXPERPLT_QTY ELSE 0 END),0) 										    AS PLT_2600
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2620' THEN BOXPERPLT_QTY ELSE 0 END),0) 										    AS PLT_2620
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2630' THEN BOXPERPLT_QTY ELSE 0 END),0) 										    AS PLT_2630
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2650' THEN BOXPERPLT_QTY ELSE 0 END),0) 										    AS PLT_2650
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2660' THEN BOXPERPLT_QTY ELSE 0 END),0) 										    AS PLT_2660
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2230' THEN BOXPERPLT_QTY ELSE 0 END),0) 										    AS PLT_2230
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2250' THEN BOXPERPLT_QTY ELSE 0 END),0) 										    AS PLT_2250
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2260' THEN BOXPERPLT_QTY ELSE 0 END),0) 										    AS PLT_2260
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2270' THEN BOXPERPLT_QTY ELSE 0 END),0) 										    AS PLT_2270
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '1000' AND MS_SKU.SKUTYPE NOT IN('20', '30') THEN BOXPERPLT_QTY ELSE 0 END),0)       AS PLT_1000
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2041' THEN BOXPERPLT_QTY ELSE 0 END),0) 										    AS PLT_2041
	                   ,NVL(SUM(CASE WHEN T_HIS.DCCODE = '2930' THEN BOXPERPLT_QTY ELSE 0 END),0) 										    AS PLT_2930
	                   ,MIN(STOCKIN) 																								    AS STOCKIN
	                   ,MAX(STOCKOUT)																								    AS STOCKOUT
                FROM (SELECT SKU, MIN(STOCKDATE) AS STOCKIN, MAX(STOCKDATE) AS STOCKOUT
                      FROM   ST_STOCK_CHAIN_HIS  T
                      WHERE  1=1
                      AND	 T.STOCKDATE <![CDATA[<=]]> #{yyyymmdd}
						<!-- 상품 다중선택 -->
						<if test='skuMulti != null and skuMulti != ""'>
					        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
				                <foreach collection="skuMulti" item="item">
				                    OR T.SKU IN
				                    <foreach collection="item" item="code" open="(" close=")" separator=",">
				                        #{code}
				                    </foreach>
				                </foreach>
				            </trim>
						</if>
                      GROUP BY SKU         
                     ) T_STOCKDATE
	            LEFT OUTER JOIN MS_SKU
	              ON  MS_SKU.STORERKEY = 'FW00'
	             AND  T_STOCKDATE.SKU = MS_SKU.SKU
                LEFT OUTER JOIN ST_STOCK_CHAIN_HIS T_HIS
	                ON  T_HIS.SKU = T_STOCKDATE.SKU
	                AND T_HIS.STOCKDATE = #{yyyymmdd}
	                AND T_HIS.QTY > 0
	                AND T_HIS.DCCODE IN ('2600', '2620', '2630', '2650', '2660', '2230', '2250', '2260', '2270', '2041', '1000', '2930')
	                <if test='dccodeMulti != null and dccodeMulti != ""'>
	                	AND T_HIS.DCCODE IN
				        <foreach collection="dccodeMulti" item="item" open="(" separator="," close=")">
				            #{item}
				        </foreach>
	                </if>
                LEFT OUTER JOIN (
	                SELECT    
					     MS_SKU.SKU               AS SKU             /* 상품코드*/    
					    ,MDPL1.DCCODE             AS DCCODE          /* 센터코드*/   
					    ,MDPL1.CUSTKEY            AS CUSTKEY         /* 협력사코드*/         
					    ,MS_SKU.DESCRIPTION       AS DESCRIPTION     /* 기본 제품명 */   
					    ,MDPL1.BOXPERLAYER * MDPL1.LAYERPERPLT AS PLTCNT         /* PLT 수 */
					FROM LOGISONE.MS_DC_PLT_LOAD MDPL1
					JOIN MS_SKUCHAIN ON
					    MS_SKUCHAIN.SKU = MDPL1.SKU
					    AND MS_SKUCHAIN.STORERKEY = MDPL1.STORERKEY
					JOIN MS_SKU ON
					    MS_SKU.SKU = MDPL1.SKU
					    AND MS_SKU.STORERKEY = MDPL1.STORERKEY
					WHERE MDPL1.STORERKEY = 'FW00'
					  
					UNION ALL
					SELECT    
					     MS_SKU.SKU               AS SKU             /* 상품코드*/    
					    ,NULL                     AS DCCODE          /* 센터코드 없음 */   
					    ,NULL                     AS CUSTKEY         /* 협력사코드 없음 */         
					    ,MS_SKU.DESCRIPTION       AS DESCRIPTION     /* 기본 제품명 */   
					    ,(MS_SKUCHAIN.BOXPERPLT)  AS PLTCNT
					FROM MS_SKUCHAIN
					JOIN MS_SKU ON
					    MS_SKU.SKU = MS_SKUCHAIN.SKU
					    AND MS_SKU.STORERKEY = MS_SKUCHAIN.STORERKEY
					WHERE MS_SKUCHAIN.STORERKEY = 'FW00'					  
					  AND NOT EXISTS (
					        SELECT 1 
					        FROM LOGISONE.MS_DC_PLT_LOAD M
					        WHERE M.STORERKEY = MS_SKUCHAIN.STORERKEY
							  AND M.SKU       = MS_SKUCHAIN.SKU
					    )
                ) T_PLT
                	ON  T_PLT.SKU       = T_STOCKDATE.SKU					
	            WHERE 1=1
	            GROUP BY T_STOCKDATE.SKU  
		),BRAND_TB AS (
				SELECT /*+ FULL(MS_CUST_BRAND) */  -- 1) ■ 2025.12.31 힌트 추가 
					   MS_SKUCHAIN_CUST.SKU AS SKU,
					   MS_SKUCHAIN_CUST.STORERKEY AS STORERKEY,
                         CASE
                           WHEN MS_CUST.PARENTCUSTKEY IS NULL THEN
                            MS_CUST.CUSTKEY
                           ELSE
                            MS_CUST.PARENTCUSTKEY
                         END AS CUSTKEY,
                         
                        -- 2) 기존 스칼라 서브쿼리 주석 
--                         CASE 
--                           WHEN MS_CUST.PARENTCUSTKEY IS NULL THEN 
--                            MS_CUST.DESCRIPTION 
--                           ELSE 
--                            (SELECT A.DESCRIPTION 
--                               FROM LOGISONE.MS_CUST A 
--                              WHERE A.CUSTKEY = MS_CUST.PARENTCUSTKEY 
--                                AND ROWNUM = 1) 
--                         END AS DESCRIPTION, 

                         MS_CUST.PARENTCUSTKEY, -- 3) ■ 2025.12.31 컬럼 추가 
                         MS_CUST.DESCRIPTION,   -- 4) ■ 2025.12.31 컬럼 추가

                         MS_CUST_BRAND.REFERENCE01,
                         MS_CUST_BRAND.REFERENCE02
                    FROM LOGISONE.MS_SKUCHAIN_CUST
                    JOIN LOGISONE.MS_SKU
                      ON MS_SKU.SKU = MS_SKUCHAIN_CUST.SKU
                     AND MS_SKU.STORERKEY = MS_SKUCHAIN_CUST.STORERKEY
                    JOIN LOGISONE.MS_CUST
                      ON MS_SKUCHAIN_CUST.CUSTKEY = MS_CUST.CUSTKEY
                     AND MS_CUST.CUSTTYPE = 'C'
                     AND MS_CUST.STORERKEY = MS_SKUCHAIN_CUST.STORERKEY
-- 5) ■ 2025.12.31 6번에 기존 상관 서브쿼리를 조인 구문으로 변경
                    JOIN (SELECT SKU, MIN(TO_NUMBER(CUSTNO)) CUSTNO
                            FROM LOGISONE.MS_SKUCHAIN_CUST
                           WHERE STORERKEY = 'FW00'
                           <!-- 상품 다중선택 -->
							<if test='skuMulti != null and skuMulti != ""'>
						        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
					                <foreach collection="skuMulti" item="item">
					                    OR SKU IN
					                    <foreach collection="item" item="code" open="(" close=")" separator=",">
					                        #{code}
					                    </foreach>
					                </foreach>
					            </trim>
							</if>
                           GROUP BY SKU ) MIN_CUSTNO
                      ON MIN_CUSTNO.SKU = MS_SKUCHAIN_CUST.SKU
                     AND MIN_CUSTNO.CUSTNO = MS_SKUCHAIN_CUST.CUSTNO
                    LEFT OUTER JOIN LOGISONE.MS_CUST_BRAND 
                      ON MS_CUST_BRAND.CUSTKEY = MS_CUST.CUSTKEY 
                     AND MS_CUST_BRAND.STORERKEY = MS_CUST.STORERKEY 
                     AND MS_CUST_BRAND.CUSTTYPE = MS_CUST.CUSTTYPE 
                   WHERE 1 = 1 
                     AND MS_CUST.DEL_YN = 'N' 
                     AND MS_SKUCHAIN_CUST.STORERKEY = 'FW00' 
-- 6) 기존 쿼리 주석
--                     AND MS_SKUCHAIN_CUST.CUSTNO = 
--                         (SELECT MIN(TO_NUMBER(CUSTNO)) 
--                            FROM LOGISONE.MS_SKUCHAIN_CUST 
--                           WHERE SKU = MS_SKU.SKU)                     
                   
                   GROUP BY MS_SKUCHAIN_CUST.SKU,
                   			MS_SKUCHAIN_CUST.STORERKEY,
                            MS_CUST.CUSTKEY,
                            MS_CUST.PARENTCUSTKEY,
                            MS_CUST.DESCRIPTION,
                            MS_CUST_BRAND.REFERENCE01,
                            MS_CUST_BRAND.REFERENCE02		
		),STO_INOUT_TB AS (
		    SELECT
		        DDD.PLANT 		AS PLANT,  
		        DDD.SKU 		AS SKU,
		        DDD.STORERKEY 	AS STORERKEY,
		        SUM(CASE WHEN DDD.DOCTYPE = 'DP' THEN DDD.CONFIRMQTY ELSE 0 END) AS STO_IN_QTY,  /* 총이체 입고량 */
		        SUM(CASE WHEN DDD.DOCTYPE = 'WD' THEN DDD.CONFIRMQTY ELSE 0 END) AS STO_OUT_QTY   /* 총이체 출고량 */
		    FROM
		        DM_DOCUMENT_D DDD
		    WHERE
		        DDD.WORKPROCESSCODE = 'STO'
		        AND DDD.DELIVERYDATE = #{yyyymmdd}
		        AND DDD.STORERKEY	 = 'FW00'
				<if test='skuMulti != null and skuMulti != ""'>
			        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
		                <foreach collection="skuMulti" item="item">
		                    OR DDD.SKU IN
		                    <foreach collection="item" item="code" open="(" close=")" separator=",">
		                        #{code}
		                    </foreach>
		                </foreach>
		            </trim>
				</if>
		        <if test='dccodeMulti != null and dccodeMulti != ""'>
                	AND DDD.DCCODE IN
			        <foreach collection="dccodeMulti" item="item" open="(" separator="," close=")">
			            #{item}
			        </foreach>
                </if>
		        
		    GROUP BY
		        DDD.PLANT,
		        DDD.SKU,
		        DDD.STORERKEY
		),TURNOVER_TB AS (
		    SELECT
		        T_SUB.STORERKEY,
		        T_SUB.SKU,
		        ROUND(
		            DECODE(
		                NVL(
		                    DECODE(TO_NUMBER(#{prevMMEnd} - #{prevMMStart}), 0, SUM(T_SUB.BASEQTY),
		                           ROUND(SUM(T_SUB.BASEQTY) / TO_NUMBER(#{prevMMEnd} - #{prevMMStart}))
		                    ), 0
		                ), 0, 0,
		                DECODE(
		                    DECODE(TO_NUMBER(#{prevMMEnd} - #{prevMMStart}), 0, SUM(T_SUB.ORDERQTY_SO) + SUM(T_SUB.ORDERQTY_PO) + SUM(T_SUB.ORDERQTY_STO) + SUM(T_SUB.ADJUSTQTY_WD) + SUM(T_SUB.ADJUSTQTY_DISUSE),
		                           ROUND((SUM(T_SUB.ORDERQTY_SO) + SUM(T_SUB.ORDERQTY_PO) + SUM(T_SUB.ORDERQTY_STO) + SUM(T_SUB.ADJUSTQTY_WD) + SUM(T_SUB.ADJUSTQTY_DISUSE)) / TO_NUMBER(#{prevMMEnd} - #{prevMMStart}))
		                    ), 0, 0,
		                    NVL(
		                        DECODE(TO_NUMBER(#{prevMMEnd} - #{prevMMStart}), 0, SUM(T_SUB.BASEQTY),
		                               ROUND(SUM(T_SUB.BASEQTY) / TO_NUMBER(#{prevMMEnd} - #{prevMMStart}))
		                        ), 0
		                    ) /
		                    DECODE(TO_NUMBER(#{prevMMEnd} - #{prevMMStart}), 0, SUM(T_SUB.ORDERQTY_SO) + SUM(T_SUB.ORDERQTY_PO) + SUM(T_SUB.ORDERQTY_STO) + SUM(T_SUB.ADJUSTQTY_WD) + SUM(T_SUB.ADJUSTQTY_DISUSE),
		                           ROUND((SUM(T_SUB.ORDERQTY_SO) + SUM(T_SUB.ORDERQTY_PO) + SUM(T_SUB.ORDERQTY_STO) + SUM(T_SUB.ADJUSTQTY_WD) + SUM(T_SUB.ADJUSTQTY_DISUSE)) / TO_NUMBER(#{prevMMEnd} - #{prevMMStart}))
		                    )
		                )
		            ), 1
		        ) AS TURNOVERDAY
		    FROM
		        (
		            SELECT /*+ FULL(ST_DAILYINOUT) */ -- 7) ■ 2025.12.31 힌트 추가 
		                ST_DAILYINOUT.STORERKEY,
		                ST_DAILYINOUT.SKU,
		                SUM(ST_DAILYINOUT.BASEQTY) AS BASEQTY,
		                SUM(ST_DAILYINOUT.ORDERQTY_SO) AS ORDERQTY_SO,
		                SUM(ST_DAILYINOUT.ORDERQTY_PO) AS ORDERQTY_PO,
		                SUM(ST_DAILYINOUT.ORDERQTY_STO) AS ORDERQTY_STO,
		                SUM(ST_DAILYINOUT.ADJUSTQTY_WD) AS ADJUSTQTY_WD,
		                SUM(ST_DAILYINOUT.ADJUSTQTY_DISUSE) AS ADJUSTQTY_DISUSE
		            FROM
		                ST_DAILYINOUT
		            WHERE
		                ST_DAILYINOUT.STORERKEY = 'FW00'
		                AND ST_DAILYINOUT.INOUTDT <![CDATA[>=]]> #{prevMMStart}
		                AND ST_DAILYINOUT.INOUTDT <![CDATA[<=]]> #{prevMMEnd}
		                <if test='dccodeMulti != null and dccodeMulti != ""'>
		                	AND ST_DAILYINOUT.DCCODE IN
					        <foreach collection="dccodeMulti" item="item" open="(" separator="," close=")">
					            #{item}
					        </foreach>
		                </if>
		                <!-- 상품 다중선택 -->
						<if test='skuMulti != null and skuMulti != ""'>
					        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
				                <foreach collection="skuMulti" item="item">
				                    OR ST_DAILYINOUT.SKU IN
				                    <foreach collection="item" item="code" open="(" close=")" separator=",">
				                        #{code}
				                    </foreach>
				                </foreach>
				            </trim>
						</if>
		            GROUP BY
		                ST_DAILYINOUT.STORERKEY,
		                ST_DAILYINOUT.SKU
		        ) T_SUB
		    GROUP BY T_SUB.STORERKEY, T_SUB.SKU
		    HAVING NVL(DECODE(TO_NUMBER(#{prevMMEnd} - #{prevMMStart}), 0, SUM(T_SUB.BASEQTY),
		                      ROUND(SUM(T_SUB.BASEQTY) / TO_NUMBER(#{prevMMEnd} - #{prevMMStart}))
		                 ), 0) <![CDATA[>]]> 0		        
		)
		SELECT        T3.CHECKYN                                  AS CHECKYN
					,T3.PURCHASE_IN                              AS PURCHASE_IN
					,T3.PURCHASE_OUT                             AS PURCHASE_OUT
					,T3.STOCKIN								  	 AS STOCKIN
					,T3.STOCKOUT								 AS STOCKOUT
					,T3.SKU                                      AS SKU
					,T3.SKUNAME                                  AS SKUNAME
					,T3.STORAGETYPENM                            AS STORAGETYPENM
					,T3.SKUTYPEDESCR                             AS SKUTYPEDESCR
					,T3.SKU_LDESC                                AS SKU_LDESC
					,T3.CUSTSKU                                  AS CUSTSKU
					,T3.REFERENCE15                              AS REFERENCE15
					,T3.NETWEIGHT                                AS NETWEIGHT
					,T3.QTYPERBOX                                AS QTYPERBOX
					,T3.BOXPERPLT                                AS BOXPERPLT
					,T3.PARENTCUSTKEY						     AS PARENTCUSTKEY
					,T3.PARENTCUSTNAME							 AS PARENTCUSTNAME
					,T3.BRANDNAME_FC							 AS BRANDNAME_FC
					,T3.CUSTKEY                                  AS CUSTKEY
					,T3.CUSTNAME                                 AS CUSTNAME
					,T3.SLAVE_CUSTKEY							 AS SLAVE_CUSTKEY
					,T3.SLAVE_CUSTNAME							 AS SLAVE_CUSTNAME
					,T3.LEADTIME                                 AS LEADTIME
					,T3.MOQ_VENDER                               AS MOQ_VENDER
					,T3.MOQ_SKU                                  AS MOQ_SKU
					,T3.LASTBUYERNM                              AS LASTBUYERNM
					,T3.SUPPLYCM                                 AS SUPPLYCM
					,T3.STOCKDC                                  AS STOCKDC
					,T3.DUPYN                                    AS DUPYN
					,T3.PO_DC_2600                               AS PO_DC_2600
					,T3.PO_DC_2620                               AS PO_DC_2620
					,T3.PO_DC_2630                               AS PO_DC_2630
					,T3.PO_DC_2650                               AS PO_DC_2650
					,T3.PO_DC_2660                               AS PO_DC_2660
					,T3.PO_DC_2260                               AS PO_DC_2260
					,T3.PO_DC_2250                               AS PO_DC_2250
					,T3.PO_DC_2230                               AS PO_DC_2230
					,T3.PO_DC_2270                               AS PO_DC_2270
					,T3.PO_DC_1000                               AS PO_DC_1000
					,T3.PO_DC_2900                               AS PO_DC_2900 
					,T3.PURCHASE_YN                              AS PURCHASE_YN
					,T3.BUYERKEYNM_2600 AS BUYERKEYNM_2600  
			        ,CASE WHEN TRIM(T3.BUYERKEYNM_2600) IS NULL THEN NULL ELSE T3.PURCHASETYPE_2600 END AS PURCHASETYPE_2600 
			        ,T3.BUYERKEYNM_2620 AS BUYERKEYNM_2620 
			        ,CASE WHEN TRIM(T3.BUYERKEYNM_2620) IS NULL THEN NULL ELSE T3.PURCHASETYPE_2620 END AS PURCHASETYPE_2620 
			        ,T3.BUYERKEYNM_2630 AS BUYERKEYNM_2630 
			        ,CASE WHEN TRIM(T3.BUYERKEYNM_2630) IS NULL THEN NULL ELSE T3.PURCHASETYPE_2630 END AS PURCHASETYPE_2630 
			        ,T3.BUYERKEYNM_2650 AS BUYERKEYNM_2650 
			        ,CASE WHEN TRIM(T3.BUYERKEYNM_2650) IS NULL THEN NULL ELSE T3.PURCHASETYPE_2650 END AS PURCHASETYPE_2650 
			        ,T3.BUYERKEYNM_2660 AS BUYERKEYNM_2660 
			        ,CASE WHEN TRIM(T3.BUYERKEYNM_2660) IS NULL THEN NULL ELSE T3.PURCHASETYPE_2660 END AS PURCHASETYPE_2660 
			        ,T3.BUYERKEYNM_2260 AS BUYERKEYNM_2260 
			        ,CASE WHEN TRIM(T3.BUYERKEYNM_2260) IS NULL THEN NULL ELSE T3.PURCHASETYPE_2260 END AS PURCHASETYPE_2260 
			        ,T3.BUYERKEYNM_2250 AS BUYERKEYNM_2250 
			        ,CASE WHEN TRIM(T3.BUYERKEYNM_2250) IS NULL THEN NULL ELSE T3.PURCHASETYPE_2250 END AS PURCHASETYPE_2250 
			        ,T3.BUYERKEYNM_2230 AS BUYERKEYNM_2230 
			        ,CASE WHEN TRIM(T3.BUYERKEYNM_2230) IS NULL THEN NULL ELSE T3.PURCHASETYPE_2230 END AS PURCHASETYPE_2230 
			        ,T3.BUYERKEYNM_2270 AS BUYERKEYNM_2270 
			        ,CASE WHEN TRIM(T3.BUYERKEYNM_2270) IS NULL THEN NULL ELSE T3.PURCHASETYPE_2270 END AS PURCHASETYPE_2270 
			        ,T3.BUYERKEYNM_2041 AS BUYERKEYNM_2041 
			        ,CASE WHEN TRIM(T3.BUYERKEYNM_2041) IS NULL THEN NULL ELSE T3.PURCHASETYPE_2041 END AS PURCHASETYPE_2041 
			        ,T3.BUYERKEYNM_1000 AS BUYERKEYNM_1000 
			        ,CASE WHEN TRIM(T3.BUYERKEYNM_1000) IS NULL THEN NULL ELSE T3.PURCHASETYPE_1000 END AS PURCHASETYPE_1000 
			        ,T3.BUYERKEYNM_2900 AS BUYERKEYNM_2900 
			        ,CASE WHEN TRIM(T3.BUYERKEYNM_2900) IS NULL THEN NULL ELSE T3.PURCHASETYPE_2900 END AS PURCHASETYPE_2900 
					,T3.STOCKAVGDAY							  	 AS STOCKAVGDAY
					,T3.STOCKDAY							     AS STOCKDAY
					,T3.STOCKUOM                                 AS STOCKUOM
					,T3.QTY_TOTAL                                AS QTY_TOTAL
					,T3.QTY_TOTAL_FW                             AS QTY_TOTAL_FW
					,T3.QTY_2600                                 AS QTY_2600
					,T3.QTY_2620                                 AS QTY_2620
					,T3.QTY_2630                                 AS QTY_2630
					,T3.QTY_2650                                 AS QTY_2650
					,T3.QTY_2660                                 AS QTY_2660
					,T3.QTY_2260                                 AS QTY_2260
					,T3.QTY_2250                                 AS QTY_2250
					,T3.QTY_2230                                 AS QTY_2230
					,T3.QTY_2270                                 AS QTY_2270
					,T3.QTY_2041                                 AS QTY_2041
					,T3.QTY_1000                                 AS QTY_1000
					,T3.QTY_2930                                 AS QTY_2930
					,T3.BOXPERPLT_QTY_TOTAL                      AS BOXPERPLT_QTY_TOTAL
					,T3.BOXPERPLT_QTY_TOTAL_FW                   AS BOXPERPLT_QTY_TOTAL_FW
					,T3.PLT_2600                                 AS PLT_2600
					,T3.PLT_2620                                 AS PLT_2620
					,T3.PLT_2630                                 AS PLT_2630
					,T3.PLT_2650                                 AS PLT_2650
					,T3.PLT_2660                                 AS PLT_2660
					,T3.PLT_2260                                 AS PLT_2260
					,T3.PLT_2250                                 AS PLT_2250
					,T3.PLT_2230                                 AS PLT_2230
					,T3.PLT_2270                                 AS PLT_2270
					,T3.PLT_2041                                 AS PLT_2041
					,T3.PLT_2930                                 AS PLT_2930
					,T3.PLT_1000                                 AS PLT_1000
					,T3.ROUTE_2600                               AS ROUTE_2600
					,T3.ROUTE_2620                               AS ROUTE_2620
					,T3.ROUTE_2630                               AS ROUTE_2630
					,T3.ROUTE_2650                               AS ROUTE_2650
					,T3.ROUTE_2660                               AS ROUTE_2660
					,T3.ROUTE_2260                               AS ROUTE_2260
					,T3.ROUTE_2230                               AS ROUTE_2230
					,T3.ROUTE_2041                               AS ROUTE_2041
					,T3.ROUTE_1000                               AS ROUTE_1000 
					,T3.SHIPQTY1W_TOTAL                          AS SHIPQTY1W_TOTAL
					,T3.SHIPQTY1W_2600                           AS SHIPQTY1W_2600
					,T3.SHIPQTY1W_2620                           AS SHIPQTY1W_2620
					,T3.SHIPQTY1W_2630                           AS SHIPQTY1W_2630
					,T3.SHIPQTY1W_2650                           AS SHIPQTY1W_2650
					,T3.SHIPQTY1W_2660                           AS SHIPQTY1W_2660
					,T3.SHIPQTY1W_2260                           AS SHIPQTY1W_2260
					,T3.SHIPQTY1W_2250                           AS SHIPQTY1W_2250
					,T3.SHIPQTY1W_2230                           AS SHIPQTY1W_2230
					,T3.SHIPQTY1W_2270                           AS SHIPQTY1W_2270
					,T3.SHIPQTY1W_2041                           AS SHIPQTY1W_2041
					,T3.SHIPQTY1W_1000                           AS SHIPQTY1W_1000
					,T3.SHIPQTY2W_TOTAL                          AS SHIPQTY2W_TOTAL
					,T3.SHIPQTY2W_2600                           AS SHIPQTY2W_2600
					,T3.SHIPQTY2W_2620                           AS SHIPQTY2W_2620
					,T3.SHIPQTY2W_2630                           AS SHIPQTY2W_2630
					,T3.SHIPQTY2W_2650                           AS SHIPQTY2W_2650
					,T3.SHIPQTY2W_2660                           AS SHIPQTY2W_2660
					,T3.SHIPQTY2W_2260                           AS SHIPQTY2W_2260
					,T3.SHIPQTY2W_2250                           AS SHIPQTY2W_2250
					,T3.SHIPQTY2W_2230                           AS SHIPQTY2W_2230
					,T3.SHIPQTY2W_2270                           AS SHIPQTY2W_2270
					,T3.SHIPQTY2W_2041                           AS SHIPQTY2W_2041
					,T3.SHIPQTY2W_1000                           AS SHIPQTY2W_1000
					,T3.SHIPQTY3W_TOTAL                          AS SHIPQTY3W_TOTAL
					,T3.SHIPQTY3W_2600                           AS SHIPQTY3W_2600
					,T3.SHIPQTY3W_2620                           AS SHIPQTY3W_2620
					,T3.SHIPQTY3W_2630                           AS SHIPQTY3W_2630
					,T3.SHIPQTY3W_2650                           AS SHIPQTY3W_2650
					,T3.SHIPQTY3W_2660                           AS SHIPQTY3W_2660
					,T3.SHIPQTY3W_2260                           AS SHIPQTY3W_2260
					,T3.SHIPQTY3W_2250                           AS SHIPQTY3W_2250
					,T3.SHIPQTY3W_2230                           AS SHIPQTY3W_2230
					,T3.SHIPQTY3W_2270                           AS SHIPQTY3W_2270
					,T3.SHIPQTY3W_2041                           AS SHIPQTY3W_2041
					,T3.SHIPQTY3W_1000                           AS SHIPQTY3W_1000
					,T3.STO_IN_QTY								 AS STO_IN_QTY
					,T3.STO_OUT_QTY								 AS STO_OUT_QTY
					,T3.TURNOVERDAY								 AS TURNOVERDAY
		FROM (
			SELECT TRIM(BOTH '/' FROM
			                  CASE WHEN T2.PO_DC_2600 = 'O' THEN '/2600' END ||
			                  CASE WHEN T2.PO_DC_2620 = 'O' THEN '/2620' END ||
			                  CASE WHEN T2.PO_DC_2630 = 'O' THEN '/2630' END ||
			                  CASE WHEN T2.PO_DC_2650 = 'O' THEN '/2650' END ||
			                  CASE WHEN T2.PO_DC_2660 = 'O' THEN '/2660' END ||
			                  CASE WHEN T2.PO_DC_2230 = 'O' THEN '/2230' END ||
			                  CASE WHEN T2.PO_DC_2250 = 'O' THEN '/2250' END ||
			                  CASE WHEN T2.PO_DC_2260 = 'O' THEN '/2260' END ||
			                  CASE WHEN T2.PO_DC_2270 = 'O' THEN '/2270' END ||
			                  CASE WHEN T2.PO_DC_1000 = 'O' THEN '/1000' END || 
			                  CASE WHEN T2.PO_DC_2900 = 'O' THEN '/2900' END
			                 )                                                                                                           AS SUPPLYCM    /* 공급SITE */
			       ,TRIM(BOTH '/' FROM
			                  CASE WHEN T2.QTY_2600 > 0 THEN '/2600' END ||
			                  CASE WHEN T2.QTY_2620 > 0 THEN '/2620' END ||
			                  CASE WHEN T2.QTY_2630 > 0 THEN '/2630' END ||
			                  CASE WHEN T2.QTY_2650 > 0 THEN '/2650' END ||
			                  CASE WHEN T2.QTY_2660 > 0 THEN '/2660' END ||
			                  CASE WHEN T2.QTY_2230 > 0 THEN '/2230' END ||
			                  CASE WHEN T2.QTY_2250 > 0 THEN '/2250' END ||
			                  CASE WHEN T2.QTY_2260 > 0 THEN '/2260' END ||
			                  CASE WHEN T2.QTY_2270 > 0 THEN '/2270' END ||
			                  CASE WHEN T2.QTY_1000 > 0 THEN '/1000' END || 
			                  CASE WHEN T2.QTY_2900 > 0 THEN '/2900' END
			                 )                                                                                                           AS STOCKDC     /* 재고배치 */
			       ,CASE 
			          WHEN(CASE WHEN PO_DC_2600 = 'O' THEN 1 ELSE 0 END +
			               CASE WHEN PO_DC_2620 = 'O' THEN 1 ELSE 0 END +
			               CASE WHEN PO_DC_2630 = 'O' THEN 1 ELSE 0 END +
			               CASE WHEN PO_DC_2650 = 'O' THEN 1 ELSE 0 END +
			               CASE WHEN PO_DC_2660 = 'O' THEN 1 ELSE 0 END 
			              ) > 1
			          THEN 'O'
			          ELSE ''
			        END                                                                                                                  AS DUPYN      /* 이원화유무 */
			       ,ROUND(CASE 
			          WHEN STOCKAVGDAY = 0 THEN 0
                      ELSE(T2.QTY_TOTAL_FW / T2.STOCKAVGDAY)
                    END)     																											 AS STOCKDAY   /* 보유일 */
			       ,T2.*
			FROM(
			        SELECT T1.*
			        	   ,CASE 
                                 WHEN T1.BUYERKEY_2600 NOT IN ('CK','MD','DMKT')
                                      AND ((SELECT DATA3 FROM CM_CODE WHERE STORERKEY = 'FW00' AND CODELIST = 'BUYERKEY' AND DEL_YN = 'N' AND BASECODE = T1.BUYERKEY_2600) = 'Y'
                                            OR T1.BUYERKEY_2600 = 'YANGSAN2')
                                 THEN 'O' 
                             END AS PO_DC_2600 /* 수급센터 2600 */
                           ,CASE 
                                 WHEN T1.BUYERKEY_2620 NOT IN ('CK','MD','DMKT')
                                      AND ((SELECT DATA3 FROM CM_CODE WHERE STORERKEY = 'FW00' AND CODELIST = 'BUYERKEY' AND DEL_YN = 'N' AND BASECODE = T1.BUYERKEY_2620) = 'Y'
                                            OR T1.BUYERKEY_2620 = 'YANGSAN2')
                                 THEN 'O' 
                             END AS PO_DC_2620 /* 수급센터 2620 */
			               ,CASE 
                                 WHEN T1.BUYERKEY_2630 NOT IN ('CK','MD','DMKT')
                                      AND ((SELECT DATA3 FROM CM_CODE WHERE STORERKEY = 'FW00' AND CODELIST = 'BUYERKEY' AND DEL_YN = 'N' AND BASECODE = T1.BUYERKEY_2630) = 'Y'
                                            OR T1.BUYERKEY_2630 = 'YANGSAN2')
                                 THEN 'O' 
                             END AS PO_DC_2630 /* 수급센터 2630 */
			               ,CASE 
                                 WHEN T1.BUYERKEY_2650 NOT IN ('CK','MD','DMKT')
                                      AND ((SELECT DATA3 FROM CM_CODE WHERE STORERKEY = 'FW00' AND CODELIST = 'BUYERKEY' AND DEL_YN = 'N' AND BASECODE = T1.BUYERKEY_2650) = 'Y'
                                            OR T1.BUYERKEY_2650 = 'YANGSAN2')
                                 THEN 'O' 
                             END AS PO_DC_2650 /* 수급센터 2650 */
                           ,CASE 
                                 WHEN T1.BUYERKEY_2660 NOT IN ('CK','MD','DMKT')
                                      AND ((SELECT DATA3 FROM CM_CODE WHERE STORERKEY = 'FW00' AND CODELIST = 'BUYERKEY' AND DEL_YN = 'N' AND BASECODE = T1.BUYERKEY_2660) = 'Y'
                                            OR T1.BUYERKEY_2660 = 'YANGSAN2')
                                 THEN 'O' 
                             END AS PO_DC_2660 /* 수급센터 2660 */
			               ,CASE 
                                 WHEN T1.BUYERKEY_2230 NOT IN ('CK','MD','DMKT')
                                      AND ((SELECT DATA3 FROM CM_CODE WHERE STORERKEY = 'FW00' AND CODELIST = 'BUYERKEY' AND DEL_YN = 'N' AND BASECODE = T1.BUYERKEY_2230) = 'Y'
                                            OR T1.BUYERKEY_2230 = 'YANGSAN2')
                                 THEN 'O' 
                             END AS PO_DC_2230 /* 수급센터 2230 */ 
			               ,CASE 
                                 WHEN T1.BUYERKEY_2250 NOT IN ('CK','MD','DMKT')
                                      AND ((SELECT DATA3 FROM CM_CODE WHERE STORERKEY = 'FW00' AND CODELIST = 'BUYERKEY' AND DEL_YN = 'N' AND BASECODE = T1.BUYERKEY_2250) = 'Y'
                                            OR T1.BUYERKEY_2250 = 'YANGSAN2')
                                 THEN 'O' 
                             END AS PO_DC_2250 /* 수급센터 2250 */ 
			               ,CASE 
                                 WHEN T1.BUYERKEY_2260 NOT IN ('CK','MD','DMKT')
                                      AND ((SELECT DATA3 FROM CM_CODE WHERE STORERKEY = 'FW00' AND CODELIST = 'BUYERKEY' AND DEL_YN = 'N' AND BASECODE = T1.BUYERKEY_2260) = 'Y'
                                            OR T1.BUYERKEY_2260 = 'YANGSAN2')
                                 THEN 'O' 
                             END AS PO_DC_2260 /* 수급센터 2260 */ 
			               ,CASE 
                                 WHEN T1.BUYERKEY_2270 NOT IN ('CK','MD','DMKT')
                                      AND ((SELECT DATA3 FROM CM_CODE WHERE STORERKEY = 'FW00' AND CODELIST = 'BUYERKEY' AND DEL_YN = 'N' AND BASECODE = T1.BUYERKEY_2270) = 'Y'
                                            OR T1.BUYERKEY_2270 = 'YANGSAN2')
                                 THEN 'O' 
                             END AS PO_DC_2270 /* 수급센터 2270 */ 
			               ,CASE 
                                 WHEN T1.BUYERKEY_1000 NOT IN ('CK','MD','DMKT')
                                      AND ((SELECT DATA3 FROM CM_CODE WHERE STORERKEY = 'FW00' AND CODELIST = 'BUYERKEY' AND DEL_YN = 'N' AND BASECODE = T1.BUYERKEY_1000) = 'Y'
                                            OR T1.BUYERKEY_1000 = 'YANGSAN2')
                                 THEN 'O' 
                             END AS PO_DC_1000 /* 수급센터 1000 */ 
			               ,CASE 
                                 WHEN T1.BUYERKEY_2900 NOT IN ('CK','MD','DMKT')
                                      AND ((SELECT DATA3 FROM CM_CODE WHERE STORERKEY = 'FW00' AND CODELIST = 'BUYERKEY' AND DEL_YN = 'N' AND BASECODE = T1.BUYERKEY_2900) = 'Y'
                                            OR T1.BUYERKEY_2900 = 'YANGSAN2')
                                 THEN 'O' 
                             END AS PO_DC_2900 /* 수급센터 2900 */ 
	                       ,CASE WHEN ( CASE WHEN T1.PURCHASETYPE_2600 IS NOT NULL AND T1.BUYERKEYNM_2600 IS NOT NULL THEN 'O'
	                                         WHEN T1.PURCHASETYPE_2620 IS NOT NULL AND T1.BUYERKEYNM_2620 IS NOT NULL THEN 'O'
	                                         WHEN T1.PURCHASETYPE_2630 IS NOT NULL AND T1.BUYERKEYNM_2630 IS NOT NULL THEN 'O'
	                                         WHEN T1.PURCHASETYPE_2650 IS NOT NULL AND T1.BUYERKEYNM_2650 IS NOT NULL THEN 'O'
	                                         WHEN T1.PURCHASETYPE_2660 IS NOT NULL AND T1.BUYERKEYNM_2660 IS NOT NULL THEN 'O'
	                                         WHEN T1.PURCHASETYPE_2230 IS NOT NULL AND T1.BUYERKEYNM_2230 IS NOT NULL THEN 'O'	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   WHEN T1.PURCHASETYPE_2250 IS NOT NULL AND T1.BUYERKEYNM_2250 IS NOT NULL THEN 'O'
	                                         WHEN T1.PURCHASETYPE_2260 IS NOT NULL AND T1.BUYERKEYNM_2260 IS NOT NULL THEN 'O'
	                                         WHEN T1.PURCHASETYPE_2270 IS NOT NULL AND T1.BUYERKEYNM_2270 IS NOT NULL THEN 'O'
	                                         WHEN T1.PURCHASETYPE_2900 IS NOT NULL AND T1.BUYERKEYNM_2900 IS NOT NULL THEN 'O'   
	                                         END
	                                  ) = 'O' THEN '有' ELSE '無' END AS PURCHASE_YN                                                                                 		   /* 수발주유무 */
	                       ,NVL(CD1.BASEDESCR,CD1.BASECODE)					                        									AS LASTBUYERNM                     /* 수급담당(최종) */
	                       ,(SELECT DESCRIPTION 
	                       		 FROM MS_CUST 
	                       		WHERE MS_CUST.STORERKEY = T1.STORERKEY 
	                       		  AND MS_CUST.CUSTKEY 	= T1.CUSTKEY  
	                       		  AND MS_CUST.CUSTTYPE 	='P') 																			AS CUSTNAME                        /* 고객명 */
	                       ,ROUND((SHIPQTY1W_TOTAL / DECODE(NETWEIGHT,0,1,NETWEIGHT) / BIZDATE))				        				AS STOCKAVGDAY                     /* 일평균 */
					       ,REGEXP_SUBSTR(ROUTE, '[^/]+', 1, 1) 																		AS ROUTE_2600
					       ,REGEXP_SUBSTR(ROUTE, '[^/]+', 1, 2) 																		AS ROUTE_2620
					       ,REGEXP_SUBSTR(ROUTE, '[^/]+', 1, 3) 																		AS ROUTE_2630
					       ,REGEXP_SUBSTR(ROUTE, '[^/]+', 1, 4) 																		AS ROUTE_2650		                                                                                                                                                                                     			       ,REGEXP_SUBSTR(ROUTE, '[^/]+', 1, 5) 																		AS ROUTE_2660
					       ,REGEXP_SUBSTR(ROUTE, '[^/]+', 1, 6) 																		AS ROUTE_2230					                                                                                                                                                                                                             ,REGEXP_SUBSTR(ROUTE, '[^/]+', 1, 7) 																		AS ROUTE_2260
					       ,REGEXP_SUBSTR(ROUTE, '[^/]+', 1, 8) 																		AS ROUTE_2041
					       ,REGEXP_SUBSTR(ROUTE, '[^/]+', 1, 9) 																		AS ROUTE_1000
					       ,MS_CUST_SECOND.SLAVE_CUSTKEY       								 											AS SLAVE_CUSTKEY
				           ,CASE WHEN MS_CUST_SECOND.SLAVE_CUSTKEY IS NULL 
				          			THEN ''
				        		  ELSE (SELECT DISTINCT TO_CHAR(NVL(CUST1.DESCRIPTION,'UNKNOWN'))
               								FROM MS_CUST CUST1
							               WHERE CUST1.STORERKEY = MS_CUST_SECOND.STORERKEY
							                 AND CUST1.CUSTTYPE = 'P'
							                 AND CUST1.CUSTKEY = MS_CUST_SECOND.SLAVE_CUSTKEY)
				            END 																 										AS SLAVE_CUSTNAME          
			        FROM   (
			                SELECT '0'              																   					AS CHECKYN
			                       ,NVL(COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY), MAX(ST_TB.STORERKEY))							AS STORERKEY
			                	     ,NVL(COALESCE(PURCHASE_TB.SKU, ST_TB.SKU), MAX(ST_TB.SKU))                                         AS SKU                             /* 상품코드 */          
			                       ,MAX(MS_SKU.DESCRIPTION)                                                            					AS SKUNAME                         /* 상품명 */ 
			                       ,MAX(MS_SKU.STORAGETYPE)                                                            					AS STORAGETYPE                     /* 저장조건 */
								   ,NVL(MAX(CD2.BASEDESCR),MAX(CD2.BASECODE))        													AS STORAGETYPENM                   /* 저장조건명 */
			                       ,MAX(PURCHASE_TB.MOQ_SKU)                                               								AS MOQ_SKU                         /* MOQ(상품 단위) */
			                       ,NVL(MAX(CD3.BASEDESCR),MAX(CD3.BASECODE))      	               										AS SKUTYPEDESCR                    /* 상품유형구분 */
			                       ,NVL(MAX(SKUSPEC1.SPECDESCR),MAX('UNKNOWN'))       													AS SKU_LDESC                       /* 상품범주(대) */
			                       ,MAX(MS_SKU.REFERENCE15)                                                            					AS REFERENCE15                     /* 체인전용구분 */
			                       ,NVL(MAX(MS_SKU.NETWEIGHT),0)                                                     					AS NETWEIGHT                       /* 단위중량 */
			                       ,MAX(MS_SKU.CUSTSKU)                                                                					AS CUSTSKU                         /* CJ상품코드 */
			                       ,NVL(MAX(MS_SKU.QTYPERBOX),0)                                                     					AS QTYPERBOX                       /* 박스입수 */
			                       ,MAX(ST_TB.UOM)                                                                     					AS STOCKUOM                        /* 재고단위 */
			                       ,NVL(MAX(ST_TB.BOXPERPLT),0)                                                  						AS BOXPERPLT                       	   /* PLT입수 */
			                       ,NVL(MAX(QTY_TOTAL),0)                                                              					AS QTY_TOTAL                       /* 전체 재고 합계 */
			                       ,NVL(MAX(QTY_TOTAL_FW),0)                                                              				AS QTY_TOTAL_FW                    /* FW센터 재고 합계 */
			                       ,NVL(MAX(QTY_2600),0)                                                               					AS QTY_2600                        /* 재고 2600 */
			                       ,NVL(MAX(QTY_2620),0)                                                               					AS QTY_2620                        /* 재고 2620 */
			                       ,NVL(MAX(QTY_2630),0)                                                               					AS QTY_2630                        /* 재고 2630 */
			                       ,NVL(MAX(QTY_2650),0)                                                               					AS QTY_2650                        /* 재고 2650 */
			                       ,NVL(MAX(QTY_2660),0)                                                               					AS QTY_2660                        /* 재고 2660 */
			                       ,NVL(MAX(QTY_2230),0) 	                                                           					AS QTY_2230                        /* 재고 2230 */
			                       ,NVL(MAX(QTY_2250),0)                                                               					AS QTY_2250                        /* 재고 2250 */
			                       ,NVL(MAX(QTY_2260),0)                                                               					AS QTY_2260                        /* 재고 2260 */
			                       ,NVL(MAX(QTY_2270),0)                                                               					AS QTY_2270                        /* 재고 2270 */
			                       ,NVL(MAX(QTY_1000),0)                                                               					AS QTY_1000                        /* 재고 1000 */
			                       ,NVL(MAX(QTY_2900),0)                                                               					AS QTY_2900                        /* 재고 2900 */
			                       ,NVL(MAX(QTY_2041),0)                                                               					AS QTY_2041                        /* 재고 2041 */
			                       ,NVL(MAX(QTY_2930),0)                                                               					AS QTY_2930                        /* 재고 2930 */
			                       ,NVL(MAX(BOXPERPLT_QTY_TOTAL),0)                                                    					AS BOXPERPLT_QTY_TOTAL             /* 전체 PLT 합계 */
			                       ,NVL(MAX(BOXPERPLT_QTY_TOTAL_FW),0)                                                    				AS BOXPERPLT_QTY_TOTAL_FW          /* FW센터 PLT 합계 */
			                       ,NVL(MAX(PLT_2600),0)                                                               					AS PLT_2600                        /* PLT 2600 */
			                       ,NVL(MAX(PLT_2620),0)                                                               					AS PLT_2620                        /* PLT 2620 */
			                       ,NVL(MAX(PLT_2630),0)                                                               					AS PLT_2630                        /* PLT 2630 */
			                       ,NVL(MAX(PLT_2650),0)                                                               					AS PLT_2650                        /* PLT 2650 */
			                       ,NVL(MAX(PLT_2660),0)                                                               					AS PLT_2660                        /* PLT 2660 */
			                       ,NVL(MAX(PLT_2230),0) 	                                                           					AS PLT_2230                        /* PLT 2230 */
			                       ,NVL(MAX(PLT_2250),0)                                                               					AS PLT_2250                        /* PLT 2250 */
			                       ,NVL(MAX(PLT_2260),0)                                                               					AS PLT_2260                        /* PLT 2260 */
			                       ,NVL(MAX(PLT_2270),0)                                                               					AS PLT_2270                        /* PLT 2270 */
			                       ,NVL(MAX(PLT_1000),0)                                                               					AS PLT_1000                        /* PLT 1000 */
			                       ,NVL(MAX(PLT_2041),0)                                                               					AS PLT_2041                        /* PLT 2041 */
			                       ,NVL(MAX(PLT_2930),0)                                                               					AS PLT_2930                        /* PLT 2930 */
        		                   ,NVL(MAX(CD4.BASEDESCR),MAX(CD4.BASECODE))                                     						AS PURCHASETYPE_2600               /* 발주구분 2600 */
		                           ,NVL(MAX(CD5.BASEDESCR),MAX(CD5.BASECODE))                                     						AS PURCHASETYPE_2620               /* 발주구분 2620 */
                            	   ,NVL(MAX(CD6.BASEDESCR),MAX(CD6.BASECODE))                                    						AS PURCHASETYPE_2630               /* 발주구분 2630 */
                    		       ,NVL(MAX(CD7.BASEDESCR),MAX(CD7.BASECODE))                                     						AS PURCHASETYPE_2650               /* 발주구분 2650 */
            		               ,NVL(MAX(CD8.BASEDESCR),MAX(CD8.BASECODE))                                     						AS PURCHASETYPE_2660               /* 발주구분 2660 */
      		                       ,NVL(MAX(CD9.BASEDESCR),MAX(CD9.BASECODE))                                     						AS PURCHASETYPE_2230               /* 발주구분 2230 */
	                               ,NVL(MAX(CD10.BASEDESCR),MAX(CD10.BASECODE))                                   						AS PURCHASETYPE_2250               /* 발주구분 2250 */
                        		   ,NVL(MAX(CD11.BASEDESCR),MAX(CD11.BASECODE))                                   						AS PURCHASETYPE_2260               /* 발주구분 2260 */
                  		           ,NVL(MAX(CD12.BASEDESCR),MAX(CD12.BASECODE))                                   						AS PURCHASETYPE_2270               /* 발주구분 2270 */
            	                   ,NVL(MAX(CD13.BASEDESCR),MAX(CD13.BASECODE))                                   						AS PURCHASETYPE_2041               /* 발주구분 2041 */
      	 	                       ,NVL(MAX(CD14.BASEDESCR),MAX(CD14.BASECODE))                                   						AS PURCHASETYPE_1000               /* 발주구분 1000 */
	                               ,NVL(MAX(CD15.BASEDESCR),MAX(CD15.BASECODE))                                   						AS PURCHASETYPE_2900               /* 발주구분 2900 */
			                       ,MAX(PURCHASE_TB.BUYERKEY_2600)     																	AS BUYERKEY_2600                   /* 수급담당 2600 */
			                       ,MAX(PURCHASE_TB.BUYERKEY_2620)     																	AS BUYERKEY_2620                   /* 수급담당 2620 */
			                       ,MAX(PURCHASE_TB.BUYERKEY_2630)    																	AS BUYERKEY_2630                   /* 수급담당 2630 */	
			                       ,MAX(PURCHASE_TB.BUYERKEY_2650)     																	AS BUYERKEY_2650                   /* 수급담당 2650 */
			                       ,MAX(PURCHASE_TB.BUYERKEY_2660)     																	AS BUYERKEY_2660                   /* 수급담당 2660 */
			                       ,MAX(PURCHASE_TB.BUYERKEY_2230)     																	AS BUYERKEY_2230                   /* 수급담당 2230 */
			                       ,MAX(PURCHASE_TB.BUYERKEY_2250)     																	AS BUYERKEY_2250                   /* 수급담당 2250 */
			                       ,MAX(PURCHASE_TB.BUYERKEY_2260)     																	AS BUYERKEY_2260                   /* 수급담당 2260 */
			                       ,MAX(PURCHASE_TB.BUYERKEY_2270)     																	AS BUYERKEY_2270                   /* 수급담당 2270 */
			                       ,MAX(PURCHASE_TB.BUYERKEY_2041)     																	AS BUYERKEY_2041                   /* 수급담당 2041 */
			                       ,MAX(PURCHASE_TB.BUYERKEY_1000)     																	AS BUYERKEY_1000                   /* 수급담당 1000 */
			                       ,MAX(PURCHASE_TB.BUYERKEY_2900)     																	AS BUYERKEY_2900 				   /* 수급담당 2900 */
		                           ,NVL(MAX(CD16.BASEDESCR),MAX(CD16.BASECODE))        			                          				AS BUYERKEYNM_2600                 /* 수급담당 2600 */
                        		   ,NVL(MAX(CD17.BASEDESCR),MAX(CD17.BASECODE))        			                          				AS BUYERKEYNM_2620                 /* 수급담당 2620 */
                		           ,NVL(MAX(CD18.BASEDESCR),MAX(CD18.BASECODE))        			                          				AS BUYERKEYNM_2630                 /* 수급담당 2630 */  
        		                   ,NVL(MAX(CD19.BASEDESCR),MAX(CD19.BASECODE))        			                          				AS BUYERKEYNM_2650                 /* 수급담당 2650 */
		                           ,NVL(MAX(CD20.BASEDESCR),MAX(CD20.BASECODE))        			                          				AS BUYERKEYNM_2660                 /* 수급담당 2660 */
                        		   ,NVL(MAX(CD21.BASEDESCR),MAX(CD21.BASECODE))        			                          				AS BUYERKEYNM_2230                 /* 수급담당 2230 */
                		           ,NVL(MAX(CD22.BASEDESCR),MAX(CD22.BASECODE))        			                          				AS BUYERKEYNM_2250                 /* 수급담당 2250 */
        		                   ,NVL(MAX(CD23.BASEDESCR),MAX(CD23.BASECODE))        			                          				AS BUYERKEYNM_2260                 /* 수급담당 2260 */
		                           ,NVL(MAX(CD24.BASEDESCR),MAX(CD24.BASECODE))        			                          				AS BUYERKEYNM_2270                 /* 수급담당 2270 */
                		           ,NVL(MAX(CD25.BASEDESCR),MAX(CD25.BASECODE))        			                          				AS BUYERKEYNM_2041                 /* 수급담당 2041 */
        		                   ,NVL(MAX(CD26.BASEDESCR),MAX(CD26.BASECODE))        			                          				AS BUYERKEYNM_1000                 /* 수급담당 1000 */
		                           ,NVL(MAX(CD27.BASEDESCR),MAX(CD27.BASECODE))        			                          				AS BUYERKEYNM_2900                 /* 수급담당 2900 */
			                       ,MAX(PURCHASE_TB.ROUTE)																				AS ROUTE						   /* */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY1W_TOTAL * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0) 		AS SHIPQTY1W_TOTAL                 /* D-1 전월출고중량 합계 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY1W_2600 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY1W_2600                  /* D-1 전월출고중량 2600 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY1W_2620 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY1W_2620                  /* D-1 전월출고중량 2620 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY1W_2630 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY1W_2630                  /* D-1 전월출고중량 2630 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY1W_2650 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY1W_2650                  /* D-1 전월출고중량 2650 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY1W_2660 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY1W_2660                  /* D-1 전월출고중량 2660 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY1W_2230 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY1W_2230                  /* D-1 전월출고중량 2230 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY1W_2250 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY1W_2250                  /* D-1 전월출고중량 2250 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY1W_2260 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY1W_2260                  /* D-1 전월출고중량 2260 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY1W_2270 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY1W_2270                  /* D-1 전월출고중량 2260 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY1W_2041 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY1W_2041                  /* D-1 전월출고중량 2041 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY1W_1000 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY1W_1000                  /* D-1 전월출고중량 1000 */ 
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY2W_TOTAL * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0) 		AS SHIPQTY2W_TOTAL                 /* D-2 전월출고중량 합계 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY2W_2600 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY2W_2600                  /* D-2 전월출고중량 2600 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY2W_2620 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY2W_2620                  /* D-2 전월출고중량 2620 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY2W_2630 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY2W_2630                  /* D-2 전월출고중량 2630 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY2W_2650 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY2W_2650                  /* D-2 전월출고중량 2650 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY2W_2660 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY2W_2660                  /* D-2 전월출고중량 2660 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY2W_2230 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY2W_2230                  /* D-2 전월출고중량 2230 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY2W_2250 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY2W_2250                  /* D-2 전월출고중량 2250 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY2W_2260 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY2W_2260                  /* D-2 전월출고중량 2260 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY2W_2270 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY2W_2270                  /* D-2 전월출고중량 2260 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY2W_2041 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY2W_2041				   /* D-2 전월출고중량 2041 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY2W_1000 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY2W_1000                  /* D-2 전월출고중량 1000 */	 
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY3W_TOTAL * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0) 		AS SHIPQTY3W_TOTAL                 /* D-3 전월출고중량 합계 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY3W_2600 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY3W_2600                  /* D-3 전월출고중량 2600 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY3W_2620 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY3W_2620                  /* D-3 전월출고중량 2620 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY3W_2630 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY3W_2630                  /* D-3 전월출고중량 2630 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY3W_2650 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY3W_2650                  /* D-3 전월출고중량 2650 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY3W_2660 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY3W_2660                  /* D-3 전월출고중량 2660 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY3W_2230 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY3W_2230                  /* D-3 전월출고중량 2230 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY3W_2250 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY3W_2250                  /* D-3 전월출고중량 2250 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY3W_2260 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY3W_2260                  /* D-3 전월출고중량 2260 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY3W_2270 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY3W_2270                  /* D-3 전월출고중량 2260 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY3W_2041 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY3W_2041				   /* D-3 전월출고중량 2041 */
			                       ,NVL(MAX(PURCHASESTATS_TB.SHIPQTY3W_1000 * DECODE(MS_SKU.NETWEIGHT,0,1,MS_SKU.NETWEIGHT)),0)  		AS SHIPQTY3W_1000                  /* D-3 전월출고중량 1000 */ 
			                       ,(SELECT SUM(CASE WHEN REST_YN = 'N' THEN 1 ELSE 0 END) 
		  	                           FROM CM_CALENDAR 
			                          WHERE YY||MM||DD BETWEEN TO_CHAR(TO_DATE(#{yyyymmdd},'YYYYMMDD')-30  ,'YYYYMMDD') AND TO_CHAR(TO_DATE(#{yyyymmdd},'YYYYMMDD')-1  ,'YYYYMMDD') 
			                            AND CM_CALENDAR.DCCODE = 'STD' 
			                            AND CM_CALENDAR.CALENDAR_ID = 'STD')                                                            AS BIZDATE                        /* 영업일(D-3 ~ D-1) */										 
			                       ,MAX(PURCHASE_TB.BUYERKEY) KEEP (DENSE_RANK FIRST ORDER BY (
			                                                               CASE 
			                                                                 WHEN PURCHASE_TB.DCCODE = '2600' THEN 1
			                                                                 WHEN PURCHASE_TB.DCCODE = '2650' THEN 2
			                                                                 WHEN PURCHASE_TB.DCCODE = '2660' THEN 3
			                                                                 WHEN PURCHASE_TB.DCCODE = '2620' THEN 4
			                                                                 WHEN PURCHASE_TB.DCCODE = '2630' THEN 5
			                                                                 WHEN PURCHASE_TB.DCCODE = '2260' THEN 6
			                                                                 WHEN PURCHASE_TB.DCCODE = '2230' THEN 7
			                                                                 WHEN PURCHASE_TB.DCCODE = '1000' THEN 8
			                                                                 WHEN PURCHASE_TB.DCCODE = '2900' THEN 9
			                                                                 ELSE 10
			                                                               END
			                                                               )
					                                                  ) AS LASTBUYERKEY																				/* 수급담당(최종) */
			                       ,MAX(PURCHASE_TB.CUSTKEY) KEEP (DENSE_RANK FIRST ORDER BY (
			                                                               CASE 
			                                                                 WHEN PURCHASE_TB.DCCODE = '2600' THEN 1
			                                                                 WHEN PURCHASE_TB.DCCODE = '2650' THEN 2
			                                                                 WHEN PURCHASE_TB.DCCODE = '2660' THEN 3
			                                                                 WHEN PURCHASE_TB.DCCODE = '2620' THEN 4
			                                                                 WHEN PURCHASE_TB.DCCODE = '2630' THEN 5
			                                                                 WHEN PURCHASE_TB.DCCODE = '2260' THEN 6
			                                                                 WHEN PURCHASE_TB.DCCODE = '2230' THEN 7
			                                                                 WHEN PURCHASE_TB.DCCODE = '1000' THEN 8
			                                                                 WHEN PURCHASE_TB.DCCODE = '2900' THEN 9
			                                                                 ELSE 10
			                                                               END
			                                                               )
					                                                  ) AS CUSTKEY																					/* 고객코드 */
			                       ,NVL(MAX(PURCHASE_TB.MOQ_VENDER) KEEP (DENSE_RANK FIRST ORDER BY (
				                                                               CASE 
				                                                                 WHEN PURCHASE_TB.MOQ_VENDER IS NULL  THEN 9999
				                                                                 WHEN PURCHASE_TB.DCCODE = '2600' THEN 1
				                                                                 WHEN PURCHASE_TB.DCCODE = '2650' THEN 2
				                                                                 WHEN PURCHASE_TB.DCCODE = '2660' THEN 3
				                                                                 WHEN PURCHASE_TB.DCCODE = '2620' THEN 4
				                                                                 WHEN PURCHASE_TB.DCCODE = '2630' THEN 5
				                                                                 WHEN PURCHASE_TB.DCCODE = '2260' THEN 6
				                                                                 WHEN PURCHASE_TB.DCCODE = '2230' THEN 7
				                                                                 WHEN PURCHASE_TB.DCCODE = '1000' THEN 8
				                                                                 WHEN PURCHASE_TB.DCCODE = '2900' THEN 9
				                                                                 ELSE 10
				                                                               END
				                                                               )
					                                                  	), 0) AS MOQ_VENDER																			/* MOQ(업체단위) */
			                       ,NVL(MAX(PURCHASE_TB.LEADTIME) KEEP (DENSE_RANK FIRST ORDER BY (
			                                                               CASE 
			                                                                 WHEN PURCHASE_TB.LEADTIME IS NULL      THEN 9999
			                                                                 WHEN PURCHASE_TB.DCCODE = '2600' 		THEN 1
			                                                                 WHEN PURCHASE_TB.DCCODE = '2650' 		THEN 2
			                                                                 WHEN PURCHASE_TB.DCCODE = '2660' 		THEN 3
			                                                                 WHEN PURCHASE_TB.DCCODE = '2620' 		THEN 4
			                                                                 WHEN PURCHASE_TB.DCCODE = '2630' 		THEN 5
			                                                                 WHEN PURCHASE_TB.DCCODE = '2260' 		THEN 6
			                                                                 WHEN PURCHASE_TB.DCCODE = '2230' 		THEN 7
			                                                                 WHEN PURCHASE_TB.DCCODE = '1000' 		THEN 8
			                                                                 WHEN PURCHASE_TB.DCCODE = '2900' 		THEN 9
			                                                                 ELSE 10
			                                                               END
			                                                               )
			                                                  		  ),0) AS LEADTIME																				/* 리드타임 */
			                       ,MAX(PURCHASE_TB.PURCHASE_IN)           																	AS PURCHASE_IN	    	/* 수발주IN */
			                       ,MAX(PURCHASE_TB.PURCHASE_OUT)          																	AS PURCHASE_OUT			/* 수발주OUT */
			                       ,MAX(ST_TB.STOCKIN)					   																	AS STOCKIN				/* 재고 IN */
			                       ,DECODE(MAX(ST_TB.STOCKOUT), #{yyyymmdd}, '', MAX(ST_TB.STOCKOUT))	                    				AS STOCKOUT				/* 재고OUT */
			                       ,MAX(BRAND_TB.CUSTKEY)                        															AS PARENTCUSTKEY        /* 본점코드 */
-- 8) 기존 컬럼 구문 주석 처리
--                            		,MAX(BRAND_TB.DESCRIPTION)                                                   AS PARENTCUSTNAME       /* 본점 */ 
-- 9) ■ 2025.12.31 2번 라인에서 스칼라 서브 쿼리 주석 부분을 해당 라인으로 이동 시킴
								   , MAX(CASE 
								   			WHEN BRAND_TB.PARENTCUSTKEY IS NULL 
								   			THEN BRAND_TB.DESCRIPTION 
                                     	 ELSE (SELECT A.DESCRIPTION FROM LOGISONE.MS_CUST A WHERE A.CUSTKEY = BRAND_TB.PARENTCUSTKEY  AND ROWNUM = 1) END)   AS PARENTCUSTNAME /* 본점 */  
			                       ,MAX(BRAND_TB.REFERENCE02)                        														AS BRANDNAME_FC         /* 브랜드마스터 */
			                	   ,NVL(MAX(STO_TB.STO_IN_QTY), 0) 																			AS STO_IN_QTY         	/* 총이체 입고량 */      
								   ,NVL(MAX(STO_TB.STO_OUT_QTY), 0) 																		AS STO_OUT_QTY       	/* 총이체 출고량 */
								   ,NVL(MAX(T_TB.TURNOVERDAY), 0) 																			AS TURNOVERDAY        /* 재고 회전일 */
			                FROM  PURCHASE_TB
			                <if test='chkyn == "Y"'>
				                LEFT OUTER JOIN ST_TB
				                  ON ST_TB.STORERKEY = PURCHASE_TB.STORERKEY
				                 AND ST_TB.SKU       = PURCHASE_TB.SKU
			                </if>
			                <if test='chkyn == "N"'>
				                FULL OUTER JOIN ST_TB
				                  ON ST_TB.STORERKEY = PURCHASE_TB.STORERKEY
				                 AND ST_TB.SKU       = PURCHASE_TB.SKU
			                </if>
							LEFT OUTER JOIN MS_SKU
			                  ON MS_SKU.STORERKEY = COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY)
			                 AND MS_SKU.SKU       = COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
			                LEFT OUTER JOIN PURCHASESTATS_TB
			                  ON PURCHASESTATS_TB.STORERKEY = COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY)
			                 AND PURCHASESTATS_TB.SKU 		= COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
			                LEFT OUTER JOIN BRAND_TB
			                  ON BRAND_TB.STORERKEY = COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY)
			                 AND BRAND_TB.SKU 		= COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
			                LEFT JOIN CM_CODE CD2
								ON  1=1
								AND CD2.CODELIST  = 'STORAGETYPE'
								AND CD2.BASECODE  = MS_SKU.STORAGETYPE
							LEFT JOIN CM_CODE CD3
								ON  CD3.STORERKEY = MS_SKU.STORERKEY
								AND CD3.CODELIST  = 'SKUTYPE'
								AND CD3.BASECODE  = MS_SKU.SKUTYPE
							LEFT JOIN MS_SKUSPEC SKUSPEC1
								ON  SKUSPEC1.STORERKEY  	= MS_SKU.STORERKEY
								AND SKUSPEC1.SPECCATEGORY  	= 'SKUGROUP'
								AND SKUSPEC1.SPECCODE  		= SUBSTR(MS_SKU.SKUGROUP, 1, 2)
							LEFT JOIN CM_CODE CD4
								ON  CD4.STORERKEY = 'STD'
								AND CD4.CODELIST  = 'PURCHASETYPE_PO'
								AND CD4.BASECODE  = PURCHASE_TB.PURCHASETYPE_2600
							LEFT JOIN CM_CODE CD5
								ON  CD5.STORERKEY = 'STD'
								AND CD5.CODELIST  = 'PURCHASETYPE_PO'
								AND CD5.BASECODE  = PURCHASE_TB.PURCHASETYPE_2620
							LEFT JOIN CM_CODE CD6
								ON  CD6.STORERKEY = 'STD'
								AND CD6.CODELIST  = 'PURCHASETYPE_PO'
								AND CD6.BASECODE  = PURCHASE_TB.PURCHASETYPE_2630							  
							LEFT JOIN CM_CODE CD7
								ON  CD7.STORERKEY = 'STD'
								AND CD7.CODELIST  = 'PURCHASETYPE_PO'
								AND CD7.BASECODE  = PURCHASE_TB.PURCHASETYPE_2650
							LEFT JOIN CM_CODE CD8
								ON  CD8.STORERKEY = 'STD'
								AND CD8.CODELIST  = 'PURCHASETYPE_PO'
								AND CD8.BASECODE  = PURCHASE_TB.PURCHASETYPE_2660
							LEFT JOIN CM_CODE CD9
								ON  CD9.STORERKEY = 'STD'
								AND CD9.CODELIST  = 'PURCHASETYPE_PO'
								AND CD9.BASECODE  = PURCHASE_TB.PURCHASETYPE_2230
							LEFT JOIN CM_CODE CD10
								ON  CD10.STORERKEY = 'STD'
								AND CD10.CODELIST  = 'PURCHASETYPE_PO'
								AND CD10.BASECODE  = PURCHASE_TB.PURCHASETYPE_2250						  
							LEFT JOIN CM_CODE CD11
								ON  CD11.STORERKEY = 'STD'
								AND CD11.CODELIST  = 'PURCHASETYPE_PO'
								AND CD11.BASECODE  = PURCHASE_TB.PURCHASETYPE_2260
							LEFT JOIN CM_CODE CD12
								ON  CD12.STORERKEY = 'STD'
								AND CD12.CODELIST  = 'PURCHASETYPE_PO'
								AND CD12.BASECODE  = PURCHASE_TB.PURCHASETYPE_2270
							LEFT JOIN CM_CODE CD13
								ON  CD13.STORERKEY = 'STD'
								AND CD13.CODELIST  = 'PURCHASETYPE_PO'
								AND CD13.BASECODE  = PURCHASE_TB.PURCHASETYPE_2041
							LEFT JOIN CM_CODE CD14
								ON  CD14.STORERKEY = 'STD'
								AND CD14.CODELIST  = 'PURCHASETYPE_PO'
								AND CD14.BASECODE  = PURCHASE_TB.PURCHASETYPE_1000							  
							LEFT JOIN CM_CODE CD15
								ON  CD15.STORERKEY = 'STD'
								AND CD15.CODELIST  = 'PURCHASETYPE_PO'
								AND CD15.BASECODE  = PURCHASE_TB.PURCHASETYPE_2900							  
							LEFT JOIN CM_CODE CD16
								ON  CD16.STORERKEY = 'FW00'
								AND CD16.CODELIST  = 'BUYERKEY'
								AND CD16.BASECODE  = PURCHASE_TB.BUYERKEY_2600
							LEFT JOIN CM_CODE CD17
								ON  CD17.STORERKEY = 'FW00'
								AND CD17.CODELIST  = 'BUYERKEY'
								AND CD17.BASECODE  = PURCHASE_TB.BUYERKEY_2620
							LEFT JOIN CM_CODE CD18
								ON  CD18.STORERKEY = 'FW00'
								AND CD18.CODELIST  = 'BUYERKEY'
								AND CD18.BASECODE  = PURCHASE_TB.BUYERKEY_2630							  
							LEFT JOIN CM_CODE CD19
								ON  CD19.STORERKEY = 'FW00'
								AND CD19.CODELIST  = 'BUYERKEY'
								AND CD19.BASECODE  = PURCHASE_TB.BUYERKEY_2650
							LEFT JOIN CM_CODE CD20
								ON  CD20.STORERKEY = 'FW00'
								AND CD20.CODELIST  = 'BUYERKEY'
								AND CD20.BASECODE  = PURCHASE_TB.BUYERKEY_2660
							LEFT JOIN CM_CODE CD21
								ON  CD21.STORERKEY = 'FW00'
								AND CD21.CODELIST  = 'BUYERKEY'
								AND CD21.BASECODE  = PURCHASE_TB.BUYERKEY_2230
							LEFT JOIN CM_CODE CD22
								ON  CD22.STORERKEY = 'FW00'
								AND CD22.CODELIST  = 'BUYERKEY'
								AND CD22.BASECODE  = PURCHASE_TB.BUYERKEY_2250							  
							LEFT JOIN CM_CODE CD23
								ON  CD23.STORERKEY = 'FW00'
								AND CD23.CODELIST  = 'BUYERKEY'
								AND CD23.BASECODE  = PURCHASE_TB.BUYERKEY_2260
							LEFT JOIN CM_CODE CD24
								ON  CD24.STORERKEY = 'FW00'
								AND CD24.CODELIST  = 'BUYERKEY'
								AND CD24.BASECODE  = PURCHASE_TB.BUYERKEY_2270
							LEFT JOIN CM_CODE CD25
								ON  CD25.STORERKEY = 'FW00'
								AND CD25.CODELIST  = 'BUYERKEY'
								AND CD25.BASECODE  = PURCHASE_TB.BUYERKEY_2041
							LEFT JOIN CM_CODE CD26
								ON  CD26.STORERKEY = 'FW00'
								AND CD26.CODELIST  = 'BUYERKEY'
								AND CD26.BASECODE  = PURCHASE_TB.BUYERKEY_1000							  
							LEFT JOIN CM_CODE CD27
								ON  CD27.STORERKEY = 'FW00'
								AND CD27.CODELIST  = 'BUYERKEY'
								AND CD27.BASECODE  = PURCHASE_TB.BUYERKEY_2900
							LEFT OUTER JOIN STO_INOUT_TB STO_TB
								ON  STO_TB.STORERKEY = COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY)
								AND STO_TB.SKU 		 = COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
							LEFT OUTER JOIN TURNOVER_TB T_TB
							    ON  T_TB.STORERKEY 	= COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY)
							    AND T_TB.SKU 		= COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
							
			                WHERE  1=1
			                	AND  MS_SKU.STORERKEY = 'FW00'
			                <if test='storagetype != null and storagetype != ""'>
			                	AND  MS_SKU.STORAGETYPE = #{storagetype}
			                </if>
			                <if test='reference15 != null and reference15 != ""'>
			                	AND  MS_SKU.REFERENCE15 = #{reference15}
			                </if>
			                <if test='parentCustkeyMulti != null and parentCustkeyMulti != ""'>
						        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
					                <foreach collection="parentCustkeyMulti" item="item">
					                    OR BRAND_TB.CUSTKEY IN
					                    <foreach collection="item" item="code" open="(" close=")" separator=",">
					                        #{code}
					                    </foreach>
					                </foreach>
					            </trim>
			                </if>
			               
			               GROUP BY COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY), COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
							
			            )T1
			         LEFT OUTER JOIN MS_CUST_SECOND
            		   ON  MS_CUST_SECOND.STORERKEY = T1.STORERKEY
           			   AND MS_CUST_SECOND.CUSTKEY = T1.CUSTKEY
           			   AND MS_CUST_SECOND.SKU = T1.SKU
           			   AND MS_CUST_SECOND.DEL_YN = 'N'
           			 LEFT JOIN CM_CODE CD1
					   ON  CD1.STORERKEY  IN ('%','STD','',T1.STORERKEY)
					   AND CD1.CODELIST  = 'BUYERKEY'
					   AND CD1.BASECODE  = T1.LASTBUYERKEY
			     )T2
			  WHERE  1=1
					<if test='purchaseYn != null and purchaseYn != ""'>
						AND T2.PURCHASE_YN = DECODE(#{purchaseYn},'Y','有','無')
					</if>
					<if test='purchaseOutYn != null and purchaseOutYn != ""'>
						AND ((#{purchaseOutYn} = 'Y' AND T2.PURCHASE_OUT IS NULL) OR (#{purchaseOutYn} = 'N' AND T2.PURCHASE_OUT IS NOT NULL))
					</if>
					<if test='stockYn != null and stockYn != ""'>
						AND ((#{stockYn} = 'N' AND T2.QTY_TOTAL = 0) OR (#{stockYn} = 'Y' AND T2.QTY_TOTAL > 0))
					</if>
				)T3
		WHERE  1=1
		<if test='dupyn != null and dupyn != ""'>
			AND NVL(T3.DUPYN, 'X') = DECODE(#{dupyn},'Y','O','X')
		</if>
    </select>
	
	
	<!-- 수발주마스터 월평균 조회(목록) -->
	<select id="getMasterAvgList" resultType="MsPurchaseDCNewAvgResDto">
	   WITH PURCHASE_TB AS(		/* [msPurchaseDCNewService.sqlx][msPurchaseDCNewService.getMasterAvgList][수발주마스터 월평균 조회(목록)][JeongHyeongCheol][20251014] */ 
		        SELECT  MS_PURCHASEDC_DAILY.STORERKEY                 
         			   ,MS_PURCHASEDC_DAILY.YYYYMMDD                  
         			   ,MS_PURCHASEDC_DAILY.DCCODE                  
         			   ,MS_PURCHASEDC_DAILY.SKU                  
         			   ,MS_PURCHASEDC_DAILY.PURCHASETYPE                  
         			   ,MS_PURCHASEDC_DAILY.BUYERKEY                  
         			   ,MS_PURCHASEDC_DAILY.ROUTE                  
         			   ,MS_PURCHASEDC_DAILY.CUSTKEY                  
         			   ,MS_PURCHASEDC_DAILY.CUSTTYPE                  
         			   ,MS_PURCHASEDC_DAILY.MOQ_VENDER                  
         			   ,MS_PURCHASEDC_DAILY.MOQ_SKU                  
         			   ,MS_PURCHASEDC_DAILY.LEADTIME                  
         			   ,MS_PURCHASEDC_DAILY.PURCHASE_IN                  
         			   ,MS_PURCHASEDC_DAILY.PURCHASE_OUT                  
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2600' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2600
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2620' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2620
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2630' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2630
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2650' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2650
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2660' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2660
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2230' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2230
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2250' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2250
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2260' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2260
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2270' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2270
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2041' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2041
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '1000' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_1000
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2900' THEN MS_PURCHASEDC_DAILY.PURCHASETYPE END AS PURCHASETYPE_2900
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2600' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2600
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2620' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2620
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2630' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2630
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2650' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2650
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2660' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2660
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2230' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2230
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2250' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2250
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2260' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2260
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2270' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2270
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2041' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2041
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '1000' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_1000
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2900' THEN MS_PURCHASEDC_DAILY.BUYERKEY     END AS BUYERKEY_2900
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2600' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2600 
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2620' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2620
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2630' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2630
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2650' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2650
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2660' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2660
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2230' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2230
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2250' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2250
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2260' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2260
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2270' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2270
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2041' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2041
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '1000' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_1000
		               ,CASE WHEN MS_PURCHASEDC_DAILY.DCCODE = '2900' THEN MS_PURCHASEDC_DAILY.CUSTKEY      END AS CUSTKEY_2900
		        FROM    MS_PURCHASEDC_DAILY
		        JOIN   (
		        			SELECT SKU, STORERKEY, MAX(YYYYMMDD) AS YYYYMMDD
				        	FROM   LOGISONE.MS_PURCHASEDC_DAILY
				        	WHERE  1=1
				        	AND    YYYYMMDD BETWEEN #{yyyymm}||'01' AND #{yyyymm}||'31'
				        	GROUP BY SKU, STORERKEY
				        ) T_MS_PURCHASEDC_DAILY
				ON      MS_PURCHASEDC_DAILY.YYYYMMDD 	= T_MS_PURCHASEDC_DAILY.YYYYMMDD
				AND 	MS_PURCHASEDC_DAILY.STORERKEY 	= T_MS_PURCHASEDC_DAILY.STORERKEY
				AND     MS_PURCHASEDC_DAILY.SKU      	= T_MS_PURCHASEDC_DAILY.SKU
		        WHERE	1=1
		        	AND MS_PURCHASEDC_DAILY.STORERKEY 	= 'FW00'
		        <!-- 상품 다중선택 -->		    	
	    		<if test='skuMulti != null and skuMulti != ""'>
			        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
		                <foreach collection="skuMulti" item="item">
		                    OR MS_PURCHASEDC_DAILY.SKU IN
		                    <foreach collection="item" item="code" open="(" close=")" separator=",">
		                        #{code}
		                    </foreach>
		                </foreach>
		            </trim>
				</if>
	    		<if test='dccodeMulti != null and dccodeMulti != ""'>
	    			AND MS_PURCHASEDC_DAILY.DCCODE IN
			        <foreach collection="dccodeMulti" item="item" open="(" separator="," close=")">
			            #{item}
			        </foreach>
	    		</if>  
	    		<if test='buyerkey != null and buyerkey != ""'>
	    			AND MS_PURCHASEDC_DAILY.BUYERKEY = #{buyerkey}
	    		</if>
	    		<if test='fromCustkeyMulti != null and fromCustkeyMulti != ""'>
			        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
		                <foreach collection="fromCustkeyMulti" item="item">
		                    OR MS_PURCHASEDC_DAILY.CUSTKEY IN
		                    <foreach collection="item" item="code" open="(" close=")" separator=",">
		                        #{code}
		                    </foreach>
		                </foreach>
		            </trim>
	    		</if>
		), ST_TB AS (
			    SELECT   TO_CHAR('FW00')      																						AS STORERKEY
			              ,T_STOCKDATE.SKU                                                    										AS SKU
			              ,MAX(ST_STOCK_CHAIN_HIS.UOM)                                                            										AS UOM
			              ,MAX(ST_STOCK_CHAIN_HIS.BOXPERPLT) 																							AS BOXPERPLT
			              ,NVL(SUM(QTY),0)                                                     										AS QTY_TOTAL
			              ,CASE WHEN COUNT(DISTINCT(STOCKDATE)) = 0 THEN 0
			                    ELSE ROUND(NVL(SUM(QTY),0) / #{lastday}, 2)													
			                    END																									AS QTY_AVG
			              ,MIN(STOCKIN)                             																AS STOCKIN
			              ,MAX(STOCKOUT)                           	 																AS STOCKOUT
			              <foreach collection="days" item="day">
							  ,SUM(CASE WHEN STOCKDATE = CONCAT(#{yyyymm}, #{day})  THEN QTY ELSE 0 END) AS QTY_${day}
						  </foreach>			              
			    FROM (SELECT SKU, MIN(STOCKDATE) AS STOCKIN, MAX(STOCKDATE) AS STOCKOUT
			            FROM   ST_STOCK_CHAIN_HIS  T
			            WHERE  1=1
			            AND   T.STOCKDATE <![CDATA[<=]]> #{yyyymm}||'31'
				          <!-- 상품 다중선택 -->
				    	<if test='skuMulti != null and skuMulti != ""'>
					        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
				                <foreach collection="skuMulti" item="item">
				                    OR T.SKU IN
				                    <foreach collection="item" item="code" open="(" close=")" separator=",">
				                        #{code}
				                    </foreach>
				                </foreach>
				            </trim>
						</if>
			            GROUP BY SKU         
			           ) T_STOCKDATE
			    LEFT OUTER JOIN ST_STOCK_CHAIN_HIS
			    ON  ST_STOCK_CHAIN_HIS.SKU = T_STOCKDATE.SKU
			    AND ST_STOCK_CHAIN_HIS.STOCKDATE BETWEEN #{yyyymm}||'01' AND #{yyyymm}||'31'
			    AND ST_STOCK_CHAIN_HIS.QTY <![CDATA[>]]> 0
			    AND ST_STOCK_CHAIN_HIS.DCCODE IN ('2600', '2620', '2630', '2650', '2660', '2260')
			    WHERE 1=1 
			    GROUP BY T_STOCKDATE.SKU
		),BRAND_TB AS (
				SELECT /*+ FULL(MS_CUST_BRAND) */  -- 1) ■ 2025.12.31 힌트 추가 
					   MS_SKUCHAIN_CUST.SKU AS SKU,
					   MS_SKUCHAIN_CUST.STORERKEY AS STORERKEY,
                         CASE
                           WHEN MS_CUST.PARENTCUSTKEY IS NULL THEN
                            MS_CUST.CUSTKEY
                           ELSE
                            MS_CUST.PARENTCUSTKEY
                         END AS CUSTKEY,
                        -- 2) 기존 스칼라 서브쿼리 주석 
--                         CASE 
--                           WHEN MS_CUST.PARENTCUSTKEY IS NULL THEN 
--                            MS_CUST.DESCRIPTION 
--                           ELSE 
--                            (SELECT A.DESCRIPTION 
--                               FROM LOGISONE.MS_CUST A 
--                              WHERE A.CUSTKEY = MS_CUST.PARENTCUSTKEY 
--                                AND ROWNUM = 1) 
--                         END AS DESCRIPTION, 
                         MS_CUST.PARENTCUSTKEY, -- 3) ■ 2025.12.31 컬럼 추가 
                         MS_CUST.DESCRIPTION,   -- 4) ■ 2025.12.31 컬럼 추가
                         MS_CUST_BRAND.REFERENCE01,
                         MS_CUST_BRAND.REFERENCE02
                    FROM LOGISONE.MS_SKUCHAIN_CUST
                    JOIN LOGISONE.MS_SKU
                      ON MS_SKU.SKU = MS_SKUCHAIN_CUST.SKU
                     AND MS_SKU.STORERKEY = MS_SKUCHAIN_CUST.STORERKEY
                    JOIN LOGISONE.MS_CUST
                      ON MS_SKUCHAIN_CUST.CUSTKEY = MS_CUST.CUSTKEY
                     AND MS_CUST.CUSTTYPE = 'C'
                     AND MS_CUST.STORERKEY = 'FW00'
-- 5) ■ 2025.12.31 6번에 기존 상관 서브쿼리를 조인 구문으로 변경
                    JOIN (SELECT SKU, MIN(TO_NUMBER(CUSTNO)) CUSTNO
                            FROM LOGISONE.MS_SKUCHAIN_CUST
                           WHERE STORERKEY = 'FW00'
                           GROUP BY SKU ) MIN_CUSTNO
                      ON MIN_CUSTNO.SKU = MS_SKUCHAIN_CUST.SKU
                     AND MIN_CUSTNO.CUSTNO = MS_SKUCHAIN_CUST.CUSTNO
                    LEFT OUTER JOIN LOGISONE.MS_CUST_BRAND 
                      ON MS_CUST_BRAND.CUSTKEY = MS_CUST.CUSTKEY 
                     AND MS_CUST_BRAND.STORERKEY = MS_CUST.STORERKEY 
                     AND MS_CUST_BRAND.CUSTTYPE = MS_CUST.CUSTTYPE 
                   WHERE 1 = 1 
                     AND MS_CUST.DEL_YN = 'N' 
                     AND MS_SKUCHAIN_CUST.STORERKEY = 'FW00' 
-- 6) 기존 쿼리 주석
--                     AND MS_SKUCHAIN_CUST.CUSTNO = 
--                         (SELECT MIN(TO_NUMBER(CUSTNO)) 
--                            FROM LOGISONE.MS_SKUCHAIN_CUST 
--                           WHERE SKU = MS_SKU.SKU) 
                   GROUP BY MS_SKUCHAIN_CUST.SKU,
                   			MS_SKUCHAIN_CUST.STORERKEY,
                            MS_CUST.CUSTKEY,
                            MS_CUST.PARENTCUSTKEY,
                            MS_CUST.DESCRIPTION,
                            MS_CUST_BRAND.REFERENCE01,
                            MS_CUST_BRAND.REFERENCE02		
		),STO_INOUT_TB AS (
		    SELECT
		        DDD.PLANT 		AS PLANT,  
		        DDD.SKU 		AS SKU,
		        DDD.STORERKEY 	AS STORERKEY,
		        SUM(CASE WHEN DDD.DOCTYPE = 'DP' THEN DDD.CONFIRMQTY ELSE 0 END) AS STO_IN_QTY,  /* 총이체 입고량 */
		        SUM(CASE WHEN DDD.DOCTYPE = 'WD' THEN DDD.CONFIRMQTY ELSE 0 END) AS STO_OUT_QTY   /* 총이체 출고량 */
		    FROM
		        DM_DOCUMENT_D DDD
		    WHERE
		        DDD.WORKPROCESSCODE = 'STO'
		        AND DDD.DELIVERYDATE BETWEEN #{yyyymm}||'01' AND #{yyyymm}||'31'
		        AND DDD.STORERKEY = 'FW00'
				<if test='skuMulti != null and skuMulti != ""'>
			        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
		                <foreach collection="skuMulti" item="item">
		                    OR DDD.SKU IN
		                    <foreach collection="item" item="code" open="(" close=")" separator=",">
		                        #{code}
		                    </foreach>
		                </foreach>
		            </trim>
				</if>
		        <if test='dccodeMulti != null and dccodeMulti != ""'>
                	AND DDD.DCCODE IN
			        <foreach collection="dccodeMulti" item="item" open="(" separator="," close=")">
			            #{item}
			        </foreach>
                </if>
		        
		    GROUP BY
		        DDD.PLANT,
		        DDD.SKU,
		        DDD.STORERKEY
		),TURNOVER_TB AS (
		    SELECT
		        T_SUB.STORERKEY,
		        T_SUB.SKU,
		        ROUND(
		            DECODE(
		                NVL(
		                    DECODE(TO_NUMBER(#{prevMMEnd} - #{prevMMStart}), 0, SUM(T_SUB.BASEQTY),
		                           ROUND(SUM(T_SUB.BASEQTY) / TO_NUMBER(#{prevMMEnd} - #{prevMMStart}))
		                    ), 0
		                ), 0, 0,
		                DECODE(
		                    DECODE(TO_NUMBER(#{prevMMEnd} - #{prevMMStart}), 0, SUM(T_SUB.ORDERQTY_SO) + SUM(T_SUB.ORDERQTY_PO) + SUM(T_SUB.ORDERQTY_STO) + SUM(T_SUB.ADJUSTQTY_WD) + SUM(T_SUB.ADJUSTQTY_DISUSE),
		                           ROUND((SUM(T_SUB.ORDERQTY_SO) + SUM(T_SUB.ORDERQTY_PO) + SUM(T_SUB.ORDERQTY_STO) + SUM(T_SUB.ADJUSTQTY_WD) + SUM(T_SUB.ADJUSTQTY_DISUSE)) / TO_NUMBER(#{prevMMEnd} - #{prevMMStart}))
		                    ), 0, 0,
		                    NVL(
		                        DECODE(TO_NUMBER(#{prevMMEnd} - #{prevMMStart}), 0, SUM(T_SUB.BASEQTY),
		                               ROUND(SUM(T_SUB.BASEQTY) / TO_NUMBER(#{prevMMEnd} - #{prevMMStart}))
		                        ), 0
		                    ) /
		                    DECODE(TO_NUMBER(#{prevMMEnd} - #{prevMMStart}), 0, SUM(T_SUB.ORDERQTY_SO) + SUM(T_SUB.ORDERQTY_PO) + SUM(T_SUB.ORDERQTY_STO) + SUM(T_SUB.ADJUSTQTY_WD) + SUM(T_SUB.ADJUSTQTY_DISUSE),
		                           ROUND((SUM(T_SUB.ORDERQTY_SO) + SUM(T_SUB.ORDERQTY_PO) + SUM(T_SUB.ORDERQTY_STO) + SUM(T_SUB.ADJUSTQTY_WD) + SUM(T_SUB.ADJUSTQTY_DISUSE)) / TO_NUMBER(#{prevMMEnd} - #{prevMMStart}))
		                    )
		                )
		            ), 1
		        ) AS TURNOVERDAY
		    FROM
		        (
		            SELECT /*+ FULL(ST_DAILYINOUT) */ -- 7) ■ 2025.12.31 힌트 추가 
		                ST_DAILYINOUT.STORERKEY,
		                ST_DAILYINOUT.SKU,
		                SUM(ST_DAILYINOUT.BASEQTY) AS BASEQTY,
		                SUM(ST_DAILYINOUT.ORDERQTY_SO) AS ORDERQTY_SO,
		                SUM(ST_DAILYINOUT.ORDERQTY_PO) AS ORDERQTY_PO,
		                SUM(ST_DAILYINOUT.ORDERQTY_STO) AS ORDERQTY_STO,
		                SUM(ST_DAILYINOUT.ADJUSTQTY_WD) AS ADJUSTQTY_WD,
		                SUM(ST_DAILYINOUT.ADJUSTQTY_DISUSE) AS ADJUSTQTY_DISUSE
		            FROM
		                ST_DAILYINOUT
		            WHERE
		                ST_DAILYINOUT.STORERKEY = 'FW00'
		                AND ST_DAILYINOUT.INOUTDT <![CDATA[>=]]> #{prevMMStart}
		                AND ST_DAILYINOUT.INOUTDT <![CDATA[<=]]> #{prevMMEnd}
		                <if test='dccodeMulti != null and dccodeMulti != ""'>
		                	AND ST_DAILYINOUT.DCCODE IN
					        <foreach collection="dccodeMulti" item="item" open="(" separator="," close=")">
					            #{item}
					        </foreach>
		                </if>
		            GROUP BY
		                ST_DAILYINOUT.STORERKEY,
		                ST_DAILYINOUT.SKU
		        ) T_SUB
		    GROUP BY T_SUB.STORERKEY, T_SUB.SKU
		    HAVING NVL(DECODE(TO_NUMBER(#{prevMMEnd} - #{prevMMStart}), 0, SUM(T_SUB.BASEQTY),
		                      ROUND(SUM(T_SUB.BASEQTY) / TO_NUMBER(#{prevMMEnd} - #{prevMMStart}))
		                 ), 0) <![CDATA[>]]> 0		        
		)
		SELECT        T3.CHECKYN                                  												  AS CHECKYN
                     ,T3.PURCHASE_IN                              												  AS PURCHASE_IN
                     ,T3.PURCHASE_OUT                             												  AS PURCHASE_OUT
                     ,T3.STOCKIN								  												  AS STOCKIN
                     ,T3.STOCKOUT								  												  AS STOCKOUT
                     ,T3.SKU                                      												  AS SKU
                     ,T3.SKUNAME                                  												  AS SKUNAME
                     ,T3.STORAGETYPENM                            												  AS STORAGETYPENM
                     ,T3.SKUTYPEDESCR                             												  AS SKUTYPEDESCR
                     ,T3.SKU_LDESC                                												  AS SKU_LDESC
                     ,T3.CUSTSKU                                  												  AS CUSTSKU
                     ,T3.REFERENCE15                              												  AS REFERENCE15
                     ,T3.NETWEIGHT                                												  AS NETWEIGHT
                     ,T3.QTYPERBOX                                												  AS QTYPERBOX
                     ,T3.BOXPERPLT                                												  AS BOXPERPLT
                     ,T3.PARENTCUSTKEY						      												  AS PARENTCUSTKEY
                     ,T3.PARENTCUSTNAME							  												  AS PARENTCUSTNAME
                     ,T3.BRANDNAME_FC							  												  AS BRANDNAME_FC
                     ,T3.CUSTKEY                                  												  AS CUSTKEY
                     ,T3.CUSTNAME                                 												  AS CUSTNAME
                     ,T3.SLAVE_CUSTKEY							  												  AS SLAVE_CUSTKEY
                     ,T3.SLAVE_CUSTNAME							  												  AS SLAVE_CUSTNAME
                     ,T3.LEADTIME                                 												  AS LEADTIME
                     ,T3.MOQ_VENDER                               												  AS MOQ_VENDER
                     ,T3.MOQ_SKU                                  												  AS MOQ_SKU
                     ,T3.LASTBUYERNM                              												  AS LASTBUYERNM
                     ,T3.STOCKUOM                                 												  AS STOCKUOM
	                 ,T3.QTY_TOTAL                                                                                AS QTY_TOTAL                            
	                 ,T3.QTY_AVG                                                                                  AS QTY_AVG                              
	                 ,T3.QTY_01                                                                                   AS QTY_01                               
	                 ,T3.QTY_02                                                                                   AS QTY_02                               
	                 ,T3.QTY_03                                                                                   AS QTY_03                               
	                 ,T3.QTY_04                                                                                   AS QTY_04                               
	                 ,T3.QTY_05                                                                                   AS QTY_05                               
	                 ,T3.QTY_06                                                                                   AS QTY_06                               
	                 ,T3.QTY_07                                                                                   AS QTY_07                               
	                 ,T3.QTY_08                                                                                   AS QTY_08                               
	                 ,T3.QTY_09                                                                                   AS QTY_09                               
	                 ,T3.QTY_10                                                                                   AS QTY_10                               
	                 ,T3.QTY_11                                                                                   AS QTY_11                               
	                 ,T3.QTY_12                                                                                   AS QTY_12                               
	                 ,T3.QTY_13                                                                                   AS QTY_13                               
	                 ,T3.QTY_14                                                                                   AS QTY_14                               
	                 ,T3.QTY_15                                                                                   AS QTY_15                               
	                 ,T3.QTY_16                                                                                   AS QTY_16                               
	                 ,T3.QTY_17                                                                                   AS QTY_17                               
	                 ,T3.QTY_18                                                                                   AS QTY_18                               
	                 ,T3.QTY_19                                                                                   AS QTY_19                               
	                 ,T3.QTY_20                                                                                   AS QTY_20                               
	                 ,T3.QTY_21                                                                                   AS QTY_21                               
	                 ,T3.QTY_22                                                                                   AS QTY_22                               
	                 ,T3.QTY_23                                                                                   AS QTY_23                               
	                 ,T3.QTY_24                                                                                   AS QTY_24                               
	                 ,T3.QTY_25                                                                                   AS QTY_25                               
	                 ,T3.QTY_26                                                                                   AS QTY_26                               
	                 ,T3.QTY_27                                                                                   AS QTY_27                               
	                 ,T3.QTY_28                                                                                   AS QTY_28                               
	                 ,T3.QTY_29                                                                                   AS QTY_29                               
	                 ,T3.QTY_30                                                                                   AS QTY_30                               
	                 ,T3.QTY_31                                                                                   AS QTY_31                               
	                 ,T3.PLT_TOTAL                                                                                AS PLT_TOTAL                            
	                 ,T3.PLT_AVG                                                                                  AS PLT_AVG                              
	                 ,T3.PLT_01                                                                                   AS PLT_01                               
	                 ,T3.PLT_02                                                                                   AS PLT_02                               
	                 ,T3.PLT_03                                                                                   AS PLT_03                               
	                 ,T3.PLT_04                                                                                   AS PLT_04                               
	                 ,T3.PLT_05                                                                                   AS PLT_05                               
	                 ,T3.PLT_06                                                                                   AS PLT_06                               
	                 ,T3.PLT_07                                                                                   AS PLT_07                               
	                 ,T3.PLT_08                                                                                   AS PLT_08                               
	                 ,T3.PLT_09                                                                                   AS PLT_09                               
	                 ,T3.PLT_10                                                                                   AS PLT_10                               
	                 ,T3.PLT_11                                                                                   AS PLT_11                               
	                 ,T3.PLT_12                                                                                   AS PLT_12                               
	                 ,T3.PLT_13                                                                                   AS PLT_13                               
	                 ,T3.PLT_14                                                                                   AS PLT_14                               
	                 ,T3.PLT_15                                                                                   AS PLT_15                               
	                 ,T3.PLT_16                                                                                   AS PLT_16                               
	                 ,T3.PLT_17                                                                                   AS PLT_17                               
	                 ,T3.PLT_18                                                                                   AS PLT_18                               
	                 ,T3.PLT_19                                                                                   AS PLT_19                               
	                 ,T3.PLT_20                                                                                   AS PLT_20                               
	                 ,T3.PLT_21                                                                                   AS PLT_21                               
	                 ,T3.PLT_22                                                                                   AS PLT_22                               
	                 ,T3.PLT_23                                                                                   AS PLT_23                               
	                 ,T3.PLT_24                                                                                   AS PLT_24                               
	                 ,T3.PLT_25                                                                                   AS PLT_25                               
	                 ,T3.PLT_26                                                                                   AS PLT_26                               
	                 ,T3.PLT_27                                                                                   AS PLT_27                               
	                 ,T3.PLT_28                                                                                   AS PLT_28                               
	                 ,T3.PLT_29                                                                                   AS PLT_29                               
	                 ,T3.PLT_30                                                                                   AS PLT_30                               
	                 ,T3.PLT_31                                                                                   AS PLT_31
	                 ,T3.STO_IN_QTY								 												  AS STO_IN_QTY
					 ,T3.STO_OUT_QTY								 											  AS STO_OUT_QTY
					 ,T3.TURNOVERDAY								 											  AS TURNOVERDAY  
		FROM (
			SELECT T2.*
			FROM(
			        SELECT T1.*
	                       ,NVL(CD1.BASEDESCR,CD1.BASECODE)						 				                        				AS LASTBUYERNM                     /* 수급담당(최종) */
	                       ,(SELECT DESCRIPTION 
	                       		 FROM MS_CUST 
	                       		WHERE MS_CUST.CUSTKEY 	= T1.CUSTKEY
	                       		  AND MS_CUST.STORERKEY = T1.STORERKEY 
	                       		  AND MS_CUST.CUSTTYPE 	='P') 																			AS CUSTNAME                        /* 고객명 */
					       ,MS_CUST_SECOND.SLAVE_CUSTKEY       								 											AS SLAVE_CUSTKEY
				           ,CASE WHEN MS_CUST_SECOND.SLAVE_CUSTKEY IS NULL 
				          			THEN ''
				        		  ELSE (SELECT DISTINCT TO_CHAR(NVL(CUST1.DESCRIPTION,'UNKNOWN'))
               								FROM MS_CUST CUST1
							               WHERE CUST1.STORERKEY = MS_CUST_SECOND.STORERKEY
							                 AND CUST1.CUSTTYPE = 'P'
							                 AND CUST1.CUSTKEY = MS_CUST_SECOND.SLAVE_CUSTKEY)
				            END 																 										AS SLAVE_CUSTNAME          
			        FROM   (
			                SELECT '0'              																   					AS CHECKYN
			                       ,NVL(COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY), MAX(ST_TB.STORERKEY))							AS STORERKEY
			                	   ,NVL(COALESCE(PURCHASE_TB.SKU, ST_TB.SKU), MAX(ST_TB.SKU))                                           AS SKU                             /* 상품코드 */          
			                       ,MAX(MS_SKU.DESCRIPTION)                                                            					AS SKUNAME                         /* 상품명 */ 
			                       ,MAX(MS_SKU.STORAGETYPE)                                                            					AS STORAGETYPE                     /* 저장조건 */
								   ,NVL(MAX(CD2.BASEDESCR),MAX(CD2.BASECODE))											        		AS STORAGETYPENM                   /* 저장조건명 */
			                       ,MAX(PURCHASE_TB.MOQ_SKU)                                               								AS MOQ_SKU                         /* MOQ(상품 단위) */
			                       ,NVL(MAX(CD3.BASEDESCR),MAX(CD3.BASECODE))      	   						            				AS SKUTYPEDESCR                    /* 상품유형구분 */
			                       ,NVL(MAX(SKUSPEC1.SPECDESCR),MAX('UNKNOWN'))       													AS SKU_LDESC                       /* 상품범주(대) */
			                       ,MAX(MS_SKU.REFERENCE15)                                                            					AS REFERENCE15                     /* 체인전용구분 */
			                       ,NVL(MAX(MS_SKU.NETWEIGHT),0)                                                     					AS NETWEIGHT                       /* 단위중량 */
			                       ,MAX(MS_SKU.CUSTSKU)                                                                					AS CUSTSKU                         /* CJ상품코드 */
			                       ,NVL(MAX(MS_SKU.QTYPERBOX),0)                                                     					AS QTYPERBOX                       /* 박스입수 */
			                       ,MAX(ST_TB.UOM)                                                                     					AS STOCKUOM                        /* 재고단위 */
			                       ,NVL(MAX(T_PLT.PLTCNT),0)                                                  							AS BOXPERPLT                       /* PLT입수 */
	                               ,NVL(MAX(ST_TB.QTY_TOTAL),0)                                                                         AS QTY_TOTAL                       
	                               ,NVL(MAX(ST_TB.QTY_AVG),0)                                                                           AS QTY_AVG
	                               ,NVL(MAX(ST_TB.QTY_01),0)                                                                            AS QTY_01
	                               ,NVL(MAX(ST_TB.QTY_02),0)                                                                            AS QTY_02
	                               ,NVL(MAX(ST_TB.QTY_03),0)                                                                            AS QTY_03
	                               ,NVL(MAX(ST_TB.QTY_04),0)                                                                            AS QTY_04
	                               ,NVL(MAX(ST_TB.QTY_05),0)                                                                            AS QTY_05
	                               ,NVL(MAX(ST_TB.QTY_06),0)                                                                            AS QTY_06
	                               ,NVL(MAX(ST_TB.QTY_07),0)                                                                            AS QTY_07
	                               ,NVL(MAX(ST_TB.QTY_08),0)                                                                            AS QTY_08
	                               ,NVL(MAX(ST_TB.QTY_09),0)                                                                            AS QTY_09
	                               ,NVL(MAX(ST_TB.QTY_10),0)                                                                            AS QTY_10
	                               ,NVL(MAX(ST_TB.QTY_11),0)                                                                            AS QTY_11
	                               ,NVL(MAX(ST_TB.QTY_12),0)                                                                            AS QTY_12
	                               ,NVL(MAX(ST_TB.QTY_13),0)                                                                            AS QTY_13
	                               ,NVL(MAX(ST_TB.QTY_14),0)                                                                            AS QTY_14
	                               ,NVL(MAX(ST_TB.QTY_15),0)                                                                            AS QTY_15
	                               ,NVL(MAX(ST_TB.QTY_16),0)                                                                            AS QTY_16
	                               ,NVL(MAX(ST_TB.QTY_17),0)                                                                            AS QTY_17
	                               ,NVL(MAX(ST_TB.QTY_18),0)                                                                            AS QTY_18
	                               ,NVL(MAX(ST_TB.QTY_19),0)                                                                            AS QTY_19
	                               ,NVL(MAX(ST_TB.QTY_20),0)                                                                            AS QTY_20
	                               ,NVL(MAX(ST_TB.QTY_21),0)                                                                            AS QTY_21
	                               ,NVL(MAX(ST_TB.QTY_22),0)                                                                            AS QTY_22
	                               ,NVL(MAX(ST_TB.QTY_23),0)                                                                            AS QTY_23
	                               ,NVL(MAX(ST_TB.QTY_24),0)                                                                            AS QTY_24
	                               ,NVL(MAX(ST_TB.QTY_25),0)                                                                            AS QTY_25
	                               ,NVL(MAX(ST_TB.QTY_26),0)                                                                            AS QTY_26
	                               ,NVL(MAX(ST_TB.QTY_27),0)                                                                            AS QTY_27
	                               ,NVL(MAX(ST_TB.QTY_28),0)                                                                            AS QTY_28
	                               ,NVL(MAX(ST_TB.QTY_29),0)                                                                            AS QTY_29
	                               ,NVL(MAX(ST_TB.QTY_30),0)                                                                            AS QTY_30
	                               ,NVL(MAX(ST_TB.QTY_31),0)                                                                            AS QTY_31
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_TOTAL), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_TOTAL) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_TOTAL
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_AVG), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_AVG) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_AVG
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_01), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_01) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_01
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_02), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_02) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_02
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_03), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_03) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_03
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_04), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_04) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_04
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_05), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_05) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_05
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_06), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_06) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_06
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_07), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_07) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_07
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_08), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_08) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_08
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_09), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_09) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_09
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_10), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_10) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_10
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_11), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_11) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_11
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_12), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_12) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_12
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_13), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_13) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_13
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_14), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_14) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_14
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_15), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_15) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_15
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_16), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_16) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_16
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_17), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_17) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_17
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_18), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_18) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_18
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_19), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_19) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_19
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_20), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_20) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_20
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_21), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_21) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_21
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_22), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_22) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_22
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_23), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_23) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_23
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_24), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_24) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_24
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_25), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_25) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_25
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_26), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_26) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_26
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_27), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_27) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_27
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_28), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_28) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_28
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_29), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_29) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_29
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_30), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_30) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_30
	                               , CASE WHEN NVL(MAX(T_PLT.PLTCNT), 0) > 0 AND NVL(MAX(ST_TB.QTY_31), 0) > 0 THEN CEIL(MAX(ST_TB.QTY_31) / NVL(MAX(MS_SKU.QTYPERBOX),0) / MAX(T_PLT.PLTCNT)) ELSE 0 END AS PLT_31
			                       ,MAX(PURCHASE_TB.BUYERKEY) KEEP (DENSE_RANK FIRST ORDER BY (
			                                                               CASE 
			                                                                 WHEN PURCHASE_TB.DCCODE = '2600' THEN 1
			                                                                 WHEN PURCHASE_TB.DCCODE = '2650' THEN 2
			                                                                 WHEN PURCHASE_TB.DCCODE = '2660' THEN 3
			                                                                 WHEN PURCHASE_TB.DCCODE = '2620' THEN 4
			                                                                 WHEN PURCHASE_TB.DCCODE = '2630' THEN 5
			                                                                 WHEN PURCHASE_TB.DCCODE = '2260' THEN 6
			                                                                 WHEN PURCHASE_TB.DCCODE = '2230' THEN 7
			                                                                 WHEN PURCHASE_TB.DCCODE = '1000' THEN 8
			                                                                 WHEN PURCHASE_TB.DCCODE = '2900' THEN 9
			                                                                 ELSE 10
			                                                               END
			                                                               )
					                                                  ) AS LASTBUYERKEY																				/* 수급담당(최종) */
			                       ,MAX(PURCHASE_TB.CUSTKEY) KEEP (DENSE_RANK FIRST ORDER BY (
			                                                               CASE 
			                                                                 WHEN PURCHASE_TB.DCCODE = '2600' THEN 1
			                                                                 WHEN PURCHASE_TB.DCCODE = '2650' THEN 2
			                                                                 WHEN PURCHASE_TB.DCCODE = '2660' THEN 3
			                                                                 WHEN PURCHASE_TB.DCCODE = '2620' THEN 4
			                                                                 WHEN PURCHASE_TB.DCCODE = '2630' THEN 5
			                                                                 WHEN PURCHASE_TB.DCCODE = '2260' THEN 6
			                                                                 WHEN PURCHASE_TB.DCCODE = '2230' THEN 7
			                                                                 WHEN PURCHASE_TB.DCCODE = '1000' THEN 8
			                                                                 WHEN PURCHASE_TB.DCCODE = '2900' THEN 9
			                                                                 ELSE 10
			                                                               END
			                                                               )
					                                                  ) AS CUSTKEY																					/* 고객코드 */
			                       ,NVL(MAX(PURCHASE_TB.MOQ_VENDER) KEEP (DENSE_RANK FIRST ORDER BY (
				                                                               CASE 
				                                                                 WHEN PURCHASE_TB.MOQ_VENDER IS NULL  THEN 9999
				                                                                 WHEN PURCHASE_TB.DCCODE = '2600' THEN 1
				                                                                 WHEN PURCHASE_TB.DCCODE = '2650' THEN 2
				                                                                 WHEN PURCHASE_TB.DCCODE = '2660' THEN 3
				                                                                 WHEN PURCHASE_TB.DCCODE = '2620' THEN 4
				                                                                 WHEN PURCHASE_TB.DCCODE = '2630' THEN 5
				                                                                 WHEN PURCHASE_TB.DCCODE = '2260' THEN 6
				                                                                 WHEN PURCHASE_TB.DCCODE = '2230' THEN 7
				                                                                 WHEN PURCHASE_TB.DCCODE = '1000' THEN 8
				                                                                 WHEN PURCHASE_TB.DCCODE = '2900' THEN 9
				                                                                 ELSE 10
				                                                               END
				                                                               )
					                                                  	), 0) AS MOQ_VENDER																			/* MOQ(업체단위) */
			                       ,NVL(MAX(PURCHASE_TB.LEADTIME) KEEP (DENSE_RANK FIRST ORDER BY (
			                                                               CASE 
			                                                                 WHEN PURCHASE_TB.LEADTIME IS NULL      THEN 9999
			                                                                 WHEN PURCHASE_TB.DCCODE = '2600' 		THEN 1
			                                                                 WHEN PURCHASE_TB.DCCODE = '2650' 		THEN 2
			                                                                 WHEN PURCHASE_TB.DCCODE = '2660' 		THEN 3
			                                                                 WHEN PURCHASE_TB.DCCODE = '2620' 		THEN 4
			                                                                 WHEN PURCHASE_TB.DCCODE = '2630' 		THEN 5
			                                                                 WHEN PURCHASE_TB.DCCODE = '2260' 		THEN 6
			                                                                 WHEN PURCHASE_TB.DCCODE = '2230' 		THEN 7
			                                                                 WHEN PURCHASE_TB.DCCODE = '1000' 		THEN 8
			                                                                 WHEN PURCHASE_TB.DCCODE = '2900' 		THEN 9
			                                                                 ELSE 10
			                                                               END
			                                                               )
			                                                  		  ),0) AS LEADTIME																				/* 리드타임         */
			                       ,MAX(PURCHASE_TB.PURCHASE_IN)           																	AS PURCHASE_IN	    	/* 수발주IN   */
			                       ,MAX(PURCHASE_TB.PURCHASE_OUT)          																	AS PURCHASE_OUT			/* 수발주OUT  */
			                       ,MAX(ST_TB.STOCKIN)					   																	AS STOCKIN				/* 재고 IN    */
			                       ,DECODE(MAX(ST_TB.STOCKOUT), #{yyyymm}||#{lastday}, '', MAX(ST_TB.STOCKOUT))	                    		AS STOCKOUT				/* 재고OUT   */
			                       ,MAX(BRAND_TB.CUSTKEY)                        															AS PARENTCUSTKEY        /* 본점코드         */
			                       
-- 8) 기존 컬럼 구문 주석 처리
--                            ,MAX(BRAND_TB.DESCRIPTION)                                                   AS PARENTCUSTNAME       /* 본점 */ 
-- 9) ■ 2025.12.31 2번 라인에서 스칼라 서브 쿼리 주석 부분을 해당 라인으로 이동 시킴 
                            	   , MAX(CASE 
                            	   			WHEN BRAND_TB.PARENTCUSTKEY IS NULL 
                            	   			THEN BRAND_TB.DESCRIPTION 
                                         ELSE (SELECT A.DESCRIPTION FROM LOGISONE.MS_CUST A WHERE A.CUSTKEY = BRAND_TB.PARENTCUSTKEY  AND ROWNUM = 1) END)   AS PARENTCUSTNAME /* 본점 */ 
			                       
			                       ,MAX(BRAND_TB.REFERENCE02)                        														AS BRANDNAME_FC         /* 브랜드마스터   */
			                       ,NVL(MAX(STO_TB.STO_IN_QTY), 0) 																			AS STO_IN_QTY         	/* 총이체 입고량 */      
								   ,NVL(MAX(STO_TB.STO_OUT_QTY), 0) 																		AS STO_OUT_QTY       	/* 총이체 출고량 */
								   ,NVL(MAX(T_TB.TURNOVERDAY), 0) 																			AS TURNOVERDAY        /* 재고 회전일 */
			                FROM  PURCHASE_TB
			                <if test='chkyn == "Y"'>
				                LEFT OUTER JOIN ST_TB
				                  ON ST_TB.STORERKEY = PURCHASE_TB.STORERKEY
				                 AND ST_TB.SKU       = PURCHASE_TB.SKU
			                </if>
			                <if test='chkyn == "N"'>
				                FULL OUTER JOIN ST_TB
				                  ON ST_TB.STORERKEY = PURCHASE_TB.STORERKEY
				                 AND ST_TB.SKU       = PURCHASE_TB.SKU
			                </if>
			                LEFT OUTER JOIN MS_SKU
			                  ON MS_SKU.STORERKEY = COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY)
			                 AND MS_SKU.SKU       = COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
			                LEFT OUTER JOIN BRAND_TB
			                  ON BRAND_TB.SKU = COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
			                LEFT OUTER JOIN MS_SKUCHAIN
			                  ON MS_SKUCHAIN.STORERKEY = COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY)
			                 AND MS_SKUCHAIN.SKU       = COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
			                 AND MS_SKUCHAIN.DEL_YN    = 'N'
			                LEFT OUTER JOIN (
				                SELECT    
								     MS_SKU.SKU               AS SKU             /* 상품코드*/
								    ,MDPL1.STORERKEY          AS STORERKEY    
								    ,MDPL1.DCCODE             AS DCCODE          /* 센터코드*/   
								    ,MDPL1.CUSTKEY            AS CUSTKEY         /* 협력사코드*/         
								    ,MS_SKU.DESCRIPTION       AS DESCRIPTION     /* 기본 제품명 */   
								    ,MDPL1.BOXPERLAYER * MDPL1.LAYERPERPLT AS PLTCNT         /* PLT 수 */
								FROM LOGISONE.MS_DC_PLT_LOAD MDPL1
								JOIN MS_SKUCHAIN ON
								    MS_SKUCHAIN.SKU = MDPL1.SKU
								    AND MS_SKUCHAIN.STORERKEY = MDPL1.STORERKEY
								JOIN MS_SKU ON
								    MS_SKU.SKU = MDPL1.SKU
								    AND MS_SKU.STORERKEY = MDPL1.STORERKEY
								WHERE MDPL1.STORERKEY = 'FW00'
								  
								UNION ALL
								SELECT    
								     MS_SKU.SKU               AS SKU             /* 상품코드*/
								    ,MS_SKU.STORERKEY         AS STORERKEY
								    ,NULL                     AS DCCODE          /* 센터코드 없음 */   
								    ,NULL                     AS CUSTKEY         /* 협력사코드 없음 */         
								    ,MS_SKU.DESCRIPTION       AS DESCRIPTION     /* 기본 제품명 */   
								    ,(MS_SKUCHAIN.BOXPERPLT)  AS PLTCNT
								FROM MS_SKUCHAIN
								JOIN MS_SKU ON
								    MS_SKU.SKU = MS_SKUCHAIN.SKU
								    AND MS_SKU.STORERKEY = MS_SKUCHAIN.STORERKEY
								WHERE MS_SKUCHAIN.STORERKEY = 'FW00'					  
								  AND NOT EXISTS (
								        SELECT 1 
								        FROM LOGISONE.MS_DC_PLT_LOAD M
								        WHERE M.STORERKEY = MS_SKUCHAIN.STORERKEY
										  AND M.SKU       = MS_SKUCHAIN.SKU
								    )
				            ) T_PLT
				            	ON  T_PLT.SKU       = COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
				            	AND T_PLT.STORERKEY = COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY)
			                LEFT JOIN CM_CODE CD2
							  ON 1=1
							 AND CD2.CODELIST  = 'STORAGETYPE'
							 AND CD2.BASECODE  = MS_SKU.STORAGETYPE 
							LEFT JOIN CM_CODE CD3
							  ON CD3.STORERKEY = MS_SKU.STORERKEY
							 AND CD3.CODELIST  = 'SKUTYPE'
							 AND CD3.BASECODE  = MS_SKU.SKUTYPE
							LEFT JOIN MS_SKUSPEC SKUSPEC1
							  ON SKUSPEC1.STORERKEY     = MS_SKU.STORERKEY
							 AND SKUSPEC1.SPECCATEGORY  = 'SKUGROUP'
							 AND SKUSPEC1.SPECCODE  	= SUBSTR(MS_SKU.SKUGROUP, 1, 2)
							LEFT OUTER JOIN STO_INOUT_TB STO_TB
								ON  STO_TB.STORERKEY = COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY)
								AND STO_TB.SKU 		 = COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
							LEFT OUTER JOIN TURNOVER_TB T_TB
							    ON  T_TB.STORERKEY 	= COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY)
							    AND T_TB.SKU 		= COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
			                 
			                WHERE  1=1
			                	AND  MS_SKU.STORERKEY = 'FW00'
			                <if test='storagetype != null and storagetype != ""'>
			                	AND  MS_SKU.STORAGETYPE = #{storagetype}
			                </if>
			                <if test='reference15 != null and reference15 != ""'>
			                	AND  MS_SKU.REFERENCE15 = #{reference15}
			                </if>
			                <if test='parentCustkeyMulti != null and parentCustkeyMulti != ""'>
						        <trim prefix="AND (" suffix=")" prefixOverrides="OR">
					                <foreach collection="parentCustkeyMulti" item="item">
					                    OR BRAND_TB.CUSTKEY IN
					                    <foreach collection="item" item="code" open="(" close=")" separator=",">
					                        #{code}
					                    </foreach>
					                </foreach>
					            </trim>
			                </if>
			                GROUP BY COALESCE(PURCHASE_TB.STORERKEY, ST_TB.STORERKEY), COALESCE(PURCHASE_TB.SKU, ST_TB.SKU)
			            )T1
			         LEFT OUTER JOIN MS_CUST_SECOND
            		   ON  MS_CUST_SECOND.STORERKEY = T1.STORERKEY
           			   AND MS_CUST_SECOND.CUSTKEY = T1.CUSTKEY
           			   AND MS_CUST_SECOND.SKU = T1.SKU
           			   AND MS_CUST_SECOND.DEL_YN = 'N'
 	                 LEFT JOIN CM_CODE CD1
				   		ON  CD1.STORERKEY  IN ('%','STD','',T1.STORERKEY)
				   		AND CD1.CODELIST  = 'BUYERKEY'
				   		AND CD1.BASECODE  = T1.LASTBUYERKEY
           			   
    				 
			     )T2
			  WHERE  1=1
			  	<if test='stockYn != null and stockYn != ""'>
			  		AND ((#{stockYn} = 'N' AND T2.QTY_TOTAL = 0) OR (#{stockYn} = 'Y' AND T2.QTY_TOTAL > 0))
			  	</if>
			 )T3
		WHERE  1=1
	</select>
    
</mapper>