package cjfw.wms.webservice.exDCTCS;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the XML-WS Tools.
 * Generated source version: 3.0
 * 
 */
@WebService(targetNamespace = "urn://scm.cjfreshway.co.kr/TCS", name = "SI_SCM0540_SCM_SO")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SISCM0540SCMSO {

    @WebMethod(operationName = "SI_SCM0540_SCM_SO", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_SCM0540_SCM_response", targetNamespace = "urn://scm.cjfreshway.co.kr/TCS", partName = "MT_SCM0540_SCM_response")
    public DTSCM0540SCMResponse siSCM0540SCMSO(

        @WebParam(partName = "MT_SCM0540_SCM", name = "MT_SCM0540_SCM", targetNamespace = "urn://scm.cjfreshway.co.kr/TCS")
        DTSCM0540SCM mtSCM0540SCM
    );
}


//@WebService(name = "SI_SCM0540_SCM_SO", targetNamespace = "urn://scm.cjfreshway.co.kr/TCS")
//@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
//@XmlSeeAlso({
//    ObjectFactory.class
//})
//public interface SISCM0540SCMSO {
//
//
//    /**
//     * 
//     * @param mtSCM0540SCM
//     * @return
//     *     returns kr.co.cjfreshway.scm.tcs.DTSCM0540SCMResponse
//     */
//    @WebMethod(operationName = "SI_SCM0540_SCM_SO", action = "http://sap.com/xi/WebService/soap1.1")
//    @WebResult(name = "MT_SCM0540_SCM_response", targetNamespace = "urn://scm.cjfreshway.co.kr/TCS", partName = "MT_SCM0540_SCM_response")
//    public DTSCM0540SCMResponse siSCM0540SCMSO(
//        @WebParam(name = "MT_SCM0540_SCM", targetNamespace = "urn://scm.cjfreshway.co.kr/TCS", partName = "MT_SCM0540_SCM")
//        DTSCM0540SCM mtSCM0540SCM);
//
//}
