cf:
  jwt:
    enable: true
    accessExpTime: 1800000 # 600000(10분), 1800000(30분)
    accessHeaderKey: 'X-CF-AccessToken'
    refreshExpTime: 43200000 # 43200000(12시간), 604800000(1주), 864000000(10일)
    refreshHeaderKey: 'X-CF-RefreshToken'
    secretPlainText : ENC(1hAN/YJmIomnzTIVbu6KvTudMoh1T8JV3nuKmvm8Jrf5Z8zhGf1qzxWMvCRhpExF)
