<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<!--
 * Copyright 2025. CJ OliveNetworks Co. all rights reserved.
 *
 * @author      : KimDongHan (liop0123@cj.net)
 * @date        : 2025.10.17
 * @description : 출고 > 출고 > 배송 라벨 출력(예외 기준 적용) SQL
 * @issues      :
--> 
<mapper namespace="wdDeliveryLabelForceService">

	<select id="getMasterT1List" resultType="cjfw.wms.wd.dto.WdDeliveryLabelForceResT1Dto">
	   WITH PRE_CLOSING_CENTER AS (
            SELECT BASECODE AS DCCODE
                 , DATA1 AS PRE_CLOSING_TIME    --1500 시분
              FROM CM_CODE
             WHERE CODELIST = 'PRE_CLOSING_CENTER'
               AND BASECODE = #{dccode}
        )  ,
        SO_SUM_QTY AS (
            SELECT SOKEY, SOLINE, WD_DCCODE, SUM(MOVE_QTY) AS MOVE_QTY
                            FROM  OM_SDY_REGN_REPL_D
                            GROUP BY SOKEY, SOLINE, WD_DCCODE
        )    
		SELECT /* [WdDeliveryLabelForceService.sqlx][WdDeliveryLabelForceService.getMasterT1List][출고 > 출고 > 배송 라벨 출력(예외 기준 적용)_분류표출력_탭 조회][KimDongHan][2025-10-17] */
			   TBL.DCCODE                                                                                                                    AS DCCODE                 /* 물류센터코드 */
			 , FN_GETDCNAME(TBL.DCCODE)                                                                                                      AS DCNAME                 /* 01. 물류센터 */
			 , TBL.TO_CUSTKEY                                                                                                                AS TO_CUSTKEY             /* 02. 관리처코드  */
			 , TBL.LBL_CUSTNAME1                                                                                                             AS LBL_CUSTNAME1          /* 03. 납품처명1 */
			 , TBL.LBL_CUSTNAME2                                                                                                             AS LBL_CUSTNAME2          /* 04. 납품처명2 */
			 , TBL.LBL_SKU                                                                                                                   AS LBL_SKU                /* 05. 상품코드 */
			 , TBL.LBL_SKU                                                                                                                   AS SKU                    /* 05. 상품코드 */
			 , TBL.LBL_SKUNAME1                                                                                                              AS LBL_SKUNAME1           /* 06. 상품명1 */
			 , TBL.LBL_SKUNAME2                                                                                                              AS LBL_SKUNAME2           /* 07. 상품명2 */
			 , TBL.LBL_QTY                                                                                                                   AS LBL_QTY                /* 08. 수량 */
			 , TBL.LBL_QTY_2                                                                                                                 AS LBL_QTY_2              /* 09. 수량2 */
			 , TBL.LBL_PAGENO1                                                                                                               AS LBL_PAGENO1            /* 10. 차량번호 */
			 , TBL.LBL_CARGROUP                                                                                                              AS LBL_CARGROUP           /* 11. 출차조 */
			 , TBL.LBL_DELIVERYGROUP                                                                                                         AS LBL_DELIVERYGROUP      /* 12. POP */
			 , TBL.LBL_DELIVERYGROUP_CHG                                                                                                     AS LBL_DELIVERYGROUP_CHG  /* 13. POP2 */
			 , TBL.LBL_MEMO                                                                                                                  AS LBL_MEMO               /* 14. 특이사항 */
			 , TBL.LBL_LOC                                                                                                                   AS LBL_LOC                /* 15. 로케이션 */
			 , (SELECT FN_CODEDESCR(#{gStorerkey} , 'MS_SKUDCLABEL_STORAGE', TBL.REAL_STORAGE_GUBUN) FROM DUAL)                              AS LBL_REAL_STORAGETYPE   /* 16. 저장조건(실제) MS_SKUDCLABEL.STORAGE_GUBUN */
			 , (SELECT FN_CODEDESCR(#{gStorerkey} , 'STORAGETYPE', TBL.STORAGETYPE)  FROM DUAL)                                              AS LBL_STORAGETYPE        /* 16. 저장조건 MS_SKU.STORAGETYPE */
			 , (SELECT MAX(CM_CODE.DATA1) FROM CM_CODE WHERE CM_CODE.CODELIST = 'STORAGETYPE' AND CM_CODE.BASECODE = TBL.STORAGETYPE)        AS LBL_STORAGETYPE_1      /* 17. 저장조건1 */
			 , (SELECT MAX(CM_CODE.DATA2) FROM CM_CODE WHERE CM_CODE.CODELIST = 'STORAGETYPE' AND CM_CODE.BASECODE = TBL.STORAGETYPE)        AS LBL_STORAGETYPE_2      /* 18. 저장조건2 */
			 , TBL.LBL_DELIVERYDT                                                                                                            AS LBL_DELIVERYDT         /* 19. 배송일자 */
			 , NVL(SUBSTR(B.FROM_CUSTNAME , 1, 30), SUBSTR(NVL(TBL.LBL_FROM_CUSTNAME, ' '), 1, 30))                                          AS LBL_FROM_CUSTNAME      /* 20. 업체명 */
			 , NVL(B.CARNO, ' ')                                                                                                             AS LBL_FROM_CARNAME       /* 21. 배송차량명 */
			 , TBL.LBL_PAGENO2                                                                                                               AS LBL_PAGENO2            /* 22. 페이지번호 */
			 , TBL.LBL_BARCODETXT                                                                                                            AS LBL_BARCODETXT         /* 23. 바코드텍스트 */
			 , TBL.LBL_BARCODE1                                                                                                              AS LBL_BARCODE1           /* 24. 바코드1 */
			 , TBL.LBL_BARCODE2                                                                                                              AS LBL_BARCODE2           /* 25. 바코드2 */
			 , TBL.LBL_SMS_YN                                                                                                                AS LBL_SMS_YN             /* 26. Sorter대상 */
			 , TBL.PICK_NO                                                                                                                   AS PICK_NO                /* 27. 피킹번호 */
			 , TBL.PICK_BATCH_NO                                                                                                             AS PICK_BATCH_NO          /* 28. 대배치키 */
			 , TBL.LBL_MEMO_OFN                                                                                                              AS LBL_MEMO_OFN           /* 29. 온푸비고란 */
			 , CASE WHEN TBL.LBL_TITLE = 'STO' 
			        THEN RTRIM(TO_CHAR(FLOOR(TBL.STO_QTY1 / TBL.QTYPERBOX),'FM99999999999990.99999'),'.') || 'BOX/'
			             ||RTRIM(TO_CHAR(MOD(TBL.STO_QTY1 , TBL.QTYPERBOX),'FM99999999999990.99999'),'.') ||'EA'
             <!--       ELSE TO_CHAR(FLOOR(SUM(TBL.PROCESSQTY) OVER(PARTITION BY TBL.PICK_NO, TBL.LBL_SKU) / TBL.QTYPERBOX)) || 'BOX/' 
                         || TO_CHAR(MOD(SUM(TBL.PROCESSQTY) OVER(PARTITION BY TBL.PICK_NO, TBL.LBL_SKU), TBL.QTYPERBOX)) || 'EA' END -->
                    ELSE TBL.LBL_QTY1 END                                                                                                    AS LBL_STOQTY             /* 30. 타센터 sto 수량 */
			 , TBL.LBL_MARKWORD                                                                                                              AS LBL_MARKWORD           /* 31. 특별관리고객표기 */			 
			 , TBL.LBL_MANUDATE                                                                                                              AS LBL_MANUDATE           /* LBL_MANUDATE  */			 
			 , TBL.LBL_PLACEOFORIGIN                                                                                                         AS LBL_PLACEOFORIGIN      /* LBL_PLACEOFORIGIN */
			 , TBL.LBL_ROUTENAME                                                                                                             AS LBL_ROUTENAME          /* LBL_ROUTENAME */
			 , NVL(TBL.STORAGE_GUBUN, ' ')	                                                                                                 AS STORAGE_GUBUN          /* STORAGE_GUBUN */
			 , DECODE(TBL.LBL_LOC, NULL, 2, 'STD', 2, 1)                                                                                     AS LOC_YN                 /* LOC_YN */
			 , TBL.INVOICESORT                                                                                                               AS INVOICESORT            /* INVOICESORT */
			 , TBL.SKUPRIORITY                                                                                                               AS SKUPRIORITY            /* SKUPRIORITY */
			 , TBL.PREDELIVERYGROUP                                                                                                          AS PREDELIVERYGROUP       /* PREDELIVERYGROUP */
			 , TBL.PRINT_YN                                                                                                                  AS PRINT_YN               /* PRINT_YN */
			 , TBL.LBL_ETC_MSG                                                                                                               AS LBL_ETC_MSG            /* LBL_ETC_MSG */
			 , TBL.DELIVERYGROUP_SEQ                                                                                                         AS DELIVERYGROUP_SEQ      /* DELIVERYGROUP_SEQ */
			 , TBL.LBL_FOLABEL_YN                                                                                                            AS LBL_FOLABEL_YN         /* LBL_FOLABEL_YN */
             , TBL.PRE_CLOSING_TIME 
             , TBL.ADDDATE
             , TBL.LBL_DCNAME  ||'/'|| CASE WHEN TBL.PRE_CLOSING_TIME >= TO_CHAR(TBL.ADDDATE,'HH24MI')  
                                            THEN '선마감'
                                            ELSE '본마감' END                                                                                  AS LBL_DCNAME
			 , TBL.LBL_TITLE                                                                                                                 AS LBL_TITLE              /* LBL_TITLE */
			 , TBL.LBL_PAGENO3                                                                                                               AS LBL_PAGENO3
			 , TBL.LBL_QTY1                                                                                                                  AS LBL_QTY1
			 , TBL.LBL_STORAGETYPE1                                                                                                          AS LBL_STORAGETYPE1 
		  FROM (SELECT  /*+ NO_MERGE */
						MAX(WD_INVOICE.DCCODE)                                                                                               AS DCCODE	 
					  , MAX(WD_INVOICE.SLIPDT)                                                                                               AS LBL_MANUDATE     
					  , MAX(CASE WHEN TRUNC(MONTHS_BETWEEN(SYSDATE,MS_CUST.ADDDATE)) = 0 OR MS_CUSTDLVINFO.QCTYPE = 'Y' THEN '(R)' END) 
						  ||CASE WHEN MAX(DM_DOCUMENT_H.B2C_YN)='Y' THEN SUBSTR(MAX(NVL(DM_DOCUMENT_H.TO_CUSTNAME,MS_CUST.DESCRIPTION)),1,30)  
								 ELSE SUBSTR(MAX(NVL(MS_CUST.DESCRIPTION,DM_DOCUMENT_H.TO_CUSTNAME)),1,30) END AS LBL_CUSTNAME1    
					  , MAX(CASE WHEN MS_SKU.QTYPERBOX > 1 THEN '( '||TO_CHAR(MS_SKU.QTYPERBOX)||MS_SKU.BASEUOM||'/BOX )' ELSE UNISTR('') END) AS LBL_CUSTNAME2     
					  , REPLACE(FN_CONV_SKUBCRNAME(MAX(MS_SKU.DESCRIPTION),1),'~','-')                                                         AS LBL_SKUNAME1            
					  , REPLACE(FN_CONV_SKUBCRNAME(MAX(MS_SKU.DESCRIPTION),2),'~','-')                                                         AS LBL_SKUNAME2            
					  , CASE WHEN NVL(MAX(SO_SUM_QTY.MOVE_QTY),0) > 0   THEN MAX(SO_SUM_QTY.MOVE_QTY) || MAX(DM_DOCUMENT_D.STORERUOM)
					         ELSE RTRIM(TO_CHAR(MAX(WD_INVOICE.CONFIRMQTY) * MAX(DM_DOCUMENT_D.BUNMO) / MAX(DM_DOCUMENT_D.BUNJA),'FM99999999999990.99999'),'.')||MAX(DM_DOCUMENT_D.STORERUOM)
					         END                                                                                                               AS LBL_QTY                          
					  , ''                                                                                                                                                          AS LBL_QTY_2 
					  , MAX(WD_INPLAN.CARNO)                                                                                                                                        AS LBL_PAGENO1                      
					  , CASE WHEN MAX(CM_CAR.CARGROUP) IS NULL  
							 THEN NVL((SELECT MAX(CONVCODE) 
										 FROM CM_CODE A  
										WHERE A.CODELIST  = 'DEFAULTCARGROUP'  
										  AND A.BASECODE  = #{dccode}
										  AND A.STORERKEY = #{gStorerkey} 
										  AND A.DEL_YN    = 'N'), 'NODATA') 
							 ELSE FN_CODEDESCR(#{gStorerkey},'CARGROUP', MAX(CM_CAR.CARGROUP))  
							 END                                                                                                                                                    AS LBL_CARGROUP		 
					  , DECODE(FN_DESCR_CODE(MAX(MS_SKU.STORERKEY),'COUNTRY',MAX(MS_SKU.COUNTRYOFORIGIN)) ,'NOT FOUND','','FW' 
						||LEFT(FN_DESCR_CODE(MAX(MS_SKU.STORERKEY),'COUNTRY',MAX(MS_SKU.COUNTRYOFORIGIN)),1)||MAX(MS_SKU.COUNTRYOFORIGIN))                                          AS LBL_PLACEOFORIGIN  
					  , MAX(WD_INVOICE.SLIPDT)                                                                                                                                      AS LBL_DELIVERYDT     
					  , CASE WHEN MAX(DM_DOCUMENT_H.B2C_YN) = 'Y'  
							 THEN MAX(TM_INPLAN.DELIVERYGROUP) || CASE WHEN CORE_CM_STRATEGY.FN_ISINVOICEUSEROTAINERNO(MAX(DM_DOCUMENT_D.DCCODE),MAX(DM_DOCUMENT_D.STORERKEY)) = 'Y'  
																	   THEN '-' || NVL(MAX(WD_INPLAN.MIXBOXKEY), UNISTR('0'))  
																		END 
							 ELSE MAX(WD_INPLAN.DELIVERYGROUP) || CASE WHEN CORE_CM_STRATEGY.FN_ISINVOICEUSEROTAINERNO(MAX(DM_DOCUMENT_D.DCCODE),MAX(DM_DOCUMENT_D.STORERKEY)) = 'Y'  
																	   THEN '-' || NVL(MAX(WD_INPLAN.MIXBOXKEY), UNISTR('0'))  
																		END 
							  END                                                                                                                                                   AS LBL_DELIVERYGROUP 
					  , MAX(NVL(MS_CUST.DESCRIPTION, ' '))                                                                                                                          AS LBL_FROM_CUSTNAME				       
					  , CASE WHEN NVL(MAX(SO_SUM_QTY.MOVE_QTY),0) > 0 
                          THEN CASE WHEN OM_SDY_REGN_REPL_D.WD_DCCODE IN ('2620', '2250') AND MAX(WD_INVOICE.DLV_DATA03) = 'CROSS' 
                                    THEN DECODE(#{crossDc},'', MAX(MS_SKUDCSET_STO.LOC), MAX(MS_SKUDCSET_CROSS.LOC))
                                    WHEN OM_SDY_REGN_REPL_D.WD_DCCODE NOT IN ('2620','2250') 
                                    THEN  DECODE(#{crossDc},'', MAX(MS_SKUDCSET_STO.LOC), MAX(MS_SKUDCSET_CROSS.LOC))
                                    ELSE MAX(MS_SKUDCSET_STO.LOC)
                                END 
                          ELSE CASE WHEN MAX(DM_DOCUMENT_D.DCCODE) IN ('2620', '2250') AND MAX(WD_INVOICE.DLV_DATA03) = 'CROSS'  
                                    THEN DECODE(#{crossDc} ,'',MAX(MS_SKUDCSET.LOC) ,MAX(MS_SKUDCSET_CROSS.LOC))  
                                    WHEN MAX(DM_DOCUMENT_D.DCCODE) NOT IN ( '2620', '2250' )  
                                    THEN DECODE(#{crossDc},'',MAX(MS_SKUDCSET.LOC),MAX(MS_SKUDCSET_CROSS.LOC))  
                                    ELSE MAX(MS_SKUDCSET.LOC) 
                                END 
                          END                                                                                                                                                       AS LBL_LOC           
					  , MAX(NVL(WD_INVOICE.PAGE_NO,' '))                                                                                                                            AS LBL_PAGENO2       
					  , MAX(NVL(WD_INPLAN.SKU,' '))                                                                                                                                 AS LBL_SKU           
					  , MAX(NVL(WD_INVOICE.ROUTE,' '))                                                                                                                              AS LBL_ROUTENAME     
					  , FN_FORMAT_MASK( WD_INVOICE.INVOICENO,'########## #################### ######## ############ ######')                                                        AS LBL_BARCODETXT   
					  , WD_INVOICE.INVOICENO                                                                                                                                        AS LBL_BARCODE1      
					  , CASE WHEN FN_CODEVALUE(#{gStorerkey} , 'BIGOLABEL_CUST', MAX(DM_DOCUMENT_H.MNGPLC_ID), 'BASECODE') IS NOT NULL 
							 THEN UNISTR('') 
							 ELSE WD_INVOICE.INVOICENO 
							  END                                                                                                                                                   AS LBL_BARCODE2 
					  , CASE WHEN FN_CODEVALUE(#{gStorerkey} , 'BIGOLABEL_CUST', MAX(DM_DOCUMENT_H.MNGPLC_ID), 'BASECODE') IS NOT NULL 
							 THEN SUBSTR(LTRIM(MAX(DM_DOCUMENT_D.REQUESTMEMO)), 0, 15) 
							 ELSE UNISTR('') 
							  END                                                                                                                                                   AS LBL_MEMO_OFN 
					  , FN_CODEDESCR(MAX(MS_SKU.STORERKEY), 'STORAGETYPE', MAX(MS_SKU.STORAGETYPE))                                                                                 AS LBL_STORAGETYPE 
					  , MAX(MS_SKU.STORAGETYPE)                                                                                                                                     AS STORAGETYPE   
					  , CASE WHEN MIN(WD_INVOICE.PRINT_CNT) > 1  
							 THEN DECODE(MAX(WD_INVOICE.LABELSTATUS),'M','물량변경',UNISTR(''))  
							 ELSE UNISTR('')  
							  END|| 
						CASE WHEN MAX(WD_INVOICE.DCCODE) = '2260' AND MIN(WD_INVOICE.PRINT_CNT) > 1 AND  
								  MAX(NVL(TM_INPLAN.PREDELIVERYGROUP,' '))  <![CDATA[<>]]>  ' ' AND  
								  MAX(NVL(TM_INPLAN.PREDELIVERYGROUP,' '))  <![CDATA[<>]]>  MAX(NVL(WD_INPLAN.DELIVERYGROUP,' '))  
							 THEN MAX(NVL(TM_INPLAN.PREDELIVERYGROUP,' ')) ||'>' 
							 ELSE UNISTR('')  
							  END|| 
						CASE WHEN MAX(WD_INVOICE.DCCODE) = '2600' AND MAX(DM_DOCUMENT_D.PLANT) = '2600' AND  
								  MAX(MS_CUSTDLVINFO.DISTANCETYPE) IN ('JC','WR') THEN UNISTR(' 거래처별>> ') 
								  ||FN_ROLLTAINER(MAX(WD_INVOICE.DCCODE), MAX(WD_INVOICE.STORERKEY), MAX(DM_DOCUMENT_H.TO_CUSTTYPE) 
												, MAX(DM_DOCUMENT_H.TO_CUSTKEY), MAX(WD_INVOICE.SLIPDT), MAX(WD_INPLAN.DELIVERYGROUP),MAX(TM_INPLAN.PRIORITY)) ELSE UNISTR('') 
							  END                                                                                                                                                   AS LBL_MEMO		               
					  , SUBSTR(WD_INVOICE.INVOICENO,0,19)||SUBSTR(WD_INVOICE.INVOICENO,26,3)                                                                                        AS INVOICESORT 
					  , NVL(MAX(MS_SKUDCSET.OTHER01),'5')                                                                                                                           AS SKUPRIORITY 
					  , MAX(DM_DOCUMENT_H.TO_CUSTKEY)                                                                                                                               AS TO_CUSTKEY 
					  , MAX(TM_INPLAN.PREDELIVERYGROUP)                                                                                                                             AS PREDELIVERYGROUP 
					  , MAX(WD_INVOICE.PRINT_YN)	                                                                                                                                AS PRINT_YN 
					  , CASE WHEN LEFT(MAX(MS_SKU.SKUGROUP),2) IN ('20','30','40')  
							 THEN UNISTR('본 배송분류표는 식품위생법상의 고지사항과는 무관합니다.') 
							 ELSE UNISTR('본 배송분류표는 관련법상의 고지사항과는 무관합니다.') 
							 END                                                                                                                                                    AS LBL_ETC_MSG 
					  , SUBSTR(MAX(WD_INPLAN.DELIVERYGROUP),2,LENGTH(MAX(WD_INPLAN.DELIVERYGROUP)))                                                                                 AS DELIVERYGROUP_SEQ 
					  , NVL(MAX(MS_SKUDCSET.SMS_YN),'N')                                                                                                                            AS LBL_SMS_YN 
					  , CASE WHEN MAX(WD_INVOICE.DCCODE) = '2260' AND  
								  MIN(WD_INVOICE.PRINT_CNT) > 1 AND MAX(NVL(TM_INPLAN.PREDELIVERYGROUP,' '))  <![CDATA[<>]]>  ' ' AND  
								  MAX(NVL(TM_INPLAN.PREDELIVERYGROUP,' '))  <![CDATA[<>]]>  MAX(NVL(WD_INPLAN.DELIVERYGROUP,' '))  
							 THEN MAX(NVL(TM_INPLAN.PREDELIVERYGROUP,' ')) ||'>' 
							 ELSE UNISTR('')  
							 END||MAX(WD_INPLAN.DELIVERYGROUP)||CASE WHEN CORE_CM_STRATEGY.FN_ISINVOICEUSEROTAINERNO(MAX(DM_DOCUMENT_D.DCCODE),MAX(DM_DOCUMENT_D.STORERKEY)) = 'Y'  
																	 THEN '-'||NVL(MAX(WD_INPLAN.MIXBOXKEY),UNISTR('0'))  
							 END                                                                                                                                                    AS LBL_DELIVERYGROUP_CHG  
					  , MAX(WD_TASK.PICK_NO)                                                                                                                                        AS PICK_NO                  
					  ,	MAX(WD_TASK.PICK_BATCH_NO)                                                                                                                                  AS PICK_BATCH_NO          
					  ,	MAX(WD_INVOICE.DOCNO)                                                                                                                                       AS DOCNO 
					  ,	MAX(WD_INVOICE.DOCLINE)                                                                                                                                     AS DOCLINE 
					  ,	MAX(MS_SKUDCLABEL.STORAGE_GUBUN)                                                                                                                            AS STORAGE_GUBUN 
					  ,	MAX(MS_SKUDCLABEL.STORAGE_GUBUN)                                                                                                                            AS REAL_STORAGE_GUBUN 
					  ,	DECODE(MAX(WD_TASK.LOC),'CROSS','Y','N')                                                                                                                    AS CROSS_YN 
					  ,	MAX(DM_DOCUMENT_D.STORERUOM)                                                                                                                                AS STORERUOM 
					  ,	SUM(WD_TASK.PROCESSQTY)                                                                                                                                     AS PROCESSQTY 
					  ,	NVL(MAX(MS_SKU.QTYPERBOX), 1)                                                                                                                               AS QTYPERBOX 
					  , FN_CODEVALUE(#{gStorerkey} , 'MARKWORD_SRM', MAX(MS_CUST_REDZONE_SRM.MARK_WORD), 'BASEDESCR')                                                               AS LBL_MARKWORD 
					  , CASE WHEN FN_CODEVALUE(#{gStorerkey} , 'FOLABEL_CUST', MAX(DM_DOCUMENT_H.MNGPLC_ID), 'BASECODE') IS NOT NULL 
							 THEN UNISTR('Y') 
							 ELSE UNISTR('N') 
						 END                                                                                                                                                        AS LBL_FOLABEL_YN 
					  , CASE WHEN NVL(MAX(SO_SUM_QTY.MOVE_QTY),0) > 0  
                             THEN FN_GETDCNAME(OM_SDY_REGN_REPL_D.WD_DCCODE)
                             ELSE FN_GETDCNAME(MAX(WD_INVOICE.DCCODE)) END                                                              AS LBL_DCNAME
                      , MAX(WD_TASK.ADDDATE)                                                                                            AS ADDDATE
                      , NVL(MAX(PRE_CLOSING_CENTER.PRE_CLOSING_TIME),'0000')                                                            AS PRE_CLOSING_TIME   																
					  , CASE WHEN NVL(MAX(SO_SUM_QTY.MOVE_QTY),0) > 0  
							 THEN 'STO' 
							 ELSE '총량피킹' END                                                                                          AS LBL_TITLE
					  , NVL(MAX(SO_SUM_QTY.MOVE_QTY),0)                                                                                 AS STO_QTY1		 
					  , NVL(FN_CODEDESCR(MAX(MS_SKUDCLABEL.STORERKEY),'MS_SKUDCLABEL_STORAGE', MAX(MS_SKUDCLABEL.STORAGE_GUBUN)), '')   AS LBL_STORAGETYPE1     
					  , NVL(MAX(B.CARNO),'')                                                                                            AS LBL_PAGENO3  
					  , MAX(NVL(LBL_QTY1.TOTALQTY,0))                                                                                   AS LBL_QTY1					  
                      , OM_SDY_REGN_REPL_D.WD_DCCODE                                                    AS WD_DCCODE
				   FROM WD_INVOICE					   
				   JOIN WD_INPLAN 
					 ON WD_INPLAN.DCCODE                 = WD_INVOICE.DCCODE 
					AND WD_INPLAN.STORERKEY              = WD_INVOICE.STORERKEY 
					AND WD_INPLAN.SLIPDT                 = WD_INVOICE.SLIPDT 
					AND WD_INPLAN.SLIPNO                 = WD_INVOICE.SLIPNO 
					AND WD_INPLAN.SLIPLINE               = WD_INVOICE.SLIPLINE 
					AND WD_INPLAN.DEL_YN                 = 'N' 
				   JOIN WD_TASK 
					 ON WD_TASK.DCCODE                   = WD_INVOICE.DCCODE 
					AND WD_TASK.STORERKEY                = WD_INVOICE.STORERKEY 
					AND WD_TASK.SLIPDT                   = WD_INVOICE.SLIPDT 
					AND WD_TASK.SLIPNO                   = WD_INVOICE.SLIPNO 
					AND WD_TASK.SLIPLINE                 = WD_INVOICE.SLIPLINE 
					AND WD_TASK.PICK_LIST_NO             = WD_INVOICE.PICK_LIST_NO 
					AND WD_TASK.PROCESSQTY    > 0 
					AND WD_TASK.TASKSYSTEM IS NOT NULL 
				<if test="pickBatchNo != null and pickBatchNo != ''">   AND WD_TASK.PICK_BATCH_NO LIKE #{pickBatchNo}||'%'  </if>		            
				<if test="pickNo != null and pickNo != ''">             AND WD_TASK.PICK_NO LIKE #{pickNo}||'%'             </if>	
				<if test="tasksystem != null and tasksystem != ''">     AND WD_TASK.TASKSYSTEM  = #{tasksystem}             </if>					            
				   JOIN DM_DOCUMENT_D 
					 ON DM_DOCUMENT_D.DCCODE             = WD_INVOICE.DCCODE 
					AND DM_DOCUMENT_D.STORERKEY          = WD_INVOICE.STORERKEY 
					AND DM_DOCUMENT_D.DOCTYPE            = WD_INVOICE.DOCTYPE 
					AND DM_DOCUMENT_D.DOCDT              = WD_INVOICE.DOCDT 
					AND DM_DOCUMENT_D.DOCNO              = WD_INVOICE.DOCNO 
					AND DM_DOCUMENT_D.DOCLINE            = WD_INVOICE.DOCLINE 
					AND DM_DOCUMENT_D.DELIVERYDATE       = WD_INVOICE.SLIPDT            
					AND DM_DOCUMENT_D.CHANNEL            = '1' 
					AND DM_DOCUMENT_D.DEL_YN             = 'N' 
				   JOIN DM_DOCUMENT_H                     
					 ON DM_DOCUMENT_H.DCCODE             = DM_DOCUMENT_D.DCCODE 
					AND DM_DOCUMENT_H.STORERKEY          = DM_DOCUMENT_D.STORERKEY 
					AND DM_DOCUMENT_H.DOCTYPE            = DM_DOCUMENT_D.DOCTYPE 
					AND DM_DOCUMENT_H.DOCDT              = DM_DOCUMENT_D.DOCDT 
					AND DM_DOCUMENT_H.DOCNO              = DM_DOCUMENT_D.DOCNO 
					AND DM_DOCUMENT_H.DELIVERYDATE       = DM_DOCUMENT_D.DELIVERYDATE  
					AND DM_DOCUMENT_H.DEL_YN             = 'N' 
				<if test="ordertype != null and ordertype != ''"> AND DM_DOCUMENT_H.ORDERTYPE  = #{ordertype} </if>
		        <!-- START.관리처멀티 -->
		        <if test="toCustkeyMulti != null and toCustkeyMulti != '' ">
					<trim prefix="AND (" suffix=")" prefixOverrides="OR">
						<foreach collection="toCustkeyMulti" item="item">
							OR DM_DOCUMENT_H.TO_CUSTKEY IN
							<foreach collection="item" item="code" open="(" close=")" separator=",">
								#{code} 	 
				      		</foreach>
				    	</foreach>
				  	</trim>			                                    
		        </if>
		        <!-- END.관리처멀티 -->					  
				   JOIN MS_SKU 
					 ON MS_SKU.STORERKEY                 = DM_DOCUMENT_D.STORERKEY 
					AND MS_SKU.SKU                       = DM_DOCUMENT_D.SKU 
					AND MS_SKU.DEL_YN                    = 'N' 
		        <!-- START.상품멀티 -->
		        <if test="skuMulti != null and skuMulti != '' ">
					<trim prefix="AND (" suffix=")" prefixOverrides="OR">
						<foreach collection="skuMulti" item="item">
							OR WD_INPLAN.SKU IN
							<foreach collection="item" item="code" open="(" close=")" separator=",">
								#{code} 	 
				      		</foreach>
				    	</foreach>
				  	</trim>			                                    
		        </if>
		        <!-- END.상품멀티 -->			            
				<if test="skugroup != null and skugroup != ''">       AND LEFT(MS_SKU.SKUGROUP,2) =  #{skugroup}    </if>
				<if test="storagetype != null and storagetype != ''"> AND MS_SKU.STORAGETYPE      =  #{storagetype} </if>				 
				   LEFT OUTER JOIN TM_INPLAN 
					 ON WD_INPLAN.DCCODE                 = TM_INPLAN.DCCODE 
					AND WD_INPLAN.DOCTYPE                = TM_INPLAN.DOCTYPE 
					AND WD_INPLAN.SLIPDT                 = TM_INPLAN.SLIPDT 
					AND WD_INPLAN.SLIPNO                 = TM_INPLAN.SLIPNO 
					AND WD_INPLAN.DEL_YN                 = 'N' 
				   LEFT OUTER JOIN MS_SKUDCSET 
					 ON MS_SKUDCSET.DCCODE               = DM_DOCUMENT_D.DCCODE 
					AND MS_SKUDCSET.STORERKEY            = DM_DOCUMENT_D.STORERKEY 
					AND MS_SKUDCSET.SKU                  = DM_DOCUMENT_D.SKU 
					AND MS_SKUDCSET.DEL_YN               = 'N' 
				   LEFT OUTER JOIN MS_SKUDCSET MS_SKUDCSET_CROSS 
					 ON MS_SKUDCSET_CROSS.DCCODE         = #{crossDc}
					 AND MS_SKUDCSET_CROSS.STORERKEY     = DM_DOCUMENT_D.STORERKEY    
					AND MS_SKUDCSET_CROSS.SKU            = DM_DOCUMENT_D.SKU    
					AND MS_SKUDCSET_CROSS.DEL_YN         = 'N'  
				   LEFT OUTER JOIN MS_CUST                  
					 ON MS_CUST.STORERKEY                = DM_DOCUMENT_H.STORERKEY 
					AND MS_CUST.CUSTTYPE                 = DM_DOCUMENT_H.TO_CUSTTYPE 
					AND MS_CUST.CUSTKEY                  = DECODE(DM_DOCUMENT_H.STORERKEY,#{gStorerkey} ,DM_DOCUMENT_H.MNGPLC_ID,DM_DOCUMENT_H.TO_CUSTKEY) 
				   LEFT OUTER JOIN MS_CUSTDLVINFO 
					 ON MS_CUSTDLVINFO.STORERKEY	     = DM_DOCUMENT_H.STORERKEY 
					AND	MS_CUSTDLVINFO.DLVCUSTKEY        = DM_DOCUMENT_H.TO_CUSTKEY 
					AND	MS_CUSTDLVINFO.CUSTTYPE	         = DM_DOCUMENT_H.TO_CUSTTYPE 
				   LEFT OUTER JOIN CM_CAR 
					 ON WD_INPLAN.CARNO	  			     = CM_CAR.CARNO 
					AND WD_INPLAN.DEL_YN   			     = 'N' 
				   LEFT OUTER JOIN MS_SKUDCLABEL 
					 ON MS_SKUDCLABEL.DCCODE             = DM_DOCUMENT_D.DCCODE 
					AND MS_SKUDCLABEL.STORERKEY          = DM_DOCUMENT_D.STORERKEY 
					AND MS_SKUDCLABEL.SKU                = DM_DOCUMENT_D.SKU 
					AND MS_SKUDCLABEL.DEL_YN             = 'N' 
--				   LEFT OUTER JOIN WD_INVOICE_STOCKSTO 
--					 ON WD_INVOICE_STOCKSTO.DCCODE       = DM_DOCUMENT_D.DCCODE 
--					AND WD_INVOICE_STOCKSTO.STORERKEY    = DM_DOCUMENT_D.STORERKEY 
--					AND WD_INVOICE_STOCKSTO.SKU          = DM_DOCUMENT_D.SKU 
--					AND WD_INVOICE_STOCKSTO.DELIVERYDATE = DM_DOCUMENT_D.DELIVERYDATE 
--					AND WD_INVOICE_STOCKSTO.DEL_YN       = 'N' 
				   LEFT OUTER JOIN MS_CUST_REDZONE_SRM 
					 ON	MS_CUST_REDZONE_SRM.STORERKEY  	 = DM_DOCUMENT_H.STORERKEY 
					AND	MS_CUST_REDZONE_SRM.CUSTKEY  	 = DM_DOCUMENT_H.TO_CUSTKEY 
					AND	MS_CUST_REDZONE_SRM.DEL_YN	  	 = 'N' 
				   LEFT JOIN (SELECT DISTINCT SOKEY, SOLINE, WD_DCCODE 
                            FROM  OM_SDY_REGN_REPL_D) OM_SDY_REGN_REPL_D 
					 ON OM_SDY_REGN_REPL_D.SOKEY         = WD_INVOICE.DOCNO 
					AND OM_SDY_REGN_REPL_D.SOLINE        = WD_INVOICE.DOCLINE    
				   LEFT JOIN SO_SUM_QTY
                     ON SO_SUM_QTY.SOKEY     = WD_INVOICE.DOCNO
                     AND  SO_SUM_QTY.SOLINE    = WD_INVOICE.DOCLINE
                     AND  SO_SUM_QTY.WD_DCCODE = OM_SDY_REGN_REPL_D.WD_DCCODE
                   LEFT JOIN MS_SKUDCSET MS_SKUDCSET_STO
                       ON MS_SKUDCSET_STO.DCCODE = OM_SDY_REGN_REPL_D.WD_DCCODE
                      AND MS_SKUDCSET_STO.STORERKEY = DM_DOCUMENT_D.STORERKEY
                      AND MS_SKUDCSET_STO.SKU = DM_DOCUMENT_D.SKU
                      AND MS_SKUDCSET_STO.DEL_YN = 'N'    
				   LEFT OUTER JOIN IB_SRMFOLABEL B 
					 ON WD_INVOICE.DOCNO                 = B.DOCNO 
					AND WD_INVOICE.DOCLINE               = B.DOCLINE 
				   LEFT OUTER JOIN (SELECT /*+ PUSH_PRED */  
										   WD_TASK.DCCODE, WD_TASK.SLIPDT, WD_TASK.PICK_LIST_NO, WD_TASK.SKU, 
										   CASE WHEN MAX(WD_TASK.UOM) = 'BOX' THEN RTRIM(TO_CHAR(SUM(WD_TASK.WORKQTY),'FM99999999999990.99999'),'.') || 'BOX/0EA' 
											    WHEN MAX(WD_TASK.UOM) = 'KG' THEN RTRIM(TO_CHAR(SUM(WD_TASK.WORKQTY),'FM99999999999990.99999'),'.') || 'BOX/0KG' 
											    ELSE RTRIM(TO_CHAR(FLOOR(SUM(WD_TASK.WORKQTY) / MAX(MS_SKU.QTYPERBOX)),'FM99999999999990.99999'),'.') || 'BOX/'||RTRIM(TO_CHAR(MOD(SUM(WD_TASK.WORKQTY) , MAX(MS_SKU.QTYPERBOX)),'FM99999999999990.99999'),'.') ||'EA' 
										    END AS TOTALQTY 
									  FROM WD_TASK 
									  JOIN MS_SKU 
										ON MS_SKU.STORERKEY     = WD_TASK.STORERKEY 
									   AND MS_SKU.SKU           = WD_TASK.SKU    
									 GROUP BY WD_TASK.DCCODE, WD_TASK.SLIPDT, WD_TASK.PICK_LIST_NO, WD_TASK.SKU) LBL_QTY1 
					 ON LBL_QTY1.DCCODE       = WD_INVOICE.DCCODE 
					AND LBL_QTY1.SLIPDT       = WD_INVOICE.SLIPDT 
					AND LBL_QTY1.PICK_LIST_NO = WD_INVOICE.PICK_LIST_NO 
					AND LBL_QTY1.SKU          = WD_INVOICE.SKU 
					LEFT JOIN PRE_CLOSING_CENTER
                     ON PRE_CLOSING_CENTER.DCCODE = WD_INVOICE.DCCODE    
				  WHERE 1=1 
				<if test="dccode != null and dccode != ''">     AND WD_INVOICE.DCCODE	=  #{dccode} </if>
				<if test="taskdt != null and taskdt != ''">     AND WD_INVOICE.SLIPDT	=  #{taskdt} </if>
				<if test="printmethod == 'NEW'">
		            AND WD_INVOICE.PRINT_YN       IN ('0','N')
		            AND WD_INVOICE.CONFIRMQTY > 0
				</if>
				<if test="printmethod == 'OLD'">			
		            AND WD_INVOICE.PRINT_YN   = 'Y' 
		            AND WD_INVOICE.PRINT_CNT   <![CDATA[>]]>   0 
				</if>
				<if test="crossdocktype != null and crossdocktype != ''"> AND MS_SKUDCSET.CROSSDOCKTYPE	  =  #{crossdocktype} </if>
				<if test="distancetype != null and distancetype != ''">   AND MS_CUSTDLVINFO.DISTANCETYPE =  #{distancetype}  </if>
				<if test="crossYn == '1'.toString()">           AND WD_TASK.LOC <![CDATA[<>]]> 'CROSS'  </if>				   
					AND WD_INVOICE.CONFIRMQTY     <![CDATA[>]]> 0 
					AND WD_INVOICE.DEL_YN          = 'N' 
				  GROUP BY WD_INVOICE.INVOICENO, OM_SDY_REGN_REPL_D.WD_DCCODE
		
			<if test="integrationLabelYn == '1'.toString()">	
			 UNION ALL
				  SELECT  /*+ NO_MERGE */
                        MAX(WD_INVOICE.DCCODE)                                                                                               AS DCCODE   
                      , MAX(WD_INVOICE.SLIPDT)                                                                                               AS LBL_MANUDATE     
                      , MAX(CASE WHEN TRUNC(MONTHS_BETWEEN(SYSDATE,MS_CUST.ADDDATE)) = 0 OR MS_CUSTDLVINFO.QCTYPE = 'Y' THEN '(R)' END) 
                          ||CASE WHEN MAX(DM_DOCUMENT_H.B2C_YN)='Y' THEN SUBSTR(MAX(NVL(DM_DOCUMENT_H.TO_CUSTNAME,MS_CUST.DESCRIPTION)),1,30)  
                                 ELSE SUBSTR(MAX(NVL(MS_CUST.DESCRIPTION,DM_DOCUMENT_H.TO_CUSTNAME)),1,30) END AS LBL_CUSTNAME1    
                      , MAX(CASE WHEN MS_SKU.QTYPERBOX > 1 THEN '( '||TO_CHAR(MS_SKU.QTYPERBOX)||MS_SKU.BASEUOM||'/BOX )' ELSE UNISTR('') END) AS LBL_CUSTNAME2     
                      , REPLACE(FN_CONV_SKUBCRNAME(MAX(MS_SKU.DESCRIPTION),1),'~','-')                                                         AS LBL_SKUNAME1            
                      , REPLACE(FN_CONV_SKUBCRNAME(MAX(MS_SKU.DESCRIPTION),2),'~','-')                                                         AS LBL_SKUNAME2            
                      , RTRIM(TO_CHAR(MAX(WD_INVOICE.CONFIRMQTY) * MAX(DM_DOCUMENT_D.BUNMO) / MAX(DM_DOCUMENT_D.BUNJA),'FM99999999999990.99999'),'.')||MAX(DM_DOCUMENT_D.STORERUOM) AS LBL_QTY                          
                      , ''                                                                                                                                                          AS LBL_QTY_2 
                      , MAX(WD_INPLAN.CARNO)                                                                                                                                        AS LBL_PAGENO1                      
                      , CASE WHEN MAX(CM_CAR.CARGROUP) IS NULL  
                             THEN NVL((SELECT MAX(CONVCODE) 
                                         FROM CM_CODE A  
                                        WHERE A.CODELIST  = 'DEFAULTCARGROUP'  
                                          AND A.BASECODE  = #{dccode}
                                          AND A.STORERKEY = #{gStorerkey} 
                                          AND A.DEL_YN    = 'N'), 'NODATA') 
                             ELSE FN_CODEDESCR(#{gStorerkey},'CARGROUP', MAX(CM_CAR.CARGROUP))  
                             END                                                                                                                                                    AS LBL_CARGROUP      
                      , DECODE(FN_DESCR_CODE(MAX(MS_SKU.STORERKEY),'COUNTRY',MAX(MS_SKU.COUNTRYOFORIGIN)) ,'NOT FOUND','','FW' 
                        ||LEFT(FN_DESCR_CODE(MAX(MS_SKU.STORERKEY),'COUNTRY',MAX(MS_SKU.COUNTRYOFORIGIN)),1)||MAX(MS_SKU.COUNTRYOFORIGIN))                                          AS LBL_PLACEOFORIGIN  
                      , MAX(WD_INVOICE.SLIPDT)                                                                                                                                      AS LBL_DELIVERYDT     
                      , CASE WHEN MAX(DM_DOCUMENT_H.B2C_YN) = 'Y'  
                             THEN MAX(TM_INPLAN.DELIVERYGROUP) || CASE WHEN CORE_CM_STRATEGY.FN_ISINVOICEUSEROTAINERNO(MAX(DM_DOCUMENT_D.DCCODE),MAX(DM_DOCUMENT_D.STORERKEY)) = 'Y'  
                                                                       THEN '-' || NVL(MAX(WD_INPLAN.MIXBOXKEY), UNISTR('0'))  
                                                                        END 
                             ELSE MAX(WD_INPLAN.DELIVERYGROUP) || CASE WHEN CORE_CM_STRATEGY.FN_ISINVOICEUSEROTAINERNO(MAX(DM_DOCUMENT_D.DCCODE),MAX(DM_DOCUMENT_D.STORERKEY)) = 'Y'  
                                                                       THEN '-' || NVL(MAX(WD_INPLAN.MIXBOXKEY), UNISTR('0'))  
                                                                        END 
                              END                                                                                                                                                   AS LBL_DELIVERYGROUP 
                      , MAX(NVL(MS_CUST.DESCRIPTION, ' '))                                                                                                                          AS LBL_FROM_CUSTNAME                       
                      , MAX(NVL(MS_SKUDCSET.LOC,' '))                                                                                                                               AS LBL_LOC  /*고정로케이션*/           
                      , MAX(NVL(WD_INVOICE.PAGE_NO,' '))                                                                                                                            AS LBL_PAGENO2       
                      , MAX(NVL(WD_INPLAN.SKU,' '))                                                                                                                                 AS LBL_SKU           
                      , MAX(NVL(WD_INVOICE.ROUTE,' '))                                                                                                                              AS LBL_ROUTENAME     
                      , FN_FORMAT_MASK( WD_INVOICE.INVOICENO,'########## #################### ######## ############ ######')                                                        AS LBL_BARCODETXT   
                      , WD_INVOICE.INVOICENO                                                                                                                                        AS LBL_BARCODE1      
                      , CASE WHEN FN_CODEVALUE(#{gStorerkey} , 'BIGOLABEL_CUST', MAX(DM_DOCUMENT_H.MNGPLC_ID), 'BASECODE') IS NOT NULL 
                             THEN UNISTR('') 
                             ELSE WD_INVOICE.INVOICENO 
                              END                                                                                                                                                   AS LBL_BARCODE2 
                      , CASE WHEN FN_CODEVALUE(#{gStorerkey} , 'BIGOLABEL_CUST', MAX(DM_DOCUMENT_H.MNGPLC_ID), 'BASECODE') IS NOT NULL 
                             THEN SUBSTR(LTRIM(MAX(DM_DOCUMENT_D.REQUESTMEMO)), 0, 15) 
                             ELSE UNISTR('') 
                              END                                                                                                                                                   AS LBL_MEMO_OFN 
                      , FN_CODEDESCR(MAX(MS_SKU.STORERKEY), 'STORAGETYPE', MAX(MS_SKU.STORAGETYPE))                                                                                 AS LBL_STORAGETYPE 
                      , MAX(MS_SKU.STORAGETYPE)                                                                                                                                     AS STORAGETYPE   
                      , CASE WHEN MIN(WD_INVOICE.PRINT_CNT) > 1  
                             THEN DECODE(MAX(WD_INVOICE.LABELSTATUS),'M','물량변경',UNISTR(''))  
                             ELSE UNISTR('')  
                              END|| 
                        CASE WHEN MAX(WD_INVOICE.DCCODE) = '2260' AND MIN(WD_INVOICE.PRINT_CNT) > 1 AND  
                                  MAX(NVL(TM_INPLAN.PREDELIVERYGROUP,' '))  <![CDATA[<>]]>  ' ' AND  
                                  MAX(NVL(TM_INPLAN.PREDELIVERYGROUP,' '))  <![CDATA[<>]]>  MAX(NVL(WD_INPLAN.DELIVERYGROUP,' '))  
                             THEN MAX(NVL(TM_INPLAN.PREDELIVERYGROUP,' ')) ||'>' 
                             ELSE UNISTR('')  
                              END|| 
                        CASE WHEN MAX(WD_INVOICE.DCCODE) = '2600' AND MAX(DM_DOCUMENT_D.PLANT) = '2600' AND  
                                  MAX(MS_CUSTDLVINFO.DISTANCETYPE) IN ('JC','WR') THEN UNISTR(' 거래처별>> ') 
                                  ||FN_ROLLTAINER(MAX(WD_INVOICE.DCCODE), MAX(WD_INVOICE.STORERKEY), MAX(DM_DOCUMENT_H.TO_CUSTTYPE) 
                                                , MAX(DM_DOCUMENT_H.TO_CUSTKEY), MAX(WD_INVOICE.SLIPDT), MAX(WD_INPLAN.DELIVERYGROUP),MAX(TM_INPLAN.PRIORITY)) ELSE UNISTR('') 
                              END                                                                                                                                                   AS LBL_MEMO
                      , SUBSTR(WD_INVOICE.INVOICENO,0,19)||SUBSTR(WD_INVOICE.INVOICENO,26,3)                                                                                        AS INVOICESORT 
                      , NVL(MAX(MS_SKUDCSET.OTHER01),'5')                                                                                                                           AS SKUPRIORITY 
                      , MAX(DM_DOCUMENT_H.TO_CUSTKEY)                                                                                                                               AS TO_CUSTKEY 
                      , MAX(TM_INPLAN.PREDELIVERYGROUP)                                                                                                                             AS PREDELIVERYGROUP 
                      , MAX(WD_INVOICE.PRINT_YN)                                                                                                                                    AS PRINT_YN 
                      , CASE WHEN LEFT(MAX(MS_SKU.SKUGROUP),2) IN ('20','30','40')  
                             THEN UNISTR('본 배송분류표는 식품위생법상의 고지사항과는 무관합니다.') 
                             ELSE UNISTR('본 배송분류표는 관련법상의 고지사항과는 무관합니다.') 
                             END                                                                                                                                                    AS LBL_ETC_MSG 
                      , SUBSTR(MAX(WD_INPLAN.DELIVERYGROUP),2,LENGTH(MAX(WD_INPLAN.DELIVERYGROUP)))                                                                                 AS DELIVERYGROUP_SEQ 
                      , NVL(MAX(MS_SKUDCSET.SMS_YN),'N')                                                                                                                            AS LBL_SMS_YN 
                      , CASE WHEN MAX(WD_INVOICE.DCCODE) = '2260' AND  
                                  MIN(WD_INVOICE.PRINT_CNT) > 1 AND MAX(NVL(TM_INPLAN.PREDELIVERYGROUP,' '))  <![CDATA[<>]]>  ' ' AND  
                                  MAX(NVL(TM_INPLAN.PREDELIVERYGROUP,' '))  <![CDATA[<>]]>  MAX(NVL(WD_INPLAN.DELIVERYGROUP,' '))  
                             THEN MAX(NVL(TM_INPLAN.PREDELIVERYGROUP,' ')) ||'>' 
                             ELSE UNISTR('')  
                             END||MAX(WD_INPLAN.DELIVERYGROUP)||CASE WHEN CORE_CM_STRATEGY.FN_ISINVOICEUSEROTAINERNO(MAX(DM_DOCUMENT_D.DCCODE),MAX(DM_DOCUMENT_D.STORERKEY)) = 'Y'  
                                                                     THEN '-'||NVL(MAX(WD_INPLAN.MIXBOXKEY),UNISTR('0'))  
                             END                                                                                                                                                    AS LBL_DELIVERYGROUP_CHG  
                      , MAX(WD_TASK.PICK_NO)                                                                                                                                        AS PICK_NO                  
                      , MAX(WD_TASK.PICK_BATCH_NO)                                                                                                                                  AS PICK_BATCH_NO          
                      , MAX(WD_INVOICE.DOCNO)                                                                                                                                       AS DOCNO 
                      , MAX(WD_INVOICE.DOCLINE)                                                                                                                                     AS DOCLINE 
                      , MAX(MS_SKUDCLABEL.STORAGE_GUBUN)                                                                                                                            AS STORAGE_GUBUN 
                      , MAX(MS_SKUDCLABEL.STORAGE_GUBUN)                                                                                                                            AS REAL_STORAGE_GUBUN 
                      , DECODE(MAX(WD_TASK.LOC),'CROSS','Y','N')                                                                                                                    AS CROSS_YN 
                      , MAX(DM_DOCUMENT_D.STORERUOM)                                                                                                                                AS STORERUOM 
                      , SUM(WD_TASK.PROCESSQTY)                                                                                                                                     AS PROCESSQTY 
                      , NVL(MAX(MS_SKU.QTYPERBOX), 1)                                                                                                                               AS QTYPERBOX 
                      , FN_CODEVALUE(#{gStorerkey} , 'MARKWORD_SRM', MAX(MS_CUST_REDZONE_SRM.MARK_WORD), 'BASEDESCR')                                                               AS LBL_MARKWORD 
                      , CASE WHEN FN_CODEVALUE(#{gStorerkey} , 'FOLABEL_CUST', MAX(DM_DOCUMENT_H.MNGPLC_ID), 'BASECODE') IS NOT NULL 
                             THEN UNISTR('Y') 
                             ELSE UNISTR('N') 
                         END                                                                                                                                                        AS LBL_FOLABEL_YN 
                      , CASE WHEN NVL(MAX(SO_SUM_QTY.MOVE_QTY),0) > 0  
                             THEN FN_GETDCNAME(OM_SDY_REGN_REPL_D.WD_DCCODE)
                             ELSE FN_GETDCNAME(MAX(WD_INVOICE.DCCODE)) END                              AS LBL_DCNAME
                      , MAX(WD_TASK.ADDDATE)                                                            AS ADDDATE
                      , NVL(MAX(PRE_CLOSING_CENTER.PRE_CLOSING_TIME),'0000')                            AS PRE_CLOSING_TIME        
                      , CASE WHEN NVL(MAX(SO_SUM_QTY.MOVE_QTY),0) > 0  
                             THEN 'STO' 
                             ELSE '총량피킹' END                                                                                          AS LBL_TITLE 
                      , NVL(MAX(SO_SUM_QTY.MOVE_QTY),0)                                                                                 AS STO_QTY1        
                      , NVL(FN_CODEDESCR(MAX(MS_SKUDCLABEL.STORERKEY),'MS_SKUDCLABEL_STORAGE', MAX(MS_SKUDCLABEL.STORAGE_GUBUN)), '')   AS LBL_STORAGETYPE1     
                      , NVL(MAX(B.CARNO),'')                                                                                            AS LBL_PAGENO3  
                      , MAX(NVL(LBL_QTY1.TOTALQTY,0))                                                                                   AS LBL_QTY1
                      , OM_SDY_REGN_REPL_D.WD_DCCODE                                                    AS WD_DCCODE
                   FROM WD_INVOICE                         
                   JOIN WD_INPLAN 
                     ON WD_INPLAN.DCCODE                 = WD_INVOICE.DCCODE 
                    AND WD_INPLAN.STORERKEY              = WD_INVOICE.STORERKEY 
                    AND WD_INPLAN.SLIPDT                 = WD_INVOICE.SLIPDT 
                    AND WD_INPLAN.SLIPNO                 = WD_INVOICE.SLIPNO 
                    AND WD_INPLAN.SLIPLINE               = WD_INVOICE.SLIPLINE 
                    AND WD_INPLAN.DEL_YN                 = 'N' 
                   JOIN WD_TASK 
                     ON WD_TASK.DCCODE                   = WD_INVOICE.DCCODE 
                    AND WD_TASK.STORERKEY                = WD_INVOICE.STORERKEY 
                    AND WD_TASK.SLIPDT                   = WD_INVOICE.SLIPDT 
                    AND WD_TASK.SLIPNO                   = WD_INVOICE.SLIPNO 
                    AND WD_TASK.SLIPLINE                 = WD_INVOICE.SLIPLINE 
                    AND WD_TASK.PICK_LIST_NO             = WD_INVOICE.PICK_LIST_NO 
                    AND WD_TASK.PROCESSQTY    > 0 
                    AND WD_TASK.TASKSYSTEM IS NOT NULL 
                <if test="pickBatchNo != null and pickBatchNo != ''">   AND WD_TASK.PICK_BATCH_NO LIKE #{pickBatchNo}||'%'  </if>                   
                <if test="pickNo != null and pickNo != ''">             AND WD_TASK.PICK_NO LIKE #{pickNo}||'%'             </if>   
                <if test="tasksystem != null and tasksystem != ''">     AND WD_TASK.TASKSYSTEM  = #{tasksystem}             </if>                               
                   JOIN DM_DOCUMENT_D 
                     ON DM_DOCUMENT_D.DCCODE             = WD_INVOICE.DCCODE 
                    AND DM_DOCUMENT_D.STORERKEY          = WD_INVOICE.STORERKEY 
                    AND DM_DOCUMENT_D.DOCTYPE            = WD_INVOICE.DOCTYPE 
                    AND DM_DOCUMENT_D.DOCDT              = WD_INVOICE.DOCDT 
                    AND DM_DOCUMENT_D.DOCNO              = WD_INVOICE.DOCNO 
                    AND DM_DOCUMENT_D.DOCLINE            = WD_INVOICE.DOCLINE 
                    AND DM_DOCUMENT_D.DELIVERYDATE       = WD_INVOICE.SLIPDT            
                    AND DM_DOCUMENT_D.CHANNEL            = '1' 
                    AND DM_DOCUMENT_D.DEL_YN             = 'N' 
                   JOIN DM_DOCUMENT_H                     
                     ON DM_DOCUMENT_H.DCCODE             = DM_DOCUMENT_D.DCCODE 
                    AND DM_DOCUMENT_H.STORERKEY          = DM_DOCUMENT_D.STORERKEY 
                    AND DM_DOCUMENT_H.DOCTYPE            = DM_DOCUMENT_D.DOCTYPE 
                    AND DM_DOCUMENT_H.DOCDT              = DM_DOCUMENT_D.DOCDT 
                    AND DM_DOCUMENT_H.DOCNO              = DM_DOCUMENT_D.DOCNO 
                    AND DM_DOCUMENT_H.DELIVERYDATE       = DM_DOCUMENT_D.DELIVERYDATE  
                    AND DM_DOCUMENT_H.DEL_YN             = 'N' 
                <if test="ordertype != null and ordertype != ''"> AND DM_DOCUMENT_H.ORDERTYPE  = #{ordertype} </if>
                <!-- START.관리처멀티 -->
                <if test="toCustkeyMulti != null and toCustkeyMulti != '' ">
                    <trim prefix="AND (" suffix=")" prefixOverrides="OR">
                        <foreach collection="toCustkeyMulti" item="item">
                            OR DM_DOCUMENT_H.TO_CUSTKEY IN
                            <foreach collection="item" item="code" open="(" close=")" separator=",">
                                #{code}      
                            </foreach>
                        </foreach>
                    </trim>                                             
                </if>
                <!-- END.관리처멀티 -->                    
                   JOIN MS_SKU 
                     ON MS_SKU.STORERKEY                 = DM_DOCUMENT_D.STORERKEY 
                    AND MS_SKU.SKU                       = DM_DOCUMENT_D.SKU 
                    AND MS_SKU.DEL_YN                    = 'N' 
                <!-- START.상품멀티 -->
                <if test="skuMulti != null and skuMulti != '' ">
                    <trim prefix="AND (" suffix=")" prefixOverrides="OR">
                        <foreach collection="skuMulti" item="item">
                            OR WD_INPLAN.SKU IN
                            <foreach collection="item" item="code" open="(" close=")" separator=",">
                                #{code}      
                            </foreach>
                        </foreach>
                    </trim>                                             
                </if>
                <!-- END.상품멀티 -->                       
                <if test="skugroup != null and skugroup != ''">       AND LEFT(MS_SKU.SKUGROUP,2) =  #{skugroup}    </if>
                <if test="storagetype != null and storagetype != ''"> AND MS_SKU.STORAGETYPE      =  #{storagetype} </if>                
                   LEFT OUTER JOIN TM_INPLAN 
                     ON WD_INPLAN.DCCODE                 = TM_INPLAN.DCCODE 
                    AND WD_INPLAN.DOCTYPE                = TM_INPLAN.DOCTYPE 
                    AND WD_INPLAN.SLIPDT                 = TM_INPLAN.SLIPDT 
                    AND WD_INPLAN.SLIPNO                 = TM_INPLAN.SLIPNO 
                    AND WD_INPLAN.DEL_YN                 = 'N' 
                   LEFT OUTER JOIN MS_SKUDCSET 
                     ON MS_SKUDCSET.DCCODE               = DM_DOCUMENT_D.DCCODE 
                    AND MS_SKUDCSET.STORERKEY            = DM_DOCUMENT_D.STORERKEY 
                    AND MS_SKUDCSET.SKU                  = DM_DOCUMENT_D.SKU 
                    AND MS_SKUDCSET.DEL_YN               = 'N' 
                   LEFT OUTER JOIN MS_SKUDCSET MS_SKUDCSET_CROSS 
                     ON MS_SKUDCSET_CROSS.DCCODE         = #{crossDc}
                     AND MS_SKUDCSET_CROSS.STORERKEY     = DM_DOCUMENT_D.STORERKEY    
                    AND MS_SKUDCSET_CROSS.SKU            = DM_DOCUMENT_D.SKU    
                    AND MS_SKUDCSET_CROSS.DEL_YN         = 'N'  
                   LEFT OUTER JOIN MS_CUST                  
                     ON MS_CUST.STORERKEY                = DM_DOCUMENT_H.STORERKEY 
                    AND MS_CUST.CUSTTYPE                 = DM_DOCUMENT_H.TO_CUSTTYPE 
                    AND MS_CUST.CUSTKEY                  = DECODE(DM_DOCUMENT_H.STORERKEY,#{gStorerkey} ,DM_DOCUMENT_H.MNGPLC_ID,DM_DOCUMENT_H.TO_CUSTKEY) 
                   LEFT OUTER JOIN MS_CUSTDLVINFO 
                     ON MS_CUSTDLVINFO.STORERKEY         = DM_DOCUMENT_H.STORERKEY 
                    AND MS_CUSTDLVINFO.DLVCUSTKEY        = DM_DOCUMENT_H.TO_CUSTKEY 
                    AND MS_CUSTDLVINFO.CUSTTYPE          = DM_DOCUMENT_H.TO_CUSTTYPE 
                   LEFT OUTER JOIN CM_CAR 
                     ON WD_INPLAN.CARNO                  = CM_CAR.CARNO 
                    AND WD_INPLAN.DEL_YN                 = 'N' 
                   LEFT OUTER JOIN MS_SKUDCLABEL 
                     ON MS_SKUDCLABEL.DCCODE             = DM_DOCUMENT_D.DCCODE 
                    AND MS_SKUDCLABEL.STORERKEY          = DM_DOCUMENT_D.STORERKEY 
                    AND MS_SKUDCLABEL.SKU                = DM_DOCUMENT_D.SKU 
                    AND MS_SKUDCLABEL.DEL_YN             = 'N' 
--                   LEFT OUTER JOIN WD_INVOICE_STOCKSTO 
--                     ON WD_INVOICE_STOCKSTO.DCCODE       = DM_DOCUMENT_D.DCCODE 
--                    AND WD_INVOICE_STOCKSTO.STORERKEY    = DM_DOCUMENT_D.STORERKEY 
--                    AND WD_INVOICE_STOCKSTO.SKU          = DM_DOCUMENT_D.SKU 
--                    AND WD_INVOICE_STOCKSTO.DELIVERYDATE = DM_DOCUMENT_D.DELIVERYDATE 
--                    AND WD_INVOICE_STOCKSTO.DEL_YN       = 'N' 
                   LEFT OUTER JOIN MS_CUST_REDZONE_SRM 
                     ON MS_CUST_REDZONE_SRM.STORERKEY    = DM_DOCUMENT_H.STORERKEY 
                    AND MS_CUST_REDZONE_SRM.CUSTKEY      = DM_DOCUMENT_H.TO_CUSTKEY 
                    AND MS_CUST_REDZONE_SRM.DEL_YN       = 'N'                     
                   JOIN (SELECT DISTINCT SOKEY, SOLINE, WD_DCCODE 
                            FROM  OM_SDY_REGN_REPL_D) OM_SDY_REGN_REPL_D 
                     ON OM_SDY_REGN_REPL_D.WD_DCCODE      = #{dccode} 
                    AND OM_SDY_REGN_REPL_D.SOKEY          = WD_INVOICE.SLIPNO
                    AND OM_SDY_REGN_REPL_D.SOLINE         = WD_INVOICE.SLIPLINE
                    <if test="checkDccodeMulti != null and checkDccodeMulti != ''">
                       AND WD_INVOICE.DCCODE IN
                       <foreach collection="checkDccodeMulti" item="code" open="(" close=")" separator=",">
                         #{code}
                       </foreach>   
                    </if>    
                   LEFT JOIN SO_SUM_QTY
                     ON   SO_SUM_QTY.SOKEY     = WD_INVOICE.DOCNO
                     AND  SO_SUM_QTY.SOLINE    = WD_INVOICE.DOCLINE
                     AND  SO_SUM_QTY.WD_DCCODE = OM_SDY_REGN_REPL_D.WD_DCCODE
                   LEFT OUTER JOIN IB_SRMFOLABEL B 
                     ON WD_INVOICE.DOCNO                 = B.DOCNO 
                    AND WD_INVOICE.DOCLINE               = B.DOCLINE 
                   LEFT OUTER JOIN (SELECT /*+ PUSH_PRED */  
                                           WD_TASK.DCCODE, WD_TASK.SLIPDT, WD_TASK.PICK_LIST_NO, WD_TASK.SKU, 
                                           CASE WHEN MAX(WD_TASK.UOM) = 'BOX' THEN RTRIM(TO_CHAR(SUM(WD_TASK.WORKQTY),'FM99999999999990.99999'),'.') || 'BOX/0EA' 
                                                WHEN MAX(WD_TASK.UOM) = 'KG' THEN RTRIM(TO_CHAR(SUM(WD_TASK.WORKQTY),'FM99999999999990.99999'),'.') || 'BOX/0KG' 
                                                ELSE RTRIM(TO_CHAR(FLOOR(SUM(WD_TASK.WORKQTY) / MAX(MS_SKU.QTYPERBOX)),'FM99999999999990.99999'),'.') || 'BOX/'||RTRIM(TO_CHAR(MOD(SUM(WD_TASK.WORKQTY) , MAX(MS_SKU.QTYPERBOX)),'FM99999999999990.99999'),'.') ||'EA' 
                                            END AS TOTALQTY 
                                      FROM WD_TASK 
                                      JOIN MS_SKU 
                                        ON MS_SKU.STORERKEY     = WD_TASK.STORERKEY 
                                       AND MS_SKU.SKU           = WD_TASK.SKU    
                                     GROUP BY WD_TASK.DCCODE, WD_TASK.SLIPDT, WD_TASK.PICK_LIST_NO, WD_TASK.SKU) LBL_QTY1 
                     ON LBL_QTY1.DCCODE       = WD_INVOICE.DCCODE 
                    AND LBL_QTY1.SLIPDT       = WD_INVOICE.SLIPDT 
                    AND LBL_QTY1.PICK_LIST_NO = WD_INVOICE.PICK_LIST_NO 
                    AND LBL_QTY1.SKU          = WD_INVOICE.SKU 
                    LEFT JOIN PRE_CLOSING_CENTER
                     ON PRE_CLOSING_CENTER.DCCODE = WD_INVOICE.DCCODE    
                  WHERE 1=1 
                <if test="taskdt != null and taskdt != ''">     AND WD_INVOICE.SLIPDT   =  #{taskdt} </if>
                <if test="printmethod == 'NEW'">
                    AND WD_INVOICE.PRINT_YN       IN ('0','N')
                    AND WD_INVOICE.CONFIRMQTY > 0
                </if>
                <if test="printmethod == 'OLD'">            
                    AND WD_INVOICE.PRINT_YN   = 'Y' 
                    AND WD_INVOICE.PRINT_CNT   <![CDATA[>]]>   0 
                </if>
                <if test="crossdocktype != null and crossdocktype != ''"> AND MS_SKUDCSET.CROSSDOCKTYPE   =  #{crossdocktype} </if>
                <if test="distancetype != null and distancetype != ''">   AND MS_CUSTDLVINFO.DISTANCETYPE =  #{distancetype}  </if>
                <if test="crossYn == '1'.toString()">           AND WD_TASK.LOC <![CDATA[<>]]> 'CROSS'  </if>                  
                    AND WD_INVOICE.CONFIRMQTY     <![CDATA[>]]> 0 
                    AND WD_INVOICE.DEL_YN          = 'N' 
                  GROUP BY WD_INVOICE.INVOICENO, OM_SDY_REGN_REPL_D.WD_DCCODE
			</if>	  
				  ) TBL
		 LEFT OUTER JOIN IB_SRMFOLABEL B
		   ON TBL.DOCNO   = B.DOCNO
		  AND TBL.DOCLINE = B.DOCLINE
--		 LEFT OUTER JOIN (SELECT /*+ PUSH_PRED */   
--								 DOCNO, DOCLINE, MAX(UNISTR(A.CONFIRMQTY || 'BOX/0EA')) BOX0 , MAX(A.CONFIRMQTY) CONFIRMQTY
--							FROM DP_INSPECT A 
--						   GROUP BY DOCNO, DOCLINE
--						  )  LBL_STOQTY
--		   ON LBL_STOQTY.DOCNO   = TBL.STO_DOCNO 
--		  AND LBL_STOQTY.DOCLINE = TBL.STO_DOCLINE	
	</select>

  	<select id="getMasterT2List" resultType="cjfw.wms.wd.dto.WdDeliveryLabelForceResT2Dto">
		SELECT /* [WdDeliveryLabelForceService.sqlx][WdDeliveryLabelForceService.getMasterT2List][출고 > 출고 > 배송 라벨 출력(예외 기준 적용)_기준정보_탭 조회][KimDongHan][2025-10-17] */
		       MS_DLV_LABEL_PRIORITY.DCCODE                                                          AS DCCODE              /* 01. 물류센터코드 */  
		     , FN_GETDCNAME(MS_DLV_LABEL_PRIORITY.DCCODE)                                            AS DCNAME              /* 02. 물류센터명 */
		     , MS_DLV_LABEL_PRIORITY.PRT_NM                                                          AS PRT_NM              /* 03. 출력명칭 */
		     , MS_DLV_LABEL_PRIORITY.PRD_ORD1                                                        AS PRD_ORD1            /* 04. 출력순서1 */
		     , MS_DLV_LABEL_PRIORITY.SEQ1                                                            AS SEQ1                /* 05. 정렬1 */
		     , MS_DLV_LABEL_PRIORITY.PRD_ORD2                                                        AS PRD_ORD2            /* 06. 출력순서2 */
		     , MS_DLV_LABEL_PRIORITY.SEQ2                                                            AS SEQ2                /* 07. 정렬2 */
		     , MS_DLV_LABEL_PRIORITY.PRD_ORD3                                                        AS PRD_ORD3            /* 08. 출력순서3 */
		     , MS_DLV_LABEL_PRIORITY.SEQ3                                                            AS SEQ3                /* 09. 정렬3 */
		     , MS_DLV_LABEL_PRIORITY.PRD_ORD4                                                        AS PRD_ORD4            /* 10. 출력순서4 */
		     , MS_DLV_LABEL_PRIORITY.SEQ4                                                            AS SEQ4                /* 11. 정렬4 */
		     , MS_DLV_LABEL_PRIORITY.PRD_ORD5                                                        AS PRD_ORD5            /* 12. 출력순서5 */
		     , MS_DLV_LABEL_PRIORITY.SEQ5                                                            AS SEQ5                /* 13. 정렬5 */
		     , MS_DLV_LABEL_PRIORITY.PRD_ORD6                                                        AS PRD_ORD6            /* 14. 출력순서6 */
		     , MS_DLV_LABEL_PRIORITY.SEQ6                                                            AS SEQ6                /* 15. 정렬6 */
		     , MS_DLV_LABEL_PRIORITY.PRD_ORD7                                                        AS PRD_ORD7            /* 16. 출력순서7 */
		     , MS_DLV_LABEL_PRIORITY.SEQ7                                                            AS SEQ7                /* 17. 정렬7 */
		     , MS_DLV_LABEL_PRIORITY.PRD_ORD8                                                        AS PRD_ORD8            /* 18. 출력순서8 */
		     , MS_DLV_LABEL_PRIORITY.SEQ8                                                            AS SEQ8                /* 19. 정렬8 */
		     , MS_DLV_LABEL_PRIORITY.RMK                                                             AS RMK                 /* 20. 비고 */
			 , USER1.USER_NM                                                                         AS ADDWHO              /* 21. 등록자 */
			 , TO_CHAR(MS_DLV_LABEL_PRIORITY.ADDDATE,'YYYY-MM-DD HH24:MI:SS')                        AS ADDDATE	            /* 22. 등록일시 */
			 , USER2.USER_NM                                                                         AS EDITWHO             /* 23. 수정자 */
			 , TO_CHAR(MS_DLV_LABEL_PRIORITY.EDITDATE,'YYYY-MM-DD HH24:MI:SS')                       AS EDITDATE            /* 24. 수정일시 */
		     , MS_DLV_LABEL_PRIORITY.USE_PGM                                                         AS USE_PGM             /* USE_PGM */
		     --
		     , MS_DLV_LABEL_PRIORITY.PRT_NM                                                          AS PRT_NM_ORI          /* 원출력명칭-명칭변경 시 사용 */	 
		  FROM MS_DLV_LABEL_PRIORITY
		  LEFT OUTER JOIN FRAMEONE_USER USER1 ON USER1.USER_ID = MS_DLV_LABEL_PRIORITY.ADDWHO   /*등록자명*/
		  LEFT OUTER JOIN FRAMEONE_USER USER2 ON USER2.USER_ID = MS_DLV_LABEL_PRIORITY.EDITWHO  /*수정자명*/
		 WHERE 1=1    
	       AND DCCODE     = #{dccode}
		<if test="usePgm != null and usePgm != ''">	       
           AND USE_PGM    = #{usePgm}
		</if>
  	</select>    
    
    <select id="getPopMasterList" resultType="cjfw.wms.wd.dto.WdDeliveryLabelForceResT1Dto">
		SELECT /* [WdDeliveryLabelForceService.sqlx][WdDeliveryLabelForceService.getPopMasterList][출고 > 출고 > 배송 라벨 출력(예외 기준 적용) STO 등록 팝업 조회 조회][KimDongHan][2025-10-17] */
		       SUBSTR(XMLAGG(XMLELEMENT(COL ,',', DOCNO) ORDER BY DOCNO).EXTRACT('//text()').GETSTRINGVAL(), 2)          AS DOCNO
		     , NVL(SUBSTR(XMLAGG(XMLELEMENT(COL ,',', DOCNO) ORDER BY DOCNO).EXTRACT('//text()').GETSTRINGVAL(), 2),'X') AS YN
		     , #{taskdt}                                                                                                 AS DELIVERYDT
		  FROM ( SELECT DISTINCT DOCNO 
		           FROM WD_INVOICE_STOCKSTO
		          WHERE DELIVERYDATE    = #{taskdt} 
		            AND DCCODE          = #{dccode}
		            AND	DEL_YN			= 'N' )      
    </select>
    
	<insert id="savePopMaster">
		BEGIN
			<!-- 1.기존 해당 센터, 해당날짜 오더 삭제 처리 -->
	        UPDATE WD_INVOICE_STOCKSTO 
	           SET DEL_YN       = 'Y'
	         WHERE DCCODE       = #{dccode}
	           AND STORERKEY    = #{gStorerkey}
	           AND DELIVERYDATE = #{taskdt} ;
	
			<!-- 2. DP_INSPECT에서 오더 찾아서 입력-->
	        INSERT 
			  INTO WD_INVOICE_STOCKSTO
	             ( SERIALKEY
	             , STORERKEY
	             , DCCODE
	             , DELIVERYDATE
	             , DOCNO
	             , DOCLINE
	             , SKU
	             , UOM
	             , ADDDATE
	             , EDITDATE
	             , ADDWHO
	             , EDITWHO )
	        SELECT SEQ_WD_INVOICE_STOCKSTO.NEXTVAL
	             , STORERKEY
	             , DCCODE
	             , SLIPDT
	             , DOCNO
	             , DOCLINE
	             , SKU
	             , UOM
	             , SYSDATE AS ADDDATE
	             , SYSDATE AS EDITDATE
	             , #{gUserId}
	             , #{gUserId}
	          FROM ( SELECT DP_INSPECT.DCCODE                                            AS DCCODE
	                      , DP_INSPECT.SKU                                               AS SKU
	                      , DP_INSPECT.STORERKEY                                         AS STORERKEY
	                      , DP_INSPECT.DOCNO                                             AS DOCNO
	                      , DP_INSPECT.DOCLINE                                           AS DOCLINE
	                      , DP_INSPECT.SLIPDT                                            AS SLIPDT
	                      , DM_DOCUMENT_D.STORERUOM                                      AS UOM
	                   FROM DP_INSPECT
	                   JOIN DM_DOCUMENT_D
	                     ON DM_DOCUMENT_D.DCCODE             = DP_INSPECT.DCCODE
	                    AND DM_DOCUMENT_D.STORERKEY          = DP_INSPECT.STORERKEY
	                    AND DM_DOCUMENT_D.DOCTYPE            = DP_INSPECT.DOCTYPE
	                    AND DM_DOCUMENT_D.DOCDT              = DP_INSPECT.DOCDT
	                    AND DM_DOCUMENT_D.DOCNO              = DP_INSPECT.DOCNO
	                    AND DM_DOCUMENT_D.DOCLINE            = DP_INSPECT.DOCLINE
	                    AND DM_DOCUMENT_D.CHANNEL            = '1' <!-- 저장품만 -->
	                    AND DM_DOCUMENT_D.DEL_YN             = 'N'
	                  WHERE  1=1
	                    AND DP_INSPECT.DCCODE = #{dccode}
	                    AND DP_INSPECT.SLIPDT = #{taskdt}
	                    <!--
					    AND DP_INSPECT.DOCNO  = #{docno}
					    --> 
		        <!-- START.주문번호_멀티 -->
		        <if test="docnoMulti != null and docnoMulti != '' ">
					<trim prefix="AND (" suffix=")" prefixOverrides="OR">
						<foreach collection="docnoMulti" item="item">
							OR DP_INSPECT.DOCNO IN
							<foreach collection="item" item="code" open="(" close=")" separator=",">
								#{code} 	 
				      		</foreach>
				    	</foreach>
				  	</trim>			                                    
		        </if>
		        <!-- END.주문번호_멀티 -->						    
					    );
		END;	
	</insert>    
	
	<select id="getDupCheck" resultType="int">
		SELECT /* [WdDeliveryLabelForceService.sqlx][WdDeliveryLabelForceService.getDupCheck][출고 > 출고 > 배송 라벨 출력(예외 기준 적용)_탭 중복조회][KimDongHan][2025-10-17] */
		       COUNT(*)
		  FROM MS_DLV_LABEL_PRIORITY
		 WHERE 1=1
		   AND DCCODE     = #{dccode}
		   AND USE_PGM    = #{usePgm}
		   AND PRT_NM     = #{prtNm} 
    </select>	
	
	<insert id="insertMaster">
		INSERT /* [WdDeliveryLabelForceService.sqlx][WdDeliveryLabelForceService.insertMaster][출고 > 출고 > 배송 라벨 출력(예외 기준 적용)_기준정보_탭 저장(신규)][KimDongHan][2025-10-17] */
		  INTO MS_DLV_LABEL_PRIORITY
		     ( DCCODE                  /* 01. 물류센터코드 */
			 , USE_PGM                 /* 02. 사용프로그램 */
			 , PRT_NM                  /* 03. 출력명칭 */
			 , PRD_ORD1                /* 04. 출력순서1 */
		     , SEQ1                    /* 05. 정렬1 */
		     , PRD_ORD2                /* 06. 출력순서2 */
		     , SEQ2                    /* 07. 정렬2 */
		     , PRD_ORD3                /* 08. 출력순서3 */
		     , SEQ3                    /* 09. 정렬3 */
		     , PRD_ORD4                /* 10. 출력순서4 */
		     , SEQ4                    /* 11. 정렬4 */
		     , PRD_ORD5                /* 12. 출력순서5 */
		     , SEQ5                    /* 13. 정렬5 */
		     , PRD_ORD6                /* 14. 출력순서6 */
		     , SEQ6                    /* 15. 정렬6 */
		     , PRD_ORD7                /* 16. 출력순서7 */
		     , SEQ7                    /* 17. 정렬7 */
		     , PRD_ORD8                /* 18. 출력순서8 */
		     , SEQ8                    /* 19. 정렬8 */
		     , RMK                     /* 20. 비고 */
		     , ADDWHO                  /* 21. 등록자 */
		     , ADDDATE	               /* 22. 등록일시 */
		     , EDITWHO                 /* 23. 수정자 */
		     , EDITDATE                /* 24. 수정일시 */
			 ) VALUES (                
		       #{dccode}               /* 01. 물류센터코드 */     
			 , #{usePgm}               /* 02. 사용프로그램 */
			 , #{prtNm}                /* 03. 출력명칭 */
			 , #{prdOrd1}              /* 04. 출력순서1 */
		     , #{seq1}                 /* 05. 정렬1 */
		     , #{prdOrd2}              /* 06. 출력순서2 */
		     , #{seq2}                 /* 07. 정렬2 */
		     , #{prdOrd3}              /* 08. 출력순서3 */
		     , #{seq3}                 /* 09. 정렬3 */
		     , #{prdOrd4}              /* 10. 출력순서4 */
		     , #{seq4}                 /* 11. 정렬4 */
		     , #{prdOrd5}              /* 12. 출력순서5 */
		     , #{seq5}                 /* 13. 정렬5 */
		     , #{prdOrd6}              /* 14. 출력순서6 */
		     , #{seq6}                 /* 15. 정렬6 */
		     , #{prdOrd7}              /* 16. 출력순서7 */
		     , #{seq7}                 /* 17. 정렬7 */
		     , #{prdOrd8}              /* 18. 출력순서8 */
		     , #{seq8}                 /* 19. 정렬8 */
		     , #{rmk}                  /* 20. 비고 */
		     , #{gUserId}              /* 21. 등록자 */
		     , SYSDATE	               /* 22. 등록일시 */
		     , #{gUserId}              /* 23. 수정자 */
		     , SYSDATE                 /* 24. 수정일시 */
			 )  
	</insert>	
	
	<update id="updateMaster">
		UPDATE /* [WdDeliveryLabelForceService.sqlx][WdDeliveryLabelForceService.insertMaster][출고 > 출고 > 배송 라벨 출력(예외 기준 적용)_기준정보_탭 저장(수정)][KimDongHan][2025-10-17] */ 	 
		       MS_DLV_LABEL_PRIORITY
		   SET EDITWHO    = EDITWHO
		     , EDITDATE   = SYSDATE
		     , PRD_ORD1	  = #{prdOrd1}
		     , SEQ1       = #{seq1}   
		     , PRD_ORD2   = #{prdOrd2}
		     , SEQ2       = #{seq2}   
		     , PRD_ORD3   = #{prdOrd3}
		     , SEQ3       = #{seq3}   
		     , PRD_ORD4   = #{prdOrd4}
		     , SEQ4       = #{seq4}   
		     , PRD_ORD5   = #{prdOrd5}
		     , SEQ5       = #{seq5}   
		     , PRD_ORD6   = #{prdOrd6}
		     , SEQ6       = #{seq6}   
		     , PRD_ORD7   = #{prdOrd7}
		     , SEQ7       = #{seq7}   
		     , PRD_ORD8   = #{prdOrd8}
		     , SEQ8       = #{seq8}   
		     , RMK        = #{rmk}    
		     --
		     ,PRT_NM     = #{prtNm} 
		 WHERE 1=1
		   AND DCCODE     = #{dccode}
		   AND USE_PGM    = #{usePgm}
		   AND PRT_NM     = #{prtNmOri} 
	</update>	
	
	<update id="saveInvoiceNoPrtYn">
		UPDATE /* [WdDeliveryLabelForceService.sqlx][WdDeliveryLabelForceService.saveInvoiceNoPrtYn][출고 > 출고 > 배송 라벨 출력(예외 기준 적용)_분류표출력_탭 인쇄시 저장][KimDongHan][2025-10-17] */ 	 
		       WD_INVOICE
		   SET WD_INVOICE.PRINT_YN   = 'Y'
		     , WD_INVOICE.PRINT_CNT  = NVL(PRINT_CNT,0) + 1
		     , WD_INVOICE.PRINT_DATE = SYSDATE
		     , WD_INVOICE.DLV_DATA04 = 'FORCEPRINT'
		 WHERE 1=1	
	    <!-- START.인보이스번호 -->
	    <if test="invoicenoMulti != null and invoicenoMulti != '' ">
			<trim prefix="AND (" suffix=")" prefixOverrides="OR">
				<foreach collection="invoicenoMulti" item="item">
			OR WD_INVOICE.INVOICENO IN
					<foreach collection="item" item="code" open="(" close=")" separator=",">
						#{code} 	 
		      		</foreach>
		    	</foreach>
		  	</trim>			                                    
	    </if>
	    <!-- END.인보이스번호 -->				 
	</update>
		
	<update id="deleteInvoiceSTO">
		UPDATE /* [WdDeliveryLabelForceService.sqlx][WdDeliveryLabelForceService.deleteInvoiceSTO][출고 > 출고 > 배송 라벨 출력(예외 기준 적용)_분류표출력_탭 인쇄시 저장][KimDongHan][2025-10-17] */ 
		       WD_INVOICE_STOCKSTO 
		   SET DEL_YN       = 'Y'
		 WHERE DCCODE       = #{dccode}
		   AND STORERKEY    = #{gStorerkey}
		   AND DELIVERYDATE = #{deliverydate}
	</update>	
	    
</mapper>