<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="wdInplanKXService">

    <select id="getInplanKXList"  resultType="WdInplanKXResDto">
		SELECT /* [wdInplanKXService.sqlx][wdInplanKXService.getInplanKXList][KX출고진행현황 통합 정보][JiSooKim][20251128] */
		           '0'                                              							AS CHECKYN 
		           ,DCCODE                                                                     AS DCCODE
		           ,STORERKEY                                                                  AS STORERKEY
		           ,ORGANIZE                                                                   AS ORGANIZE
		           ,SLIPDT                                                                     AS SLIPDT
		           ,SLIPNO                                                                     AS SLIPNO
		           ,SLIPLINE                                                                   AS SLIPLINE
		           ,DOCDT                                                                      AS DOCDT
		           ,DOCNO                                                                      AS DOCNO
		           ,DOCTYPE                                                                    AS DOCTYPE
		           ,DOCLINE                                                                    AS DOCLINE
		           ,(SELECT FN_CODEDESCR(STORERKEY,'ORDERTYPE_WD',   ORDERTYPE     ) FROM DUAL) AS ORDERTYPE
		           ,(SELECT FN_CODEDESCR(STORERKEY,'SOTYPE',         SOTYPE        ) FROM DUAL) AS SOTYPE
		           ,(SELECT FN_CODEDESCR(STORERKEY,'SALEGROUP',      SALEGROUP     ) FROM DUAL) AS SALEGROUP
		           ,(SELECT FN_CODEDESCR(STORERKEY,'SALEDEPARTMENT', SALEDEPARTMENT) FROM DUAL) AS SALEDEPARTMENT
		           ,(SELECT FN_CODEDESCR(STORERKEY,'SALEORGANIZE',   OTHER04       ) FROM DUAL) AS SALEORGANIZE
		           ,CUSTGROUP                                                                  AS CUSTGROUP
		           ,BILLTOCUSTKEY                                                              AS BILLTOCUSTKEY
		           ,(SELECT FN_DESCR_CUST(STORERKEY, BILLTOCUSTKEY) FROM DUAL)                 AS BILLTOCUSTNAME
		           ,TO_CUSTKEY                                                                 AS TO_CUSTKEY
		           ,TO_CUSTNAME                                                                AS TO_CUSTNAME
		           ,MNGPLC_ID																AS MNGPLC_ID
		           ,(SELECT FN_DESCR_CUST(STORERKEY, MNGPLC_ID) FROM DUAL)							AS MNGPLC_NAME
		           ,(SELECT FN_CODEDESCR (STORERKEY,'STATUS_WD', STATUS) FROM DUAL)            AS STATUS
		           ,DELIVERYGROUP                                                              AS DELIVERYGROUP
		           ,CARNO                                                                      AS CARNO
		           ,SKU                                                                        AS SKU
		           ,DESCRIPTION                                                                AS SKUNAME
		           ,(SELECT FN_CODEDESCR(STORERKEY,'PUTAWAYTYPE', CHANNEL)     FROM DUAL)      AS CHANNEL
		           ,(SELECT FN_CODEDESCR(STORERKEY,'STORAGETYPE', STORAGETYPE) FROM DUAL)      AS STORAGETYPE
		           ,STOREROPENQTY                                                              AS ORDERQTY
		           ,ROUND(FN_CONV_UOM(STORERKEY , SKU ,STORERUOM ,'KG' ,STOREROPENQTY),2)      AS ORDERWEIGHT 
		           ,(SELECT FN_UOMCAL(BUNMO, BUNJA, CANCELQTY) FROM DUAL)                      AS CANCELQTY
		           ,TRUNC((SELECT FN_CONV_UOM(STORERKEY ,SKU ,UOM ,'KG' ,CONFIRMQTY) FROM DUAL), 2) AS CONFIRMWEIGHT
		           ,STORERUOM                                                                  AS UOM
		           ,(SELECT FN_UOMCAL(BUNMO, BUNJA, QTYALLOCATED) FROM DUAL)                   AS PROCESSQTY
		           ,(SELECT FN_UOMCAL(BUNMO, BUNJA, QTYPICKED   ) FROM DUAL)                   AS WORKQTY
		           ,(SELECT FN_UOMCAL(BUNMO, BUNJA, INSPECTQTY  ) FROM DUAL)                   AS INSPECTQTY
		           ,(SELECT FN_UOMCAL(BUNMO, BUNJA, CONFIRMQTY  ) FROM DUAL)                   AS CONFIRMQTY
		           ,OMS_FLAG                                                                   AS CLOSEYN
		           ,DEL_YN                                                                     AS DEL_YN
		           ,IF_AUDIT_FILE                                                              AS IF_AUDIT_FILE
		           ,IF_SEND_FILE                                                               AS IF_SEND_FILE 
		           ,to_char(ADDDATE,'yyyy-mm-dd hh24:mi:ss')    AS ADDDATE
		           ,PLANT                                                                      AS PLANT
		           ,'[' || PLANT || ']' || (SELECT FN_DESCR_PLANT(PLANT) FROM DUAL)            AS PLANT_DESCR
		           ,DELIVERYPRIORITY                                                           AS LOADPLACE 
		           ,ROUTE                                                                      AS ROUTE
		           ,DECODE(ROUTE, NULL, NULL,'[' || ROUTE || ']' || (SELECT FN_DESCR_PLANT(ROUTE) FROM DUAL)) AS ROUTE_DESCR
		           ,(SELECT FN_CODEDESCR(STORERKEY, 'DELIVERYTYPE', DELIVERYTYPE) FROM DUAL)   AS DELIVERYTYPE
		           ,(SELECT FN_CODEDESCR(STORERKEY, 'SERIALYN',     SERIALYN)     FROM DUAL)   AS SERIALYN
		           ,LINE01                                                                     AS LINE01
		           ,PROCPOSS_YN                                                                AS BEFORESHORTAGEPLANYN
		           ,(SELECT FN_GETCUSTCLASSCODE(STORERKEY, CUSTSTRATEGY3, '1', 'DESCR') FROM DUAL) AS SALECUSHRC1
		           ,(SELECT FN_GETCUSTCLASSCODE(STORERKEY, CUSTSTRATEGY3, '2', 'DESCR') FROM DUAL) AS SALECUSHRC2
		           ,(SELECT FN_GETCUSTCLASSCODE(STORERKEY, CUSTSTRATEGY3, '3', 'DESCR') FROM DUAL) AS SALECUSHRC3
		           ,QTYPERBOX																			AS QTYPERBOX
		           ,CASE WHEN EXCEPT_YN = 'Y' THEN '제외대상' ELSE '비제외대상' END                  AS EXCEPT_YN
		           ,TO_VATADDRESS1
		           ,TO_ZIPCODE
		    FROM
		    (
		            SELECT /*+ FULL(DM_DOCUMENT_D) */
		                   DM_DOCUMENT_D.DCCODE                                                                     AS DCCODE
		                  ,DM_DOCUMENT_D.STORERKEY                                                                  AS STORERKEY
		                  ,(SELECT FN_DESCR_ORGANIZE(DM_DOCUMENT_D.DCCODE, DM_DOCUMENT_D.ORGANIZE) FROM DUAL)           AS ORGANIZE
		                  ,DM_DOCUMENT_D.DELIVERYDATE                                                              AS SLIPDT
		                  ,DM_DOCUMENT_D.DOCNO                                                                     AS SLIPNO
		                  ,DM_DOCUMENT_D.DOCLINE                                                                   AS SLIPLINE
		                  ,MAX(DM_DOCUMENT_D.DOCDT )                                                                AS DOCDT
		                  ,MAX(DM_DOCUMENT_D.DOCNO )                                                                AS DOCNO
		                  ,MAX(DM_DOCUMENT_D.DOCTYPE)                                                               AS DOCTYPE
		                  ,MAX(DM_DOCUMENT_D.DOCLINE)                                                               AS DOCLINE
		                  ,MAX(DM_DOCUMENT_D.ORDERTYPE)                                                             AS ORDERTYPE
		                  ,MAX(DM_DOCUMENT_H.SOTYPE)                                                            AS SOTYPE
		                  ,MAX(MS_CUST.SALEGROUP)                                                               AS SALEGROUP
		                  ,MAX(MS_CUST.SALEDEPARTMENT)                                                          AS SALEDEPARTMENT
		                  ,MAX(MS_CUST.OTHER04)                                                                 AS OTHER04
		                  ,MAX(MS_CUST.CUSTGROUP)                                                               AS CUSTGROUP
		                  ,MAX(MS_CUST.BILLTOCUSTKEY)                  												AS BILLTOCUSTKEY         
		                  ,MAX(DM_DOCUMENT_H.TO_CUSTKEY)                                                        AS TO_CUSTKEY
		                  ,MAX(DM_DOCUMENT_H.TO_CUSTNAME)                                                       AS TO_CUSTNAME
		                  ,MAX(DM_DOCUMENT_H.MNGPLC_ID)                                                        	AS MNGPLC_ID
		                  ,MIN(DM_DOCUMENT_D.STATUS)                                                            AS STATUS
		                  ,MAX(TM_INPLAN.DELIVERYGROUP)                                                         AS DELIVERYGROUP
		                  ,MAX(TM_INPLAN.CARNO        )                                                         AS CARNO
		                  ,MAX(DM_DOCUMENT_D.SKU      )                                                     AS SKU
		                  ,MAX(MS_SKU.DESCRIPTION     )                                                         AS DESCRIPTION
		                  ,MAX(DM_DOCUMENT_D.CHANNEL  )                                                         AS CHANNEL
		                  ,MAX(MS_SKU.STORAGETYPE     )                                                         AS STORAGETYPE
		                  ,MAX(DM_DOCUMENT_D.STOREROPENQTY)                                                     AS STOREROPENQTY
		                  ,MAX(DM_DOCUMENT_D.CANCELQTY)                                                         AS CANCELQTY
		                  ,MAX(DM_DOCUMENT_D.BUNMO)                                                             AS BUNMO
		                  ,MAX(DM_DOCUMENT_D.BUNJA)                                                             AS BUNJA
		                  ,MAX(WD_INPLAN.CONFIRMQTY)                                                            AS CONFIRMWEIGHT
		                  ,MAX(DM_DOCUMENT_D.STORERUOM     )                                                    AS STORERUOM
		                  ,MAX(DM_DOCUMENT_D.UOM     )                                                          AS UOM
		                  ,MAX(WD_INPLAN.QTYALLOCATED      )                                                    AS QTYALLOCATED
		                  ,MAX(WD_INPLAN.QTYPICKED         )                                                    AS QTYPICKED
		                  ,MAX(WD_INPLAN.INSPECTQTY        )                                                    AS INSPECTQTY
		                  ,MAX(WD_INPLAN.CONFIRMQTY        )                                                    AS CONFIRMQTY
		                  ,MAX(DM_DOCUMENT_D.OMS_FLAG)                                                          AS OMS_FLAG
		                  ,MAX(DM_DOCUMENT_D.DEL_YN)                                                            AS DEL_YN
		                  ,MAX(DM_DOCUMENT_D.IF_AUDIT_FILE)                                                     AS IF_AUDIT_FILE
		                  ,MAX(DM_DOCUMENT_D.IF_SEND_FILE)                                                      AS IF_SEND_FILE 
		                  ,MAX(DM_DOCUMENT_D.ADDDATE)                                                           AS ADDDATE
		                  ,MAX(DM_DOCUMENT_D.PLANT	)                                                           AS PLANT
		                  ,MAX(TM_INPLANCUST.DELIVERYPRIORITY)                                                  AS DELIVERYPRIORITY 
		                  ,MAX(TRIM(DM_DOCUMENT_D.ROUTE))                                                       AS ROUTE
		                  ,MAX(DM_DOCUMENT_H.DELIVERYTYPE)                                                      AS DELIVERYTYPE
		                  ,MAX(MS_SKU.SERIALYN)                                                                 AS SERIALYN
		                  ,CASE WHEN MAX(MS_SKU.LINE01) = 'Y' THEN UNISTR('Y') ELSE UNISTR('') END              AS LINE01
		                  ,CASE WHEN MAX(DM_DOCUMENT_D.PROCPOSS_YN) = 'R' THEN UNISTR('Y') ELSE UNISTR('') END  AS PROCPOSS_YN
		                  ,MAX(MS_CUST.CUSTSTRATEGY3)                                                           AS CUSTSTRATEGY3
		                  ,MAX(MS_SKU.QTYPERBOX)                                                                AS QTYPERBOX
		                  ,MAX(MS_EXCEPTION_SKU.EXCEPT_YN)                                                      AS EXCEPT_YN
		                  ,MAX(DM_DOCUMENT_H.TO_VATADDRESS1)                                                    AS TO_VATADDRESS1
		                  ,MAX(DM_DOCUMENT_H.TO_ZIPCODE)                                                        AS TO_ZIPCODE
		            FROM   DM_DOCUMENT_D
		            JOIN   DM_DOCUMENT_H           
		            ON     DM_DOCUMENT_H.DCCODE         =  DM_DOCUMENT_D.DCCODE         
		            AND    DM_DOCUMENT_H.STORERKEY      =  DM_DOCUMENT_D.STORERKEY               
		            AND    DM_DOCUMENT_H.ORGANIZE       =  DM_DOCUMENT_D.ORGANIZE               
		            AND    DM_DOCUMENT_H.DOCTYPE        =  DM_DOCUMENT_D.DOCTYPE         
		            AND    DM_DOCUMENT_H.DOCDT          =  DM_DOCUMENT_D.DOCDT         
		            AND    DM_DOCUMENT_H.DOCNO          =  DM_DOCUMENT_D.DOCNO         
		            AND    DM_DOCUMENT_H.DOCTYPE        = 'WD'     
		            AND    DM_DOCUMENT_H.WORKPROCESSCODE <![CDATA[<>]]> 'STO'
		            AND    NVL(DM_DOCUMENT_H.IF_SEND_TYPE,'SO')    <![CDATA[<>]]> 'STODC'
		
		            <if test="toVatno != null and toVatno != ''">
		                AND    DM_DOCUMENT_H.TO_VATNO                  =     #{toVatno}
		            </if>
		
		            <!-- 배송그룹 공통조회 조건 -->
		            <if test="gMultiCourier != null and gMultiCourier != ''">
		                AND    DM_DOCUMENT_H.COURIER          =      #{gMultiCourier}
		            </if>
		            <if test="sotype != null and sotype != ''">
		                AND    DM_DOCUMENT_H.SOTYPE           =      #{sotype}
		            </if>
		            <if test="toEmpname1 != null and toEmpname1 != ''">
		                AND    DM_DOCUMENT_H.TO_EMPNAME1      =      #{toEmpname1}
		            </if>
		
		            <!-- 고객 다중선택 -->
		            <if test="toCustkeyMulti != null and toCustkeyMulti != '' ">
				    	<trim prefix="AND (" suffix=")" prefixOverrides="OR">
				    		<foreach collection="toCustkeyMulti" item="item">
				    			OR DM_DOCUMENT_H.TO_CUSTKEY IN
				    			<foreach collection="item" item="code" open="(" close=")" separator=",">
				    				#{code} 	 
				          		</foreach>
				        	</foreach>
				      	</trim>			                                    
		            </if>
		
		            LEFT OUTER JOIN   WD_INPLAN           
		            ON     WD_INPLAN.DCCODE             =  DM_DOCUMENT_D.DCCODE         
		            AND    WD_INPLAN.STORERKEY          =  DM_DOCUMENT_D.STORERKEY               
		            AND    WD_INPLAN.ORGANIZE           =  DM_DOCUMENT_D.ORGANIZE               
		            AND    WD_INPLAN.AREA               =  DM_DOCUMENT_D.AREA               
		            AND    WD_INPLAN.DOCTYPE            =  DM_DOCUMENT_D.DOCTYPE         
		            AND    WD_INPLAN.DOCDT              =  DM_DOCUMENT_D.DOCDT         
		            AND    WD_INPLAN.DOCNO              =  DM_DOCUMENT_D.DOCNO         
		            AND    WD_INPLAN.DOCLINE            =  DM_DOCUMENT_D.DOCLINE         
		            AND    WD_INPLAN.DEL_YN             = 'N'    
		
		            <if test="fromSlipdt != null and fromSlipdt != ''">
		                AND    DM_DOCUMENT_D.DELIVERYDATE   <![CDATA[>=]]>  #{fromSlipdt}
		            </if>
		            <if test="toSlipdt != null and toSlipdt != ''">
		                AND    DM_DOCUMENT_D.DELIVERYDATE   <![CDATA[<=]]>  #{toSlipdt}
		            </if>
		
		            <!-- 고객 다중선택 (WD_INPLAN 기준) -->
		           
		            <if test="toCustkeyMulti != null and toCustkeyMulti != '' ">
				    	<trim prefix="AND (" suffix=")" prefixOverrides="OR">
				    		<foreach collection="toCustkeyMulti" item="item">
				    			OR WD_INPLAN.CUSTKEY IN
				    			<foreach collection="item" item="code" open="(" close=")" separator=",">
				    				#{code} 	 
				          		</foreach>
				        	</foreach>
				      	</trim>			                                    
		            </if>
		            
		            
		            
		            LEFT OUTER JOIN TM_INPLAN
		            ON     TM_INPLAN.DCCODE      = WD_INPLAN.DCCODE
		            AND    TM_INPLAN.STORERKEY   = WD_INPLAN.STORERKEY
		            AND    TM_INPLAN.DOCTYPE     = WD_INPLAN.DOCTYPE
		            AND    TM_INPLAN.SLIPDT      = WD_INPLAN.SLIPDT
		            AND    TM_INPLAN.SLIPNO      = WD_INPLAN.SLIPNO
		            
		            <if test="skuMulti != null and skuMulti != '' ">
		                <if test="fromSlipdt != null and fromSlipdt != ''">
		                    AND    TM_INPLAN.SLIPDT    <![CDATA[>=]]>  #{fromSlipdt}
		                </if>
		                <if test="toSlipdt != null and toSlipdt != ''">
		                    AND    TM_INPLAN.SLIPDT    <![CDATA[<=]]>  #{toSlipdt}
		                </if>
		            </if>
		            AND    TM_INPLAN.DEL_YN      = 'N'
		            
		            LEFT OUTER JOIN TM_INPLANCUST
		            ON     TM_INPLANCUST.DCCODE        = TM_INPLAN.DCCODE
		            AND    TM_INPLANCUST.STORERKEY     = TM_INPLAN.STORERKEY
		            AND    TM_INPLANCUST.DELIVERYDT    = TM_INPLAN.DELIVERYDT
		            AND    TM_INPLANCUST.DELIVERYGROUP = TM_INPLAN.DELIVERYGROUP
		            AND    TM_INPLANCUST.CARNO         = TM_INPLAN.CARNO
		            AND    TM_INPLANCUST.PRIORITY      = TM_INPLAN.PRIORITY
		            AND    TM_INPLANCUST.CUSTKEY       = TM_INPLAN.CUSTKEY
		            
		            JOIN   MS_SKU
		            ON     MS_SKU.STORERKEY             = DM_DOCUMENT_D.STORERKEY
		            AND    MS_SKU.SKU                   = DM_DOCUMENT_D.SKU   
		            AND    MS_SKU.DEL_YN                = 'N'                                                          
		            <if test="storagetype != null and storagetype != ''">
		                AND    MS_SKU.STORAGETYPE             =      #{storagetype}
		            </if>
		            <!-- 협력사 다중선택 -->
		            <if test="vendorMulti != null and vendorMulti.size() > 0">
		                AND MS_SKU.VENDOR IN
		                <foreach collection="vendorMulti" item="v" open="(" close=")" separator=",">
		                    #{v}
		                </foreach>
		            </if>
		            JOIN   MS_CUST           
		            ON     MS_CUST.STORERKEY            = DM_DOCUMENT_H.STORERKEY         
		            AND    MS_CUST.CUSTKEY              = DM_DOCUMENT_H.TO_CUSTKEY 
		            AND    MS_CUST.CUSTTYPE             = DM_DOCUMENT_H.TO_CUSTTYPE
		            <!-- AND    MS_CUST.DEL_YN               = 'N' --> <!-- 2015-11-13 정상권님 요청으로 삭제된 거래처도 보이도록 수정 --> 
		            <if test="saledepartment != null and saledepartment != ''">
		                AND    MS_CUST.SALEDEPARTMENT     =      #{saledepartment}
		            </if>
		            
		            JOIN   MS_CUSTDLVINFO
		            ON     MS_CUSTDLVINFO.STORERKEY     = DM_DOCUMENT_H.STORERKEY
		            AND    MS_CUSTDLVINFO.CUSTTYPE      = DM_DOCUMENT_H.TO_CUSTTYPE
		            AND    MS_CUSTDLVINFO.DLVCUSTKEY    = DM_DOCUMENT_H.TO_CUSTKEY
		            <!-- AND    MS_CUSTDLVINFO.DEL_YN        = 'N' --> <!-- 2015-11-13 정상권님 요청으로 삭제된 거래처도 보이도록 수정 -->
		            LEFT OUTER JOIN MS_EXCEPTION_SKU
		            ON     MS_EXCEPTION_SKU.STORERKEY     = DM_DOCUMENT_D.STORERKEY  
		            AND    MS_EXCEPTION_SKU.DCCODE        = DM_DOCUMENT_D.DCCODE
		            AND    MS_EXCEPTION_SKU.DELIVERYDATE  = DM_DOCUMENT_D.DELIVERYDATE
		            AND    MS_EXCEPTION_SKU.DOCNO         = DM_DOCUMENT_D.DOCNO
		            AND    MS_EXCEPTION_SKU.DOCLINE       = DM_DOCUMENT_D.DOCLINE
		            AND    MS_EXCEPTION_SKU.SKU           = DM_DOCUMENT_D.SKU
		        WHERE  1=1
		            AND    DM_DOCUMENT_D.DCCODE         = #{fixdccode}
		            AND    DM_DOCUMENT_D.DOCTYPE        = 'WD'
		            <!-- 창고.다중검색(필요 시) -->
		            <if test='gOrganizeMulti != null and gOrganizeMulti.length > 0'>
		                AND DM_DOCUMENT_D.ORGANIZE IN
		                <foreach collection="gOrganizeMulti" item="code" open="(" close=")" separator=",">
		                  #{code}
		                </foreach>
		            </if>      
			        <!-- START.권한센터 -->
			        AND EXISTS (SELECT 1
		                          FROM CM_USER_AUTHORITY 
		                         WHERE CM_USER_AUTHORITY.DCCODE    = DM_DOCUMENT_D.DCCODE       
		                           AND CM_USER_AUTHORITY.STORERKEY = DM_DOCUMENT_D.STORERKEY    
		                           AND CM_USER_AUTHORITY.ORGANIZE  = DM_DOCUMENT_D.ORGANIZE     
		                           AND CM_USER_AUTHORITY.AREA      = DM_DOCUMENT_D.AREA         
		                           AND CM_USER_AUTHORITY.STORERKEY = #{gStorerkey}
		                           AND CM_USER_AUTHORITY.USERID    = #{gUserId}
		                           AND CM_USER_AUTHORITY.DCCODE    = #{fixdccode}
		                           AND CM_USER_AUTHORITY.AREA      = #{gArea}   
			 	   	           <!-- 창고.다중검색 -->
			 	   	           <if test='gOrganizeMulti != null and gOrganizeMulti.length > 0'>
			 	   		           AND CM_USER_AUTHORITY.ORGANIZE IN
			 	   		           <foreach collection="gOrganizeMulti" item="code" open="(" close=")" separator=",">
			 	   		             #{code}
			 	   		           </foreach>
			 	   	           </if>                       
		                       )
			        <!-- END.권한센터	-->  
		            
		            <if test="ordergrp != null and ordergrp != ''">
		                AND DM_DOCUMENT_H.OTCO_GRPCD = #{ordergrp}
		            </if>
		            <if test="ordertype != null and ordertype != ''">
		                AND    DM_DOCUMENT_D.ORDERTYPE        =      #{ordertype}
		            </if>
		            <if test="fromDeliverydt != null and fromDeliverydt != ''">
		                AND    DM_DOCUMENT_D.DELIVERYDATE    <![CDATA[>=]]>  #{fromDeliverydt}
		            </if>
		            <if test="toDeliverydt != null and toDeliverydt != ''">
		                AND    DM_DOCUMENT_D.DELIVERYDATE    <![CDATA[<=]]>  #{toDeliverydt}
		            </if>
		
		            <!-- 문서번호 다중선택 -->
		            <if test="docnoMulti != null and docnoMulti.size() > 0">
		                AND DM_DOCUMENT_D.DOCNO IN
		                <foreach collection="docnoMulti" item="doc" open="(" close=")" separator=",">
		                    #{doc}
		                </foreach>
		            </if>
		            
		            <if test="channel != null and channel != ''">
		                AND    DM_DOCUMENT_D.CHANNEL          =     #{channel}
		            </if>
		            <if test="status != null and status != ''">
		                AND    DM_DOCUMENT_D.STATUS           =     #{status}
		            </if>
		            <if test="closeyn != null and closeyn != ''">
		                AND    DM_DOCUMENT_D.OMS_FLAG         =     #{closeyn}
		            </if>
		            <if test="delYn != null and delYn != ''">
		                AND    DM_DOCUMENT_D.DEL_YN       =   #{delYn}
		            </if>
		            <if test="beforeshotage != null and beforeshotage == 'Y'.toString()">
		                AND    DM_DOCUMENT_D.PROCPOSS_YN        =   'R'
		            </if>
		            <if test="beforeshotage != null and beforeshotage == 'N'.toString()">
		                AND    DM_DOCUMENT_D.PROCPOSS_YN <![CDATA[<>]]> 'R'
		            </if>
		            
		            <if test="fromSlipdt != null and fromSlipdt != ''">
		                AND    DM_DOCUMENT_D.DELIVERYDATE    <![CDATA[>=]]>  #{fromSlipdt}
		            </if>
		            <if test="toSlipdt != null and toSlipdt != ''">
		                AND    DM_DOCUMENT_D.DELIVERYDATE    <![CDATA[<=]]>  #{toSlipdt}
		            </if>
		            <!-- AND    DM_DOCUMENT_H.STATUS         <![CDATA[<]]> '90' -->    
		            <!-- 상품 다중선택 -->           
		         	<if test="skuMulti != null and skuMulti != '' ">
						<trim prefix="AND (" suffix=")" prefixOverrides="OR">
							<foreach collection="skuMulti" item="item">
								OR DM_DOCUMENT_D.SKU IN
								<foreach collection="item" item="code" open="(" close=")" separator=",">
									#{code}
					      		</foreach>
					    	</foreach>
					  	</trim>
			        </if>
		
		            
		            <if test="carnoMulti != null and carnoMulti != ''">
					       AND TM_INPLAN.CARNO IN
					       <foreach collection="carnoMulti" item="code" open="(" close=")" separator=",">
					         #{code}
					       </foreach>   
			        </if>
		            
		            GROUP BY DM_DOCUMENT_D.DCCODE
		                    ,DM_DOCUMENT_D.STORERKEY 
		                    ,DM_DOCUMENT_D.ORGANIZE 
		                    ,DM_DOCUMENT_D.AREA 
		                    ,DM_DOCUMENT_D.DELIVERYDATE
		                    ,DM_DOCUMENT_D.DOCNO
		                    ,DM_DOCUMENT_D.DOCLINE
		            ORDER BY DM_DOCUMENT_D.DCCODE
		                    ,DM_DOCUMENT_D.STORERKEY 
		                    ,DM_DOCUMENT_D.ORGANIZE 
		                    ,DM_DOCUMENT_D.AREA 
		                    ,DM_DOCUMENT_D.DELIVERYDATE
		                    ,DM_DOCUMENT_D.DOCNO
		                    ,DM_DOCUMENT_D.DOCLINE
		    ) AA		
    </select>

</mapper>