<?xml version="1.0" encoding="UTF-8"?><!--Converted at: Wed Nov 12 11:33:48 KST 2025-->
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" 
"http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="wdInplanSTOService">
	<select id="getMasterList" resultType="cjfw.wms.wd.dto.WdInplanSTOResDto">
		select /* [wdInplanSTOService.sqlx][wdInplanSTOService.getMasterList][광역출고현황 조회][YeoSeungCheol][2025.11.12] */
		       '0' AS CHECKYN
		      ,FROM_DM_DOCUMENT_H.DCCODE 									AS FROM_DCCODE
		      ,FROM_DM_DOCUMENT_H.ORGANIZE 									AS FROM_ORGANIZE
		      ,FROM_DM_DOCUMENT_H.DELIVERYDATE 								AS SLIPDT
		      ,FROM_DM_DOCUMENT_H.DOCDT 									AS DOCDT
		      ,FROM_DM_DOCUMENT_H.DOCNO 									AS DOCNO
		      ,(SELECT FN_CODEDESCR(FROM_DM_DOCUMENT_H.STORERKEY
		                           ,'ORDERTYPE_STO'
		                           ,FROM_DM_DOCUMENT_H.ORDERTYPE)
		        FROM   DUAL) 												AS ORDERTYPE
		      ,(SELECT FN_GETDCNAME(FROM_DM_DOCUMENT_H.DCCODE) FROM DUAL) 	AS FROM_DCNAME
		      ,FROM_DM_DOCUMENT_H.FROM_CUSTKEY 								AS FROM_CUSTKEY
		      ,(SELECT FN_DESCR_ORGANIZE(FROM_DM_DOCUMENT_H.DCCODE
		                                ,FROM_DM_DOCUMENT_H.FROM_CUSTKEY)
		        FROM   DUAL) 												AS FROM_CUSTNAME
		      ,TO_DM_DOCUMENT_H.DCCODE 										AS TO_DCCODE
		      ,(SELECT FN_GETDCNAME(TO_DM_DOCUMENT_H.DCCODE) FROM DUAL) 	AS TO_DCNAME
		      ,TO_DM_DOCUMENT_H.ORGANIZE 									AS TO_ORGANIZE
		      ,TO_DM_DOCUMENT_H.TO_CUSTKEY 									AS TO_CUSTKEY
		      ,(SELECT FN_DESCR_ORGANIZE(TO_DM_DOCUMENT_H.DCCODE
		                                ,TO_DM_DOCUMENT_H.TO_CUSTKEY)
		        FROM   DUAL) 												AS TO_CUSTNAME
		      ,FN_CODEDESCR(FROM_DM_DOCUMENT_H.STORERKEY
		                           ,'STATUS_WD'
		                           ,(SELECT MIN(DM_DOCUMENT_D.STATUS)
		                             FROM   DM_DOCUMENT_D
		                             WHERE  DM_DOCUMENT_D.DCCODE = FROM_DM_DOCUMENT_H.DCCODE
		                             AND    DM_DOCUMENT_D.DOCTYPE = FROM_DM_DOCUMENT_H.DOCTYPE
		                             AND    DM_DOCUMENT_D.DOCNO   = FROM_DM_DOCUMENT_H.DOCNO
		                             AND    DM_DOCUMENT_D.DEL_YN  = 'N' ) ) AS STATUS
		      ,FROM_DM_DOCUMENT_H.DCCODE 									AS DCCODE
		      ,FROM_DM_DOCUMENT_H.STORERKEY 								AS STORERKEY
		      ,FROM_DM_DOCUMENT_H.DOCTYPE 									AS DOCTYPE
		      ,TM_INPLAN.CARNO 												AS CARNO
		      ,TO_CHAR(TM_INPLAN.DCDEPARTUREDT, 'MM/DD HH24:MI') 			AS DCDEPARTUREDT
		      ,FROM_DM_DOCUMENT_H.DEL_YN                                    AS DEL_YN
		      ,FN_CODEDESCR(FROM_DM_DOCUMENT_H.STORERKEY
		                   ,'CREATIONTYPE_STO'
		                   ,FROM_DM_DOCUMENT_H.SOTYPE) 						AS STOTYPE
		      ,FROM_DM_DOCUMENT_H.MEMO1 									AS MEMO1
          	  , NVL( ( SELECT NVL(TRIM(USER_NM), FROM_DM_DOCUMENT_H.ADDWHO)
                          FROM FRAMEONE_USER
                         WHERE (FRAMEONE_USER.USER_NO = FROM_DM_DOCUMENT_H.ADDWHO
                                OR FRAMEONE_USER.USER_ID = FROM_DM_DOCUMENT_H.ADDWHO)
                           AND ROWNUM = 1 ), FROM_DM_DOCUMENT_H.ADDWHO ) AS ADDWHO    /* 등록자 */
               , NVL( ( SELECT NVL(TRIM(USER_NM), FROM_DM_DOCUMENT_H.EDITWHO)
                          FROM FRAMEONE_USER
                         WHERE (FRAMEONE_USER.USER_NO = FROM_DM_DOCUMENT_H.EDITWHO
                                OR FRAMEONE_USER.USER_ID = FROM_DM_DOCUMENT_H.EDITWHO)
                           AND ROWNUM = 1 ), FROM_DM_DOCUMENT_H.EDITWHO ) AS EDITWHO  /* 수정자 */
               , FROM_DM_DOCUMENT_H.ADDDATE                  AS ADDDATE              /* 등록일시 */
               , FROM_DM_DOCUMENT_H.EDITDATE                 AS EDITDATE             /*수정일시*/
               , FROM_DM_DOCUMENT_H.ADDWHO                   AS ADDWHOID
               , FROM_DM_DOCUMENT_H.EDITWHO                  AS EDITWHOID
		FROM  DM_DOCUMENT_H FROM_DM_DOCUMENT_H
		JOIN   DM_DOCUMENT_H TO_DM_DOCUMENT_H ON TO_DM_DOCUMENT_H.DOCTYPE = 'DP'
			                                  AND    TO_DM_DOCUMENT_H.DEL_YN = 'N'
			                                  AND    TO_DM_DOCUMENT_H.DOCDT = FROM_DM_DOCUMENT_H.DOCDT
			                                  AND    TO_DM_DOCUMENT_H.DOCNO = FROM_DM_DOCUMENT_H.DOCNO
		LEFT   OUTER JOIN TM_INPLAN ON TM_INPLAN.DCCODE = FROM_DM_DOCUMENT_H.DCCODE
			                        AND    TM_INPLAN.STORERKEY = FROM_DM_DOCUMENT_H.STORERKEY
			                        AND    TM_INPLAN.DOCDT = FROM_DM_DOCUMENT_H.DOCDT
			                        AND    TM_INPLAN.DOCNO = FROM_DM_DOCUMENT_H.DOCNO
			                        AND    TM_INPLAN.DELIVERYDT = FROM_DM_DOCUMENT_H.DELIVERYDATE
			                        AND    TM_INPLAN.DOCTYPE = 'WD'
			                        AND    TM_INPLAN.DEL_YN = 'N'
		WHERE 1=1       
			       
		<if test="fromSlipdt != null and fromSlipdt != ''">
		    AND FROM_DM_DOCUMENT_H.DELIVERYDATE	 <![CDATA[>=]]>   #{fromSlipdt}
		</if>		
		<if test="toSlipdt != null and toSlipdt != ''">
		    AND FROM_DM_DOCUMENT_H.DELIVERYDATE	 <![CDATA[<=]]>   #{toSlipdt}
		</if>	    
		<if test="gMultiCourier != null and gMultiCourier != ''">
		    AND FROM_DM_DOCUMENT_H.COURIER 		 =                #{gMultiCourier}
		</if>			
		<if test="fromDocdt != null and fromDocdt != ''">
		    AND FROM_DM_DOCUMENT_H.DOCDT         <![CDATA[>=]]>   #{fromDocdt}
		</if>        
		<if test="toDocdt != null and toDocdt != ''">
		    AND FROM_DM_DOCUMENT_H.DOCDT         <![CDATA[<=]]>   #{toDocdt}
		</if>        	
		<if test="fromDeliverydt != null and fromDeliverydt != ''">
		    AND FROM_DM_DOCUMENT_H.DELIVERYDATE	 <![CDATA[>=]]>   #{fromDeliverydt}
		</if>       		
		<if test="toDeliverydt != null and toDeliverydt != ''">
		    AND FROM_DM_DOCUMENT_H.DELIVERYDATE	 <![CDATA[<=]]>   #{toDeliverydt}
		</if>
				
        <choose>
            <when test="organizeMulti != null and organizeMulti != ''">
                AND FROM_DM_DOCUMENT_H.FROM_CUSTKEY IN
               <foreach collection="organizeMulti" item="code" open="(" close=")" separator=",">
                 #{code}
               </foreach>
            </when>
            <otherwise>
                 <if test="fromDccode != null and fromDccode != ''">
                    AND FROM_DM_DOCUMENT_H.FROM_CUSTKEY LIKE #{fromDccode} || '%'
                </if>
            </otherwise>
        </choose>
        <choose>
            <when test="organize2Multi != null and organize2Multi != ''">
                AND TO_DM_DOCUMENT_H.TO_CUSTKEY IN
               <foreach collection="organize2Multi" item="code" open="(" close=")" separator=",">
                 #{code}
               </foreach>
            </when>
            <otherwise>
                 <if test="toDccode != null and toDccode != ''">
                    AND TO_DM_DOCUMENT_H.TO_CUSTKEY LIKE #{toDccode} || '%'
                </if>
            </otherwise>
        </choose>
		           
		<if test="status != null and status != ''">
		    AND FROM_DM_DOCUMENT_H.STATUS         =            #{status}
		</if>
		
		<!-- 문서번호 다중선택 -->
        <if test="docnoMulti != null and docnoMulti != ''">
           AND FROM_DM_DOCUMENT_H.DOCNO IN
           <foreach collection="docnoMulti" item="code" open="(" close=")" separator=",">
             #{code}
           </foreach>   
        </if>        	     
		AND   FROM_DM_DOCUMENT_H.STORERKEY =  #{gStorerkey}
		AND   FROM_DM_DOCUMENT_H.DOCTYPE   = 'WD'
		AND   FROM_DM_DOCUMENT_H.DEL_YN    = 'N'
		AND   FROM_DM_DOCUMENT_H.WORKPROCESSCODE = 'STO'
		AND   EXISTS (SELECT 1
		              FROM   DM_DOCUMENT_D 
		              WHERE  DM_DOCUMENT_D.DCCODE = FROM_DM_DOCUMENT_H.DCCODE
		              AND    DM_DOCUMENT_D.DOCTYPE = FROM_DM_DOCUMENT_H.DOCTYPE
		              AND    DM_DOCUMENT_D.DOCNO   = FROM_DM_DOCUMENT_H.DOCNO
		              --AND   (DM_DOCUMENT_D.WORKPROCESSCODE = 'STO' OR DM_DOCUMENT_D.IF_SEND_TYPE = 'STOFS')
			          <if test="delYn == &quot;N&quot;">
			          	AND    DM_DOCUMENT_D.DEL_YN       =  	'N'	
			          </if>
			          
					  <if test="delYn == &quot;Y&quot;">
					  	AND    DM_DOCUMENT_D.DEL_YN <![CDATA[<>]]> 'N'
					  </if>
			    	  <if test="sku != null and sku != '' ">
                        <if test="skuMulti != null and skuMulti.size() > 0">
                            <trim prefix="AND (" suffix=")" prefixOverrides="OR">
                                <foreach collection="skuMulti" item="item">
                                    OR DM_DOCUMENT_D.SKU IN
                                    <foreach collection="item" item="code" open="(" close=")" separator=",">
                                        #{code}      
                                    </foreach>
                                </foreach>
                            </trim>                                             
                        </if>
                      </if>
			    	  <if test="storagetype != null and storagetype != ''">
			    	  AND   EXISTS (SELECT 1
			    	  				FROM   MS_SKU 
			    	  				WHERE  MS_SKU.STORERKEY = DM_DOCUMENT_D.STORERKEY
			    	  				AND    MS_SKU.SKU       = DM_DOCUMENT_D.SKU                   
       		    	  				AND   MS_SKU.DEL_YN     = 'N'
       		    	  				AND   MS_SKU.STORAGETYPE = #{storagetype})
       		    	  </if>    
       		    	  )

		<if test="serialno != null and serialno != ''">
		AND EXISTS (SELECT 1
				    FROM    DM_DOCUMENT_D JOIN WD_INPLAN 	ON    WD_INPLAN.DCCODE             = DM_DOCUMENT_D.DCCODE         
															AND   WD_INPLAN.STORERKEY          = DM_DOCUMENT_D.STORERKEY 
															AND   WD_INPLAN.ORGANIZE           = DM_DOCUMENT_D.ORGANIZE                      
													        AND   WD_INPLAN.AREA               = DM_DOCUMENT_D.AREA              
															AND   WD_INPLAN.DOCDT              = DM_DOCUMENT_D.DOCDT         
															AND   WD_INPLAN.DOCNO              = DM_DOCUMENT_D.DOCNO         
															AND   WD_INPLAN.DOCLINE            = DM_DOCUMENT_D.DOCLINE  
										  JOIN ST_SNINFOSLIP ST_SERIALINFO  ON     ST_SERIALINFO.DCCODE         = WD_INPLAN.DCCODE            
																	        AND    ST_SERIALINFO.STORERKEY      = WD_INPLAN.STORERKEY 
																	        AND    ST_SERIALINFO.ORGANIZE       = WD_INPLAN.ORGANIZE            
																	        AND    ST_SERIALINFO.SKU            = WD_INPLAN.SKU
																			AND    ST_SERIALINFO.DOCTYPE        = WD_INPLAN.DOCTYPE
																			AND    ST_SERIALINFO.SLIPDT         = WD_INPLAN.SLIPDT
																			AND    ST_SERIALINFO.SLIPNO         = WD_INPLAN.SLIPNO
																			AND    ST_SERIALINFO.SLIPLINE       = WD_INPLAN.SLIPLINE
																			AND    ST_SERIALINFO.DOCTYPE 	    = 'WD'
																			AND    ST_SERIALINFO.DEL_YN         = 'N'
																        	<if test="serialno != null and serialno != ''">
																        		AND    ST_SERIALINFO.SERIALNO         =      #{serialno}
																        	</if>
																			<if test="blno != null and blno != ''">
																				AND    ST_SERIALINFO.CONVSERIALNO     =      #{blno}
																			</if>
																			<if test="contractcompany != null and contractcompany != ''">
																				AND    ST_SERIALINFO.CONTRACTCUSTKEY   =      #{contractcompany}
																			</if>
		            WHERE  DM_DOCUMENT_D.DCCODE = FROM_DM_DOCUMENT_H.DCCODE
		            AND    DM_DOCUMENT_D.DOCTYPE = FROM_DM_DOCUMENT_H.DOCTYPE
		            AND    DM_DOCUMENT_D.DOCNO   = FROM_DM_DOCUMENT_H.DOCNO )    
		</if>
        ORDER BY FROM_DM_DOCUMENT_H.DCCODE
                ,FROM_DM_DOCUMENT_H.STORERKEY
                ,FROM_DM_DOCUMENT_H.DELIVERYDATE
                ,FROM_DM_DOCUMENT_H.DOCDT
                ,FROM_DM_DOCUMENT_H.DOCNO
                ,FROM_DM_DOCUMENT_H.DOCTYPE
                ,FROM_DM_DOCUMENT_H.ORDERTYPE
                ,TM_INPLAN.CARNO
	</select>  
    
	<select id="getMasterListTab1" parameterType="cjfw.wms.wd.dto.WdInplanSTOReqDto" resultType="cjfw.wms.wd.dto.WdInplanSTOResTab1Dto">
	SELECT /* [wdInplanSTOService.sqlx][wdInplanSTOService.getMasterListTab1][광역출고현황 - 주문현황][YeoSeungCheol][2025.11.12] */
	       FROMSTO.DCCODE                                                           AS DCCODE
	      ,FROMSTO.STORERKEY     													AS STORERKEY
	      ,FROMSTO.ORGANIZE 														AS ORGANIZE
	      ,FROMSTO.AREA 															AS AREA
	      ,FROMSTO.DOCDT 															AS DOCDT
	      ,FROMSTO.DOCNO 															AS DOCNO
	      ,FROMSTO.DOCTYPE 															AS DOCTYPE
	      ,FROMSTO.DOCLINE 															AS DOCLINE
	      ,FROMSTO.SKU 																AS SKU
	      ,MS_SKU.DESCRIPTION 														AS SKUNAME
	      ,FN_CODEDESCR(FROMSTO.STORERKEY, 'PUTAWAYTYPE', FROMSTO.CHANNEL)			AS CHANNEL_DMD
	      ,FN_CODEDESCR(FROMSTO.STORERKEY, 'STORAGETYPE', MS_SKU.STORAGETYPE) 		AS STORAGETYPE
	      ,FROMSTO.STORERORDERQTY 													AS ORDERQTY_WD
	      ,FN_UOMCAL(FROMSTO.BUNMO, FROMSTO.BUNJA, FROMSTO.PROCESSQTY) 				AS DISTRIBUTEQTY_WD
	      ,FN_UOMCAL(FROMSTO.BUNMO, FROMSTO.BUNJA, FROMSTO.WORKQTY) 				AS WORKQTY_WD
	      ,FN_UOMCAL(FROMSTO.BUNMO, FROMSTO.BUNJA, FROMSTO.INSPECTQTY) 				AS INSPECTQTY
	      ,FN_UOMCAL(TOSTO.BUNMO, TOSTO.BUNJA, TOSTO.INSPECTQTY) 					AS TOSTO_INSPECTQTY
	      ,FROMSTO.STORERCONFIRMQTY 												AS CONFIRMQTY
	      ,TOSTO.STORERCONFIRMQTY 													AS TOSTO_CONFIRMQTY
	      ,FROMSTO.STORERUOM 														AS UOM_STO
	      ,CASE WHEN MS_UOM.BUNJA IS NULL THEN 0
	            ELSE FROMSTO.CONFIRMQTY 
	               * MS_UOM.BUNMO
                   / MS_UOM.BUNJA
           END																		AS CONFIRMWEIGHT
	      ,CASE WHEN MS_UOM.BUNJA IS NULL THEN 0
	            ELSE TOSTO.CONFIRMQTY 
	               * MS_UOM.BUNMO
                   / MS_UOM.BUNJA
           END																		AS TOSTO_CONFIRMWEIGHT
	      ,FN_CODEDESCR(FROMSTO.STORERKEY, 'STATUS_WD', FROMSTO.STATUS) 			AS STATUS
	      ,FN_CODEDESCR(TOSTO.STORERKEY, 'STATUS_DP', TOSTO.STATUS) 				AS TOSTO_STATUS
	      ,FROMSTO.PLANT 															AS PLANT
	      ,'[' || FROMSTO.PLANT || ']' || FN_DESCR_PLANT(FROMSTO.PLANT) 			AS PLANT_DESCR
	      ,FROMSTO.DEL_YN															AS DEL_YN
	  FROM DM_DOCUMENT_D FROMSTO
	  JOIN MS_SKU
	    ON MS_SKU.STORERKEY = FROMSTO.STORERKEY
	   AND MS_SKU.SKU       = FROMSTO.SKU
	   AND MS_SKU.DEL_YN 	= 'N'
  	 <!-- 상품 다중선택 -->
    	<if test="sku != null and sku != '' ">
            <if test="skuMulti != null and skuMulti.size() > 0">
                <trim prefix="AND (" suffix=")" prefixOverrides="OR">
                    <foreach collection="skuMulti" item="item">
                        OR MS_SKU.SKU IN
                        <foreach collection="item" item="code" open="(" close=")" separator=",">
                            #{code}      
                        </foreach>
                    </foreach>
                </trim>                                             
            </if>
        </if>
    	<if test="storagetype != null and storagetype != ''"> 
       		AND MS_SKU.STORAGETYPE      = #{storagetype}             
    	</if>
    	
      LEFT OUTER JOIN 
           MS_UOM
      ON   MS_UOM.STORERKEY        = FROMSTO.STORERKEY
      AND  MS_UOM.SKU              = FROMSTO.SKU
      AND  MS_UOM.BASEUOM          = FROMSTO.UOM
      AND  MS_UOM.UOM              = 'KG'
	  JOIN DM_DOCUMENT_D TOSTO
	    ON TOSTO.DCCODE 		   = #{toDccode}
	   AND TOSTO.STORERKEY 		   = FROMSTO.STORERKEY
	   AND TOSTO.DOCTYPE           = 'DP'
	   AND TOSTO.DOCDT 			   = FROMSTO.DOCDT
	   AND TOSTO.DOCNO 			   = FROMSTO.DOCNO
	   AND TOSTO.DOCLINE 		   = FROMSTO.DOCLINE
	   AND TOSTO.WORKPROCESSCODE   = 'STO'
	   
	<if test="delYn == &quot;N&quot;">
		AND    TOSTO.DEL_YN       =  	'N'
	</if>
	
	<if test="delYn == &quot;Y&quot;">
		AND    TOSTO.DEL_YN &lt;&gt; 'N'
	</if>
	 
	 WHERE FROMSTO.WORKPROCESSCODE = 'STO'
	   AND FROMSTO.DCCODE          = #{dccode}
	   AND FROMSTO.STORERKEY       = #{gStorerkey}
	   AND FROMSTO.DOCTYPE         = #{doctype}
	   AND FROMSTO.DOCDT           = #{docdt}
	   AND FROMSTO.DOCNO           = #{docno}
	   
	 <if test="delYn == &quot;N&quot;"> 
	<!--	<if test="delYn == 'Y'.toString()">-->
		AND    FROMSTO.DEL_YN       =  	'N'
	</if>
	
	<if test="delYn == &quot;Y&quot;">
		AND    FROMSTO.DEL_YN &lt;&gt; 'N'
	</if>
	   
     ORDER BY FROMSTO.DOCLINE, FROMSTO.SKU
	</select>
	
	
	<select id="getMasterListTab2" parameterType="cjfw.wms.wd.dto.WdInplanSTOReqDto" resultType="cjfw.wms.wd.dto.WdInplanSTOResTab2Dto">
        SELECT /* [wdInplanSTOService.sqlx][wdInplanSTOService.getMasterListTab2][광역출고현황 - 이력현황][YeoSeungCheol][2025.11.12] */
		       DM_DOCUMENT_D.DCCODE                                                          AS DCCODE
		      ,DM_DOCUMENT_D.STORERKEY                                                       AS STORERKEY
		      ,DM_DOCUMENT_D.ORGANIZE                                                        AS ORGANIZE         
              ,DM_DOCUMENT_D.AREA                                                            AS AREA     
		      ,DM_DOCUMENT_D.DOCDT                                                           AS DOCDT
              ,DM_DOCUMENT_D.DOCNO                                                           AS DOCNO
              ,DM_DOCUMENT_D.DOCTYPE                                                         AS DOCTYPE
              ,DM_DOCUMENT_D.DOCLINE                                                         AS DOCLINE
              ,DM_DOCUMENT_D.SKU                                                             AS SKU
              ,MS_SKU.DESCRIPTION                                                            AS SKUNAME      
              ,DM_DOCUMENT_D.STORERORDERQTY                                                  AS ORDERQTY
              ,FN_UOMCAL(DM_DOCUMENT_D.BUNMO,DM_DOCUMENT_D.BUNJA,DM_DOCUMENT_D.PROCESSQTY)   AS PROCESSQTY
		      ,FN_UOMCAL(DM_DOCUMENT_D.BUNMO,DM_DOCUMENT_D.BUNJA,DM_DOCUMENT_D.WORKQTY)      AS WORKQTY
		      ,FN_UOMCAL(DM_DOCUMENT_D.BUNMO,DM_DOCUMENT_D.BUNJA,DM_DOCUMENT_D.INSPECTQTY)   AS INSPECTQTY
              ,DM_DOCUMENT_D.STORERCONFIRMQTY                                                AS CONFIRMQTY
              ,DM_DOCUMENT_D.STORERUOM                                                       AS UOM
              ,DM_DOCUMENT_D.CONFIRMWEIGHT                                                   AS CONFIRMWEIGHT
              ,FN_CODEDESCR(DM_DOCUMENT_D.STORERKEY,'STATUS_WD', ST_SERIALINFO.STATUS) AS STATUS
              ,ST_SERIALINFO.LOTTABLE01                                                AS LOTTABLE01
              ,FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, ST_SERIALINFO.LOTTABLE01, 'N')||'/'||MS_SKU.DURATION AS DURATION_TERM
              ,ST_SERIALINFO.SERIALNO                                                  AS SERIALNO
              ,ST_SERIALINFO.SERIALLEVEL                                               AS SERIALLEVEL
              ,ST_SERIALINFO.SERIALTYPE                                                AS SERIALTYPE
              ,ST_SERIALINFO.FACTORYNAME                                               AS FACTORYNAME
              ,ST_SERIALINFO.PLACEOFORIGIN                                             AS PLACEOFORIGIN
              ,DM_DOCUMENT_D.PLANT													   AS PLANT
        	  ,'['||DM_DOCUMENT_D.PLANT||']'||FN_DESCR_PLANT(DM_DOCUMENT_D.PLANT)      AS PLANT_DESCR
        	  ,ST_SERIALINFO.CONVSERIALNO       												  AS CONVSERIALNO
              ,ST_SERIALINFO.BUTCHERYDT															  AS BUTCHERYDT
              ,ST_SERIALINFO.CONTRACTCUSTKEY                                                           AS CONTRACTCOMPANY
              ,(SELECT DESCRIPTION FROM MS_CUST 
                WHERE  MS_CUST.STORERKEY = ST_SERIALINFO.STORERKEY
                AND    MS_CUST.CUSTKEY   = ST_SERIALINFO.CONTRACTCUSTKEY
                AND    ROWNUM = 1 )                                                               AS CONTRACTCOMPANYNAME
              ,ST_SERIALINFO.FROMVALIDDT														  AS FROMVALIDDT
              ,ST_SERIALINFO.TOVALIDDT															  AS TOVALIDDT
              ,FN_CODEDESCR(DM_DOCUMENT_D.STORERKEY,'CONTRACTTYPE_SN', ST_SERIALINFO.CONTRACTTYPE)   AS CONTRACTTYPE
              ,ST_SERIALINFO.STOCKID																AS BARCODE
              ,ST_SERIALINFO.ORDERQTY           												  AS SERIALORDERQTY
              ,ST_SERIALINFO.CONFIRMQTY                											  AS SERIALINSPECTQTY  
              ,ST_SERIALINFO.ORDERQTY - ST_SERIALINFO.CONFIRMQTY								  AS SERIALSCANWEIGHT
              ,DM_DOCUMENT_D.DEL_YN																  AS DEL_YN
			  ,'0'         AS AVGWEIGHT       /* 평균중량     */
			  ,'0'         AS CALORDERBOX     /* 환산주문박스 */		
			  ,'0'         AS CALCONFIRMBOX   /* 환산확정박스 */
			  ,'0'         AS REALBOX         /* 실박스       */              
               
		FROM   DM_DOCUMENT_D           
		
        <if test="serialno != null and serialno != ''">
			JOIN   ST_SNINFOSLIP ST_SERIALINFO           
	        ON     ST_SERIALINFO.DCCODE         = DM_DOCUMENT_D.DCCODE            
	        AND    ST_SERIALINFO.STORERKEY      = DM_DOCUMENT_D.STORERKEY 
	        AND    ST_SERIALINFO.ORGANIZE       = DM_DOCUMENT_D.ORGANIZE            
	        AND    ST_SERIALINFO.SKU            = DM_DOCUMENT_D.SKU     
			<!-- AND    ST_SERIALINFO.STOCKID        = WD_INPLAN.STOCKID-->
			AND    ST_SERIALINFO.DOCTYPE        = DM_DOCUMENT_D.DOCTYPE
			AND    ST_SERIALINFO.DOCDT          = DM_DOCUMENT_D.DOCDT
			AND    ST_SERIALINFO.DOCNO          = DM_DOCUMENT_D.DOCNO
			AND    ST_SERIALINFO.DOCLINE        = DM_DOCUMENT_D.DOCLINE
			AND    ST_SERIALINFO.DOCTYPE = 'WD'
			AND    ST_SERIALINFO.DEL_YN         = 'N'
		</if>
		<if test="serialno == null or serialno == ''">
			LEFT OUTER JOIN   ST_SNINFOSLIP ST_SERIALINFO           
	        ON     ST_SERIALINFO.DCCODE         = DM_DOCUMENT_D.DCCODE            
	        AND    ST_SERIALINFO.STORERKEY      = DM_DOCUMENT_D.STORERKEY 
	        AND    ST_SERIALINFO.ORGANIZE       = DM_DOCUMENT_D.ORGANIZE            
	        AND    ST_SERIALINFO.SKU            = DM_DOCUMENT_D.SKU     
			<!-- AND    ST_SERIALINFO.STOCKID        = WD_INPLAN.STOCKID-->
			AND    ST_SERIALINFO.DOCTYPE        = DM_DOCUMENT_D.DOCTYPE
			AND    ST_SERIALINFO.DOCDT          = DM_DOCUMENT_D.DOCDT
			AND    ST_SERIALINFO.DOCNO          = DM_DOCUMENT_D.DOCNO
			AND    ST_SERIALINFO.DOCLINE        = DM_DOCUMENT_D.DOCLINE
			AND    ST_SERIALINFO.DOCTYPE = 'WD'
			AND    ST_SERIALINFO.DEL_YN         = 'N'
		</if>		
		
		<!-- LEFT OUTER JOIN MS_CUST
		ON     ST_SERIALINFO.WD_CUSTKEY     = MS_CUST.CUSTKEY
		AND    ST_SERIALINFO.STORERKEY      = MS_CUST.STORERKEY
		AND    MS_CUST.CUSTTYPE             = 'P' -->
		
		JOIN   MS_SKU 
		ON     MS_SKU.STORERKEY             =  DM_DOCUMENT_D.STORERKEY         
		AND    MS_SKU.SKU                   =  DM_DOCUMENT_D.SKU
		AND    MS_SKU.DEL_YN                = 'N'		
		AND    MS_SKU.SERIALYN              = 'Y'  
		<!-- 상품 다중선택 -->
    	<if test="sku != null and sku != '' ">
            <if test="skuMulti != null and skuMulti.size() > 0">
                <trim prefix="AND (" suffix=")" prefixOverrides="OR">
                    <foreach collection="skuMulti" item="item">
                        OR MS_SKU.SKU IN
                        <foreach collection="item" item="code" open="(" close=")" separator=",">
                            #{code}      
                        </foreach>
                    </foreach>
                </trim>                                             
            </if>
        </if>
    	
    	<if test="storagetype != null and storagetype != ''">
    		AND    MS_SKU.STORAGETYPE = #{storagetype}
    	</if>
		            
		WHERE  DM_DOCUMENT_D.DCCODE	        =  #{gDccode}
		AND    DM_DOCUMENT_D.STORERKEY	    =  #{gStorerkey}
		AND    DM_DOCUMENT_D.DOCDT	        =  #{docdt}
		AND    DM_DOCUMENT_D.DOCNO	        =  #{docno}
		AND    DM_DOCUMENT_D.DOCTYPE        =  #{doctype}
		
		<if test="serialno != null and serialno != ''">
			AND    ST_SERIALINFO.SERIALNO   =  #{serialno}
		</if>
		
		<if test="blno != null and blno != ''">
			AND    ST_SERIALINFO.CONVSERIALNO     =      #{blno}
		</if>
		
		<if test="contractcompany != null and contractcompany != ''">
			AND    ST_SERIALINFO.CONTRACTCUSTKEY   =      #{contractcompany}
		</if>
		  
		<if test="delYn == &quot;N&quot;">
			AND    DM_DOCUMENT_D.DEL_YN       =  	'N'
		</if>
		
		<if test="delYn == &quot;Y&quot;">
			AND    DM_DOCUMENT_D.DEL_YN &lt;&gt; 'N'
		</if>   
		 
		ORDER BY DM_DOCUMENT_D.DOCLINE
		        ,DM_DOCUMENT_D.SKU 
		
	</select>
	
	<select id="getMasterListTab3" parameterType="cjfw.wms.wd.dto.WdInplanSTOReqDto" resultType="cjfw.wms.wd.dto.WdInplanSTOResTab3Dto">
		SELECT /* [wdInplanSTOService.sqlx][wdInplanSTOService.getMasterListTab3][광역출고현황 - 출고이력정보][YeoSeungCheol][2025.11.12] */
		           WD_TASK.DCCODE                                                           AS DCCODE
		          ,WD_TASK.STORERKEY                                                        AS STORERKEY
		          ,WD_TASK.ORGANIZE                                                         AS ORGANIZE
		          ,WD_TASK.AREA                                                             AS AREA
		          ,WD_TASK.DOCDT                                                            AS DOCDT
		          ,WD_TASK.DOCNO                                                            AS DOCNO
		          ,WD_TASK.DOCLINE                                                          AS DOCLINE
		          ,WD_TASK.SKU                                                              AS SKU
		          ,MS_SKU.DESCRIPTION                                                       AS SKUNAME
		          ,WD_TASK.LOC                                                              AS LOC
		          ,CM_LOT.LOTTABLE01                                                        AS LOTTABLE01
		          ,FN_UOMCAL(WD_TASK.BUNMO, WD_TASK.BUNJA, WD_TASK.PROCESSQTY)              AS PROCESSQTY
		          ,FN_UOMCAL(WD_TASK.BUNMO, WD_TASK.BUNJA, WD_TASK.WORKQTY)                 AS WORKQTY
		          ,FN_UOMCAL(WD_TASK.BUNMO, WD_TASK.BUNJA, WD_TASK.INSPECTQTY)              AS INSPECTQTY
		          ,FN_UOMCAL(WD_TASK.BUNMO, WD_TASK.BUNJA, WD_TASK.CONFIRMQTY)              AS CONFIRMQTY
		          ,WD_TASK.UOM                                                              AS UOM
		      FROM WD_TASK
		      JOIN MS_SKU
		        ON MS_SKU.STORERKEY = WD_TASK.STORERKEY
		       AND MS_SKU.SKU       = WD_TASK.SKU
		       AND MS_SKU.DEL_YN     = 'N'
		       
		<!-- 상품 다중선택 -->
    	<if test="sku != null and sku != '' ">
            <if test="skuMulti != null and skuMulti.size() > 0">
                <trim prefix="AND (" suffix=")" prefixOverrides="OR">
                    <foreach collection="skuMulti" item="item">
                        OR MS_SKU.SKU IN
                        <foreach collection="item" item="code" open="(" close=")" separator=",">
                            #{code}      
                        </foreach>
                    </foreach>
                </trim>                                             
            </if>
        </if>
		      JOIN CM_LOT
		        ON CM_LOT.STORERKEY = WD_TASK.STORERKEY
		       AND CM_LOT.LOT       = WD_TASK.LOT            
		WHERE  WD_TASK.DCCODE	        =  #{gDccode}
		AND    WD_TASK.STORERKEY	    =  #{gStorerkey}
		AND    WD_TASK.DOCDT	        =  #{docdt}
		AND    WD_TASK.DOCNO	        =  #{docno}
		ORDER BY WD_TASK.DOCLINE
		        ,WD_TASK.SKU 
		
	</select>	
    
    <select id="getExcellist" resultType="WdInplanSTOResExcelDto">	    
        SELECT /* [wdInplanSTOService.sqlx][getExcellist][광역출고현황 - 엑셀][공두경][2026.02.01] */              
               '0'                                                                                       AS CHECKYN            
               ,FROM_DM_DOCUMENT_H.DCCODE                                                                AS FROM_DCCODE                  
               ,FROM_DM_DOCUMENT_H.ORGANIZE                                                              AS FROM_ORGANIZE
               ,WD_INPLAN.SLIPDT                                                                         AS SLIPDT
               ,FROM_DM_DOCUMENT_H.DOCDT                                                                 AS DOCDT
               ,FROM_DM_DOCUMENT_H.DOCNO                                                                 AS DOCNO
               ,FN_CODEDESCR(FROM_DM_DOCUMENT_H.STORERKEY, 'ORDERTYPE_WD', FROM_DM_DOCUMENT_H.ORDERTYPE) AS ORDERTYPE
               ,FN_GETDCNAME(FROM_DM_DOCUMENT_H.DCCODE)                                                  AS FROM_DCNAME
               ,FROM_DM_DOCUMENT_H.FROM_CUSTKEY															 AS FROM_CUSTKEY
               ,FN_DESCR_ORGANIZE(FROM_DM_DOCUMENT_H.DCCODE, FROM_DM_DOCUMENT_H.FROM_CUSTKEY)            AS FROM_CUSTNAME
               ,TO_DM_DOCUMENT_H.DCCODE                                                                  AS TO_DCCODE
               ,FN_GETDCNAME(TO_DM_DOCUMENT_H.DCCODE)                                                    AS TO_DCNAME
               ,TO_DM_DOCUMENT_H.ORGANIZE                                                                AS TO_ORGANIZE
               ,TO_DM_DOCUMENT_H.TO_CUSTKEY															     AS TO_CUSTKEY               
               ,FN_DESCR_ORGANIZE(TO_DM_DOCUMENT_H.DCCODE, TO_DM_DOCUMENT_H.TO_CUSTKEY)                  AS TO_CUSTNAME
               ,FN_CODEDESCR(FROM_DM_DOCUMENT_H.STORERKEY, 'STATUS_WD', FROM_DM_DOCUMENT_H.STATUS)       AS STATUS
               ,FROM_DM_DOCUMENT_H.DCCODE                                                                AS DCCODE
               ,FROM_DM_DOCUMENT_H.STORERKEY                                                             AS STORERKEY
               ,FROM_DM_DOCUMENT_H.DOCTYPE                                                               AS DOCTYPE
               ,TM_INPLAN.CARNO                                                                          AS CARNO
               ,TO_CHAR(TM_INPLAN.DCDEPARTUREDT, 'MM/DD HH24:MI')                                        AS DCDEPARTUREDT
               
               ,DM_DOCUMENT_D.DOCLINE                													 AS DOCLINE
               ,DM_DOCUMENT_D.SKU                 													     AS SKU
               ,MS_SKU.DESCRIPTION                                                                       AS SKUNAME
               ,FN_CODEDESCR(DM_DOCUMENT_D.STORERKEY, 'PUTAWAYTYPE', DM_DOCUMENT_D.CHANNEL)   			 AS CHANNEL
               ,FN_CODEDESCR(DM_DOCUMENT_D.STORERKEY, 'STORAGETYPE', MS_SKU.STORAGETYPE)   				 AS STORAGETYPE
               ,DM_DOCUMENT_D.STORERORDERQTY              												 AS ORDERQTY
               ,FN_UOMCAL(DM_DOCUMENT_D.BUNMO, DM_DOCUMENT_D.BUNJA, DM_DOCUMENT_D.PROCESSQTY)            AS PROCESSQTY
               ,FN_UOMCAL(DM_DOCUMENT_D.BUNMO, DM_DOCUMENT_D.BUNJA, DM_DOCUMENT_D.WORKQTY)     		 	 AS WORKQTY
               ,FN_UOMCAL(DM_DOCUMENT_D.BUNMO, DM_DOCUMENT_D.BUNJA, DM_DOCUMENT_D.INSPECTQTY)     		 AS INSPECTQTY
               ,FN_UOMCAL(TOSTO.BUNMO, TOSTO.BUNJA, TOSTO.INSPECTQTY)      								 AS TOSTO_INSPECTQTY
               ,DM_DOCUMENT_D.STORERCONFIRMQTY             												 AS CONFIRMQTY
               ,TOSTO.STORERCONFIRMQTY              													 AS TOSTO_CONFIRMQTY
               ,DM_DOCUMENT_D.STORERUOM               													 AS UOM
               ,CASE WHEN MS_UOM.BUNJA IS NULL THEN 0              
             		 ELSE DM_DOCUMENT_D.CONFIRMQTY * MS_UOM.BUNMO / MS_UOM.BUNJA            
         		 END                  																	 AS CONFIRMWEIGHT
               ,CASE WHEN MS_UOM.BUNJA IS NULL THEN 0              
                     ELSE TOSTO.CONFIRMQTY * MS_UOM.BUNMO / MS_UOM.BUNJA            
                 END                  																	 AS TOSTO_CONFIRMWEIGHT
               ,FN_CODEDESCR(DM_DOCUMENT_D.STORERKEY, 'STATUS_WD', DM_DOCUMENT_D.STATUS)    			 AS STATUS
               ,FN_CODEDESCR(TOSTO.STORERKEY, 'STATUS_DP', TOSTO.STATUS)     							 AS TOSTO_STATUS
               ,DM_DOCUMENT_D.PLANT                														 AS PLANT
               ,'[' || DM_DOCUMENT_D.PLANT || ']' || FN_DESCR_PLANT(DM_DOCUMENT_D.PLANT)                 AS PLANT_DESCR
          	   , NVL( ( SELECT NVL(TRIM(USER_NM), FROM_DM_DOCUMENT_H.ADDWHO)
                          FROM FRAMEONE_USER
                         WHERE (FRAMEONE_USER.USER_NO = FROM_DM_DOCUMENT_H.ADDWHO
                                OR FRAMEONE_USER.USER_ID = FROM_DM_DOCUMENT_H.ADDWHO)
                           AND ROWNUM = 1 ), FROM_DM_DOCUMENT_H.ADDWHO )                                 AS ADDWHO    /* 등록자 */
               , NVL( ( SELECT NVL(TRIM(USER_NM), FROM_DM_DOCUMENT_H.EDITWHO)
                          FROM FRAMEONE_USER
                         WHERE (FRAMEONE_USER.USER_NO = FROM_DM_DOCUMENT_H.EDITWHO
                                OR FRAMEONE_USER.USER_ID = FROM_DM_DOCUMENT_H.EDITWHO)
                           AND ROWNUM = 1 ), FROM_DM_DOCUMENT_H.EDITWHO )                                AS EDITWHO  /* 수정자 */
               , FROM_DM_DOCUMENT_H.ADDDATE                                                              AS ADDDATE              /* 등록일시 */
               , FROM_DM_DOCUMENT_H.EDITDATE                                                             AS EDITDATE             /*수정일시*/
          	   
        FROM   DM_DOCUMENT_H FROM_DM_DOCUMENT_H   
         
        JOIN   DM_DOCUMENT_H TO_DM_DOCUMENT_H
        ON     TO_DM_DOCUMENT_H.DOCTYPE     = 'DP'
        <if test="toDccode != null and toDccode != ''">
            AND TO_DM_DOCUMENT_H.TO_CUSTKEY IN
                              (SELECT TRIM(REGEXP_SUBSTR(VAL,'[^,]+',1,LEVEL)) AS VAL
                                            FROM (SELECT #{toDccode} AS VAL FROM DUAL) A
                                         CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
        </if>          
        <!-- From창고.다중검색 -->
        <if test="organize2Multi != null and organize2Multi != ''">    
           AND TO_DM_DOCUMENT_H.ORGANIZE IN
           <foreach collection="organize2Multi" item="code" open="(" close=")" separator=",">
             #{code}
           </foreach>
        </if> 
        AND    TO_DM_DOCUMENT_H.DEL_YN      = 'N'                 
        AND    TO_DM_DOCUMENT_H.DELIVERYDATE       = FROM_DM_DOCUMENT_H.DELIVERYDATE                
        AND    TO_DM_DOCUMENT_H.DOCNO       = FROM_DM_DOCUMENT_H.DOCNO                  
        <!-- AND    TO_DM_DOCUMENT_H.FROM_CUSTKEY  = FROM_DM_DOCUMENT_H.DCCODE -->
         
        JOIN   DM_DOCUMENT_D         
        ON     DM_DOCUMENT_D.DCCODE          = FROM_DM_DOCUMENT_H.DCCODE                                  
        AND    DM_DOCUMENT_D.STORERKEY       = FROM_DM_DOCUMENT_H.STORERKEY               
        AND    DM_DOCUMENT_D.ORGANIZE        = FROM_DM_DOCUMENT_H.ORGANIZE                                 
        AND    DM_DOCUMENT_D.DELIVERYDATE           = FROM_DM_DOCUMENT_H.DELIVERYDATE                                  
        AND    DM_DOCUMENT_D.DOCNO           = FROM_DM_DOCUMENT_H.DOCNO                                                                                      
        AND    DM_DOCUMENT_D.DOCTYPE         = FROM_DM_DOCUMENT_H.DOCTYPE        
        <if test="delYn == &quot;N&quot;">
            AND    DM_DOCUMENT_D.DEL_YN       =     'N' 
        </if>
        <if test="delYn == &quot;Y&quot;">
            AND    DM_DOCUMENT_D.DEL_YN <![CDATA[<>]]> 'N'
        </if>                             
        LEFT JOIN  WD_INPLAN
		ON    WD_INPLAN.DCCODE             = DM_DOCUMENT_D.DCCODE         
		AND   WD_INPLAN.STORERKEY          = DM_DOCUMENT_D.STORERKEY 
		AND   WD_INPLAN.ORGANIZE           = DM_DOCUMENT_D.ORGANIZE                      
        AND   WD_INPLAN.AREA               = DM_DOCUMENT_D.AREA              
		AND   WD_INPLAN.SLIPDT              = DM_DOCUMENT_D.DELIVERYDATE         
		AND   WD_INPLAN.DOCNO              = DM_DOCUMENT_D.DOCNO         
		AND   WD_INPLAN.DOCLINE            = DM_DOCUMENT_D.DOCLINE         
		AND   WD_INPLAN.DEL_YN             = 'N'
    	<if test="fromSlipdt != null and fromSlipdt != ''"> AND WD_INPLAN.SLIPDT  <![CDATA[>=]]>   #{fromSlipdt}    </if>       
        <if test="toSlipdt != null and toSlipdt != ''">     AND WD_INPLAN.SLIPDT  <![CDATA[<=]]>   #{toSlipdt}      </if>     
        JOIN  MS_SKU                
        ON    MS_SKU.STORERKEY              = DM_DOCUMENT_D.STORERKEY                
        AND   MS_SKU.SKU                    = DM_DOCUMENT_D.SKU                   
        AND   MS_SKU.DEL_YN                 = 'N'
        <!-- 상품 다중선택 -->
    	<if test="sku != null and sku != '' ">
            <if test="skuMulti != null and skuMulti.size() > 0">
                <trim prefix="AND (" suffix=")" prefixOverrides="OR">
                    <foreach collection="skuMulti" item="item">
                        OR MS_SKU.SKU IN
                        <foreach collection="item" item="code" open="(" close=")" separator=",">
                            #{code}      
                        </foreach>
                    </foreach>
                </trim>                                             
            </if>
        </if>
        
        <if test="storagetype != null and storagetype != ''"> AND    MS_SKU.STORAGETYPE = #{storagetype}             </if>          
        
        LEFT JOIN MS_UOM       
        ON   MS_UOM.STORERKEY        = DM_DOCUMENT_D.STORERKEY       
        AND  MS_UOM.SKU              = DM_DOCUMENT_D.SKU       
        AND  MS_UOM.BASEUOM          = DM_DOCUMENT_D.UOM       
        AND  MS_UOM.UOM              = 'KG'    
        
        JOIN DM_DOCUMENT_D TOSTO      
        ON   TOSTO.STORERKEY         = DM_DOCUMENT_D.STORERKEY     
        AND  TOSTO.DOCTYPE           = 'DP'     
        AND  TOSTO.DELIVERYDATE             = DM_DOCUMENT_D.DELIVERYDATE     
        AND  TOSTO.DOCNO             = DM_DOCUMENT_D.DOCNO     
        AND  TOSTO.DOCLINE           = DM_DOCUMENT_D.DOCLINE     
        AND  TOSTO.WORKPROCESSCODE   = 'STO'     
        AND  TOSTO.DEL_YN            = 'N'          
        
        LEFT JOIN TM_INPLAN
		ON    TM_INPLAN.DCCODE             = WD_INPLAN.DCCODE         
		AND   TM_INPLAN.STORERKEY          = WD_INPLAN.STORERKEY               
		AND   TM_INPLAN.DOCDT              = WD_INPLAN.DOCDT         
		AND   TM_INPLAN.DOCNO              = WD_INPLAN.DOCNO    
		AND   TM_INPLAN.SLIPDT             = WD_INPLAN.SLIPDT
        AND   TM_INPLAN.SLIPNO             = WD_INPLAN.SLIPNO     
		AND   TM_INPLAN.DOCTYPE            = 'WD'
		AND   TM_INPLAN.DEL_YN             = 'N'
        WHERE 1=1
        <if test="fromSlipdt != null and fromSlipdt != ''">       AND    FROM_DM_DOCUMENT_H.DELIVERYDATE	            &gt;=  #{fromSlipdt}      </if>
	    <if test="toSlipdt != null and toSlipdt != ''">          AND    FROM_DM_DOCUMENT_H.DELIVERYDATE	            &lt;=  #{toSlipdt}        </if>
        AND   FROM_DM_DOCUMENT_H.DOCTYPE = 'WD'
        AND   FROM_DM_DOCUMENT_H.DEL_YN  = 'N'
        AND   FROM_DM_DOCUMENT_H.WORKPROCESSCODE = 'STO'
        <!-- 배송그룹 공통조회 조건 -->
		<if test="gMultiCourier != null and gMultiCourier != ''"> AND    FROM_DM_DOCUMENT_H.COURIER                  =      #{gMultiCourier}   </if>          
		<!-- 문서번호 다중선택 -->		    
        <if test="docnoMulti != null and docnoMulti != ''">
           AND FROM_DM_DOCUMENT_H.DOCNO IN
           <foreach collection="docnoMulti" item="code" open="(" close=")" separator=",">
             #{code}
           </foreach>   
        </if>   
        <if test="fromDccode != null and fromDccode != ''">
            AND FROM_DM_DOCUMENT_H.DCCODE IN
                              (SELECT TRIM(REGEXP_SUBSTR(VAL,'[^,]+',1,LEVEL)) AS VAL
                                            FROM (SELECT #{fromDccode} AS VAL FROM DUAL) A
                                         CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0)
        </if>
        <!-- From창고.다중검색 -->
        <if test="organizeMulti != null and organizeMulti != ''">    
           AND FROM_DM_DOCUMENT_H.ORGANIZE IN
           <foreach collection="organizeMulti" item="code" open="(" close=")" separator=",">
             #{code}
           </foreach>
        </if>      
        <if test="status != null and status != ''">                     AND    FROM_DM_DOCUMENT_H.STATUS      =    #{status}            </if>          
        <if test="serialno != null and serialno != ''">
        AND EXISTS (SELECT 1
                    FROM    DM_DOCUMENT_D JOIN WD_INPLAN    ON    WD_INPLAN.DCCODE             = DM_DOCUMENT_D.DCCODE         
                                                            AND   WD_INPLAN.STORERKEY          = DM_DOCUMENT_D.STORERKEY 
                                                            AND   WD_INPLAN.ORGANIZE           = DM_DOCUMENT_D.ORGANIZE                      
                                                            AND   WD_INPLAN.AREA               = DM_DOCUMENT_D.AREA              
                                                            AND   WD_INPLAN.DOCDT              = DM_DOCUMENT_D.DOCDT         
                                                            AND   WD_INPLAN.DOCNO              = DM_DOCUMENT_D.DOCNO         
                                                            AND   WD_INPLAN.DOCLINE            = DM_DOCUMENT_D.DOCLINE  
                                          JOIN ST_SNINFOSLIP ST_SERIALINFO  ON     ST_SERIALINFO.DCCODE         = WD_INPLAN.DCCODE            
                                                                            AND    ST_SERIALINFO.STORERKEY      = WD_INPLAN.STORERKEY 
                                                                            AND    ST_SERIALINFO.ORGANIZE       = WD_INPLAN.ORGANIZE            
                                                                            AND    ST_SERIALINFO.SKU            = WD_INPLAN.SKU
                                                                            AND    ST_SERIALINFO.DOCTYPE        = WD_INPLAN.DOCTYPE
                                                                            AND    ST_SERIALINFO.SLIPDT         = WD_INPLAN.SLIPDT
                                                                            AND    ST_SERIALINFO.SLIPNO         = WD_INPLAN.SLIPNO
                                                                            AND    ST_SERIALINFO.SLIPLINE       = WD_INPLAN.SLIPLINE
                                                                            AND    ST_SERIALINFO.DOCTYPE        = 'WD'
                                                                            AND    ST_SERIALINFO.DEL_YN         = 'N'
                                                                            <if test="serialno != null and serialno != ''">
                                                                                AND    ST_SERIALINFO.SERIALNO         =      #{serialno}
                                                                            </if>
                                                                            <if test="blno != null and blno != ''">
                                                                                AND    ST_SERIALINFO.CONVSERIALNO     =      #{blno}
                                                                            </if>
                                                                            <if test="contractcompany != null and contractcompany != ''">
                                                                                AND    ST_SERIALINFO.CONTRACTCUSTKEY   =      #{contractcompany}
                                                                            </if>
                    WHERE  DM_DOCUMENT_D.DCCODE = FROM_DM_DOCUMENT_H.DCCODE
                    AND    DM_DOCUMENT_D.DOCTYPE = FROM_DM_DOCUMENT_H.DOCTYPE
                    AND    DM_DOCUMENT_D.DOCNO   = FROM_DM_DOCUMENT_H.DOCNO )    
        </if>
        ORDER BY FROM_DM_DOCUMENT_H.DCCODE
                ,FROM_DM_DOCUMENT_H.STORERKEY
                ,WD_INPLAN.SLIPDT
                ,FROM_DM_DOCUMENT_H.DOCDT
                ,FROM_DM_DOCUMENT_H.DOCNO
                ,FROM_DM_DOCUMENT_H.DOCTYPE
                ,FROM_DM_DOCUMENT_H.ORDERTYPE
                ,TM_INPLAN.CARNO
    </select>
    
    <select id="getPrintMasterInvoice"  resultType="cjfw.wms.wd.dto.WdInplanSTOEntity">
		SELECT /* [wdInplanSTOService.sqlx][wdInplanSTOService.getDataPrintInvoicelist][광역출고현황 이체확인서출력][YeoSeungCheol][2025.11.12] */
		        FROMSTO.DCCODE AS DCCODE,
	            FROMSTO.DELIVERYDATE AS DELIVERYDT,
	            FROMSTO.DCCODE AS FROM_CUSTKEY,
	            (SELECT D.DESCRIPTION FROM MS_CUST D WHERE D.CUSTKEY = FROMSTO.DCCODE AND D.CUSTTYPE = 'D' AND D.STORERKEY = FROMSTO.STORERKEY) AS FROM_CUSTNAME,
	            (SELECT D.ADDRESS1 || D.ADDRESS2 FROM MS_CUST D WHERE D.CUSTKEY = FROMSTO.DCCODE AND D.CUSTTYPE = 'D' AND D.STORERKEY = FROMSTO.STORERKEY) AS FROM_CUSTADDRESS,
	 			FROMSTO.DOCDT AS DOCDT,
	 			FROMSTO.DOCNO AS DOCNO,
	 		    FROMSTO.DOCTYPE AS DOCTYPE,
	 			FROMSTO.TO_CUSTKEY AS TO_CUSTKEY,
	 			(SELECT D.DESCRIPTION FROM MS_CUST D WHERE D.CUSTKEY = FROMSTO.TO_CUSTKEY AND D.CUSTTYPE = 'D' AND D.STORERKEY = FROMSTO.STORERKEY) AS TO_CUSTNAME,
	 			(SELECT  D.ADDRESS1 || D.ADDRESS2 FROM MS_CUST D WHERE D.CUSTKEY = FROMSTO.TO_CUSTKEY AND D.CUSTTYPE = 'D' AND D.STORERKEY = FROMSTO.STORERKEY) AS TO_CUSTADDRESS
	  FROM DM_DOCUMENT_H FROMSTO
	 WHERE FROMSTO.STORERKEY =  #{gStorerkey}
		   AND FROMSTO.DOCTYPE         = 'WD'
		   AND FROMSTO.DEL_YN          = 'N'
		   AND FROMSTO.WORKPROCESSCODE = 'STO'
	       AND FROMSTO.DCCODE          = #{dccode}
		<!-- START.DOCNO 
		<if test="docnoMulti != null and docnoMulti != '' ">
			<trim prefix="AND (" suffix=")" prefixOverrides="OR">
				<foreach collection="docnoMulti" item="item">
	                                OR FROMSTO.DOCNO IN
					<foreach collection="item" item="code" open="(" close=")" separator=",">
						#{code} 	 
					</foreach>
				</foreach>
			</trim>
		</if> -->
		<if test="docnoMulti != null and docnoMulti != ''">
           AND FROMSTO.DOCNO IN
           <foreach collection="docnoMulti" item="code" open="(" close=")" separator=",">
             #{code}
           </foreach>   
        </if>
		<!-- END.DOCNO -->
	</select>
	
	
	<select id="getPrintDetailInvoice" parameterType="cjfw.wms.wd.dto.WdInplanSTOEntity" resultType="cjfw.wms.wd.dto.WdInplanSTOEntity">
		SELECT /* [wdInplanSTOService.sqlx][wdInplanSTOService.getDataPrintInvoiceDetail][광역출고현황 이체확인서출력][YeoSeungCheol][2025.11.12] */
	               DM_DOCUMENT_D.DOCNO AS DOCNO
	              ,DM_DOCUMENT_D.DOCLINE AS DOCLINE        
	              ,MAX(FN_CODEDESCR(MS_SKU.STORERKEY,'STORAGETYPE',MS_SKU.STORAGETYPE))       AS STORAGETYPE   
	              ,MS_SKU.SKU                                                            AS SKU            
	              ,MAX(MS_SKU.DESCRIPTION) AS SKUNAME
	              ,FN_CODEDESCR(MAX(DM_DOCUMENT_D.STORERKEY), 'PUTAWAYTYPE', MAX(DM_DOCUMENT_D.CHANNEL)) AS CHANNEL
	              ,WD_TASK.UOM                                                         AS UOM           
	              ,CASE WHEN WD_TASK.UOM = 'BOX' THEN SUM(WD_TASK.PROCESSQTY)
	                    WHEN WD_TASK.UOM = 'KG'  THEN NULL
	                    ELSE CASE WHEN FN_CONV_UOM(WD_TASK.STORERKEY,MS_SKU.SKU,'BOX',WD_TASK.UOM,1) = 0 THEN NULL
	                              ELSE TRUNC(FN_CONV_UOM(WD_TASK.STORERKEY,MS_SKU.SKU,WD_TASK.UOM,'BOX',SUM(WD_TASK.PROCESSQTY)))
	                         END END AS BOXQTY                                                             
	              ,CASE WHEN WD_TASK.UOM = 'BOX' THEN 0
	                    WHEN WD_TASK.UOM = 'KG'  THEN NULL
	                    ELSE CASE WHEN FN_CONV_UOM(WD_TASK.STORERKEY,MS_SKU.SKU,'BOX',WD_TASK.UOM,1) = 0 THEN NULL
	                              ELSE MOD(SUM(WD_TASK.PROCESSQTY),FN_CONV_UOM(WD_TASK.STORERKEY,MS_SKU.SKU,'BOX',WD_TASK.UOM,1))
	                         END  END AS ORDERQTY
	             , MAX(MS_SKU.QTYPERBOX) AS QTYPERBOX
	             ,MAX(CM_LOT.LOTTABLE01) AS LOTTABLE01  
	        FROM
	            WD_TASK   
	        JOIN 
	            WD_INPLAN
	                ON     WD_INPLAN.DCCODE       = WD_TASK.DCCODE             
	                AND    WD_INPLAN.STORERKEY    = WD_TASK.STORERKEY          
	                AND    WD_INPLAN.SLIPDT       = WD_TASK.SLIPDT             
	                AND    WD_INPLAN.SLIPNO       = WD_TASK.SLIPNO             
	                AND    WD_INPLAN.SLIPLINE     = WD_TASK.SLIPLINE                                                                                      
	        JOIN
	            MS_SKU         
	                ON     MS_SKU.STORERKEY    = WD_TASK.STORERKEY         
	                AND    MS_SKU.SKU          = WD_TASK.SKU                                              
	        JOIN
	            DM_DOCUMENT_H         
	                ON     DM_DOCUMENT_H.DCCODE        = WD_TASK.DCCODE         
	                AND    DM_DOCUMENT_H.STORERKEY     = WD_TASK.STORERKEY         
	                AND    DM_DOCUMENT_H.ORGANIZE      = WD_TASK.ORGANIZE         
	                AND    DM_DOCUMENT_H.DOCTYPE       = 'WD'         
	                AND    DM_DOCUMENT_H.DOCDT         = WD_TASK.DOCDT         
	                AND    DM_DOCUMENT_H.DOCNO         = WD_TASK.DOCNO                                                                                       
	                AND    DM_DOCUMENT_H.DEL_YN        = 'N'         
	        JOIN
	                DM_DOCUMENT_D         
	            ON     DM_DOCUMENT_D.DCCODE     = WD_TASK.DCCODE
	            AND    DM_DOCUMENT_D.DOCTYPE    = 'WD'
	            AND    DM_DOCUMENT_D.STORERKEY  = WD_TASK.STORERKEY
	            AND    DM_DOCUMENT_D.DOCDT      = WD_TASK.DOCDT    
	            AND    DM_DOCUMENT_D.DOCNO      = WD_TASK.DOCNO    
	            AND    DM_DOCUMENT_D.DOCLINE    = WD_TASK.DOCLINE    
	            AND    DM_DOCUMENT_D.DEL_YN     = 'N'         
	        JOIN
	            MS_SKU         
	                ON     MS_SKU.STORERKEY            = WD_TASK.STORERKEY         
	                AND    MS_SKU.SKU                  = WD_TASK.SKU       
	    JOIN   CM_LOT
			ON     CM_LOT.STORERKEY         = WD_TASK.STORERKEY
			AND    CM_LOT.LOT               = WD_TASK.LOT       
	        WHERE
	            1=1   
		<!-- START.DOCNO -->
		
		<if test="docnoMulti != null and docnoMulti != ''">
           AND DM_DOCUMENT_D.DOCNO IN
           <foreach collection="docnoMulti" item="code" open="(" close=")" separator=",">
             #{code}
           </foreach>   
        </if>
           
		<!-- END.DOCNO -->
		<!-- START.DOCNO 
		<if test="docnoMulti != null and docnoMulti != '' ">
			<trim prefix="AND (" suffix=")" prefixOverrides="OR">
				<foreach collection="docnoMulti" item="item">
	                                OR DM_DOCUMENT_D.DOCNO IN
					<foreach collection="item" item="code" open="(" close=")" separator=",">
						#{code} 	 
					</foreach>
				</foreach>
			</trim>
		</if>
		END.DOCNO -->		
	            AND DM_DOCUMENT_D.DOCTYPE = 'WD'
	            AND DM_DOCUMENT_D.WORKPROCESSCODE ='STO'     
	            GROUP BY DM_DOCUMENT_D.DOCNO
	                            ,DM_DOCUMENT_D.DOCLINE
	                            ,MS_SKU.SKU
	                            ,WD_TASK.UOM
	                            ,WD_TASK.STORERKEY
	                            ,WD_TASK.LOT
	                            ,DM_DOCUMENT_D.STORERORDERQTY
	</select>
	    
</mapper>
