<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="wdShipmentExDCService">

    <select id="getMasterList" resultType="WdShipmentExDCResDto">
        SELECT   /* [wdShipmentExDCService.sqlx][getMasterList][외부창고 출고확정 목록 조회][sunho.kim][2025.06.30] */
               WD_INPLAN.DCCODE                                                                                                                 AS DCCODE                               /* 물류센터 */
              ,WD_INPLAN.STORERKEY                                                                                                              AS STORERKEY                            /* 고객사코드 */
              ,WD_INPLAN.ORGANIZE                                                                                                               AS ORGANIZE                             /* 창고코드 */
              ,FN_DESCR_ORGANIZE(WD_INPLAN.DCCODE,WD_INPLAN.ORGANIZE)                                                                           AS ORGANIZENAME                         /* 창고명 */
              ,WD_INPLAN.AREA                                                                                                                   AS AREA                                 /* 작업영역 */
              ,WD_INPLAN.DOCDT                                                                                                                  AS DOCDT                                /* 문서생셩일자 */
              ,WD_INPLAN.DOCNO                                                                                                                  AS DOCNO                                /* 문서번호 */
              ,WD_INPLAN.DOCLINE                                                                                                                AS DOCLINE                              /* 문서라인 */
              ,WD_INPLAN.DOCTYPE                                                                                                                AS DOCTYPE                              /* 문서유형 */
              ,WD_INPLAN.SLIPDT                                                                                                                 AS SLIPDT                               /* 전표일자 */
              ,WD_INPLAN.SLIPNO                                                                                                                 AS SLIPNO                               /* 전표번호 */    
              ,WD_INPLAN.SLIPLINE                                                                                                               AS SLIPLINE                             /* 전표라인 */
              ,WD_INPLAN.ORDERTYPE                                                                                                              AS ORDERTYPE                            /* 구매유형코드 */
              ,CD1.BASEDESCR                                                                                                                    AS ORDERTYPE_NAME                       /* 구매유형명 */
              ,WD_INPLAN.SKU                                                                                                                    AS SKU                                  /* 상품코드 */
              ,MS_SKU.DESCRIPTION                                                                                                               AS SKUNAME                              /* 상품명 */
              ,DM_DOCUMENT_H.TO_CUSTKEY                                                                                                         AS TO_CUSTKEY                           /* 관리처코드 */
              ,DM_DOCUMENT_H.TO_CUSTNAME                                                                                                        AS TO_CUSTNAME                          /* 관리처명 */
              ,DM_DOCUMENT_D.SERIALKEY                                                                                                          AS SERIALKEY                            /* 데이터번호 */
              ,DM_DOCUMENT_D.STORERUOM                                                                                                          AS STORERUOM                            /* 저장단위 */
              ,DM_DOCUMENT_D.UOM                                                                                                                AS UOM                                  /* 단위 */
              ,DM_DOCUMENT_D.BUNJA                                                                                                              AS BUNJA                                /* 분자 */
              ,DM_DOCUMENT_D.BUNMO                                                                                                              AS BUNMO                                /* 분모 */
              ,CASE WHEN WD_INPLAN.UOM = 'KG' THEN FN_UOMCAL ( DM_DOCUMENT_D.BUNMO
                                                              ,DM_DOCUMENT_D.BUNJA
                                                              ,DM_DOCUMENT_D.ORDERQTY  )     
                    ELSE FN_UOMCAL ( DM_DOCUMENT_D.BUNMO
                                    ,DM_DOCUMENT_D.BUNJA
                                    ,WD_INPLAN.ORDERQTY + WD_INPLAN.CANCELQTY    )    
               END                                                                                                                              AS ORDERQTY                          /* 주문수량 */
              ,FN_UOMCAL  ( DM_DOCUMENT_D.BUNMO
                           ,DM_DOCUMENT_D.BUNJA
                           ,WD_INPLAN.ORDERQTY + WD_INPLAN.CANCELQTY    )                                                                       AS ORGORDERQTY                       /* 영업주문수량 */             
              ,FN_UOMCAL  ( DM_DOCUMENT_D.BUNMO
                           ,DM_DOCUMENT_D.BUNJA
                           ,WD_INPLAN.INSPECTQTY)                                                                                               AS INSPECTQTY                           /* 검수수량 */
              ,FN_UOMCAL  ( DM_DOCUMENT_D.BUNMO
                           ,DM_DOCUMENT_D.BUNJA
                           ,WD_INPLAN.CONFIRMQTY)                                                                                               AS CONFIRMQTY                           /* 출고수량 */
              ,ABS(FN_UOMCAL  ( DM_DOCUMENT_D.BUNMO
                           ,DM_DOCUMENT_D.BUNJA
                           ,WD_INPLAN.CANCELQTY    ))                                                                                           AS SHORTAGEQTY                          /* 결품수량 */
              ,0                                                                                                                                AS SHORTAGETRANQTY                      /* 결품작업량 */
              ,0                                                                                                                                AS TRANQTY                              /* 출고작업량 */
              ,CORE_CM_STRATEGY.FN_GETTOLOC ( WD_INPLAN.DOCTYPE    
                                             ,WD_INPLAN.DCCODE     
                                             ,WD_INPLAN.STORERKEY  
                                             ,WD_INPLAN.ORDERTYPE  
                                             ,WD_INPLAN.SLIPTYPE   )                                                                            AS TOLOC                                /* TO 로케이션 */
              ,NVL(ST_SNINFO.LOTTABLE01,'STD')                                                                                                  AS LOTTABLE01                           /* 기준일 */
              ,FN_LOTDURATION(WD_INPLAN.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, NVL(ST_SNINFO.LOTTABLE01,'STD'), 'N')||'/'||MS_SKU.DURATION      AS DURATION_TERM              /* 소비기간 */
              ,MS_SKU.COLORDESCR                                                                                                                AS COLORDESCR                           /* 색상 */   
              ,DM_DOCUMENT_D.REFERENCE02                                                                                                        AS REFERENCE02                          /* REFERENCE02 */
              ,NVL(DM_DOCUMENT_D.REFERENCE08,0)                                                                                                 AS REFERENCE08                          /* 주문수량에 대한 총 보관료 */
              ,NVL(DM_DOCUMENT_D.REFERENCE09,0)                                                                                                 AS REFERENCE09                          /* 계산된 보관료 */
              ,NVL(DM_DOCUMENT_D.REFERENCE10,0)                                                                                                 AS REFERENCE10                          /* 운송료 */
              --,CASE WHEN MS_SKU.OTHER05 = 'X3' THEN ROUND(TO_NUMBER(NVL(DM_DOCUMENT_D.REFERENCE10,0))*10/11)
              --      ELSE TO_NUMBER(NVL(DM_DOCUMENT_D.REFERENCE10,0))
              -- END                                                                                                                              AS TRANDELIVERYPRICE                    /* 운송료(공급가) */
              ,TO_NUMBER(NVL(DM_DOCUMENT_D.REFERENCE10,0))                                                                                      AS TRANDELIVERYPRICE                    /* 운송료(공급가) */
              ,CASE WHEN MS_SKU.OTHER05 = 'X3' THEN ROUND(TO_NUMBER(NVL(DM_DOCUMENT_D.REFERENCE10,0))*10/11)
                    ELSE TO_NUMBER(NVL(DM_DOCUMENT_D.REFERENCE10,0))
               END                                                                                                                              AS TRANDELIVERYPRICEPRE                 /* 운송료(공급가) */
              --,DM_DOCUMENT_D.REASONCODE                                                                                                         AS REASONCODE                           /* 사유코드 */
              --,DM_DOCUMENT_D.REASONMSG                                                                                                          AS REASONMSG                            /* 처리결과 */
              ,WD_INPLAN.REASONCODE                                                                                                             AS REASONCODE                           /* 사유코드 */
              ,CASE WHEN NVL(WD_INPLAN.REASONMSG, '') = 'null' THEN ''
                    ELSE WD_INPLAN.REASONMSG
                END                                                                                                                             AS REASONMSG                            /* 처리결과 */
              ,CASE WHEN NVL(ST_SNINFO.LOTTABLE01,'STD')='STD' THEN 'N' 
                    WHEN MONTHS_BETWEEN(TO_DATE(NVL(ST_SNINFO.LOTTABLE01,'STD'),'yyyy-mm-dd'),SYSDATE) <![CDATA[>]]> 3 
                    THEN 'N' 
                    ELSE 'Y' 
                END                                                                                                                             AS NEARDURATIONYN                       /* 소비기한여부 */
              ,DM_DOCUMENT_D.STATUS                                                                                                             AS STATUS                               /* 상태코드 */    
              ,CD2.BASEDESCR                                                                                                                    AS STATUSNAME                           /* 상태명 */
              ,MS_SKU.QTYPERBOX                                                                                                                 AS QTYPERBOX                            /* 박스수량 */    
              ,DM_DOCUMENT_D.CHANNEL                                                                                                            AS CHANNEL                              /* 채녈 */  
              ,MS_SKU.DURATION                                                                                                                  AS DURATION                             /* 기간코드 */
              ,MS_SKU.DURATIONTYPE                                                                                                              AS DURATIONTYPE                         /* 기간유형코드 */    
              ,''                                                                                                                               AS LASTLOTTABLE01                       /* LASTLOTTABLE01 */
              ,NVL(ST_SNINFO.STOCKID,WD_INPLAN.STOCKID)                                                                                         AS STOCKID                              /* 재고 구분 ID */    
              ,WD_INPLAN.STOCKGRADE                                                                                                             AS STOCKGRADE                           /* 재고 구분 등급 */
              ,DM_DOCUMENT_D.PLANT                                                                                                              AS PLANT                                /* 플랜트코드 */
              ,'['||DM_DOCUMENT_D.PLANT||']'||FN_DESCR_PLANT(DM_DOCUMENT_D.PLANT)                                                               AS PLANT_DESCR                          /* 플랜트명 */
              ,CD3.BASEDESCR                                                                                                                    AS CHANNEL_NAME                         /* 채널명 */
              ,MS_SKU.STORAGETYPE                                                                                                               AS STORAGETYPE                          /* 저장조건 */ 
              ,CD4.BASEDESCR                                                                                                                    AS STORAGETYPENAME                      /* 저장조건명 */
              ,ST_SNINFO.SERIALNO                                                                                                               AS SERIALNO                             /* 이력번호 */    
              ,ST_SNINFO.CONVSERIALNO                                                                                                           AS CONVSERIALNO                         /* B/L번호 */   
              ,ST_SNINFO.FACTORYNAME                                                                                                            AS FACTORYNAME                          /* 도축장명 */
              ,ST_SNINFO.CONTRACTCUSTKEY                                                                                                        AS CONTRACTCOMPANY                      /* 계약업체코드 */      
              ,( SELECT DESCRIPTION  FROM MS_CUST
                  WHERE CUSTKEY = ST_SNINFO.CONTRACTCUSTKEY
                    AND ROWNUM = 1)                                                                                                             AS CONTRACTCOMPANYNAME                  /* 계약업체명 */    
              ,CD5.BASEDESCR                                                                                                                    AS CONTRACTTYPE                         /* 계약유형 */    
              ,ST_SNINFO.BUTCHERYDT                                                                                                             AS BUTCHERYDT                           /* 도축일자 */
              ,ST_SNINFO.FROMVALIDDT                                                                                                            AS FROMVALIDDT                          /* 유효시작일 */    
              ,ST_SNINFO.TOVALIDDT                                                                                                              AS TOVALIDDT                            /* 유효종료일 */
              ,ST_SNINFO.STOCKID                                                                                                                AS BARCODE                              /* 바코드 */
              ,CASE WHEN ST_SNINFO.STOCKID IS NULL THEN NULL
                    ELSE CASE WHEN WD_INPLAN.UOM = 'KG' THEN FN_UOMCAL ( DM_DOCUMENT_D.BUNMO
                                                                        ,DM_DOCUMENT_D.BUNJA
                                                                        ,DM_DOCUMENT_D.ORDERQTY  )     
                              ELSE FN_UOMCAL ( DM_DOCUMENT_D.BUNMO
                                              ,DM_DOCUMENT_D.BUNJA
                                              ,WD_INVOICE_SN.ORDERQTY - WD_INVOICE_SN.CONFIRMQTY) 
                         END
               END                                                                                                                              AS SERIALORDERQTY                       /* 스캔예정량 */   
              --,CASE WHEN ST_SNINFO.STOCKID IS NULL THEN NULL
              --      ELSE FN_UOMCAL ( DM_DOCUMENT_D.BUNMO
              --                     ,DM_DOCUMENT_D.BUNJA
              --                     ,WD_INVOICE_SN.ORDERQTY - WD_INVOICE_SN.CONFIRMQTY)
              -- END                                                                                                                              AS SERIALORDERQTY                       /* 스캔예정량 */
              ,CASE WHEN ST_SNINFO.STOCKID IS NULL THEN NULL    
                    ELSE 0
               END                                                                                                                              AS SERIALINSPECTQTY                     /* 스캔량 */
              ,CASE WHEN ST_SNINFO.STOCKID IS NULL THEN NULL
                     ELSE 0
                END                                                                                                                             AS SERIALSCANWEIGHT                     /* 스캔중량 */
              ,CASE WHEN  WD_INPLAN.STORERKEY = 'CJFW' 
                     OR (    ST_SNINFO.SERIALNO IS NOT NULL
                         AND (   DM_DOCUMENT_D.CHANNEL <![CDATA[<>]]> '1' 
                              OR WD_INPLAN.DCCODE IN ('2170'))
                         ) THEN 'Y'                                         
                   WHEN  WD_INPLAN.DCCODE IN (SELECT BASECODE
                                              FROM   CM_CODE_STORER WMS_MNG_DC
                                              WHERE  WMS_MNG_DC.STORERKEY = #{gStorerkey}
                                              AND    WMS_MNG_DC.CODELIST  = 'WMS_MNG_DC'
                                              AND    WMS_MNG_DC.DATA3     = 'Y'
                                              AND    WMS_MNG_DC.BASECODE  != '2170') THEN 'Y'
                   ELSE 'N' 
               END                                                                                                                              AS CHECKFLAG                            /* 체크플래그 */
              ,MS_SKU.LINE01                                                                                                                    AS LINE01                               /* LINE01 */
              ,CASE WHEN WD_INPLAN.DCCODE IN (SELECT BASECODE
                                              FROM   CM_CODE_STORER WMS_MNG_DC
                                              WHERE  WMS_MNG_DC.STORERKEY = #{gStorerkey}
                                              AND    WMS_MNG_DC.CODELIST  = 'WMS_MNG_DC'
                                              AND    WMS_MNG_DC.DATA3     = 'Y'
                                              AND    WMS_MNG_DC.BASECODE  != '2170') THEN 'black' 
                   WHEN WD_INPLAN.STORERKEY = 'FW00' AND ST_SNINFO.SERIALNO IS NULL  THEN 'gray' 
                   ELSE 'black' 
               END                                                                                                                              AS FONTCOLOR                             /* 폰트컬러 */
              ,ROUND(CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 
                     AND WD_INPLAN.DCCODE       = '2170' 
                     AND NVL(MS_SKU.LINE01,'N') = 'Y'          THEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) 
                    ELSE 0 
                END, 3)                                                                                                                         AS AVGWEIGHT                            /* 평균중량 */
              ,ROUND(CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 
                               AND WD_INPLAN.DCCODE       = '2170' 
                               AND NVL(MS_SKU.LINE01,'N') = 'Y'    
                          THEN (WD_INVOICE_SN.ORDERQTY + WD_INVOICE_SN.CANCELQTY) / TO_NUMBER(NVL(MS_SKU.LINE02,0)) 
                          ELSE 0 
                    END ,3)                                                                                                                     AS CALBOX                               /* 환산박스 */        
              ,CASE WHEN WD_INPLAN.DCCODE       = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'          
                    THEN NVL(WD_INVOICE_SN.ETCQTY1,0)                                                                                                  
                    ELSE 0
               END                                                                                                                              AS REALORDERBOX                         /* 실박스예정 */
              ,CASE WHEN WD_INPLAN.DCCODE       = '2170'  AND NVL(MS_SKU.LINE01,'N') = 'Y'          
                    THEN NVL(WD_INVOICE_SN.ETCQTY2,0)
                    ELSE 0
               END                                                                                                                              AS REALCFMBOX                           /* 실박스확정 */              
              ,CASE WHEN WD_INPLAN.DCCODE       = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y' AND NVL(WD_INVOICE_SN.ETCQTY2,0) = 0      
                    THEN NVL(WD_INVOICE_SN.ETCQTY1,0)
                     ELSE 0
               END                                                                                                                              AS TRANBOX                              /* 작업박스 */
              ,CASE WHEN WD_INPLAN.DCCODE       = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'          
                    THEN 'Y'
                    ELSE 'N'
               END                                                                                                                              AS BOXFLAG                              /* 박스처리유무 */
              ,CASE WHEN DM_DOCUMENT_D.DCCODE   = '2170' AND DM_DOCUMENT_D.ORDERTYPE = 'ZUB' AND DM_DOCUMENT_D.SOTYPE = 'STO'
                    THEN 'Y'
                    ELSE 'N'
               END                                                                                                                              AS STOFLAG                              /* STO플래그 */
              ,CASE WHEN MS_SKU.OTHER05 = 'X3' 
                    THEN 1.1
                    ELSE 1
               END                                                                                                                              AS OTHER05                              /* 과세,면세 구분(비율)*/
              ,CD6.BASEDESCR                                                                                                                    AS TAX_CLS                              /* 과세,면세 구분*/
              ,MS_SKU.SERIALYN                                                                                                                  AS SERIALYN
              ,NVL(DM_DOCUMENT_D.REAL_YN, '')                                                                                                   AS REAL_YN                              /* 가/진오더 여부 */
              ,DM_DOCUMENT_D.TEMP_YN                                                                                                            AS TEMP_YN                              /* 임시 여부 */
              ,ST_SNINFO.POKEY                                                                                                                  AS POKEY                                /* PO번호 */
              ,ST_SNINFO.POLINE                                                                                                                 AS POLINE                               /* PO라인 */
              ,CASE WHEN DM_DOCUMENT_D.CANCELQTY > 0 
                         AND DM_DOCUMENT_D.CONFIRMQTY = 0 
                         AND DM_DOCUMENT_D.STATUS = '90'  
                       THEN 'Y'
                    ELSE 'N'
                END                                                                                                                             AS ALL_CANCEL_STATUS                    /* 전체취소여부 */  
              ,CASE WHEN DM_DOCUMENT_H.ORDERTYPE = 'ZTP' 
                    THEN
                        CASE WHEN(SELECT COUNT(1)
                                  FROM MS_EXDCRATE B
                                  WHERE 1=1
                                    AND B.ORGANIZE  = DM_DOCUMENT_H.ORGANIZE
                                    AND B.SKU       = DM_DOCUMENT_D.SKU
                                    AND B.CUSTKEY   = DM_DOCUMENT_H.FROM_CUSTKEY
                                    AND B.STORERKEY = DM_DOCUMENT_H.STORERKEY
                                    AND B.FROMDATE <![CDATA[<=]]> DM_DOCUMENT_H.DELIVERYDATE
                                    AND B.TODATE   <![CDATA[>=]]> DM_DOCUMENT_H.DELIVERYDATE
                                 ) <![CDATA[>]]> 0 
                                 THEN 'Y' 
                             ELSE 'N' 
                        END 
                    ELSE 
                        CASE WHEN(SELECT COUNT(1)
                                  FROM MS_EXDCRATE B
                                  WHERE 1=1
                                    AND B.ORGANIZE   = DM_DOCUMENT_H.ORGANIZE
                                    AND B.SKU        = DM_DOCUMENT_D.SKU
                                    AND B.CUSTKEY    IS NULL
                                    AND B.STORERKEY  = DM_DOCUMENT_H.STORERKEY
                                    AND B.FROMDATE <![CDATA[<=]]> DM_DOCUMENT_H.DELIVERYDATE
                                    AND B.TODATE   <![CDATA[>=]]> DM_DOCUMENT_H.DELIVERYDATE
                                ) <![CDATA[>]]> 0 
                                THEN 'Y' 
                             ELSE 'N' 
                        END  
                END                                                                                                                             AS EXDCRATE_YN                          /* 창고요율등록여부 */
              ,CD7.BASEDESCR                                                                                                                    AS DELIVERYTYPENAME                     /* 출고방법 */
              ,FN_CONV_UOM(WD_INPLAN.STORERKEY, WD_INPLAN.SKU, WD_INPLAN.UOM, 'KG'
                         , FN_UOMCAL(DM_DOCUMENT_D.BUNMO
                                   , DM_DOCUMENT_D.BUNJA
                                   , CASE WHEN WD_INPLAN.CONFIRMQTY > 0 THEN WD_INPLAN.CONFIRMQTY
                                          ELSE (WD_INPLAN.ORDERQTY + WD_INPLAN.CANCELQTY)
                                      END
                                    ) 
                          )                                                                                                                     AS WEIGHT                               /* 중량 */ 
              ,CASE WHEN NVL(DM_DOCUMENT_D.REFERENCE03, '') = '' THEN NULL
                    ELSE DM_DOCUMENT_D.REFERENCE03
                 END                                                                                                                            AS SERIALKEY_GROUP                      /* 그룹 데이터번호 */
              ,DM_DOCUMENT_D.ADDWHO                                                                                                             AS ADDWHO                               /* 등록자 */
              ,USER1.USER_NM                                                                                                                    AS ADDWHO_NM                            /* 등록자명 */
              ,DM_DOCUMENT_D.ADDDATE                                                                                                            AS ADDDATE                              /* 등록일시 */ 
              ,CASE WHEN DM_DOCUMENT_D.STATUS IN ('85','90')
                    THEN DM_DOCUMENT_D.EDITWHO
                    ELSE NULL 
               END                                                                                                                              AS EDITWHO                              /* 수정자 */
              ,CASE WHEN DM_DOCUMENT_D.STATUS IN ('85','90')
                    THEN USER2.USER_NM
                    ELSE NULL 
               END                                                                                                                              AS EDITWHO_NM                           /* 수정자명 */
              ,CASE WHEN DM_DOCUMENT_D.STATUS IN ('85','90')
                    THEN DM_DOCUMENT_D.EDITDATE
                    ELSE NULL 
               END                                                                                                                              AS EDITDATE                             /* 수정일시 */
              ,NVL(DP_INPLAN.STATUS, '10')                                                                                                      AS DP_INPLAN_STATUS                     /* 입고예정상태 */   
       
        FROM  WD_INPLAN                
        
        JOIN  CM_USER_AUTHORITY          
             ON  CM_USER_AUTHORITY.USERID     = #{gUserId}     
            AND  CM_USER_AUTHORITY.DCCODE     = WD_INPLAN.DCCODE             
            AND  CM_USER_AUTHORITY.STORERKEY  = WD_INPLAN.STORERKEY          
            AND  CM_USER_AUTHORITY.ORGANIZE   = WD_INPLAN.ORGANIZE           
            AND  CM_USER_AUTHORITY.AREA       = WD_INPLAN.AREA           
        <if test="fixdccode != null and fixdccode != ''"> 
            AND  CM_USER_AUTHORITY.DCCODE     = #{fixdccode}      
        </if>
        <if test="gStorerkey != null and gStorerkey != ''">
            AND  CM_USER_AUTHORITY.STORERKEY  = #{gStorerkey}   
        </if>
        <if test="organizeMulti != null and organizeMulti != ''">
            AND  CM_USER_AUTHORITY.ORGANIZE      IN
            <foreach collection="organizeMulti" item="item" open="(" separator="," close=")">
                 #{item}
            </foreach> 
        </if>
        <if test="area != null and area != ''">
            AND  CM_USER_AUTHORITY.AREA       = #{area}        
        </if>       
        JOIN DM_DOCUMENT_H          
             ON  DM_DOCUMENT_H.DCCODE         = WD_INPLAN.DCCODE                  
            AND  DM_DOCUMENT_H.DELIVERYDATE   = WD_INPLAN.SLIPDT         
            AND  DM_DOCUMENT_H.DOCTYPE        = WD_INPLAN.DOCTYPE               
            AND  DM_DOCUMENT_H.DOCNO          = WD_INPLAN.DOCNO        
            AND  DM_DOCUMENT_H.DOCTYPE        = 'WD'         
            AND  DM_DOCUMENT_H.DEL_YN         = 'N'  
          <if test="fromCustkeyMulti != null and fromCustkeyMulti != ''">
            AND  DM_DOCUMENT_H.TO_CUSTKEY      IN
            <foreach collection="fromCustkeyMulti" item="item" open="(" separator="," close=")">
                 #{item}
            </foreach> 
          </if>           
        JOIN DM_DOCUMENT_D
             ON  DM_DOCUMENT_D.DCCODE         = WD_INPLAN.DCCODE      
            AND  DM_DOCUMENT_D.DOCTYPE        = WD_INPLAN.DOCTYPE     
            AND  DM_DOCUMENT_D.DELIVERYDATE   = WD_INPLAN.SLIPDT       
            AND  DM_DOCUMENT_D.DOCNO          = WD_INPLAN.DOCNO       
            AND  DM_DOCUMENT_D.DOCLINE        = WD_INPLAN.DOCLINE 
            AND  DM_DOCUMENT_D.CHANNEL        IN ('1','2','3')   <!-- 저장품만 처리함 1.저장 2.일배 3.광역일배 2015.01.26 SLLEE MODIFY [ 1,2] 김해경님 요청 -->
        <if test="channel != null and channel != ''">
            AND  DM_DOCUMENT_D.CHANNEL        = #{channel}             
        </if>
            AND  DM_DOCUMENT_D.DEL_YN         = 'N'    
        <if test="allshortageYn == 'N'">
            AND  DM_DOCUMENT_D.OPENQTY <![CDATA[>]]> DM_DOCUMENT_D.CANCELQTY              
        </if>
        <if test="allshortageYn == 'Y'">
            AND  DM_DOCUMENT_D.OPENQTY <![CDATA[=]]> DM_DOCUMENT_D.CANCELQTY             
        </if>
        JOIN MS_SKU 
             ON  MS_SKU.STORERKEY             = WD_INPLAN.STORERKEY         
            AND  MS_SKU.SKU                   = WD_INPLAN.SKU
            AND  MS_SKU.DEL_YN                = 'N'
        <if test="storagetype != null and storagetype != ''">  
            AND  MS_SKU.STORAGETYPE           = #{storagetype}                  
        </if>
        LEFT OUTER JOIN  WD_INVOICE_SN
             ON  WD_INVOICE_SN.DCCODE        = WD_INPLAN.DCCODE                   
            AND  WD_INVOICE_SN.STORERKEY     = WD_INPLAN.STORERKEY        
            AND  WD_INVOICE_SN.DOCTYPE       = WD_INPLAN.DOCTYPE
            AND  WD_INVOICE_SN.WD_SLIPNO     = WD_INPLAN.SLIPNO 
            AND  WD_INVOICE_SN.WD_SLIPDT     = WD_INPLAN.SLIPDT
            AND  WD_INVOICE_SN.WD_SLIPLINE   = WD_INPLAN.SLIPLINE                   
            AND  WD_INVOICE_SN.SKU           = WD_INPLAN.SKU 
        LEFT OUTER JOIN  DP_INPLAN
             ON  DP_INPLAN.STORERKEY         = WD_INPLAN.STORERKEY        
            AND  DP_INPLAN.DOCNO             = WD_INPLAN.DOCNO     
            AND  DP_INPLAN.DOCLINE           = WD_INPLAN.DOCLINE 
            AND  DP_INPLAN.DCCODE            = WD_INPLAN.CUSTKEY 
            AND  DP_INPLAN.SKU               = WD_INPLAN.SKU
            AND  DP_INPLAN.DEL_YN            = 'N'
        LEFT OUTER JOIN  ST_SNINFO                        
             ON  ST_SNINFO.STORERKEY         = WD_INVOICE_SN.STORERKEY 
            AND  ST_SNINFO.SKU               = WD_INVOICE_SN.SKU       
            AND  ST_SNINFO.SERIALNO          = WD_INVOICE_SN.SERIALNO  
            AND  ST_SNINFO.STOCKID           = WD_INVOICE_SN.STOCKID
                
        LEFT OUTER JOIN FRAMEONE_USER USER1
             ON USER1.USER_ID = DM_DOCUMENT_D.ADDWHO OR USER1.USER_NO = DM_DOCUMENT_D.ADDWHO
             
        LEFT OUTER JOIN FRAMEONE_USER USER2
             ON USER2.USER_ID = DM_DOCUMENT_D.EDITWHO OR USER2.USER_NO = DM_DOCUMENT_D.EDITWHO  
        
        LEFT OUTER JOIN CM_CODE_STORER CD1
                    ON CD1.STORERKEY = DM_DOCUMENT_H.STORERKEY
                   AND CD1.CODELIST  = 'ORDERTYPE_WD'   
                   AND CD1.BASECODE  = DM_DOCUMENT_H.ORDERTYPE                   
        LEFT OUTER JOIN CM_CODE_STORER CD2
                    ON CD2.STORERKEY = DM_DOCUMENT_D.STORERKEY
                   AND CD2.CODELIST  = 'STATUS_WD'   
                   AND CD2.BASECODE  = DM_DOCUMENT_D.STATUS                   
        LEFT OUTER JOIN CM_CODE_STORER CD3
                    ON CD3.STORERKEY = DM_DOCUMENT_D.STORERKEY
                   AND CD3.CODELIST  = 'PUTAWAYTYPE'   
                   AND CD3.BASECODE  = DM_DOCUMENT_D.CHANNEL                   
        LEFT OUTER JOIN CM_CODE_STORER CD4
                    ON CD4.STORERKEY = WD_INPLAN.STORERKEY
                   AND CD4.CODELIST  = 'STORAGETYPE'   
                   AND CD4.BASECODE  = MS_SKU.STORAGETYPE                   
        LEFT OUTER JOIN CM_CODE_STORER CD5
                    ON CD5.STORERKEY = ST_SNINFO.STORERKEY
                   AND CD5.CODELIST  = 'CONTRACTTYPE_SN'   
                   AND CD5.BASECODE  = ST_SNINFO.CONTRACTTYPE           
         LEFT OUTER JOIN CM_CODE_STORER CD6
                    ON CD6.STORERKEY = WD_INPLAN.STORERKEY
                   AND CD6.CODELIST  = 'TAX_CLS'   
                   AND CD6.BASECODE  = MS_SKU.OTHER05        
         LEFT OUTER JOIN CM_CODE_STORER CD7
                    ON CD7.STORERKEY = WD_INPLAN.STORERKEY
                   AND CD7.CODELIST  = 'DELIVERYTYPE'   
                   AND CD7.BASECODE  = (SELECT CASE WHEN MAX(DM_DOCUMENT_H.WORKPROCESSCODE) = 'STO'
                                                    THEN 'WOD'
                                                    ELSE MAX(DM_DOCUMENT_H.DELIVERYTYPE)
                                               END
                                         FROM DM_DOCUMENT_H
                                        WHERE DM_DOCUMENT_H.DCCODE       = WD_INPLAN.DCCODE
                                          AND DM_DOCUMENT_H.ORGANIZE     = WD_INPLAN.ORGANIZE
                                          AND DM_DOCUMENT_H.DELIVERYDATE = WD_INPLAN.SLIPDT
                                          AND DM_DOCUMENT_H.DOCNO        = WD_INPLAN.DOCNO
                                               )            

      WHERE  WD_INPLAN.DCCODE            = #{fixdccode}
        AND  WD_INPLAN.STORERKEY         = #{gStorerkey}
        <if test="sku != null and sku != '' ">
            <if test="skuMulti != null and skuMulti.size() > 0">
                <trim prefix="AND (" suffix=")" prefixOverrides="OR">
                    <foreach collection="skuMulti" item="item">
                        OR WD_INPLAN.SKU IN
                        <foreach collection="item" item="code" open="(" close=")" separator=",">
                            #{code}      
                        </foreach>
                    </foreach>
                </trim> 
            </if>
        </if>
        <if test="organizeMulti != null and organizeMulti != ''">
            AND  WD_INPLAN.ORGANIZE      IN
            <foreach collection="organizeMulti" item="item" open="(" separator="," close=")">
                 #{item}
            </foreach> 
        </if>
        <if test="docnoMulti != null and docnoMulti != ''">
            AND  WD_INPLAN.DOCNO IN
            <foreach collection="docnoMulti" item="item" open="(" separator="," close=")">
                 #{item}
            </foreach> 
        </if>                    
        <if test="ordertype != null and ordertype != ''">    
            AND  WD_INPLAN.ORDERTYPE          = #{ordertype}                  
        </if>             
        <if test="status != null and status != ''">    
            AND  DM_DOCUMENT_D.STATUS         = #{status}                  
        </if>
        <if test="status == null or status == ''">    
            AND  DM_DOCUMENT_D.STATUS         IN (SELECT BASECODE FROM CM_CODE_STORER WHERE STORERKEY = WD_INPLAN.STORERKEY AND CODELIST = 'STATUS_WD' AND DATA2 = 'EX')                  
        </if>
            AND  DM_DOCUMENT_D.DELIVERYDATE  <![CDATA[>=]]> #{fromSlipdt}
            AND  DM_DOCUMENT_D.DELIVERYDATE  <![CDATA[<=]]> #{toSlipdt}
              
        <if test="blnoMulti != null and blnoMulti != ''">
                   AND    ST_SNINFO.CONVSERIALNO      IN
                 <foreach collection="blnoMulti" item="item" open="(" separator="," close=")">
                     #{item}
                 </foreach> 
        </if>
        <if test="serialno != null and serialno != ''"> 
            AND  ST_SNINFO.SERIALNO           = #{serialno}
        </if>  
        <if test="wdCustkeyMulti != null and wdCustkeyMulti != ''">
            AND  ST_SNINFO.CONTRACTCUSTKEY      IN
            <foreach collection="wdCustkeyMulti" item="item" open="(" separator="," close=")">
                 #{item}
            </foreach> 
        </if>   
        <if test="contracttypeSn != null and contracttypeSn != ''"> 
            AND  ST_SNINFO.CONTRACTTYPE       = #{contracttypeSn}
        </if>
        <if test="stoYn == 1">
            AND (DM_DOCUMENT_D.DCCODE = '2170' AND DM_DOCUMENT_D.ORDERTYPE = 'ZUB' AND DM_DOCUMENT_D.SOTYPE = 'STO')
        </if>
        <if test="scmUser != null and scmUser != ''">
            AND DM_DOCUMENT_H.ADDWHO IN ( SELECT * FROM TABLE(FN_SPLIT_ARRAY( 
                        (SELECT DATA2
                        FROM CM_CODE_STORER
                        WHERE CODELIST = 'EXDC_MANAGE_USER' 
                        AND BASECODE = #{scmUser}
                        FETCH FIRST 1 ROWS ONLY ))
                   )
                )
        </if>

      ORDER BY DM_DOCUMENT_H.ORDERTYPE
              ,DM_DOCUMENT_H.TO_CUSTKEY
              ,DM_DOCUMENT_H.DOCNO
              ,WD_INPLAN.SLIPDT
              ,WD_INPLAN.SLIPNO
    </select>    
    
    <select id="getPriceMasterList" resultType="WdShipmentExDCResDto">
        SELECT   /* [wdShipmentExDCService.sqlx][getExDcDataHeaderList][외부창고 출고확정 목록 조회][sunho.kim][2025.06.30] */
               WD_INPLAN.DCCODE                                                                                                                 AS DCCODE                               /* 물류센터 */
              ,WD_INPLAN.STORERKEY                                                                                                              AS STORERKEY                            /* 고객사코드 */
              ,WD_INPLAN.ORGANIZE                                                                                                               AS ORGANIZE                             /* 창고코드 */
              ,FN_DESCR_ORGANIZE(WD_INPLAN.DCCODE,WD_INPLAN.ORGANIZE)                                                                           AS ORGANIZENAME                         /* 창고명 */
              ,WD_INPLAN.AREA                                                                                                                   AS AREA                                 /* 작업영역 */
              ,WD_INPLAN.DOCDT                                                                                                                  AS DOCDT                                /* 문서생셩일자 */
              ,WD_INPLAN.DOCNO                                                                                                                  AS DOCNO                                /* 문서번호 */
              ,WD_INPLAN.DOCLINE                                                                                                                AS DOCLINE                              /* 문서라인 */
              ,WD_INPLAN.DOCTYPE                                                                                                                AS DOCTYPE                              /* 문서유형 */
              ,WD_INPLAN.SLIPDT                                                                                                                 AS SLIPDT                               /* 전표일자 */
              ,WD_INPLAN.SLIPNO                                                                                                                 AS SLIPNO                               /* 전표번호 */    
              ,WD_INPLAN.SLIPLINE                                                                                                               AS SLIPLINE                             /* 전표라인 */
              ,WD_INPLAN.ORDERTYPE                                                                                                              AS ORDERTYPE                            /* 구매유형코드 */
              ,CD1.BASEDESCR                                                                                                                    AS ORDERTYPE_NAME                       /* 구매유형명 */
              ,WD_INPLAN.SKU                                                                                                                    AS SKU                                  /* 상품코드 */
              ,MS_SKU.DESCRIPTION                                                                                                               AS SKUNAME                              /* 상품명 */
              ,DM_DOCUMENT_H.TO_CUSTKEY                                                                                                         AS TO_CUSTKEY                           /* 관리처코드 */
              ,DM_DOCUMENT_H.TO_CUSTNAME                                                                                                        AS TO_CUSTNAME                          /* 관리처명 */
              ,DM_DOCUMENT_D.SERIALKEY                                                                                                          AS SERIALKEY                            /* 데이터번호 */
              ,DM_DOCUMENT_D.STORERUOM                                                                                                          AS STORERUOM                            /* 저장단위 */
              ,DM_DOCUMENT_D.UOM                                                                                                                AS UOM                                  /* 단위 */
              ,DM_DOCUMENT_D.BUNJA                                                                                                              AS BUNJA                                /* 분자 */
              ,DM_DOCUMENT_D.BUNMO                                                                                                              AS BUNMO                                /* 분모 */
              ,FN_UOMCAL  ( DM_DOCUMENT_D.BUNMO
                           ,DM_DOCUMENT_D.BUNJA
                           ,WD_INPLAN.ORDERQTY + WD_INPLAN.CANCELQTY    )                                                                       AS ORDERQTY                             /* 주문수량 */
              ,FN_UOMCAL  ( DM_DOCUMENT_D.BUNMO
                           ,DM_DOCUMENT_D.BUNJA
                           ,WD_INPLAN.INSPECTQTY)                                                                                               AS INSPECTQTY                           /* 검수수량 */
              ,FN_UOMCAL  ( DM_DOCUMENT_D.BUNMO
                           ,DM_DOCUMENT_D.BUNJA
                           ,WD_INPLAN.CONFIRMQTY)                                                                                               AS CONFIRMQTY                           /* 출고수량 */
              ,ABS(FN_UOMCAL  ( DM_DOCUMENT_D.BUNMO
                           ,DM_DOCUMENT_D.BUNJA
                           ,WD_INPLAN.CANCELQTY    ))                                                                                           AS SHORTAGEQTY                          /* 결품수량 */
              ,0                                                                                                                                AS SHORTAGETRANQTY                      /* 결품작업량 */
              ,0                                                                                                                                AS TRANQTY                              /* 출고작업량 */
              ,CORE_CM_STRATEGY.FN_GETTOLOC ( WD_INPLAN.DOCTYPE    
                                             ,WD_INPLAN.DCCODE     
                                             ,WD_INPLAN.STORERKEY  
                                             ,WD_INPLAN.ORDERTYPE  
                                             ,WD_INPLAN.SLIPTYPE   )                                                                            AS TOLOC                                /* TO 로케이션 */
              ,NVL(ST_SNINFO.LOTTABLE01,'STD')                                                                                                  AS LOTTABLE01                           /* 기준일 */
              ,FN_LOTDURATION(WD_INPLAN.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, NVL(ST_SNINFO.LOTTABLE01,'STD'), 'N')||'/'||MS_SKU.DURATION      AS DURATION_TERM              /* 소비기간 */
              ,MS_SKU.COLORDESCR                                                                                                                AS COLORDESCR                           /* 색상 */   
              ,DM_DOCUMENT_D.REFERENCE02                                                                                                        AS REFERENCE02                          /* REFERENCE02 */
              ,NVL(DM_DOCUMENT_D.REFERENCE08,0)                                                                                                 AS REFERENCE08                          /* 주문수량에 대한 총 보관료 */
              ,NVL(DM_DOCUMENT_D.REFERENCE09,0)                                                                                                 AS REFERENCE09                          /* 계산된 보관료 */
              ,NVL(DM_DOCUMENT_D.REFERENCE10,0)                                                                                                 AS REFERENCE10                          /* 운송료 */
              ,CASE WHEN MS_SKU.OTHER05 = 'X3' THEN ROUND(TO_NUMBER(NVL(DM_DOCUMENT_D.REFERENCE10,0))*10/11)
                    ELSE TO_NUMBER(NVL(DM_DOCUMENT_D.REFERENCE10,0))
               END                                                                                                                              AS TRANDELIVERYPRICE                    /* 운송료(공급가) */
              ,DM_DOCUMENT_D.REASONCODE                                                                                                         AS REASONCODE                           /* 사유코드 */
              ,DM_DOCUMENT_D.REASONMSG                                                                                                          AS REASONMSG                            /* 처리결과 */
              ,CASE WHEN NVL(ST_SNINFO.LOTTABLE01,'STD')='STD' THEN 'N' 
                    WHEN MONTHS_BETWEEN(TO_DATE(NVL(ST_SNINFO.LOTTABLE01,'STD'),'yyyy-mm-dd'),SYSDATE) <![CDATA[>]]> 3 
                    THEN 'N' 
                    ELSE 'Y' 
                END                                                                                                                             AS NEARDURATIONYN                       /* 소비기한여부 */
              ,DM_DOCUMENT_D.STATUS                                                                                                             AS STATUS                               /* 상태코드 */    
              ,CD2.BASEDESCR                                                                                                                    AS STATUSNAME                           /* 상태명 */
              ,MS_SKU.QTYPERBOX                                                                                                                 AS QTYPERBOX                            /* 박스수량 */    
              ,DM_DOCUMENT_D.CHANNEL                                                                                                            AS CHANNEL                              /* 채녈 */  
              ,MS_SKU.DURATION                                                                                                                  AS DURATION                             /* 기간코드 */
              ,MS_SKU.DURATIONTYPE                                                                                                              AS DURATIONTYPE                         /* 기간유형코드 */    
              ,''                                                                                                                               AS LASTLOTTABLE01                       /* LASTLOTTABLE01 */
              ,NVL(ST_SNINFO.STOCKID,WD_INPLAN.STOCKID)                                                                                         AS STOCKID                              /* 재고 구분 ID */    
              ,WD_INPLAN.STOCKGRADE                                                                                                             AS STOCKGRADE                           /* 재고 구분 등급 */
              ,DM_DOCUMENT_D.PLANT                                                                                                              AS PLANT                                /* 플랜트코드 */
              ,'['||DM_DOCUMENT_D.PLANT||']'||FN_DESCR_PLANT(DM_DOCUMENT_D.PLANT)                                                               AS PLANT_DESCR                          /* 플랜트명 */
              ,CD3.BASEDESCR                                                                                                                    AS CHANNEL_NAME                         /* 채널명 */
              ,MS_SKU.STORAGETYPE                                                                                                               AS STORAGETYPE                          /* 저장조건 */ 
              ,CD4.BASEDESCR                                                                                                                    AS STORAGETYPENAME                      /* 저장조건명 */
              ,ST_SNINFO.SERIALNO                                                                                                               AS SERIALNO                             /* 이력번호 */    
              ,ST_SNINFO.CONVSERIALNO                                                                                                           AS CONVSERIALNO                         /* B/L번호 */   
              ,ST_SNINFO.FACTORYNAME                                                                                                            AS FACTORYNAME                          /* 도축장명 */
              ,ST_SNINFO.CONTRACTCUSTKEY                                                                                                        AS CONTRACTCOMPANY                      /* 계약업체코드 */      
              ,( SELECT DESCRIPTION  FROM MS_CUST
                  WHERE CUSTKEY = ST_SNINFO.CONTRACTCUSTKEY
                    AND ROWNUM = 1)                                                                                                             AS CONTRACTCOMPANYNAME                  /* 계약업체명 */    
              ,CD5.BASEDESCR                                                                                                                    AS CONTRACTTYPE                         /* 계약유형 */    
              ,ST_SNINFO.BUTCHERYDT                                                                                                             AS BUTCHERYDT                           /* 도축일자 */
              ,ST_SNINFO.FROMVALIDDT                                                                                                            AS FROMVALIDDT                          /* 유효시작일 */    
              ,ST_SNINFO.TOVALIDDT                                                                                                              AS TOVALIDDT                            /* 유효종료일 */
              ,ST_SNINFO.STOCKID                                                                                                                AS BARCODE                              /* 바코드 */
              ,CASE WHEN ST_SNINFO.STOCKID IS NULL THEN NULL
                    ELSE FN_UOMCAL ( DM_DOCUMENT_D.BUNMO
                                   ,DM_DOCUMENT_D.BUNJA
                                   ,WD_INVOICE_SN.ORDERQTY - WD_INVOICE_SN.CONFIRMQTY)
               END                                                                                                                              AS SERIALORDERQTY                       /* 스캔예정량 */
              ,CASE WHEN ST_SNINFO.STOCKID IS NULL THEN NULL    
                    ELSE 0
               END                                                                                                                              AS SERIALINSPECTQTY                     /* 스캔량 */
              ,CASE WHEN ST_SNINFO.STOCKID IS NULL THEN NULL
                     ELSE 0
                END                                                                                                                             AS SERIALSCANWEIGHT                     /* 스캔중량 */
              ,CASE WHEN  WD_INPLAN.STORERKEY = 'CJFW' 
                     OR (    ST_SNINFO.SERIALNO IS NOT NULL
                         AND (   DM_DOCUMENT_D.CHANNEL <![CDATA[<>]]> '1' 
                              OR WD_INPLAN.DCCODE IN ('2170'))
                         ) THEN 'Y'                                         
                   WHEN  WD_INPLAN.DCCODE IN (SELECT BASECODE
                                              FROM   CM_CODE_STORER WMS_MNG_DC
                                              WHERE  WMS_MNG_DC.STORERKEY = #{gStorerkey}
                                              AND    WMS_MNG_DC.CODELIST  = 'WMS_MNG_DC'
                                              AND    WMS_MNG_DC.DATA3     = 'Y'
                                              AND    WMS_MNG_DC.BASECODE  != '2170') THEN 'Y'
                   ELSE 'N' 
               END                                                                                                                              AS CHECKFLAG                            /* 체크플래그 */
              ,MS_SKU.LINE01                                                                                                                    AS LINE01                               /* LINE01 */
              ,CASE WHEN WD_INPLAN.DCCODE IN (SELECT BASECODE
                                              FROM   CM_CODE_STORER WMS_MNG_DC
                                              WHERE  WMS_MNG_DC.STORERKEY = #{gStorerkey}
                                              AND    WMS_MNG_DC.CODELIST  = 'WMS_MNG_DC'
                                              AND    WMS_MNG_DC.DATA3     = 'Y'
                                              AND    WMS_MNG_DC.BASECODE  != '2170') THEN 'black' 
                   WHEN WD_INPLAN.STORERKEY = 'FW00' AND ST_SNINFO.SERIALNO IS NULL  THEN 'gray' 
                   ELSE 'black' 
               END                                                                                                                              AS FONTCOLOR                             /* 폰트컬러 */
              ,CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 
                     AND WD_INPLAN.DCCODE       = '2170' 
                     AND NVL(MS_SKU.LINE01,'N') = 'Y'          THEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) 
                    ELSE 0 
                END                                                                                                                             AS AVGWEIGHT                            /* 평균중량 */
              ,ROUND(CASE WHEN TO_NUMBER(NVL(MS_SKU.LINE02,0)) <![CDATA[<>]]> 0 
                               AND WD_INPLAN.DCCODE       = '2170' 
                               AND NVL(MS_SKU.LINE01,'N') = 'Y'    
                          THEN (WD_INVOICE_SN.ORDERQTY + WD_INVOICE_SN.CANCELQTY) / TO_NUMBER(NVL(MS_SKU.LINE02,0)) 
                          ELSE 0 
                    END ,3)                                                                                                                     AS CALBOX                               /* 환산박스 */        
              ,CASE WHEN WD_INPLAN.DCCODE       = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'          
                    THEN NVL(WD_INVOICE_SN.ETCQTY1,0)                                                                                                  
                    ELSE 0
               END                                                                                                                              AS REALORDERBOX                         /* 실박스예정 */
              ,CASE WHEN WD_INPLAN.DCCODE       = '2170'  AND NVL(MS_SKU.LINE01,'N') = 'Y'          
                    THEN NVL(WD_INVOICE_SN.ETCQTY2,0)
                    ELSE 0
               END                                                                                                                              AS REALCFMBOX                           /* 실박스확정 */              
              ,CASE WHEN WD_INPLAN.DCCODE       = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y' AND NVL(WD_INVOICE_SN.ETCQTY2,0) = 0      
                    THEN NVL(WD_INVOICE_SN.ETCQTY1,0)
                     ELSE 0
               END                                                                                                                              AS TRANBOX                              /* 작업박스 */
              ,CASE WHEN WD_INPLAN.DCCODE       = '2170' AND NVL(MS_SKU.LINE01,'N') = 'Y'          
                    THEN 'Y'
                    ELSE 'N'
               END                                                                                                                              AS BOXFLAG                              /* 박스처리유무 */
              ,CASE WHEN DM_DOCUMENT_D.DCCODE   = '2170' AND DM_DOCUMENT_D.ORDERTYPE = 'ZUB' AND DM_DOCUMENT_D.SOTYPE = 'STO'
                    THEN 'Y'
                    ELSE 'N'
               END                                                                                                                              AS STOFLAG                              /* STO플래그 */
              ,CASE WHEN MS_SKU.OTHER05 = 'X3' 
                    THEN 1.1
                    ELSE 1
               END                                                                                                                              AS OTHER05                              /* 과세,면세 구분(비율)*/
              ,CD6.BASEDESCR                                                                                                                    AS TAX_CLS                              /* 과세,면세 구분*/
              ,MS_SKU.SERIALYN                                                                                                                  AS SERIALYN
              ,NVL(DM_DOCUMENT_D.REAL_YN, '')                                                                                                   AS REAL_YN                              /* 가/진오더 여부 */
              ,DM_DOCUMENT_D.TEMP_YN                                                                                                            AS TEMP_YN                              /* 임시 여부 */
              ,ST_SNINFO.POKEY                                                                                                                  AS POKEY                                /* PO번호 */
              ,ST_SNINFO.POLINE                                                                                                                 AS POLINE                               /* PO라인 */
              ,CASE WHEN DM_DOCUMENT_D.CANCELQTY > 0 
                         AND DM_DOCUMENT_D.CONFIRMQTY = 0 
                         AND DM_DOCUMENT_D.STATUS = '90'  
                     THEN 'Y'
                     ELSE 'N'
                END                                                                                                                             AS ALL_CANCEL_STATUS                    /* 전체취소여부 */ 
              ,DECODE(MS_EXDCRATE.SKU, NULL, 'N', 'Y')                                                                                          AS EXDCRATE_YN                          /* 창고요율등록여부 */ 
              ,CD7.BASEDESCR                                                                                                                    AS DELIVERYTYPENAME                     /* 출고방법 */
              ,FN_CONV_UOM(WD_INPLAN.STORERKEY, WD_INPLAN.SKU, WD_INPLAN.UOM, 'KG'
                         , FN_UOMCAL(DM_DOCUMENT_D.BUNMO
                                   , DM_DOCUMENT_D.BUNJA
                                   , CASE WHEN WD_INPLAN.CONFIRMQTY > 0 THEN WD_INPLAN.CONFIRMQTY
                                          ELSE (WD_INPLAN.ORDERQTY + WD_INPLAN.CANCELQTY)
                                      END
                                    ) 
                          )                                                                                                                     AS WEIGHT                               /* 중량 */ 
              ,CASE WHEN NVL(DM_DOCUMENT_D.REFERENCE03, '') = '' THEN NULL
                    ELSE DM_DOCUMENT_D.REFERENCE03
                 END                                                                                                                            AS SERIALKEY_GROUP                      /* 그룹 데이터번호 */
              ,DM_DOCUMENT_D.ADDWHO                                                                                                             AS ADDWHO                               /* 등록자 */
              ,USER1.USER_NM                                                                                                                    AS ADDWHO_NM                            /* 등록자명 */
              ,DM_DOCUMENT_D.ADDDATE                                                                                                            AS ADDDATE                              /* 등록일시 */ 
              ,DM_DOCUMENT_D.EDITWHO                                                                                                            AS EDITWHO                              /* 수정자 */
              ,USER2.USER_NM                                                                                                                    AS EDITWHO_NM                           /* 수정자명 */
              ,DM_DOCUMENT_D.EDITDATE                                                                                                           AS EDITDATE                             /* 수정일시 */
        
        FROM  WD_INPLAN                
        
        JOIN  CM_USER_AUTHORITY          
             ON  CM_USER_AUTHORITY.USERID     = #{gUserId}     
            AND  CM_USER_AUTHORITY.DCCODE     = WD_INPLAN.DCCODE             
            AND  CM_USER_AUTHORITY.STORERKEY  = WD_INPLAN.STORERKEY          
            AND  CM_USER_AUTHORITY.ORGANIZE   = WD_INPLAN.ORGANIZE           
            AND  CM_USER_AUTHORITY.AREA       = WD_INPLAN.AREA           
        <if test="fixdccode != null and fixdccode != ''"> 
            AND  CM_USER_AUTHORITY.DCCODE     = #{fixdccode}      
        </if>
        <if test="gStorerkey != null and gStorerkey != ''">
            AND  CM_USER_AUTHORITY.STORERKEY  = #{gStorerkey}   
        </if>
        <if test="organizeMulti != null and organizeMulti != ''">
            AND  CM_USER_AUTHORITY.ORGANIZE      IN
            <foreach collection="organizeMulti" item="item" open="(" separator="," close=")">
                 #{item}
            </foreach> 
        </if>
        <if test="area != null and area != ''">
            AND  CM_USER_AUTHORITY.AREA       = #{area}        
        </if>       
        JOIN DM_DOCUMENT_H          
             ON  DM_DOCUMENT_H.DCCODE         = WD_INPLAN.DCCODE                  
            AND  DM_DOCUMENT_H.DELIVERYDATE   = WD_INPLAN.SLIPDT         
            AND  DM_DOCUMENT_H.DOCTYPE        = WD_INPLAN.DOCTYPE               
            AND  DM_DOCUMENT_H.DOCNO          = WD_INPLAN.DOCNO        
            AND  DM_DOCUMENT_H.DOCTYPE        = 'WD'         
            AND  DM_DOCUMENT_H.DEL_YN         = 'N'  
          <if test="fromCustkeyMulti != null and fromCustkeyMulti != ''">
            AND  DM_DOCUMENT_H.TO_CUSTKEY      IN
            <foreach collection="fromCustkeyMulti" item="item" open="(" separator="," close=")">
                 #{item}
            </foreach> 
          </if>           
        JOIN DM_DOCUMENT_D
             ON  DM_DOCUMENT_D.DCCODE         = WD_INPLAN.DCCODE      
            AND  DM_DOCUMENT_D.DOCTYPE        = WD_INPLAN.DOCTYPE     
            AND  DM_DOCUMENT_D.DELIVERYDATE   = WD_INPLAN.SLIPDT       
            AND  DM_DOCUMENT_D.DOCNO          = WD_INPLAN.DOCNO       
            AND  DM_DOCUMENT_D.DOCLINE        = WD_INPLAN.DOCLINE 
            AND  DM_DOCUMENT_D.CHANNEL        IN ('1','2','3')   <!-- 저장품만 처리함 1.저장 2.일배 3.광역일배 2015.01.26 SLLEE MODIFY [ 1,2] 김해경님 요청 -->
        <if test="channel != null and channel != ''">
            AND  DM_DOCUMENT_D.CHANNEL        = #{channel}             
        </if>
            AND  DM_DOCUMENT_D.DEL_YN         = 'N'    
        <if test="allshortageYn == 'N'">
            AND  DM_DOCUMENT_D.OPENQTY <![CDATA[>]]> DM_DOCUMENT_D.CANCELQTY              
        </if>
        <if test="allshortageYn == 'Y'">
            AND  DM_DOCUMENT_D.OPENQTY <![CDATA[=]]> DM_DOCUMENT_D.CANCELQTY             
        </if>
        JOIN MS_SKU 
             ON  MS_SKU.STORERKEY             = WD_INPLAN.STORERKEY         
            AND  MS_SKU.SKU                   = WD_INPLAN.SKU
            AND  MS_SKU.DEL_YN                = 'N'
        <if test="storagetype != null and storagetype != ''">  
            AND  MS_SKU.STORAGETYPE           = #{storagetype}                  
        </if>
        LEFT OUTER JOIN  WD_INVOICE_SN
             ON  WD_INVOICE_SN.DCCODE        = WD_INPLAN.DCCODE                   
            AND  WD_INVOICE_SN.STORERKEY     = WD_INPLAN.STORERKEY        
            AND  WD_INVOICE_SN.DOCTYPE       = WD_INPLAN.DOCTYPE
            AND  WD_INVOICE_SN.WD_SLIPNO     = WD_INPLAN.SLIPNO                              
            AND  WD_INVOICE_SN.WD_SLIPDT     = WD_INPLAN.SLIPDT                   
            AND  WD_INVOICE_SN.WD_SLIPLINE   = WD_INPLAN.SLIPLINE                   
            AND  WD_INVOICE_SN.SKU           = WD_INPLAN.SKU
        LEFT OUTER JOIN  ST_SNINFO                        
             ON  ST_SNINFO.STORERKEY         = WD_INVOICE_SN.STORERKEY 
            AND  ST_SNINFO.SKU               = WD_INVOICE_SN.SKU       
            AND  ST_SNINFO.SERIALNO          = WD_INVOICE_SN.SERIALNO  
            AND  ST_SNINFO.STOCKID           = WD_INVOICE_SN.STOCKID
        LEFT OUTER JOIN (
                    SELECT 
                        DCCODE, ORGANIZE, SKU, AREA_PRICE_UOM
                    FROM MS_EXDCRATE 
                    WHERE MS_EXDCRATE.DCCODE                  = #{fixdccode}
                        AND  MS_EXDCRATE.DEL_YN               = 'N'
                        AND  MS_EXDCRATE.FROMDATE    <![CDATA[<=]]> #{fromSlipdt} 
                        AND  MS_EXDCRATE.TODATE      <![CDATA[>=]]> #{toSlipdt} 
                    GROUP BY DCCODE, ORGANIZE, SKU, AREA_PRICE_UOM
                     )  MS_EXDCRATE 
            ON   MS_EXDCRATE.DCCODE           = DM_DOCUMENT_D.DCCODE
            AND  MS_EXDCRATE.ORGANIZE         = DM_DOCUMENT_D.ORGANIZE
            AND  MS_EXDCRATE.SKU              = DM_DOCUMENT_D.SKU
                
        LEFT OUTER JOIN FRAMEONE_USER USER1
             ON USER1.USER_ID = DM_DOCUMENT_D.ADDWHO OR USER1.USER_NO = DM_DOCUMENT_D.ADDWHO
             
        LEFT OUTER JOIN FRAMEONE_USER USER2
             ON USER2.USER_ID = DM_DOCUMENT_D.EDITWHO OR USER2.USER_NO = DM_DOCUMENT_D.EDITWHO  
        
        LEFT OUTER JOIN CM_CODE_STORER CD1
                    ON CD1.STORERKEY = DM_DOCUMENT_H.STORERKEY
                   AND CD1.CODELIST  = 'ORDERTYPE_WD'   
                   AND CD1.BASECODE  = DM_DOCUMENT_H.ORDERTYPE                   
        LEFT OUTER JOIN CM_CODE_STORER CD2
                    ON CD2.STORERKEY = DM_DOCUMENT_D.STORERKEY
                   AND CD2.CODELIST  = 'STATUS_WD'   
                   AND CD2.BASECODE  = DM_DOCUMENT_D.STATUS                   
        LEFT OUTER JOIN CM_CODE_STORER CD3
                    ON CD3.STORERKEY = DM_DOCUMENT_D.STORERKEY
                   AND CD3.CODELIST  = 'PUTAWAYTYPE'   
                   AND CD3.BASECODE  = DM_DOCUMENT_D.CHANNEL                   
        LEFT OUTER JOIN CM_CODE_STORER CD4
                    ON CD4.STORERKEY = WD_INPLAN.STORERKEY
                   AND CD4.CODELIST  = 'STORAGETYPE'   
                   AND CD4.BASECODE  = MS_SKU.STORAGETYPE                   
        LEFT OUTER JOIN CM_CODE_STORER CD5
                    ON CD5.STORERKEY = ST_SNINFO.STORERKEY
                   AND CD5.CODELIST  = 'CONTRACTTYPE_SN'   
                   AND CD5.BASECODE  = ST_SNINFO.CONTRACTTYPE           
         LEFT OUTER JOIN CM_CODE_STORER CD6
                    ON CD6.STORERKEY = WD_INPLAN.STORERKEY
                   AND CD6.CODELIST  = 'TAX_CLS'   
                   AND CD6.BASECODE  = MS_SKU.OTHER05        
         LEFT OUTER JOIN CM_CODE_STORER CD7
                    ON CD7.STORERKEY = WD_INPLAN.STORERKEY
                   AND CD7.CODELIST  = 'DELIVERYTYPE'   
                   AND CD7.BASECODE  = (SELECT CASE WHEN MAX(DM_DOCUMENT_H.WORKPROCESSCODE) = 'STO'
                                                    THEN 'WOD'
                                                    ELSE MAX(DM_DOCUMENT_H.DELIVERYTYPE)
                                               END
                                         FROM DM_DOCUMENT_H
                                        WHERE DM_DOCUMENT_H.DCCODE       = WD_INPLAN.DCCODE
                                          AND DM_DOCUMENT_H.ORGANIZE     = WD_INPLAN.ORGANIZE
                                          AND DM_DOCUMENT_H.DELIVERYDATE = WD_INPLAN.SLIPDT
                                          AND DM_DOCUMENT_H.DOCNO        = WD_INPLAN.DOCNO
                                               )            

      WHERE   WD_INPLAN.STORERKEY       = #{gStorerkey}
        <if test="dccode != null and dccode != ''"> 
          AND WD_INPLAN.DCCODE          = #{dccode} 
        </if>
          AND DM_DOCUMENT_D.DELIVERYDATE  <![CDATA[>=]]> #{fromSlipdt}
          AND DM_DOCUMENT_D.DELIVERYDATE  <![CDATA[<=]]> #{toSlipdt}
          AND DM_DOCUMENT_D.REFERENCE03 = #{serialkeyGroup}
        <if test="scmUser != null and scmUser != ''">
          AND DM_DOCUMENT_H.ADDWHO IN ( SELECT * FROM TABLE(FN_SPLIT_ARRAY( 
                        (SELECT DATA2
                        FROM CM_CODE_STORER
                        WHERE CODELIST = 'EXDC_MANAGE_USER' 
                        AND BASECODE = #{scmUser}
                        FETCH FIRST 1 ROWS ONLY ))
                   )
                )
        </if>
        
      ORDER BY DM_DOCUMENT_H.ORDERTYPE
              ,DM_DOCUMENT_H.TO_CUSTKEY
              ,DM_DOCUMENT_H.DOCNO
              ,WD_INPLAN.SLIPDT
              ,WD_INPLAN.SLIPNO
    </select>
    
    <select id="getExistDoc" resultType="int">
        SELECT   /* [wdShipmentExDCService.sqlx][getExistDoc][디테일 확정/취소 Validation Check][sunho.kim][2025.06.30] */
               COUNT(1) AS CHECK_CNT
        FROM   DM_DOCUMENT_D 
        JOIN   ST_EXDCSTORAGE
            ON     ST_EXDCSTORAGE.YYYYMM   = ST_EXDCSTORAGE.YYYYMM
            AND    ST_EXDCSTORAGE.DCCODE   = DM_DOCUMENT_D.DCCODE  
            AND    ST_EXDCSTORAGE.ORGANIZE = DM_DOCUMENT_D.ORGANIZE
            AND    ST_EXDCSTORAGE.IO_FLAG  = DM_DOCUMENT_D.DOCTYPE 
            AND    ST_EXDCSTORAGE.DOCNO    = DM_DOCUMENT_D.DOCNO   
            AND    ST_EXDCSTORAGE.DOCLINE  = DM_DOCUMENT_D.DOCLINE 
        <if test="stockid != null and stockid != ''">
            AND    ST_EXDCSTORAGE.STOCKID  = #{stockid}
        </if>
        JOIN   IB_EXPENSE_DISTRIBUTION
            ON     IB_EXPENSE_DISTRIBUTION.DOCUMENT_TYPE_CODE = 'WH'
            AND    IB_EXPENSE_DISTRIBUTION.DOCUMENT_SN        = ST_EXDCSTORAGE.SERIALKEY
        JOIN   IB_EXPENSE
            ON     IB_EXPENSE.SERIALKEY    = IB_EXPENSE_DISTRIBUTION.EXPENSE_SN
            AND    IB_EXPENSE.IF_ID        = 'SCM0470'
        WHERE      DM_DOCUMENT_D.DCCODE    = #{dccode}
            AND    DM_DOCUMENT_D.DOCTYPE   = 'WD'
            AND    DM_DOCUMENT_D.DELIVERYDATE = #{slipdt}
            AND    DM_DOCUMENT_D.DOCNO     = #{slipno}
        <if test="slipline != null and slipline != ''">
            AND    DM_DOCUMENT_D.DOCLINE   = #{slipline}
        </if>
    </select> 
    
    <select id="getSkuForCheck" resultType="WdShipmentExDCResDto">
        SELECT   /* [wdShipmentExDCService.sqlx][getSkuForCheck][디테일 확정/취소 Validation Check][sunho.kim][2025.06.30] */
               DM_DOCUMENT_D.DCCODE            AS DCCODE                        /* 물류센터 */
             , DM_DOCUMENT_D.SKU               AS SKU                           /* 상품코드 */
             , ST_SNINFO.CONVSERIALNO          AS CONVSERIALNO                  /* B/L번호 */
             , ST_SNINFO.SERIALNO              AS SERIALNO                      /* 이력번호 */  
             , ST_SNINFO.POKEY                 AS POKEY                         /* 구매번호 */
             , ST_SNINFO.POLINE                AS POLINE                        /* 구매번호라인 */
        FROM   DM_DOCUMENT_D 
        JOIN   WD_INVOICE_SN
            ON     WD_INVOICE_SN.DCCODE      = DM_DOCUMENT_D.DCCODE
            AND    WD_INVOICE_SN.STORERKEY   = DM_DOCUMENT_D.STORERKEY
            AND    WD_INVOICE_SN.DOCTYPE     = DM_DOCUMENT_D.DOCTYPE
            AND    WD_INVOICE_SN.WD_SLIPDT   = DM_DOCUMENT_D.DELIVERYDATE
            AND    WD_INVOICE_SN.WD_SLIPNO   = DM_DOCUMENT_D.DOCNO
            AND    WD_INVOICE_SN.WD_SLIPLINE = DM_DOCUMENT_D.DOCLINE
        <if test="stockid != null and stockid != ''">
            AND    WD_INVOICE_SN.STOCKID     = #{stockid}
        </if>
        JOIN   ST_SNINFO
            ON     ST_SNINFO.STORERKEY       = WD_INVOICE_SN.STORERKEY
            AND    ST_SNINFO.STOCKID         = WD_INVOICE_SN.STOCKID
        WHERE  1=1
            AND    DM_DOCUMENT_D.DCCODE      = #{dccode}
            AND    DM_DOCUMENT_D.DOCTYPE     = 'WD'
            AND    DM_DOCUMENT_D.DOCNO       = #{slipno}
        <if test="slipline != null and slipline != ''">
            AND    DM_DOCUMENT_D.DOCLINE     = #{slipline}
        </if>        
    </select>
  
    <select id="getFoSapIfYn" resultType="int">
        SELECT  /* [wdShipmentExDCService.sqlx][getFoSapIfYn][FO SAP I/F 대상여부 확인][sunho.kim][2025.06.30] */
               COUNT(1) AS CNT
        FROM   CM_CODE_STORER   CM_CODE
        WHERE  CM_CODE.STORERKEY = #{gStorerkey}
        AND    CM_CODE.DEL_YN    = 'N'
        AND    CM_CODE.CODELIST  = 'FO_SAP_IF_DC'
        AND    CM_CODE.BASECODE  = #{fixdccode}
    </select>
    
    <select id="getStockCntForExdc" resultType="WdShipmentExDCResDto">
        WITH TARGET AS (   /* [wdShipmentExDCService.sqlx][getStockCntForExdc][비정량상품 box수량 유무 확인][sunho.kim][2025.06.30] */
            SELECT  WD_TASK.DCCODE
                  , WD_TASK.STORERKEY
                  , WD_TASK.ORGANIZE
                  , WD_TASK.AREA
                  , WD_TASK.SKU
                  , WD_TASK.LOC
                  , WD_TASK.LOT
                  , WD_TASK.STOCKID
                  , WD_TASK.STOCKGRADE
            FROM   WD_TASK 
            WHERE      WD_TASK.STORERKEY = #{gStorerkey}
                AND    WD_TASK.DCCODE    = #{dccode}
                AND    WD_TASK.DOCNO     = #{slipno}
            <if test="slipline != null and slipline != ''">
                AND    WD_TASK.DOCLINE   = #{slipline}
            </if>
                AND    EXISTS (SELECT 1
                           FROM   MS_SKU
                           WHERE  MS_SKU.STORERKEY = WD_TASK.STORERKEY
                           AND    MS_SKU.SKU       = WD_TASK.SKU
                           AND    MS_SKU.LINE01    = 'Y')          
        )
        
        SELECT ST_STOCK.SKU                       AS SKU                /* 상품코드 */
              ,COUNT(1)                           AS CNT                /* 수량 */
              ,MAX(LEFT(TRIM(ST_SNINFO.POKEY),1)) AS PO_DIV_CD          /* 발주번호 구분 */
        FROM ST_STOCK LEFT OUTER 
        JOIN ST_SNINFO 
            ON   ST_STOCK.STOCKID = ST_SNINFO.STOCKID
            AND  ST_STOCK.SKU     = ST_SNINFO.SKU
        WHERE  (ST_STOCK.DCCODE
              , ST_STOCK.STORERKEY
              , ST_STOCK.ORGANIZE
              , ST_STOCK.AREA
              , ST_STOCK.SKU
              , ST_STOCK.LOC
              , ST_STOCK.LOT
              , ST_STOCK.STOCKID
              , ST_STOCK.STOCKGRADE) IN (SELECT DCCODE
                                              , STORERKEY
                                              , ORGANIZE
                                              , AREA
                                              , SKU
                                              , LOC
                                              , LOT
                                              , STOCKID
                                              , STOCKGRADE
                                         FROM   TARGET)
        AND    ST_STOCK.QTY > 0
        AND    ST_STOCK.BOXQTY = 0
        GROUP BY ST_STOCK.SKU
        HAVING COUNT(1) > 0
    </select>
    
    <select id="getCarrierPriceList" resultType="WdShipmentExDCPricePopupResDto">
        SELECT   /* [wdShipmentExDCService.sqlx][getCarrierPriceList][수송 운임단가 조회][sunho.kim][2025.11.13] */
            A.SERIALKEY      AS ROUTE_ID                /* 노선 아이디 */
          , A.ROUTE_NM       AS ROUTE_NM                /* 노선명 */
          , B.SERIALKEY      AS TCR_SERIALKEY           /* 운송비일련번호 */
          , B.COURIER        AS COURIER                 /* 운송사 */
          , C.DESCRIPTION    AS COURIER_NM              /* 운송사명 */
          , B.TON            AS TON                     /* 톤급 */
          , CD1.BASEDESCR    AS TON_NM                  /* 톤급명 */
          , B.STORAGETYPE    AS STORAGETYPE             /* 저장조건 */
          , CD2.BASEDESCR    AS STORAGETYPE_NM          /* 저장조건명 */
          , B.PRICE          AS PRICE                   /* 단가 */
          , 0                AS CARCNT                  /* 차량대수 */
          , 0                AS SHIP_FEE                /* 운송료 */
          , 0                AS ADD_FEE                 /* 추가비용 */
        FROM TM_CARRIER_ROUTE  A

        INNER JOIN TM_CARRIER_PRICE B
           ON B.ROUTE_SERIALKEY = A.SERIALKEY
           
        LEFT OUTER JOIN (
               SELECT CARRIERKEY, MAX(DESCRIPTION) AS DESCRIPTION
               FROM MS_CARRIER 
               GROUP BY CARRIERKEY
           ) C
           ON C.CARRIERKEY = B.COURIER
           
        LEFT OUTER JOIN CM_CODE_STORER CD1
           ON CD1.STORERKEY = #{gStorerkey}
          AND CD1.CODELIST  = 'CARCAPACITY'
          AND CD1.BASECODE  = B.TON    
          
        LEFT OUTER JOIN CM_CODE_STORER CD2
           ON CD2.STORERKEY = #{gStorerkey}
          AND CD2.CODELIST  = 'TM_CARRIER_STORAGE'
          AND CD2.BASECODE  = B.STORAGETYPE  

        WHERE 1=1
          AND A.FROM_DCCODE   = #{dccode}
          AND A.FROM_ORGANIZE = #{organize}
          AND A.TO_DCCODE     = #{toCustkey}
          AND A.FROMDATE <![CDATA[<=]]> #{fromdt}
          AND A.TODATE   <![CDATA[>=]]> #{todt}
          AND B.FROMDATE <![CDATA[<=]]> #{fromdt}
          AND B.TODATE   <![CDATA[>=]]> #{todt}

        ORDER BY A.SERIALKEY, B.COURIER, B.TON
    </select>
    
    <select id="getCarrierPriceSN" resultType="Long">
        SELECT    /* [wdShipmentExDCService.sqlx][getCarrierPriceSN][그룹번호 채번][sunho.kim][2025.11.13] */
                SEQ_TM_EXDC_TRSP_COST_02.NEXTVAL AS TRANSACTION_SN
        FROM    DUAL
    </select>
    
    <select id="getExdcTrspCost" resultType="WdShipmentExDCPricePopupResDto">
        SELECT    /* [wdShipmentExDCService.sqlx][getCarrierPriceSN][외부창고운송비내역 조회][sunho.kim][2025.11.13] */
             A.SERIALKEY                AS SERIALKEY            /* 데이터번호 */
           , A.SERIALKEY_GROUP          AS SERIALKEY_GROUP      /* 그룹 데이터번호 */
           , A.TCR_SERIALKEY            AS TCR_SERIALKEY        /* 운송비일련번호(TM_CARRIER_PRICE-SERIALKEY) */
           , B.COURIER                  AS COURIER              /* 운송사 */
           , C.DESCRIPTION              AS COURIER_NM           /* 운송사명 */
           , B.TON                      AS TON                  /* 톤급 */
           , CD1.BASEDESCR              AS TON_NM               /* 톤급명 */
           , B.STORAGETYPE              AS STORAGETYPE          /* 저장조건 */
           , CD2.BASEDESCR              AS STORAGETYPE_NM       /* 저장조건명 */
           , A.CARCNT                   AS CARCNT               /* 차량대수 */
           , B.PRICE                    AS PRICE                /* 단가 */
           , A.SHIP_FEE                 AS SHIP_FEE             /* 운송료 */
           , A.ADD_FEE                  AS ADD_FEE              /* 추가비용 */
           , A.RMK                      AS RMK                  /* 비고 */
        FROM  TM_EXDC_TRSP_COST A

        LEFT OUTER JOIN TM_CARRIER_PRICE B
           ON B.SERIALKEY  = A.TCR_SERIALKEY
           
        LEFT OUTER JOIN (
               SELECT CARRIERKEY, MAX(DESCRIPTION) AS DESCRIPTION
               FROM MS_CARRIER 
               GROUP BY CARRIERKEY
           ) C
           ON C.CARRIERKEY = B.COURIER 
        
        LEFT OUTER JOIN CM_CODE_STORER CD1
           ON CD1.STORERKEY = #{gStorerkey}
          AND CD1.CODELIST  = 'CARCAPACITY'
          AND CD1.BASECODE  = B.TON
          
        LEFT OUTER JOIN CM_CODE_STORER CD2
           ON CD2.STORERKEY = #{gStorerkey}
          AND CD2.CODELIST  = 'TM_CARRIER_STORAGE'
          AND CD2.BASECODE  = B.STORAGETYPE  
          
        WHERE A.SERIALKEY_GROUP = #{serialkeyGroup}
        
        ORDER BY A.SERIALKEY 
    </select>
    
    <select id="getStockPrice" resultType="WdShipmentExDCStockpriceResDto">
        SELECT /* [wdShipmentExDCService.sqlx][getStockPrice][보관료 계산 조회][sunho.kim][2025.11.13] */ 
          FN_EXDCSTOCKPRICE ( 
              #{slipdt}
            , #{sku}
            , #{fixdccode}
            , #{gStorerkey}
            , #{organize}
            , NULL
            , #{stockid}
            ) AS stockprice
        FROM DUAL 
    </select>
    
    <update id="saveExdcTrspCost">
        MERGE INTO TM_EXDC_TRSP_COST /* [wdShipmentExDCService.sqlx][saveExdcTrspCost][외부창고운송비내역 MERGE 저장][sunho.kim][2025.11.13] */
             USING DUAL ON ( SERIALKEY   = #{serialkey}
                            )
             WHEN MATCHED THEN
                UPDATE SET TCR_SERIALKEY  = #{tcrSerialkey}
                          ,CARCNT         = #{carcnt}
                          ,SHIP_FEE       = #{shipFee}
                          ,ADD_FEE        = #{addFee}
                          ,RMK            = #{rmk}
                          ,EDITDATE       = SYSDATE
                          ,EDITWHO        = #{gUserId}
             WHEN NOT MATCHED THEN
             INSERT (SERIALKEY 
                    ,SERIALKEY_GROUP
                    ,TCR_SERIALKEY
                    ,CARCNT        
                    ,SHIP_FEE
                    ,ADD_FEE
                    ,RMK
                    ,ADDWHO 
                    ,EDITWHO
                    )
                VALUES
                    (LOGISONESVC.SEQ_TM_EXDC_TRSP_COST_01.NEXTVAL
                    ,#{transactionSn}
                    ,#{tcrSerialkey}
                    ,#{carcnt}
                    ,#{shipFee}
                    ,#{addFee}
                    ,#{rmk}
                    ,#{gUserId}
                    ,#{gUserId}
                    )
    </update>
    
    <delete id="deleteExdcTrspCost">
        DELETE  /* [wdShipmentExDCService.sqlx][deleteExdcTrspCost][외부창고운송비내역 삭제][sunho.kim][2025.11.13] */
        FROM TM_EXDC_TRSP_COST 
        WHERE SERIALKEY  = #{serialkey}
    
    </delete>
    
    <select id="updateCarrierPrice" statementType="CALLABLE" resultType="HMAP">
        <![CDATA[
        {CALL  /* [wdShipmentExDCService.sqlx][updateCarrierPrice][운송료 UPDATE][sunho.kim][2025.11.13] */
            DECLARE
                V_AFTER     DM_DOCUMENT_D%rowtype;
                O_SUCCESS   NUMBER         :=  1;      /* 성공여부(1이면 성공) */
                O_ERRCODE   NUMBER         :=  0;      /* 오류 코드 */
                O_ERRMSG    VARCHAR2(4000) := '';      /* 오류 메세지 */
            BEGIN
                FOR KEY_LIST IN (
                    SELECT
                            SERIALKEY, DELIVERYDATE
                    FROM    DM_DOCUMENT_D
                   WHERE    SERIALKEY    = #{serialkey}
                     AND    DELIVERYDATE = #{slipdt}
                )
                LOOP
                    BEGIN
                        SELECT  *
                        INTO    V_AFTER
                        FROM    DM_DOCUMENT_D
                        WHERE   SERIALKEY    =    KEY_LIST.SERIALKEY
                         AND    DELIVERYDATE =    KEY_LIST.DELIVERYDATE
                        ;
    
                       V_AFTER.REFERENCE03      := #{transactionSn};   /* 운송료 배부 연결키 */
                       V_AFTER.REFERENCE10      := #{carrierAmount};   /* 운송료 */
                       V_AFTER.EDITDATE         := SYSDATE;            /* 최종변경시간 */
                       V_AFTER.EDITWHO          := #{gUserId};         /* 최종변경자 */

                       TRDM_DOCUMENT_D.TR_UPDATE(
                                V_AFTER
                            ,   O_SUCCESS
                            ,   O_ERRCODE
                            ,   O_ERRMSG
                        );
    
                        EXIT    WHEN O_SUCCESS < 1;
    
                    END;
                END    LOOP;
    
                #{success, mode=OUT, jdbcType=INTEGER, javaType=int}    :=  O_SUCCESS;
                #{err, mode=OUT, jdbcType=INTEGER, javaType=int}        :=  O_ERRCODE;
                #{errmsg, mode=OUT, jdbcType=VARCHAR, javaType=String}  :=  O_ERRMSG;
    
            END
        }
        ]]>        
    </select>
    
    <select id="updateREFERENCE10" statementType="CALLABLE" resultType="HMAP">
        <![CDATA[
        {CALL  /* [wdShipmentExDCService.sqlx][updateREFERENCE10][운송료 UPDATE][sunho.kim][2025.11.13] */
            DECLARE
                V_AFTER     DM_DOCUMENT_D%rowtype;
                O_SUCCESS   NUMBER         :=  1;      /* 성공여부(1이면 성공) */
                O_ERRCODE   NUMBER         :=  0;      /* 오류 코드 */
                O_ERRMSG    VARCHAR2(4000) := '';      /* 오류 메세지 */
            BEGIN
                FOR KEY_LIST IN (
                    SELECT
                            SERIALKEY, DELIVERYDATE
                    FROM    DM_DOCUMENT_D
                   WHERE    SERIALKEY    = #{serialkey}
                     AND    DELIVERYDATE = #{slipdt}
                )
                LOOP
                    BEGIN
                        SELECT  *
                        INTO    V_AFTER
                        FROM    DM_DOCUMENT_D
                        WHERE   SERIALKEY    =    KEY_LIST.SERIALKEY
                         AND    DELIVERYDATE =    KEY_LIST.DELIVERYDATE
                        ;
    
                       V_AFTER.REFERENCE03      := CASE WHEN NVL(#{trandeliveryprice}, 0) > 0 THEN V_AFTER.REFERENCE03 ELSE NULL END;   /* 운송료 배부 연결키 */
                       V_AFTER.REFERENCE10      := NVL(#{trandeliveryprice}, 0);     /* 운송료 */
                       V_AFTER.EDITDATE         := SYSDATE;            /* 최종변경시간 */
                       V_AFTER.EDITWHO          := #{gUserId};         /* 최종변경자 */

                       TRDM_DOCUMENT_D.TR_UPDATE(
                                V_AFTER
                            ,   O_SUCCESS
                            ,   O_ERRCODE
                            ,   O_ERRMSG
                        );
    
                        EXIT    WHEN O_SUCCESS < 1;
    
                    END;
                END    LOOP;
    
                #{success, mode=OUT, jdbcType=INTEGER, javaType=int}    :=  O_SUCCESS;
                #{err, mode=OUT, jdbcType=INTEGER, javaType=int}        :=  O_ERRCODE;
                #{errmsg, mode=OUT, jdbcType=VARCHAR, javaType=String}  :=  O_ERRMSG;
    
            END
        }
        ]]>        
    </select>
    
    <select id="getScmUserList" resultType="WdShipmentExDCResDto">
        SELECT   /* [wdShipmentExDCService.sqlx][getScmUserList][SCM사용자목록 조회][sunho.kim][2025.06.30] */
               CM_CODE_STORER.BASECODE                                 AS USER_ID 
             , NVL(FRAMEONE_USER.USER_NM, CM_CODE_STORER.BASECODE)     AS USER_NM 
        FROM CM_CODE_STORER 
        LEFT OUTER JOIN FRAMEONE_USER
           ON FRAMEONE_USER.USER_ID   = CM_CODE_STORER.BASECODE
        WHERE CM_CODE_STORER.CODELIST = 'EXDC_MANAGE_USER'
          AND CM_CODE_STORER.DEL_YN   = 'N' 
    </select>
    
</mapper>