package cjfw.batch.shr0160.soap;

import jakarta.jws.Oneway;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "urn://shr.cjfreshway.co.kr/COMM", name = "SI_SHR0160_EAI_AO")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SISHR0160EAIAO {

    @WebMethod(operationName = "SI_SHR0160_EAI_AO", action = "http://sap.com/xi/WebService/soap1.1")
    @Oneway
    public void siSHR0160EAIAO(

        @WebParam(partName = "MT_SHR0160_EAI", name = "MT_SHR0160_EAI", targetNamespace = "urn://shr.cjfreshway.co.kr/COMM")
        DTSHR0160EAI mtSHR0160EAI
    );
}
