package cjfw.batch.shr0160.soap;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebServiceClient(name = "SI_SHR0160_EAI_AOService",
                  wsdlLocation = "wsdl/SI_SHR0160_EAI_AOService.wsdl",
                  targetNamespace = "urn://shr.cjfreshway.co.kr/COMM")
public class SISHR0160EAIAOService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn://shr.cjfreshway.co.kr/COMM", "SI_SHR0160_EAI_AOService");
    public final static QName HTTPSPort = new QName("urn://shr.cjfreshway.co.kr/COMM", "HTTPS_Port");
    public final static QName HTTPPort = new QName("urn://shr.cjfreshway.co.kr/COMM", "HTTP_Port");
    static {
        URL url = SISHR0160EAIAOService.class.getResource("wsdl/SI_SHR0160_EAI_AOService.wsdl");
        if (url == null) {
            url = SISHR0160EAIAOService.class.getClassLoader().getResource("wsdl/SI_SHR0160_EAI_AOService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(SISHR0160EAIAOService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "wsdl/SI_SHR0160_EAI_AOService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SISHR0160EAIAOService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SISHR0160EAIAOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SISHR0160EAIAOService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SISHR0160EAIAOService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SISHR0160EAIAOService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SISHR0160EAIAOService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SISHR0160EAIAO
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISHR0160EAIAO getHTTPSPort() {
        return super.getPort(HTTPSPort, SISHR0160EAIAO.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISHR0160EAIAO
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISHR0160EAIAO getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SISHR0160EAIAO.class, features);
    }


    /**
     *
     * @return
     *     returns SISHR0160EAIAO
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISHR0160EAIAO getHTTPPort() {
        return super.getPort(HTTPPort, SISHR0160EAIAO.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISHR0160EAIAO
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISHR0160EAIAO getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SISHR0160EAIAO.class, features);
    }

}
