package cjfw.wms.webservice.scm0570;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

import cjfw.wms.webservice.scm0570.SISCM0570SCMSOService;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "SI_SCM0570_SCM_SOService"
                , targetNamespace = "urn://scm.cjfreshway.co.kr/TCS"
                , wsdlLocation = "wsdl/SI_SCM0570_SCM_SOService.wsdl")
public class SISCM0570SCMSOService
    extends Service
{
    
    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn://scm.cjfreshway.co.kr/TCS", "SI_SCM0570_SCM_SOService");
    public final static QName HTTPSPort = new QName("urn://scm.cjfreshway.co.kr/TCS", "HTTPS_Port");
    public final static QName HTTPPort = new QName("urn://scm.cjfreshway.co.kr/TCS", "HTTP_Port");
    static {
        URL url = SISCM0570SCMSOService.class.getResource("wsdl/SI_SCM0570_SCM_SOService.wsdl");
        if (url == null) {
            url = SISCM0570SCMSOService.class.getClassLoader().getResource("wsdl/SI_SCM0570_SCM_SOService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(SISCM0570SCMSOService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "wsdl/SI_SCM0570_SCM_SOService.wsdl");
        }
        WSDL_LOCATION = url;
    }
    
    public SISCM0570SCMSOService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SISCM0570SCMSOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SISCM0570SCMSOService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SISCM0570SCMSOService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SISCM0570SCMSOService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SISCM0570SCMSOService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

//    private final static URL SISCM0570SCMSOSERVICE_WSDL_LOCATION;
//    private final static WebServiceException SISCM0570SCMSOSERVICE_EXCEPTION;
//    private final static QName SISCM0570SCMSOSERVICE_QNAME = new QName("urn://scm.cjfreshway.co.kr/TCS", "SI_SCM0570_SCM_SOService");
//
//    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("file:/C:/ADEV/workspace/api-lib/jaxws-ri/bin/SI_SCM0570_SCM_SOService.wsdl");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
//        SISCM0570SCMSOSERVICE_WSDL_LOCATION = url;
//        SISCM0570SCMSOSERVICE_EXCEPTION = e;
//    }
//
//    public SISCM0570SCMSOService() {
//        super(__getWsdlLocation(), SISCM0570SCMSOSERVICE_QNAME);
//    }
//
//    public SISCM0570SCMSOService(WebServiceFeature... features) {
//        super(__getWsdlLocation(), SISCM0570SCMSOSERVICE_QNAME, features);
//    }
//
//    public SISCM0570SCMSOService(URL wsdlLocation) {
//        super(wsdlLocation, SISCM0570SCMSOSERVICE_QNAME);
//    }
//
//    public SISCM0570SCMSOService(URL wsdlLocation, WebServiceFeature... features) {
//        super(wsdlLocation, SISCM0570SCMSOSERVICE_QNAME, features);
//    }
//
//    public SISCM0570SCMSOService(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public SISCM0570SCMSOService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
//        super(wsdlLocation, serviceName, features);
//    }
//
//    /**
//     * 
//     * @return
//     *     returns SISCM0570SCMSO
//     */
//    @WebEndpoint(name = "HTTP_Port")
//    public SISCM0570SCMSO getHTTPPort() {
//        return super.getPort(new QName("urn://scm.cjfreshway.co.kr/TCS", "HTTP_Port"), SISCM0570SCMSO.class);
//    }
//
//    /**
//     * 
//     * @param features
//     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns SISCM0570SCMSO
//     */
//    @WebEndpoint(name = "HTTP_Port")
//    public SISCM0570SCMSO getHTTPPort(WebServiceFeature... features) {
//        return super.getPort(new QName("urn://scm.cjfreshway.co.kr/TCS", "HTTP_Port"), SISCM0570SCMSO.class, features);
//    }
//
//    /**
//     * 
//     * @return
//     *     returns SISCM0570SCMSO
//     */
//    @WebEndpoint(name = "HTTPS_Port")
//    public SISCM0570SCMSO getHTTPSPort() {
//        return super.getPort(new QName("urn://scm.cjfreshway.co.kr/TCS", "HTTPS_Port"), SISCM0570SCMSO.class);
//    }
//
//    /**
//     * 
//     * @param features
//     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
//     * @return
//     *     returns SISCM0570SCMSO
//     */
//    @WebEndpoint(name = "HTTPS_Port")
//    public SISCM0570SCMSO getHTTPSPort(WebServiceFeature... features) {
//        return super.getPort(new QName("urn://scm.cjfreshway.co.kr/TCS", "HTTPS_Port"), SISCM0570SCMSO.class, features);
//    }
//
//    private static URL __getWsdlLocation() {
//        if (SISCM0570SCMSOSERVICE_EXCEPTION!= null) {
//            throw SISCM0570SCMSOSERVICE_EXCEPTION;
//        }
//        return SISCM0570SCMSOSERVICE_WSDL_LOCATION;
//    }

}
