package cjfw.wms.webservice.scm0570;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SI_SCM0570_SCM_SO", targetNamespace = "urn://scm.cjfreshway.co.kr/TCS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SISCM0570SCMSO {


    /**
     * 
     * @param mtSCM0570SCM
     * @return
     *     returns com.example.wsclient.DTSCM0570SCMResponse
     */
    @WebMethod(operationName = "SI_SCM0570_SCM_SO", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_SCM0570_SCM_response", targetNamespace = "urn://scm.cjfreshway.co.kr/TCS", partName = "MT_SCM0570_SCM_response")
    public DTSCM0570SCMResponse siSCM0570SCMSO(
        @WebParam(name = "MT_SCM0570_SCM", targetNamespace = "urn://scm.cjfreshway.co.kr/TCS", partName = "MT_SCM0570_SCM")
        DTSCM0570SCM mtSCM0570SCM);

}
