package cjfw.wms.webservice.scm0560;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SI_SCM0560_SCM_SO", targetNamespace = "urn://scm.cjfreshway.co.kr/TCS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SISCM0560SCMSO {


    /**
     * 
     * @param mtSCM0560SCM
     * @return
     *     returns com.example.wsclient.DTSCM0560SCMResponse
     */
    @WebMethod(operationName = "SI_SCM0560_SCM_SO", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_SCM0560_SCM_response", targetNamespace = "urn://scm.cjfreshway.co.kr/TCS", partName = "MT_SCM0560_SCM_response")
    public DTSCM0560SCMResponse siSCM0560SCMSO(
        @WebParam(name = "MT_SCM0560_SCM", targetNamespace = "urn://scm.cjfreshway.co.kr/TCS", partName = "MT_SCM0560_SCM")
        DTSCM0560SCM mtSCM0560SCM);

}
