package cjfw.wms.st.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

/**
 * Copyright 2025. CJ OliveNetworks Co. all rights reserved.
 * @author : 공두경 (medstorm@cj.net) 
 * @date : 2025.07.16 
 * @description : ASRS 결과 DTO
 * @issues :<pre> 
 * ----------------------------------------------------------- 
 * DATE       AUTHOR                MAJOR_ISSUE 
 * ----------------------------------------------------------- 
 * 2025.07.16 공두경 (medstorm@cj.net)  생성 </pre>
 */
@Data
@Schema(description = "ASRS 결과")
public class StLocMoveRPResTab2Dto {
	@Schema(description = "요청번호", example = "REQ001")
    private String docno; // AS DOCNO -> docno (언더바 없으므로 소문자)
    @Schema(description = "회사", example = "COMPANY_KEY")
    private String storerkey; // AS STORERKEY -> storerkey (언더바 없으므로 소문자)
    @Schema(description = "상품코드", example = "SKU456")
    private String sku; // AS SKU -> sku (언더바 없으므로 소문자)
    @Schema(description = "상품명칭", example = "상품명칭 예시")
    private String skuname; // AS SKUNAME -> skuname (언더바 없으므로 소문자)
    @Schema(description = "로케이션종류", example = "로케이션종류 예시")
    private String loccategory; // AS LOCCATEGORY -> loccategory (언더바 없으므로 소문자)
    @Schema(description = "FROM 로케이션", example = "FROM_LOC_002")
    private String fromloc; // AS FROMLOC -> fromloc (언더바 없으므로 소문자)
    @Schema(description = "TO 로케이션", example = "TO_LOC_002")
    private String toloc; // AS TOLOC -> toloc (언더바 없으므로 소문자)
    @Schema(description = "팔레트ID", example = "PLT001")
    private String pltid; // AS PLTID -> pltid (언더바 없으므로 소문자)
    @Schema(description = "BOX", example = "10")
    private String confirmqtyBox; // AS CONFIRMQTY_BOX -> confirmqtyBox (언더바 있으므로 카멜 케이스)
    @Schema(description = "EA", example = "5")
    private String confirmqtyEa; // AS CONFIRMQTY_EA -> confirmqtyEa (언더바 있으므로 카멜 케이스)
    @Schema(description = "처리소스키", example = "LINE001")
    private String docline; // AS DOCLINE -> docline (언더바 없으므로 소문자)
    @Schema(description = "진행상태", example = "처리완료")
    private String statusname; // AS STATUSNAME -> statusname (언더바 없으므로 소문자)
    @Schema(description = "ASRS지시여부", example = "Y")
    private String ifFlag; // AS IF_FLAG -> ifFlag (언더바 있으므로 카멜 케이스)
    @Schema(description = "ASRS처리결과", example = "성공")
    private String ifSendFile; // AS IF_SEND_FILE -> ifSendFile (언더바 있으므로 카멜 케이스)
    @Schema(description = "전송시간", example = "2025-07-16 13:00:00")
    private String ifDate; // AS IF_DATE -> ifDate (언더바 있으므로 카멜 케이스)
    @Schema(description = "등록일자", example = "2025-07-16 10:30:00")
    private String adddate; // AS ADDDATE -> adddate (언더바 없으므로 소문자)
    @Schema(description = "최종변경시간", example = "2025-07-16 13:25:00")
    private String editdate; // AS EDITDATE -> editdate (언더바 없으므로 소문자)
    @Schema(description = "생성인", example = "홍길동")
    private String addwho; // AS ADDWHO -> addwho (언더바 없으므로 소문자)
    @Schema(description = "최종변경자", example = "김철수")
    private String editwho; // AS EDITWHO -> editwho (언더바 없으므로 소문자)
    @Schema(description = "DCCODE", example = "DCCODE_EX")
    private String dccode; // AS DCCODE -> dccode (언더바 없으므로 소문자)
    @Schema(description = "DCNAME", example = "DCNAME_EX")
    private String dcname; // AS DCNAME -> dcname (언더바 없으므로 소문자)
    @Schema(description = "ORGANIZE", example = "ORGANIZE_EX")
    private String organize; // AS ORGANIZE -> organize (언더바 없으므로 소문자)
    @Schema(description = "STORAGETYPE", example = "STORAGETYPE_EX")
    private String storagetype; // AS STORAGETYPE -> storagetype (언더바 없으므로 소문자)
    @Schema(description = "STORAGETYPENAME", example = "STORAGETYPENAME_EX")
    private String storagetypename; // AS STORAGETYPENAME -> storagetypename (언더바 없으므로 소문자)
    @Schema(description = "UOM", example = "UOM_EX")
    private String uom; // AS UOM -> uom (언더바 없으므로 소문자)
    @Schema(description = "STOCKID", example = "STOCKID_EX")
    private String stockid; // AS STOCKID -> stockid (언더바 없으므로 소문자)
    @Schema(description = "OPENQTY", example = "100")
    private String openqty; // AS OPENQTY -> openqty (언더바 없으므로 소문자)
    @Schema(description = "CONFIRMQTY", example = "80")
    private String confirmqty; // AS CONFIRMQTY -> confirmqty (언더바 없으므로 소문자)
    @Schema(description = "QTYPERBOX", example = "QTYPERBOX_EX")
    private String qtyperbox; // AS QTYPERBOX -> qtyperbox (언더바 없으므로 소문자)
    @Schema(description = "OPENQTY_BOX", example = "OPENQTY_BOX_EX")
    private String openqtyBox; // AS OPENQTY_BOX -> openqtyBox (언더바 있으므로 카멜 케이스)
    @Schema(description = "OPENQTY_EA", example = "OPENQTY_EA_EX")
    private String openqtyEa; // AS OPENQTY_EA -> openqtyEa (언더바 있으므로 카멜 케이스)
    @Schema(description = "STOCKGRADE", example = "GOOD")
    private String stockgrade; // AS STOCKGRADE -> stockgrade (언더바 없으므로 소문자)
    @Schema(description = "STOCKGRADENAME", example = "STOCKGRADENAME_EX")
    private String stockgradename; // AS STOCKGRADENAME -> stockgradename (언더바 없으므로 소문자)
    @Schema(description = "LOTTABLE01", example = "20250716")
    private String lottable01; // AS LOTTABLE01 -> lottable01 (언더바 없으므로 소문자)
    @Schema(description = "DURATION_TERM", example = "30/90")
    private String durationTerm; // AS DURATION_TERM -> durationTerm (언더바 있으므로 카멜 케이스)
    @Schema(description = "PRINTYN", example = "Y")
    private String printyn; // AS PRINTYN -> printyn (언더바 없으므로 소문자)
    @Schema(description = "PRINTYNNAME", example = "PRINTYNNAME_EX")
    private String printynname; // AS PRINTYNNAME -> printynname (언더바 없으므로 소문자)
    @Schema(description = "STATUS", example = "COMPLETED")
    private String status; // AS STATUS -> status (언더바 없으므로 소문자)
    @Schema(description = "SUPPLNO", example = "SUPPLNO_EX")
    private String supplno; // AS SUPPLNO -> supplno (언더바 없으므로 소문자)
    @Schema(description = "SUPPLLINE", example = "SUPPLLINE_EX")
    private String supplline; // AS SUPPLLINE -> supplline (언더바 없으므로 소문자)
}
