<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<!--
 * Copyright 2025. CJ OliveNetworks Co. all rights reserved.
 *
 * @author      : KimDongHan (liop0123@cj.net)
 * @date        : 2025.08.21
 * @description : Admin > 모니터링 > 마감상태 관리 SQL
 * @issues      :
-->
<mapper namespace="ibCloseService">
	  
    <select id="getMasterList" resultType="cjfw.wms.ib.dto.IbCloseResDto">
    	SELECT /* [IbCloseService.sqlx][IbCloseService.getMasterList][Admin > 모니터링 > 마감상태 관리 조회][KimDongHan][2025-08-21] */
               IB_CLOSE.CLOSEDT                                AS CLOSEDT   /* 마감일자 */
             , IB_CLOSE.DCCODE                                 AS DCCODE    /* 물류센터코드 */
             , CM_DC.DCNAME                                    AS DCNAME    /* 물류센터명 */
             , IB_CLOSE.PLANT                                  AS PLANT     /* 플랜트 */
             , IB_CLOSE.DEL_YN                                 AS DEL_YN    /* 삭제여부 */
             , IB_CLOSE.SERIALKEY                              AS SERIALKEY /* 일련번호 */
             , 'Y'                                             AS SAP_YN    
		  FROM IB_CLOSE                                                    
		  JOIN CM_DC
		    ON CM_DC.DCCODE = IB_CLOSE.DCCODE
		 WHERE 1=1 
		<if test="dccode != null and dccode != ''">	 
		   AND IB_CLOSE.DCCODE         = #{dccode}
		</if>
		<if test="docdt != null and docdt != ''">	 
		   AND IB_CLOSE.CLOSEDT         = #{docdt}
		</if>
    </select>
    
    <update id="updateMaster">
    	UPDATE /* [IbCloseService.sqlx][IbCloseService.updateMaster][Admin > 모니터링 > 마감상태 관리 저장][KimDongHan][2025-08-21] */
    	       IB_CLOSE
    	   SET EDITWHO   = #{gUserId}
    	     , EDITDATE  = SYSDATE 
    	     , DEL_YN    = #{delYn}
		 WHERE SERIALKEY = #{serialkey}
	</update> 
    
</mapper>