<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="kpEXstorageMonitoringService">

     <select id="getDataHeaderList" resultType="kpEXstorageMonitoringMasterListResDto">
     <![CDATA[
		     SELECT /* [kpEXstorageMonitoringService.sqlx][getDataHeaderList][외부창고재고모티터링 헤더][ParkJinWoo][20250716] */
		         MAX(DM_DOCUMENT_D.MAPKEY_NO)                                 AS MAPKEYNO          /* MAPKEY */
		       , DM_EXDC_AUTOORD_CHECK.POKEY                                 AS POKEY             /* POKEY */
		       , DM_EXDC_AUTOORD_CHECK.POLINE                                AS POLINE            /* POLINE */
		       , MAX(DM_DOCUMENT_D.DELIVERYDATE)                             AS DELIVERYDATE      /* DELIVERYDATE */
		       , MAX(DM_DOCUMENT_D.DOCDT)                                    AS DOCDT             /* DOCDT */
		       , MAX(DM_EXDC_AUTOORD_CHECK.TMP_DPKEY)                        AS TMPDPKEY          /* TMP_DPKEY */
		       , MAX(RL.DPKEY)                                               AS DPKEY             /* DPKEY */
		       , MAX(DM_DOCUMENT_H.FROM_CUSTKEY)                             AS FROMCUSTKEY       /* FROM_CUSTKEY */
		       , MAX(DM_DOCUMENT_H.FROM_CUSTNAME)                            AS FROMCUSTNAME      /* FROM_CUSTNAME */
		       , MAX(DM_DOCUMENT_H.ORGANIZE)                                 AS ORGANIZE          /* ORGANIZE */
		       , MAX(FN_DESCR_ORGANIZE(DM_DOCUMENT_H.DCCODE, DM_DOCUMENT_H.ORGANIZE))
		                                                                    AS ORGANIZENAME      /* 창고명 */
		       , MAX(NVL(CD_MAPDIV.BASEDESCR        , DM_EXDC_AUTOORD_CHECK.MAP_DIV))
		                                                                    AS CONTRACTTYPE      /* 계약유형 */
		       , MAX(NVL(CD_MOVE.BASEDESCR          , DM_EXDC_AUTOORD_CHECK.MOVE_YN))
		                                                                    AS MOVEYN            /* 이동여부 */
		       , MAX(NVL(CD_TEMP.BASEDESCR          , DM_EXDC_AUTOORD_CHECK.MOVE_YN))
		                                                                    AS TEMPYN            /* 온도 / 중량 상태 */
		       , MAX(NVL(CD_STATUS.BASEDESCR        , DM_EXDC_AUTOORD_CHECK.SERIALINFO_CFM_YN))
		                                                                    AS STATUS            /* 상태 */
		       , CASE WHEN MAX(DM_EXDC_AUTOORD_CHECK.TMP_DP_STATUS) = '30' THEN UNISTR('처리예정')
		              WHEN MAX(DM_DOCUMENT_D.STATUS) = '90'                THEN UNISTR('처리완료')
		              WHEN MAX(DM_EXDC_AUTOORD_CHECK.TMP_DP_STATUS) = '90' THEN UNISTR('처리완료')
		         END                                                       AS TMPDPSTATUS        /* TMP_DP_STATUS */
		       , CASE WHEN MAX(DM_EXDC_AUTOORD_CHECK.SERIALINFO_CFM_YN) = '30' THEN UNISTR('생성')
		              WHEN MAX(RL.SO_STATUS) >= '30'                       THEN UNISTR('처리완료')
		              WHEN MAX(DM_EXDC_AUTOORD_CHECK.SERIALINFO_CFM_YN) = '40' THEN UNISTR('예정')
		              ELSE UNISTR('처리중')
		         END                                                       AS DPSTATUS           /* DP_STATUS */
		       , CASE WHEN MAX(AD.DP_STATUS) = '30'                        THEN UNISTR('처리예정')
		              WHEN MAX(AD.DP_STATUS) >= '60'                       THEN UNISTR('처리완료')
		              ELSE UNISTR('처리예정')
		         END                                                       AS ADDDPSTATUS        /* ADD_DP_STATUS */
		       , MAX(DECODE(DM_EXDC_AUTOORD_CHECK.ADD_YN,'Y','10',DM_EXDC_AUTOORD_CHECK.SERIALINFO_CFM_YN))
		                                                                    AS SERIALINFOCFMYN   /* SERIALINFO_CFM_YN */
		       , MAX(DM_EXDC_AUTOORD_CHECK.TMP_SO_DEL_YN)                  AS TMPSODELYN         /* TMP_SO_DEL_YN */
		       , MAX(DM_EXDC_AUTOORD_CHECK.ADD_YN)                         AS ADDYN              /* ADD_YN */
		       , MAX(ST_STOCK.QTY)                                         AS QTY                /* QTY */
		       , MAX(ST_STOCK.OPENQTY)                                     AS OPENQTY            /* OPENQTY */
		       , MAX(ST_STOCK.BOXQTY)                                      AS BOXQTY             /* BOXQTY */
		       , MAX(ST_STOCK.UOM)                                         AS UOM                /* UOM */
		       , MAX(MS_SKU.QTYPERBOX)                                     AS QTYPERBOX          /* QTYPERBOX */
		       , MAX(DM_EXDC_AUTOORD_CHECK.ISSUE_NO)                       AS ISSUENO            /* ISSUE_NO */
		       , MAX(DM_EXDC_AUTOORD_CHECK.TMP_SOKEY)                      AS SOKEY              /* SO_KEY */
		       , MAX(DM_EXDC_AUTOORD_CHECK.ADDWHO)                         AS ADDWHO             /* ADDWHO */
		       , MAX(EXDC_AUTO_SERIALINFO.ADDWHO)                          AS EDITWHO            /* EDITWHO */
		       , MAX((SELECT USER_NM
		                FROM FRAMEONE_USER
		               WHERE USER_ID = DM_EXDC_AUTOORD_CHECK.ADDWHO
		                  OR USER_NO = DM_EXDC_AUTOORD_CHECK.ADDWHO))      AS CREATEWHO          /* 최초생성자 */
		       , MAX((SELECT USER_NM
		                FROM FRAMEONE_USER
		               WHERE USER_ID = EXDC_AUTO_SERIALINFO.ADDWHO
		                  OR USER_NO = EXDC_AUTO_SERIALINFO.ADDWHO))       AS REGWHO             /* 등록자 */
		       , MAX(TO_CHAR(EXDC_AUTO_SERIALINFO.ADDDATE,'YYYY-MM-DD HH24:MI'))
		                                                                    AS REGDATE           /* 등록일시 */
		       , MAX(NVL((SELECT USER_NM
		                    FROM FRAMEONE_USER
		                   WHERE USER_ID = EXDC_AUTO_SERIALINFO.EDITWHO
		                      OR USER_NO = DM_DOCUMENT_D.EDITWHO),
		                 DM_DOCUMENT_D.EDITWHO))                           AS LASTWHO            /* 최종수정자 */
		       , MAX(TO_CHAR(DM_DOCUMENT_D.EDITDATE,'YYYY-MM-DD HH24:MI')) AS LASTDATE           /* 최종수정일시 */
		       , MAX(NVL(CD_ERROR.BASEDESCR , DM_EXDC_AUTOORD_CHECK.ERROR_CHECK))
		                                                                    AS ERRORSTATUS       /* 오류상태 */
		       , MAX(CASE WHEN DM_EXDC_AUTOORD_CHECK.TMP_SO_DEL_YN = 'Y' THEN 'red'
		                  ELSE 'black' END)                                AS FONTCOLOR          /* 글꼴색 */
		       , MAX(CASE WHEN DECODE(DM_EXDC_AUTOORD_CHECK.ADD_YN,'Y','10',
		                              NVL(DM_EXDC_AUTOORD_CHECK.SERIALINFO_CFM_YN,'40')) = '20' THEN 'gray'
		                  WHEN DECODE(DM_EXDC_AUTOORD_CHECK.ADD_YN,'Y','10',
		                              NVL(DM_EXDC_AUTOORD_CHECK.SERIALINFO_CFM_YN,'40')) = '40'
		                       AND TO_CHAR(EXDC_AUTO_SERIALINFO.ADDDATE,'YYYYMMDD') <
		                           TO_CHAR(SYSDATE,'YYYYMMDD')                               THEN 'pink'
		                  ELSE '' END)                                     AS BGCOLOR            /* 배경색 */
		       , MAX(CM_CODE.DATA1)                                        AS DATA1  
        FROM        DP_INPLAN
        JOIN        DM_DOCUMENT_D
              ON    DM_DOCUMENT_D.DCCODE     = DP_INPLAN.DCCODE
              AND   DM_DOCUMENT_D.STORERKEY  = DP_INPLAN.STORERKEY
              AND   DM_DOCUMENT_D.DOCDT      = DP_INPLAN.DOCDT
              AND   DM_DOCUMENT_D.DOCTYPE    = DP_INPLAN.DOCTYPE
              AND   DM_DOCUMENT_D.DOCNO      = DP_INPLAN.DOCNO
              AND   DM_DOCUMENT_D.DOCLINE    = DP_INPLAN.DOCLINE
              AND 	DM_DOCUMENT_D.DELIVERYDATE     = DP_INPLAN.DELIVERYDATE 
              AND   DM_DOCUMENT_D.DOCTYPE    = 'DP'
              AND   DM_DOCUMENT_D.DEL_YN     = 'N'
              AND   DM_DOCUMENT_D.CHANNEL    IN ('1','2','3')
        JOIN        MS_SKU
              ON    MS_SKU.STORERKEY         = DP_INPLAN.STORERKEY
              AND   MS_SKU.SKU               = DP_INPLAN.SKU
              AND   MS_SKU.DEL_YN            = 'N'
        JOIN        DM_DOCUMENT_H
              ON    DM_DOCUMENT_H.DCCODE     = DM_DOCUMENT_D.DCCODE
              AND   DM_DOCUMENT_H.STORERKEY  = DM_DOCUMENT_D.STORERKEY
              AND   DM_DOCUMENT_H.DOCDT      = DM_DOCUMENT_D.DOCDT
              AND   DM_DOCUMENT_H.DOCTYPE    = DM_DOCUMENT_D.DOCTYPE
              AND   DM_DOCUMENT_H.DOCNO      = DM_DOCUMENT_D.DOCNO
               AND DM_DOCUMENT_D.DELIVERYDATE = DM_DOCUMENT_H.DELIVERYDATE 
              AND   DM_DOCUMENT_H.DOCTYPE    = 'DP'
              AND   DM_DOCUMENT_H.DEL_YN     = 'N'
        JOIN        DM_EXDC_AUTOORD_CHECK
              ON    DM_EXDC_AUTOORD_CHECK.MAPKEY_NO   = DM_DOCUMENT_D.MAPKEY_NO
              AND   DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE = DM_DOCUMENT_D.MAPKEY_LINE
              AND   DM_EXDC_AUTOORD_CHECK.ISSUE_NO    = DM_DOCUMENT_D.ISSUE_NO
              AND   DM_EXDC_AUTOORD_CHECK.REAL_YN     = DM_DOCUMENT_D.REAL_YN
              AND   DM_EXDC_AUTOORD_CHECK.ADD_YN      = DM_DOCUMENT_D.ADD_YN
        LEFT JOIN   ST_STOCK
              ON    ST_STOCK.DCCODE     = DP_INPLAN.DCCODE
              AND   ST_STOCK.ORGANIZE   = DP_INPLAN.ORGANIZE
              AND   ST_STOCK.SKU        = DP_INPLAN.SKU
              AND   ST_STOCK.STOCKID    = DP_INPLAN.STOCKID
        LEFT JOIN   DP_INVOICE_SN
              ON    DP_INVOICE_SN.DCCODE    = DP_INPLAN.DCCODE
              AND   DP_INVOICE_SN.STORERKEY = DP_INPLAN.STORERKEY
              AND   DP_INVOICE_SN.DOCTYPE   = DP_INPLAN.DOCTYPE
              AND   DP_INVOICE_SN.SLIPNO    = DP_INPLAN.SLIPNO
              AND   DP_INVOICE_SN.SLIPDT    = DP_INPLAN.SLIPDT
              AND   DP_INVOICE_SN.SLIPLINE  = DP_INPLAN.SLIPLINE
              AND   DP_INVOICE_SN.SKU       = DP_INPLAN.SKU
              AND   DP_INVOICE_SN.STOCKID   = DP_INPLAN.STOCKID
        LEFT JOIN   ST_SNINFO
              ON    ST_SNINFO.STORERKEY    = DP_INVOICE_SN.STORERKEY
              AND   ST_SNINFO.SKU          = DP_INVOICE_SN.SKU
              AND   ST_SNINFO.SERIALNO     = DP_INVOICE_SN.SERIALNO
              AND   ST_SNINFO.STOCKID      = DP_INVOICE_SN.STOCKID
              AND   ST_SNINFO.POKEY        = DM_DOCUMENT_D.POKEY
        LEFT JOIN   EXDC_AUTO_SERIALINFO
              ON    DM_EXDC_AUTOORD_CHECK.MAPKEY_NO   = EXDC_AUTO_SERIALINFO.MAPKEY_NO
              AND   DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE = EXDC_AUTO_SERIALINFO.MAPKEY_LINE
        LEFT JOIN   DM_EXDC_AUTOORD_CHECK AD
              ON    DM_EXDC_AUTOORD_CHECK.MAPKEY_NO   = AD.MAPKEY_NO
              AND   DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE = AD.MAPKEY_LINE
              AND   AD.ADD_YN = 'Y'
        LEFT JOIN   DM_EXDC_AUTOORD_CHECK RL
              ON    DM_EXDC_AUTOORD_CHECK.MAPKEY_NO   = RL.MAPKEY_NO
              AND   DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE = RL.MAPKEY_LINE
              AND   RL.REAL_YN = 'R'
        LEFT JOIN   CM_CODE
              ON    CM_CODE.BASECODE = DM_EXDC_AUTOORD_CHECK.SERIALINFO_CFM_YN
              AND   CM_CODE.STORERKEY = 'FW00'
              AND   CM_CODE.CODELIST  = 'SERIAL_CFM_STATUS'
                /* ----- CODE JOIN ----- */
		LEFT JOIN CM_CODE_STORER CD_MAPDIV
		       ON CD_MAPDIV.STORERKEY = DM_DOCUMENT_D.STORERKEY
		      AND CD_MAPDIV.CODELIST  = 'MAP_DIV'
		      AND CD_MAPDIV.BASECODE  = DM_EXDC_AUTOORD_CHECK.MAP_DIV
		
		LEFT JOIN CM_CODE_STORER CD_MOVE
		       ON CD_MOVE.STORERKEY = DM_DOCUMENT_D.STORERKEY
		      AND CD_MOVE.CODELIST  = 'EXDC_MOVE'
		      AND CD_MOVE.BASECODE  = DM_EXDC_AUTOORD_CHECK.MOVE_YN
		
		LEFT JOIN CM_CODE_STORER CD_TEMP
		       ON CD_TEMP.STORERKEY = DM_DOCUMENT_D.STORERKEY
		      AND CD_TEMP.CODELIST  = 'TMEP_WEIGHT_STATUS'
		      AND CD_TEMP.BASECODE  = DM_EXDC_AUTOORD_CHECK.MOVE_YN
		
		LEFT JOIN CM_CODE_STORER CD_STATUS
		       ON CD_STATUS.STORERKEY = DM_DOCUMENT_D.STORERKEY
		      AND CD_STATUS.CODELIST  = 'SERIAL_CFM_STATUS'
		      AND CD_STATUS.BASECODE  = DM_EXDC_AUTOORD_CHECK.SERIALINFO_CFM_YN
		
		LEFT JOIN CM_CODE_STORER CD_ERROR
		       ON CD_ERROR.STORERKEY = DM_DOCUMENT_D.STORERKEY
		      AND CD_ERROR.CODELIST  = 'ERROR_CHECK'
		      AND CD_ERROR.BASECODE  = DM_EXDC_AUTOORD_CHECK.ERROR_CHECK
        WHERE DM_DOCUMENT_D.DCCODE      = #{gDccode}
          AND DM_DOCUMENT_D.STORERKEY   = #{gStorerkey}
          AND DM_EXDC_AUTOORD_CHECK.REAL_YN = 'T'
        
		          
        ]]>

        
        <if test="slipDtFrom != null and slipDtFrom != ''">
            AND DM_DOCUMENT_D.DELIVERYDATE <![CDATA[>=]]> #{slipDtFrom}
        </if>
        <if test="slipDtTo != null and slipDtTo != ''">
            AND DM_DOCUMENT_D.DELIVERYDATE <![CDATA[<=]]> #{slipDtTo}
        </if>



        <if test="organize != null and organize != ''">
            AND DM_DOCUMENT_H.ORGANIZE IN 
             (	
	             SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{organize} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>

        <if test="fromCustKey != null and fromCustKey != ''">
            AND DM_DOCUMENT_H.FROM_CUSTKEY IN 
    			(	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{fromCustKey} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>

        <if test="sku != null and sku != ''">
            AND MS_SKU.SKU IN 
            (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{sku} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>

        <!-- 이하 개별 파라미터 조건 -->
        <if test="mapkeyno != null and mapkeyno != ''">
            AND DM_EXDC_AUTOORD_CHECK.MAPKEY_NO IN 
             (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{mapkeyno} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>
        <if test="pokey != null and pokey != ''">
            AND DM_EXDC_AUTOORD_CHECK.POKEY IN 
             (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{pokey} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>
        <if test="docno != null and docno != ''">
            AND (
				      RL.SOKEY IN (
				        SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
				          FROM (SELECT #{docno} AS VAL FROM DUAL) A
				        CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				      )
				   OR DM_EXDC_AUTOORD_CHECK.TMP_SOKEY IN (
				        SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
				          FROM (SELECT #{docno} AS VAL FROM DUAL) A
				        CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				      )
				)
        </if> 
        <if test="stockId != null and stockId != ''">
            AND ST_SNINFO.STOCKID IN 
            (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{stockId} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>
        <if test="blNo != null and blNo != ''">
            AND ST_SNINFO.CONVSERIALNO IN 
            (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{blNo} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>
        <if test="serialNo != null and serialNo != ''">
            AND ST_SNINFO.SERIALNO IN 
             (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{serialNo} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>
        <if test="contractCustKey != null and contractCustKey != ''">
            AND ST_SNINFO.CONTRACTCUSTKEY IN 
              (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{contractCustKey} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>
        <if test="contractType != null and contractType != ''">
            AND ST_SNINFO.CONTRACTTYPE = #{contractType}
        </if>
        <if test="moveYn != null and moveYn != ''">
            AND DM_EXDC_AUTOORD_CHECK.MOVE_YN = #{moveYn}
        </if>
        <if test="exdcOrderType != null and exdcOrderType != ''">
            AND DM_EXDC_AUTOORD_CHECK.EXDC_ORDERTYPE = #{exdcOrderType}
        </if>
        <if test="serialinfoCfmYn != null and serialinfoCfmYn != ''">
            AND DM_EXDC_AUTOORD_CHECK.SERIALINFO_CFM_YN = #{serialinfoCfmYn}
        </if>
        <if test="tempYn != null and tempYn != ''">
            AND DM_EXDC_AUTOORD_CHECK.TEMP_YN = #{tempYn}
        </if>
        <if test="addYn != null and addYn != ''">
            AND DM_EXDC_AUTOORD_CHECK.ADD_YN = #{addYn}
        </if>
        <if test="realYn != null and realYn != ''">
            AND DM_EXDC_AUTOORD_CHECK.REAL_YN = #{realYn}
        </if>
        <if test="skul != null and skul != ''">
            AND SUBSTR(MS_SKU.SKUGROUP,0,2) = #{skul}
        </if>

        <![CDATA[
        GROUP BY DM_EXDC_AUTOORD_CHECK.MAPKEY_NO,
                 DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE,
                 DM_EXDC_AUTOORD_CHECK.ISSUE_NO,
                 DM_EXDC_AUTOORD_CHECK.POKEY,
                 DM_EXDC_AUTOORD_CHECK.POLINE
        ORDER BY data1
        ]]>
    </select>    
    
    <select id="getDataLocalHeaderList" resultType="kpEXstorageMonitoringLocalMasterListResDto">
	   SELECT /* [kpEXstorageMonitoringService.sqlx][getDataLocalHeaderList][외부창고재고모티터링 로컬 헤더][ParkJinWoo][20250716] */
	         FF.MAPKEY_NO                                   AS MAPKEYNO          /* MAPKEY */
	       , MAX(FF.ISSUE_NO)                               AS ISSUENO           /* ISSUE_NO */
	       , MAX(FF.DPWEIGHT)                               AS DPWEIGHT          /* 입고중량 */
	       , MAX(FF.DPBOXQTY)                               AS DPBOXQTY          /* 입고박스수 */
	       , SUM(FF.WDQTY)                                  AS WDQTY             /* 출고중량 */
	       , SUM(FF.WDBOXQTY)                               AS WDBOXQTY          /* 출고박스수 */
	       , SUM(FF.OPENQTY)                                AS QTY               /* 현재고수량 */
	       , SUM(FF.BOXQTY)                                 AS BOXQTY            /* 현재고 박스수량 */
	       , ( SUM(FF.DPWEIGHT)  - SUM(FF.WDQTY)  - SUM(FF.OPENQTY) )  AS ADQTY      /* 조정중량 */
	       , ( SUM(FF.DPBOXQTY) - SUM(FF.WDBOXQTY) - SUM(FF.BOXQTY) ) AS ADBOXQTY   /* 조정박스수 */
	       , MAX(A.POKEY)                                   AS POKEY             /* POKEY */
	       , MAX(A.POLINE)                                  AS POLINE            /* POLINE */
	       , MAX(B.DPKEY)                                   AS DPKEY             /* 입고 DPKEY */
	       , MAX(CASE WHEN A.CONFIRM_YN = '10' THEN '10'
	                  WHEN A.CONFIRM_YN = '20' THEN '20'
	                  ELSE '40' END)                        AS SERIALINFOCFMYN   /* SERIALINFO_CFM_YN */
	       , MAX(A.DELIVERYDATE)                            AS DELIVERYDATE      /* DELIVERYDATE */
	       , MAX(TO_CHAR(A.ADDDATE,'YYYYMMDD'))             AS DOCDT             /* DOCDT */
	       , MAX(A.CUSTKEY)                                 AS FROMCUSTKEY       /* FROM_CUSTKEY */
	       , MAX(MS_CUST.DESCRIPTION)                       AS FROMCUSTNAME      /* FROM_CUSTNAME */
	       , MAX('2170-'||A.ORGANIZE)                       AS ORGANIZE          /* ORGANIZE */
	       , MAX(( SELECT DESCRIPTION
	                 FROM CM_DCXORGANIZE
	                WHERE ORGANIZE = '2170-'||A.ORGANIZE )) AS ORGANIZENAME      /* ORGANIZENAME */
	       , MAX(A.BASEUOM)                                 AS BASEUOM           /* BASEUOM */
	       , MAX(A.BASEUOM)                                 AS SALESUOM          /* SALESUOM */
	       , MAX(MS_SKU.QTYPERBOX)                          AS QTYPERBOX         /* QTYPERBOX */
	       , MAX(A.CONVSERIALNO)                            AS CONVSERIALNO      /* CONVSERIALNO */
	       , MAX(A.SKU)                                     AS SKU               /* SKU */
	       , MAX(NVL(( SELECT B.UOM
	                     FROM ST_STOCK B
	                    WHERE B.STOCKID = A.ISSUE_NO ),0))  AS UOM               /* UOM */
	       , MAX(A.ADDWHO)                                  AS ADDWHO            /* ADDWHO */
	       , MAX(A.ADDWHO)                                  AS EDITWHO           /* EDITWHO */
	       , MAX(( SELECT USER_NM
	                 FROM FRAMEONE_USER
	                WHERE USER_ID = A.ADDWHO
	                   OR USER_NO = A.ADDWHO ))             AS CREATEWHO         /* 최초생성자 */
	       , MAX(( SELECT USER_NM
	                 FROM FRAMEONE_USER
	                WHERE USER_ID = A.REQ_WHO
	                   OR USER_NO = A.REQ_WHO ))            AS REGWHO            /* 등록자 */
	       , MAX(TO_CHAR(A.ADDDATE,'YYYY-MM-DD HH24:MI'))   AS REGDATE           /* 등록일시 */
	       , MAX(( SELECT USER_NM
	                 FROM FRAMEONE_USER
	                WHERE USER_ID = A.EDITWHO
	                   OR USER_NO = A.EDITWHO ))            AS LASTWHO           /* 최종수정자 */
	       , MAX(TO_CHAR(A.EDITDATE,'YYYY-MM-DD HH24:MI'))  AS LASTDATE          /* 최종수정일시 */
	       , 'black'                                        AS FONTCOLOR         /* 글꼴색 */
	       , CASE WHEN MAX(A.CONFIRM_YN) = '20' THEN 'gray'
	              WHEN NVL(MAX(A.CONFIRM_YN),'') = '' AND
	                   TO_CHAR(MAX(A.ADDDATE),'YYYYMMDD')<![CDATA[ < ]]>TO_CHAR(SYSDATE,'YYYYMMDD')
	                   THEN 'pink'
	              ELSE ''
	         END                                           AS BGCOLOR            /* 배경색 */
	       , MAX(NVL(CD_STATUS.BASEDESCR , NVL(A.CONFIRM_YN,'40')))              AS STATUS        /* 처리상태 */
	       , MAX(NVL(CD_MAPDIV.BASEDESCR , A.MAP_DIV))                            AS CONTRACTTYPE  /* 거래유형 */
	       , MAX(NVL(CD_MOVE.BASEDESCR   , A.MOVE_YN))                            AS MOVEYN        /* 이체여부 */
	       , MAX(NVL(CD_TEMP.BASEDESCR   , A.MOVE_YN))                            AS TEMPYN
	        FROM (
                /* ------------------- 중첩 서브쿼리 FF ------------------- */
                SELECT  A.MAPKEY_NO
                      , A.ISSUE_NO
                      , MAX(PO.CONFIRMQTY)      AS DPWEIGHT   /* 입고중량 */
                      , MAX(PO.ETCQTY2)         AS DPBOXQTY   /* 입고박스수 */
                      , SUM(SO.CONFIRMQTY)      AS WDQTY      /* 출고중량 */
                      , SUM(SO.ETCQTY2)         AS WDBOXQTY   /* 출고박스수 */
                      , MAX(ST_STOCK.OPENQTY)   AS OPENQTY    /* 현재고수량 */
                      , MAX(ST_STOCK.BOXQTY)    AS BOXQTY     /* 현재고 박스수량 */
                      , SUM(ADSO.CONFIRMQTY)    AS RTSO       /* 반품SO */
                      , SUM(ADDSO.CONFIRMQTY)   AS ADDSO      /* 추가SO */
                      , MAX(ADSO.CONFIRMQTY)    AS ADSOCONFIRMQTY
                      , MAX(ADDSO.CONFIRMQTY)   AS ADDSOCONFIRMQTY
                FROM EXDC_SCM_CFM_LOCAL A
                      /* 입고 DP */
                      LEFT JOIN DM_DOCUMENT_D PO
                        ON A.POKEY      = PO.POKEY
                       AND A.POLINE     = PO.POLINE
                       AND A.ISSUE_NO   = PO.ISSUE_NO
                       AND A.MAPKEY_NO  = PO.MAPKEY_NO
                       AND A.SKU        = PO.SKU
                       AND A.DELIVERYDATE = PO.DELIVERYDATE
                       AND PO.DOCTYPE   = 'DP'
                      /* 출고 WD(정상) */
                      LEFT JOIN DM_DOCUMENT_D SO
                        ON A.SKU        = SO.SKU
                       AND A.MAPKEY_NO  = SO.MAPKEY_NO
                       AND A.ISSUE_NO   = SO.ISSUE_NO
                       AND A.DELIVERYDATE = SO.DELIVERYDATE
                       AND SO.DOCTYPE   = 'WD'
                       AND SO.ADD_YN    = 'N'
                      /* 추가 조건·재고 테이블 등 */
                      LEFT JOIN DM_EXDC_AUTOORD_CHECK B
                        ON A.MAPKEY_NO  = B.MAPKEY_NO
                       AND A.MAPKEY_LINE= B.MAPKEY_LINE
                       AND A.ISSUE_NO   = B.ISSUE_NO
                      /* 반품 SO (RT) */
                      LEFT JOIN DM_DOCUMENT_D ADSO
                        ON SO.MAPKEY_NO = ADSO.MAPKEY_NO
                       AND SO.ISSUE_NO  = ADSO.ISSUE_NO
                       AND SO.MAPKEY_LINE= ADSO.MAPKEY_LINE
                       AND SO.DELIVERYDATE = ADSO.DELIVERYDATE
                       AND ADSO.ADD_YN  = 'Y'
                       AND ADSO.DOCTYPE = 'RT'
                      /* 추가 SO (WD) */
                      LEFT JOIN DM_DOCUMENT_D ADDSO
                        ON SO.MAPKEY_NO = ADDSO.MAPKEY_NO
                       AND SO.ISSUE_NO  = ADDSO.ISSUE_NO
                       AND SO.MAPKEY_LINE= ADDSO.MAPKEY_LINE
                       AND SO.DELIVERYDATE = ADDSO.DELIVERYDATE
                       AND ADDSO.ADD_YN = 'Y'
                       AND ADDSO.DOCTYPE= 'WD'
                      /* 재고 */
                      LEFT JOIN ST_STOCK
                        ON A.ISSUE_NO   = ST_STOCK.STOCKID
                       AND A.SKU        = ST_STOCK.SKU
                GROUP BY A.MAPKEY_NO, A.ISSUE_NO
             ) FF
        JOIN EXDC_SCM_CFM_LOCAL A
          ON FF.MAPKEY_NO = A.MAPKEY_NO
         AND FF.ISSUE_NO  = A.ISSUE_NO
        LEFT JOIN MS_CUST
          ON A.STORERKEY  = MS_CUST.STORERKEY
         AND A.CUSTKEY    = MS_CUST.CUSTKEY
        JOIN MS_SKU
          ON A.SKU        = MS_SKU.SKU
         AND A.STORERKEY  = MS_SKU.STORERKEY
        LEFT JOIN DM_EXDC_AUTOORD_CHECK B
          ON A.MAPKEY_NO  = B.MAPKEY_NO
         AND A.MAPKEY_LINE= B.MAPKEY_LINE
         AND A.ISSUE_NO   = B.ISSUE_NO
         /* ----------- CODE LIST 변환 JOIN ----------- */
			LEFT JOIN CM_CODE_STORER CD_STATUS
			       ON CD_STATUS.STORERKEY = A.STORERKEY
			      AND CD_STATUS.CODELIST  = 'SERIAL_CFM_STATUS'
			      AND CD_STATUS.BASECODE  = NVL(A.CONFIRM_YN,'40')
			
			LEFT JOIN CM_CODE_STORER CD_MAPDIV
			       ON CD_MAPDIV.STORERKEY = A.STORERKEY
			      AND CD_MAPDIV.CODELIST  = 'MAP_DIV'
			      AND CD_MAPDIV.BASECODE  = A.MAP_DIV
			
			LEFT JOIN CM_CODE_STORER CD_MOVE
			       ON CD_MOVE.STORERKEY = A.STORERKEY
			      AND CD_MOVE.CODELIST  = 'EXDC_MOVE'
			      AND CD_MOVE.BASECODE  = A.MOVE_YN
			
			LEFT JOIN CM_CODE_STORER CD_TEMP
			       ON CD_TEMP.STORERKEY = A.STORERKEY
			      AND CD_TEMP.CODELIST  = 'TMEP_WEIGHT_STATUS'
			      AND CD_TEMP.BASECODE  = A.MOVE_YN												
        WHERE 1 = 1
       

         <if test="slipDtTo != null and slipDtTo != ''">
            AND A.DELIVERYDATE <![CDATA[ >=]]> #{slipDtFrom}
        </if>
        <if test="slipDtTo != null and slipDtTo != ''">
            AND A.DELIVERYDATE <![CDATA[<=]]> #{slipDtTo}
        </if>

        <!-- 다중(콤마) 파라미터는 FN_SPLIT_ARRAY 활용 -->
        <if test="pokey != null and pokey != ''">
            AND A.POKEY IN 
              (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{pokey} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>

        <if test="organize != null and organize != ''">
            AND '2170-'||A.ORGANIZE IN   (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{organize} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>

        <if test="fromCustKey != null and fromCustKey != ''">
            AND A.CUSTKEY IN  (	 
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{fromCustKey} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>

        <if test="sku != null and sku != ''">
            AND MS_SKU.SKU IN  (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{sku} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>

        <!-- 단건 파라미터 -->
        <if test="mapkeyno != null and mapkeyno != ''">
            AND A.MAPKEY_NO IN  (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{mapkeyno} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>

        <if test="docno != null and docno != ''">
            AND A.MAPKEY_NO IN (
                SELECT F.MAPKEY_NO
                  FROM DM_DOCUMENT_D F
                 WHERE F.DOCNO IN (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL 
					FROM (SELECT #{docno} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
            )
        </if>
        <if test="stockId != null and stockId != ''">
            AND A.ISSUE_NO IN
			(	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{stockId} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>
        <if test="blNo != null and blNo != ''">
            AND A.CONVSERIALNO IN (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{blNo} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>
        <if test="serialNo != null and serialNo != ''">
            AND A.SERIALNO IN (	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{serialNo} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>
        <!-- 
        <if test="contractCustKey != null and contractCustKey != ''">
            AND A.CONTRACTCUSTKEY IN 
		(	
    			SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL)) AS VAL
					FROM (SELECT #{contractCustKey} AS VAL FROM DUAL) A
						CONNECT BY INSTR(A.VAL, ',', 1, LEVEL - 1) > 0
				)
        </if>
        -->
       <!-- 
        <if test="contractType != null and contractType != ''">
            AND A.CONTRACTTYPE = #{contractType}
        </if>
         -->
        <if test="moveYn != null and moveYn != ''">
            AND A.MOVE_YN = #{moveYn}
        </if>
        <!-- 
        <if test="exdcOrderType != null and exdcOrderType != ''">
            AND A.EXDC_ORDERTYPE = #{exdcOrderType}
        </if>
         -->
        <if test="serialinfoCfmYn != null and serialinfoCfmYn != ''">
            AND A.CONFIRM_YN = #{serialinfoCfmYn}
        </if>
        <if test="tempYn != null and tempYn != ''">
            AND A.TEMP_YN = #{tempYn}
        </if>
        <if test="addYn != null and addYn != ''">
            AND A.ADD_YN = #{addYn}
        </if>
        <if test="realYn != null and realYn != ''">
            AND A.REAL_YN = #{realYn}
        </if>
        <if test="skul != null and skul != ''">
            AND SUBSTR(MS_SKU.SKUGROUP,0,2) = #{skul}
        </if>
        <if test="mapDiv != null and mapDiv != ''">
            AND A.MAP_DIV = #{mapDiv}
        </if>

      
        GROUP BY FF.MAPKEY_NO

        
    </select>    
    
    <select id="getDataTcsHeaderList" resultType="kpEXstorageMonitoringTCSMasterListResDto">
    	<![CDATA[
	    SELECT /* [kpEXstorageMonitoringService.sqlx][getDataTcsHeaderList][외부창고재고모티터링 Tcs 헤더][ParkJinWoo][20250716] */
	         A.MAPKEY_NO                               AS MAPKEYNO        /* MAPKEY */
	       , B.POKEY                                   AS POKEY           /* POKEY */
	       , B.POLINE                                  AS POLINE          /* POLINE */
	       , B.DELIVERYDATE                            AS DELIVERYDATE    /* DELIVERYDATE */
	       , B.DOCDT                                   AS DOCDT           /* DOCDT */
	       , B.DOCNO                                   AS DOCNO           /* DOCNO */
	       , C.FROM_CUSTKEY                            AS FROMCUSTKEY     /* FROM_CUSTKEY */
	       , C.FROM_CUSTNAME                           AS FROMCUSTNAME    /* FROM_CUSTNAME */
	       , B.ORGANIZE                                AS ORGANIZE        /* ORGANIZE */
	       , ( SELECT DESCRIPTION
	             FROM CM_DCXORGANIZE
	            WHERE ORGANIZE = B.ORGANIZE )          AS ORGANIZENAME    /* ORGANIZENAME */
	       , NVL(CD_MAPDIV.BASEDESCR , A.MAP_DIV)      AS CONTRACTTYPE    /* 거래유형 */
	       , NVL(CD_MOVE.BASEDESCR   , A.MOVE_YN)      AS MOVEYN          /* 이체여부 */
	       , NVL(CD_TEMP.BASEDESCR   , A.MOVE_YN)      AS TEMPYN          /* 가중량여부 */
	       , B.CONFIRMQTY                              AS DPWEIGHT        /* 입고중량 */
	       , B.QCQTY                                   AS DPBOXQTY        /* 입고박스수 */
	       , ST_STOCK.OPENQTY                          AS OPENQTY         /* 현재고 수량 */
	       , ST_STOCK.BOXQTY                           AS BOXQTY          /* 현재고 박스수 */
	       , NVL( ( SELECT USER_NM
	                  FROM FRAMEONE_USER
	                 WHERE USER_ID = B.ADDWHO
	                    OR USER_NO = B.ADDWHO ),
	              B.ADDWHO )                           AS CREATEWHO       /* 최초생성자 */
	       , 'black'                                   AS FONTCOLOR       /* 글꼴색 */
	       , ''                                        AS BGCOLOR         /* 배경색 */
	        FROM DM_EXDC_AUTOORD_CHECK A
	        JOIN DM_DOCUMENT_D B
	          ON A.DPKEY  = B.DOCNO
	         AND A.DPLINE = B.DOCLINE
	        JOIN DM_DOCUMENT_H C
	          ON C.DCCODE     = B.DCCODE
	         AND C.STORERKEY  = B.STORERKEY
	         AND C.DOCDT      = B.DOCDT
	         AND C.DOCTYPE    = B.DOCTYPE
	         AND C.DELIVERYDATE = B.DELIVERYDATE
	         AND C.DOCNO      = B.DOCNO
	        LEFT JOIN MS_SKU
	          ON B.STORERKEY  = MS_SKU.STORERKEY
	         AND B.SKU        = MS_SKU.SKU
	        LEFT JOIN ST_STOCK
	          ON ST_STOCK.SKU     = B.SKU
	         AND ST_STOCK.STOCKID = B.STOCKID
	       	LEFT JOIN CM_CODE_STORER CD_MAPDIV
			       ON CD_MAPDIV.STORERKEY = B.STORERKEY
			      AND CD_MAPDIV.CODELIST  = 'MAP_DIV'
			      AND CD_MAPDIV.BASECODE  = A.MAP_DIV          /* 거래유형 */  	
			
			LEFT JOIN CM_CODE_STORER CD_MOVE
			       ON CD_MOVE.STORERKEY = B.STORERKEY
			      AND CD_MOVE.CODELIST  = 'EXDC_MOVE'
			      AND CD_MOVE.BASECODE  = A.MOVE_YN            /* 이체여부 */
			
			LEFT JOIN CM_CODE_STORER CD_TEMP
			       ON CD_TEMP.STORERKEY = B.STORERKEY
			      AND CD_TEMP.CODELIST  = 'TMEP_WEIGHT_STATUS'
			      AND CD_TEMP.BASECODE  = A.MOVE_YN            /* 가중량여부 */
	        WHERE B.DOCTYPE   = 'DP'
	          AND B.DCCODE    = '2170'
	          AND A.MAP_DIV   = '40'
	          /* ----------- CODE LIST 변환 JOIN ----------- */
	
       	 ]]>

        <!-- 날짜 조건 -->
        <if test="slipDtFrom != null and slipDtFrom != ''">
            AND B.DELIVERYDATE <![CDATA[>=]]> #{slipDtFrom}
        </if>
        <if test="slipDtTo != null and slipDtTo != ''">
            AND B.DELIVERYDATE <![CDATA[<=]]> #{slipDtTo}
        </if>



        <if test="organize != null and organize != ''">
            AND B.ORGANIZE IN (
                SELECT TRIM(REGEXP_SUBSTR(val,'[^,]+',1,LEVEL)) AS val
                  FROM (SELECT #{organize} AS val FROM DUAL)
                 CONNECT BY INSTR(val, ',', 1, LEVEL - 1) > 0
            )
        </if>
<!-- 
        <if test="multiFromCustKey != null and multiFromCustKey != ''">
            AND B.FROM_CUSTKEY IN (
                SELECT TRIM(REGEXP_SUBSTR(val,'[^,]+',1,LEVEL)) AS val
                  FROM (SELECT #{multiFromCustKey} AS val FROM DUAL)
                 CONNECT BY INSTR(val, ',', 1, LEVEL - 1) > 0
            )
        </if>
 -->
        <if test="sku != null and sku != ''">
            AND B.SKU IN (
                SELECT TRIM(REGEXP_SUBSTR(val,'[^,]+',1,LEVEL)) AS val
                  FROM (SELECT #{sku} AS val FROM DUAL)
                 CONNECT BY INSTR(val, ',', 1, LEVEL - 1) > 0
            )
        </if>


        <if test="mapkeyno != null and mapkeyno != ''">
            AND A.MAPKEY_NO IN (
                SELECT TRIM(REGEXP_SUBSTR(val,'[^,]+',1,LEVEL)) AS val
                  FROM (SELECT #{mapkeyno} AS val FROM DUAL)
                 CONNECT BY INSTR(val, ',', 1, LEVEL - 1) > 0
            )
        </if>

        <if test="pokey != null and pokey != ''">
            AND B.POKEY IN (
                SELECT TRIM(REGEXP_SUBSTR(val,'[^,]+',1,LEVEL)) AS val
                  FROM (SELECT #{pokey} AS val FROM DUAL)
                 CONNECT BY INSTR(val, ',', 1, LEVEL - 1) > 0
            )
        </if>

        <if test="docno != null and docno != ''">
            AND A.MAPKEY_NO IN (
                SELECT F.MAPKEY_NO
                  FROM DM_DOCUMENT_D F
                 WHERE F.DOCNO IN (
                     SELECT TRIM(REGEXP_SUBSTR(val,'[^,]+',1,LEVEL)) AS val
                       FROM (SELECT #{docno} AS val FROM DUAL)
                      CONNECT BY INSTR(val, ',', 1, LEVEL - 1) > 0
                 )
            )
        </if>

        <if test="stockId != null and stockId != ''">
            AND A.ISSUE_NO IN (
                SELECT TRIM(REGEXP_SUBSTR(val,'[^,]+',1,LEVEL)) AS val
                  FROM (SELECT #{stockId} AS val FROM DUAL)
                 CONNECT BY INSTR(val, ',', 1, LEVEL - 1) > 0
            )
        </if>
<!-- 
        <if test="blNo != null and blNo != ''">
            AND B.CONVSERIALNO IN (
                SELECT TRIM(REGEXP_SUBSTR(val,'[^,]+',1,LEVEL)) AS val
                  FROM (SELECT #{blNo} AS val FROM DUAL)
                 CONNECT BY INSTR(val, ',', 1, LEVEL - 1) > 0
            )
        </if>
         -->
<!-- 
        <if test="serialNo != null and serialNo != ''">
            AND B.SERIALNO IN (
                SELECT TRIM(REGEXP_SUBSTR(val,'[^,]+',1,LEVEL)) AS val
                  FROM (SELECT #{serialNo} AS val FROM DUAL)
                 CONNECT BY INSTR(val, ',', 1, LEVEL - 1) > 0
            )
        </if>
 -->
        <if test="skul != null and skul != ''">
            AND SUBSTR(MS_SKU.SKUGROUP,0,2) = #{skul}
        </if>

        <if test="mapDiv != null and mapDiv != ''">
            AND A.MAP_DIV = #{mapDiv}
        </if>
    </select>    
    
      <select id="getDataDetailList" resultType="kpEXstorageMonitoringDetailListResDto">

        <![CDATA[
	        SELECT /* [kpEXstorageMonitoringService.sqlx][getDataDetailList][외부창고재고모티터링 상세][ParkJinWoo][20250716] */
	        	     DM_EXDC_AUTOORD_CHECK.MAPKEY_NO                            AS MAPKEYNO            /* 구매요청번호 */
		       , DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE                          AS MAPKEYLINE          /* 구매요청항번 */
		       , EXDC_AUTO_SERIALINFO.ISSUE_NO                              AS ISSUENO             /* 이슈번호 */
		
		       , MAX(DM_EXDC_AUTOORD_CHECK.POKEY)            AS POKEY                         /* 구매번호 */
		       , MAX(DM_EXDC_AUTOORD_CHECK.POLINE)           AS POLINE                        /* 구매라인 */
		       , MAX(AD.POKEY)                               AS ADDPOKEY                      /* 조정구매번호 */
		       , MAX(AD.POLINE)                              AS ADDPOLINE                     /* 조정구매라인 */
		
		       , MAX(DM_DOCUMENT_D.DELIVERYDATE)             AS DELIVERYDATE                  /* 납품일 */
		       , MAX(DM_DOCUMENT_D.DOCDT)                    AS DOCDT                         /* 문서일자 */
		
		       /* ─── 상품 정보 ───────────────────────────────────────────────── */
		       , MAX(DP_INPLAN.SKU)                          AS SKU                           /* 상품코드 */
		       , MAX(MS_SKU.DESCRIPTION)                     AS SKUNAME                       /* 상품명 */
		       , MAX( NVL(CD_STORAGETYPE.BASEDESCR , MS_SKU.STORAGETYPE) )
		                                                    AS STORAGETYPENAME               /* 저장조건 */
		
		       , MAX( '('||MS_SKU.PLACEOFORIGIN||')'||
		               ( SELECT BASEDESCR
		                   FROM CM_CODE
		                  WHERE STORERKEY = MS_SKU.STORERKEY
		                    AND CODELIST  = 'COUNTRY'
		                    AND BASECODE  = MS_SKU.PLACEOFORIGIN
		                    AND DEL_YN    = 'N' ) )         AS ORG                            /* 원산지 */
		
		      
		       , ( MAX(TMP_SN.ORDERQTY)   + MAX(TMP_SN.CANCELQTY) )        AS TMP_QTY          /* 임시수량 */
		       , ( MAX(TMP_SN.ETCQTY2)    + MAX(TMP_SN.ETCQTY1)    )       AS TMP_ETCQTY2      /* 임시박스 */
		
		     
		       , NVL( MAX(ADD_SN.ORDERQTY) , MAX(ADDWD_SN.ORDERQTY) )      AS ADD_ORDERQTY     /* 조정수량 */
		       , NVL( MAX(ADD_SN.ETCQTY1)  , MAX(ADDWD_SN.ETCQTY1)  )      AS ADD_BOXQTY       /* 조정박스 */
		
		     
		       , MAX(TMP_SN.SERIALNO)                          AS TMP_SERIALNO                 /* 임시이력 */
		       , MAX(TMP_SN.STOCKID)                           AS TMP_STOCKID                  /* 임시바코드 */
		       , MAX(NVL(TMP_SNINFO.LOTTABLE01,'STD'))         AS TMP_LOTTABLE01               /* 임시LOT */
		       , MAX( FN_LOTDURATION(DP_INPLAN.STORERKEY,
		                              MS_SKU.DURATIONTYPE,
		                              MS_SKU.DURATION,
		                              NVL(TMP_SNINFO.LOTTABLE01,'STD'),
		                              'N')||'/'||MS_SKU.DURATION )
		                                                    AS TMP_DURATION_TERM               /* 임시유통기한 */
		       , MAX(CASE
		               WHEN NVL(TMP_SNINFO.LOTTABLE01,'STD') = 'STD' THEN 'N'
		               WHEN MONTHS_BETWEEN(
		                      TO_DATE(NVL(TMP_SNINFO.LOTTABLE01,'STD'),'yyyy-mm-dd'),
		                      SYSDATE) > 3 THEN 'N'
		               ELSE 'Y'
		             END)                                   AS TMP_NEARDURATIONYN              /* 임박여부 */
		       , MAX(TMP_SNINFO.CONVSERIALNO)                AS TMP_CONVSERIALNO               /* 임시BL */
		
		       , NVL( MAX(ADD_SN.SERIALNO) ,       MAX(ADDWD_SN.SERIALNO) )  AS ADD_SERIALNO   /* 조정이력 */
		       , NVL( MAX(ADD_SN.STOCKID)  ,       MAX(ADDWD_SN.STOCKID)  )  AS ADD_STOCKID    /* 조정바코드 */
		       , MAX(CASE
		               WHEN NVL(ADD_SNINFO.LOTTABLE01,'STD') = 'STD' THEN 'N'
		               WHEN MONTHS_BETWEEN(
		                      TO_DATE(NVL(ADD_SNINFO.LOTTABLE01,'STD'),'yyyy-mm-dd'),
		                      SYSDATE) > 3 THEN 'N'
		               ELSE 'Y'
		             END)                                   AS ADD_NEARDURATIONYN              /* 임박여부 */
		       , NVL( MAX(ADD_SNINFO.CONVSERIALNO) , MAX(ST_SNINFO.CONVSERIALNO) )
		                                                    AS ADD_CONVSERIALNO                /* 조정BL */
		       , MAX(NVL(ADD_SNINFO.LOTTABLE01,'STD'))       AS ADD_LOTTABLE01                 /* 조정LOT */
		       , MAX( FN_LOTDURATION(DP_INPLAN.STORERKEY,
		                              MS_SKU.DURATIONTYPE,
		                              MS_SKU.DURATION,
		                              NVL(ADD_SNINFO.LOTTABLE01,'STD'),
		                              'N')||'/'||MS_SKU.DURATION )
		                                                    AS ADD_DURATION_TERM               /* 조정유통기한 */
		
		 
		       , MAX(ST_SNINFO.SERIALNO)                     AS SERIALNO                       /* 최종이력 */
		       , MAX(DP_INVOICE_SN.STOCKID)                  AS STOCKID                        /* 최종바코드 */
		       , MAX(ST_SNINFO.CONVSERIALNO)                 AS CONVSERIALNO                   /* BL번호 */
		       , MAX(CASE
		               WHEN NVL(ST_SNINFO.LOTTABLE01,'STD') = 'STD' THEN 'N'
		               WHEN MONTHS_BETWEEN(
		                      TO_DATE(NVL(ST_SNINFO.LOTTABLE01,'STD'),'yyyy-mm-dd'),
		                      SYSDATE) > 3 THEN 'N'
		               ELSE 'Y'
		             END)                                   AS NEARDURATIONYN
		       , MAX(NVL(ST_SNINFO.LOTTABLE01,'STD'))        AS LOTTABLE01
		       , MAX( FN_LOTDURATION(DP_INPLAN.STORERKEY,
		                              MS_SKU.DURATIONTYPE,
		                              MS_SKU.DURATION,
		                              NVL(ST_SNINFO.LOTTABLE01,'STD'),
		                              'N')||'/'||MS_SKU.DURATION )
		                                                    AS DURATION_TERM
		
		       , MAX(DP_INVOICE_SN.ORDERQTY)                 AS ORDERQTY
		       , MAX(DP_INVOICE_SN.ETCQTY1)                  AS ETCQTY
		       , MAX(DM_DOCUMENT_D.UOM)                      AS UOM
		       , MAX(MS_SKU.QTYPERBOX)                       AS QTYPERBOX
		
		       
		       , MAX( NVL(CD_MOVE_FW.BASEDESCR , DM_EXDC_AUTOORD_CHECK.MOVE_YN) )
		                                                    AS MOVE_YN                        /* 이체여부 */
		       , MAX( NVL(CD_TEMP_FW.BASEDESCR , DM_EXDC_AUTOORD_CHECK.TEMP_YN) )
		                                                    AS TEMP_YN                        /* 가중량여부 */
		
		       
		       , MAX(DM_DOCUMENT_H.TO_CUSTKEY)               AS FROM_CUSTKEY                  /* 고객코드 */
		       , MAX(DM_DOCUMENT_H.TO_CUSTNAME)              AS FROM_CUSTNAME                 /* 고객명 */
		       , MAX( NVL(CD_MAPDIV.BASEDESCR , DM_EXDC_AUTOORD_CHECK.MAP_DIV) )
		                                                    AS CONTRACTTYPE                  /* 거래유형 */
		
		       , MAX(DM_DOCUMENT_H.REFERENCE02)              AS PAYYMD                        /* 지급일 */
		       , MAX(EXDC_AUTO_SERIALINFO.RECEIVE_MEMO)      AS RECEIVE_MEMO                  /* 영업사항 */
		       , MAX(EXDC_AUTO_SERIALINFO.REF_DOCID)         AS REF_DOCID                     /* 내부첨부 */
		       , MAX(EXDC_AUTO_SERIALINFO.REF_CUST_DOCID)    AS REF_CUST_DOCID                /* 고객첨부 */
		       , MAX(EXDC_AUTO_SERIALINFO.REF_DOCID)         AS ADD_DOCID                     /* 추가첨부 */
		       , MAX(MS_SKU.DURATION)                        AS DURATION                      /* 기준일 */
		       , MAX(EXDC_AUTO_SERIALINFO.REJECT_REASON)     AS REJECT_REASON                 /* 반려사유 */
		       , MAX(EXDC_AUTO_SERIALINFO.SEND_MEMO)         AS SEND_MEMO                     /* 확인사항 */
		
		       , MAX( NVL(CD_STATUS.BASEDESCR , TMP.SERIALINFO_CFM_YN) )
		                                                    AS STATUS                         /* 처리상태 */
		
		       , MAX(ST_SNINFO.CONTRACTCUSTKEY)              AS CONTRACTCOMPANY               /* 계약고객 */
		       , MAX( ( SELECT DESCRIPTION
		                 FROM MS_CUST
		                WHERE CUSTKEY = ST_SNINFO.CONTRACTCUSTKEY
		                  AND ROWNUM  = 1 ) )              AS CONTRACTCOMPANYNAME             /* 계약고객명 */
		       , MAX( NVL(CD_CONTYPE_SN.BASEDESCR , ST_SNINFO.CONTRACTTYPE) )
		                                                    AS CONTRACTTYPE_SN                /* 계약구분 */
		
			       , MAX(DM_EXDC_AUTOORD_CHECK.CANCELRMK)        AS CANCELRMK 
	        FROM   DP_INPLAN           DP_INPLAN
	        JOIN   DM_DOCUMENT_H       DM_DOCUMENT_H
	          ON   DM_DOCUMENT_H.DCCODE      = DP_INPLAN.DCCODE
	         AND   DM_DOCUMENT_H.STORERKEY   = DP_INPLAN.STORERKEY
	         AND   DM_DOCUMENT_H.DOCDT       = DP_INPLAN.DOCDT
	         AND   DM_DOCUMENT_H.DOCTYPE     = DP_INPLAN.DOCTYPE
	         AND   DM_DOCUMENT_H.DOCNO       = DP_INPLAN.DOCNO
	         AND  DM_DOCUMENT_H.DELIVERYDATE = DP_INPLAN.DELIVERYDATE
	         AND   DM_DOCUMENT_H.DOCTYPE     = 'DP'
	         AND   DM_DOCUMENT_H.DEL_YN      = 'N'
	        JOIN   DM_DOCUMENT_D        DM_DOCUMENT_D
	          ON   DM_DOCUMENT_D.DCCODE      = DP_INPLAN.DCCODE
	         AND   DM_DOCUMENT_D.STORERKEY   = DP_INPLAN.STORERKEY
	         AND   DM_DOCUMENT_D.DOCTYPE     = DP_INPLAN.DOCTYPE
	         AND   DM_DOCUMENT_D.DOCDT       = DP_INPLAN.DOCDT
	         AND   DM_DOCUMENT_D.DOCNO       = DP_INPLAN.DOCNO
	         AND   DM_DOCUMENT_D.DOCLINE     = DP_INPLAN.DOCLINE
	         AND   DM_DOCUMENT_D.DELIVERYDATE = DP_INPLAN.DELIVERYDATE
	         AND   DM_DOCUMENT_D.CHANNEL     IN ('1','2','3')
	         AND   DM_DOCUMENT_D.DEL_YN      = 'N'
	        JOIN   DP_INVOICE_SN        DP_INVOICE_SN
	          ON   DP_INVOICE_SN.DCCODE      = DP_INPLAN.DCCODE
	         AND   DP_INVOICE_SN.STORERKEY   = DP_INPLAN.STORERKEY
	         AND   DP_INVOICE_SN.DOCTYPE     = DP_INPLAN.DOCTYPE
	         AND   DP_INVOICE_SN.SLIPNO      = DP_INPLAN.SLIPNO
	         AND   DP_INVOICE_SN.SLIPDT      = DP_INPLAN.SLIPDT
	         AND   DP_INVOICE_SN.SLIPLINE    = DP_INPLAN.SLIPLINE
	         AND   DP_INVOICE_SN.SKU         = DP_INPLAN.SKU
	        JOIN   ST_SNINFO            ST_SNINFO
	          ON   ST_SNINFO.STORERKEY       = DP_INVOICE_SN.STORERKEY
	         AND   ST_SNINFO.SKU             = DP_INVOICE_SN.SKU
	         AND   ST_SNINFO.SERIALNO        = DP_INVOICE_SN.SERIALNO
	         AND   ST_SNINFO.STOCKID         = DP_INVOICE_SN.STOCKID
	        JOIN   MS_SKU               MS_SKU
	          ON   MS_SKU.STORERKEY          = DP_INPLAN.STORERKEY
	         AND   MS_SKU.SKU                = DP_INPLAN.SKU
	         AND   MS_SKU.DEL_YN             = 'N'
	        JOIN   DM_EXDC_AUTOORD_CHECK DM_EXDC_AUTOORD_CHECK
	          ON   DM_EXDC_AUTOORD_CHECK.MAPKEY_NO   = DM_DOCUMENT_D.MAPKEY_NO
	         AND   DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE = DM_DOCUMENT_D.MAPKEY_LINE
	         AND   DM_EXDC_AUTOORD_CHECK.ISSUE_NO    = DM_DOCUMENT_D.ISSUE_NO
	         AND   DM_EXDC_AUTOORD_CHECK.MAP_DIV     = DM_DOCUMENT_D.MAP_DIV
	         AND   DM_EXDC_AUTOORD_CHECK.REAL_YN     = DM_DOCUMENT_D.REAL_YN
	        LEFT JOIN DM_EXDC_AUTOORD_CHECK  AD
	          ON   AD.MAPKEY_NO    = DM_EXDC_AUTOORD_CHECK.MAPKEY_NO
	         AND   AD.MAPKEY_LINE  = DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE
	         AND   AD.ISSUE_NO     = DM_EXDC_AUTOORD_CHECK.ISSUE_NO
	         AND   AD.ADD_YN       = 'Y'
	        LEFT JOIN DM_EXDC_AUTOORD_CHECK  TMP
	          ON   TMP.MAPKEY_NO   = DM_EXDC_AUTOORD_CHECK.MAPKEY_NO
	         AND   TMP.MAPKEY_LINE = DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE
	         AND   TMP.REAL_YN     = 'T'
	        LEFT JOIN DP_INVOICE_SN      TMP_SN
	          ON   TMP_SN.SLIPNO   = TMP.TMP_DPKEY
	        LEFT JOIN ST_SNINFO         TMP_SNINFO
	          ON   TMP_SNINFO.STORERKEY = TMP_SN.STORERKEY
	         AND   TMP_SNINFO.SKU       = TMP_SN.SKU
	         AND   TMP_SNINFO.SERIALNO  = TMP_SN.SERIALNO
	         AND   TMP_SNINFO.STOCKID   = TMP_SN.STOCKID
	        LEFT JOIN DP_INVOICE_SN      ADD_SN
	          ON   ADD_SN.SLIPNO   = AD.DPKEY
	         AND   ADD_SN.DOCTYPE  = 'DP'
	        LEFT JOIN WD_INVOICE_SN      ADDWD_SN
	          ON   ADDWD_SN.WD_DOCNO = AD.DPKEY
	         AND   ADDWD_SN.DOCTYPE  = 'WD'
	        LEFT JOIN ST_SNINFO         ADD_SNINFO
	          ON   ADD_SNINFO.STORERKEY = ADD_SN.STORERKEY
	         AND   ADD_SNINFO.SKU       = ADD_SN.SKU
	         AND   ADD_SNINFO.SERIALNO  = ADD_SN.SERIALNO
	         AND   ADD_SNINFO.STOCKID   = ADD_SN.STOCKID
	        
	        ]]>
	
	        <!-- ▼ SERIALINFO_CFM_YN 값별 EXDC_AUTO_SERIALINFO JOIN 구분 -->
	        <if test="serialinfoCfmYn == '10'">
	            JOIN EXDC_AUTO_SERIALINFO EXDC_AUTO_SERIALINFO
	              ON EXDC_AUTO_SERIALINFO.MAPKEY_NO   = DM_EXDC_AUTOORD_CHECK.MAPKEY_NO
	             AND EXDC_AUTO_SERIALINFO.MAPKEY_LINE = DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE
	             AND EXDC_AUTO_SERIALINFO.ISSUE_NO    = DM_EXDC_AUTOORD_CHECK.ISSUE_NO
	        </if>
	        <if test="serialinfoCfmYn == '20'">
	            JOIN EXDC_AUTO_SERIALINFO EXDC_AUTO_SERIALINFO
	              ON EXDC_AUTO_SERIALINFO.MAPKEY_NO   = DM_EXDC_AUTOORD_CHECK.MAPKEY_NO
	             AND EXDC_AUTO_SERIALINFO.MAPKEY_LINE = DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE
	             AND EXDC_AUTO_SERIALINFO.ISSUE_NO    = DM_EXDC_AUTOORD_CHECK.ISSUE_NO
	             AND EXDC_AUTO_SERIALINFO.SERIALNO     = ST_SNINFO.SERIALNO
	             AND EXDC_AUTO_SERIALINFO.CONVSERIALNO = ST_SNINFO.CONVSERIALNO
	        </if>
	        <if test="serialinfoCfmYn == '30'">
	            LEFT JOIN EXDC_AUTO_SERIALINFO EXDC_AUTO_SERIALINFO
	              ON EXDC_AUTO_SERIALINFO.MAPKEY_NO   = DM_EXDC_AUTOORD_CHECK.MAPKEY_NO
	             AND EXDC_AUTO_SERIALINFO.MAPKEY_LINE = DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE
	             AND EXDC_AUTO_SERIALINFO.ISSUE_NO    = DM_EXDC_AUTOORD_CHECK.ISSUE_NO
	             AND EXDC_AUTO_SERIALINFO.SERIALNO     = ST_SNINFO.SERIALNO
	             AND EXDC_AUTO_SERIALINFO.CONVSERIALNO = ST_SNINFO.CONVSERIALNO
	        </if>
	        <if test="serialinfoCfmYn == '40'">
	            LEFT JOIN EXDC_AUTO_SERIALINFO EXDC_AUTO_SERIALINFO
	              ON EXDC_AUTO_SERIALINFO.MAPKEY_NO   = DM_EXDC_AUTOORD_CHECK.MAPKEY_NO
	             AND EXDC_AUTO_SERIALINFO.MAPKEY_LINE = DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE
	             AND EXDC_AUTO_SERIALINFO.ISSUE_NO    = DM_EXDC_AUTOORD_CHECK.ISSUE_NO
	             AND EXDC_AUTO_SERIALINFO.SERIALNO     = ST_SNINFO.SERIALNO
	             AND EXDC_AUTO_SERIALINFO.CONVSERIALNO = ST_SNINFO.CONVSERIALNO
	        </if>
	        <if test="serialinfoCfmYn == '50'">
	            LEFT JOIN EXDC_AUTO_SERIALINFO EXDC_AUTO_SERIALINFO
	              ON EXDC_AUTO_SERIALINFO.MAPKEY_NO   = DM_EXDC_AUTOORD_CHECK.MAPKEY_NO
	             AND EXDC_AUTO_SERIALINFO.MAPKEY_LINE = DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE
	             AND EXDC_AUTO_SERIALINFO.ISSUE_NO    = DM_EXDC_AUTOORD_CHECK.ISSUE_NO
	             AND EXDC_AUTO_SERIALINFO.SERIALNO     = ST_SNINFO.SERIALNO
	             AND EXDC_AUTO_SERIALINFO.CONVSERIALNO = ST_SNINFO.CONVSERIALNO
	        </if>
	
			LEFT JOIN CM_CODE_STORER CD_STORAGETYPE
			       ON CD_STORAGETYPE.STORERKEY = MS_SKU.STORERKEY
			      AND CD_STORAGETYPE.CODELIST  = 'STORAGETYPE'
			      AND CD_STORAGETYPE.BASECODE  = MS_SKU.STORAGETYPE
			
			LEFT JOIN CM_CODE_STORER CD_MOVE_FW          
			       ON CD_MOVE_FW.STORERKEY = 'FW00'
			      AND CD_MOVE_FW.CODELIST  = 'EXDC_MOVE'
			      AND CD_MOVE_FW.BASECODE  = DM_EXDC_AUTOORD_CHECK.MOVE_YN
			
			LEFT JOIN CM_CODE_STORER CD_TEMP_FW          
			       ON CD_TEMP_FW.STORERKEY = 'FW00'
			      AND CD_TEMP_FW.CODELIST  = 'TMEP_WEIGHT_STATUS'
			      AND CD_TEMP_FW.BASECODE  = DM_EXDC_AUTOORD_CHECK.TEMP_YN
			
			LEFT JOIN CM_CODE_STORER CD_MAPDIV
			       ON CD_MAPDIV.STORERKEY = DM_DOCUMENT_D.STORERKEY
			      AND CD_MAPDIV.CODELIST  = 'MAP_DIV'
			      AND CD_MAPDIV.BASECODE  = DM_EXDC_AUTOORD_CHECK.MAP_DIV
			
			LEFT JOIN CM_CODE_STORER CD_STATUS
			       ON CD_STATUS.STORERKEY = DM_DOCUMENT_D.STORERKEY
			      AND CD_STATUS.CODELIST  = 'SERIAL_CFM_STATUS'
			      AND CD_STATUS.BASECODE  = TMP.SERIALINFO_CFM_YN
			
			LEFT JOIN CM_CODE_STORER CD_CONTYPE_SN
			       ON CD_CONTYPE_SN.STORERKEY = ST_SNINFO.STORERKEY
			      AND CD_CONTYPE_SN.CODELIST  = 'CONTRACTTYPE_SN'
			      AND CD_CONTYPE_SN.BASECODE  = ST_SNINFO.CONTRACTTYPE
	        <![CDATA[
	        WHERE  DM_EXDC_AUTOORD_CHECK.MAPKEY_NO = #{mapkeyNo}
	          AND  DM_EXDC_AUTOORD_CHECK.POKEY     = #{pokey}
	          AND  DM_EXDC_AUTOORD_CHECK.ADD_YN    = 'N'
	          AND  DM_DOCUMENT_D.POKEY             = #{pokey}
	          AND  ST_SNINFO.POKEY                 = #{pokey}
	        ]]>
	   
	        <if test="serialinfoCfmYn == '10'">
	            <![CDATA[
	              AND DM_EXDC_AUTOORD_CHECK.REAL_YN = 'R'
	              AND EXDC_AUTO_SERIALINFO.ISSUE_NO IS NOT NULL
	            ]]>
	        </if>
	        <if test="serialinfoCfmYn == '20'">
	            <![CDATA[
	              AND DM_EXDC_AUTOORD_CHECK.REAL_YN = 'T'
	            ]]>
	        </if>
	        <if test="serialinfoCfmYn == '30'">
	            <![CDATA[
	              AND DM_EXDC_AUTOORD_CHECK.REAL_YN = 'T'
	            ]]>
	        </if>
	        <if test="serialinfoCfmYn == '40'">
	            <![CDATA[
	              AND DM_EXDC_AUTOORD_CHECK.REAL_YN = 'T'
	            ]]>
	        </if>
	        <if test="serialinfoCfmYn == '50'">
	            <![CDATA[
	              AND DM_EXDC_AUTOORD_CHECK.REAL_YN = 'T'
	            ]]>
	        </if>
	
	        <![CDATA[
	        GROUP BY
	              DM_EXDC_AUTOORD_CHECK.MAPKEY_NO,
	              DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE,
	              DM_EXDC_AUTOORD_CHECK.ISSUE_NO,
	              DM_EXDC_AUTOORD_CHECK.POKEY,
	              DM_EXDC_AUTOORD_CHECK.POLINE,
	              DM_DOCUMENT_D.MAPKEY_NO,
	              DM_DOCUMENT_D.MAPKEY_LINE,
	              DM_DOCUMENT_D.ISSUE_NO,
	              DP_INVOICE_SN.STOCKID,
	              DP_INPLAN.DCCODE,
	              DP_INPLAN.STORERKEY,
	              DP_INPLAN.DOCDT,
	              DP_INPLAN.DOCNO,
	              DP_INPLAN.DOCTYPE,
	              DP_INPLAN.SLIPDT,
	              DP_INPLAN.SLIPNO,
	              TMP.TMP_DPKEY,
	              AD.POKEY,
	              DM_EXDC_AUTOORD_CHECK.DPKEY,
	              EXDC_AUTO_SERIALINFO.ISSUE_NO,
	              TMP.TMP_DPKEY,              /* 원본에 중복 존재 – 그대로 유지 */
	              DM_EXDC_AUTOORD_CHECK.DPKEY,/* 중복 */
	              DM_EXDC_AUTOORD_CHECK.SOKEY,
	              DM_EXDC_AUTOORD_CHECK.EXDC_ORDERTYPE
	        ]]>

    </select>
    
     <select id="getDataLocalDetailList" resultType="kpEXstorageMonitoringLocalDetailListResDto">

        <![CDATA[
	        SELECT	/* [kpEXstorageMonitoringService.sqlx][getDataLocalDetailList][외부창고재고모티터링 상세][ParkJinWoo][20250716] */
				  A.MAPKEY_NO                                        AS MAPKEY_NO           /* 구매요청번호 */
		       , MAX(A.POKEY)                                        AS POKEY               /* 구매번호 */
		       , MAX(A.POLINE)                                       AS POLINE              /* 구매라인 */
		       , MAX(PO.POKEY)                                       AS ADDPOKEY            /* 조정구매번호 */
		       , MAX(PO.POLINE)                                      AS ADDPOLINE           /* 조정구매라인 */
		       , MAX( CASE
		                  WHEN A.CONFIRM_YN = '10' THEN '10'
		                  WHEN A.CONFIRM_YN = '20' THEN '20'
		                  ELSE '40'
		               END )                                         AS SERIALINFO_CFM_YN   /* 처리확정여부 */
		       , MAX(A.DELIVERYDATE)                                 AS DELIVERYDATE        /* 배송일 */
		       , MAX(TO_CHAR(A.ADDDATE,'YYYYMMDD'))                  AS DOCDT               /* 문서일자 */
		       , MAX(A.SKU)                                          AS SKU                 /* 상품코드 */
		       , MAX(MS_SKU.DESCRIPTION)                             AS SKUNAME             /* 상품명 */
		       , MAX( NVL(CD_STORAGETYPE.BASEDESCR
		                 , MS_SKU.STORAGETYPE) )                      AS STORAGETYPENAME     /* 저장조건 */
		       , MAX('('||MS_SKU.PLACEOFORIGIN||')'||
		             ( SELECT BASEDESCR
		                 FROM CM_CODE
		                WHERE STORERKEY = MS_SKU.STORERKEY
		                  AND CODELIST  = 'COUNTRY'
		                  AND BASECODE  = MS_SKU.PLACEOFORIGIN
		                  AND DEL_YN    = 'N' ))                      AS ORG                 /* 원산지 */
		       , MAX(A.CUSTKEY)                                      AS FROM_CUSTKEY        /* 출고처코드 */
		       , MAX(MS_CUST.DESCRIPTION)                            AS FROM_CUSTNAME       /* 출고처명 */
		       , MAX('2170-'||A.ORGANIZE)                            AS ORGANIZE            /* 창고 */
		       , MAX(( SELECT DESCRIPTION
		                 FROM CM_DCXORGANIZE
		                WHERE ORGANIZE = '2170-'||A.ORGANIZE ))      AS ORGANIZENAME        /* 창고명 */
		       , NVL(MAX(A.GROSSWEIGHT),0)                           AS ORDERQTY            /* 총중량 */
		       , MAX(A.BASEUOM)                                      AS UOM                 /* 단위 */
		       , MAX(A.ORDR_QTY)                                     AS ETCQTY              /* 주문수량 */
		       , MAX(A.ORDR_QTY)                                     AS DPBOXQTY            /* 박스수량 */
		       , MAX(NVL(( SELECT SUM(B.QTY)
		                    FROM ST_STOCK B
		                   WHERE B.STOCKID = A.ISSUE_NO ),0))        AS QTY                 /* 현재고수량 */
		       , MAX(A.GROSSWEIGHT)
		           - MAX(NVL(( SELECT MAX(B.QTY)
		                         FROM ST_STOCK B
		                        WHERE B.STOCKID = A.ISSUE_NO ),0))    AS WDQTY               /* 출고중량 */
		       , MAX(A.BASEUOM)                                      AS SALESUOM            /* 판매단위 */
		       , MAX(MS_SKU.QTYPERBOX)                               AS QTYPERBOX           /* 박스당수량 */
		       , MAX(A.SKU)                                          AS SKU2                /* 보조상품코드 */
		       , SUM(NVL(( SELECT B.QTY
		                    FROM ST_STOCK B
		                   WHERE B.STOCKID = A.ISSUE_NO ),0))        AS QTY_SUM             /* 수량합계 */
		       , MAX(A.ISSUE_NO)                                     AS ISSUE_NO            /* 발행번호 */
		       , MAX(NVL(( SELECT SUM(B.BOXQTY)
		                    FROM ST_STOCK B
		                   WHERE B.STOCKID = A.ISSUE_NO ),0))        AS BOXQTY              /* 박스합계 */
		       , MAX(NVL(( SELECT B.UOM
		                    FROM ST_STOCK B
		                   WHERE B.STOCKID = A.ISSUE_NO ), A.BASEUOM)) AS UOM2               /* 보조단위 */
		       , MAX(A.ADDWHO)                                       AS ADDWHO              /* 등록자 */
		       , MAX(A.ADDWHO)                                       AS EDITWHO             /* 수정자 */
		       , MAX(( SELECT USER_NM
		                 FROM FRAMEONE_USER
		                WHERE USER_ID = A.ADDWHO
		                   OR USER_NO = A.ADDWHO ))                  AS CREATEWHO           /* 최초생성자 */
		       , MAX(( SELECT USER_NM
		                 FROM FRAMEONE_USER
		                WHERE USER_ID = A.EDITWHO
		                   OR USER_NO = A.EDITWHO ))                 AS LASTWHO             /* 최종수정자 */
		       , MAX(TO_CHAR(A.ADDDATE,'YYYY-MM-DD HH24:MI'))        AS REGDATE             /* 등록일시 */
		       , MAX(TO_CHAR(A.EDITDATE,'YYYY-MM-DD HH24:MI'))       AS LASTDATE            /* 최종수정일시 */
		       , 'black'                                             AS FONTCOLOR           /* 글꼴색 */
		       , CASE
		           WHEN MAX(A.CONFIRM_YN) = '20' THEN 'gray'
		           WHEN NVL(MAX(A.CONFIRM_YN),'') IS NULL
		                AND TO_CHAR(MAX(A.ADDDATE),'YYYYMMDD')
		                    < TO_CHAR(SYSDATE,'YYYYMMDD')           THEN 'pink'
		           ELSE ''
		         END                                                 AS BGCOLOR             /* 배경색 */
		       , MAX( NVL(CD_STATUS.BASEDESCR
		                 , NVL(A.CONFIRM_YN,'40')) )               AS STATUS              /* 처리상태 */
		       , MAX( NVL(CD_MOVE_FW.BASEDESCR
		                 , A.MOVE_YN) )                            AS MOVE_YN             /* 이체여부 */
		       , MAX( NVL(CD_TEMP_FW.BASEDESCR
		                 , A.TEMP_YN) )                            AS TEMP_YN             /* 가중량여부 */
		       , MAX( NVL(CD_MAPDIV.BASEDESCR
		                 , B.MAP_DIV) )                            AS CONTRACTTYPE        /* 거래유형 */
		       , MAX(A.PAY_YMD)                                      AS PAYYMD              /* 지급일 */
		       , MAX(A.RECEIVE_MEMO)                                 AS RECEIVE_MEMO        /* 영업사항 */
		       , MAX(A.REF_DOCID)                                    AS REF_DOCID           /* 내부첨부 */
		       , MAX(A.REF_CUST_DOCID)                               AS REF_CUST_DOCID      /* 고객첨부 */
		       , MAX(A.REF_ADD_DOCID)                                AS REF_ADD_DOCID       /* 추가첨부 */
		       , MAX(( SELECT C.CONVSERIALNO
		                 FROM ST_SNINFO C
		                WHERE C.STOCKID = A.ISSUE_NO ))            AS CONVSERIALNO        /* BL번호 */
		       , MAX(( SELECT C.CONVSERIALNO
		                 FROM ST_SNINFO C
		                WHERE C.STOCKID = A.ISSUE_NO ))            AS ADD_CONVSERIALNO     /* 조정BL */
		       , MAX(( SELECT C.SERIALNO
		                 FROM ST_SNINFO C
		                WHERE C.STOCKID = A.ISSUE_NO ))            AS SERIALNO            /* 최종이력 */
		       , MAX(( SELECT C.SERIALNO
		                 FROM ST_SNINFO C
		                WHERE C.STOCKID = A.ISSUE_NO ))            AS ADD_SERIALNO         /* 조정이력 */
		       , MAX(A.ISSUE_NO)                                     AS STOCKID             /* 재고바코드 */
		       , MAX(A.TO_CUSTKEY)                                   AS FROM_CUSTKEY2       /* 입고처코드 */
		       , MAX(MS_CUST.DESCRIPTION)                            AS FROM_CUSTNAME2      /* 입고처명 */
		       , MAX(MS_SKU.DURATION)                                AS DURATION            /* 유통기한기준 */
		       , MAX(MS_SKU.DURATION)                                AS ADD_DURATION        /* 조정유통기한기준 */
		       , MAX( CASE
		                WHEN NVL(ST_SNINFO.LOTTABLE01,'STD') = 'STD' THEN 'N'
		                WHEN MONTHS_BETWEEN(
		                       TO_DATE(NVL(ST_SNINFO.LOTTABLE01,'STD'),'YYYY-MM-DD'),
		                       SYSDATE) > 3                         THEN 'N'
		                ELSE 'Y'
		             END )                                          AS NEARDURATIONYN      /* 임박여부 */
		       , MAX( CASE
		                WHEN NVL(ST_SNINFO.LOTTABLE01,'STD') = 'STD' THEN 'N'
		                WHEN MONTHS_BETWEEN(
		                       TO_DATE(NVL(ST_SNINFO.LOTTABLE01,'STD'),'YYYY-MM-DD'),
		                       SYSDATE) > 3                         THEN 'N'
		                ELSE 'Y'
		             END )                                          AS ADD_NEARDURATIONYN   /* 조정임박여부 */
		       , MAX(NVL(ST_SNINFO.LOTTABLE01,'STD'))                 AS LOTTABLE01          /* LOT번호 */
		       , MAX(NVL(ST_SNINFO.LOTTABLE01,'STD'))                 AS ADD_LOTTABLE01      /* 조정LOT번호 */
		       , MAX( FN_LOTDURATION(A.STORERKEY,
		                             MS_SKU.DURATIONTYPE,
		                             MS_SKU.DURATION,
		                             NVL(ST_SNINFO.LOTTABLE01,'STD'),
		                             'N')
		             || '/' || MS_SKU.DURATION )                     AS DURATION_TERM        /* 유통기간 */
		       , MAX(A.REJECT_CODE)                                   AS REJECT_REASON       /* 반려사유 */
		       , MAX(A.SEND_MEMO)                                     AS SEND_MEMO           /* 확인사항 */
		       , MAX(MS_SKU.QTYPERBOX)                                AS QTYPERBOX2          /* 박스당수량 */
		       , MAX(A.TO_CUSTKEY)                                    AS CONTRACTCOMPANY     /* 계약고객코드 */
		       , MAX(( SELECT DESCRIPTION
		                 FROM MS_CUST
		                WHERE CUSTKEY = A.TO_CUSTKEY
		                  AND ROWNUM = 1 ))                        AS CONTRACTCOMPANYNAME /* 계약고객명 */
		       , MAX(PODM.ISSUE_NO)                                  AS ADD_STOCKID         /* 추가바코드 */
		       , MAX(PODM.UOM)                                       AS UOM3                /* 추가단위 */
		       , MAX(PODM.ETCQTY2)                                   AS ADD_BOXQTY          /* 추가박스수 */
		       , MAX(PODM.CONFIRMQTY)                                AS ADD_ORDERQTY        /* 추가수량 */
		       , MAX( FN_LOTDURATION(A.STORERKEY,
		                             MS_SKU.DURATIONTYPE,
		                             MS_SKU.DURATION,
		                             NVL(ST_SNINFO.LOTTABLE01,'STD'),
		                             'N')
		             || '/' || MS_SKU.DURATION )                     AS ADD_DURATION_TERM   /* 조정유통기간 */
	        /* ─────────────── FROM / JOIN ─────────────── */
	        FROM    EXDC_SCM_CFM_LOCAL       A
	        LEFT JOIN MS_CUST                MS_CUST
	               ON A.STORERKEY    = MS_CUST.STORERKEY
	              AND A.CUSTKEY      = MS_CUST.CUSTKEY
	        JOIN  MS_SKU                     MS_SKU
	               ON A.SKU         = MS_SKU.SKU
	              AND A.STORERKEY   = MS_SKU.STORERKEY
	        LEFT JOIN DM_EXDC_AUTOORD_CHECK  B
	               ON A.MAPKEY_NO    = B.MAPKEY_NO
	              AND A.MAPKEY_LINE  = B.MAPKEY_LINE
	              AND A.ISSUE_NO     = B.ISSUE_NO
	        LEFT JOIN DM_EXDC_AUTOORD_CHECK  PO
	               ON B.POKEY        = PO.DP_SOURCEKEY
	              AND B.POLINE       = PO.DP_SOURCEKEYLINE
	              AND B.ISSUE_NO     = PO.ISSUE_NO
	              AND PO.ADD_YN      = 'Y'
	        LEFT JOIN DM_DOCUMENT_D          PODM
	               ON PO.POKEY        = PODM.POKEY
	              AND PO.POLINE       = PODM.POLINE
	              AND PO.MAPKEY_NO    = PODM.MAPKEY_NO
	              AND PO.MAPKEY_LINE  = PODM.MAPKEY_LINE
	              AND PO.ISSUE_NO     = PODM.ISSUE_NO
	              AND PO.ADD_YN       = PODM.ADD_YN
	        LEFT JOIN MS_CUST                MS_CUST2
	               ON A.STORERKEY    = MS_CUST2.STORERKEY
	              AND A.TO_CUSTKEY   = MS_CUST2.CUSTKEY
	        LEFT JOIN ST_SNINFO              ST_SNINFO
	               ON ST_SNINFO.STOCKID  = A.ISSUE_NO
	              AND ST_SNINFO.SERIALNO = A.SERIALNO
	            /* ----- CODE LIST 변환 JOIN ----- */  
	        LEFT JOIN CM_CODE_STORER CD_STORAGETYPE
			       ON CD_STORAGETYPE.STORERKEY = MS_SKU.STORERKEY
			      AND CD_STORAGETYPE.CODELIST  = 'STORAGETYPE'
			      AND CD_STORAGETYPE.BASECODE  = MS_SKU.STORAGETYPE
			
			LEFT JOIN CM_CODE_STORER CD_STATUS
			       ON CD_STATUS.STORERKEY = A.STORERKEY
			      AND CD_STATUS.CODELIST  = 'SERIAL_CFM_STATUS'
			      AND CD_STATUS.BASECODE  = NVL(A.CONFIRM_YN,'40')
			
			LEFT JOIN CM_CODE_STORER CD_MOVE_FW
			       ON CD_MOVE_FW.STORERKEY = 'FW00'
			      AND CD_MOVE_FW.CODELIST  = 'EXDC_MOVE'
			      AND CD_MOVE_FW.BASECODE  = A.MOVE_YN
			
			LEFT JOIN CM_CODE_STORER CD_TEMP_FW
			       ON CD_TEMP_FW.STORERKEY = 'FW00'
			      AND CD_TEMP_FW.CODELIST  = 'TMEP_WEIGHT_STATUS'
			      AND CD_TEMP_FW.BASECODE  = A.TEMP_YN
			
			LEFT JOIN CM_CODE_STORER CD_MAPDIV
			       ON CD_MAPDIV.STORERKEY = A.STORERKEY
			      AND CD_MAPDIV.CODELIST  = 'MAP_DIV'
			      AND CD_MAPDIV.BASECODE  = B.MAP_DIV	
	        /* ─────────────── WHERE / GROUP BY ─────────────── */
	        WHERE   A.MAPKEY_NO      = #{mapkeyNo}
	        GROUP BY A.MAPKEY_NO, A.ISSUE_NO
        ]]>
    </select>
    
    <select id="getDataDetailSubList" resultType="kpEXstorageMonitoringDetailSubListResDto">
		<![CDATA[
		SELECT	/* [kpEXstorageMonitoringService.sqlx][getDataDetailSubList][외외창고재고모티터링 Sub 상세][ParkJinWoo][20250716] */
	         DISTINCT DM_EXDC_AUTOORD_CHECK.MAPKEY_NO                                  AS MAPKEY_NO           /* 구매요청번호 */
	       , DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE                                        AS MAPKEY_LINE         /* 구매요청항번 */
	       , EXDC_AUTO_SERIALINFO.ISSUE_NO                                            AS ISSUE_NO            /* 이슈번호 */
	       , MAX(DM_EXDC_AUTOORD_CHECK.POKEY)                 AS POKEY                  /* 구매번호 */
	       , MAX(DM_EXDC_AUTOORD_CHECK.POLINE)                AS POLINE                 /* 구매라인 */
	       , MAX(AD.POKEY)                                   AS ADDPOKEY               /* 조정구매번호 */
	       , MAX(AD.POLINE)                                  AS ADDPOLINE              /* 조정구매라인 */
	       , MAX(TMP.TMP_SOKEY)                              AS TMP_SOKEY              /* 가SO번호 */
	       , MAX(TMP.TMP_SOLINE)                             AS TMP_SOLINE             /* 가SO항번 */
	       , DM_EXDC_AUTOORD_CHECK.SOKEY                   	 AS SOKEY                 /* SO번호 */
	       , MAX(DM_EXDC_AUTOORD_CHECK.SOLINE)               AS SOLINE                 /* SO항번 */
	       , MAX(AD.SOKEY)                                   AS AD_SOKEY               /* 조정SO번호 */
	       , MAX(AD.SOLINE)                                  AS AD_SOLINE              /* 조정SO항번 */
	       , MAX(DM_DOCUMENT_D.DELIVERYDATE)                 AS DELIVERYDATE           /* 배송일 */
	       , MAX(DM_DOCUMENT_D.DOCDT)                        AS DOCDT                  /* 문서일자 */
	       , MAX(TMP.TMP_DPKEY)                              AS TMP_DPKEY              /* 가DPKEY */
	       , MAX(DM_EXDC_AUTOORD_CHECK.DPKEY)                AS DPKEY                  /* DPKEY */
	       , MAX(DP_INPLAN.SKU)                              AS SKU                    /* 상품코드 */
	       , MAX(MS_SKU.DESCRIPTION)                         AS SKUNAME                /* 상품명 */
	       , MAX( NVL(CD_STORAGETYPE.BASEDESCR , MS_SKU.STORAGETYPE) )
	                                                         AS STORAGETYPENAME        /* 저장조건 */
	       , MAX('('||MS_SKU.PLACEOFORIGIN||')'||
	             ( SELECT BASEDESCR
	                 FROM CM_CODE
	                WHERE STORERKEY = MS_SKU.STORERKEY
	                  AND CODELIST  = 'COUNTRY'
	                  AND BASECODE  = MS_SKU.PLACEOFORIGIN
	                  AND DEL_YN    = 'N' ))
	                                                         AS ORG                     /* 원산지 */
	       , ( MAX(TMP_SN.ORDERQTY) + MAX(TMP_SN.CANCELQTY) ) AS TMP_QTY                 /* 임시수량 */
	       , ( MAX(TMP_SN.ETCQTY2) + MAX(TMP_SN.ETCQTY1) )   AS TMP_ETCQTY2             /* 임시박스 */
	       , NVL(MAX(ADD_SN.ORDERQTY), MAX(ADDWD_SN.ORDERQTY))
	                                                         AS ADD_ORDERQTY            /* 조정수량 */
	       , NVL(MAX(ADD_SN.ETCQTY1), MAX(ADDWD_SN.ETCQTY1))
	                                                         AS ADD_BOXQTY              /* 조정박스 */
	       , MAX(TMP_SN.SERIALNO)                            AS TMP_SERIALNO            /* 임시이력 */
	       , MAX(TMP_SN.STOCKID)                             AS TMP_STOCKID             /* 임시바코드 */
	       , MAX(NVL(TMP_SNINFO.LOTTABLE01,'STD'))           AS TMP_LOTTABLE01          /* 임시LOT */
	       , MAX( FN_LOTDURATION(DP_INPLAN.STORERKEY,
	                             MS_SKU.DURATIONTYPE,
	                             MS_SKU.DURATION,
	                             NVL(TMP_SNINFO.LOTTABLE01,'STD'),
	                             'N') || '/' || MS_SKU.DURATION )
	                                                         AS TMP_DURATION_TERM       /* 임시유통기간 */
	       , MAX(CASE
	               WHEN NVL(TMP_SNINFO.LOTTABLE01,'STD') = 'STD' THEN 'N'
	               WHEN MONTHS_BETWEEN(
	                      TO_DATE(NVL(TMP_SNINFO.LOTTABLE01,'STD'),'YYYY-MM-DD'),
	                      SYSDATE) > 3 THEN 'N'
	               ELSE 'Y'
	             END)
	                                                         AS TMP_NEARDURATIONYN       /* 임박여부 */
	       , MAX(TMP_SNINFO.CONVSERIALNO)                    AS TMP_CONVSERIALNO         /* 임시BL */
	       , NVL(MAX(ADD_SN.SERIALNO), MAX(ADDWD_SN.SERIALNO))
	                                                         AS ADD_SERIALNO             /* 조정이력 */
	       , NVL(MAX(ADD_SN.STOCKID), MAX(ADDWD_SN.STOCKID))
	                                                         AS ADD_STOCKID              /* 조정바코드 */
	       , MAX(CASE
	               WHEN NVL(ADD_SNINFO.LOTTABLE01,'STD') = 'STD' THEN 'N'
	               WHEN MONTHS_BETWEEN(
	                      TO_DATE(NVL(ADD_SNINFO.LOTTABLE01,'STD'),'YYYY-MM-DD'),
	                      SYSDATE) > 3 THEN 'N'
	               ELSE 'Y'
	             END)
	                                                         AS AD_NEARDURATIONYN        /* 조정임박여부 */
	       , NVL(MAX(ADD_SNINFO.CONVSERIALNO), MAX(ST_SNINFO.CONVSERIALNO))
	                                                         AS ADD_CONVSERIALNO         /* 조정BL */
	       , MAX(NVL(ADD_SNINFO.LOTTABLE01,'STD'))           AS AD_LOTTABLE01            /* 조정LOT */
	       , MAX( FN_LOTDURATION(DP_INPLAN.STORERKEY,
	                             MS_SKU.DURATIONTYPE,
	                             MS_SKU.DURATION,
	                             NVL(ADD_SNINFO.LOTTABLE01,'STD'),
	                             'N') || '/' || MS_SKU.DURATION )
	                                                         AS AD_DURATION_TERM         /* 조정유통기간 */
	       , MAX(ST_SNINFO.SERIALNO)                         AS SERIALNO                 /* 최종이력 */
	       , MAX(DP_INVOICE_SN.STOCKID)                      AS STOCKID                  /* 최종바코드 */
	       , MAX(ST_SNINFO.CONVSERIALNO)                     AS CONVSERIALNO             /* 최종BL */
	       , MAX(CASE
	               WHEN NVL(ST_SNINFO.LOTTABLE01,'STD') = 'STD' THEN 'N'
	               WHEN MONTHS_BETWEEN(
	                      TO_DATE(NVL(ST_SNINFO.LOTTABLE01,'STD'),'YYYY-MM-DD'),
	                      SYSDATE) > 3 THEN 'N'
	               ELSE 'Y'
	             END)
	                                                         AS NEARDURATIONYN           /* 최종임박여부 */
	       , MAX(NVL(ST_SNINFO.LOTTABLE01,'STD'))            AS LOTTABLE01               /* 최종LOT */
	       , MAX( FN_LOTDURATION(DP_INPLAN.STORERKEY,
	                             MS_SKU.DURATIONTYPE,
	                             MS_SKU.DURATION,
	                             NVL(ST_SNINFO.LOTTABLE01,'STD'),
	                             'N') || '/' || MS_SKU.DURATION )
	                                                         AS DURATION_TERM            /* 최종유통기간 */
	       , MAX(DP_INVOICE_SN.ORDERQTY)                     AS ORDERQTY                 /* 최종수량 */
	       , MAX(DP_INVOICE_SN.ETCQTY1)                      AS ETCQTY                  /* 최종박스 */
	       , MAX(DM_DOCUMENT_D.UOM)                          AS UOM                      /* 단위 */
	       , MAX(MS_SKU.QTYPERBOX)                           AS QTYPERBOX                /* 박스당수량 */
	       , MAX( NVL(CD_MOVE_FW.BASEDESCR , DM_EXDC_AUTOORD_CHECK.MOVE_YN) )
	                                                         AS MOVE_YN                  /* 이체여부 */
	       , MAX( NVL(CD_TEMP_FW.BASEDESCR , DM_EXDC_AUTOORD_CHECK.TEMP_YN) )
	                                                         AS TEMP_YN                  /* 가중량여부 */
	       , MAX( NVL(CD_MAPDIV.BASEDESCR , DM_EXDC_AUTOORD_CHECK.MAP_DIV) )
	                                                         AS CONTRACTTYPE             /* 거래유형 */
	       , MAX(DM_DOCUMENT_H.TO_CUSTKEY)                   AS FROM_CUSTKEY             /* 입고처코드 */
	       , MAX(DM_DOCUMENT_H.TO_CUSTNAME)                  AS FROM_CUSTNAME            /* 입고처명 */
	       , MAX(DM_DOCUMENT_H.REFERENCE02)                  AS PAYYMD                   /* 지급일 */
	       , MAX(EXDC_AUTO_SERIALINFO.RECEIVE_MEMO)          AS RECEIVE_MEMO             /* 영업사항 */
	       , MAX(EXDC_AUTO_SERIALINFO.REF_DOCID)             AS REF_DOCID                /* 내부첨부 */
	       , MAX(EXDC_AUTO_SERIALINFO.REF_CUST_DOCID)        AS REF_CUST_DOCID           /* 고객첨부 */
	       , MAX(EXDC_AUTO_SERIALINFO.REF_DOCID)             AS ADD_DOCID                /* 추가첨부 */
	       , MAX(MS_SKU.DURATION)                            AS DURATION                 /* 기준유통기한 */
	       , MAX(EXDC_AUTO_SERIALINFO.REJECT_REASON)         AS REJECT_REASON            /* 반려사유 */
	       , MAX(EXDC_AUTO_SERIALINFO.SEND_MEMO)             AS SEND_MEMO                /* 확인사항 */
	       , MAX( NVL(CD_STATUS.BASEDESCR , TMP.SERIALINFO_CFM_YN) )
	                                                         AS STATUS                   /* 처리상태 */
	       , MAX(DM_EXDC_AUTOORD_CHECK.CANCELRMK)             AS CANCELRMK               /* 취소사유 */
	       , NVL(MAX(( SELECT DECODE(FC_MSG_TRAN.TR_RSLTSTAT,'0','S','E')
	                     FROM FC_MSG_TRAN
	                    WHERE FC_MSG_TRAN.TR_BATCHID =
	                          ( SELECT MAX(FC_MSG_TRAN.TR_BATCHID)
	                              FROM WD_EXDC_PRTLOG
	                              JOIN FC_META_TRAN ON WD_EXDC_PRTLOG.DOCNAME = FC_META_TRAN.TR_DOCNAME
	                              JOIN FC_MSG_TRAN  ON FC_META_TRAN.TR_BATCHID = FC_MSG_TRAN.TR_BATCHID
	                             WHERE WD_EXDC_PRTLOG.STORERKEY = DP_INPLAN.STORERKEY
	                               AND WD_EXDC_PRTLOG.DCCODE    = DP_INPLAN.DCCODE
	                               AND WD_EXDC_PRTLOG.DOCNO     = DP_INPLAN.DOCNO
	                               AND WD_EXDC_PRTLOG.DOCLINE   = DP_INPLAN.DOCLINE
	                               AND WD_EXDC_PRTLOG.PAPERTYPE = 'FAX'
	                               AND FC_MSG_TRAN.TR_SENDSTAT  = '2'
	                          )
	                 ) ), '0')
	                                                         AS FAX_LAST_TR_RSLT         /* FAX최종전송결과 */
	       , MAX(( SELECT TO_CHAR(FC_MSG_TRAN.TR_SENDDATE,'YYYY-MM-DD HH24:MI')
	                 FROM FC_MSG_TRAN
	                WHERE FC_MSG_TRAN.TR_BATCHID =
	                      ( SELECT MAX(FC_MSG_TRAN.TR_BATCHID)
	                          FROM WD_EXDC_PRTLOG
	                          JOIN FC_META_TRAN ON WD_EXDC_PRTLOG.DOCNAME = FC_META_TRAN.TR_DOCNAME
	                          JOIN FC_MSG_TRAN  ON FC_META_TRAN.TR_BATCHID = FC_MSG_TRAN.TR_BATCHID
	                         WHERE WD_EXDC_PRTLOG.STORERKEY = 'FW00'
	                           AND WD_EXDC_PRTLOG.DCCODE    = '2170'
	                           AND WD_EXDC_PRTLOG.DOCNO     = TMP.TMP_SOKEY
	                           AND WD_EXDC_PRTLOG.DOCLINE   = TMP.TMP_SOLINE
	                           AND FC_MSG_TRAN.TR_SENDSTAT  = '2'
	                      )
	             ))
	                                                         AS FAX_LAST_TR_SENDDATE     /* FAX최종전송일시 */
	       , MAX(( SELECT FC_META_TRAN.TR_SENDNAME
	                 FROM FC_MSG_TRAN
	                 JOIN FC_META_TRAN ON FC_MSG_TRAN.TR_BATCHID = FC_META_TRAN.TR_BATCHID
	                WHERE FC_MSG_TRAN.TR_BATCHID =
	                      ( SELECT MAX(FC_MSG_TRAN.TR_BATCHID)
	                          FROM WD_EXDC_PRTLOG
	                          JOIN FC_META_TRAN ON WD_EXDC_PRTLOG.DOCNAME = FC_META_TRAN.TR_DOCNAME
	                          JOIN FC_MSG_TRAN  ON FC_META_TRAN.TR_BATCHID = FC_MSG_TRAN.TR_BATCHID
	                         WHERE WD_EXDC_PRTLOG.STORERKEY = 'FW00'
	                           AND WD_EXDC_PRTLOG.DCCODE    = '2170'
	                           AND WD_EXDC_PRTLOG.DOCNO     = TMP.TMP_SOKEY
	                           AND WD_EXDC_PRTLOG.DOCLINE   = TMP.TMP_SOLINE
	                           AND FC_MSG_TRAN.TR_SENDSTAT  = '2'
	                      )
	             ))
	                                                         AS FAX_LAST_TR_SENDNAME     /* FAX최종전송자 */
	       , MAX(ST_SNINFO.CONTRACTCUSTKEY)                   AS CONTRACTCOMPANY          /* 계약고객코드 */
	       , MAX(( SELECT DESCRIPTION
	                 FROM MS_CUST
	                WHERE CUSTKEY = ST_SNINFO.CONTRACTCUSTKEY
	                  AND ROWNUM  = 1 ))
	                                                         AS CONTRACTCOMPANYNAME      /* 계약고객명 */
	       , MAX( NVL(CD_CONTYPE_SN.BASEDESCR , ST_SNINFO.CONTRACTTYPE) )
	                                                         AS CONTRACTTYPE_SN          /* 계약구분 */
	       , MAX(DP_INPLAN.DOCNO)                             AS DOCNO                    /* DP문서번호 */
	       , MAX(DP_INPLAN.DOCLINE)                           AS DOCLINE      
		/* ===== FROM · JOIN 절 (원문 그대로, 스키마 ) ===== */
		FROM  DP_INPLAN
			JOIN  DM_DOCUMENT_H
			  ON  DM_DOCUMENT_H.DCCODE      = DP_INPLAN.DCCODE
			 AND  DM_DOCUMENT_H.STORERKEY   = DP_INPLAN.STORERKEY
			 AND  DM_DOCUMENT_H.DOCDT       = DP_INPLAN.DOCDT
			 AND  DM_DOCUMENT_H.DOCTYPE     = DP_INPLAN.DOCTYPE
			 AND  DM_DOCUMENT_H.DOCNO       = DP_INPLAN.DOCNO
			 
			 AND  DM_DOCUMENT_H.DOCTYPE     = 'DP'
			 AND  DM_DOCUMENT_H.DEL_YN      = 'N'
			JOIN  DM_DOCUMENT_D
			  ON  DM_DOCUMENT_D.DCCODE      = DP_INPLAN.DCCODE
			 AND  DM_DOCUMENT_D.STORERKEY   = DP_INPLAN.STORERKEY
			 AND  DM_DOCUMENT_D.DOCTYPE     = DP_INPLAN.DOCTYPE
			 AND  DM_DOCUMENT_D.DOCDT       = DP_INPLAN.DOCDT
			 AND  DM_DOCUMENT_D.DOCNO       = DP_INPLAN.DOCNO
			 AND  DM_DOCUMENT_D.DOCLINE     = DP_INPLAN.DOCLINE
			 AND  DM_DOCUMENT_D.DELIVERYDATE  = DP_INPLAN.DELIVERYDATE
			 AND  DM_DOCUMENT_D.CHANNEL    IN ('1','2','3')
			 AND  DM_DOCUMENT_D.DEL_YN      = 'N'
			JOIN  DP_INVOICE_SN
			  ON  DP_INVOICE_SN.DCCODE      = DP_INPLAN.DCCODE
			 AND  DP_INVOICE_SN.STORERKEY   = DP_INPLAN.STORERKEY
			 AND  DP_INVOICE_SN.DOCTYPE     = DP_INPLAN.DOCTYPE
			 AND  DP_INVOICE_SN.SLIPNO      = DP_INPLAN.SLIPNO
			 AND  DP_INVOICE_SN.SLIPDT      = DP_INPLAN.SLIPDT
			 AND  DP_INVOICE_SN.SLIPLINE    = DP_INPLAN.SLIPLINE
			 AND  DP_INVOICE_SN.SKU         = DP_INPLAN.SKU
			JOIN  ST_SNINFO
			  ON  ST_SNINFO.STORERKEY       = DP_INVOICE_SN.STORERKEY
			 AND  ST_SNINFO.SKU             = DP_INVOICE_SN.SKU
			 AND  ST_SNINFO.SERIALNO        = DP_INVOICE_SN.SERIALNO
			 AND  ST_SNINFO.STOCKID         = DP_INVOICE_SN.STOCKID
			JOIN  MS_SKU
			  ON  MS_SKU.STORERKEY          = DP_INPLAN.STORERKEY
			 AND  MS_SKU.SKU                = DP_INPLAN.SKU
			 AND  MS_SKU.DEL_YN             = 'N'
			JOIN  DM_EXDC_AUTOORD_CHECK
			  ON  DM_EXDC_AUTOORD_CHECK.MAPKEY_NO   = DM_DOCUMENT_D.MAPKEY_NO
			 AND  DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE = DM_DOCUMENT_D.MAPKEY_LINE
			 AND  DM_EXDC_AUTOORD_CHECK.MAP_DIV     = DM_DOCUMENT_D.MAP_DIV
			 AND  DM_EXDC_AUTOORD_CHECK.REAL_YN     = DM_DOCUMENT_D.REAL_YN
			LEFT JOIN DM_EXDC_AUTOORD_CHECK AD
			  ON  AD.MAPKEY_NO   = DM_EXDC_AUTOORD_CHECK.MAPKEY_NO
			 AND AD.MAPKEY_LINE  = DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE
			 AND AD.ISSUE_NO     = DM_EXDC_AUTOORD_CHECK.ISSUE_NO
			 AND AD.ADD_YN       = 'Y'
			LEFT JOIN DM_EXDC_AUTOORD_CHECK TMP
			  ON  TMP.MAPKEY_NO  = DM_EXDC_AUTOORD_CHECK.MAPKEY_NO
			 AND TMP.MAPKEY_LINE = DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE
			 AND TMP.REAL_YN     = 'T'
			LEFT JOIN DP_INVOICE_SN TMP_SN
			  ON  TMP_SN.SLIPNO  = TMP.TMP_DPKEY
			LEFT JOIN ST_SNINFO TMP_SNINFO
			  ON  TMP_SNINFO.STORERKEY = TMP_SN.STORERKEY
			 AND TMP_SNINFO.SKU       = TMP_SN.SKU
			 AND TMP_SNINFO.SERIALNO  = TMP_SN.SERIALNO
			 AND TMP_SNINFO.STOCKID   = TMP_SN.STOCKID
			LEFT JOIN DP_INVOICE_SN ADD_SN
			  ON  ADD_SN.SLIPNO  = AD.DPKEY
			 AND ADD_SN.DOCTYPE  = 'DP'
			LEFT JOIN WD_INVOICE_SN ADDWD_SN
			  ON  ADDWD_SN.WD_DOCNO = AD.DPKEY
			 AND ADDWD_SN.DOCTYPE   = 'WD'
			LEFT JOIN ST_SNINFO ADD_SNINFO
			  ON  ADD_SNINFO.STORERKEY = ADD_SN.STORERKEY
			 AND ADD_SNINFO.SKU       = ADD_SN.SKU
			 And ADD_SNINFO.SERIALNO  = ADD_SN.SERIALNO
			 And ADD_SNINFO.STOCKID   = ADD_SN.STOCKID
			LEFT JOIN EXDC_AUTO_SERIALINFO
			  ON  EXDC_AUTO_SERIALINFO.MAPKEY_NO   = DM_EXDC_AUTOORD_CHECK.MAPKEY_NO
			 AND EXDC_AUTO_SERIALINFO.MAPKEY_LINE  = DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE
			 AND EXDC_AUTO_SERIALINFO.ISSUE_NO     = DM_EXDC_AUTOORD_CHECK.ISSUE_NO
			 AND EXDC_AUTO_SERIALINFO.SERIALNO     = ST_SNINFO.SERIALNO
			 AND EXDC_AUTO_SERIALINFO.CONVSERIALNO = ST_SNINFO.CONVSERIALNO
			 /* ――― CODE LIST 변환 JOIN 절 ――― */
			LEFT JOIN CM_CODE_STORER CD_STORAGETYPE
			       ON CD_STORAGETYPE.STORERKEY = MS_SKU.STORERKEY
			      AND CD_STORAGETYPE.CODELIST  = 'STORAGETYPE'
			      AND CD_STORAGETYPE.BASECODE  = MS_SKU.STORAGETYPE
			
			LEFT JOIN CM_CODE_STORER CD_MAPDIV
			       ON CD_MAPDIV.STORERKEY = DM_DOCUMENT_D.STORERKEY
			      AND CD_MAPDIV.CODELIST  = 'MAP_DIV'
			      AND CD_MAPDIV.BASECODE  = DM_EXDC_AUTOORD_CHECK.MAP_DIV
			
			LEFT JOIN CM_CODE_STORER CD_MOVE_FW
			       ON CD_MOVE_FW.STORERKEY = 'FW00'
			      AND CD_MOVE_FW.CODELIST  = 'EXDC_MOVE'
			      AND CD_MOVE_FW.BASECODE  = DM_EXDC_AUTOORD_CHECK.MOVE_YN
			
			LEFT JOIN CM_CODE_STORER CD_TEMP_FW
			       ON CD_TEMP_FW.STORERKEY = 'FW00'
			      AND CD_TEMP_FW.CODELIST  = 'TMEP_WEIGHT_STATUS'
			      AND CD_TEMP_FW.BASECODE  = DM_EXDC_AUTOORD_CHECK.TEMP_YN
			
			LEFT JOIN CM_CODE_STORER CD_STATUS
			       ON CD_STATUS.STORERKEY = DM_DOCUMENT_D.STORERKEY
			      AND CD_STATUS.CODELIST  = 'SERIAL_CFM_STATUS'
			      AND CD_STATUS.BASECODE  = TMP.SERIALINFO_CFM_YN
			
			LEFT JOIN CM_CODE_STORER CD_CONTYPE_SN
			       ON CD_CONTYPE_SN.STORERKEY = ST_SNINFO.STORERKEY
			      AND CD_CONTYPE_SN.CODELIST  = 'CONTRACTTYPE_SN'
			      AND CD_CONTYPE_SN.BASECODE  = ST_SNINFO.CONTRACTTYPE
		]]>
		<!-- ===== WHERE 파라미터 ===== -->
		WHERE DM_EXDC_AUTOORD_CHECK.MAPKEY_NO = #{mapkeyNo}
		  AND DM_EXDC_AUTOORD_CHECK.POKEY     = #{pokey}
		  AND DM_EXDC_AUTOORD_CHECK.ADD_YN    = 'N'
		  AND DM_DOCUMENT_D.POKEY             = #{pokey}
		  AND ST_SNINFO.POKEY                 = #{pokey}
		<if test="serialinfoCfmYn == '10'">
		    AND DM_EXDC_AUTOORD_CHECK.REAL_YN = 'R'
		    AND EXDC_AUTO_SERIALINFO.ISSUE_NO IS NOT NULL
		</if>
		<if test="serialinfoCfmYn == '20'">
		    AND DM_EXDC_AUTOORD_CHECK.REAL_YN = 'T'
		</if>
		<if test="serialinfoCfmYn == '30'">
		    AND DM_EXDC_AUTOORD_CHECK.REAL_YN = 'T'
		</if>
		<if test="serialinfoCfmYn == '40'">
		    AND DM_EXDC_AUTOORD_CHECK.REAL_YN = 'T'
		</if>
		<if test="serialinfoCfmYn == '50'">
		    AND DM_EXDC_AUTOORD_CHECK.REAL_YN = 'T'
		</if>
		<![CDATA[
		/* ===== GROUP BY (원문) ===== */
		GROUP BY DM_EXDC_AUTOORD_CHECK.MAPKEY_NO,
		         DM_EXDC_AUTOORD_CHECK.MAPKEY_LINE,
		         DM_EXDC_AUTOORD_CHECK.ISSUE_NO,
		         DM_EXDC_AUTOORD_CHECK.POKEY,
		         DM_EXDC_AUTOORD_CHECK.POLINE,
		         DM_DOCUMENT_D.MAPKEY_NO,
		         DM_DOCUMENT_D.MAPKEY_LINE,
		         DM_DOCUMENT_D.ISSUE_NO,
		         DP_INVOICE_SN.STOCKID,
		         DP_INPLAN.DCCODE,
		         DP_INPLAN.STORERKEY,
		         DP_INPLAN.DOCDT,
		         DP_INPLAN.DOCNO,
		         DP_INPLAN.DOCTYPE,
		         DP_INPLAN.SLIPDT,
		         DP_INPLAN.SLIPNO,
		         TMP.TMP_DPKEY,
		         DM_EXDC_AUTOORD_CHECK.DPKEY,
		         EXDC_AUTO_SERIALINFO.ISSUE_NO,
		         TMP.TMP_DPKEY,
		         DM_EXDC_AUTOORD_CHECK.DPKEY,
		         DM_EXDC_AUTOORD_CHECK.SOKEY
		]]>
		</select>
		
	<select id="getDataDetailTcsList" resultType="kpEXstorageMonitoringDetailTcsListResDto">
		 <![CDATA[
			SELECT /* [kpEXstorageMonitoringService.sqlx][getDataDetailTcsList][외부창고재고모티터링 Tcs 상세][ParkJinWoo][20250716] */
			       A.MAPKEY_NO                       AS MAPKEY_NO      /* 구매요청번호 */
			     , A.POKEY                           AS POKEY          /* 구매번호 */
			     , A.POLINE                          AS POLINE         /* 구매라인 */
			     , A.DELIVERYDATE                    AS DELIVERYDATE   /* 납품일 */
			     , B.SKU                             AS SKU            /* 상품코드 */
			     , MS_SKU.DESCRIPTION                AS SKUNAME        /* 상품명 */
			     , NVL(CD_STORAGETYPE.BASEDESCR , MS_SKU.STORAGETYPE)
			                                         AS STORAGETYPENAME/* 저장조건 */
			     , '('||MS_SKU.PLACEOFORIGIN||')'||
			       ( SELECT BASEDESCR
			           FROM CM_CODE
			          WHERE STORERKEY = MS_SKU.STORERKEY
			            AND CODELIST  = 'COUNTRY'
			            AND BASECODE  = MS_SKU.PLACEOFORIGIN
			            AND DEL_YN    = 'N' )        AS ORG            /* 원산지 */
			     , B.STOCKID                         AS STOCKID        /* 바코드 */
			     , ST_SNINFO.CONVSERIALNO            AS CONVSERIALNO   /* BL번호 */
			     , B.CONFIRMQTY                      AS ORDERQTY       /* 수량 */
			     , B.UOM                             AS UOM            /* 단위 */
			     , B.QCQTY                           AS ETCQTY         /* 박스수량 */
			     , MS_SKU.QTYPERBOX                  AS QTYPERBOX      /* 박스입수 */
			 FROM  DM_EXDC_AUTOORD_CHECK A
		        JOIN DM_DOCUMENT_D B
		          ON A.DPKEY = B.DOCNO
		         AND A.DPLINE = B.DOCLINE
		        JOIN DM_DOCUMENT_H C
		          ON     C.DCCODE          = B.DCCODE            
		          AND     C.STORERKEY        = B.STORERKEY            
		          AND     C.DOCDT            = B.DOCDT            
		          AND     C.DOCTYPE          = B.DOCTYPE                  
		          AND     C.DOCNO            = B.DOCNO           
		          AND    C.DELIVERYDATE     = B.DELIVERYDATE 
		          AND     C.DOCTYPE          = 'DP'    
		       LEFT OUTER JOIN MS_SKU 
		         ON B.STORERKEY = MS_SKU.STORERKEY
		        AND B.SKU       = MS_SKU.SKU   
		       LEFT OUTER JOIN ST_SNINFO 
		         ON B.STOCKID   = ST_SNINFO.STOCKID
		        AND B.SKU       = ST_SNINFO.SKU
		       LEFT JOIN CM_CODE_STORER CD_STORAGETYPE
		       ON CD_STORAGETYPE.STORERKEY = MS_SKU.STORERKEY
		      AND CD_STORAGETYPE.CODELIST  = 'STORAGETYPE'
		      AND CD_STORAGETYPE.BASECODE  = MS_SKU.STORAGETYPE
		    WHERE B.POKEY  = #{pokey}
		      AND B.POLINE = #{poLine}
		    ]]>
		    
	</select>
	
	<select id="getDataDetailTcsSubList" resultType="kpEXstorageMonitoringDetailTcsSubListResDto">
			<![CDATA[
		    SELECT	/* [kpEXstorageMonitoringService.sqlx][getDataDetailTcsSubList][외부창고재고모티터링 Tcs 서브 상세][ParkJinWoo][20250716] */ 
			       A.MAPKEY_NO                              AS MAPKEY_NO      /* 구매요청번호 */
			     , A.SOKEY                                  AS SOKEY          /* SO번호 */
			     , MAX(B.DOCLINE)                           AS DOCLINE        /* SO항번 */
			     , MAX(B.SKU)                               AS SKU            /* 상품코드 */
			     , MAX(MS_SKU.DESCRIPTION)                  AS SKUNAME        /* 상품명 */
			     , MAX( NVL(CD_STORAGETYPE.BASEDESCR , MS_SKU.STORAGETYPE) )
			                                              AS STORAGETYPENAME  /* 저장조건 */
			     , MAX('('||MS_SKU.PLACEOFORIGIN||')'||
			           ( SELECT BASEDESCR
			               FROM CM_CODE
			              WHERE STORERKEY = MS_SKU.STORERKEY
			                AND CODELIST  = 'COUNTRY'
			                AND BASECODE  = MS_SKU.PLACEOFORIGIN
			                AND DEL_YN    = 'N' ))           AS ORG           /* 원산지 */
			     , MAX(B.ORGANIZE)                          AS ORGANIZE       /* 창고코드 */
			     , MAX(( SELECT DESCRIPTION
			               FROM CM_DCXORGANIZE
			              WHERE ORGANIZE = B.ORGANIZE ))     AS ORGANIZENAME   /* 창고명 */
		      FROM DM_EXDC_AUTOORD_CHECK A
		      JOIN DM_DOCUMENT_D        B
		        ON A.SOKEY    = B.DOCNO
		       AND A.SOLINE   = B.DOCLINE
		       AND A.MAPKEY_NO= B.MAPKEY_NO
		      JOIN MS_SKU               MS_SKU
		        ON B.STORERKEY = MS_SKU.STORERKEY
		       AND B.SKU       = MS_SKU.SKU
		       /* ● CODE JOIN */
				LEFT JOIN CM_CODE_STORER CD_STORAGETYPE
				       ON CD_STORAGETYPE.STORERKEY = MS_SKU.STORERKEY
				      AND CD_STORAGETYPE.CODELIST  = 'STORAGETYPE'
				      AND CD_STORAGETYPE.BASECODE  = MS_SKU.STORAGETYPE
		     WHERE A.MAPKEY_NO = #{mapkeyNo}
		       AND A.SOKEY     IS NOT NULL
		  GROUP BY A.MAPKEY_NO, A.SOKEY
		    ]]>
		</select>	
		
		 <select id="getDataLocalDetailSubList" resultType="kpEXstorageMonitoringLocalDetailSubListResDto">
		    <![CDATA[
			    SELECT	/* [kpEXstorageMonitoringService.sqlx][getDataLocalDetailSubList][외부창고재고모티터링 로컬 상세 서브 상세][ParkJinWoo][20250716] */
			         MAX(A.MAPKEY_NO)                               AS MAPKEY_NO          /* 구매요청번호          */
			       , MAX(A.ISSUE_NO)                                AS ISSUE_NO           /* 이슈번호              */
			       , A.MAPKEY_LINE                                  AS MAPKEY_LINE        /* 구매요청항번          */
			       , A.SOKEY                                        AS SOKEY              /* SO번호               */
			       , MAX(A.SOLINE)                                  AS SOLINE             /* SO항번               */
			       , MAX(PO.SOKEY)                                  AS AD_SOKEY           /* 조정SO번호           */
			       , MAX(PO.SOLINE)                                 AS AD_SOLINE          /* 조정SO항번           */
			       , MAX(B.SERIALNO)                                AS ADD_SERIALNO       /* 조정이력             */
			       , MAX(B.ISSUE_NO)                                AS ADD_STOCKID        /* 조정바코드           */
			       , MAX(B.CONVSERIALNO)                            AS ADD_CONVSERIALNO   /* 조정BL               */
			       , MAX(CASE WHEN B.CONFIRM_YN='10' THEN '10'
			                  WHEN B.CONFIRM_YN='20' THEN '20' ELSE '40' END)
			                                                     AS SERIALINFO_CFM_YN     /* 처리확정여부         */
			       , MAX(MS_SKU.DURATION)                           AS ADD_DURATION       /* 기준일               */
			       , MAX(CASE WHEN NVL(ST_SNINFO.LOTTABLE01,'STD')='STD' THEN 'N'
			                  WHEN MONTHS_BETWEEN(
			                         TO_DATE(NVL(ST_SNINFO.LOTTABLE01,'STD'),'YYYY-MM-DD')
			                       , SYSDATE) > 3 THEN 'N' ELSE 'Y' END)
			                                                     AS AD_NEARDURATIONYN     /* 임박여부(조정)       */
			       , MAX(NVL(ST_SNINFO.LOTTABLE01,'STD'))          AS AD_LOTTABLE01       /* 조정LOT              */
			       , MAX(FN_LOTDURATION(B.STORERKEY
			                            ,MS_SKU.DURATIONTYPE
			                            ,MS_SKU.DURATION
			                            ,NVL(ST_SNINFO.LOTTABLE01,'STD')
			                            ,'N') || '/' || MS_SKU.DURATION)
			                                                     AS AD_DURATION_TERM      /* 조정유통기간         */
			       , MAX((SELECT FF.CONFIRMQTY
			                FROM DM_DOCUMENT_D FF
			               WHERE FF.DOCNO   = PO.SOKEY
			                 AND FF.DOCLINE = PO.SOLINE))        AS ADD_ORDERQTY          /* 조정수량             */
			       , MAX((SELECT FF.ETCQTY2
			                FROM DM_DOCUMENT_D FF
			               WHERE FF.DOCNO   = PO.SOKEY
			                 AND FF.DOCLINE = PO.SOLINE))        AS ADD_BOXQTY            /* 조정박스             */
			       , MAX(NVL(CD_STATUS.BASEDESCR , NVL(B.CONFIRM_YN,'40')))
			                                                     AS STATUS                /* 처리상태             */
			       , MAX(B.POKEY)                                 AS POKEY                /* 구매번호             */
			       , MAX(B.POLINE)                                AS POLINE               /* 구매라인             */
			       , MAX(PO.POKEY)                                AS ADDPOKEY             /* 조정구매번호         */
			       , MAX(PO.POLINE)                               AS ADDPOLINE            /* 조정구매라인         */
			       , MAX((SELECT FF.CONFIRMQTY
			                FROM DM_DOCUMENT_D FF
			               WHERE FF.DOCNO   = A.SOKEY
			                 AND FF.DOCLINE = A.SOLINE))        AS ORDERQTY               /* 수량                 */
			       , MAX((SELECT FF.UOM
			                FROM DM_DOCUMENT_D FF
			               WHERE FF.DOCNO   = A.SOKEY
			                 AND FF.DOCLINE = A.SOLINE))        AS UOM                    /* 단위                 */
			       , MAX((SELECT FF.ETCQTY2
			                FROM DM_DOCUMENT_D FF
			               WHERE FF.DOCNO   = A.SOKEY
			                 AND FF.DOCLINE = A.SOLINE))        AS ETCQTY                 /* 박스수량             */
			       , MAX(B.SKU)                                   AS SKU                  /* 상품코드             */
			       , MAX(MS_SKU.DESCRIPTION)                      AS SKUNAME              /* 상품명               */
			       , MAX(NVL(CD_STORAGETYPE.BASEDESCR , MS_SKU.STORAGETYPE))
			                                                     AS STORAGETYPENAME       /* 저장조건             */
			       , MAX('('||MS_SKU.PLACEOFORIGIN||')'||
			             (SELECT BASEDESCR
			                FROM CM_CODE
			               WHERE STORERKEY=MS_SKU.STORERKEY
			                 AND CODELIST ='COUNTRY'
			                 AND BASECODE =MS_SKU.PLACEOFORIGIN
			                 AND DEL_YN   ='N'))                 AS ORG                   /* 원산지               */
			       , MAX(B.TO_CUSTKEY)                            AS FROM_CUSTKEY         /* 출고처코드           */
			       , MAX(MS_CUST.DESCRIPTION)                     AS FROM_CUSTNAME        /* 출고처명             */
			       , MAX(NVL(CD_MAPDIV.BASEDESCR , A.MAP_DIV))    AS CONTRACTTYPE         /* 거래유형             */
			       , MAX('2170-'||B.ORGANIZE)                     AS ORGANIZE             /* 창고코드             */
			       , MAX((SELECT DESCRIPTION
			                FROM CM_DCXORGANIZE
			               WHERE ORGANIZE = '2170-'||B.ORGANIZE)) AS ORGANIZENAME         /* 창고명               */
			       , MAX(B.SERIALNO)                              AS SERIALNO             /* 최종이력             */
			       , MAX(B.ISSUE_NO)                              AS STOCKID              /* 최종바코드           */
			       , MAX(B.CONVSERIALNO)                          AS CONVSERIALNO         /* 최종BL               */
			       , MAX(MS_SKU.DURATION)                         AS DURATION             /* 기준유통기한         */
			       , MAX(CASE WHEN NVL(ST_SNINFO.LOTTABLE01,'STD')='STD' THEN 'N'
			                  WHEN MONTHS_BETWEEN(
			                         TO_DATE(NVL(ST_SNINFO.LOTTABLE01,'STD'),'YYYY-MM-DD')
			                       , SYSDATE) > 3 THEN 'N' ELSE 'Y' END)
			                                                     AS NEARDURATIONYN        /* 임박여부             */
			       , MAX(NVL(ST_SNINFO.LOTTABLE01,'STD'))         AS LOTTABLE01           /* LOT번호             */
			       , MAX(FN_LOTDURATION(B.STORERKEY,MS_SKU.DURATIONTYPE,MS_SKU.DURATION,
			                             NVL(ST_SNINFO.LOTTABLE01,'STD'),'N')
			            || '/' || MS_SKU.DURATION)               AS DURATION_TERM         /* 유통기간             */
			       , MAX(B.ORDR_QTY)                              AS ETCQTY2              /* 출고박스수량         */
			       , MAX(MS_SKU.QTYPERBOX)                        AS QTYPERBOX            /* 박스입수             */
			       , MAX(NVL(CD_MOVE_FW.BASEDESCR , A.MOVE_YN))   AS MOVE_YN              /* 이체여부             */
			       , MAX(NVL(CD_TEMP_FW.BASEDESCR , A.TEMP_YN))   AS TEMP_YN              /* 가중량여부           */
			       , MAX(B.REJECT_CODE)                           AS REJECT_REASON        /* 반려사유             */
			       , MAX(B.SEND_MEMO)                             AS SEND_MEMO            /* 확인사항             */
			  FROM  DM_EXDC_AUTOORD_CHECK A
			  LEFT JOIN EXDC_SCM_CFM_LOCAL B
			         ON A.MAPKEY_NO = B.MAPKEY_NO AND A.ISSUE_NO = B.ISSUE_NO
			  LEFT JOIN DM_EXDC_AUTOORD_CHECK PO
			         ON PO.ADD_YN='Y'
			        AND PO.MAPKEY_NO   = A.MAPKEY_NO
			        AND PO.MAPKEY_LINE = A.MAPKEY_LINE
			        AND PO.ISSUE_NO    = A.ISSUE_NO
			  JOIN MS_SKU MS_SKU
			        ON B.SKU = MS_SKU.SKU AND B.STORERKEY = MS_SKU.STORERKEY
			  LEFT JOIN MS_CUST MS_CUST
			        ON B.STORERKEY = MS_CUST.STORERKEY AND B.TO_CUSTKEY = MS_CUST.CUSTKEY
			  LEFT JOIN ST_SNINFO ST_SNINFO
			        ON ST_SNINFO.STOCKID = B.ISSUE_NO AND ST_SNINFO.SERIALNO = B.SERIALNO 			       
				/* ─── CODE LIST 변환 JOIN ─── */
				LEFT JOIN CM_CODE_STORER CD_STATUS
				       ON CD_STATUS.STORERKEY = B.STORERKEY
				      AND CD_STATUS.CODELIST  = 'SERIAL_CFM_STATUS'
				      AND CD_STATUS.BASECODE  = NVL(B.CONFIRM_YN,'40')
				
				LEFT JOIN CM_CODE_STORER CD_STORAGETYPE
				       ON CD_STORAGETYPE.STORERKEY = MS_SKU.STORERKEY
				      AND CD_STORAGETYPE.CODELIST  = 'STORAGETYPE'
				      AND CD_STORAGETYPE.BASECODE  = MS_SKU.STORAGETYPE
				
				LEFT JOIN CM_CODE_STORER CD_MAPDIV
				       ON CD_MAPDIV.STORERKEY = B.STORERKEY
				      AND CD_MAPDIV.CODELIST  = 'MAP_DIV'
				      AND CD_MAPDIV.BASECODE  = A.MAP_DIV
				
				LEFT JOIN CM_CODE_STORER CD_MOVE_FW
				       ON CD_MOVE_FW.STORERKEY = 'FW00'
				      AND CD_MOVE_FW.CODELIST  = 'EXDC_MOVE'
				      AND CD_MOVE_FW.BASECODE  = A.MOVE_YN
				
				LEFT JOIN CM_CODE_STORER CD_TEMP_FW
				       ON CD_TEMP_FW.STORERKEY = 'FW00'
				      AND CD_TEMP_FW.CODELIST  = 'TMEP_WEIGHT_STATUS'
				      AND CD_TEMP_FW.BASECODE  = A.TEMP_YN
			 WHERE B.MAPKEY_NO = #{mapkeyNo}
			   AND A.ADD_YN    = 'N'
			   AND A.SOKEY IS NOT NULL
			GROUP BY A.MAPKEY_NO, A.MAPKEY_LINE, A.ISSUE_NO, A.SOKEY
		    ]]>
  </select>
  
</mapper>