<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="tmClaimCarService">
	
	<select id="getDataHeaderlist"  resultType="TmClaimCarListResDto">
		SELECT /* [TmClaimCarService.sqlx][getDataHeaderlist][배송클레임정보조회][박진우][2025.08.07] */
		     '0'                                         AS CHECKYN           /* 체크여부 */
		    ,M1.DCCODE									AS fixDcCode
		    ,M1.SAPCLAIMNO                               AS VOCNO             /* VOC번호 */
		    ,M1.STORERKEY                                AS STORERKEY         /* 고객사코드 */
		    ,M1.DCCODE                                   AS DCCODE            /* 센터코드 */
		    ,'['||M1.DCCODE||']' || FN_DESCR_DC(M1.DCCODE) AS DCNAME          /* 센터명 */
		    ,M1.DELIVERYDT                               AS DELIVERYDT        /* 배송일자 */
		    ,M1.CARNO                                    AS CARNO             /* 차량번호 */
		    ,M1.CUSTKEY                                  AS CUSTKEY           /* 고객사키 */
		    ,M1.CUSTNAME                                 AS CUSTNAME          /* 고객사명 */
		    ,M1.OTHER04                                  AS CLAIM_DIV         /* 클레임구분 */
		    ,M1.MEMO                                     AS MEMO              /* 메모 */
		    ,M1.MANAME                                   AS MANAME            /* 담당자명 */
		    ,M1.WRITER                                   AS VOCNAME           /* 작성자명 */
		    ,M1.CLAIMDTLIDL                AS CLAIMDTLIDL  /*대분류*/
            ,M1.CLAIMDTLIDM                AS CLAIMDTLIDM  /*중분류*/
            ,M1.CLAIMDTLIDS                AS CLAIMDTLIDS /*소분류*/
            ,M1.CLAIMDTLID                 AS CLAIMDTLID /*세분류*/ 
            ,MAX(M1.CLAIMDTLIDLNM) 		  AS CLAIMDTLIDLNM
            ,MAX(M1.CLAIMDTLIDMNM) AS CLAIMDTLIDMNM
            ,MAX(M1.CLAIMDTLIDSNM) AS CLAIMDTLIDSNM
            ,MAX(M1.CLAIMDTLIDNM) AS CLAIMDTLIDNM
		    ,TO_CHAR(TO_DATE(M1.WRITEDATE , 'YYYYMMDDHH24:MI:SS'),'YYYY/MM/DD HH24:MI') AS VOCDT /* VOC작성일시 */
		    
		FROM (
		    SELECT
		         RT_CLAIMINFO.SAPCLAIMNO                 AS SAPCLAIMNO
		        ,RT_CLAIMINFO.STORERKEY                  AS STORERKEY
		        ,RT_CLAIMINFO.DCCODE                     AS DCCODE
		        ,RT_CLAIMINFO.SOURCEDT                   AS DELIVERYDT
		        
		        ,M.CARNO                                 AS CARNO
		        ,RT_CLAIMINFO.MNGPLC_ID                  AS CUSTKEY
		        ,M.CUSTNAME                              AS CUSTNAME
	            ,RT_CLAIMINFO.CLAIMDTLIDL                AS CLAIMDTLIDL
	            ,RT_CLAIMINFO.CLAIMDTLIDM                AS CLAIMDTLIDM
	            ,RT_CLAIMINFO.CLAIMDTLIDS                AS CLAIMDTLIDS
	            ,RT_CLAIMINFO.CLAIMDTLID                AS CLAIMDTLID 
		        ,FN_DESCR_CODESPEC(RT_CLAIMINFO.STORERKEY, 'CLAIMTYPE', 'L' ,RT_CLAIMINFO.CLAIMDTLIDL) AS OTHER04
		        ,RT_CLAIMINFO.MEMO                       AS MEMO
		        ,M.MANAME                                AS MANAME
		        ,RT_CLAIMINFO.WRITER                     AS WRITER
		        ,L.SPECDESCR							 AS CLAIMDTLIDLNM
		        ,M.SPECDESCR                             AS CLAIMDTLIDMNM
		        ,S.SPECDESCR		                 AS CLAIMDTLIDSNM	
		        ,D.SPECDESCR				 AS CLAIMDTLIDNM
		        <!-- ,RT_CLAIMINFO.CLAIMDTLIDS				 AS CLAIMDTLIDS -->
		        ,RT_CLAIMINFO.WRITEDATE || RT_CLAIMINFO.WRITETIME AS WRITEDATE
		    FROM RT_CLAIMINFO
		    JOIN CM_CODESPEC L
		      ON L.STORERKEY = RT_CLAIMINFO.STORERKEY
		     AND L.SPECCODE = RT_CLAIMINFO.CLAIMDTLIDL
		     AND L.CODELIST  = 'CLAIMTYPE'
		     AND L.BASECODE  = 'L'
		    JOIN CM_CODESPEC M
		      ON M.STORERKEY = RT_CLAIMINFO.STORERKEY
		     AND M.SPECCODE = RT_CLAIMINFO.CLAIMDTLIDM
		     AND M.CODELIST  = 'CLAIMTYPE'
		     AND M.BASECODE  = 'M'
		    JOIN CM_CODESPEC S
		      ON S.STORERKEY = RT_CLAIMINFO.STORERKEY
		      AND S.SPECCODE = RT_CLAIMINFO.CLAIMDTLIDS
		     AND S.CODELIST  = 'CLAIMTYPE'
		     AND S.BASECODE  = 'S'
		    JOIN CM_CODESPEC D
		      ON D.STORERKEY = RT_CLAIMINFO.STORERKEY
		      AND D.SPECCODE = RT_CLAIMINFO.CLAIMDTLID
		     AND D.CODELIST  = 'CLAIMTYPE'
		     AND D.BASECODE  = 'D' 
		    LEFT OUTER JOIN (
		        SELECT
		             TM_INPLAN.STORERKEY                    AS STORERKEY
		            ,TM_INPLAN.DCCODE                       AS DCCODE
		            ,TM_INPLAN.DELIVERYDT                   AS DELIVERYDT
		            ,TM_INPLAN.CUSTKEY                      AS CUSTKEY
		            ,MAX(MS_CUST.DESCRIPTION)               AS CUSTNAME
		            ,MAX(MS_CUST.EMPNAME1)                  AS MANAME
		            ,MAX(TM_INPLAN.CARNO)                   AS CARNO
		        FROM TM_INPLAN

		        JOIN MS_CUST
		          ON MS_CUST.STORERKEY = TM_INPLAN.STORERKEY
		         AND MS_CUST.CUSTKEY   = TM_INPLAN.CUSTKEY
		         AND MS_CUST.CUSTTYPE  = TM_INPLAN.CUSTTYPE
		        WHERE 1=1
		        <if test="fixDcCode != null and fixDcCode != ''">
		            <![CDATA[AND TM_INPLAN.DCCODE = #{fixDcCode}]]>
		        </if>
		        <if test="gStorerkey != null and gStorerkey != ''">
		            <![CDATA[AND TM_INPLAN.STORERKEY = #{gStorerkey}]]>
		        </if>
		        <if test="fromDeliverydt != null and fromDeliverydt != ''">
		            <![CDATA[AND TM_INPLAN.DELIVERYDT >= #{fromDeliverydt}]]>
		        </if>
		        <if test="toDeliverydt != null and toDeliverydt != ''">
		            <![CDATA[AND TM_INPLAN.DELIVERYDT <= #{toDeliverydt}]]>
		        </if>
		        <if test="multiToCustkey != null and multiToCustkey != ''">
		            <![CDATA[AND TM_INPLAN.CUSTKEY IN (
		                SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL))
		                  FROM (SELECT #{multiToCustkey} AS VAL FROM DUAL)
		                 CONNECT BY INSTR(VAL, ',', 1, LEVEL - 1) > 0
		            )]]>
		        </if>
		      
		        GROUP BY TM_INPLAN.STORERKEY
		                ,TM_INPLAN.DCCODE
		                ,TM_INPLAN.DELIVERYDT
		                ,TM_INPLAN.CUSTKEY
		    ) M
		      ON M.DCCODE     = RT_CLAIMINFO.DCCODE
		     AND M.CUSTKEY    = RT_CLAIMINFO.MNGPLC_ID
		     AND M.DELIVERYDT = RT_CLAIMINFO.SOURCEDT
		) M1
		WHERE 1 = 1
		<if test="fixDcCode != null and fixDcCode != ''">
		    <![CDATA[AND M1.DCCODE = #{fixDcCode}]]>
		</if>
		<if test="gStorerkey != null and gStorerkey != ''">
		    <![CDATA[AND M1.STORERKEY = #{gStorerkey}]]>
		</if>

		<if test="fromDeliverydt != null and fromDeliverydt != ''">
		    <![CDATA[AND M1.DELIVERYDT >= #{fromDeliverydt}]]>
		</if>
		<if test="toDeliverydt != null and toDeliverydt != ''">
		    <![CDATA[AND M1.DELIVERYDT <= #{toDeliverydt}]]>
		</if>
		<if test="fromdt != null and fromdt != ''">
		    <![CDATA[AND TO_CHAR(TO_DATE(M1.WRITEDATE , 'YYYYMMDDHH24:MI:SS'),'YYYYMMDD') >= #{fromdt}]]>
		</if>
		<if test="todt != null and todt != ''">
		    <![CDATA[AND TO_CHAR(TO_DATE(M1.WRITEDATE , 'YYYYMMDDHH24:MI:SS'),'YYYYMMDD') <= #{todt}]]>
		</if>
		<if test="claimtypeL != null and claimtypeL != ''">
		    <![CDATA[AND M1.CLAIMDTLIDL =#{claimtypeL}]]>
		</if>
		<if test="claimtypeM != null and claimtypeM != ''">
		    <![CDATA[AND M1.CLAIMDTLIDM =#{claimtypeM}]]>
		    </if>
				<if test="claimtypeS != null and claimtypeS != ''">
		    <![CDATA[AND M1.CLAIMDTLIDS =#{claimtypeS}]]>
		</if>
		<if test="claimtypeD != null and claimtypeD != ''">
		    <![CDATA[AND M1.CLAIMDTLID =#{claimtypeD}]]>
		</if>
		
		  <if test="multiCarno != null and multiCarno != ''">
		            <![CDATA[AND M1.CARNO IN (
		                SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL))
		                  FROM (SELECT #{multiCarno} AS VAL FROM DUAL)
		                 CONNECT BY INSTR(VAL, ',', 1, LEVEL - 1) > 0
		            )]]>
		        </if>
		<if test="multiToCustkey != null and multiToCustkey != ''">
		    <![CDATA[AND M1.CUSTKEY IN (
		        SELECT TRIM(REGEXP_SUBSTR(VAL, '[^,]+', 1, LEVEL))
		          FROM (SELECT #{multiToCustkey} AS VAL FROM DUAL)
		         CONNECT BY INSTR(VAL, ',', 1, LEVEL - 1) > 0
		    )]]>
		</if>
		      AND M1.CLAIMDTLID IN ('056','055','032','031','030','005')
		GROUP BY
		     M1.SAPCLAIMNO
            ,M1.STORERKEY
            ,M1.DCCODE
            ,M1.DELIVERYDT
            ,M1.CARNO
            ,M1.CUSTKEY
            ,M1.CUSTNAME
            ,M1.CLAIMDTLIDL             
            ,M1.CLAIMDTLIDM              
            ,M1.CLAIMDTLIDS              
            ,M1.CLAIMDTLID              
            ,M1.OTHER04
            ,M1.MEMO
            ,M1.MANAME
            ,M1.WRITER
            ,M1.WRITEDATE
            
  	</select>
  	
  	<select id="getClaimDtlList"  resultType="TmClaimCarClaimListResDto">
	  	SELECT /* [TmClaimCarService.sqlx][getDataHeaderlist][배송클레임세분류 조회][박진우][2025.08.07] */
	  		CM_CODESPEC.SPECCODE AS SPECCODE
			,CM_CODESPEC.SPECDESCR AS SPECDESCR
			,CM_CODESPEC.BASECODE  AS BASECODE
			, CM_CODESPEC.SPECCATEGORY AS SPECCATEGORY
	 	  FROM CM_CODESPEC
	 	 WHERE 1=1
	 	   AND STORERKEY =#{gStorerkey}
	 	   AND CODELIST = #{codeList}
	 	   AND BASECODE IN ('D','L','M','S')
	 	   AND DEL_YN = 'N'
	 	    AND SPECDESCR <![CDATA[<>]]> '중대 클레임'
  </select>
  <select id="getDataDtllist"
        resultType="TmClaimCarListDtlResDto">
<!-- SELECT /* [ifRtClaiminfoDMapper.xml][selectIfRtClaiminfoD][SAP 클레임 조치정보 조회][ParkJinWoo][20251227] */
               A.SERIALKEY          AS SERIALKEY          /* 일련번호 */
             , A.STORERKEY          AS STORERKEY          /* 고객사코드 */
             , A.SAPCLAIMNO         AS SAPCLAIMNO         /* SAP클레임번호 */
             , A.SAPCLAIMLINE       AS SAPCLAIMLINE       /* SAP클레임품목번호 */
             , A.CLAIM_SEQ          AS CLAIM_SEQ          /* 데이터번호 */
             , SUBSTR(A.ACTION_DATE, 1, 8) AS ACTION_DATE        /* 조치일시 */
             , A.ACTION_WHO         AS ACTION_WHO         /* 조치자명 */
             , A.ACTION_METHOD      AS ACTION_METHOD      /* 방법 */
             , A.ACTION_DESC        AS ACTION_DESC        /* 조치내용 */
             , A.ACTION_DETAIL_DESC AS ACTION_DETAIL_DESC /* 상세내용 */
             , A.RMK                AS RMK                /* 비고 */
             , A.ADDDATE            AS ADDDATE            /* 최초등록시간 */
             , A.EDITDATE           AS EDITDATE           /* 최종변경시간 */
             , A.ADDWHO             AS ADDWHO             /* 최초등록자 */
             , A.EDITWHO            AS EDITWHO            /* 최종변경자 */
             , USER1.USER_NM        AS ADDWHONAME         /* 등록자명 */
             , USER2.USER_NM        AS EDITWHONAME        /* 수정자명 */
  FROM RT_CLAIMINFO_D A
  LEFT JOIN FRAMEONE_USER USER1
         ON USER1.USER_ID <![CDATA[=]]> A.ADDWHO
  LEFT JOIN FRAMEONE_USER USER2
         ON USER2.USER_ID <![CDATA[=]]> A.EDITWHO
 WHERE 1 <![CDATA[=]]> 1
   AND A.SAPCLAIMNO <![CDATA[=]]> #{sapClaimNo}          /* SAP클레임번호 */ -->
   
   SELECT
        MAX(A.SERIALKEY)		 AS SERIALKEY
     ,  A.STORERKEY                 AS STORERKEY
     , A.SAPCLAIMNO                AS SAPCLAIMNO
     , SUBSTR(A.ACTION_DATE, 1, 8) AS ACTION_DATE
     , A.ACTION_WHO                AS ACTION_WHO
     , A.ACTION_METHOD             AS ACTION_METHOD
     , A.ACTION_DESC               AS ACTION_DESC
     , A.ACTION_DETAIL_DESC        AS ACTION_DETAIL_DESC
     , A.RMK
     , MAX(A.ADDDATE)              AS ADDDATE
     , MAX(A.EDITDATE) 				AS EDITDATE	
     , MAX(A.ADDWHO)			  AS ADDWHO
     , MAX (A.EDITWHO)			  AS EDITWHO
     , MAX(USER1.USER_NM)        AS ADDWHONAME         /* 등록자명 */
     , MAX(USER2.USER_NM)        AS EDITWHONAME        /* 수정자명 */
     , A.MOBILE_DISP_YN		 AS MOBILE_DISP_YN
  FROM RT_CLAIMINFO_D A
  JOIN (
        SELECT DISTINCT SAPCLAIMNO
          FROM RT_CLAIMINFO
         WHERE DCCODE =  #{fixDcCode}
       ) B
    ON B.SAPCLAIMNO = A.SAPCLAIMNO
      LEFT JOIN FRAMEONE_USER USER1
         ON USER1.USER_ID = A.ADDWHO
  LEFT JOIN FRAMEONE_USER USER2
         ON USER2.USER_ID= A.EDITWHO
   WHERE 1=1
     AND A.SAPCLAIMNO = #{sapClaimNo}  
 GROUP BY
       A.STORERKEY
     , A.SAPCLAIMNO
     , SUBSTR(A.ACTION_DATE, 1, 8)
     , A.ACTION_WHO
     , A.ACTION_METHOD
     , A.ACTION_DESC
     , A.ACTION_DETAIL_DESC
     , A.RMK
     , A.MOBILE_DISP_YN
     
</select>

<update id="updateIfRtClaiminfoD">
		<!-- UPDATE RT_CLAIMINFO_D A  
		   SET 
		       A.RMK                = #{rmk}               /* 비고 */
		     , A.EDITDATE           = SYSDATE              /* 최종변경시간 */ 
		     , A.EDITWHO            = #{gUserId}           /* 최종변경자 */
		     , A.MOBILE_DISP_YN     = #{mobileDispYn}      /* 모바일표시여부 */
		 WHERE 1 <![CDATA[=]]> 1
		   AND  A.CLAIM_SEQ IN (
					       SELECT B.CLAIM_SEQ
					         FROM RT_CLAIMINFO_D B
					        WHERE B.SERIALKEY = #{serialKey}
		 ) -->
		   UPDATE RT_CLAIMINFO_D A
   SET A.RMK            = #{rmk}          /* 비고 */
     , A.EDITDATE       = SYSDATE         /* 최종변경시간 */
     , A.EDITWHO        = #{gUserId}        /* 최종변경자 */
     , A.MOBILE_DISP_YN =#{mobileDispYn}  /* 모바일표시여부 */
 WHERE 1= 1
   AND EXISTS (
       SELECT 1
         FROM RT_CLAIMINFO_D B
        WHERE B.SERIALKEY = #{serialKey}
          AND A.STORERKEY          = B.STORERKEY
          AND A.SAPCLAIMNO         = B.SAPCLAIMNO
          AND SUBSTR(A.ACTION_DATE,1,8) = SUBSTR(B.ACTION_DATE,1,8)
          AND A.ACTION_WHO         = B.ACTION_WHO
          AND A.ACTION_METHOD      = B.ACTION_METHOD
          AND A.ACTION_DESC        = B.ACTION_DESC
          AND A.ACTION_DETAIL_DESC = B.ACTION_DETAIL_DESC
   )
		</update>
</mapper>