<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
    "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="tmTmapRouteMapper">

    <!-- ============================================
         T-map 경로 계산: DC 좌표 조회
         ============================================ -->
    <select id="selectDcCoordinate" resultType="java.util.HashMap">
        SELECT
            LATITUDE AS LATITUDE,
            LONGITUDE AS LONGITUDE
        FROM CM_DC
        WHERE DCCODE = #{dccode}
    </select>

    <!-- ============================================
         T-map 경로 계산: 고객 좌표 조회
         ============================================ -->
    <select id="selectCustomerCoordinates" resultType="java.util.HashMap">
        SELECT
    			DLVCUSTKEY AS TRUTHCUSTKEY,
    			LATITUDE AS LATITUDE,
    			LONGITUDE AS LONGITUDE
			
        FROM MS_CUSTDLVINFO
        WHERE DLVCUSTKEY IN
        <foreach collection="truthCustKeyList" item="key" open="(" separator="," close=")">
            #{key}
        </foreach>
          AND CUSTTYPE = 'C' 
   		  AND STORERKEY = 'FW00' 
          AND DLVCUSTKEY = TRUTHCUSTKEY 
    </select>

</mapper>
