package cjfw.batch.scm0320.saop;

import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;

import javax.xml.namespace.QName;
import java.net.URL;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebServiceClient(name = "SI_SCM0320_SCM_SOService",
                  wsdlLocation = "wsdl/SI_SCM0320_SCM_SOService.wsdl",
                  targetNamespace = "urn://scm.cjfreshway.co.kr/MM")
public class SISCM0320SCMSOService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn://scm.cjfreshway.co.kr/MM", "SI_SCM0320_SCM_SOService");
    public final static QName HTTPSPort = new QName("urn://scm.cjfreshway.co.kr/MM", "HTTPS_Port");
    public final static QName HTTPPort = new QName("urn://scm.cjfreshway.co.kr/MM", "HTTP_Port");
    static {
        URL url = SISCM0320SCMSOService.class.getResource("wsdl/SI_SCM0320_SCM_SOService.wsdl");
        if (url == null) {
            url = SISCM0320SCMSOService.class.getClassLoader().getResource("wsdl/SI_SCM0320_SCM_SOService.wsdl");
        }
        if (url == null) {
            java.util.logging.Logger.getLogger(SISCM0320SCMSOService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "wsdl/SI_SCM0320_SCM_SOService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SISCM0320SCMSOService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SISCM0320SCMSOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SISCM0320SCMSOService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SISCM0320SCMSOService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SISCM0320SCMSOService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SISCM0320SCMSOService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SISCM0320SCMSO
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISCM0320SCMSO getHTTPSPort() {
        return super.getPort(HTTPSPort, SISCM0320SCMSO.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISCM0320SCMSO
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SISCM0320SCMSO getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, SISCM0320SCMSO.class, features);
    }


    /**
     *
     * @return
     *     returns SISCM0320SCMSO
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISCM0320SCMSO getHTTPPort() {
        return super.getPort(HTTPPort, SISCM0320SCMSO.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SISCM0320SCMSO
     */
    @WebEndpoint(name = "HTTP_Port")
    public SISCM0320SCMSO getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, SISCM0320SCMSO.class, features);
    }

}
