<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="pushSendBatchService">
	<select id="selectPush" resultType="cjfw.batch.shr0250.PushSendParamsDto">
        SELECT SERIALKEY
             , RECEIVEPHONE
             , SENDMESSAGE
             , RECEIVEGROUP
             , RECEIVENAME
          FROM MG_SMSMMSSEND
         WHERE 1=1
           AND MESSAGETYPE = 'PUSH'
           AND STATUS      = '00'
    </select>

    <select id="updatePush" parameterType="cjfw.batch.shr0250.PushSendParamsDto">
        UPDATE MG_SMSMMSSEND
           SET STATUS   = #{STATUS}
             , IF_MEMO  = SUBSTRB(#{IF_MEMO}, 1, 1000) <!-- COLUMN SIZE 200 ▶ 1024 변경됨 (*20260108) -->
             , IF_FLAG  = ''
             , EDITWHO  = 'LOGISONEBATCH'
             , EDITDATE = SYSDATE
             , IF_DATE  = SYSDATE
         WHERE 1=1
           AND SERIALKEY = #{SERIALKEY}
  </select>
</mapper>