<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="dailyInoutService">
    <sql id="procedureParams">
          #{AVC_SYSTEM,     mode=IN, jdbcType=VARCHAR}
        , #{AVC_EXECUTEMODE,mode=IN, jdbcType=VARCHAR}
        , #{AVC_COMMAND,    mode=IN, jdbcType=VARCHAR}
        , #{AVC_DCCODE,     mode=IN, jdbcType=VARCHAR}
        , #{AVC_STORERKEY,  mode=IN, jdbcType=VARCHAR}
        , #{AVC_ORGANIZE,   mode=IN, jdbcType=VARCHAR}
        , #{AVC_AREA,       mode=IN, jdbcType=VARCHAR}
        , #{AVC_REQUESTCODE,mode=IN, jdbcType=VARCHAR}
        , #{AVC_REQUESTMSG, mode=IN, jdbcType=VARCHAR}
        , #{AVC_WORKER,     mode=IN, jdbcType=VARCHAR}
        , #{AVC_SECURITYKEY,mode=IN, jdbcType=VARCHAR}
        , #{AI_SPID,        mode=IN, jdbcType=INTEGER}
        , #{I_ERR,          mode=INOUT, jdbcType=INTEGER}
        , #{VC_RESULTMSG,   mode=INOUT, jdbcType=VARCHAR}
        , #{VC_RETURNMSG,   mode=INOUT, jdbcType=VARCHAR}
        , AVC_LOG_PARAMS => #{AVC_LOG_PARAMS, mode=IN, jdbcType=VARCHAR} /*(20250821) BATCH LOG관련 PARAMS.*/	
    </sql>
    <select id="callProcExecute" statementType="CALLABLE" parameterType="BatchParamsUtil" resultType="BatchParamsUtil" timeout="6000">
        { CALL SPST_DAILYINOUT.EXECUTE( /* [dailyInoutService.sqlx][callProcExecute][수불 일괄 재생성][김환수][20250801] */
               <include refid="procedureParams"/>
        ) }
    </select>
</mapper>