<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="exdcSendNoticeService">
    <sql id="procedureParams">
        #{AVC_IFID,       mode=IN, jdbcType=VARCHAR}
      , #{AVC_IFRESULT,   mode=OUT, jdbcType=VARCHAR}
    </sql>
    
    <select id = "sendNotice" statementType="CALLABLE" timeout="12000">
        { CALL SPIF_RECEIVEDATA_EXDC.P_IF_EXDC_SEND_NOTICE( /* [exdcSendNoticeService.sqlx][sendNotice][외부창고 입,출고 알람 처리][sunho.kim][20260210] */
               <include refid="procedureParams"/>
        ) }
    </select> 
</mapper>