<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="wdClaimInfoVSRService">
    <sql id="procedureParams">
        #{AVC_IFID,       mode=IN, jdbcType=VARCHAR}
      , #{AVC_IFRESULT,   mode=OUT, jdbcType=VARCHAR}
    </sql>
    
      <select id = "saveClaiminfoVSR" statementType="CALLABLE" timeout="12000">
        { CALL SPIF_RECEIVEDATA_RT.P_IF_RT_CLAIMINFO_VSR( /* [wdClaimInfoDetailService.sqlx][saveClaiminfoDetail][클레임조치이력 저장][박요셉][20251014] */
               <include refid="procedureParams"/>
        ) }
    </select> 
</mapper>