<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="cmDcManagerService">

	<select id="getMasterList" resultType="CmDcManagerResDto">			
        SELECT /* [cmDcManagerService.sqlx][cmDcManagerService.getMasterList][물류센터 기준정보 조회 (목록)][jangjaehyun][20250717] */
	    	   CM_DC.SERIALKEY               	    AS SERIALKEY      /* 데이터번호 */               
              ,CM_DC.DCCODE                         AS DCCODE         /* 센터코드 */
              ,CM_DC.DCNAME                         AS DCNAME         /* 센터명 */
              ,CM_DC.DCTYPE                         AS DCTYPE         /* 거래처 유형 */
              ,CM_DC.VATNO                          AS VATNO          /* 사업자 등록 등록번호 */
              ,CM_DC.STATUS                         AS STATUS         /* 상태 */
              ,CM_DC.DEL_YN                         AS DEL_YN         /* 삭제여부 */
              ,'['||CM_DC.DCCODE||']'||CM_DC.DCNAME AS DCNAME_DESCR
              ,CM_DC.SMS_YN                         AS SMS_YN         /* SMS관리여부 */
              ,CM_DC.ADDDATE                        AS ADDDATE        /* 최초등록시간 */
              ,CM_DC.EDITDATE                       AS EDITDATE       /* 최종변경시간 */
              ,CM_DC.ADDWHO                         AS ADDWHO         /* 최초등록자 */
              ,CM_DC.EDITWHO                        AS EDITWHO        /* 최종변경자 */
              ,CM_DC.ARRORD                         AS ARRORD         /* 정렬순서 */
              ,CM_DC.DISPLAY_YN                     AS DISPLAY_YN     /* 노출여부 */
              ,CM_DC.ROLLTAINER_WEIGHT              AS ROLLTAINER_WEIGHT /* 롤테이너 중량 */
              ,CM_DC.ROLLTAINER_CUBE                AS ROLLTAINER_CUBE   /* 롤테이너 체적 */              
              ,USER1.USER_NM AS ADDWHO_NM  /*등록자명*/
			  ,USER2.USER_NM AS EDITWHO_NM  /*수정자명*/
        FROM   CM_DC
        LEFT JOIN FRAMEONE_USER USER1 ON USER1.USER_ID = CM_DC.ADDWHO  /*등록자명*/
        LEFT JOIN FRAMEONE_USER USER2 ON USER2.USER_ID = CM_DC.EDITWHO  /*수정자명*/
        WHERE  1=1
          AND  CM_DC.DEL_YN = 'N'
          AND (CM_DC.REAL_DC_YN <![CDATA[<>]]> 'N' OR CM_DC.REAL_DC_YN IS NULL) /* 실센터여부 */
        <if test='multiDcCode != null and multiDcCode.length > 0'>
		   AND CM_DC.DCCODE IN
	        <foreach collection="multiDcCode" item="dccodeItem" open="(" separator="," close=")">
	            #{dccodeItem}
	        </foreach>
		</if>
		ORDER BY CM_DC.ARRORD
    </select>
    
    <select id="getDetail" resultType="CmDcManagerResDto">
		SELECT /* [cmDcManagerService.sqlx][cmDcManagerService.getDetail][물류센터 기준정보 조회 (단건)][jangjaehyun][20250717] */
  	    	   CM_DC.SERIALKEY               	   AS SERIALKEY      /* 데이터번호 */
              ,CM_DC.DCCODE                        AS DCCODE         /* 센터코드 */
              ,CM_DC.DCNAME                        AS DCNAME         /* 센터명 */
              ,CM_DC.CONN_SERVER                   AS CONN_SERVER    /* 접속서버 */
              ,CM_DC.CONN_DB                       AS CONN_DB        /* 접속데이터베이스 */
              ,CM_DC.CONN_TYPE                     AS CONN_TYPE      /* 접속유형 */
              ,CM_DC.DCTYPE                        AS DCTYPE         /* 거래처 유형 */
              ,CM_DC.BILLTOCUSTKEY                 AS BILLTOCUSTKEY  /* 대금청구거래처 실배송이 아닌 대금 청구 거래처 */
              ,CM_DC.DESCRIPTION                   AS DESCRIPTION    /* 거래처명 */
              ,CM_DC.DCGROUP                       AS DCGROUP        /* 거래처그룹 */
              ,CM_DC.PRIORITY                      AS PRIORITY       /* 우선순위 */
              ,CM_DC.DISTRICTTYPE                  AS DISTRICTTYPE   /* 권역구분 */
              ,CM_DC.DISTRICTCODE                  AS DISTRICTCODE   /* 권역코드 */
              ,CM_DC.ROUTE                         AS ROUTE          /* 경유지 */
              ,CM_DC.COURIER                       AS COURIER        /* 기본배송택배사 */
              ,CM_DC.INVOICETYPE                   AS INVOICETYPE    /* 기본운송장유형 */
              ,CM_DC.DLV_DCCODE                    AS DLV_DCCODE     /* 주출고처 */
              ,CM_DC.OWNER                         AS OWNER          /* 사업주명 */
              ,CM_DC.COUNTRY                       AS COUNTRY        /* 국가코드 */
              ,CM_DC.STATE                         AS STATE          /* 주,도 */
              ,CM_DC.CITY                          AS CITY           /* 시,읍,면 */
              ,CM_DC.ZIPCODE                       AS ZIPCODE        /* 우편번호 */
              ,CM_DC.ADDRESS1                      AS ADDRESS1       /* 기본주소 */
              ,CM_DC.ADDRESS2                      AS ADDRESS2       /* 상세주소 */
              ,DAMO.DEC(CM_DC.PHONE1)              AS PHONE1         /* 전화번호1 */
              ,DAMO.DEC(CM_DC.PHONE2)              AS PHONE2         /* 전화번호2 */
              ,CM_DC.FAX                           AS FAX            /* 팩스번호 */
              ,CM_DC.VATNO                         AS VATNO          /* 사업자 등록 등록번호 */
              ,CM_DC.VATOWNER                      AS VATOWNER       /* 사업자 등록 사업주명 */
              ,CM_DC.VATTYPE                       AS VATTYPE        /* 사업자 등록 업태 */
              ,CM_DC.VATCATEGORY                   AS VATCATEGORY    /* 사업자 등록 종목 */
              ,CM_DC.VATADDRESS1                   AS VATADDRESS1    /* 사업자 등록 기본주소 */
              ,CM_DC.VATADDRESS2                   AS VATADDRESS2    /* 사업자 등록 상세주소 */
              ,CM_DC.VATPHONE                      AS VATPHONE       /* 사업자 등록 전화번호 */
              ,CM_DC.VATFAX                        AS VATFAX         /* 사업자 등록 팩스번호 */
              ,CM_DC.EMPNAME1                      AS EMPNAME1       /* 관리 사원명1 */
              ,CM_DC.EMPNAME2                      AS EMPNAME2       /* 관리 사원명2 */
              ,CM_DC.EMPPHONE1                     AS EMPPHONE1      /* 관리 사원 전화번호1 */
              ,CM_DC.EMPPHONE2                     AS EMPPHONE2      /* 관리 사원 전화번호2 */
              ,CM_DC.STARTDATE                     AS STARTDATE      /* 거래 시작 일자 */
              ,CM_DC.ENDDATE                       AS ENDDATE        /* 거래 종료 일자 */
              ,CM_DC.OPENTIME                      AS OPENTIME       /* 업무 시작 시간(24hr  2300) */
              ,CM_DC.CLOSINGTIME                   AS CLOSINGTIME    /* 업무 종료 시간(24hr  2300) */
              ,CM_DC.FLOATMASK                     AS FLOATMASK      /* 기본표시FLOATMASK */
              ,CM_DC.MEMO                          AS MEMO           /* 기타사항 */
              ,CM_DC.IFFILENAME                    AS IFFILENAME     /* 인터페이스파일명 */
              ,CM_DC.STATUS                        AS STATUS         /* 상태 */
              ,CM_DC.DEL_YN                        AS DEL_YN         /* 삭제여부 */
              ,CM_DC.ADDDATE                       AS ADDDATE        /* 최초등록시간 */
              ,CM_DC.EDITDATE                      AS EDITDATE       /* 최종변경시간 */
              ,CM_DC.ADDWHO                        AS ADDWHO         /* 최초등록자 */
              ,CM_DC.EDITWHO                       AS EDITWHO        /* 최종변경자 */
              ,CM_DC.SMS_YN                        AS SMS_YN         /* SMS관리여부 */
              ,CM_DC.ARRORD                        AS ARRORD         /* 정렬순서 */              
              ,CM_DC.PROC_STORAGE_ARRIVEDTIME      AS PROC_STORAGE_ARRIVEDTIME /* 조달저장도착시간 */
              ,CM_DC.PROC_SAMEDAY_ARRIVEDTIME      AS PROC_SAMEDAY_ARRIVEDTIME /* 조달일배도착시간 */
              ,CM_DC.PROC_STORAGE_INTIME           AS PROC_STORAGE_INTIME /* 조달저장입차시간 */
              ,CM_DC.PROC_SAMEDAY_INTIME           AS PROC_SAMEDAY_INTIME /* 조달일배입차시간 */
              ,CM_DC.LATITUDE                      AS LATITUDE       /* 위도 */
              ,CM_DC.LONGITUDE                     AS LONGITUDE      /* 경도 */
              ,CM_DC.REAL_DC_YN                    AS REAL_DC_YN     /* 실센터여부 */
              ,CM_DC.DISPLAY_YN                    AS DISPLAY_YN     /* 노출여부 */
              ,CM_DC.ROLLTAINER_WEIGHT             AS ROLLTAINER_WEIGHT /* 롤테이너 중량 */
              ,CM_DC.ROLLTAINER_CUBE               AS ROLLTAINER_CUBE   /* 롤테이너 체적 */
              ,CM_DC.RADIUS                        AS RADIUS /* 반경 */
              ,CM_DC.STYTIME                       AS STYTIME   /* 체류시간 */
        FROM   CM_DC
        WHERE  1=1
        <if test='dcCode != null and dcCode != ""'>
		  AND CM_DC.DCCODE = #{dcCode}
		</if>
    </select>
    
    <insert id="insertMaster">
	    INSERT /* [cmDcManagerService.sqlx][cmDcManagerService.insert][물류센터 기준정보 INSERT][jangjaehyun][20250717] */
	      INTO CM_DC
	         ( DCCODE, DCNAME, CONN_SERVER, CONN_DB, CONN_TYPE,
	           DCTYPE, BILLTOCUSTKEY, DESCRIPTION, DCGROUP, PRIORITY,
	           DISTRICTTYPE, DISTRICTCODE, ROUTE, COURIER, INVOICETYPE,
	           DLV_DCCODE, OWNER, COUNTRY, STATE, CITY,
	           ZIPCODE, ADDRESS1, ADDRESS2, PHONE1, PHONE2,
	           FAX, VATNO, VATOWNER, VATTYPE, VATCATEGORY,
	           VATADDRESS1, VATADDRESS2, VATPHONE, VATFAX, EMPNAME1,
	           EMPNAME2, EMPPHONE1, EMPPHONE2, STARTDATE, ENDDATE,
	           OPENTIME, CLOSINGTIME, FLOATMASK, MEMO, IFFILENAME,
	           DEL_YN, STATUS, ADDWHO, EDITWHO, SMS_YN, ARRORD, 
	           PROC_STORAGE_ARRIVEDTIME, PROC_SAMEDAY_ARRIVEDTIME, PROC_STORAGE_INTIME, PROC_SAMEDAY_INTIME, LATITUDE, LONGITUDE, REAL_DC_YN, DISPLAY_YN,
	           ROLLTAINER_WEIGHT, ROLLTAINER_CUBE, RADIUS, STYTIME
	         )
	    VALUES
	         ( #{dcCode},        /* 센터코드 */
	           #{dcName},        /* 센터명 */
	           #{connServer},    /* 접속서버 */
	           #{connDb},        /* 접속데이터베이스 */
	           #{connType},      /* 접속유형 */
	           #{dcType},        /* 거래처 유형 */
	           #{billToCustKey}, /* 대금청구거래처 */
	           #{description},   /* 거래처명 */
	           #{dcGroup},       /* 거래처그룹 */
	           #{priority},      /* 우선순위 */
	           #{districtType},  /* 권역구분 */
	           #{districtCode},  /* 권역코드 */
	           #{route},         /* 경유지 */
	           #{courier},       /* 기본배송택배사 */
	           #{invoiceType},   /* 기본운송장유형 */
	           #{dlvDcCode},     /* 주출고처 */
	           #{owner},         /* 사업주명 */
	           #{country},       /* 국가코드 */
	           #{state},         /* 주,도 */
	           #{city},          /* 시,읍,면 */
	           #{zipCode},       /* 우편번호 */
	           #{address1},      /* 기본주소 */
	           #{address2},      /* 상세주소 */
	           #{phone1},        /* 전화번호1 */
	           #{phone2},        /* 전화번호2 */
	           #{fax},           /* 팩스번호 */
	           #{vatNo},         /* 사업자 등록 등록번호 */
	           #{vatOwner},      /* 사업자 등록 사업주명 */
	           #{vatType},       /* 사업자 등록 업태 */
	           #{vatCategory},   /* 사업자 등록 종목 */
	           #{vatAddress1},   /* 사업자 등록 기본주소 */
	           #{vatAddress2},   /* 사업자 등록 상세주소 */
	           #{vatPhone},      /* 사업자 등록 전화번호 */
	           #{vatFax},        /* 사업자 등록 팩스번호 */
	           #{empName1},      /* 관리 사원명1 */
	           #{empName2},      /* 관리 사원명2 */
	           #{empPhone1},     /* 관리 사원 전화번호1 */
	           #{empPhone2},     /* 관리 사원 전화번호2 */
	           #{startDate},     /* 거래 시작 일자 */
	           #{endDate},       /* 거래 종료 일자 */
	           #{openTime},      /* 업무 시작 시간 */
	           #{closingTime},   /* 업무 종료 시간 */
	           NVL(#{floatMask},'##,####0'), /* 기본표시FLOATMASK */
	           #{memo},          /* 기타사항 */
	           #{ifFileName},    /* 인터페이스파일명 */
	           NVL(#{delYn},'N'), /* 삭제여부 */
	           NVL(#{ifFileName},'00'), /* 상태*/
	           #{gUserId},       /* 최초등록자 */
	           #{gUserId},       /* 최종변경자 */
	           NVL(#{smsYn},'N'),/* SMS관리여부 */
	           #{arrOrd},        /* 정렬순서 */
	           #{procStorageArrivedtime}, /* 조달저장도착시간 */
	           #{procSamedayArrivedtime}, /* 조달일배도착시간 */
	           #{procStorageIntime}, /* 조달저장입차시간 */
	           #{procSamedayIntime}, /* 조달일배입차시간 */
	           #{latitude},      /* 위도 */
	           #{longitude},     /* 경도 */
	           #{realDcYn},      /* 실센터여부 */
	           #{displayYn},     /* 노출여부 */
	           #{rolltainerWeight}, /* 롤테이너 중량 */
	           #{rolltainerCube},    /* 롤테이너 체적 */
	           #{radius},       /* 반경 */
	           #{stytime}       /* 체류시간 */
	         )
	</insert>
	
	<update id="updateMaster">
	    UPDATE /* [cmDcManagerService.sqlx][cmDcManagerService.update][물류센터 기준정보 UPDATE][jangjaehyun][20250717] */
	           CM_DC
	       SET 
	       	   <!-- DCNAME        = #{dcName},        /* 센터명 */
	           CONN_SERVER   = #{connServer},    /* 접속서버 */
	           CONN_DB       = #{connDb},        /* 접속데이터베이스 */
	           CONN_TYPE     = #{connType},      /* 접속유형 */
	           DCTYPE        = #{dcType},        /* 거래처 유형 */
	           BILLTOCUSTKEY = #{billToCustKey}, /* 대금청구거래처 */
	           DESCRIPTION   = #{description},   /* 거래처명 */
	           DCGROUP       = #{dcGroup},       /* 거래처그룹 */
	           PRIORITY      = #{priority},      /* 우선순위 */
	           DISTRICTTYPE  = #{districtType},  /* 권역구분 */
	           DISTRICTCODE  = #{districtCode},  /* 권역코드 */
	           ROUTE         = #{route},         /* 경유지 */
	           COURIER       = #{courier},       /* 기본배송택배사 */
	           INVOICETYPE   = #{invoiceType},   /* 기본운송장유형 */
	           DLV_DCCODE    = #{dlvDcCode},     /* 주출고처 */
	           OWNER         = #{owner},         /* 사업주명 */
	           COUNTRY       = #{country},       /* 국가코드 */
	           STATE         = #{state},         /* 주,도 */
	           CITY          = #{city},          /* 시,읍,면 */
	           ZIPCODE       = #{zipCode},       /* 우편번호 */
	           ADDRESS1      = #{address1},      /* 기본주소 */
	           ADDRESS2      = #{address2},      /* 상세주소 */
	           PHONE1        = #{phone1},        /* 전화번호1 */
	           PHONE2        = #{phone2},        /* 전화번호2 */
	           FAX           = #{fax},           /* 팩스번호 */
	           VATNO         = #{vatNo},         /* 사업자 등록 등록번호 */
	           VATOWNER      = #{vatOwner},      /* 사업자 등록 사업주명 */
	           VATTYPE       = #{vatType},       /* 사업자 등록 업태 */
	           VATCATEGORY   = #{vatCategory},   /* 사업자 등록 종목 */
	           VATADDRESS1   = #{vatAddress1},   /* 사업자 등록 기본주소 */
	           VATADDRESS2   = #{vatAddress2},   /* 사업자 등록 상세주소 */
	           VATPHONE      = #{vatPhone},      /* 사업자 등록 전화번호 */
	           VATFAX        = #{vatFax},        /* 사업자 등록 팩스번호 */
	           EMPNAME1      = #{empName1},      /* 관리 사원명1 */
	           EMPNAME2      = #{empName2},      /* 관리 사원명2 */
	           EMPPHONE1     = #{empPhone1},     /* 관리 사원 전화번호1 */
	           EMPPHONE2     = #{empPhone2},     /* 관리 사원 전화번호2 */
	           STARTDATE     = #{startDate},     /* 거래 시작 일자 */
	           ENDDATE       = #{endDate},       /* 거래 종료 일자 */
	           OPENTIME      = #{openTime},      /* 업무 시작 시간 */
	           CLOSINGTIME   = #{closingTime},   /* 업무 종료 시간 */
	           FLOATMASK     = #{floatMask},     /* 기본표시FLOATMASK */
	           MEMO          = #{memo},          /* 기타사항 */
	           IFFILENAME    = #{ifFileName},    /* 인터페이스파일명 */
	           STATUS        = NVL(#{status},'00'), /* 상태 */
	           DEL_YN        = NVL(#{delYn},'N'), /* 삭제여부 */	           
	           SMS_YN        = NVL(#{smsYn},'N'), /* SMS관리여부 */ -->
	           EDITDATE      = SYSDATE,           /* 최종변경시간 */
	           EDITWHO       = #{gUserId},        /* 최종변경자 */
	           ARRORD        = #{arrOrd},         /* 정렬순서 */	           
	           PROC_STORAGE_ARRIVEDTIME = #{procStorageArrivedtime}, /* 조달저장도착시간 */
	           PROC_SAMEDAY_ARRIVEDTIME = #{procSamedayArrivedtime}, /* 조달일배도착시간 */
	           PROC_STORAGE_INTIME = #{procStorageIntime}, /* 조달저장입차시간 */
	           PROC_SAMEDAY_INTIME = #{procSamedayIntime}, /* 조달일배입차시간 */
	           LATITUDE      = #{latitude},      /* 위도 */
	           LONGITUDE     = #{longitude},     /* 경도 */
	           REAL_DC_YN    = #{realDcYn},      /* 실센터여부 */
	           DISPLAY_YN    = NVL(#{displayYn},'Y'), /* 노출여부 */
	           ROLLTAINER_WEIGHT = #{rolltainerWeight}, /* 롤테이너 중량 */
	           ROLLTAINER_CUBE   = #{rolltainerCube},    /* 롤테이너 체적 */
	           RADIUS       = #{radius},       /* 반경 */
	           STYTIME      = #{stytime}       /* 체류시간 */
	     WHERE SERIALKEY     = #{serialKey}
	</update>
    
</mapper>