<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="cmIssuePicturePopupService">

	<select id="getMasterList" resultType="CmIssuePicturePopupResDto">
		SELECT DISTINCT    /* [cmIssuePicturePopupService.sqlx][getMasterList][배송이슈 사진 파일 조회][sunho.kim][2026.02.20] */
		      VW_TM_INPLAN_ALL.DCCODE                 AS DCCODE
		    , VW_TM_INPLAN_ALL.DELIVERYDT             AS DELIVERYDT
		    , VW_TM_INPLAN_ALL.CUSTTYPE               AS CUSTTYPE
		    , VW_TM_INPLAN_ALL.TRUTHCUSTKEY           AS TRUTHCUSTKEY
		    , VW_TM_INPLAN_ALL.CARNO                  AS CARNO
		    , VW_TM_INPLAN_ALL.PRIORITY               AS PRIORITY
		    , TM_ISSUE_FILE.FILE_NAME                 AS FILENAME
		    , TM_ISSUE_FILE.FILE_LOCATION             AS FILELOCATION
		FROM VW_TM_INPLAN_ALL
		LEFT JOIN TM_ISSUE
		    ON  TM_ISSUE.CUSTKEY    = VW_TM_INPLAN_ALL.TRUTHCUSTKEY
		    AND TM_ISSUE.DELIVERYDT = VW_TM_INPLAN_ALL.DELIVERYDT
		    AND TM_ISSUE.PRIORITY   = VW_TM_INPLAN_ALL.PRIORITY
		    AND TM_ISSUE.CARNO      = VW_TM_INPLAN_ALL.CARNO
		LEFT JOIN TM_ISSUE_FILE
		    ON  TM_ISSUE_FILE.ISSUENO = TM_ISSUE.ISSUENO
		WHERE VW_TM_INPLAN_ALL.DCCODE       = #{dccode}
		  AND VW_TM_INPLAN_ALL.DELIVERYDT   <![CDATA[=]]> #{deliverydt}
		  AND VW_TM_INPLAN_ALL.TRUTHCUSTKEY = #{truthcustkey} 
		  AND VW_TM_INPLAN_ALL.CARNO        = #{carno}
		  AND VW_TM_INPLAN_ALL.PRIORITY     = #{priority}
		  AND TM_ISSUE_FILE.FILE_NAME IS NOT NULL
    </select>
 
</mapper>