package cjfw.wms.sys.entity;

import cjfw.wms.common.extend.CommonTriggerDto;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Copyright 2025. CJ OliveNetworks Co. all rights reserved.
 * @author      : Generated by GitHub Copilot
 * @date        : 2025.08.21
 * @description : 라벨 다국어 Entity
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "라벨 다국어 Entity")
public class SysLabelLangEntity extends CommonTriggerDto {
    /** 시스템구분 */
    @Schema(description = "시스템구분", maxLength = 10)
    private String systemCl;

    /** 라벨코드 */
    @Schema(description = "라벨코드", maxLength = 256)
    private String labelCd;

    /** 라벨명 */
    @Schema(description = "라벨명", maxLength = 200)
    private String labelNm;

    /** 언어구분 */
    @Schema(description = "언어구분", maxLength = 20)
    private String langCl;

    /** 등록자 */
    @Schema(description = "등록자", maxLength = 20)
    private String regId;

    /** 등록일자 */
    @Schema(description = "등록일자")
    private String regDate;

    /** 수정자 */
    @Schema(description = "수정자", maxLength = 20)
    private String modrId;

    /** 수정일자 */
    @Schema(description = "수정일자")
    private String modDate;

    /** 소스구분 */
    @Schema(description = "소스구분", maxLength = 10)
    private String sourceCl;
}
