######### Canal Frame config ###########
cf:
  defaultLang: ko_KR
  maxResultRows: 300000
  accessIpRange: 52.0.0.0~52.255.255.250,52.255.255.251~52.255.255.255,10.0.0.0~10.255.255.255,127.0.0.1~127.0.0.2
  static:
    basePath: http://localhost:${server.port}
  drm:
    dsdcode: "0000000000002519"
    enable: true
    fsdinitPath: C:/CJFW_WMS/fsdinit
  domainUrl: https://waylodev.ifresh.co.kr:9443
  file:
    uploadPath: C:/CJFW_WMS/uploads/dwaylo/upload
    dirPermission: 755
    largeDataTempFilePath: C:/CJFW_WMS/uploads/dwaylo/upload/largedatatemp
    polygonDataPath: C:/app/uploads/dwaylo/polygon/
    cpt: #biz Type
      extentionLimit: ppt|doc|xls|pptx|xlsx|docx|txt|jpg|gif|bmp|jpeg|pdf|tif|png
      sizeLimit: 31458000
  upload:
    dir:
      temp: C:/CJFW_WMS/uploads/dwaylo/upload/temp
      approval: C:/CJFW_WMS/uploads/dwaylo/upload/approval
      board: C:/CJFW_WMS/uploads/dwaylo/upload/board
      fax: C:/CJFW_WMS/uploads/report/report
      email: C:/CJFW_WMS/uploads/dwaylo/upload/email
      excel: C:/CJFW_WMS/uploads/dwaylo/upload/excel
      excelTemplate: C:/CJFW_WMS/uploads/dwaylo/upload/excelTemplate
      smartphoneimage: C:/CJFW_WMS/uploads/dwaylo/upload/smartphoneimage
      quick: C:/CJFW_WMS/uploads/dwaylo/upload/wd/quick
      report: C:/CJFW_WMS/uploads/report/report
      sttpl: C:/CJFW_WMS/uploads/dwaylo/upload/sttpl
      trsp: C:/CJFW_WMS/uploads/dwaylo/upload/trsp
  excel:
    uploadPath: C:/CJFW_WMS/uploads/dwaylo/upload/excel
  email:
    debug: true
    host: 10.75.113.125
    id: admin
    logPath: C:/CJFW_WMS/logs/email-log
    logType: DB  #or FILE
    port: 25
    pw: 12345
    sender: tester
    #senderAddr: ictdev@cj.net
    senderAddr: postmaster@fwportalqa01a.cjfwqa.com
  auth:
    pattern: "/api/cm/login/**,/api/cm/sso/**,/api/cm/public/**,/api/cm/elec/**,/api/ext/test/**,/api/cm/main/v1.0/getUserCodeList,/api/adapterGwms/**,/api/crm/**,/api/ofn/**,/api/ib/expense/v1.0/getApprPosting/**,/api/st/adjustmentreqeustexdc/v1.0/saveStockAutoHandle,/api/om/stockReocation/v1.0/optimization,/api/wd/itemTrace/v1.0/getPopList,/swagger-ui/**,/v3/api-docs/**,/swagger-resources/**"
  ### BackEnd 간 API 호출용 JWT 설정###
  apiJwt:
    algorithm: HS256
    expirTime: 5000
    headerKey: Api-CF-Token
    secretKey: cfbackendapikey20220114
  sso:
    redirectUrl: /ssoLogin
    secretKey: 90fd33a9fbb56cd1
  edms:
    workPlaceId: 101
    attrId: 100
    tempDir: C:/CJFW_WMS/uploads/dwaylo/upload/edms
    url: http://edmsqa2.ifresh.co.kr/edms/
  sap:
    client: 100
    userId: RFC_COM1
    password: cktpeo79!
    language: KO
    poolCapaciry: 10
    poolPeakLimit: 50
    host: 10.85.38.97
    hostType: ashost
    systemNumber: 10
    group: PUBLIC
    r3name: FWP
    msserv: ""
  eai:
    userId: SCM_IFQUSER
    password: IFQUSER2@15#@
    url: fwpiqas.cjfreshway.co.kr
    mode: SCM_QAS
    comMode: COM_QAS
    smsMode: EAI_QAS
    iamUrl: http://ssoqa2.ifresh.co.kr/ssoserver/services/SSO_NON_SAP_EAI.SSO_NON_SAP_EAIHttpSoap11Endpoint/
    iamOpMode: staging
    scmIfaceNamespace: urn://scm.cjfreshway.co.kr
    shrIfaceNamespace: urn://shr.cjfreshway.co.kr
    httpPort: http
  api:
    crm:
      url: https://gwmsqa.ifresh.co.kr/gwms/crm/rest/LIF1017/WM001/
      interfaceId: IFN_LIF1017_WM001_
      interfaceAuthKey: sclwEZRE/XQnc4kwlK3HUV9nBMAws0I8r1d8IWAsJUE=
    cs:
      url: https://safsqa2.ifresh.co.kr/com/wms/ifReceive/
    srm:
      url: https://nsrmqa.ifresh.co.kr/restful/
      username: if_restful
      password: emro1004!
  link:
    custUserSmsSec: /custUserSmsSec
  iam:
    secretKey: ejqmfdbdpadptmwpdl
    ssoUrl: https://nssoqa.ifresh.co.kr/sso/outerauthn.do
    returnUrl: /api/cm/sso/v1.0/loginProc
    
  whitelist:
    companies:
      - name: Nwill
        ips:
          - 127.0.0.1
          - 211.10.10.2

  # 퀵 API
  quick:
    url_reg: https://stnlogis.com/api/order_receive.php
    url_list: https://cjfreshway.stnlogis.com/api/order_list_dept.php
    appkey: c86fda0a22e404ad0d6cba5ea0a70741
    realOpen: N
  # 택배 API
  kxdelivery:
    url_token: https://dxapi-dev.cjlogistics.com:5054/ReqOneDayToken
    url_book: https://dxapi-dev.cjlogistics.com:5054/RegBook
    url_addr: https://dxapi-dev.cjlogistics.com:5054/ReqAddrRfnSm
    url_invoice: https://dxapi-dev.cjlogistics.com:5054/ReqInvcNo
    bizNo: 6038111270
    realOpen: N	
    # 대한통운 주소정제 접속클라이언트 번호
    clientNumber: 30451233
  
  # SHA256 SALT KEY
  sha256SaltKey: FWEnckeY3040
  
  # 대한통운 API 서비스
  cjlogistics:
    url: http://61.33.235.161:58080
  
---

spring:
  config:
    activate:
      on-profile: dev

cf:
  domainUrl: https://waylodev.ifresh.co.kr:9443
  file:
    uploadPath: /app/uploads/dwaylo/upload
    largeDataTempFilePath: /app/uploads/dwaylo/upload/largedatatemp
    polygonDataPath: /app/uploads/dwaylo/polygon/
  upload:
    dir:
      temp: /app/uploads/dwaylo/upload/temp
      approval: /app/uploads/dwaylo/upload/approval
      board: /app/uploads/dwaylo/upload/board
      fax: /app/uploads/report/report
      email: /app/uploads/dwaylo/upload/email
      excel: /app/uploads/dwaylo/upload/excel
      excelTemplate: /app/uploads/dwaylo/upload/excelTemplate
      smartphoneimage: /app/uploads/dwaylo/upload/smartphoneimage
      quick: /app/uploads/dwaylo/upload/wd/quick
      report: /app/uploads/report/report
      sttpl: /app/uploads/dwaylo/upload/sttpl
      trsp: /app/uploads/dwaylo/upload/trsp
  excel:
    uploadPath: /app/uploads/dwaylo/upload/excel
  static:
    basePath: http://dev.ictdev.cj.net # https://dev.ictdev.cj.net
  drm:
    dsdcode: "0000000000002519"
    enable: true
    fsdinitPath: /app/drm/fsdinit
  email:
    logPath: /app/logs/applog/email-log
  edms:
    workPlaceId: 101
    attrId: 100
    tempDir: /app/uploads/dwaylo/upload/edms
    url: http://edmsqa2.ifresh.co.kr/edms/

  # 퀵 API
  quick:
    url_reg: https://stnlogis.com/api/order_receive.php
    url_list: https://cjfreshway.stnlogis.com/api/order_list_dept.php
    appkey: c86fda0a22e404ad0d6cba5ea0a70741
    realOpen: N    
  # 택배 API
  kxdelivery:
    url_token: https://dxapi-dev.cjlogistics.com:5054/ReqOneDayToken
    url_book: https://dxapi-dev.cjlogistics.com:5054/RegBook
    url_addr: https://dxapi-dev.cjlogistics.com:5054/ReqAddrRfnSm
    url_invoice: https://dxapi-dev.cjlogistics.com:5054/ReqInvcNo
    bizNo: 6038111270	
    realOpen: N	
    # 대한통운 주소정제 접속클라이언트 번호
    clientNumber: 30451233	
  # 카카오알림톡.APIKEY
  kakao:
    appkey: e703ed8559c51491710fe0794029c2c56ca2af2b
---

spring:
  config:
    activate:
      on-profile: qa
      
cf:
  domainUrl: https://wayloqa.ifresh.co.kr
  file:
    uploadPath: /app/uploads/qwaylo/upload
    largeDataTempFilePath: /app/uploads/qwaylo/upload/largedatatemp
    polygonDataPath: /app/uploads/qwaylo/polygon/
  upload:
    dir:
      temp: /app/uploads/qwaylo/upload/temp
      approval: /app/uploads/qwaylo/upload/approval
      board: /app/uploads/qwaylo/upload/board
      fax: /app/uploads/report/report
      email: /app/uploads/qwaylo/upload/email
      excel: /app/uploads/qwaylo/upload/excel
      excelTemplate: /app/uploads/qwaylo/upload/excelTemplate
      smartphoneimage: /app/uploads/qwaylo/upload/smartphoneimage
      quick: /app/uploads/qwaylo/upload/wd/quick
      report: /app/uploads/report/report
      sttpl: /app/uploads/qwaylo/upload/sttpl
      trsp: /app/uploads/qwaylo/upload/trsp
  excel:
    uploadPath: /app/uploads/qwaylo/upload/excel
  static:
    basePath: http://dev.ictdev.cj.net # https://dev.ictdev.cj.net
  drm:
    dsdcode: "0000000000002519"
    enable: true
    fsdinitPath: /app/drm/fsdinit
  email:
    logPath: /app/logs/applog/email-log
  edms:
    workPlaceId: 101
    attrId: 100
    tempDir: /app/uploads/qwaylo/upload/edms
    url: http://edmsqa2.ifresh.co.kr/edms/

  # 퀵 API
  quick:
    url_reg: https://stnlogis.com/api/order_receive.php
    url_list: https://cjfreshway.stnlogis.com/api/order_list_dept.php
    appkey: c86fda0a22e404ad0d6cba5ea0a70741
    realOpen: N
  # 택배 API
  kxdelivery:
    url_token: https://dxapi-dev.cjlogistics.com:5054/ReqOneDayToken
    url_book: https://dxapi-dev.cjlogistics.com:5054/RegBook
    url_addr: https://dxapi-dev.cjlogistics.com:5054/ReqAddrRfnSm
    url_invoice: https://dxapi-dev.cjlogistics.com:5054/ReqInvcNo
    bizNo: 6038111270		
    realOpen: N		
    # 대한통운 주소정제 접속클라이언트 번호
    clientNumber: 30451233
  # 카카오알림톡.APIKEY
  kakao:
    appkey: e703ed8559c51491710fe0794029c2c56ca2af2b	

---

spring:
  config:
    activate:
      on-profile: prd
      
cf:
  domainUrl: https://waylo.ifresh.co.kr
  file:
    uploadPath: /app/uploads/pwaylo/upload
    largeDataTempFilePath: /app/uploads/pwaylo/upload/largedatatemp
    polygonDataPath: /app/uploads/pwaylo/polygon/
  upload:
    dir:
      temp: /app/uploads/pwaylo/upload/temp
      approval: /app/uploads/pwaylo/upload/approval
      board: /app/uploads/pwaylo/upload/board
      fax: /app/uploads/report/report
      email: /app/uploads/pwaylo/upload/email
      excel: /app/uploads/pwaylo/upload/excel
      excelTemplate: /app/uploads/pwaylo/upload/excelTemplate
      smartphoneimage: /app/uploads/pwaylo/upload/smartphoneimage
      quick: /app/uploads/pwaylo/upload/wd/quick
      report: /app/uploads/report/report
      sttpl: /app/uploads/pwaylo/upload/sttpl
      trsp: /app/uploads/pwaylo/upload/trsp
  excel:
    uploadPath: /app/uploads/pwaylo/upload/excel
  #email:
  #  debug: true
  #  host: 10.75.115.128
  #  id: admin
  #  logPath: C:/CJFW_WMS/logs/email-log
  #  logType: DB  #or FILE
  #  port: 25
  #  pw: 12345
  #  sender: tester
  #  #senderAddr: ictdev@cj.net
  #  senderAddr: postmaster@fwportalqa01a.cjfwqa.com
  static:
    basePath: http://dev.ictdev.cj.net # https://dev.ictdev.cj.net
  drm:
    dsdcode: "0000000000002519"
    enable: true
    fsdinitPath: /app/drm/fsdinit
  email:
    logPath: /app/logs/applog/email-log
  #sso:
  #  redirectUrl: /ssoLogin
  #  secretKey: 90fd33a9fbb56cd1 # CJ World SSO 복호화 키값
  edms:
    workPlaceId: 101
    attrId: 100
    tempDir: /app/uploads/pwaylo/upload/edms
    #url: http://edms.ifresh.co.kr/edms/
  #sap:
  #  client: 100
  #  userId: RFC_EA
  #  password: dldpdl1!
  #  language: KO
  #  poolCapaciry: 10
  #  poolPeakLimit: 50
  #  host: 52.2.92.85
  #  hostType: ashost
  #  systemNumber: 10
  #  group: PUBLIC
  #  r3name: FWP
  #  msserv: ""
  #eai:
  #  userId: SCM_IFPUSER
  #  password: IFPUSER2@15#@
  #  url: fwpivap.cjfreshway.co.kr
  #  mode: SCM_PRD
  #  comMode: COM_PRD
  #  smsMode: EAI_PRD
  #  iamUrl: http://sso.ifresh.co.kr/ssoserver/services/SSO_NON_SAP_EAI.SSO_NON_SAP_EAIHttpSoap11Endpoint/
  #  iamOpMode: real
  #  scmIfaceNamespace: urn://scm.cjfreshway.co.kr
  #  shrIfaceNamespace: urn://shr.cjfreshway.co.kr
  #  httpPort: http
  #api:
  #  crm:
  #    url: https://gwms.ifresh.co.kr/gwms/crm/rest/LIF1017/WM001/
  #    interfaceId: IFN_LIF1017_WM001_
  #    interfaceAuthKey: sclwEZRE/XQnc4kwlK3HUV9nBMAws0I8r1d8IWAsJUE=
  #  cs:
  #    url: https://safs.ifresh.co.kr/com/wms/ifReceive/
  #  srm:
  #    url: https://srm.ifresh.co.kr/restful/
  #    username: if_restful
  #    password: emro1004!
  iam:
    secretKey: ejqmfdbdpadptm1
    ssoUrl: https://nsso.ifresh.co.kr/sso/outerauthn.do
    returnUrl: /api/cm/sso/v1.0/loginProc

  # 퀵 API
  quick:
    url_reg: https://stnlogis.com/api/order_receive.php
    url_list: https://cjfreshway.stnlogis.com/api/order_list_dept.php
    appkey: c86fda0a22e404ad0d6cba5ea0a70741
    realOpen: N
  # 택배 API
  kxdelivery:
    url_token: https://dxapi-dev.cjlogistics.com:5054/ReqOneDayToken
    url_book: https://dxapi-dev.cjlogistics.com:5054/RegBook
  # 오픈 시 주석해제 및 realOpen Y로 변경해야 함  
    #url_token: https://dxapi.cjlogistics.com:5052/ReqOneDayToken 
    #url_book: https://dxapi.cjlogistics.com:5052/RegBook
    bizNo: 6038111270
    realOpen: N		
    # 대한통운 주소정제 접속클라이언트 번호
    clientNumber: 30451233
  # 카카오알림톡.APIKEY.PRD
  kakao:
    appkey: 344c6c25b2c3eacae088fa7b60f52582b9eb8b72	
---

spring:
  config:
    activate:
      on-profile: set
      
cf:
  domainUrl: https://10.74.11.78
  file:
    uploadPath: /app/uploads/qwaylo/upload
    largeDataTempFilePath: /app/uploads/qwaylo/upload/largedatatemp
    polygonDataPath: /app/uploads/qwaylo/polygon/
  upload:
    dir:
      temp: /app/uploads/qwaylo/upload/temp
      approval: /app/uploads/qwaylo/upload/approval
      board: /app/uploads/qwaylo/upload/board
      fax: /app/uploads/report/report
      email: /app/uploads/qwaylo/upload/email
      excel: /app/uploads/qwaylo/upload/excel
      excelTemplate: /app/uploads/qwaylo/upload/excelTemplate
      smartphoneimage: /app/uploads/qwaylo/upload/smartphoneimage
      quick: /app/uploads/qwaylo/upload/wd/quick
      report: /app/uploads/report/report
      sttpl: /app/uploads/qwaylo/upload/sttpl
      trsp: /app/uploads/qwaylo/upload/trsp
  excel:
    uploadPath: /app/uploads/qwaylo/upload/excel
  static:
    basePath: http://dev.ictdev.cj.net # https://dev.ictdev.cj.net
  drm:
    dsdcode: "0000000000002519"
    enable: true
    fsdinitPath: /app/drm/fsdinit
  email:
    logPath: /app/logs/applog/email-log
  edms:
    workPlaceId: 101
    attrId: 100
    tempDir: /app/uploads/qwaylo/upload/edms
    url: http://edmsqa2.ifresh.co.kr/edms/

  # 퀵 API
  quick:
    url_reg: https://stnlogis.com/api/order_receive.php
    url_list: https://cjfreshway.stnlogis.com/api/order_list_dept.php
    appkey: c86fda0a22e404ad0d6cba5ea0a70741
    realOpen: N
  # 택배 API
  kxdelivery:
    url_token: https://dxapi-dev.cjlogistics.com:5054/ReqOneDayToken
    url_book: https://dxapi-dev.cjlogistics.com:5054/RegBook
    url_addr: https://dxapi-dev.cjlogistics.com:5054/ReqAddrRfnSm
    url_invoice: https://dxapi-dev.cjlogistics.com:5054/ReqInvcNo
    bizNo: 6038111270		
    realOpen: N		
    # 대한통운 주소정제 접속클라이언트 번호
    clientNumber: 30451233
    # 카카오알림톡.APIKEY
    kakao:
      appkey: e703ed8559c51491710fe0794029c2c56ca2af2b	
