project:
  name: someProject
  
feign:
  test: 
    name: feigntest
    url: https://jsonplaceholder.typicode.com
  config:
    log-level: BASIC #NONE, BASIC, HEADERS, FULL
    connect-timeout: 10000 # 10 sec
    read-timeout: 15000    # 15 sec

