<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">

<mapper namespace="smsSendBatchService">

    <select id="selectSms" resultType="cjfw.batch.shr0130.SmsSendParamsDto">
        SELECT /* [smsSendBatchService.sqlx][selectSms][SMS발송대상조회][ASIS쿼리][20260108] */
               SENDPHONE
             , RECEIVEPHONE
             , SENDDT
             , SENDMESSAGE
             , SERIALKEY
          FROM MG_SMSMMSSEND
         WHERE  1=1
           AND STATUS = '10' 
           AND DEL_YN = 'N'
           AND SENDDT <![CDATA[>=]]> TO_CHAR(SYSDATE-1,'YYYYMMDDHH24MISS')
    </select>

    <update id="updateSms">
        UPDATE /* [smsSendBatchService.sqlx][updateSms][SMS발송상태변경][ASIS쿼리][20260108] */ MG_SMSMMSSEND
        SET	   STATUS   = '90'
              ,EDITDATE = SYSDATE
              ,EDITWHO  = 'LOGISONEBATCH'
        WHERE  1=1
          AND  SERIALKEY = #{SERIALKEY}
    </update>

</mapper>