spring:
  config:
    import:
      - classpath:/config/batch-config.yml

springdoc:
  use-fqn: true
  swagger-ui:
    enabled: true
    path: swagger.html #http://localhost:8080/swagger.html 로 호출
    defaultModelsExpandDepth: 10
    defaultModelExpandDepth: 3
  override-with-generic-response: false # Default 응답 메시지(@ControllerAdvice) 제외
  default-produces-media-type: application/json
  api-docs:
    enabled: true # http://ip:port/context-path/v3/api-docs.yaml 또는 ~/v3/api-docs End-point 활성화 여부
    # 특정 API의 End-point를 노출하면 안되는 경우는 Controller class 또는 Method 상단에 @Hidden 추가
