<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="dpInplanSTOService">

	<select id="getMasterList" resultType="DpInplanSTOResDto">	 
        SELECT /* [DpInplanSTOService.sqlx][getMasterList][광역입고현황 목록 조회][공두경][2025.06.18] */
        	/*+ USE_HASH(DP_INPLAN) FULL(DP_INPLAN)*/
			  MIN(NVL(CD1.BASEDESCR,CD1.BASECODE))														AS ORDERTYPE_NAME	/* 구매유형 */ 
			, DP_INPLAN.SLIPDT																            AS SLIPDT 			/* 광역입고일자 */	
			, TO_DM_DOCUMENT_H.DOCNO                                                                    AS DOCNO			/* 광역주문번호 */
			, FROM_DM_DOCUMENT_H.DCCODE                                                                 AS FROM_DCCODE		/* 물류센터 */
			, MIN(FROM_DC.DCNAME)                                                                       AS FROM_DCNAME		/* 물류센터명 */
			, FROM_DM_DOCUMENT_H.FROM_CUSTKEY															AS FROM_CUSTKEY		/* 창고 */
			, MIN(DCXORGANIZE1.DESCRIPTION)                   											AS FROM_CUSTNAME	/* 창고명 */
			, TO_DM_DOCUMENT_H.DCCODE                                                                   AS TO_DCCODE		/* 물류센터 */
			, MIN(TO_DC.DCNAME)                                                                         AS TO_DCNAME		/* 물류센터명 */
			, TO_DM_DOCUMENT_H.TO_CUSTKEY																AS TO_CUSTKEY		/* 창고 */
			, MIN(DCXORGANIZE2.DESCRIPTION)                   											AS TO_CUSTNAME		/* 창고명 */
			, FN_CODEDESCR(DM_DOCUMENT_D.STORERKEY,'STATUS_DP', MIN(DM_DOCUMENT_D.STATUS))                        AS STATUSNAME 		/* 진행상태 */
			, FN_CODEDESCR(DM_DOCUMENT_D.STORERKEY,'CREATIONTYPE_STO', MIN(TO_DM_DOCUMENT_H.SOTYPE))              AS STOTYPE <!-- 센터간이체시 선택된 STO유형 -->  /*이체유형*/
			, MAX(TO_DM_DOCUMENT_H.MEMO1)                                                               AS MEMO1			/* 메모 */	
			, MAX(USER1.USER_NM)                                              							AS ADDWHO			/* 생성인 */
			, MAX(DP_INPLAN.ADDDATE)                                                                 	AS ADDDATE			/* 등록일자 */
			, MAX(USER2.USER_NM)                                               							AS EDITWHO			/* 최종변경자 */
			, MAX(DP_INPLAN.EDITDATE)                                                                  AS EDITDATE			/* 최종변경시간 */
			, TO_DM_DOCUMENT_H.DOCDT                                                                   AS DOCDT  			/**/
			, TO_DM_DOCUMENT_H.ORDERTYPE                                                               AS ORDERTYPE			/**/
			, FROM_DM_DOCUMENT_H.ORGANIZE                                                              AS FROM_ORGANIZE		/**/
			, TO_DM_DOCUMENT_H.ORGANIZE                                                                AS TO_ORGANIZE		/**/
			, MIN(DM_DOCUMENT_D.STATUS)                                                                AS STATUS			/**/
			, TO_DM_DOCUMENT_H.STORERKEY                                                               AS STORERKEY  		/**/
			, TO_DM_DOCUMENT_H.DOCTYPE                                                                 AS DOCTYPE  			/**/
		FROM DM_DOCUMENT_D          
		JOIN CM_USER_AUTHORITY         
		ON   CM_USER_AUTHORITY.USERID         =  #{gUserId}       
		AND  CM_USER_AUTHORITY.DCCODE         = DM_DOCUMENT_D.DCCODE             
		AND  CM_USER_AUTHORITY.STORERKEY      = DM_DOCUMENT_D.STORERKEY          
		AND  CM_USER_AUTHORITY.ORGANIZE       = DM_DOCUMENT_D.ORGANIZE           
		AND  CM_USER_AUTHORITY.AREA           = DM_DOCUMENT_D.AREA   
		<if test="toDccode != null and toDccode != ''">		AND CM_USER_AUTHORITY.DCCODE	=  #{toDccode}		</if>
		<if test="gStorerkey != null and gStorerkey != ''">		AND CM_USER_AUTHORITY.STORERKEY	=  #{gStorerkey}		</if>    
		<if test="gArea != null and gArea != ''">			AND CM_USER_AUTHORITY.AREA	    =  #{gArea}			</if>    
		JOIN DM_DOCUMENT_H TO_DM_DOCUMENT_H /* 공급받는센터 */
		ON   DM_DOCUMENT_D.DCCODE = TO_DM_DOCUMENT_H.DCCODE
		AND DM_DOCUMENT_D.DOCTYPE = TO_DM_DOCUMENT_H.DOCTYPE
		AND DM_DOCUMENT_D.DELIVERYDATE = TO_DM_DOCUMENT_H.DELIVERYDATE
		AND DM_DOCUMENT_D.DOCNO = TO_DM_DOCUMENT_H.DOCNO
		<if test="toDccode != null and toDccode != ''">		AND TO_DM_DOCUMENT_H.TO_CUSTKEY   LIKE #{toDccode} || '%' 	</if>
		<if test="fromDccode != null and fromDccode != ''">	AND TO_DM_DOCUMENT_H.FROM_CUSTKEY LIKE #{fromDccode} || '%' 	</if>
		<!-- 배송그룹 공통조회 조건 -->
		<if test="gMultiCourier != null and gMultiCourier != ''">	AND DM_DOCUMENT_H.COURIER = #{gMultiCourier}	</if>
		JOIN DM_DOCUMENT_H FROM_DM_DOCUMENT_H /* 공급센터 */   
		ON   FROM_DM_DOCUMENT_H.DOCTYPE 		  = 'WD'
		AND  FROM_DM_DOCUMENT_H.DOCNO   		  = TO_DM_DOCUMENT_H.DOCNO
		AND  FROM_DM_DOCUMENT_H.STORERKEY         = TO_DM_DOCUMENT_H.STORERKEY  
		AND  FROM_DM_DOCUMENT_H.DELIVERYDATE      = TO_DM_DOCUMENT_H.DELIVERYDATE  
		JOIN DP_INPLAN
		ON   DP_INPLAN.DCCODE = DM_DOCUMENT_D.DCCODE
		AND DP_INPLAN.DOCTYPE = DM_DOCUMENT_D.DOCTYPE
		AND DP_INPLAN.SLIPDT = DM_DOCUMENT_D.DELIVERYDATE
		AND DP_INPLAN.DOCNO = DM_DOCUMENT_D.DOCNO
		AND DP_INPLAN.DOCLINE = DM_DOCUMENT_D.DOCLINE
		AND  DP_INPLAN.DEL_YN         		=  'N'
		JOIN MS_SKU
		ON   MS_SKU.STORERKEY                 = DM_DOCUMENT_D.STORERKEY
		AND  MS_SKU.SKU                       = DM_DOCUMENT_D.SKU   
		AND  MS_SKU.DEL_YN                    = 'N'
		<if test="storagetype != null and storagetype != ''"> AND MS_SKU.STORAGETYPE = #{storagetype}			</if>
		JOIN CM_DC    FROM_DC
		ON   FROM_DC.DCCODE = FROM_DM_DOCUMENT_H.DCCODE
		AND  FROM_DC.DEL_YN = 'N'
		JOIN CM_DC    TO_DC
		ON   TO_DC.DCCODE = TO_DM_DOCUMENT_H.DCCODE  
		AND  TO_DC.DEL_YN = 'N'               
		LEFT JOIN CM_CODE_STORER CD1  ON CD1.STORERKEY  = TO_DM_DOCUMENT_H.STORERKEY AND CD1.CODELIST  = 'ORDERTYPE_STO' 	AND CD1.BASECODE   = TO_DM_DOCUMENT_H.ORDERTYPE
		LEFT JOIN CM_DCXORGANIZE DCXORGANIZE1 ON DCXORGANIZE1.DCCODE = FROM_DM_DOCUMENT_H.DCCODE AND DCXORGANIZE1.ORGANIZE = FROM_DM_DOCUMENT_H.FROM_CUSTKEY
		LEFT JOIN CM_DCXORGANIZE DCXORGANIZE2 ON DCXORGANIZE2.DCCODE = TO_DM_DOCUMENT_H.DCCODE   AND DCXORGANIZE2.ORGANIZE = TO_DM_DOCUMENT_H.TO_CUSTKEY
		LEFT JOIN FRAMEONE_USER USER1 ON USER1.USER_ID = DP_INPLAN.ADDWHO  OR USER1.USER_NO = DP_INPLAN.ADDWHO
		LEFT JOIN FRAMEONE_USER USER2 ON USER2.USER_ID = DP_INPLAN.EDITWHO OR USER2.USER_NO = DP_INPLAN.EDITWHO																																		 
		WHERE DM_DOCUMENT_D.DOCTYPE                    = 'DP'         
		AND   DM_DOCUMENT_D.DEL_YN                     = 'N'         
		<if test="fromSlipdt != null and fromSlipdt != ''">	AND DM_DOCUMENT_D.DELIVERYDATE <![CDATA[>=]]> #{fromSlipdt}		</if>  
		<if test="toSlipdt != null and toSlipdt != ''">		AND DM_DOCUMENT_D.DELIVERYDATE <![CDATA[<=]]> #{toSlipdt}		</if>
		<!-- 상품 다중선택 -->
		<if test="skuMulti != null and skuMulti != '' ">
			<trim prefix="AND (" suffix=")" prefixOverrides="OR">
				<foreach collection="skuMulti" item="item">
					OR DM_DOCUMENT_D.SKU IN
					<foreach collection="item" item="code" open="(" close=")" separator=",">
						#{code}
		      		</foreach>
		    	</foreach>
		  	</trim>
        </if>
		<if test="status != null and status != ''">			AND DM_DOCUMENT_D.STATUS	=	#{status} 						</if>
		<if test="fromDocdt != null and fromDocdt != ''">	AND DM_DOCUMENT_D.DELIVERYDATE    <![CDATA[>=]]> #{fromDocdt}			</if>
		<if test="toDocdt != null and toDocdt != ''">		AND DM_DOCUMENT_D.DELIVERYDATE    <![CDATA[<=]]> #{toDocdt}			</if>
				           
		<!-- 문서번호 다중선택 -->
		<if test="docnoMulti != null and docnoMulti != ''">
			AND DM_DOCUMENT_D.DOCNO IN
			<foreach collection="docnoMulti" item="code" open="(" close=")" separator=",">
				#{code}
			</foreach>
		</if>
		<if test="serialCheck != null and serialCheck != ''">
			AND    EXISTS (
							SELECT 'A'
							FROM ST_SNINFO
							JOIN DP_INVOICE_SN
								ON DP_INVOICE_SN.STORERKEY             = ST_SNINFO.STORERKEY
							AND DP_INVOICE_SN.SKU                   = ST_SNINFO.SKU
							AND DP_INVOICE_SN.SERIALNO              = ST_SNINFO.SERIALNO
							AND DP_INVOICE_SN.STOCKID               = ST_SNINFO.STOCKID
							AND DP_INVOICE_SN.DEL_YN                = 'N'
							WHERE DP_INVOICE_SN.DCCODE                = DP_INPLAN.DCCODE                   
							AND DP_INVOICE_SN.STORERKEY             = DP_INPLAN.STORERKEY        
							AND DP_INVOICE_SN.SLIPNO                = DP_INPLAN.SLIPNO                              
							AND DP_INVOICE_SN.SLIPDT                = DP_INPLAN.SLIPDT                   
							AND DP_INVOICE_SN.SLIPLINE              = DP_INPLAN.SLIPLINE
							AND DP_INVOICE_SN.DOCTYPE               = DP_INPLAN.DOCTYPE
							AND DP_INVOICE_SN.SKU                   = DP_INPLAN.SKU    
							AND DP_INVOICE_SN.DEL_YN                = 'N'
				<if test="serialnoMulti != null and serialnoMulti != ''">
					AND ST_SNINFO.SERIALNO IN
					<foreach collection="serialnoMulti" item="code" open="(" close=")" separator=",">
						#{code}
					</foreach>
				</if>
				<if test="blnoMulti != null and blnoMulti != ''">
					AND ST_SNINFO.CONVSERIALNO IN
					<foreach collection="blnoMulti" item="code" open="(" close=")" separator=",">
						#{code}
					</foreach>
				</if>
		    	<if test="contractcompany != null and contractcompany != ''">	AND    ST_SNINFO.CONTRACTCUSTKEY	=	#{contractcompany} 	</if>
							)
		</if>
		GROUP BY
			TO_DM_DOCUMENT_H.DOCDT
			,TO_DM_DOCUMENT_H.ORDERTYPE
			,TO_DM_DOCUMENT_H.DOCNO
			,FROM_DM_DOCUMENT_H.DCCODE               
			,FROM_DM_DOCUMENT_H.ORGANIZE
			,TO_DM_DOCUMENT_H.DCCODE
			,TO_DM_DOCUMENT_H.ORGANIZE
			,TO_DM_DOCUMENT_H.STORERKEY
			,TO_DM_DOCUMENT_H.DOCTYPE   
			,DM_DOCUMENT_D.STORERKEY       
			,DP_INPLAN.SLIPDT     
			,FROM_DM_DOCUMENT_H.FROM_CUSTKEY
			,TO_DM_DOCUMENT_H.TO_CUSTKEY
		ORDER BY
			DP_INPLAN.SLIPDT
			,TO_DM_DOCUMENT_H.ORDERTYPE
			,TO_DM_DOCUMENT_H.DOCNO   
    </select>
    
    <select id="getDetailList" resultType="DpInplanSTODetailResDto">
	   SELECT /* [DpInplanSTOService.sqlx][getDetailList][광역입고현황 주문현황 조회][공두경][2025.06.18] */
			 DM_DOCUMENT_D.DOCLINE         																			AS DOCLINE			/*품목번호*/
			,DM_DOCUMENT_D.SKU         																				AS SKU				/*상품코드*/
			,MS_SKU.DESCRIPTION       																				AS SKUNAME			/*상품명칭*/
			,'['||DM_DOCUMENT_D.PLANT||']'|| DECODE(TRIM(NVL(PLANT1.DESCRIPTION,'')),'',PLANT1.PLANT,TRIM(NVL(PLANT1.DESCRIPTION,'')))				AS PLANT_DESCR		/*플랜트*/
			,NVL(CD1.BASEDESCR,CD1.BASECODE)																		AS CHANNELNAME   	/*저장유무*/
			,NVL(CD2.BASEDESCR,CD2.BASECODE)																		AS STORAGETYPE_NAME /*저장조건*/     
			,DM_DOCUMENT_D.STORERUOM             										    						AS UOM				/*이체단위*/
			,NVL((DP_INPLAN.ORDERQTY + DP_INPLAN.CANCELQTY) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0)			AS ORDERQTY			/*주문수량*/
			,NVL((DM_DOCUMENT_D_WD.INSPECTQTY) * DM_DOCUMENT_D_WD.BUNJA / DM_DOCUMENT_D_WD.BUNMO,0)					AS INSPECTQTY_WD	/*검수량출고*/
			,NVL((DP_INPLAN.INSPECTQTY) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0)								AS INSPECTQTY		/*검수량입고*/
			,NVL((DM_DOCUMENT_D_WD.CONFIRMQTY) * DM_DOCUMENT_D_WD.BUNJA / DM_DOCUMENT_D_WD.BUNMO,0)					AS CONFIRMQTY_WD	/*확정수량출고*/
			,NVL((DP_INPLAN.CONFIRMQTY ) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0)								AS CONFIRMQTY		/*확정수량입고*/
			,NVL((NVL((DM_DOCUMENT_D_WD.CONFIRMQTY * UOM13.BUNJA / UOM13.BUNMO),0) * UOM14.BUNMO / UOM14.BUNJA),0)	AS CONFIRMWEIGHT_WD	/*충량출고*/
			,CASE WHEN DP_INPLAN.STORERKEY = 'CJFW' 
				  THEN (
							CASE WHEN DM_DOCUMENT_D.STORERUOM = 'KG' 
								 THEN NVL((DP_INPLAN.CONFIRMQTY) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0)
								 ELSE MS_SKU.NETWEIGHT * NVL((DP_INPLAN.CONFIRMQTY) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0) 
						    END
						)		 
				  ELSE NVL((NVL((DP_INPLAN.CONFIRMQTY * UOM11.BUNJA / UOM11.BUNMO),0) * UOM12.BUNMO / UOM12.BUNJA),0)
			 END 																									AS CONFIRMWEIGHT 	/*중량입고*/
			,NVL(CD4.BASEDESCR,CD4.BASECODE)																		AS STATUSNAME_WD  	/*진행상태출고*/
			,NVL(CD3.BASEDESCR,CD3.BASECODE)																		AS STATUSNAME  		/*진행상태입고*/        
			,DM_DOCUMENT_D.CHANNEL     																				AS CHANNEL			/**/
			,MS_SKU.STORAGETYPE										                    							AS STORAGETYPE		/**/
			,DM_DOCUMENT_D.STATUS 																					AS STATUS			/**/
			,MS_SKU.QTYPERBOX    																					AS QTYPERBOX		/**/
			,DM_DOCUMENT_D.PLANT																					AS PLANT			/**/
			,DM_DOCUMENT_D.DEL_YN																					AS DEL_YN 			/**/
		FROM DM_DOCUMENT_D  
		JOIN CM_USER_AUTHORITY         
		ON   CM_USER_AUTHORITY.USERID         =  #{gUserId}                          
		AND  CM_USER_AUTHORITY.DCCODE         =  #{dccode}
		AND  CM_USER_AUTHORITY.STORERKEY      =  #{storerkey}             
		AND  CM_USER_AUTHORITY.DCCODE         = DM_DOCUMENT_D.DCCODE             
		AND  CM_USER_AUTHORITY.STORERKEY      = DM_DOCUMENT_D.STORERKEY          
		AND  CM_USER_AUTHORITY.ORGANIZE       = DM_DOCUMENT_D.ORGANIZE           
		AND  CM_USER_AUTHORITY.AREA           = DM_DOCUMENT_D.AREA    
		<if test="gStorerkey != null and gStorerkey != ''">		AND CM_USER_AUTHORITY.STORERKEY	=  #{gStorerkey}		</if>    
		<if test="gArea != null and gArea != ''">			AND CM_USER_AUTHORITY.AREA	    =  #{gArea}			</if>    
		JOIN DP_INPLAN
		ON   DP_INPLAN.DCCODE = DM_DOCUMENT_D.DCCODE
		AND DP_INPLAN.DOCTYPE = DM_DOCUMENT_D.DOCTYPE
		AND DP_INPLAN.SLIPDT = DM_DOCUMENT_D.DELIVERYDATE
		AND DP_INPLAN.DOCNO = DM_DOCUMENT_D.DOCNO
		AND DP_INPLAN.DOCLINE = DM_DOCUMENT_D.DOCLINE
		AND  DP_INPLAN.DEL_YN         		=  'N' 		    	  
		JOIN MS_SKU
		ON   MS_SKU.STORERKEY                 = DM_DOCUMENT_D.STORERKEY
		AND  MS_SKU.SKU                       = DM_DOCUMENT_D.SKU 
		AND  MS_SKU.DEL_YN                    = 'N'
		<if test="storagetype != null and storagetype != ''"> AND MS_SKU.STORAGETYPE = #{storagetype}			</if>
		JOIN DM_DOCUMENT_D DM_DOCUMENT_D_WD
		ON   DM_DOCUMENT_D_WD.DOCNO      		= DM_DOCUMENT_D.DOCNO    
		AND  DM_DOCUMENT_D_WD.DOCLINE    		= DM_DOCUMENT_D.DOCLINE  
		AND  DM_DOCUMENT_D_WD.DOCTYPE    		= 'WD'    
		AND  DM_DOCUMENT_D_WD.WORKPROCESSCODE = 'STO'            
		LEFT JOIN CM_CODE_STORER CD1  ON CD1.STORERKEY  = DM_DOCUMENT_D.STORERKEY AND CD1.CODELIST  = 'PUTAWAYTYPE' 	AND CD1.BASECODE   = DM_DOCUMENT_D.CHANNEL
        LEFT JOIN CM_CODE_STORER CD2  ON CD2.STORERKEY  = MS_SKU.STORERKEY AND CD2.CODELIST  = 'STORAGETYPE' 		AND CD2.BASECODE   = MS_SKU.STORAGETYPE
        LEFT JOIN CM_CODE_STORER CD3  ON CD3.STORERKEY  = DM_DOCUMENT_D.STORERKEY AND CD3.CODELIST  = 'STATUS_DP' 		AND CD3.BASECODE   = DM_DOCUMENT_D.STATUS
        LEFT JOIN CM_CODE_STORER CD4  ON CD4.STORERKEY  = DM_DOCUMENT_D_WD.STORERKEY AND CD4.CODELIST  = 'STATUS_WD' 	AND CD4.BASECODE   = DM_DOCUMENT_D_WD.STATUS
        LEFT JOIN MS_PLANT PLANT1 	  ON PLANT1.PLANT = DM_DOCUMENT_D.PLANT
		LEFT JOIN MS_UOM UOM11  	  ON UOM11.STORERKEY = DP_INPLAN.STORERKEY AND UOM11.SKU  = DP_INPLAN.SKU AND UOM11.UOM = DP_INPLAN.UOM
        LEFT JOIN MS_UOM UOM12	  	  ON UOM12.STORERKEY = DP_INPLAN.STORERKEY AND UOM12.SKU  = DP_INPLAN.SKU AND UOM12.UOM = 'KG'
		LEFT JOIN MS_UOM UOM13  	  ON UOM13.STORERKEY = DM_DOCUMENT_D_WD.STORERKEY AND UOM13.SKU  = DM_DOCUMENT_D_WD.SKU AND UOM13.UOM = DM_DOCUMENT_D_WD.UOM
        LEFT JOIN MS_UOM UOM14	  	  ON UOM14.STORERKEY = DM_DOCUMENT_D_WD.STORERKEY AND UOM14.SKU  = DM_DOCUMENT_D_WD.SKU AND UOM14.UOM = 'KG'
		WHERE DM_DOCUMENT_D.DOCTYPE          = 'DP'           
		AND   DM_DOCUMENT_D.DEL_YN           = 'N'      
		AND   DM_DOCUMENT_D.DCCODE           = #{dccode}
		AND   DM_DOCUMENT_D.STORERKEY        = #{storerkey}         
		AND   DM_DOCUMENT_D.DELIVERYDATE	         = #{docdt}
		AND   DM_DOCUMENT_D.DOCNO	         = #{docno}
		AND   DM_DOCUMENT_D.DOCTYPE          = #{doctype}
		<!-- 상품 다중선택 -->
		<if test="skuMulti != null and skuMulti != '' ">
			<trim prefix="AND (" suffix=")" prefixOverrides="OR">
				<foreach collection="skuMulti" item="item">
					OR DM_DOCUMENT_D.SKU IN
					<foreach collection="item" item="code" open="(" close=")" separator=",">
						#{code}
		      		</foreach>
		    	</foreach>
		  	</trim>
        </if>
		<if test="serialCheck != null and serialCheck != ''">
				AND    EXISTS (
							SELECT 'A'
							FROM ST_SNINFO
							JOIN DP_INVOICE_SN
								ON DP_INVOICE_SN.STORERKEY             = ST_SNINFO.STORERKEY
							AND DP_INVOICE_SN.SKU                   = ST_SNINFO.SKU
							AND DP_INVOICE_SN.SERIALNO              = ST_SNINFO.SERIALNO
							AND DP_INVOICE_SN.STOCKID               = ST_SNINFO.STOCKID
							AND DP_INVOICE_SN.DEL_YN                = 'N'
							WHERE DP_INVOICE_SN.DCCODE                = DP_INPLAN.DCCODE                   
							AND DP_INVOICE_SN.STORERKEY             = DP_INPLAN.STORERKEY        
							AND DP_INVOICE_SN.SLIPNO                = DP_INPLAN.SLIPNO                              
							AND DP_INVOICE_SN.SLIPDT                = DP_INPLAN.SLIPDT                   
							AND DP_INVOICE_SN.SLIPLINE              = DP_INPLAN.SLIPLINE
							AND DP_INVOICE_SN.DOCTYPE               = DP_INPLAN.DOCTYPE
							AND DP_INVOICE_SN.SKU                   = DP_INPLAN.SKU    
							AND DP_INVOICE_SN.DEL_YN                = 'N'
				<if test="serialnoMulti != null and serialnoMulti != ''">
					AND ST_SNINFO.SERIALNO IN
					<foreach collection="serialnoMulti" item="code" open="(" close=")" separator=",">
						#{code}
					</foreach>
				</if>
				<if test="blnoMulti != null and blnoMulti != ''">
					AND ST_SNINFO.CONVSERIALNO IN
					<foreach collection="blnoMulti" item="code" open="(" close=")" separator=",">
						#{code}
					</foreach>
				</if>
		    	<if test="contractcompany != null and contractcompany != ''">	AND    ST_SNINFO.CONTRACTCUSTKEY	=	#{contractcompany} 	</if>
							)
		</if>
			ORDER BY DM_DOCUMENT_D.DOCLINE
			,DM_DOCUMENT_D.SKU	
    </select>
    
    <select id="getSerialInfoList" resultType="DpInplanSTOSerialInfoResDto">
	   SELECT /* [DpInplanSTOService.sqlx][getSerialInfoList][광역입고현황 이력정보 조회][공두경][2025.06.18] */
			 DM_DOCUMENT_D.DOCLINE                      														AS DOCLINE			/*품목번호*/
			,DM_DOCUMENT_D.SKU                          								 						AS SKU				/*상품코드*/
			,MS_SKU.DESCRIPTION                         														AS SKUNAME			/*상품명칭*/
			,'['||DM_DOCUMENT_D.PLANT||']'|| DECODE(TRIM(NVL(PLANT1.DESCRIPTION,'')),'',PLANT1.PLANT,TRIM(NVL(PLANT1.DESCRIPTION,'')))     		AS PLANT_DESCR		/*플랜트*/
			,NVL(CD1.BASEDESCR,CD1.BASECODE)																	AS CHANNELNAME   	/*저장유무*/	
			,NVL(CD2.BASEDESCR,CD2.BASECODE) 																	AS STORAGETYPENAME  /*저장조건*/ 
			,MS_SKU.QTYPERBOX    																				AS QTYPERBOX 		/*박스입수*/
			,ST_SNINFO.UOM                    																	AS UOM				/*단위*/
			,'0'         																						AS AVGWEIGHT        /*평균중량*/
			,'0'         																						AS CALORDERBOX      /*환산주문박스*/		
			,'0'         																						AS CALCONFIRMBOX    /*환산확정박스*/
			,'0'         																						AS REALBOX          /*실박스*/
			,NVL((DP_INPLAN.ORDERQTY + DP_INPLAN.CANCELQTY ) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0)		AS ORDERQTY			/*주문수량*/
			,NVL((DP_INVOICE_SN.CONFIRMQTY ) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0)						AS INSPECTQTY		/*입고검수량*/
			,NVL((DP_INVOICE_SN.CONFIRMQTY ) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0)	 					AS CONFIRMQTY		/*입고확정량*/
			,ST_SNINFO.NETWEIGHT              																	AS WEIGHT			/*입고중량*/
			,DM_DOCUMENT_D.STATUS                 																AS STATUS			/*진행상태*/
			,ST_SNINFO.LOTTABLE01                          														AS LOTTABLE01		/*기준일(소비,제조)*/
			, NVL(CASE WHEN MS_SKU.DURATIONTYPE = '1'
			THEN TO_CHAR(TO_DATE(ST_SNINFO.LOTTABLE01,'YYYYMMDD') - (MS_SKU.DURATION - 1), 'YYYYMMDD')
			ELSE ST_SNINFO.LOTTABLE01
			END,'STD') AS LOT_MANUFACTURE                    /** 제조 */
			, NVL(CASE WHEN MS_SKU.DURATIONTYPE = '1'
			THEN ST_SNINFO.LOTTABLE01
			ELSE TO_CHAR(TO_DATE(ST_SNINFO.LOTTABLE01,'YYYYMMDD') + (MS_SKU.DURATION - 1), 'YYYYMMDD')
			END,'STD') AS LOT_EXPIRE                         /** 유통 */
			,FN_LOTDURATION(MS_SKU.STORERKEY, MS_SKU.DURATIONTYPE, MS_SKU.DURATION, ST_SNINFO.LOTTABLE01, 'N')||'/'||MS_SKU.DURATION	AS DURATION_TERM	/*소비기간(잔여/전체)*/          
			,ST_SNINFO.SERIALNO               																	AS SERIALNO			/*이력번호*/
			,ST_SNINFO.STOCKID                                                                                  AS STOCKID			/*바코드*/
			,ST_SNINFO.CONVSERIALNO           																	AS CONVSERIALNO		/*B/L 번호*/
			,ST_SNINFO.BUTCHERYDT                                                                               AS BUTCHERYDT		/*도축일자*/
			,ST_SNINFO.FACTORYNAME            																	AS FACTORYNAME		/*도축장*/
			,NVL(CD3.BASEDESCR,CD3.BASECODE)                                            						AS CONTRACTTYPE 	/*계약유형*/
			,ST_SNINFO.CONTRACTCUSTKEY                                                                          AS CONTRACTCOMPANY  /*계약업체*/           	          
			,( SELECT DESCRIPTION  FROM MS_CUST
				WHERE CUSTKEY = ST_SNINFO.CONTRACTCUSTKEY
					AND ROWNUM = 1)                                                                             AS CONTRACTCOMPANYNAME	/*계약업체명*/
			,ST_SNINFO.FROMVALIDDT                                                                              AS FROMVALIDDT		/*FROM*/
			,ST_SNINFO.TOVALIDDT                                                                                AS TOVALIDDT		/*TO*/
			,DP_INVOICE_SN.ORDERQTY                                                                             AS SERIALORDERQTY	/*스캔예정량*/      
			,DP_INVOICE_SN.CONFIRMQTY                                                                           AS SERIALINSPECTQTY /*스캔량*/   
			,CASE WHEN DP_INPLAN.STORERKEY = 'CJFW' 
				  THEN (
							CASE WHEN DP_INPLAN.UOM = 'KG' 
								 THEN DP_INVOICE_SN.CONFIRMQTY
								 ELSE DP_INVOICE_SN.CONFIRMQTY * ST_SNINFO.NETWEIGHT
							END      																		                		                    
				  )	
				  ELSE NVL((NVL((DP_INVOICE_SN.CONFIRMQTY * UOM11.BUNJA / UOM11.BUNMO),0) * UOM12.BUNMO / UOM12.BUNJA),0)
			END                                                                                                 AS SERIALSCANWEIGHT	/*스캔중량*/


			,DP_INVOICE_SN.OPENQTY                    															AS QTY				/**/
			,ST_SNINFO.SERIALLEVEL           																	AS SERIALLEVEL		/**/
			,ST_SNINFO.SERIALTYPE             																	AS SERIALTYPE 		/**/
			,ST_SNINFO.FACTORYKEY            																	AS FACTORYKEY		/**/
			,MS_SKU.COLORDESCR                          														AS COLORDESCR		/**/
			,ST_SNINFO.PLACEOFORIGIN          																	AS PLACEOFORIGIN 	/**/
			,DM_DOCUMENT_D.CHANNEL     																			AS CHANNEL			/**/
			,MS_SKU.STORAGETYPE										                    						AS STORAGETYPE		/**/
			,MS_SKU.DURATION																					AS DURATION			/**/
			,MS_SKU.DURATIONTYPE																				AS DURATIONTYPE		/**/
			,DM_DOCUMENT_D.PLANT																				AS PLANT			/**/
		FROM DM_DOCUMENT_D  
		JOIN CM_USER_AUTHORITY         
		ON   CM_USER_AUTHORITY.USERID         =  #{gUserId}                          
		AND  CM_USER_AUTHORITY.DCCODE         =  #{dccode}              
		AND  CM_USER_AUTHORITY.STORERKEY      =  #{storerkey}             
		AND  CM_USER_AUTHORITY.DCCODE         = DM_DOCUMENT_D.DCCODE             
		AND  CM_USER_AUTHORITY.STORERKEY      = DM_DOCUMENT_D.STORERKEY          
		AND  CM_USER_AUTHORITY.ORGANIZE       = DM_DOCUMENT_D.ORGANIZE           
		AND  CM_USER_AUTHORITY.AREA           = DM_DOCUMENT_D.AREA 
		<if test="gStorerkey != null and gStorerkey != ''">		AND CM_USER_AUTHORITY.STORERKEY	=  #{gStorerkey}		</if>    		
		JOIN MS_SKU
		ON    MS_SKU.STORERKEY                   = DM_DOCUMENT_D.STORERKEY  
		AND   MS_SKU.SKU                         = DM_DOCUMENT_D.SKU 
		AND   MS_SKU.DEL_YN                      = 'N'
		AND   MS_SKU.SERIALYN                    = 'Y' 
		<if test="storagetype != null and storagetype != ''"> AND MS_SKU.STORAGETYPE = #{storagetype}			</if>        
		JOIN DP_INPLAN
		ON    DP_INPLAN.DCCODE = DM_DOCUMENT_D.DCCODE
		AND DP_INPLAN.DOCTYPE = DM_DOCUMENT_D.DOCTYPE
		AND DP_INPLAN.SLIPDT = DM_DOCUMENT_D.DELIVERYDATE
		AND DP_INPLAN.DOCNO = DM_DOCUMENT_D.DOCNO
		AND DP_INPLAN.DOCLINE = DM_DOCUMENT_D.DOCLINE
		AND   DP_INPLAN.DEL_YN             	  = 'N'
		LEFT JOIN DP_INVOICE_SN
		ON    DP_INVOICE_SN.DCCODE                = DP_INPLAN.DCCODE                   
		AND   DP_INVOICE_SN.STORERKEY             = DP_INPLAN.STORERKEY        
		AND   DP_INVOICE_SN.SLIPNO                = DP_INPLAN.SLIPNO                              
		AND   DP_INVOICE_SN.SLIPDT                = DP_INPLAN.SLIPDT                   
		AND   DP_INVOICE_SN.SLIPLINE              = DP_INPLAN.SLIPLINE
		AND   DP_INVOICE_SN.DOCTYPE               = DP_INPLAN.DOCTYPE
		AND   DP_INVOICE_SN.SKU                   = DP_INPLAN.SKU    
		AND   DP_INVOICE_SN.DEL_YN                = 'N'
		<choose>
			<when test="serialCheck != null and serialCheck != ''">
				JOIN   ST_SNINFO 
			</when>
			<otherwise>
				LEFT JOIN   ST_SNINFO 
			</otherwise>
		</choose>	
				ON     DP_INVOICE_SN.STORERKEY             = ST_SNINFO.STORERKEY
				AND    DP_INVOICE_SN.SKU                   = ST_SNINFO.SKU
				AND    DP_INVOICE_SN.SERIALNO              = ST_SNINFO.SERIALNO
				AND    DP_INVOICE_SN.STOCKID               = ST_SNINFO.STOCKID
				AND    DP_INVOICE_SN.DEL_YN                = 'N'
		LEFT JOIN CM_CODE_STORER CD1  ON CD1.STORERKEY  = DM_DOCUMENT_D.STORERKEY AND CD1.CODELIST  = 'PUTAWAYTYPE' 	AND CD1.BASECODE   = DM_DOCUMENT_D.CHANNEL
        LEFT JOIN CM_CODE_STORER CD2  ON CD2.STORERKEY  = MS_SKU.STORERKEY 		  AND CD2.CODELIST  = 'STORAGETYPE' 	AND CD2.BASECODE   = MS_SKU.STORAGETYPE
        LEFT JOIN CM_CODE_STORER CD3  ON CD3.STORERKEY  = ST_SNINFO.STORERKEY 	  AND CD3.CODELIST  = 'CONTRACTTYPE_SN' AND CD3.BASECODE   = ST_SNINFO.CONTRACTTYPE        
        LEFT JOIN MS_PLANT PLANT1 	  ON PLANT1.PLANT = DM_DOCUMENT_D.PLANT
		LEFT JOIN MS_UOM UOM11  	  ON UOM11.STORERKEY = DP_INPLAN.STORERKEY AND UOM11.SKU  = DP_INPLAN.SKU AND UOM11.UOM = DP_INPLAN.UOM
        LEFT JOIN MS_UOM UOM12	  	  ON UOM12.STORERKEY = DP_INPLAN.STORERKEY AND UOM12.SKU  = DP_INPLAN.SKU AND UOM12.UOM = 'KG'		
		WHERE DM_DOCUMENT_D.DOCTYPE                      = 'DP'         
		AND   DM_DOCUMENT_D.DEL_YN                   = 'N'      
		AND   DM_DOCUMENT_D.DCCODE	        =  #{dccode}
		AND   DM_DOCUMENT_D.STORERKEY	    =  #{storerkey}
		AND   DM_DOCUMENT_D.DELIVERYDATE	        =  #{docdt}
		AND   DM_DOCUMENT_D.DOCNO	        =  #{docno}
		AND   DM_DOCUMENT_D.DOCTYPE        =  #{doctype}   
		<!-- 상품 다중선택 -->
		<if test="skuMulti != null and skuMulti != '' ">
			<trim prefix="AND (" suffix=")" prefixOverrides="OR">
				<foreach collection="skuMulti" item="item">
					OR DM_DOCUMENT_D.SKU IN
					<foreach collection="item" item="code" open="(" close=")" separator=",">
						#{code}
		      		</foreach>
		    	</foreach>
		  	</trim>
        </if>
		<if test="serialnoMulti != null and serialnoMulti != ''">
			AND ST_SNINFO.SERIALNO IN
			<foreach collection="serialnoMulti" item="code" open="(" close=")" separator=",">
				#{code}
			</foreach>
		</if>
		<if test="blnoMulti != null and blnoMulti != ''">
			AND ST_SNINFO.CONVSERIALNO IN
			<foreach collection="blnoMulti" item="code" open="(" close=")" separator=",">
				#{code}
			</foreach>
		</if>
		<if test="contractcompany != null and contractcompany != ''">	AND    ST_SNINFO.CONTRACTCUSTKEY	=	#{contractcompany} 	</if>
		ORDER BY DM_DOCUMENT_D.DOCLINE
			,DM_DOCUMENT_D.SKU     
    </select>
    
    <select id="getDataExcelList" resultType="DpInplanSTOExcelResDto">		
	   SELECT /* [DpInplanSTOService.sqlx][getDataExcelList][광역입고현황 엑셀 조회][공두경][2025.06.19] */
			  NVL(CD1.BASEDESCR,CD1.BASECODE)              														AS ORDERTYPE_NAME	/*구매유형*/ 
			, DP_INPLAN.SLIPDT																                    AS SLIPDT      		/*광역입고일자*/
			, TO_DM_DOCUMENT_H.DOCNO                                                                            AS DOCNO			/*광역주문번호*/
			, FROM_DM_DOCUMENT_H.DCCODE                                                                         AS FROM_DCCODE		/*물류센터*/
			, FROM_DC.DCNAME                                                                                    AS FROM_DCNAME		/*물류센터명*/
			, FROM_DM_DOCUMENT_H.FROM_CUSTKEY																	AS FROM_CUSTKEY		/*창고*/
			, DCXORGANIZE1.DESCRIPTION 																			AS FROM_CUSTNAME	/*창고명*/
			, TO_DM_DOCUMENT_H.DCCODE                                                                           AS TO_DCCODE		/*물류센터*/
			, TO_DC.DCNAME                                                                                      AS TO_DCNAME		/*물류센터명*/
			, TO_DM_DOCUMENT_H.TO_CUSTKEY																		AS TO_CUSTKEY		/*창고*/
			, DCXORGANIZE2.DESCRIPTION 																			AS TO_CUSTNAME		/*창고명*/
			, DM_DOCUMENT_D.SKU         																		AS SKU				/*상품코드*/
			, MS_SKU.DESCRIPTION       																			AS SKUNAME			/*상품명칭*/
			, '['||DM_DOCUMENT_D.PLANT||']'||DECODE(TRIM(NVL(PLANT1.DESCRIPTION,'')),'',PLANT1.PLANT,TRIM(NVL(PLANT1.DESCRIPTION,''))) AS PLANT_DESCR 	/*플랜트*/
			, NVL(CD2.BASEDESCR,CD2.BASECODE)              														AS CHANNELNAME   	/*저장유무*/
			, NVL(CD3.BASEDESCR,CD3.BASECODE)              														AS STORAGETYPENAME 	/*저장조건*/     
			, MS_SKU.QTYPERBOX    																				AS QTYPERBOX		/*박스입수*/
			, DM_DOCUMENT_D.STORERUOM             										    					AS UOM				/*구매단위*/
			, '0'         																						AS AVGWEIGHT        /*평균중량*/
			, '0'         																						AS CALORDERBOX      /*환산주문박스*/		
			, '0'         																						AS CALCONFIRMBOX    /*환산확정박스*/
			, '0'         																						AS REALBOX          /*실박스*/
			, NVL((DP_INPLAN.ORDERQTY + DP_INPLAN.CANCELQTY) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0)		AS ORDERQTY			/*주문수량*/
			, NVL((DM_DOCUMENT_D_WD.INSPECTQTY ) * DM_DOCUMENT_D_WD.BUNJA / DM_DOCUMENT_D_WD.BUNMO,0)			AS INSPECTQTY_WD    /*검수량출고*/                    
			, NVL((DP_INPLAN.INSPECTQTY ) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0)						AS INSPECTQTY		/*검수량입고*/
			, NVL((DM_DOCUMENT_D_WD.CONFIRMQTY ) * DM_DOCUMENT_D_WD.BUNJA / DM_DOCUMENT_D_WD.BUNMO,0)			AS CONFIRMQTY_WD	/*확정수량출고*/                        
			, NVL((DP_INPLAN.CONFIRMQTY) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0)							AS CONFIRMQTY		/*확정수량입고*/
			, NVL((NVL((DM_DOCUMENT_D_WD.CONFIRMQTY * UOM13.BUNJA / UOM13.BUNMO),0) * UOM14.BUNMO / UOM14.BUNJA),0) AS CONFIRMWEIGHT_WD 	/*충량출고*/	           
			, CASE WHEN DP_INPLAN.STORERKEY = 'CJFW' 
				   THEN (
							CASE WHEN DM_DOCUMENT_D.STORERUOM = 'KG' 
								 THEN NVL((DP_INPLAN.CONFIRMQTY) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0)
								 ELSE MS_SKU.NETWEIGHT * NVL((DP_INPLAN.CONFIRMQTY) * DM_DOCUMENT_D.BUNJA / DM_DOCUMENT_D.BUNMO,0)
							END      																		                		                    
				   )	
				   ELSE NVL((NVL((DP_INPLAN.CONFIRMQTY * UOM11.BUNJA / UOM11.BUNMO),0) * UOM12.BUNMO / UOM12.BUNJA),0)
				END                                                                                             AS CONFIRMWEIGHT	/*중량입고*/
			, NVL(CD4.BASEDESCR,CD4.BASECODE)              														AS STATUSNAME 		/*진행상태*/
			, USER1.USER_NM																						AS ADDWHO			/*생성인*/
			, DP_INPLAN.ADDDATE                                                                                 AS ADDDATE			/*등록일자*/
			, USER2.USER_NM																						AS EDITWHO			/*최종변경자*/
			, DP_INPLAN.EDITDATE                                                                                AS EDITDATE			/*최종변경시간*/
			, FROM_DM_DOCUMENT_H.ORGANIZE                                                                       AS FROM_ORGANIZE	/**/
			, TO_DM_DOCUMENT_H.ORGANIZE                                                                         AS TO_ORGANIZE		/**/
			, TO_DM_DOCUMENT_H.DOCDT                                                                            AS DOCDT  			/**/
			, TO_DM_DOCUMENT_H.ORDERTYPE                                                                        AS ORDERTYPE		/**/
			, DM_DOCUMENT_D.STATUS                                                                              AS STATUS			/**/
			, TO_DM_DOCUMENT_H.STORERKEY                                                                        AS STORERKEY  		/**/
			, TO_DM_DOCUMENT_H.DOCTYPE																			AS DOCTYPE  		/**/
			, DM_DOCUMENT_D.DOCLINE         																	AS DOCLINE			/**/
			, DM_DOCUMENT_D.CHANNEL     																		AS CHANNEL			/**/
			, MS_SKU.STORAGETYPE										                    					AS STORAGETYPE		/**/
			, DM_DOCUMENT_D.STATUS 																				AS STATUS			/**/	
			, DM_DOCUMENT_D.PLANT																				AS PLANT			/**/
		FROM DM_DOCUMENT_H TO_DM_DOCUMENT_H /* 공급받는센터 */
		JOIN DM_DOCUMENT_H FROM_DM_DOCUMENT_H /* 공급센터 */   
		ON   FROM_DM_DOCUMENT_H.DOCTYPE 		  = 'WD'
		AND  FROM_DM_DOCUMENT_H.DELIVERYDATE   		  = TO_DM_DOCUMENT_H.DELIVERYDATE
		AND  FROM_DM_DOCUMENT_H.DOCNO   		  = TO_DM_DOCUMENT_H.DOCNO  
		AND  FROM_DM_DOCUMENT_H.STORERKEY       = TO_DM_DOCUMENT_H.STORERKEY  		
		JOIN DM_DOCUMENT_D         
		ON   DM_DOCUMENT_D.DCCODE = TO_DM_DOCUMENT_H.DCCODE
		AND DM_DOCUMENT_D.DOCTYPE = TO_DM_DOCUMENT_H.DOCTYPE
		AND DM_DOCUMENT_D.DELIVERYDATE = TO_DM_DOCUMENT_H.DELIVERYDATE
		AND DM_DOCUMENT_D.DOCNO = TO_DM_DOCUMENT_H.DOCNO
		<!-- 상품 다중선택 -->
		<if test="skuMulti != null and skuMulti != '' ">
			<trim prefix="AND (" suffix=")" prefixOverrides="OR">
				<foreach collection="skuMulti" item="item">
					OR DM_DOCUMENT_D.SKU IN
					<foreach collection="item" item="code" open="(" close=")" separator=",">
						#{code}
		      		</foreach>
		    	</foreach>
		  	</trim>
        </if>
		<if test="status != null and status != ''">			AND DM_DOCUMENT_D.STATUS	=	#{status} 						</if>
		JOIN DM_DOCUMENT_D DM_DOCUMENT_D_WD
		ON   DM_DOCUMENT_D_WD.DOCNO      		= DM_DOCUMENT_D.DOCNO    
		AND  DM_DOCUMENT_D_WD.DOCLINE    		= DM_DOCUMENT_D.DOCLINE  
		AND  DM_DOCUMENT_D_WD.DOCTYPE    		= 'WD'    
		AND  DM_DOCUMENT_D_WD.WORKPROCESSCODE = 'STO'  
		JOIN CM_USER_AUTHORITY         
		ON   CM_USER_AUTHORITY.USERID         =  #{gUserId}       
		AND  CM_USER_AUTHORITY.DCCODE         = DM_DOCUMENT_D.DCCODE             
		AND  CM_USER_AUTHORITY.STORERKEY      = DM_DOCUMENT_D.STORERKEY          
		AND  CM_USER_AUTHORITY.ORGANIZE       = DM_DOCUMENT_D.ORGANIZE           
		AND  CM_USER_AUTHORITY.AREA           = DM_DOCUMENT_D.AREA   
		<if test="toDccode != null and toDccode != ''">		AND CM_USER_AUTHORITY.DCCODE	=  #{toDccode}		</if>    
		<if test="gStorerkey != null and gStorerkey != ''">		AND CM_USER_AUTHORITY.STORERKEY	=  #{gStorerkey}		</if>    
		<if test="gArea != null and gArea != ''">			AND CM_USER_AUTHORITY.AREA	    =  #{gArea}			</if>    
		JOIN DP_INPLAN
		ON   DP_INPLAN.DCCODE = DM_DOCUMENT_D.DCCODE
		AND DP_INPLAN.DOCTYPE = DM_DOCUMENT_D.DOCTYPE
		AND DP_INPLAN.SLIPDT = DM_DOCUMENT_D.DELIVERYDATE
		AND DP_INPLAN.DOCNO = DM_DOCUMENT_D.DOCNO
		AND DP_INPLAN.DOCLINE = DM_DOCUMENT_D.DOCLINE
		AND  DP_INPLAN.DEL_YN         		=  'N' 	
		<if test="fromSlipdt != null and fromSlipdt != ''">	AND DP_INPLAN.SLIPDT <![CDATA[>=]]> #{fromSlipdt}		</if>
		<if test="toSlipdt != null and toSlipdt != ''">		AND DP_INPLAN.SLIPDT <![CDATA[<=]]> #{toSlipdt}		</if>
		JOIN MS_SKU
		ON    MS_SKU.STORERKEY                 = DM_DOCUMENT_D.STORERKEY
		AND   MS_SKU.SKU                       = DM_DOCUMENT_D.SKU   
		AND   MS_SKU.DEL_YN                    = 'N'
		<if test="storagetype != null and storagetype != ''"> AND MS_SKU.STORAGETYPE = #{storagetype}			</if>
		JOIN CM_DC    FROM_DC
		ON    FROM_DC.DCCODE = FROM_DM_DOCUMENT_H.DCCODE
		AND   FROM_DC.DEL_YN = 'N'
		JOIN CM_DC    TO_DC
		ON    TO_DC.DCCODE = TO_DM_DOCUMENT_H.DCCODE  
		AND   TO_DC.DEL_YN = 'N'                            
		LEFT JOIN CM_CODE_STORER CD1  ON CD1.STORERKEY  = TO_DM_DOCUMENT_H.STORERKEY AND CD1.CODELIST  = 'ORDERTYPE_STO' 	AND CD1.BASECODE   = TO_DM_DOCUMENT_H.ORDERTYPE
        LEFT JOIN CM_CODE_STORER CD2  ON CD2.STORERKEY  = DM_DOCUMENT_D.STORERKEY 	 AND CD2.CODELIST  = 'PUTAWAYTYPE' 		AND CD2.BASECODE   = DM_DOCUMENT_D.CHANNEL
        LEFT JOIN CM_CODE_STORER CD3  ON CD3.STORERKEY  = MS_SKU.STORERKEY 			 AND CD3.CODELIST  = 'STORAGETYPE' 		AND CD3.BASECODE   = MS_SKU.STORAGETYPE
        LEFT JOIN CM_CODE_STORER CD4  ON CD4.STORERKEY  = DM_DOCUMENT_D.STORERKEY 	 AND CD4.CODELIST  = 'STATUS_DP' 		AND CD4.BASECODE   = DM_DOCUMENT_D.STATUS
        LEFT JOIN MS_PLANT PLANT1 	  ON PLANT1.PLANT = DM_DOCUMENT_D.PLANT
		LEFT JOIN MS_UOM UOM11  	  ON UOM11.STORERKEY = DP_INPLAN.STORERKEY AND UOM11.SKU  = DP_INPLAN.SKU AND UOM11.UOM = DP_INPLAN.UOM
        LEFT JOIN MS_UOM UOM12	  	  ON UOM12.STORERKEY = DP_INPLAN.STORERKEY AND UOM12.SKU  = DP_INPLAN.SKU AND UOM12.UOM = 'KG'
		LEFT JOIN MS_UOM UOM13  	  ON UOM13.STORERKEY = DM_DOCUMENT_D_WD.STORERKEY AND UOM13.SKU  = DM_DOCUMENT_D_WD.SKU AND UOM13.UOM = DM_DOCUMENT_D_WD.UOM
        LEFT JOIN MS_UOM UOM14	  	  ON UOM14.STORERKEY = DM_DOCUMENT_D_WD.STORERKEY AND UOM14.SKU  = DM_DOCUMENT_D_WD.SKU AND UOM14.UOM = 'KG'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
		LEFT JOIN CM_DCXORGANIZE DCXORGANIZE1 ON DCXORGANIZE1.DCCODE = FROM_DM_DOCUMENT_H.DCCODE AND DCXORGANIZE1.ORGANIZE = FROM_DM_DOCUMENT_H.FROM_CUSTKEY
		LEFT JOIN CM_DCXORGANIZE DCXORGANIZE2 ON DCXORGANIZE2.DCCODE = TO_DM_DOCUMENT_H.DCCODE   AND DCXORGANIZE2.ORGANIZE = TO_DM_DOCUMENT_H.FROM_CUSTKEY
		LEFT JOIN FRAMEONE_USER USER1 ON USER1.USER_ID = DP_INPLAN.ADDWHO OR USER1.USER_NO = DP_INPLAN.ADDWHO
		LEFT JOIN FRAMEONE_USER USER2 ON USER2.USER_ID = DP_INPLAN.EDITWHO OR USER2.USER_NO = DP_INPLAN.EDITWHO
		WHERE TO_DM_DOCUMENT_H.DOCTYPE                 = 'DP'         
		AND   TO_DM_DOCUMENT_H.DEL_YN                  = 'N'     
		<if test="fromDocdt != null and fromDocdt != ''">	AND DM_DOCUMENT_D.DELIVERYDATE    <![CDATA[>=]]> #{fromDocdt}			</if>
		<if test="toDocdt != null and toDocdt != ''">		AND DM_DOCUMENT_D.DELIVERYDATE    <![CDATA[<=]]> #{toDocdt}			</if>
		<!-- 문서번호 다중선택 -->
		<if test="docnoMulti != null and docnoMulti != ''">
			AND TO_DM_DOCUMENT_H.DOCNO IN
			<foreach collection="docnoMulti" item="code" open="(" close=")" separator=",">
				#{code}
			</foreach>
		</if>
		<if test="tocustkey != null and tocustkey != ''">		AND TO_DM_DOCUMENT_H.TO_CUSTKEY   = #{tocustkey} 	</if>
		<if test="fromcustkey != null and fromcustkey != ''">	AND TO_DM_DOCUMENT_H.FROM_CUSTKEY = #{fromcustkey} 	</if>
		<!-- 배송그룹 공통조회 조건 -->
		<if test="gMultiCourier != null and gMultiCourier != ''">	AND DM_DOCUMENT_H.COURIER = #{gMultiCourier}	</if>
		<if test="serialCheck != null and serialCheck != ''">		
			AND    EXISTS (
						SELECT 'A'
						FROM ST_SNINFO
						JOIN DP_INVOICE_SN
							ON DP_INVOICE_SN.STORERKEY             = ST_SNINFO.STORERKEY
						AND DP_INVOICE_SN.SKU                   = ST_SNINFO.SKU
						AND DP_INVOICE_SN.SERIALNO              = ST_SNINFO.SERIALNO
						AND DP_INVOICE_SN.STOCKID               = ST_SNINFO.STOCKID
						AND DP_INVOICE_SN.DEL_YN                = 'N'
						WHERE DP_INVOICE_SN.DCCODE                = DP_INPLAN.DCCODE                   
						AND DP_INVOICE_SN.STORERKEY             = DP_INPLAN.STORERKEY        
						AND DP_INVOICE_SN.SLIPNO                = DP_INPLAN.SLIPNO                              
						AND DP_INVOICE_SN.SLIPDT                = DP_INPLAN.SLIPDT                   
						AND DP_INVOICE_SN.SLIPLINE              = DP_INPLAN.SLIPLINE
						AND DP_INVOICE_SN.DOCTYPE               = DP_INPLAN.DOCTYPE
						AND DP_INVOICE_SN.SKU                   = DP_INPLAN.SKU    
						AND DP_INVOICE_SN.DEL_YN                = 'N'
				<if test="serialnoMulti != null and serialnoMulti != ''">
					AND ST_SNINFO.SERIALNO IN
					<foreach collection="serialnoMulti" item="code" open="(" close=")" separator=",">
						#{code}
					</foreach>
				</if>
				<if test="blnoMulti != null and blnoMulti != ''">
					AND ST_SNINFO.CONVSERIALNO IN
					<foreach collection="blnoMulti" item="code" open="(" close=")" separator=",">
						#{code}
					</foreach>
				</if>
		    	<if test="contractcompany != null and contractcompany != ''">	AND    ST_SNINFO.CONTRACTCUSTKEY	=	#{contractcompany} 	</if>
							)
		</if>        
		ORDER BY
			DP_INPLAN.SLIPDT
			,TO_DM_DOCUMENT_H.ORDERTYPE
			,TO_DM_DOCUMENT_H.DOCNO  
    </select>
    
</mapper>