<?xml version="1.0" encoding="UTF-8"?><!--Converted at: Mon Feb 17 11:21:55 KST 2014-->
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN"
"http://mybatis.org/dtd/mybatis-3-mapper.dtd">
<mapper namespace="sampleChartService">

	<!-- 시스템 예외 이력 년도별 건수 조회 -->
	<select id="getSystemExceptionCount" resultType="SampleChartGetResDto">
	    <![CDATA[
		SELECT    YM
       			, NVL(CNT,0) AS CNT
		  FROM (
					SELECT TO_CHAR (ADD_MONTHS (TO_DATE (#{fromDt}, 'YYYY-MM-DD'), LEVEL - 1),'YYYY-MM') YM
                    FROM DUAL
                    CONNECT BY ADD_MONTHS (TO_DATE (#{fromDt}, 'YYYY-MM-DD'), LEVEL-1) <=TO_DATE (#{thruDt}, 'YYYY-MM-DD')
			    ) A
		LEFT OUTER JOIN
		(
					SELECT   OCCR_YM
					       , COUNT(*) AS CNT
		  			  FROM
					(
						  SELECT substr(OCCR_DY,0,7) AS OCCR_YM
						    FROM TB_CF_EXN_LOG
					)
				    GROUP BY OCCR_YM
		) B 
		ON A.YM = OCCR_YM
		ORDER BY A.YM
		]]>
	</select>
</mapper>