package cjfw.batch.scm0160.soap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.2
 * Generated source version: 4.0.2
 *
 */
@WebService(targetNamespace = "urn://scm.cjfreshway.co.kr/MM", name = "SI_SCM0160_SCM_SO")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SISCM0160SCMSO {

    @WebMethod(operationName = "SI_SCM0160_SCM_SO", action = "http://sap.com/xi/WebService/soap1.1")
    @WebResult(name = "MT_SCM0160_SCM_response", targetNamespace = "urn://scm.cjfreshway.co.kr/MM", partName = "MT_SCM0160_SCM_response")
    public DTSCM0160SCMResponse siSCM0160SCMSO(

        @WebParam(partName = "MT_SCM0160_SCM", name = "MT_SCM0160_SCM", targetNamespace = "urn://scm.cjfreshway.co.kr/MM")
        DTSCM0160SCM mtSCM0160SCM
    );
}
