server:
  port: 8081
spring:
  profiles:
    active: local
  config:
    import:
      - classpath:/config/cf-config.yml
      - classpath:/config/batch-config.yml
      - classpath:/config/auth-config.yml
  batch:
    job:
      enabled: false
  datasource-oracle:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.73.197.41:1531/FWWMSDBD.cj.net
    username: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
    password: ENC(VfW2zCbD7leUYCVEunPh2nppaLV0+v27)
    hikari:
      pool-name: hikaricp-batch
      maximum-pool-size: 30
      minimum-idle: 30
      connection-timeout: 10000       # 10초
      validation-timeout: 5000        # 5초
      max-lifetime: 1800000           # 30분
      idle-timeout: 300000            # 5분
      keepalive-time: 120000          # 2분
      leak-detection-threshold: 60000 # 60초
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  quartz:
    #startup-delay: 10
    job-store-type: jdbc
    jdbc:
      initialize-schema: never  # 이미 수동으로 테이블 생성했기 때문에
    properties:
      org:
        quartz:
          scheduler:
            instanceId: auto
            instanceName: wmsbatch_QA
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 60000   # 인스턴스가 DB에 상태 체크인하는 주기(ms)
            misfireThreshold: 60000
            useProperties: false
            dataSource: myDS
          dataSource:
            myDS:
              driver: oracle.jdbc.OracleDriver
              URL: jdbc:oracle:thin:@//10.73.197.41:1531/FWWMSDBD.cj.net
              user: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
              password: ENC(VfW2zCbD7leUYCVEunPh2nppaLV0+v27)
          auto-startup: true

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/oracle/**/*.sqlx  #oracle
  executorType: SIMPLE



---

spring:
  config:
    activate:
      on-profile: local


---

spring:
  config:
    activate:
      on-profile: dev

  datasource-oracle:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.73.197.41:1531/FWWMSDBD.cj.net
    username: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
    password: ENC(VfW2zCbD7leUYCVEunPh2nppaLV0+v27)
    hikari:
      pool-name: hikaricp-batch
      maximum-pool-size: 30
      minimum-idle: 30
      connection-timeout: 10000       # 10초
      validation-timeout: 5000        # 5초
      max-lifetime: 1800000           # 30분
      idle-timeout: 300000            # 5분
      keepalive-time: 120000          # 2분
      leak-detection-threshold: 60000 # 60초
  quartz:
    #startup-delay: 10
    job-store-type: jdbc
    jdbc:
      initialize-schema: never  # 이미 수동으로 테이블 생성했기 때문에
    properties:
      org:
        quartz:
          scheduler:
            instanceId: auto
            instanceName: wmsbatch_DEV
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 60000   # 인스턴스가 DB에 상태 체크인하는 주기(ms)
            misfireThreshold: 60000
            useProperties: false
            dataSource: myDS
          dataSource:
            myDS:
              driver: oracle.jdbc.OracleDriver
              URL: jdbc:oracle:thin:@//10.73.197.41:1531/FWWMSDBD.cj.net
              user: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
              password: ENC(VfW2zCbD7leUYCVEunPh2nppaLV0+v27)
          auto-startup: true




---

spring:
  config:
    activate:
      on-profile: qa

  datasource-oracle:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//10.73.197.41:1541/FWWMSDBQ.cj.net
    username: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
    password: ENC(8z/0HjWxtjhC0fQ3XqYNb664cZ5rfpiI)

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: auto
            instanceName: wmsbatch_QA
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 20000
            misfireThreshold: 60000
            useProperties: false
            dataSource: myDS
          dataSource:
            myDS:
              driver: oracle.jdbc.OracleDriver
              URL: jdbc:oracle:thin:@//10.73.197.41:1541/FWWMSDBQ.cj.net
              user: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
              password: ENC(8z/0HjWxtjhC0fQ3XqYNb664cZ5rfpiI)



---

spring:
  config:
    activate:
      on-profile: prd

  datasource-oracle:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=ON)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=10.73.151.111)(PORT=1591))(ADDRESS=(PROTOCOL=TCP)(HOST=10.73.151.113)(PORT=1591)))(CONNECT_DATA=(SERVICE_NAME=FWWMSDBP.cj.net)))
    username: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
    password: ENC(iOgNulfg0LPnM/8UXwa+LCYrAoZzY4wp)

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceId: auto
            instanceName: wmsbatch_PRD
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
            threadPriority: 5
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 20000
            misfireThreshold: 60000
            useProperties: false
            dataSource: myDS
          dataSource:
            myDS:
              driver: oracle.jdbc.OracleDriver
              URL: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=ON)(FAILOVER=ON)(ADDRESS=(PROTOCOL=TCP)(HOST=10.73.151.111)(PORT=1591))(ADDRESS=(PROTOCOL=TCP)(HOST=10.73.151.113)(PORT=1591)))(CONNECT_DATA=(SERVICE_NAME=FWWMSDBP.cj.net)))
              user: ENC(sB3uW+EvWloX2xJZiaMQKwKduLpmheQ5)
              password: ENC(iOgNulfg0LPnM/8UXwa+LCYrAoZzY4wp)
