######### Canal Frame config ###########
cf:
  defaultLang: ko_KR
  maxResultRows: 30000
  accessIpRange: 52.0.0.0~52.255.255.250,52.255.255.251~52.255.255.255,10.0.0.0~10.255.255.255,127.0.0.1~127.0.0.2
  static:
    basePath: http://localhost:${server.port}
  drm:
    dsdcode: "0000000000002519"
    enable: true
    fsdinitPath: C:/cf-workspace/fsdinit
  file:
    uploadPath: C:/cf-workspace/upload
    dirPermission: 755
    largeDataTempFilePath: C:/cf-workspace/largedatatemp
    polygonDataPath: C:/app/uploads/dwaylo/polygon/
    cpt: #biz Type
      extentionLimit: ppt|doc|xls|pptx|xlsx|docx|txt|jpg|gif|bmp|jpeg|pdf|tif|png
      sizeLimit: 1000000000
  excel:
    uploadPath: C:/cf-workspace/upload/excel
  email:
    debug: true
    host: 116.121.26.123
    id: ictdev@cj.net
    logPath: C:/cf-workspace/logs/email-log
    logType: DB  #or FILE
    port: 25
    pw: ''
    sender: tester
    senderAddr: ictdev@cj.net
  auth:
    pattern: '/comfuncTmp/**, /sysmgtTmp/**'
  ### BackEnd 간 API 호출용 JWT 설정###
  apiJwt:
    algorithm: 'HS256'
    expirTime: 5000
    headerKey: 'Api-CF-Token'
    secretKey: 'cfbackendapikey20220114'
  sso:
    redirectUrl: 'http://vue.canalframe.cj.net'
    secretKey: 90fd33a9fbb56cd1
  api:
    crm:
      url: https://gwmsqa.ifresh.co.kr/gwms/crm/rest/LIF1017/WM001/
      interfaceId: IFN_LIF1017_WM001_
      interfaceAuthKey: sclwEZRE/XQnc4kwlK3HUV9nBMAws0I8r1d8IWAsJUE=
    cs:
      url: https://safsqa2.ifresh.co.kr/com/wms/ifReceive/
    srm:
      url: https://nsrmqa.ifresh.co.kr/restful/
      username: if_restful
      password: emro1004!
  soap-api:
    userId: SCM_IFQUSER
    password: IFQUSER2@15#@
    url: fwpiqas.cjfreshway.co.kr
    mode: SCM_QAS
    smsMode: EAI_QAS
    iamUrl: https://ssoqa.ifresh.co.kr:9800/ssoserver/services/SSO_NON_SAP_EAI.SSO_NON_SAP_EAIHttpSoap11Endpoint/
    iamOpMode: staging
    useHttps: false
    scmIfaceNamespace: urn://scm.cjfreshway.co.kr
    shrIfaceNamespace: urn://shr.cjfreshway.co.kr

  kma:
    base-url: https://apis.data.go.kr
    base-path: /1360000/VilageFcstInfoService_2.0/getVilageFcst
    service-key: ${KMA_SERVICE_KEY:default_key_for_QA}
    min-interval-ms: 250          # 200~300 권장
    max-retries: 3
    backoff-initial-ms: 1000
    backoff-max-ms: 8000


  opinet:
    url: https://www.opinet.co.kr/api/avgAllPrice.do
    key: F260121083

  tmap:
    api:
      key: l7xx78a123696af740b8a2b4c8c8fa8c6e86
      url: https://apis.openapi.sk.com

  naver:
    api:
      id: pzz52pipm2
      key: sXxjz7QxVtUBH7GPDXenCpwU5i9WmQDOains5oBM
      urlMapGc: https://maps.apigw.ntruss.com/map-geocode/v2/geocode   ###위도(Y),경도(X)
      urlMapRGc: https://maps.apigw.ntruss.com/map-reversegeocode/v2/gc ###행정동코드

  juso:
    appKey: U01TX0FVVEgyMDI1MDYyMDE2NTIyNjExNTg2NDM=
    filePath: C:/CJFW_WMS/uploads/dwaylo/juso

  sap:
    client: 100
    userId: RFC_COM1
    password: cktpeo79!
    language: KO
    poolCapaciry: 10
    poolPeakLimit: 50
    host: 10.85.38.97
    hostType: ashost
    systemNumber: 10
    group: PUBLIC
    r3name: FWP
    msserv: ""

---

spring:
  config:
    activate:
      on-profile: dev

cf:
  file:
    uploadPath: /app/svcroot/runtime/webapps/cf-apiserver/upload
    largeDataTempFilePath: /app/svcroot/runtime/webapps/cf-apiserver/largedatatemp
    polygonDataPath: /app/uploads/dwaylo/polygon/
  excel:
    uploadPath: /app/svcroot/runtime/webapps/cf-apiserver/upload/excel
  static:
    basePath: http://dev.ictdev.cj.net # https://dev.ictdev.cj.net
  drm:
    dsdcode: "0000000000002519"
    enable: true
    fsdinitPath: /app/drm/fsdinit
  email:
    logPath: /app/logs/applog/email-log
  api:
    crm:
      url: https://gwmsqa.ifresh.co.kr/gwms/crm/rest/LIF1017/WM001/
      interfaceId: IFN_LIF1017_WM001_
      interfaceAuthKey: sclwEZRE/XQnc4kwlK3HUV9nBMAws0I8r1d8IWAsJUE=
    cs:
      url: https://safsqa2.ifresh.co.kr/com/wms/ifReceive/
    srm:
      url: https://nsrmqa.ifresh.co.kr/restful/
      username: if_restful
      password: emro1004!

  soap-api:
    userId: SCM_IFQUSER
    password: IFQUSER2@15#@
    url: fwpiqas.cjfreshway.co.kr
    mode: SCM_QAS
    smsMode: EAI_QAS
    iamUrl: https://ssoqa.ifresh.co.kr:9800/ssoserver/services/SSO_NON_SAP_EAI.SSO_NON_SAP_EAIHttpSoap11Endpoint/
    iamOpMode: staging
    useHttps: false
    scmIfaceNamespace: urn://scm.cjfreshway.co.kr
    shrIfaceNamespace: urn://shr.cjfreshway.co.kr

  kma:
    base-url: https://apis.data.go.kr
    base-path: /1360000/VilageFcstInfoService_2.0/getVilageFcst
    service-key: xczws4qQ4beavJRCX0ygejB5jU%2FFCSttO65Ws7BBrHJLbLBWqUILqLxOu%2BM2eZ7V1Zc%2FPWqv%2FL3txpNUYxOQsQ%3D%3D  # 기상청 운영계정
    min-interval-ms: 250          # 200~300 권장
    max-retries: 3
    backoff-initial-ms: 1000
    backoff-max-ms: 8000

  opinet:
    url: https://www.opinet.co.kr/api/avgAllPrice.do
    key: F260121083

  tmap:
    api:
      key: l7xx78a123696af740b8a2b4c8c8fa8c6e86
      url: https://apis.openapi.sk.com

  naver:
    api:
      id: pzz52pipm2
      key: sXxjz7QxVtUBH7GPDXenCpwU5i9WmQDOains5oBM
      urlMapGc: https://maps.apigw.ntruss.com/map-geocode/v2/geocode   ###위도(Y),경도(X)
      urlMapRGc: https://maps.apigw.ntruss.com/map-reversegeocode/v2/gc ###행정동코드

  juso:
    appKey: U01TX0FVVEgyMDI1MDYyMDE2NTIyNjExNTg2NDM=
    filePath: /app/uploads/dwaylo/juso

  # 카카오알림톡.APIKEY
  kakao:
    appkey: e703ed8559c51491710fe0794029c2c56ca2af2b
---

spring:
  config:
    activate:
      on-profile: qa

cf:
  file:
    uploadPath: /app/svcroot/runtime/webapps/cf-apiserver/upload
    largeDataTempFilePath: /app/svcroot/runtime/webapps/cf-apiserver/largedatatemp
    polygonDataPath: /app/uploads/qwaylo/polygon/
  excel:
    uploadPath: /app/svcroot/runtime/webapps/cf-apiserver/upload/excel
  static:
    basePath: http://dev.ictdev.cj.net # https://dev.ictdev.cj.net
  drm:
    dsdcode: "0000000000002519"
    enable: true
    fsdinitPath: /app/drm/fsdinit
  email:
    logPath: /app/logs/applog/email-log
  api:
    crm:
      url: https://gwmsqa.ifresh.co.kr/gwms/crm/rest/LIF1017/WM001/
      interfaceId: IFN_LIF1017_WM001_
      interfaceAuthKey: sclwEZRE/XQnc4kwlK3HUV9nBMAws0I8r1d8IWAsJUE=
    cs:
      url: https://safsqa2.ifresh.co.kr/com/wms/ifReceive/
    srm:
      url: https://nsrmqa.ifresh.co.kr/restful/
      username: if_restful
      password: emro1004!

  soap-api:
    userId: SCM_IFQUSER
    password: IFQUSER2@15#@
    url: fwpiqas.cjfreshway.co.kr
    mode: SCM_QAS
    smsMode: EAI_QAS
    iamUrl: https://ssoqa.ifresh.co.kr:9800/ssoserver/services/SSO_NON_SAP_EAI.SSO_NON_SAP_EAIHttpSoap11Endpoint/
    iamOpMode: staging
    useHttps: false
    scmIfaceNamespace: urn://scm.cjfreshway.co.kr
    shrIfaceNamespace: urn://shr.cjfreshway.co.kr

  kma:
    base-url: https://apis.data.go.kr
    base-path: /1360000/VilageFcstInfoService_2.0/getVilageFcst
    service-key: xczws4qQ4beavJRCX0ygejB5jU%2FFCSttO65Ws7BBrHJLbLBWqUILqLxOu%2BM2eZ7V1Zc%2FPWqv%2FL3txpNUYxOQsQ%3D%3D  # 기상청 운영계정
    min-interval-ms: 250          # 200~300 권장
    max-retries: 3
    backoff-initial-ms: 1000
    backoff-max-ms: 8000

  opinet:
    url: https://www.opinet.co.kr/api/avgAllPrice.do
    key: F260121083

  tmap:
    api:
      key: l7xx78a123696af740b8a2b4c8c8fa8c6e86
      url: https://apis.openapi.sk.com

  naver:
    api:
      id: pzz52pipm2
      key: sXxjz7QxVtUBH7GPDXenCpwU5i9WmQDOains5oBM
      urlMapGc: https://maps.apigw.ntruss.com/map-geocode/v2/geocode   ###위도(Y),경도(X)
      urlMapRGc: https://maps.apigw.ntruss.com/map-reversegeocode/v2/gc ###행정동코드

  juso:
    appKey: U01TX0FVVEgyMDI1MDYyMDE2NTIyNjExNTg2NDM=
    filePath: /app/uploads/dwaylo/juso

  # 카카오알림톡.APIKEY
  kakao:
    appkey: e703ed8559c51491710fe0794029c2c56ca2af2b
---

spring:
  config:
    activate:
      on-profile: prd

cf:
  file:
    uploadPath: /app/svcroot/runtime/webapps/cf-apiserver/upload
    largeDataTempFilePath: /app/svcroot/runtime/webapps/cf-apiserver/largedatatemp
    polygonDataPath: /app/uploads/pwaylo/polygon/
  excel:
    uploadPath: /app/svcroot/runtime/webapps/cf-apiserver/upload/excel
  static:
    basePath: http://dev.ictdev.cj.net # https://dev.ictdev.cj.net
  drm:
    dsdcode: "0000000000002519"
    enable: true
    fsdinitPath: /app/drm/fsdinit
  email:
    logPath: /app/logs/applog/email-log
  api:
    crm:
      url: https://gwmsqa.ifresh.co.kr/gwms/crm/rest/LIF1017/WM001/
      interfaceId: IFN_LIF1017_WM001_
      interfaceAuthKey: sclwEZRE/XQnc4kwlK3HUV9nBMAws0I8r1d8IWAsJUE=
    cs:
      url: https://safsqa2.ifresh.co.kr/com/wms/ifReceive/
    srm:
      url: https://nsrmqa.ifresh.co.kr/restful/
      username: if_restful
      password: emro1004!
  kma:
    base-url: https://apis.data.go.kr
    base-path: /1360000/VilageFcstInfoService_2.0/getVilageFcst
    service-key: xczws4qQ4beavJRCX0ygejB5jU%2FFCSttO65Ws7BBrHJLbLBWqUILqLxOu%2BM2eZ7V1Zc%2FPWqv%2FL3txpNUYxOQsQ%3D%3D  # 기상청 운영계정
    min-interval-ms: 250          # 200~300 권장
    max-retries: 3
    backoff-initial-ms: 1000
    backoff-max-ms: 8000

  opinet:
    url: https://www.opinet.co.kr/api/avgAllPrice.do
    key: F260121083

  tmap:
    api:
      key: l7xx78a123696af740b8a2b4c8c8fa8c6e86
      url: https://apis.openapi.sk.com

  naver:
    api:
      id:  pzz52pipm2
      key: sXxjz7QxVtUBH7GPDXenCpwU5i9WmQDOains5oBM
      urlMapGc:  https://maps.apigw.ntruss.com/map-geocode/v2/geocode   ###위도(Y),경도(X)
      urlMapRGc: https://maps.apigw.ntruss.com/map-reversegeocode/v2/gc ###행정동코드


  juso:
    appKey: U01TX0FVVEgyMDI1MDYyMDE2NTIyNjExNTg2NDM=
    filePath: /app/uploads/dwaylo/juso

  # 카카오알림톡.APIKEY.PRD
  kakao:
    appkey: 344c6c25b2c3eacae088fa7b60f52582b9eb8b72





